### ISSUE TITLE
Search engine support in vomnibar

### ISSUE THREAD

**Issue by ceiron61** [philc/vimium#1009]
Considering that it doesn't look like the Chrome devs are ever going to provide an API for accessing the user search engines, would it be possible to add support for defining our own search engines shortcuts in a Vimium-specific way?

In such a scenario, I could map "w" to the Wikipedia search engine in Viumium and typing "w github" in the Vomnibar would bring me to the Wikipedia page for Github. It doesn't really matter whether "w" is also set as a search engine shortcut for Wikipedia in Chromium/Chrome or not as these will be independent settings.

As an example, you might want to look at Vrome, which seems to have taken this approach: https://github.com/jinzhu/vrome/blob/master/Features.mkd

Thanks,

**Comment by rajeevksahu** [comment]
They have established our company according to the requirement of your energy and effort. As time changes, routine have changed absolutely. This is not a moment when we all can perform according to our convenience. This is plenty of time when we have to do everything promptly. In such hectic schedule it is really difficult to handle moving house and workplaces. We have to seek the services of some helping hands that help us and save us in typical conditions.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
We charge some expenses to you but believe us, you love our alternatives. You do not have to take any stress about moving, because we are there to help you. Mysore packers and movers are known for their well popularity and their perform. We have earned a lot of cash, but what is essential which we achieve is the believe in of our clients.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
If you don’t know what to do while moving and moving, then just leave it on us. You have to contact us and tell us your finish address. We will reach to you, whenever you need us. Trust us once, we will never Expert you. Our perform has made us so trustable. Our client’s believe in and our effort provide us with so excellent status and popularity in the market.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
You may have some bad experiences while moving and moving, but movers and packers in Mysore will definitely earn your believe in. We pick your fill from your position and package it very well. We provide packed content to your new property or workplace. If you requirement for unpacked it, then we also provide such type of alternatives too.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>
