### ISSUE TITLE
Vimium not working for pdf tabs

### ISSUE THREAD

**Issue by ddydng** [philc/vimium#1014]
This is extremely inconvenience when a pdf tab is opened in chrome and you try to navigate between tabs. Navigating stuck on pdf tab.

**Comment by gshrikant** [comment]
I have a similar issue on Vimium 1.5.1. I am able to switch tabs until I hit a tab with PDF open (OS: Windows 7 Enterprise; Chrome Version 43.0.2357.124 m) on Chrome's native PDF viewer.

Navigation gets stuck on the PDF page (see [1] for example) and none of the Vimium shortcuts seem to work even though the icon indicates that Vimium is active. 

[1] http://users.ece.cmu.edu/~omutlu/pub/raidr-dram-refresh_isca12.pdf

**Comment by rajeevksahu** [comment]
If you are going to seek the services of movers and packers in Thane or Bangalore , remember not to select inexperienced movers who allure you by providing very low estimates but later they impose different types of expenses. Very low estimate provided by some company can also indicate inexperience of the movers and packers or it can be a compromise on protection and protective concerns of your expensive content, etc. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
That is why, come to EXPERT Packers and do the choosing of a renowned experts in your area. Movers packers Thane provide excellent moving or moving alternatives for a lesser cost. Right preparations are essential before you seek the services of the Moving Company and start your trip. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
We know that your property can consist of all significant appliances such as refrigerators and televisions and units. We will recommend you to keep all essential documents and valuables such as jewelry and cash with you. Let the experts help you to fill and package all the rest.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
We at EXPERT Packers are expert Home and Office Movers in Thane and Bangalore providing trustable workplace, company, shop or house moving alternatives. Customer care is the most essential factor for us. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>
