### ISSUE TITLE
Key Mapping

### ISSUE THREAD

**Issue by alexherbo2** [philc/vimium#1046]
We could redefine keys meaning using the map command

```
map <scope> <modes> <key> <keys>
```

with `scope` being one of `global`, `tab` or `window`, `modes` being hierarchical, comma separated list `insert`, `normal` or `bar` then optional labels as submodes, `key` being a single key name and `keys` a list of keys.

`map` can also takes some flags:

 * `-docstring`: define the documentation string for the command

Examples

```
map global normal,goto g
map global normal,goto 0 g
```

```
map global normal,leader ,
map global normal,leader K /Chromium<ret>
```

_Note_ the `map` syntax command is inspired by [Kakoune][Kakoune — Key Mapping].

[Kakoune]: https://github.com/mawww/kakoune
[Kakoune — Key Mapping]: https://github.com/mawww/kakoune#key-mapping

**Comment by dragon788** [comment]
I believe the vim way to do this is define the modes ahead of the map command i.e. imap vmap etc. But I completely agree it might be more user friendly to define these after the map command and with better descriptions of when/where they happen.

**Comment by smblott-github** [comment]
Closing.
Lack of interest.
