### ISSUE TITLE
Hook support

### ISSUE THREAD

**Issue by alexherbo2** [philc/vimium#1051]
```
hook <scope> <hook_name> <match_patterns> <commands>
```

`scope` can be either `global`, `tab` or `window`, `match_patterns` is from [Chromium — Match Patterns][], `command` is a string containing the commands to execute when the hook is called.

Examples

What to do when a website wants to open a new window:

```
hook global NewWindow <all_urls> OpenIn(Current|New)(Tab|Window)
```

_Note_ the `hook` syntax command is inspired by [Kakoune][Kakoune — Hooks].

[Chromium — Match Patterns]: https://developer.chrome.com/extensions/match_patterns
[Kakoune]: https://github.com/mawww/kakoune
[Kakoune — Hooks]: https://github.com/mawww/kakoune#hooks

**Comment by smblott-github** [comment]
Closing.
Lack of interest.
