### ISSUE TITLE
Tab and Enter key support for hint mode

### ISSUE THREAD

**Issue by alexherbo2** [philc/vimium#1054]
* `Tab` to cycle though matching links
* `Enter` to open selected link

**Comment by dragon788** [comment]
I really think the current implementation supercedes the need for pressing tab (an "expensive" pinky character) and with the option to match by letter, link name, or number and using Enter to accept the current selection, I'd say I wouldn't change it for the world.

**Comment by smblott-github** [comment]
Closing.
This is implemented now.
