### ISSUE TITLE
ctrl-i in insert mode to open external editor

### ISSUE THREAD

**Issue by alexherbo2** [philc/vimium#1055]

**Comment by dragon788** [comment]
If vim if your external editor of choice you can search the tool vim-anywhere and install it into your startup configuration. Essentially you can map a keystroke to trigger the script, which uses xdotool to grab the text in the input field you are presently in and select all and copy, then open your editor and paste, then when you close the editor it reads the temp file that was created into the clipboard and pastes it again. Worst case scenario you might have to click and paste again if it missed the mark.
