### ISSUE TITLE
Major suggestion: Insert mode mappings.

### ISSUE THREAD

**Issue by freeo** [philc/vimium#1059]
The readme says, that while in insert mode, all mappings are disabled. But often enough I find myself in need for basic vim features for editing an input field. Specifically I'd like to do this, for example:
```
imap <c-0> <home>
imap <c-4> <end>
```
And I could restore my favourite vim-way of getting out of insert mode:
```
imap jk <Esc>                     " SMASH escape
```
We could even reimplement all bindings of vim's command mode (emacs bindings):
```
c-w delete word
c-a home
c-e end
c-b left
c-h backspace
```
and so on...

It would also be the beginning of emulating vim inside an input field. If this is on the roadmap for the distant future, we should think of text-editing mode and input-mode together in advance. 

Yay or nay?

**Comment by dragon788** [comment]
I'm looking forward to this as well. I also use jk for my ESC, though with remapping CapsLock as Esc I have less use for it, I'm sure I'll still keep mashing jk to try and exit insert mode.

Fun fact, the reason I didn't use ii (invert insert?) was I could think of a word that has that sequence, Hawaii, whereas I couldn't come up with one that has jk, and if I were abbreviating joking I'd do it as j/k not jk. I did a search of the English dictionary for "jk" as a sequence, and only one 6 or 7 letter word came up, so I think its safe to say I'll never have to change that mapping.
