### ISSUE TITLE
Vimium does not work on Gmail

### ISSUE THREAD

**Issue by int3** [philc/vimium#107]
I'm not sure if this issue has been posted already, but I couldn't find anything on it so here it is. I don't have Gmail shortcuts enabled so I'm not sure what's the problem... maybe the iframes?

**Comment by laike9m** [comment]
It surely works.

**Comment by rrsahu** [comment]
Here, we will tell you about well-known packers & movers in Bangalore who helps experts and other individuals in moving and shifting house or their workplaces. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by rrsahu** [comment]
The main objective of starting up this article is to cover main information about Packers movers Bangalore like how much they are effective for you, how they can help you, the price for product packaging and movers in Bangalore and what kind of products they can shift. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers Chennai">Packers and Movers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers Noida">Packers and Movers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers Navi Mumbai">Packers and Movers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers Thane">Packers and Movers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers Ghaziabad">Packers and Movers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers Faridabad">Packers and Movers Faridabad</a>

**Comment by rrsahu** [comment]
Once you will be sure about all these information, you will not hesitate in making provides with best packers and movers in Bangalore .

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers Delhi">Packers and Movers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>

**Comment by rrsahu** [comment]
The job of product packaging and moving Industry is to shift fragile and most valuable products from one position to other with reliable protection. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by kosir** [comment]
@DavidMetcalfe "After having disabled the native keyboard shortcuts in Settings to ensure there's no conflicts..." sorry, which settings, gmail or vimium?

**Comment by limitedAtonement** [comment]
@kosir He means gmail keyboard shortcuts. Since you want to use vimium shortcuts, you should make sure that "f" isn't being interpreted by gmail to, say, delete all messages. ;-)

**Comment by eyalev** [comment]
Is there a solution for focusing on the email-content frame in gmail? Currently I can't use 'j'/'k' initially. I need to reach the mouse and click inside the email contents.

**Comment by mkarnicki** [comment]
I confirm @eyalev 's report (even though it's January 2018). I have Gmail shortcuts disabled, yet vimium's "j/k" keys are not scrolling the window. Am I missing something, @DavidMetcalfe ? :) Thanks.

<img width="671" alt="screen shot 2018-01-13 at 12 10 39" src="https://user-images.githubusercontent.com/2966794/34905534-f03cbe82-f85a-11e7-9687-2bd8116fd6a0.png">

**Comment by smblott-github** [comment]
@mkarnicki ...

1.  Check on the options page or in the popup that you do not have an exclusion rule for GMail.  For better or for worse, Vimium ships with one.

2. Failing that, The GMail page contains lots of frames, and it's easy to end up with the focus in the wrong frame.

**Comment by mkarnicki** [comment]
Thank you for replying, @smblott-github . Re: 1, I do not have the exlusion for GMail in Viumium (double checked). Re: 2, the interesting bit is I realized I can scroll the Hangout contacts list to the right with J/K (assuming correct focus), but I can't scroll a thread of messages, even though I tried focusing that area multiple times. Sorry for "re-opening" this issue, I was hoping someone might have that part figured out.

**Comment by hugadams** [comment]
Just for anyone new to vimium who isn't super clear on how to change these options:

First click the vimium extension icon on your browser and choose the small "options" link in the bottom.

![image](https://user-images.githubusercontent.com/1972276/68037754-c9ab7480-fc9e-11e9-97d5-57df468beaf3.png)

Then look for your "excluded keys and urs" list and remove gmail. 

![image](https://user-images.githubusercontent.com/1972276/68037793-e21b8f00-fc9e-11e9-9431-5a40c36edeb8.png)

**Comment by limitedAtonement** [comment]
@lookbothways When you click the vimium icon in the browser toolbar, do you see something that looks like this?

![image](https://user-images.githubusercontent.com/7562490/137440175-9f62494b-9cf8-4c98-aefc-c22b961c480d.png)

Click the little "x" on the right side, then "save changes". Just now, mine looked like that (apparently I haven't been using vimium in gmail :man_shrugging:), and it didn't work for me either. I followed the instruction and now it works:

![image](https://user-images.githubusercontent.com/7562490/137440306-5b5a8c2d-b0a0-403c-b0a3-93ed532f54bb.png)
