### ISSUE TITLE
Use `ctrl+shift+h` be back and open new tab?

### ISSUE THREAD

**Issue by mijoharas** [philc/vimium#1070]
Hi, I thought I'd open this issue before I add the feature (unless anyone else wants to take it?).

Since `Shift+H` is the back command and `Shift+L` is the forward command, and since in chrome you can hold `Ctrl` and click back and it will open the previous page in a new tab (similarly for forward), I propose that `Ctrl+Shift+H` should be back-and-open-new-tab and `Ctrl+Shift+L` is forward-and-open-new-tab.

Do people agree with this? I'd like to have it included so am happy to add the feature, just want to check that it would be wanted before I start.

**Comment by sesas** [comment]
I'd like this feature to be implemented, and tbh I think it's more intuitive than `ytH` even though I am glad I know this shortcut now.  Just to make sure, on a Mac it would be `CMD+SHIFT+H` right?

**Comment by sesas** [comment]
Maybe we should just publicize `yt,shift+H` more. (in the readmes)

**Comment by rrsahuone** [comment]
If you are interested in partial moving or shifting then packers and movers will help you for the same also. The expert will package your stuff and I will be shifted to desired place in few hours only. Leave the running and unloading procedure on to experts as it is done by the group and you don’t have to take pressure at all for moving related solutions.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by rrsahuone** [comment]
Our detailed packers and movers guarantee exceptional solutions without compromising on protection. The best aspect is that all product packaging and movers can be enjoyed in your price range only. Our product packaging solutions not only useful time but provide you with an opportunity to spend a while on most effective factors.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers in Delhi">Packers and Movers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by rrsahuone** [comment]
It will manage your stage of pressure as well and headache of product packaging and moving will reduce significantly. Reputed packers and moving service Information mill ready to perform depending on your schedules and package all products professionally to protect them.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers in Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a>

**Comment by rrsahuone** [comment]
Complete your moving and product packaging needs more effectively with our detailed packers and movers. We have group of experts who have created deep research on all packers and movers to get information on to their qualifications. This is the purpose we guarantee provides from certified suppliers only. We create sure that you are working with best product packaging and moving Companies and provides are available in your price range only

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
