### ISSUE TITLE
Removing 'f' from default characters used for link hints

### ISSUE THREAD

**Issue by gto76** [philc/vimium#1079]
Just a suggestion.
That way pressing 'f' again closes the hints.
Feels natural to me.

Cheers.

```diff
diff --git a/background_scripts/settings.coffee b/background_scripts/settings.coffee
index 175f326..343c80a 100644
--- a/background_scripts/settings.coffee
+++ b/background_scripts/settings.coffee
@@ -58,7 +58,7 @@ root.Settings = Settings =
   # or strings
   defaults:
     scrollStepSize: 60
-    linkHintCharacters: "sadfjklewcmpgh"
+    linkHintCharacters: "sadjklewcmpgh"
     linkHintNumbers: "0123456789"
     filterLinkHints: false
     hideHud: false
-- 
1.9.1
```

**Comment by aldafu** [comment]
The first thing I do when installing Vimium is this change, removing f from the default link hints.

+1

**Comment by smblott-github** [comment]
I think we can close this.

Phil makes a good point, above, and user's who whant this behaviour can just remove `f` from the hint characters.

(Anyway, filtered hints are far superior -- but I guess that's a matter of taste.)

**Comment by mrmr1993** [comment]
I'd rather this wasn't closed: the default is jarringly disruptive to this workflow, especially on a new machine/profile, whereas the alternative only occasionally increases the number of characters per hint. Basically, I hate moving to a new machine and clicking a random link when I'm trying to close hints.

NB: If #1871 is merged, then changing the default will negate its benefit, to give no net loss/gain in hint character length, but will be a big win for us.

**Comment by fire17** [comment]
For anyone still looking for the solutions I also just found out, go to chrome -> Vimium extension settings -> Extension Options -> Advanced Settings (bottom) -> 
Characters used for link hints - Remove f from list :)

originally i didnt notice the advance tab and tried doing unmap f - which obviously disabled this option
