### ISSUE TITLE
Incorrect handling of polymer input elements

### ISSUE THREAD

**Issue by unya** [philc/vimium#1083]
On the polymer-project demo page, http://www.polymer-project.org/components/paper-elements/demo.html#paper-input the input elements don't register properly as input elements under vimium, i.e. they do not cause a switch to input mode and thus "lose" the keys that are mapped in Vimium.

I am not sure if it's an issue with Polymer itself or with Vimium (Vimperator in Firefox handles it fine) or maybe even Chrome.

Chrome version: linux/x86_64 35.0.1916.153 (Official Build 274914)
Vimium: 1.44, from Chrome Store
Matching issue in polymer bugtracker: https://github.com/Polymer/polymer/issues/559

**Comment by smblott-github** [comment]
Closing.
Problematic site no longer exists.
