### ISSUE TITLE
Cmd+= on Mac triggers pin/unpin tab command in addition to zooming in

### ISSUE THREAD

**Issue by gulkily** [philc/vimium#1087]
Vimium should ignore the Cmd+= shortcut, which is used to enlarge the text on the current page.

The = key also triggers the pin/unpin command when typed into a text entry box, which also should not happen

Steps to reproduce the issue:

1) Open a web page on which Vimium is activated.
2) Press Cmd+= to = enlarge the text on the page

Expected: The text on the page is enlarged (page is zoomed in). No other action.

Actual: The text on the page is enlarged, but the Chrome tab is also pinned/unpinned

3) Focus a text box on the page. Type an equals sign (=) into the text box

Expected: An equals sign is entered into the text box. No other action.

Actual: In addition to the equals sign being input into the text box, the current Chrome tab is pinned/unpinned

**Comment by smblott-github** [comment]
Closing.
Assume no longer an issue.

**Comment by gulkily** [comment]
Verified that it is no longer an issue.
Alt-p appears to work for pin/unpin.
I don't really use this feature, but is there a reason that a two-key shortcut was chosen?

**Comment by smblott-github** [comment]
> I don't really use this feature, but is there a reason that a two-key shortcut was chosen?

I don't know.  It was a possibly a poor choice.
