### ISSUE TITLE
Option to disable insert mode

### ISSUE THREAD

**Issue by wolfmanstout** [philc/vimium#1092]
Would you consider adding an option to disable insert mode altogether? In other words, the keyboard shortcuts would still be active when the cursor is in a text box. Of course, this only makes sense if all the actions have been remapped to use modifiers. I confess, I'm an Emacs user…

I've tested this locally with a one line change to never enter insert mode, and it appears to work fine. I only bind keys for link following, though.

My motivation is that many webpages automatically adjust focus, and thereby enter insert mode unexpectedly. I suppose another workaround for this would be to somehow prevent that behavior. Sometimes the focus change is welcome, though — I would just like the option to use my keyboard shortcuts.

**Comment by smblott-github** [comment]
Closing.
Lack of interest.
