### ISSUE TITLE
Opening link in new window behaviour

### ISSUE THREAD

**Issue by kul** [philc/vimium#1096]
With the newest update of vimium  i was no longer able to open links in new tabs by,

press `f` -> (let say`PC` is one of the suggestions) press `pC`.

This used to work consistently till now. I have to now resort to `F -> pc`.

**Comment by z0rch** [comment]
A month has passed.... is there anything, that blocks us from merging #1104?

/cc @philc, @mrmr1993

**Comment by smblott-github** [comment]
#1104 is merged.
