### ISSUE TITLE
dashlane + vimium = :(

### ISSUE THREAD

**Issue by prior** [philc/vimium#1107]
The latest greatest? password tool, Dashlane, is not playing nice with vimium :( and I'm not sure who's at fault.  If both extenstions are turned on, certain input boxes will record keypresses appropriately showing those letters in the input box, BUT they will also be recognized by vimium as happening outside of an input box, so all sorts of crazy shit happens when you start typing as you can imagine.

Please help!

**Comment by philc** [comment]
Closing due to lack of update.
