### ISSUE TITLE
When showing possible links to open use more single letter characters instead of 2 letter combinations

### ISSUE THREAD

**Issue by workistoofun** [philc/vimium#1125]
Maybe make this an option or primary but I think the opening of links could be sped up (for the user) by using fewer two letter combinations and more single letter ones.

**Comment by dragon788** [comment]
I think tylercal is exactly right, if you want more single character shortcuts you simple need to add them to the list of available characters for links. I think the current ones were chosen because they are easy to hit, don't require much effort, and most pages don't have a million links on them.

**Comment by smblott-github** [comment]
Fixed in #1949.
