### ISSUE TITLE
Selective disabling of keybindings

### ISSUE THREAD

**Issue by justmytwospence** [philc/vimium#1134]
I've searched the issues, but haven't been able to find anything addressing this issue. For most sites where I disable Vimium, I would still like to preserve the tab navigation bindings. Right now, if I'm tabbing across a bunch of tabs and one of them is, say, feedly or gmail, I get stuck and then have to resort to the native chrome shortcuts.

Is there any way to preserve a few keybindings (namely tabbing) but disable the rest?

**Comment by smblott-github** [comment]
Closing.
Fixed with pass keys.
