### ISSUE TITLE
Select option in the 'open link' dropdown and put it on the text field

### ISSUE THREAD

**Issue by luanpotter** [philc/vimium#1141]
Hello! First of all, I'd like to say that Vimium is amazing, I absolutely love it. Therefore, I have a feature suggestion that you help me, and I hope many others, greatly.

Currently, when you press 'o' or 'O' to open the 'open link' bar, you can start typing an address and then select from a dropdown below one of the matches. Commonly enough, though, the match is almost what I wanted: I need just to append a path to the end or change a few characters. However, there seem to be no way (I couldn't find any, sorry if I missed it) to select one of the URLs but instead of following it, just populating the text box with the path. I suggest that to be done via pressing tab when selecting an option on the list. Currently tab goes to the next item, but that can be done with the navigation keys as all.

It would also be nice if, by default or via a key stroke, I could add the current page URL to the box, so that I could see it or alter it slightly as well (specially when working on full-screen mode, in which you may know chrome happily makes it impossible to change the current address by default).

**Comment by fly1ngDream** [comment]
Is there any reason, why this functionality was removed? (or why url was substituted with search engine query). In my opinion, it would be great to have such an option
