### ISSUE TITLE
Vomnibar.activateTabSelection should list all open tabs so that scrolling through all of them is possible

### ISSUE THREAD

**Issue by deiga** [philc/vimium#1156]
Currently when opening the Vomnibar for tab search (`shift-T`)  it shows only 10 tabs.
It would be great if it listed all open tabs and then be able to scroll through them.

**Comment by dragon788** [comment]
Since I'm using Vimium like crazy going through the GH issues today, I'll say I definitely think this would be useful, storing the entire list somewhere and pulling up the current 10 and having the next 10 on deck would be very handy for continuously scrolling. I've actually uninstalled ALL my other tab switching plugins once I found this behavior in Vimium, but the limit of 10 is pretty low considering I've had up to 200 open and active tabs in Chrome at a time, so many that even my favorite research organizer Tabs Outliner wasn't helping me out.

**Comment by deiga** [comment]
Basically this just needs editing of this number https://github.com/philc/vimium/blob/master/background_scripts%2Fcompletion.coffee#L500 or the possibility for `TabCompleter` to pass in as argument the max to unlimited f.ex.

**Comment by smblott-github** [comment]
Is it really so simple?  You'd have to deal with scrolling the vomnibar too, and a couple of other issues.

But, more fundamentally, is the use case for this particularly strong?  You'd have to have *many* open tabs and not have *any* text suitable for filtering.  Well, ok, I guess that can happen.  But then, you'd also have to think that hitting `Tab` fifteen or twenty times, say, is better than finding the tab some other way.

(Off topic: If what I'm looking for is not in the top three or four vomnibar entries, I won't even see it. Changing the max. results from 10 to 6 would be reasonable, for me, and would improve how the vomnibar looks on smaller screens, where it currently nudges too closely against the bottom of the screen.)

**Comment by deiga** [comment]
We could make the maxsize an option and implement scrolling in the vomnibar. Also make it "scale" with screen size.

I normally have 30+ tabs open and can't remember what they are all about. Instead of tabbing through all of them (which takes time to load each first) It would be nice to just be able to scroll in the vomnibar

**Comment by dragon788** [comment]
I normally have 50+ tabs open and while sometimes I have an idea of what to search to narrow down the tab I want to open, if I'm researching powershell in a window I have the google results page and a dozen or more tabs with powershell in the title, if I had found one that was useful but had to task switch, getting back to that one if I had to open a new window with more than 10 tabs (it happens, especially when a system goes down and I'm opening a bunch of tabs to check the status of build nodes etc), then I have to spend a few minutes getting back to the right tab, when I could more easily use the vomnibar, but in conjuction with https://github.com/philc/vimium/issues/1170 this would be AWESOME!

**Comment by deiga** [comment]
I'd love to reopen this, if it would be ok to work this into Vimium. I've upgraded from 30+ tabs to 150+ tabs and really desperately need this functionality :D 

I'd also need some help on how to implement this :)

**Comment by enavarrocu** [comment]
Same issue here. Just I can't say the amounts of tabs I have open ... is really too much. Ten results are not enough for our use case :D. Maybe is possible to put this as a configuration parameter. 

Thank you guys for your hard work.
