### ISSUE TITLE
Custom html what would be treated as href/link

### ISSUE THREAD

**Issue by mbollemeijer** [philc/vimium#1157]
I am a Java web dev one of the frameworks we have in every project is http://www.zkoss.org/
ZK basically generates the html for you.

The problem is that I cant use vimium on most of the mouse clickble links because vimium doesn't recognise the generated links by ZK.
I would love the option to that I can specify which html structures must be treated as a link.

Greets

**Comment by smblott-github** [comment]
Closing.
No response from OP.
