### ISSUE TITLE
Per-site next/prev patterns

### ISSUE THREAD

**Issue by matthew-cline** [philc/vimium#1158]
On forums which have have both next/prev page (within thread) links and next/prev thread links, the default next/prev patterns often pick the thread links (which I don't want) rather than page links (which I do want).  But I don't want to change the global prev/next patterns just to deal with this issue, plus the necessary patterns might differ from one forum to the other.  So, some way of having per-site patterns would be nice.

**Comment by smblott-github** [comment]
Closing.
Probably won't fix this one, ... sorry.
