### ISSUE TITLE
Close function delay causes wrong tab to close

### ISSUE THREAD

**Issue by horta1212** [philc/vimium#1160]
When I type 'x' and then change tabs quickly using ctrl-shift-tab or shift-tab the new tab I'm working in ends up getting closed because the X takes so long to close. I'm surprised it 1) takes so long to close a tab and 2) it doesn't record the order in which keystrokes are pressed or it doesn't make note of which tab is currently open immediately to ensure closer of the correct tab.

The reason I use ctrl-shift-tab or shift tab rather than gt or gT is because it's faster to press all the keys at the same time rather than press two keys in sequence. It's also more universal.

Google Chrome	36.0.1985.125 (Official Build 283153) dev-m
OS	Windows
Vimium 1.45

**Comment by smblott-github** [comment]
Fixed in e0ab4722f2298addd6d80ea1af1427bb41fc2fd9.
