### ISSUE TITLE
Is there any way to change (remap) keyboard shortcuts

### ISSUE THREAD

**Issue by ashkrosh** [philc/vimium#1168]
Hi, vimium shortcuts have conflicts with other handy extensions like Evernote clipper. Is there anyway to remap shortcuts for vimium or better just auto-disable it in context of open evernote clipper? I mean if evernote web clipper was open (as overlay on page) then vimium should not listen to key events.

Cheers,

**Comment by dm17** [comment]
Possible *per site*? Facebook's default shortcuts can't work for many OSs... For example I need ALT not to be ALT for FB.
