### ISSUE TITLE
Selecting vomnibar results using keyboard shortcuts 

### ISSUE THREAD

**Issue by ayberk** [philc/vimium#1170]
It would be great if we could select vomnibar results using keyboard shortcuts similar to Alfred. A screenshot of how Alfred presents results is: 

![Alfred](https://cloud.githubusercontent.com/assets/309940/4516423/d279fee2-4bf5-11e4-8137-2777f596c703.png)

As you can see there are shortcuts assigned to each result which are displayed on the right side. It would be really nice to have similar shortcuts in vomnibar as well.

**Comment by dragon788** [comment]
I agree there should be some way to select the results from the Vomnibar quicker, I would also like to see it applied to the open tabs search as well, though I seem to recall somebody mentioning there was a shortcut to jump back further in that case.

**Comment by smblott-github** [comment]
So the idea would be that `<c-1>` would directly select the first suggestion, and so on?  Is there a reason that wouldn't work? (I don't get @deiga's point, above.)

**Comment by ayberk** [comment]
Yep, that's the idea. His point is it is not possible to use the same shortcuts as Alfred(see SS I provided), because they're already assigned.

Maybe it's possible to temporarily reassign them only when Vomnibar is active?

**Comment by mrmr1993** [comment]
> Maybe it's possible to temporarily reassign them only when Vomnibar is active?

Not just possible, it would take extra work to unnecessarily override the mapping when the Vomnibar is closed.

> (I don't get @deiga's point, above.)

Looks like @deiga is worried about a clash between our mappings and the chrome default. Since there doesn't seem to be a valid use case for switching to the nth tab while the Vomnibar is open, I'd say his point is moot.

**Comment by dragon788** [comment]
If its possible to use modifier keys to select things from the vomnibar by position, I would love to see this use something similar to link hinting where I can hold Ctrl or Alt and press a letter or two to jump immediately to a tab a ways down the list. This is more in line with the vim feeling of keeping your fingers on the home row and if you have Ctrl remapped to Caps (why NOT!) it would be amazingly fast. Avoiding conflicts with existing mappings in Vimium/Chrome would be the hardest part as mrmr1993 mentioned.
