### ISSUE TITLE
Open tab next to current or at specific tab position 

### ISSUE THREAD

**Issue by jottr** [philc/vimium#1175]
ViChrome offers this by passing a parameter to `:TabOpenNew`: https://github.com/k2nr/ViChrome/wiki/Vichrome-User-Manual#tabopennew

`--next : Open new tab next to the current tab`

It would be really nice if we could have more control over the position of a new tab, i.e. something like this: 

`3t`  insert new tab 3 tabs to the right. 
`-3t` insert new tab 3 tabs to the left. 
`$t`  open new tab on the far right.

**Comment by smblott-github** [comment]
Closing.
Lack of interest.
(And you can do this with a couple of extra keystrokes.)
