### ISSUE TITLE
option to make insert mode manual-only

### ISSUE THREAD

**Issue by ilya** [philc/vimium#118]
suggested on hacker news. avoids getting trapped in insert mode due to forms.

**Comment by smblott-github** [comment]
Closing.
Very old and not now relevant.

**Comment by masaeedu** [comment]
@smblott-github I think it's still relevant. As an example, if I open gitter.im, I get dropped into the input field at the bottom. This means when I'm hitting H/J etc. to try and switch tabs, i'm actually just typing garbage data into the form field. There's a number of focus traps like this that make tab navigation annoying, e.g. sometimes something will focus the url bar and your flow will be disrupted by "why isn't J working, oh the url is focused, ok, ctrl+f6", etc.

It'd be nice if the only time I got entered into insert mode anywhere was when I explicitly hit I.

**Comment by smblott-github** [comment]
Is this option what you're looking for, @masaeedu (the bottom one)...

![image](https://user-images.githubusercontent.com/2641335/36960849-c11e3c94-2040-11e8-8dbf-1c255c3a0c5c.png)

**Comment by masaeedu** [comment]
@smblott-github Sweet, that *is* indeed the option I'm looking for. I wonder if there's a way to do the same for the URL bar?

**Comment by smblott-github** [comment]
> I wonder if there's a way to do the same for the URL bar?

There's no API for getting the focus out of the URL bar (I think).
