### ISSUE TITLE
Links "hovered" by clicking are never "unhovered"

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#1189]
Links which are clicked using `LinkHints.activateModeToOpenInNewTab`, `LinkHints.activateModeWithQueue`, etc. trigger the hover effect of the link by sending a `mouseover` event, but the corresponding `mouseout` event is never sent, so the hover effect persists even after clicking other links.

An example of this behaviour is the movie posters on [this IMDb list](http://www.imdb.com/list/ls059872711?start=1&view=grid&sort=listorian:asc&defaults=1&scb=0.034486552234739065).

PR #1032 fixes this.

**Comment by menelaos** [comment]
Is there any progress on this issue?

**Comment by mrmr1993** [comment]
I've created PR #1819, using the idea from #1032 but without adding any new commands.
