### ISSUE TITLE
There is no feedback given for overlapping mappings

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#1190]
A user can happily provide the custom key mappings
```
map h scrollLeft
map hh LinkHints.activateModeToHover
```
but will not be able to trigger the `hh` mapping, and will not receive any warning about it. This can cause confusion, especially when the first binding may not be explicit in their settings (due to the default mappings).

This example was derived from [this comment](https://github.com/philc/vimium/pull/1032#commitcomment-8304377).

**Comment by smblott-github** [comment]
Closing.
Despite a number of nonsense scenarios being possible, almost nobody has complained.
