### ISSUE TITLE
Should domains have favicons shown in the vomnibar?

### ISSUE THREAD

**Issue by philc** [philc/vimium#1208]
![image](https://cloud.githubusercontent.com/assets/8598/4827600/b47dd6ce-5f79-11e4-9f96-c1a64c7e1650.png)

**Comment by dragon788** [comment]
Does this still need some security auditing? I do like the idea of a favicon, sometimes sites like to masquerade with a false favicon, but its an easy way to distinguish between them.

**Comment by mrmr1993** [comment]
So far I think we've tried a couple of things but rejected them:

* #1210 had privacy issues I mentioned [here](https://github.com/philc/vimium/pull/1210#issuecomment-61002199), but worked for most URLs.
* #1232 had no privacy issues but failed to get an icon a lot of the time from `chrome://favicon`.

Realistically, we need a new way to get favicon URLs before we try this again.

**Comment by smblott-github** [comment]
An alternative would be to have *icons* in the vomnibar to indicate the type of the suggestion, as chrome does...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7559403/8ce5842c-f7ae-11e4-8c21-4eaeb904b353.png)

The current text-based approach looks pretty clunky, IMHO.

**Comment by smblott-github** [comment]
We've rejected this idea, for now.
