### ISSUE TITLE
No user feedback for vimium disabled URLs loaded in frames

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#1212]
Example: [r/videos](http://www.reddit.com/r/videos), click one of the ![](https://cloud.githubusercontent.com/assets/1847343/4765582/9fec5f10-5b40-11e4-964b-c96175bdca01.png) buttons to load a frame from another URL.

Blocking either the top frame or one of the iframes only gives feedback to the user about the state of the top frame.

**Comment by smblott-github** [comment]
Closing.

This should be fixed.
The icon now reflects the frame's URL.
