### ISSUE TITLE
Improve the options UI

### ISSUE THREAD

**Issue by philc** [philc/vimium#1237]
When you expand the advanced options, the Save button is in the middle of the form. I completely missed it and thought we had removed it! The Save buttons for forms should be at the bottom of the form.

![image](https://cloud.githubusercontent.com/assets/8598/4989840/c8dfbf60-6933-11e4-8c26-75a7a8f8071f.png)

Secondly, the checkboxes appear as if they're sub-options of "characters used for link hints" due to their alignment and indentation, but they're not (maybe the first one could be). One proposal is to make them flush-left with form's bounding box. Another is to give them a "caption", like "Misc", so it's clear that they are their own section.

**Comment by smblott-github** [comment]
Closed due to #1244
