### ISSUE TITLE
cVim or "Why don't we concentrate on that?"

### ISSUE THREAD

**Issue by hpurmann** [philc/vimium#1278]
Hey community :)

with a hint from @tkossak I started to use [another vim plugin for Chrome, called cVim](https://github.com/1995eaton/chromium-vim). 

The development started in March 2014 and it's already better than vimium. Just look at all the features and the problems it solves as opposed to vimium. For example these vimium issues which were opened a long time ago are already solved in cVim.
- Prevent pages from taking focus: https://github.com/philc/vimium/issues/886
- **Visual mode** (works great): https://github.com/philc/vimium/issues/61
- Mouse hovering: https://github.com/philc/vimium/issues/484

So the general question is: Why don't we just switch over, start using and contributing to cVim instead of vimium? In my opinion that would be better than having two projects with exactly the same goals.

What do you think?

**Comment by rrsahutwo** [comment]
Are you looking for expert movers and packers in Bangalore? Well, you have come to the right position and definitely your search has been completed at EXPERT Packers, a well well-known moving company. We are a group of expert packers and movers who create the moving process secure and secure. With an ample encounter in the transportation market, we are able to help you shift in any aspect of the nation and some areas in abroad. Our national and worldwide moving alternatives create you totally exempt from all types of pressure and troubles what you might have.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
Everything in this world is getting proficient and personalized now a days. Did you ever employ any expert support for packaging and running your things or goods? Your answer may be no, yet today, factors are different now. In the event that you are moving to another zone or a town, packers movers Bangalore at EXPERT Packers take a swing at your salvage. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
Professional Packers & movers in Bangalore are additionally essentially known as movers. Our whole process of moving consist of pressing various factors, for example, your closet to the kitchen utensils and furniture securely, even the sensitive ones whatever you have at your house. We keep all obligations to take the same to your new desired place without giving you a chance for hardly lifting a finger.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
Presently it’s certainly not the same way when you used to package family things yourself in huge sacks or compartments and get rid of the same. We are national leveled expert best packers and movers in Bangalore to stack all your items or items and take it to the new area in appropriate transportation, for example, car, ship, planes or may be huge trucks. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
