### ISSUE TITLE
'ESC' blurs input in Google Hangout (Chrome extension) window rather than closing the window

### ISSUE THREAD

**Issue by enoch** [philc/vimium#1285]
This may be related to #1176 but I figured I would open another issue just in case it wasn't? I'm not sure how Vimium behaves with chrome extensions since Vimium seems to not be active in other chrome extension-related windows/tabs.

Mac OSX 10.10.1
Chrome Version 39.0.2171.71 (64-bit)
Vimium v 1.45

Steps to reproduce:
* With Vimium active, open a Google Hangout (Chrome Extension) chat window
  * Input field should be automatically highlighted
* Press 'ESC' and the input field should blur/lose focus
* Close chat window
* Disable Vimium extension
* Re-open Google Hangout chat window
* Press 'ESC' and the chat window should close.

**Comment by rrsahutwo** [comment]
With Bangalore packers and movers, changing house and workplace become very simple, as we do not have to do all the large and annoying perform alone. Bangalore is historical town. Here, lots of work at house opportunities are waiting for the right person. It is regarded as one of the best growing places on the basis of commercial areas. Movers and packers are not only to show status in society, but they seems as a need now.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
Finding labors to provide your fill is very simple, but discover someone trustable is really tough or we can say, it seems to be impossible. Packers and Movers Services in Bangalore is the right choice which you can select anytime at any position. They are trustable and wise to their jobs, that you can leave whole perform on them without any type of doubt.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
They are experts and know how to perform without harming anything. You can believe in them and leave all your useful content, over them without any risk. They do not only package your items but also help in moving and moving from your present position to the new one. Transport process is also included in their alternatives.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
If you have any doubt about their alternatives then let us obvious it. They have expert abilities and know how to finish perform promptly. Once you seek the services of them, your duty is absolutely finished. You just have to provide your address and some other details, so they can quickly get in touch with you. They come to your position and package all the things in great quality content.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
