### ISSUE TITLE
Modes to deal with Vimium vs site specific shortcuts

### ISSUE THREAD

**Issue by rkpatel33** [philc/vimium#1287]
Is it possbile to implement a 'normal' mode and 'insert' mode concept, such that on sites like Gmail:

- normal mode blocks native gmail shortcuts/allows only vimium shortcuts
- insert mode allows the native gmail shortcuts to work and blocks Vimium shortcuts until you return to 'normal' mode. 

I could even see this extending to a 'desktop' Vimium application so you can navigate your OS without the mouse and using relavent Vim commands in different settings (things like entering text in text fields/boxes).

**Comment by rrsahu** [comment]
The best aspect is that we guarantee highest possible protection and protection. Bangalore movers and packers create sure all your individual valuables are loaded carefully with multiple layer of protection and they will not break during transportation.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by rrsahu** [comment]
Packing and moving Company in Bangalore usually provides moving solutions in same town or close by places. In stressful schedule, it is very hard for experts moving or shifting from one position to other. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers Delhi">Packers and Movers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>

**Comment by rrsahu** [comment]
It requires lots of your energy and effort and initiatives as well. To preserve now, packers and movers are completing your job. They will package everything and shift to desire position. In this way, Packers movers are helping their customers.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers Chennai">Packers and Movers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers Noida">Packers and Movers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers Navi Mumbai">Packers and Movers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers Thane">Packers and Movers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers Ghaziabad">Packers and Movers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers Faridabad">Packers and Movers Faridabad</a>

**Comment by rrsahu** [comment]
Moving and shifting is much simpler than it was regarded in previous Let us see how moving service and packers in Bangalore create it possible!!!

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by AdrieanKhisbe** [comment]
Seem to be already implemented. Just tested on a trello board.
Should be close?

**Comment by smblott-github** [comment]
Closing.
In light of pass keys, it's not clear that there's any action needed.

**Comment by vimniky** [comment]
How can I get a block cursor when I navigate using vimium . without a visual cursor I just don't know where I was . One thing , what if I want to copy a word on a webpage ? please help !

**Comment by vimniky** [comment]
It would be great if vimium support vimiumrc .

**Comment by vimniky** [comment]
Esc is far away from reach . It would nicer if there's a handy key map for Esc

**Comment by johnmolino** [comment]
Probably not the answer your looking for - but if you are into keyboard shortcuts (you wouldn't be here if you weren't so that's a given) - and you probably already know all this, but in the event you do not... I am truly sorry to do this to you .....Look into getting an HHKB keyboard and mod it with a Teensy controller and code from Hasu from Geekhack - the world is your oyster ....

WARNING...on the off chance you don't know what I'm talking about - these links WILL 1) eat up your time, 2) lighten your wallet 3) possibly cause a divorce and 3) ultimately consume you: (OK I'm kidding about the divorce)...
https://geekhack.org/index.php?PHPSESSID=afjevpth96rs81k12db5oevcbo2flk1q&topic=57008.0
https://elitekeyboards.com/products.php?sub=pfu_keyboards,hhkbpro2&pid=pdkb400b

But yeah it would be nicer to have a key map for Esc. :)

(Sorry if this was a little off - topic)
