### ISSUE TITLE
Link hints don't show for Facebook comment fields

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#1295]
Facebook have just pushed a new UI update (UK), and now link hints don't show for the "Write a comment..." textbox (until you've clicked on it once, then they magically start showing).

Eg.
Original:
![screenshot from 2014-12-11 02 13 10](https://cloud.githubusercontent.com/assets/1847343/5388028/8655b3d8-80db-11e4-8e20-5823c5cb13da.png)
With link hints:
![screenshot from 2014-12-11 02 12 45](https://cloud.githubusercontent.com/assets/1847343/5388026/8651a96e-80db-11e4-8d38-8498d79655ba.png)
Link hints again after selecting (and subsequently deselecting) the comment field:
![screenshot from 2014-12-11 02 13 44](https://cloud.githubusercontent.com/assets/1847343/5388027/8652ea18-80db-11e4-88d3-881afe3de72f.png)
Link hints *again* after also clicking the photo button:
![screenshot from 2014-12-11 02 14 22](https://cloud.githubusercontent.com/assets/1847343/5388029/86580462-80db-11e4-9e95-83df481143a9.png)

**Comment by smblott-github** [comment]
Closing.
Not clear we can fix this.

**Comment by eft890** [comment]
Sorry for necroing the thread, but wouldn't it be possible to tokenize the facebook comment thread by div.UFICommentContainer? Like using document.getElementsByClassName("UFICommentContainer")? Then we simulate a mouseclick on that and let the FB JS do it's focusing thing for us.

I think FB is a common enough site to warrant special casing.
