### ISSUE TITLE
generally not working

### ISSUE THREAD

**Issue by githubdbes1** [philc/vimium#1296]
Hi All,

I just installed Vimium.  Thank you to everyone who's worked on this project.

Unfortunately, it seems like Vimium won't work on most web pages I visit.  If I type Shift-F nothing happens.  I wonder if maybe there is a conflict with one of the other extensions I have installed?  Below is a listing of those extensions in case someone spots one they know is problematic.  Otherwise, are there any recommendations on preliminary things to investigate when Vimium isn't working?

Thanks,
david

Windows 7 Pro SP1 64-bit
Chromium 37 Portable details:
+++++
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.3 Safari/537.36

Extensions: 48
- Auto Refresh v0.2
- Better History v3.7.8
- Chrome extension source viewer v1.2.4
- chromeIPass v2.6.7
- Chromoji - Emoji for Google Chrome™ v2.3.1
- Context Menu Search v2.93
- Cookie Inspector v2.0.4
- CSSViewer v1.6
- Edit in Zed v0.1.3
- Extensions Manager (aka Switcher) v0.2.1.2
- Extensions Update Notifier v2.3.1
- eyeCare - Protect your vision and health v0.0.0.9
- F.B Purity-Clean Up Facebook v12.7.0.10
- Feedbro v2.9.3
- FlashControl v5.14.4
- Hover Free v1.0.11
- HTTP Switchboard v1.0.1.5
- Humble New Tab Page v1.16
- IP Address and Domain Information v3.33
- IPvFoo v1.30
- JSON Formatter v0.6.0
- LocalLinks v1.1
- Magic Actions for YouTube™ v6.8.3
- Page load time v1.2.2
- performance-HTML v0.1.3
- Popup Notifications for Craigslist v2.0.0.108
- Privacy Guardr v0.1.6
- Privacy manager v2.9
- Quick source viewer v1.0.8: https
- Reddit Enhancement Suite v4.5.2
- Server Details v1.0.12
- Share Extensions v0.1.1
- ShowPassword v1.1.1
- Simple Time Track v2.6.3
- SingleFile Core v0.3.18
- SingleFile v0.3.18
- Stop AutoRefresh v1.2.1
- Stylebot v2.2
- sunglasses v1.1
- TabList Manager v4.4
- Tabs Outliner v0.4.81
- TagSpaces Light v1.9.0
- tinyurl v1.0
- Toggle Switch Recent Last Tabs v1.4.2
- Url in title v1.1
- Vimium v1.45
- ZenMate v3.8
- zoomWheel v1.0.1.5

Disabled Extensions: 0

Exported with Share Extensions for Google Chrome™ - https://chrome.google.com/webstore/detail/chdafcbnfkfenoeejpaeenpdamhmalhe
+++++

**Comment by rajeevksahu** [comment]
If you are going to shift recently, you just need to book your moving package after discussing about all need and price range. We will handle your secure and convenient moving needs with our efficient alternatives. Our commitment and transparency will create you realized that the company you have hired is really what you would like to seek the services of again and again in your upcoming needs and we are sure you will be our permanent clients later on.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
Are you looking for the best packers and movers in Bangalore ? Well, you have come to the right position. Now you need not go anywhere else, you will discover all you need to shift your, company, shop, house. EXPERT Packers is an knowledgeable movers with many divisions in the different places across the nation. We have a huge system of our expert experts as well as pleased clients. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
We aim at providing the most efficient moving alternatives to people from across the nation that is why we have developed the system of the experts in different places like as Bangalore , Bangalore , Bangalore , Bangalore , Bangalore , Thane, Bangalore and Bangalore . You may look for the various other transportation organizations or movers in your area or on the internet, but you will discover that most of them are self claimed best movers and packers. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
Apart from those self-claimed best packers and movers, we have built a believe in on our clients and people of the significant places through our credible alternatives. Whether your trip is short or lengthy, we handle it with our best effort and finish commitment that result in the protection, protection and effective moving.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>
