### ISSUE TITLE
<n>gt is inconsistent with vim

### ISSUE THREAD

**Issue by bamos** [philc/vimium#1298]
Hi, in vim, `<n>gt` will switch to the nth tab, but in vimium, `<n>gt` moves 3 tabs to the right.

Sorry for filing an issue if this feature is intentional.
I think it should be mentioned near these lines in the README:

```
J, gT      go one tab left
K, gt      go one tab right
```

**Comment by charliewynn** [comment]
I like vimium's implementation better (since it's 3 gt, not go-to the 3rd tab)- but I wish they were the same more than anything

I'd go for
g<n>t  go to nth tab
<n>gt go n tabs to the right

**Comment by smblott-github** [comment]
If we were starting from scratch, then we may do things differently.  However, there probably isn't a strong enough case for either changing the existing behaviour or adding a new command.

**Comment by charliewynn** [comment]
I decided to just add the vimium functionality to my vimrc

nmap gt @='gt'<cr>
nmap 0gt :tabfirst<cr>

**Comment by smblott-github** [comment]
Instead of focusing thinking about `gt`, we could look at `g0` and `g$`.

`<count>g0` (which currently has no special meaning) could be "go to the count-th tab".  Similarly `<count>g$`.

That way, at least we would have absolute tab selection (even if it isn't consistent with Vim).

**Comment by bamos** [comment]
Thanks! Will start using this.
