### ISSUE TITLE
Security issue: Pages can access priviledged information by manipulating the vomnibar dom

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#1300]
Since the vomnibar is injected directly into the page's dom, once it is opened a malicious page can change the Vomnibar's contents and force it to update by doing:

```
var inpEv = new Event("input");
vomnibarElement.value = "a"; // Could loop over all the letters of the alphabet to get more user info
vomnibarElement.dispatchEvent(inpEv);
```

This means that on any page where the vomnibar is activated, the page can access (much of) the user's bookmarks/open tabs/history.

As for stealth, it would also be trivial to clone the vomnibar dom, hide the original, and use the copy to pass results to the user (while also performing the desired searches to steal the user's data), which would be nearly undetectable for the user.

Merging #1214 would fix this.

**Comment by iferguson90** [comment]
I believe I noticed a manifestation of this issue activating Instapaper's [Save to Instapaper](https://www.instapaper.com/save) bookmarklet through the Vomnibar. I took a quick glance at the bookmarklet and it looks like it injects a script into the document which then grabs (what it believes is) the text of the article you're trying to save for later. Occasionally some of my bookmarks that are visible in the Vomnibar when the bookmarklet is activated will be appended to the saved article text.

Does this sound like the same issue? I will probably try testing this on `master` later tonight.

<sup>(I realize there's an Instapaper Chrome extension but I prefer the bookmarklet, and either way the security issue still stands.)</sup>

**Comment by smblott-github** [comment]
Thanks for the report, @iferguson90.  In principle, #1214 (which is in `master`, but not yet in the Chrome Store release) should fix this.  It would be great if you could try out `master` and verify this.

**Comment by iferguson90** [comment]
Tried `master` on ed06688979cbed11ce1fd388acb042d30598036b and it now has the correct behavior. Page styles aren't leaking into the Vomnibar and the Instapaper bookmarklet isn't picking up my bookmarks.

Looking forward to the next release! Thanks for the great extension! :octopus:

**Comment by smblott-github** [comment]
That's great, @iferguson90.
I guess we can close this now
