### ISSUE TITLE
Unable to expand groups and open emails on inbox.google.com with `f`

### ISSUE THREAD

**Issue by maximbaz** [philc/vimium#1307]
Suppose I have a group of conversations on Google Inbox:

![image](https://cloud.githubusercontent.com/assets/1177900/5426172/efac9376-8340-11e4-852e-27dab8e9623c.png)

I want to expand it, so I hit `f`:

![image](https://cloud.githubusercontent.com/assets/1177900/5426175/1745a5e4-8341-11e4-8994-64e80253c75f.png)

Finally I press `K`.

**Expected**: Group is expanded (like on the picture below)
**Actual**: Group remains collapsed (just like on the first picture)

![image](https://cloud.githubusercontent.com/assets/1177900/5426182/5657e936-8341-11e4-9e3c-a15e69ed21c5.png)

Same happens not only with groups, but with emails as well:

![image](https://cloud.githubusercontent.com/assets/1177900/5426184/80c076ac-8341-11e4-8773-ac3d2f47c937.png)

Nothing happens when I hit `E`.

-------------------------------------------------------------------
Kubuntu 14.10, Google Chrome 39.0.2171.71
b6125a2b13d6927c10f381f51b207445fd3f049b
I have no custom rules defined in vimium options.

**Comment by dragon788** [comment]
From reading a bunch of comments, it sounds like the current workaround, without even requiring passkeys is to enter Insert mode, which will pass raw keystrokes to the page, which will allow f / i / whatever to pass through and control the underlying page. I find this an acceptable workaround on these sites, since I only hit i once to enter insert mode and then everything else is "Google-y".

**Comment by rrsahu** [comment]
When you are finalizing cope, it is expected to provide 25 % payment in advance during Professional. Simultaneously, there are few Businesses that don’t ask about upfront payment at all. Here, option is completely yours which option suits you most.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by rrsahu** [comment]
Final expenses always depend on weight of products and range from current place to moving place. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers Delhi">Packers and Movers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>

**Comment by rrsahu** [comment]
For automobile transportation, you need to pay additional expenses that are mandatory. For moving different types of automobiles, different providers are used as per the specifications.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers Chennai">Packers and Movers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers Noida">Packers and Movers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers Navi Mumbai">Packers and Movers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers Thane">Packers and Movers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers Ghaziabad">Packers and Movers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers Faridabad">Packers and Movers Faridabad</a>

**Comment by rrsahu** [comment]
Never create decision in hurry. Take concept from 3 to 5 packers and movers Companies in Bangalore and cope with one that suits your pocket most. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>
