### ISSUE TITLE
Proposal: implement a Vimium-specific right-click menu for links

### ISSUE THREAD

**Issue by philc** [philc/vimium#1312]
Hey everyone, what do you think about a Vimium-specific right-click UI as a means to gracefully scale the number of commands that one may want to perform on a link?

You would "right click" on a link using link hints, and then get a popup, where each action has a reasonable hotkey:

![image](https://cloud.githubusercontent.com/assets/8598/5428924/242b3256-838c-11e4-9b53-a46b33595094.png)

Comments

* We can handle lots of commands this way without introducing new top-level commands.
* Since you don't need to bind any of these sub-commands to specific keys, it means you'll have to remember fewer keybindings to be able to use these commands. This is a nice property since most of these would see relatively rare usage compared to other top level commands.
* This naturally mirrors the interaction model Chrome uses for this use case.
* The UI elements are based on Chrome's right click menu (at least what they look like in OSX). The link which is being operated on is highlighted as it is when you right click using the mouse.
* The specific use case of hovering probably requires more thought, since you'll want to be able to unhover as well. Perhaps this is how you hover, and then hitting esc at any time unhovers.

Related issues: #484 and likely many others.

**Comment by dragon788** [comment]
OMG YES PLEASE! I've actually been thinking about this since I frequently save
documents with Pocket or want to send them with Pushbullet, and it is
difficult to activate and send those normally via the keyboard (unless using
the default mapped Ctrl+Shift+X for a single endpoint).

**Comment by Rajwin** [comment]
Yes Please, I cant believe there is no function for this

**Comment by wcpines** [comment]
I would pay for this

**Comment by smblott-github** [comment]
Move discussion to #1948.
