### ISSUE TITLE
Google inbox and gmail create many tiny, useless iframes - frames are unusable

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1317]
Take a look at this:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/5438083/7dacd7e4-846d-11e4-954d-d763c710db29.png)

In the top half, we log the ID, width and height of each `iframe` on Google inbox as it is created.  Most of them are tiny.

Then (in the bottom half), we start cycling through them using `gf`, and again log the ID, width and height.  Again, they're nearly all still tiny.  We don't even see the frame flash.  Only the last one (this is the hangouts list) actually has a real size.

So all of the frames encountered between the main frame and the hangouts frame (about ten of them) are useless.

Frames are currently unusable on Google's inbox.

This problem was also alluded to in #1182.

**Comment by rrsahuone** [comment]
Reputed Companies always create sure that experts will shift your valuables without any damage or harm. Professionals are providing unique attention to fragile products that are extremely susceptible to harm.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by rrsahuone** [comment]
Responsible packers and movers will clean and organize everything during shifting and label them wisely. During moving they are stacked depending on their labeling and fragile products are placed accordingly. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers in Delhi">Packers and Movers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by rrsahuone** [comment]
Our product packaging solutions not only useful time but provide you with an opportunity to spend a while on most effective factors. It will manage your stage of pressure as well and headache of product packaging and moving will reduce significantly. Reputed packers and moving service Information mill ready to perform depending on your schedules and package all products professionally to protect them.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers in Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a>

**Comment by rrsahuone** [comment]
Either you are interested in moving house, best packers and movers Companies in Bangalore is outstanding remedy to manage your needs. Everything will settle down depending on your time and effort and effort schedules and availability. Packing and movers are available 24/7 and our expert group assists you in best possible way.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
