### ISSUE TITLE
Disable Vimium 1.46 scrolling animations

### ISSUE THREAD

**Issue by wulftone** [philc/vimium#1320]
I'd like to be able to disable the scrolling animations--they cause a lot of problems on websites: they don't always scroll a predictable amount and are very slow.

For example, in JIRA, they only scroll 1px, even though I have scrolling set to 60px in the vimium options.  Vimium behaves similarly strangely on other pages now, too.

Chrome 39.0.2171.71 (Official Build) OSX
Vimium 1.46

**Comment by wulftone** [comment]
Thanks for the fix!  However, I'd like to reiterate my desire to have an option to disable the animations.  I prefer a snappier response, especially when holding down `d` and its ilk.  The animations just get in the way of speedy browsing.

**Comment by philc** [comment]
Hey Trevor, the option is present in the latest version of Vimium on the
store.

**Comment by wulftone** [comment]
Awesome, thank you!

**Comment by rrsahuone** [comment]
We comprehend your specifications, your emotions and always cope in best possible way with our customers. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by rrsahuone** [comment]
This is the purpose our customers are extremely pleased with our product packaging and movers in Bangalore .

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers in Delhi">Packers and Movers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by rrsahuone** [comment]
Packing, moving or shifting can be most frustrating procedure when you have to shift within Bangalore or close by place. This procedure gets more boring when one has to finish this alone. Nowadays, movers and packers in Bangalore have become most practical option for moving to a different position.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers in Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a>

**Comment by rrsahuone** [comment]
Undoubtedly, packers movers Bangalore has created moving procedure simpler than it was regarded in previous. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
