### ISSUE TITLE
Incompatible with The Great Suspender

### ISSUE THREAD

**Issue by benplumley** [philc/vimium#1346]
Vimium isn't compatible with [The Great Suspender](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg) extension. If I'm using J and K to navigate between tabs, as soon as I hit a suspended tab, I can't navigate off it, even though Control-Page Up and Down still work.

**Comment by JZL** [comment]
The Great suspender is [open source](https://github.com/deanoemcke/thegreatsuspender) so I would think it would be possible to add the needed javascript library to the suspend pages. I am just getting started with vimium so I haven't dived into the code to see if I can fork the needed change in TGS. Any help would be appreciated as without this change to TGS, vimium becomes way less useful for me

Thanks (and sorry to reopen an old thread but the problem still stands the same)

**Comment by leoj3n** [comment]
Seems it would be reasonable to add just the J and K functionality to the suspender extension. Honestly don't see any need to load entire Vimium into suspended pages, and would essentially go against the philosophy of reducing footprint. So just need to lift JK functionality from Vimium and duplicate it into suspender.

**Comment by leoj3n** [comment]
I'd be interested in attempting the separate extension idea mentioned in #2152.

**Comment by JZL** [comment]
That would be amazing

**Comment by leoj3n** [comment]
PR sent https://github.com/deanoemcke/thegreatsuspender/pull/423

The Great Suspender has been idle for a couple of months so you might just want to download [leoj3n:match-vimium-next-prev-tab](https://github.com/leoj3n/thegreatsuspender/tree/match-vimium-next-prev-tab) and [Load unpacked extension...](https://developer.chrome.com/extensions/getstarted#unpacked) (navigate to the `src/` folder).

**Comment by lucasfariaslf** [comment]
@leoj3n I unsuspended all my tabs, uninstalled The Great Suspender I got from Chrome Web Store and then followed the procedure you described. No success; can't Shift+j/k through suspended tabs. Could you please help?

**Comment by leoj3n** [comment]
@lucasfariaslf It's been a long time since I wrote the code for this fix and don't really have time to troubleshoot it. I'd suggest looking at the code that changed in the old commits I made and try applying similar changes to the newest version of the great suspender chrome extension.

**Comment by colossatr0n** [comment]
@lucasfariaslf I've updated the Vimium shortcuts to work with version 7.1.6.

7.1.6 is the last stable/safe build before GS was purchased.

I have an open PR into @leoj3n's Vimium branch, but it hasn't been merged yet. So for the time being, use this fork: https://github.com/colossatr0n/thegreatsuspender/tree/match-vimium-next-prev-tab
