### ISSUE TITLE
Shift+F links open in foreground instead of background

### ISSUE THREAD

**Issue by gulkily** [philc/vimium#1354]
Since upgrading to 1.49, when I "Shift-F" a link, it opens a new tab in the foreground instead of the background when the link is set to target=_blank. Before, they would open in the background, which was great for queueing up a bunch of things to read.

Reproducing the issue:

1) Open www.reddit.com/prefs/ and make sure that "open links in a new window" is checked
2) Go to www.reddit.com
3) Press Shift+F and select one of the article links

Expected: The link opens in a new background tab

Actual: The link opens in a new foreground tab

**Comment by ericvw** [comment]
I am experiencing this issue on websites other than [reddit](http://reddit.com).  Choose any other website and try `Shift + f (i.e., F)` or `<a-f>` to open a link.

**Comment by mrmr1993** [comment]
Sounds like #1279, does the discussion there describe your issue?

**Comment by gulkily** [comment]
Sorry I didn't respond sooner. This issue has gone away for me, so I think it was in part due to a code change on Reddit's end that went away.

**Comment by ericvw** [comment]
#1279 sounds like my issue.  Will follow the conversation there.  Thanks!
