### ISSUE TITLE
js error clicking on anything

### ISSUE THREAD

**Issue by gitaaron** [philc/vimium#1357]
after updating to 1.49 my browser seems to be throwing a js error when i click on anything

Here is the error thrown - 

VM39 extensions::utils:93 Uncaught TypeError: Cannot read property 'impl' of undefined
VM39 extensions::utils:93publicClass.(anonymous function)
vimium_frontend.js:79settings.load
vimium_frontend.js:212(anonymous function)

**Comment by rajeevksahu** [comment]
All the perform is done properly to make sure the relaxed moving of your house. Our clients do not need to do anything Expert Regarding to packaging and running the items. We recommend our clients to have their valuables like as jeweler and essential documents in their custody. For the rest we help them thoroughly and create them totally exempt from the worry and worry.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
If you are worried about the destruction of your house keep items, you need not worry about them. First, we are so knowledgeable to take the precious items to the place securely and the second factor is that we have some insurance strategy group from the well well-known insurance strategy organizations with us. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
We handle to create your items insured before we start the trip. Our expert Packers and Movers Services in Nagpur consist of all the alternatives to be done in stress free-way. For such types of the alternatives, you need not to search the different organizations and experts to get your perform done. The only factor what comes under your liability is to get in touch with us and tell us your exact need about your baggage and place. The rest with you is what we can handle in a right way. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
The most essential factor what our clients agree is that we create all the expenses and fees obvious before the agreement with the clients. Some of our competitors can allure you by providing you a low estimate for your trip, but here you need to be very peculiar about that because they can impose on you some other expenses. Unlike them we don’t have any hidden expenses and fees. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>
