### ISSUE TITLE
help! help!  open a link on a new tab background?

### ISSUE THREAD

**Issue by akokak** [philc/vimium#1379]
1, Thanks to the Vimium, it is very nice.
2. I want to find a command, to open a link on a new tab background, but I can't find out.

3, Please, give me a command, like click mid-key of a mouse on a link.

thanks.

**Comment by mrmr1993** [comment]
Should have picked up on this earlier: this issue sounds just like #1279.

To check if this is the same Chrome bug, you can try my test from [this comment](https://github.com/philc/vimium/issues/1279#issuecomment-64960158):

>If you right-click a link, choose "Inspect Element" from the context menu and then run

>```javascript
var mouseEvent=document.createEvent("MouseEvents");mouseEvent.initMouseEvent("click", true, true, window, 1, 0, 0, 0, 0, true, false, false, false, 0, null);$0.dispatchEvent(mouseEvent);
```

>in the console (you can show it by pressing `esc`), is the opened tab focused? (You might have to enable pop-ups for the domain while you run this test :( )

**Comment by joebadmo** [comment]
chrome beta just updated for me and I'm seeing the same behavior (Version 41.0.2272.35 beta (64-bit))

I've reproduced the above bug in the dev tools as well.

**Comment by dwayneyuen** [comment]
I just updated my Chrome and now the default functionality for me switches to the new tab when opened. Even when mapping to LinkHints.activateModeToOpenInNewTab it still switches to the new tab.

Chrome: Version 41.0.2272.76 (64-bit)
Vimium: Version 1.49

**Comment by smblott-github** [comment]
I think this is #1279.  @dwayneyuen: see the last few comments there.  Will close this as a dup.

**Comment by rrsahuone** [comment]
Packers & movers in Bangalore helps you in moving and shifting everything either it is little or big, large or light-weight, fragile or strong. They cope with everything for practical moving and shifting. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by rrsahuone** [comment]
This procedure is usually regarded daunting for experts but now it has become simple with the help of Bangalore packers and movers.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers in Delhi">Packers and Movers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by rrsahuone** [comment]
Packers movers Bangalore take guarantee that your valuables and products are 100 % safe with well-known companies and it will be shifted to desire position without causing any harm or reduction. Our detailed Packers movers always give superior stage of solutions in comparison to other similar vendors in Bangalore or close by places.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers in Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a>

**Comment by rrsahuone** [comment]
Only educated employees is appointed who is well versed in English and other Professional languages. The organization creates sure that all necessary guidelines related to product packaging and moving have already been discussed and explained to appointed employees. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
