### ISSUE TITLE
unable to map <c-n>

### ISSUE THREAD

**Issue by rubic** [philc/vimium#1380]
I've attempted to map Ctrl+n to scrollDown, but Chromium keeps popping up a new window (which is the default behavior):

`map <c-n> scrollDown`

I can assign other keys to `scrollDown` (e.g. Ctrl+x) but not the `n` key.  I've also attempted to `unmap <c-n>` prior to mapping it.

Environment: Version 38.0.2125.111 Ubuntu 14.04 (290379) (64-bit)

**Comment by smblott-github** [comment]
Closing.
This has been added to the FAQ.
