### ISSUE TITLE
Migrate to a testing library that supports asynchronous tests

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#1386]
Much of our code relies on asynchronous chrome APIs, javascript events, etc. when run natively. Currently, with [shoulda.js](https://github.com/philc/shoulda.js/), we have to hack code into running synchronously with intrusive stubs. (This is especially obvious when trying to test the Vomnibar in an iframe, as in e33df51c6d1f870e19461ed9941c48dd07b4c68e.)

I propose we migrate to a framework with async capabilities like [CasperJS](http://casperjs.org/), with a view to implementing chrome APIs properly(-ish) and essentially simulating the extension in PhantomJS.

Being able to move beyond our current 'dom-aware unit test'-style tests towards a simulated extension has a few major wins:
- testing that we gracefully handle race conditions.
- testing async actions such as scrolling (and behaviour on key repeats, etc.).
- separate test cases for issues such as #1245, to automatically test our attempted fixes and to ensure we don't regress.
- testing user-facing output rather than implementation details, so we can write higher-level tests.

@philc shoulda.js was your brainchild, what do you think?

**Comment by philc** [comment]
Async testing was introduced in shoulda.js awhile back, so now we're good!
