### ISSUE TITLE
Open links won't work with different language input method 

### ISSUE THREAD

**Issue by vans239** [philc/vimium#1387]
I have multiple layouts: english and russian.  I can use almost all functionality of vimium extension with russian layout and mapping. But i can't choose links by letters from another layout (no mappings). 
Please bind shortcuts to actual physical keys or create mappings for letters

**Comment by kapsh** [comment]
I second this, it's annoying. Vrome (vimium's analog) doesn't have such problem even in link hinting mode (but it has many other bugs, so I choose to return to the Vimium).

**Comment by grey0ne** [comment]
I also have this problem. And for me it ruins all the experience of using vimium.

**Comment by smblott-github** [comment]
There seems to be no issue putting non-English characters into link hints:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/6966086/411fd840-d94e-11e4-8f18-fdf71e5a7d6b.png)

Is the problem that these are then not recognised when the keys are pressed?  If so, then the issue might be solvable by moving the character handling from `keydown` to `keypress`.

(I only have a UK keyboard, so I'm not sure how to test this.)

**Comment by grey0ne** [comment]
@smblott-github It seems to me, that displayed symbols is not the problem. Actually, having only english symbols displayed is even better for recognition. Probably, Vimium somehow should "ignore the layout" in this mode.

**Comment by grey0ne** [comment]
Sadly, fix #1722 doesn't solve the issue. Programmers, who use non latin layouts constantly switch layouts. If i define, for example, russian characters for link hinting, i will again need to switch back to russian layout half of the time. Solutiion for this is keymap for link hinting, same as for commands.

**Comment by rrsahu** [comment]
The procedure becomes more irritating when it comes to shifting sofa, wardrobes, and other large furnishings. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by rrsahu** [comment]
Sometimes, when individuals are not getting any practical moving option, they are leaving products on the same position and buying everything new when shifting to other position.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers Delhi">Packers and Movers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>

**Comment by rrsahu** [comment]
Can you afford this loss? Obviously not! Here, we are ready to help you with outstanding moving options. It is simple to get in touch with us. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers Chennai">Packers and Movers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers Noida">Packers and Movers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers Navi Mumbai">Packers and Movers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers Thane">Packers and Movers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers Ghaziabad">Packers and Movers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers Faridabad">Packers and Movers Faridabad</a>

**Comment by rrsahu** [comment]
You can either drop us a mail or get in touch with us through phone now. The next issue is about how to get provides from certified suppliers only.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>
