### ISSUE TITLE
Find into text area then non-vimium keys broken

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1415]
Use find or `n` to get to a situation that looks like this:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/5628734/34accc88-95a3-11e4-8b8b-1f2c92f52937.png)

(the selection is in a text area, or similar).

Type `j`, `k`, `j`, `k`.  Nothing happens.  That's good, you're in normal mode, as you're supposed to be.

Now type any unmapped key (I used `a`).  Oops, we're actually in insert mode too!  It's not useful to be inserting text into a text area, but only have some keys available.

~~This is hard to fix.~~  The source of the problem is this [trick](https://github.com/philc/vimium/blob/master/content_scripts/vimium_frontend.coffee#L724), which prevents us dropping into insert mode.  However, there's no memory of what happened.

(This is fixed in #1413.)

Edit: On reflection, it's not so hard to fix.  It requires (yet) another state variable and a blur listener.

**Comment by mrmr1993** [comment]
Disputing this issue; if the user presses a key that they don't expect us to handle, we shouldn't handle it.

Also, 'fixing' creates some wonkiness:
* We've given the user a selection that they can only look at &mdash; they can't do *anything* to it with the keyboard until they hit `esc`. Specifically,
  - changing the selection with `shift` and a direction doesn't work,
  - copy/paste with keyboard shortcuts doesn't work, and
  - any actions (which may want to use the selection) that other extensions/the page have bound to keys we don't handle don't work.
* We suppress browser keyboard actions using `f1`-`f12` (and possibly some others).

I vote for this issue to be closed as invalid.

**Comment by smblott-github** [comment]
@mrmr1993. You make reasonable points.  Obviously it's a close call.  Try this argument.

Option 1. Pass unmapped keys through in this situation (the status quo).
Option 2. Block them.

Imagine the status quo was Option 2, and someone proposed changing it to Option 1.  How might such a proposal be received?  I guess we'd think it strange.  Pass through `a` and `s` from the middle row, but nothing else?  And a few select keys from the other rows, but not the others?  That's a pretty weird UX.

In fact, we could even do the experiment.  Head on over to the vim forums, and propose that unmapped keys should be inserted into the buffer...

With Option 1, recovering after a goof is pretty ugly:
- delete the unwanted keys, replace with whatever is in the selection, `Escape`

That's a pretty bad UX too.

**Comment by smblott-github** [comment]
There's also an Option 3:
- When the user enters an unmapped key, drop them into insert mode.

That way, recovery is easier.  Currently, if I search for `orange`, then accidentally hit `a`, the selection is removed an `a` is inserted. Darn!.  I'll just retype it, `o`, blast! That's the vomnibar....

With Option 3, I just retype it and I'm done.  (I know, I could use `Ctrl-V`, if I remembered to).

I'm guessing nobody would advocate Option 1 if it weren't the status quo.

**Comment by mrmr1993** [comment]
> ... Option 3:
> * When the user enters an unmapped key, drop them into insert mode.

This seems nearly right. In going to advocate for Option 4:
* When the user enters an unmapped key, pass it.
* If an `input` event fires on the element, drop into insert mode.

This covers us for chrome/page/extension bindings, and drops us in input mode *only if we input something*.

**Comment by smblott-github** [comment]
> In going to advocate for Option 4

Say we have CodeMirror running in a `textarea`, and a search happens to land there.  We press `s`, not a Vimium key, but a CodeMirror key.  However, it generates no `input` event, so we don't drop into insert mode.  But the CodeMirror state *has* changed.  That's weird too, just as weird as Option 1. Although a lot less common.

Also, with 4, the behaviour is different depending upon some detail of the input in which we happen to land. `s` triggers insert mode in some inputs, but not in others.

But these are corner cases.  The two easy options for the user to understand are 2 and 3.  I prefer 2.  I don't find myself wanting to use `a` or `s` to trigger insert mode.

**Comment by mrmr1993** [comment]
> That's weird too, just as weird as Option 1.

Now I think about it, this is true. It's probably even weirder.

> The two easy options for the user to understand are 2 and 3.

Option 2 takes away some reasonable functionality we already have, for a net gain of... what exactly? If the user isn't typing a key that we handle, they're clearly not expecting us to do anything with it, so we should just get out the way and let other code handle it.

I'm happy to put my support behind 3. It looks like an improvement on the current status quo.

**Comment by smblott-github** [comment]
> Option 2 ..., for a net gain of... what exactly?

For me, the common use case currently is: find into a text area, fumble the "a" key, trash the selection, and emit an expletive.

Option 2 means fewer expletives.  That's a win.
Option 2 never trashes the selection unexpectedly.  That's a win too.

Option 3 is better than the status quo, but still expletive laden.

**Comment by mrmr1993** [comment]
> For me, the common use case currently is: find into a text area, fumble the "a" key, trash the selection, and emit an expletive.

I can see this, but we don't don't do this for anything else, so it feels a bit inconsistent. For example, I often use `1x` on reddit to close the tab (since `x` is a passkey for me), and sometimes I accidentally `11x` instead, followed by similar despair and expletives.

I don't want to trash functionality to mitigate user error, can we make 'strict Vimium mode' an option instead?

**Comment by smblott-github** [comment]
The same problem we've been discussing here also arises as follows:
- Enter insert mode on a content-editable element, either by clicking or with `gi`.
- Hit `Esc`.
- Similarly, you're both in normal mode and in insert mode.

In this case, Option 2 looks best, because the user specifically asked to leave insert mode.

**Comment by mrmr1993** [comment]
I've thought about this some more, and would like to propose a few variants on Option 4.

Option 5a:
* When the user enters an unmapped key, run `DomUtils.suppressPropagation event`. This
  - stops page listeners from running (so nothing really weird happens), and
  - lets native events still run, so copy, paste, arrows and shift, delete, function keys etc. all work as expected.
* If an `input` event fires on the element, drop into insert mode.

Option 5b: same as Option 5a, except
* If the unmapped key is a printing character, run `DomUtils.suppressEvent event` instead, so printing characters don't modify the input *or* get passed to page listeners.

(Note: We can still paste from Option 5b, so we'd still want the `input` event.)

Option 5c: same as Option 5b, except
* If the selection has been cleared when the `keyup` event fires (eg. by using the arrow keys without holding shift), drop into insert mode.
  - This means that we are never in normal mode when the user has a caret, which seems fairly sensible.

What do you think @smblott-github?

**Comment by smblott-github** [comment]
Part of me thinks don't over-engineer a corner case.  But the use case with paste is quite compelling.

Can you not just do 5c, but *without* the `input` listener?  If the selection changes, you're into insert mode.

**Comment by mrmr1993** [comment]
> Can you not just do 5c, but *without* the `input` listener?

Of course, I hadn't considered that the caret detection would make the `input` listener redundant! I think this is the way to go; it's quite powerful and really not very complicated

**Comment by smblott-github** [comment]
OK.  We're agreed.

I've tried this out in #1413 (7684019cb5d5c1d0ac5d7216653613220b4fd8d9, dev branch).  It works very nicely.

**Comment by mrmr1993** [comment]
> I've tried this out in #1413

Your implementation there doesn't implement 5c, since it exits on all selection changes. This makes e.g. extending the selection with shift+arrow keys, copying it with ctrl+c and then changing tab with `J`/`K` not work, when it should under 5c.

I note that any kind of input will completely clear the selection, so unless we're looking to explicitly stop the user from resizing the selection, we only need to check that the selection is still a range.

You can try an implementation that matches 5c from [my branch](https://github.com/mrmr1993/vimium/tree/modes%2B1415-fix) (relevant commit: 38b73a5f7a46b1d7685a8dffc3badb5b3e6ad368).

**Comment by smblott-github** [comment]
Sounds better!
