### ISSUE TITLE
We're no suppressing the keyup event for Escape

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1416]
From discussion in #499, @ZombieHippie put together this [demo](http://codepen.io/ZombieHippie/pen/zxoXwW).

Focus the input (bottom left) and press `Esc`.

We're not suppressing the `keyup` event.

**Comment by ZombieHippie** [comment]
I'm not seeing this issue on my version of Vimium(1.49) and Chrome(39).

Interestingly enough, I remember attempting to solve my CodeMirror problem
by detecting the keyup event (
https://github.com/codemirror/CodeMirror/pull/2245), but then I reallized
it was Vimium.

But I don't think that applies to my version of Vim and Chrome. Maybe
Chrome doesn't fire the keyup event if the keydown event is cancelled.

**Comment by smblott-github** [comment]
OK. Thanks, @ZombieHippie.

Closing. `master` is fine.  It's something in my dev branch.

**Comment by mrmr1993** [comment]
It was a typo by me, your fc2201b996e47ca06090e10e4ebfcd9f4b345fde should fix this.

**Comment by smblott-github** [comment]
> It was a typo by me, your fc2201b should fix this.

Yes.  Unfortunately, I reintroduced it in #1413.

The same bug is [here](https://github.com/philc/vimium/blob/master/content_scripts/vimium_frontend.coffee#L808), too.
