### ISSUE TITLE
Shift-modified number keys aren't passed to the page even if we don't handle them

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#1417]
Currently `KeyboardUtils.getKeyChar` doesn't check the `shiftKey` attribute of the key event for number keys, so it returns `1` for `!`, `2` for `"`, etc. We end up blocking these keys that we will never handle ourselves based on this wrong information. This also means that our `g$` mapping working is a complete fluke; we accept `$` because we want to handle `4`.

This is closely related to #1411. [Chromium issue 227231](https://code.google.com/p/chromium/issues/detail?id=227231) should make all this pain go away.

**Comment by dragon788** [comment]
This makes me really sad, because I have been throwing all the Gmail special
characters for managing my email into my .vimiumrc and was wondering why # wasn't working for delete and @ didn't work for archiving.

**Comment by mrmr1993** [comment]
[Chromium issue 22731](https://code.google.com/p/chromium/issues/detail?id=227231) did indeed make all this pain go away. Closing.
