### ISSUE TITLE
Travis test failing

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#1419]
Tests are failing in travis on current master:
```
$ cake test
Running unit tests...
Pass (131/131)
Running DOM tests...
Error: Cannot find module 'util'

  phantomjs://bootstrap.js:289
  phantomjs://bootstrap.js:254 in require
  /home/travis/build/mrmr1993/vimium/node_modules/path/path.js:28
  /home/travis/build/mrmr1993/vimium/node_modules/path/path.js:522
  /home/travis/build/mrmr1993/vimium/node_modules/path/path.js:523
TypeError: 'undefined' is not a function (evaluating 'path.dirname(system.args[0])')

  ./tests/dom_tests/phantom_runner.js:35
  ./tests/dom_tests/phantom_runner.js:60
```

Compare [here](https://travis-ci.org/mrmr1993/vimium/builds/46269081) (a copy of master on my fork) to [here](https://travis-ci.org/philc/vimium/builds/46035786) when the last commit was pushed yesterday.

**Comment by smblott-github** [comment]
What do you think the issue is, @mrmr1993?  Is it Travis' configuration?

Tests work for me...

```
Script started on Thu 08 Jan 2015 06:16:56 GMT
$ git fetch upstream
$ git checkout upstream/master
HEAD is now at 30dee76... Merge pull request #1407 from smblott-github/post-1.46
$ cake test
Running unit tests...
Pass (131/131)
Running DOM tests...
Pass (31/31)
$ 

Script done on Thu 08 Jan 2015 06:17:42 GMT
```

**Comment by mrmr1993** [comment]
Tests work locally for me too.

> What do you think the issue is, @mrmr1993?

Not really sure. Looks like something has gone wonky with the 'unit' module. Possibly an update that depreciated it? I'll try and repro this locally later.
