### ISSUE TITLE
shift+j and shift+k do not work on facebook

### ISSUE THREAD

**Issue by acohan** [philc/vimium#1422]
While on facebook, you cannot change tabs by using shift+j or shift+k.

**Comment by smblott-github** [comment]
I'm not seeing this.  Is there a specific page on Facebook, or is it the whole site?

**Comment by acohan** [comment]
The whole site. https://www.facebook.com/

**Comment by djds23** [comment]
I am able to change tabs using shift+j & shift+k in OS X 10.10/ Chrome Version 39.0.2171.99

Perhaps there are more steps to reproducing the issue?
