### ISSUE TITLE
Cannot enter insert mode by clicking when focusInput is active.

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1423]
With `focusInput`, like this...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/5677198/b1cddbe2-97da-11e4-84d4-0c48d273428d.png)

Clicking on either input does not take us into insert mode.

Obviously, the click is being delivered to the overlay.  But it's a weird UX nonetheless.

**Comment by mrmr1993** [comment]
Fixed in #1258 (by setting `pointer-events: none;`).

**Comment by mrmr1993** [comment]
Sounds good, thanks Steve

**Comment by smblott-github** [comment]
> Actually, we should put just that line in master.

Done: 75565049e160042017486c10a61bed3a292e0c58 is in `master`.
Closing.
