### ISSUE TITLE
HTML buttons are getting selected instead of being clicked

### ISSUE THREAD

**Issue by vdudouyt** [philc/vimium#1428]
Hi,

I'm using Vimium for the years, and today I mentioned that it doesn't clicks on form buttons after tapping 'f' and typing a hint anymore. Instead of that, the buttons are just getting focused. So now I have to proceed with all following steps each time when I'm about to navigate forward:

1. Realize if I'm going to click a button or <a href> link
2. Tap 'f'
3. Type a corresponding hint
4. Hit 'Enter' if it's a button

Personally, I'm finding this behavior very frustrating.
Is it a bug or was it added intentionally? And is there a way to reduce this to steps 2 and 3 like in old good Vimium? I'm using the latest version from Chrome Store, and couldn't find anything like that in the settings.

Thank you very much for your time! Looking forward to hear from you!
Valentin

**Comment by smblott-github** [comment]
Where are you seeing this?  Can you give a specific example?

**Comment by vdudouyt** [comment]
Sorry, I forgot to mention that it only reproduces for the submit buttons. You can find a specific example on http://www.w3schools.com/html/html_forms.asp (navigate to 'The Submit Button' section and try clicking it with Vimium).

**Comment by smblott-github** [comment]
You mean [here](http://www.w3schools.com/html/tryit.asp?filename=tryhtml_form_submit)?

Seems to work for me...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/5717356/594fc5c8-9af7-11e4-847c-833080e68a9f.png)

**Comment by z0rch** [comment]
I can confirm it does repro in latest Chrome Store build, and it does not repro in latest `master`. So, @vdudouyt, it will be fixed for you when a new build comes to the Chrome Store.

**Comment by mrmr1993** [comment]
I thought we'd already pushed the fix for this. @philc, is there any chance of pushing version 1.50 at 09f8527915eae8067072277e2b161493ede359cd?

**Comment by smblott-github** [comment]
Closing.
Assuming fixed.
