### ISSUE TITLE
A rect flashed by LinkHints may is too smaller

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#1444]
Says there is a link: `<a href="#"><em>JK</em><i>RL</i></a>`.
Then `LinkHints` will compute its client rect and get `[0,0,17,16]`. That is, a rect of the first child "em" will be computed.
It's because `DomUtils.getVisibleClientRect` calls `element.getClientRects` and then returns the result array's first item.
(I tested some different versions of Vimium, all did just like the above.)
So, If something passed to `DomUtils.flashRect` can be better ?

**Comment by smblott-github** [comment]
Thanks, @gdh1995.  Can you work through why this is a problem?  Do you know of an example site where this comes up?  What happens?  What would you like to happen?

**Comment by gdh1995** [comment]
There is a typical example: `<a>I am an <span class="...">example</span> of link</a>`.
Search engines usually generate links like this: `span` is used to highlight matching characters.
Then, `LinkHints` will create a flashRect enclosing `its first nodechild` which is only `I am an`.

What I expect is a rect wide enough to enclose all of the link's visibie area.

It seems `getBoundingClientRect` just create this, but I'm not sure if there was anything inappropriate.

**Comment by gdh1995** [comment]
Sadly I've done some tests and convinced myself that sometimes no perfect rect can be get by calling `getBoundingClientRect`.

Then, closed.
