### ISSUE TITLE
Evernote. Duplicate link hits

### ISSUE THREAD

**Issue by MaikoID** [philc/vimium#1446]
Hey guys, thanks for this extension. I'm using it and thinking its great.

At Evernote I can't use it properly, even with the the old Evernote interface. There are links with duplicate  link hits, or sort of, at the same location. It bothers me in the edit box from the "Notes Description" and I've to use the mouse because I can't identify with label I've to type.

It will be nice if we could develop layers on overlapping link hits with the same group, starting with the same letter. Then you can get rid of this kind of problem.

thanks

**Comment by smblott-github** [comment]
Closing.
Discussed elsewhere.
