### ISSUE TITLE
Evernote. VIMIUM stops working after edit a "Notes Description"

### ISSUE THREAD

**Issue by MaikoID** [philc/vimium#1447]
Hey guys, I'm having this problem with the Evernote web interface. After I choose to edit a note I can't get the vimum working again.

**Comment by smblott-github** [comment]
Thanks for the report, @MaikoID.

My first thought was that this was related to this fix (#1247) to this problem (#1245).  However, while it might indeed be related, there appears to be more at play.

Our event handlers aren't seeing keyboard events *at all*!  Not sure what to look next...

Does anybody have any ideas?

**Comment by smblott-github** [comment]
Closing.
No response from OP.
