### ISSUE TITLE
Remove "programming commands" from Help Page

### ISSUE THREAD

**Issue by esster** [philc/vimium#1450]
I am used to similar help pages in gdrive and gmail,

![gmail](http://cdn.appstorm.net/web.appstorm.net/files/2009/11/shortcut-overlay-1024x503.png)

and I would consider it insane, if they, just for "fun",
listed, added the underlying programming commands,
for my "information", to their help pages,

it is, it would be, I exaggerate, of course, a USABILITY nightmare,

but, of course, because you can customize, and remap
the key bindings, it makes total sense, to

combine both use cases, in an elegant and "holistic" way
into one:

show me all available mapping commands,
"I want to program, remap my keys"
and show me the active, current key bindings
"I forgot ..., I want to know what I can do",

and isn't it confusing for a user,
looking for what he can do,
to see an entry with a function description
and no KEY attached to it?

Another point, maybe ":" is not,
from a vim-perspective, where, as you know,
a colon signifies "command-line mode",
the best choice, and as such
unnecessarily confusing ...

This issue has already been raised
by __mrmr1993__, #1280, in a more general way,
and I fully support his contention,
that the help page could be less "cluttered" more
helpful ...

**Comment by dragon788** [comment]
I would contend the "average user" doesn't install vimium. I do think there could be some changes, but more for clarity and a balanced layout, I think linking to the options page and maybe adding the "programming" aspects on as an additional tab to the help page might help, but I don't think every Tom Sam and Sally are installing Vimium.
