### ISSUE TITLE
Future request: Custom hint strings for Web Developers

### ISSUE THREAD

**Issue by mashify** [philc/vimium#1451]
I was wondering if Web Developers could set custom hint strings with a data-vimium attribute on the link. So that some links always have the same hint string and people can more or less navigate blindly if they know the site.
Also links to the same location could be combined by using that future. So the same hint string may appear multiple times but they all do the same thing.

**Comment by gdh1995** [comment]
With `filterHints`, users can type characters in a link's text to filter markers, it's easy to use an attribute to do this, and we may name the attr `data-vim-hint`. But users can not get to know what they should type, unless a text is shown beside a link.

With `alphabetHints`, if doing this, duplicate hints must be prevented, which is hard to implement (just to me).

**Comment by smblott-github** [comment]
Closing.
Niche.  Lack of interest.
