### ISSUE TITLE
Vimium steals focus when typing into address bar

### ISSUE THREAD

**Issue by alexluecke** [philc/vimium#1452]
This should never happen, in my opinion. When using the address bar to search, any words with 'f' or 'i' characters result in unwanted behavior.

**Comment by alexluecke** [comment]
Really? This one is gonna get buried?

**Comment by smblott-github** [comment]
Could you explain *exactly* what you do, what happens, and what should happen, please?

**Comment by alexluecke** [comment]
When using the address bar for typing, say, a Google search. Any word with the vimium hot keys (f, for instance), vimium will hijack the focus and begin showing the URL jump links on the page. Expected action: vimium should ignore any input when the address bar has focus.

**Comment by smblott-github** [comment]
Which address bar?  The Vimium one or the Chrome one?

**Comment by alexluecke** [comment]
Chrome

**Comment by mrmr1993** [comment]
We don't develop or support Vimium for firefox, sorry. This project is for the Chrome extension Vimium.
