### ISSUE TITLE
Should exclusion rules apply per tab or per frame?

### ISSUE THREAD

**Issue by z0rch** [philc/vimium#1453]
Use [this page](http://jsfiddle.net/v0fznbrf/embedded/result/) as a playground.

* Open playground, make sure no passkeys are defined.
* Hit `t` to make sure that vimium creates a new tab.
* Define `t` as a passkey.
* Hit `t` and ensure that `t` is now passed to the page.
* Reload the playground page.
* Hit `t` again.

EXPECTED: `t` is still a passkey, so it is passed to the page.  
ACTUAL: `t` creates a new tab.

* Modify the passkeys, for example add another character there.
* Now `t` is passed to the playground page again, until the next refresh.

------------------------

I wonder if you can reproduce this, or something is wrong with my setup. I think it is used feature, that's why I'm concerned that nobody reported it yet.

Windows and Linux, `philc/master`.

**Comment by smblott-github** [comment]
Nice.  It's not actually a passkeys issue, you get the same effect in 1.42 setting the page as an excluded site.  The exclusion rule applies to `jsfiddle.net`, but the page contains an iframe from `fiddle.jshell.net`.

I'd say this is actually the correct behaviour, and what's wrong is that we're proposing the wrong pattern in the page popup.

**Comment by z0rch** [comment]
Thanks for looking into it! 

So this actually uncovers a bigger problem, how to treat multiple iframes with our passkey popup. I'm going to rename this issue then.

As a user, I never know how many iframes are in the current page. But if I want to create a passkey, I probably expect it to work on the entire page, no matter if I'm inside an iframe or outside.

Can you think of an example, when we would like to be more granular, and define different sets of passkeys for different iframes inside a single page?

**Comment by smblott-github** [comment]
> Can you think of an example, when we would like to be more granular, and define different sets of passkeys for different iframes inside a single page?

Yes.  The hangouts frame on Google's Inbox.  Within the main frame, `j` and `k` are passkeys (for me).  If I select the hangouts frame, `j` and `k` scroll. This seems to be the right behaviour, in this particular case.

That being said, this "feature" was introduced (unintentionally) in #1413.  I'll fix it.

**Comment by z0rch** [comment]
I'm curious which approach you are going to take. List all possible frames in the popup? Then it must be easy to understand, which line in popup corresponds to which part of the page.

By the way, you may recall that Google Inbox has ~20 frames, and only 2-3 of them are actually visible. We have some extra logic for `gf` to skip invisible frames, it may be interesting to reuse it.

**Comment by smblott-github** [comment]
Actually, this wasn't introduced in #1413, it's in 1.49.  And it's not specific to passkeys, it's legacy exclusion rules too.

Go to the jsfiddle test page, *completely* disable vimium (no passkeys, no nothing), reload it if you like (it makes no difference), click in the frame so it gets the focus, and `o` opens the vomnibar.

You might change the title to something like *Should exclusion rules apply per tab or per frame?*.

**Comment by smblott-github** [comment]
> List all possible frames in the popup?

Definitely not!  This needs some thought.  Doing nothing is one option.  Nobody's even noticed

**Comment by z0rch** [comment]
> Doing nothing is one option. Nobody's even noticed

Perhaps you are right, I think we can even close this issue as of now and spend time on other things. We can always reopen it and give some thought when it becomes important to anyone. Agree?

**Comment by smblott-github** [comment]
> I think we can even close this issue as of now

Suggest just leave it open.  It does no harm.  Maybe somebody else will chip in with some useful insight.

**Comment by mrmr1993** [comment]
Responding to a comment *way* back:

> what's wrong is that we're proposing the wrong pattern in the page popup.

Suggest expanding the popup slightly, by adding radio buttons that toggle between showing passkey info for the URL and passkey info for the focused frame. Defaulting to frame, since the user will usually open the popup to modify passkeys for their current context (too see why/change that a key is being passed or not). It's also probably a good idea to show the frame URL somewhere in it, in case the user wants to have the passkey active only on that frame's URL.

**Comment by smblott-github** [comment]
Closing. See #1534.
