### ISSUE TITLE
Abide by the style guide, have coffeelint automatically check code on compile

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#1458]
It would be good to update the code to match the [style guide](https://github.com/polarmobile/coffeescript-style-guide) mentioned in CONTRIBUTING.md. Since that link has a coffeelint configuration file, it would be easy to add our tweaks and automatically lint code at compile time/on Travis, so that we can have consistent style going forward.

Edit: See #1135 for my attempt at this (code has drifted, so there's a merge conflict).

**Comment by philc** [comment]
Good idea -- this seems like an easy productive win.

**Comment by mrmr1993** [comment]
The commit (22ffaab) for adding the tests and the style guide should still merge with very little difficulty, if this is something we want to get in the codebase.

**Comment by philc** [comment]
Closing, as we no longer use coffeescript and the current JS codebase conforms to `deno fmt`.
