### ISSUE TITLE
Wrong link description in "Open URL" popup.

### ISSUE THREAD

**Issue by robsonq** [philc/vimium#1466]
I'm not sure if it's a bug or intended feature, but when I use O key in normal mode and type some keywords for site - for example "reddit linux": 
![example]
(http://i.imgur.com/Muj34gg.png)
When I choose SECOND link in list it still open more specific link (in this example this: http://www.reddit.com/r/linux/comments/2uyupl/gnu_privacy_guard_on_twitter_just_got_the_okay/) 

It makes O option almost unusable since I always land on site that i didn't meant to...

**Comment by smblott-github** [comment]
@robsonq.  I can't reproduce this in `1.49` (the current chrome store release) or `master`.  How are you choosing the second link? Tab? Ctrl-J?

**Comment by robsonq** [comment]
@smblott-github
All ways of navigating in that list didn't work as intended (arrows included). 
I have 1.49 (from chrome store). 

I'm gonna include my system specifics
- User Agent
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36
- System
Arch Linux 64bit
- Browser
Chromium 40.0.2214.94

**Comment by robsonq** [comment]
@smblott-github
UPDATE: I just wanna point, that this bug is not present on latest version of Chrome. Chromium is affected.
