### ISSUE TITLE
How to handle entering visual mode....

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1467]
#1441 implements visual mode (and is now merged).  How should we handle entering visual mode?

Currently, when we enter visual mode:
- If there is an existing selection (including a collapsed selection), and the selection is in the viewport, then we use it.
- Otherwise, we enter caret mode, selecting the first non-whitespace character of the first visible text node (with 50 or more characters).  Usually, this skips banners and puts the caret near the top of the viewport (which is good for`/`).

This works ok-ish.  However, there are issues:
- It is possible for the caret to become trapped because character-wise selection operations cannot move over certain elements (e.g. inputs).
- The route from the initial position to the position the user is looking for can be odd (e.g. on the BBC News web site, it often takes a short side trip through some side-bar material).
- It can take a lot of tapping on `j` and `w` to take the user to where they want to be (it would be quicker just to use the mouse -- @z0rch's point from #1441).

Personally, I'm not convinced that caret mode is helping at all.  It's clumsy.  The way I find the text I'm looking for is with `/`.

Suggestion 1:
- Ditch caret mode.
- Require there to be a pre-existing selection (typically established via `/`) on entry to visual mode.

Suggestion 2:
- Ditch caret mode.
- If there is no pre-existing selection on entry to visual mode, then automatically launch *viewport find mode* (see below) to allow the user to establish the selection.

Suggestion 3:
- Keep caret mode.
- `/` within visual mode launches *viewport find mode*.

Viewport find mode:
- The same as normal find mode (and not labelled differently to the user), except...
- A collapsed selection is first established at the top of the viewport.  Therefore, matches above the viewport are found only if the search wraps, and matches within the viewport are favoured.  This is (I think) similar to @z0rch's idea from #1441, except that the search is not restricted to only the viewport.

My view?  In order of preference, 2 then 3 then 1.  All are better than the status quo.  But it's a close call between 2 and 3.

**Comment by z0rch** [comment]
2 -> 3 -> 1 is what I prefer as well.

**Comment by rajeevksahu** [comment]
We do their best to satisfy our clients. We take your believe in as our liability. Your whole baggage will provide to you without harming it. We use best content to package delicate items so there are no chances of damage. We also provide features to transportation digital items like refrigerators, computers, units, television, air conditioners, etc.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
Most often, we all prefer to shift to some remote locations and in such situations, this is really difficult to shift large components. Fragile product belongs to us are very useful but their moving is very difficult. But now, Movers packers Mysore transportation all that delicate components without only one the begining. This large items definitely charge for additional payment but at least you get 100 secure and secure deliveries.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
Shifting and moving agencies expenses additional according to the specifications of clients. Delicate items need some additional attentions and how movers and packers help us. Packing Moving Mysore is now simple. Now remote place moving is not a big process as you do not have to shift all the loads alone.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
Transportation we provide to provide such sensitive product is of best type. Our group is so devoted and accountable to their perform that they do not allow even only one the begining over you fill. We use best technology to finish our perform. We have automobile providers to provide all types of automobiles like truck, bikes, and scooters, etc. unique type of car providers are used by us, so that there is not even only one the begining while moving and moving.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by smblott-github** [comment]
Closing.
I think we should leave this as is.
Seems to work ok in practice.

**Comment by aemonge** [comment]
I disagree, I would love to have a find in current visualized page only. Most of the times the text I'm needing to copy has repeating words all over the page, so when I start the find to copy and paste, it's scrolls me all the way to the top and normally I loose the text i wanted to copy.

So I usually use the mouse, therefore I think we can get the feature back on the hipe :)

**Comment by politicus** [comment]
So glad I red your comment @aemonge as your second sentence perfectly sums my thoughts up. 

Why not take as a starting point of reflexion, the user ONLY wants to select a piece of text that he can see?  

Therefore no scrolling. No mouse. No time wasted.

I do not see any use case for me, the user, being willing to select a piece of text that is not visible from the me and is a duplicate of the content I have in front of my eyes. 

But I might be wrong.
