### ISSUE TITLE
How to handle exiting visual mode...

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1468]
As discussed in #1441, there are issues around what to do with the selection when we exit visual mode.

The status quo:
- When we exit visual mode (via `Esc`, `y`, `Y` `p`, `P`, or `Enter` -- these are, I think, all cases), we wholly remove the selection.

As @mrmr1993 pointed out in #1441, there are use cases where it could be useful to retain the selection:

> I would suggest keeping the selection, which would enable a few things:
> - running a bookmark in the Vomnibar that uses the current selection
> - click a link with link hints on the page that does something with the selection (eg. make text bold)
> - trigger a page shortcut using the selection (eg. r here to quote the selection to use in a reply)
> - scrolling the page (looks like, from the code, automatic scrolling to the selection point might still be a bit sticky)
> - use the selection as the base point for the next search (this may happen anyway, I'm not in a position to test anything at the moment)

For a while, #1441 implemented (approximately) the following:
- Remove the selection in all cases except `Esc`.
- For `Esc`, retain the selection, but clear it on an immediate further `Esc`.  (So, `Esc`, `Esc` clears the selection.)

I believe this was @mrmr1993's idea.  It works quite nicely if you know about it.  However, unfortunately, there's no particular reason for a user to suspect that a subsequent `Esc` will clear the selection.  @philc was tripped up by this.

What should we do?  Any other ideas?

**Comment by mrmr1993** [comment]
> What should we do? Any other ideas?

Add a command to visual mode that clears the current selection and exits the mode, with `<esc><esc>` listed as (one of) the bindings?

**Comment by rrsahutwo** [comment]
There are a lot of residents here. A large variety of nonresidents of Coimbatore come here to shift every year from all over the nation. We at EXPERT Packers provide many such types of alternatives which assist the people to shift here comfortably. Whether you are coming here or you are going outside in any aspect of the nation, we help you in moving qualities to your new place securely and securely. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
We do not only help you take your items, but also help you strategy a finish process with timing. It means that we frame the finish process of moving to the new place. We make sure the highest level of reliability, commitment, protection in our alternatives to shift your items. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
We prominently provide finish assistance for packaging your useful items and then for moving and moving your items. You may think that moving is time-consuming affair and is a process full of pressure and issues, but with the assistance of Coimbatore packers and movers, this tedious process seems to be very enjoyable. With the assistance of most trustable movers, EXPERT Packers, your perform of transferable process will seem to be very simple, convenient, secure and also cost-effective.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
EXPERT Packers have expert employees and qualified employees in its devoted group which can efficiently handle all actions of the moving your qualities with your close relatives in a well- planned way. We provide a range of most efficient alternatives at affordable price to create our clients relaxed. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
