### ISSUE TITLE
Does visual mode need custom key mappings?

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1469]
#1441 implements visual mode.

Status quo:
- All key mappings (`j`, `k`, `w`, etc) are hard-wired into the code.
- The user just has to guess as to what movements are available (although we do have a fair selection of the most basic movements, such as `3)` or `2e`).

The case *against* custom key mappings:
- They're not needed!
- Few users remap the basic movements in vim, so we would be adding an extra layer of complexity for very little payoff.
- Even users who do remap the basic movements are used to occasionally firing up `vi` and dealing with the native bindings.

The case *for* custom key mappings:
- Non-English, non-latin-alphabet keyboards.  Probably non-QWERTY keyboards too.
- Edit: It's odd to *not* have custom mappings, when we have custom mappings elsewhere.

The case *against* is pretty strong if you're a QWERTY-using English speaker.  Otherwise, the case *for* is pretty strong.

Issues:
- We would have to find a way to fit a whole bunch of extra visual-mode commands into the options-page help page.
- We would have to implement a custom help page (for `?`) in visual mode.

For the record... I'm a QWERTY-using English speaker (:wink:).

**Comment by Darksonn** [comment]
As for me, I definitely want custom keybindings for visual mode. I use colemak and the default bindings for movement are pretty akward to use.

**Comment by emallson** [comment]
Gonna chime in here and agree with @Darksonn. I use colemak and using hjkl is incredibly awkward. I can, but it's quite annoying.
