### ISSUE TITLE
Provide a way to ignore the current site without having to use the mouse.

### ISSUE THREAD

**Issue by deleteme** [philc/vimium#147]
It's a pretty big inconvenience to have to ignore a random website that doesn't work well with Vimium.

Current flow: Depends on the mouse.

* Realizes there is a problem
* Clicks Extensions from the app menu
* Finds the Vimium extension and clicks options
* Finds tab that has the problem
* Copies URL
* Goes back to Vimium options tab
* Pastes URL then modify it as needed
* Save options
* Go back to tab that has the problem site
* Refresh to restart vimium

It would be nice to be able to add to my ignore list without having to leave the page.

Proposed flow: yy <some ignore shortcut> <paste> <enter>

* Realizes there is a problem
* yy - Yanks URL to clipboard
* <some ignore shortcut> - displays input field
* paste URL and tweak as needed
* enter (Updates ignore list)
* refresh page automatically? or maybe just have vimium know to stop running.

Alternative flows/ideas:

* Display the options in a modal window similar to how ? works.
* or Create an icon to display in the upper right corner that functions similarly to the [FlashBlock addon](http://bit.ly/a9h332).

**Comment by smblott-github** [comment]
Closing.

We have this with the page icon and [this tip](https://github.com/philc/vimium/wiki/Disabling-Vimium#tip).
