### ISSUE TITLE
Where should find mode start searching from?

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1471]
Find mode uses `window.find` to perform the actual search.  The search  starts at the current selection or, if there is no current selection, *then at the top of the page*.

Lately, I've been finding this particularly frustrating.  With visual mode (#1441), the text I'm looking for is right there in the viewport, but `/` goes off to the top of the page.  Sometimes, it takes `n` (many times)
and a lot of patience -- just to get back to where you started.

Proposal:
- If there is no existing selection, then `/` should *always* start at the top of the viewport.

This would change the behaviour of `/` for other use cases, and is not how chrome's native find works.

Any opinions for or against this?
@philc: This is the type of UX change that you sometimes have strong views on.

This is related to #1467.  However, the proposal here is that `/` should *always* behave this way, not just within the context of visual mode.

**Comment by ryrych** [comment]
Hi @smblott-github!

Have you found any solution for that?

**Comment by smblott-github** [comment]
@ryrych... It can be fixed very easily.  Visual mode sets works this way.

**Comment by smblott-github** [comment]
Oops.  Posted the previous message before I'd finished editing.

The question is, whether folks would find it acceptable if normal find mode worked in that way.
