### ISSUE TITLE
Custom Search Engine Conflicts with Omnibar

### ISSUE THREAD

**Issue by RobertCompton** [philc/vimium#1472]
Relatively recently, the custom search engine broke. For instance, if I have the following CSE:
#duckduckgo
ddg: https://duckduckgo.com/?q=%s

and I query the Vomnibar with "ddg this is my query", it used to work correctly. Now instead, it searches on Google the generated URL (in this case, "ddg: https://duckduckgo.com/?q=this is my query"). Pretty sure this is caused from Chrome mistaking the URL as a search because of the white space.

I think that the query should generate the URL and automatically replace the white space with plus signs.

If there is a temp fix around this for Chrome, that would be great as well. Perhaps simply disabling the omnibar is the answer...

**Comment by smblott-github** [comment]
Hi @RobertCompton.  Thanks for the report.  I think we caught this already.  See #1334 and #1384 (which is merged into `master`, but not yet released).

No workaround, I'm afraid.

**Comment by gdh1995** [comment]
If you paste " https://duckduckgo.com/?q=this is my query" to Chrome's omni bar, it will open a new tab with such a url.
Do you mean Chrome open a tab and use Google to search a string of "ddg: https://duckduckgo.com/?q=this is my query"? If so, it's indeed a bug of Vimium (but I haven't find it in my computer)

**Comment by smblott-github** [comment]
> If so, it's indeed a bug of Vimium

It's a bug.  It's been fixed, and the fix will be in the next release.
