### ISSUE TITLE
Vomnibar closing visible/late after changing tab

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1485]
This is one for you, @mrmr1993.
- Use `O` or `B` to open a new tab.
- Return to the original tab.
- Briefly, the original vomnibar is visible.

Might this be fixed by adding a short delay (a la `nextTick`) before opening the new tab?

**Comment by smblott-github** [comment]
Well, b08508470f84c0a4202a63353934405ba2f1faa7 fixes this issue, but is not entirely satisfactory.  It would probably better if the UI Component framework had a way to invoke a callback once the UI has been removed.  Then, `setTimeout callback, 0` might work.

**Comment by mrmr1993** [comment]
> It would probably better if the UI Component framework had a way to invoke a callback once the UI has been removed.

Okay, I'll get on that when I get home.
