### ISSUE TITLE
Vimium page icon showing disabled when enabled

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1487]
I'm seeing an intermittent issue whereby the page icon is showing disabled when Vimium is in fact enabled.  I tried 0aa6a115c518d9412b752d79f6dea7ca87f7d254 a few days ago, but that didn't do the trick.  Now I'm trying 0f17a45c288445b4400ccdf67065f5ae56153aa2.  Seems to be happening mainly when a new tab is created.

(The first of those two commits is in `master`, the second is not.)

**Comment by smblott-github** [comment]
I've left this issue like [this](https://github.com/philc/vimium/blob/master/background_scripts/main.coffee#L368) in `master`.  This seems better.  However, there's still a fundamental issue where we sometimes get the badge wrong.  The source of the remaining problem is basically a race condition in how we maintain the icon.

**Comment by mrmr1993** [comment]
This seems to have be fixed by #1534.

**Comment by smblott-github** [comment]
Yes.  Thanks, @mrmr1993.  It should indeed be so,
