### ISSUE TITLE
Suggestion [f/F] Open a link: Don't use F or f as a tooltip

### ISSUE THREAD

**Issue by gavinengel** [philc/vimium#1488]
Just a small suggestion.  I understand that hitting esc turns off the tooltips.  I'd like if hitting the key again turned them off.  For that to work, there shouldn't be a tooltip link with the letter f or F.  

In any case, thanks for your work on this extension.

**Comment by mrmr1993** [comment]
We've had this request several times before (#991, #972, #638, #577), and there is a PR open to change the default settings to provide this option (#1079), but it seems as though @philc is opposed to the idea.

You can get the behaviour you want by removing `f` from the "characters used for link hints" box in the options (and then pressing save).

**Comment by gavinengel** [comment]
Oh I'm sorry, I should have searched!  Thanks!
