### ISSUE TITLE
Can not pack extension. "Could not load javascript 'lib/utils.js' for content script."

### ISSUE THREAD

**Issue by arizzubair** [philc/vimium#1493]
Hi all,
I have been trying to fiddle around with this wonderful extension. But when I try to pack extension in chrome, following error appears:
Failed to load extension from: ~\Downloads\Programs\vimium-master\vimium-master
Could not load javascript 'lib/utils.js' for content script.

Same error appears when I try to load the unpacked extension.

Please don't shout at me if I'm making some noob mistake.
Thanks

**Comment by smblott-github** [comment]
Have you looked [here](https://github.com/philc/vimium/blob/master/CONTRIBUTING.md#installing-from-source)?

**Comment by arizzubair** [comment]
Thank you very much Stephen.

On Thu, Feb 19, 2015 at 5:47 PM, Stephen Blott <notifications@github.com>
wrote:

> Have you looked here
> <https://github.com/philc/vimium/blob/master/CONTRIBUTING.md#installing-from-source>
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/philc/vimium/issues/1493#issuecomment-75042735>.
>



-- 
-Ariz Zubair
