### ISSUE TITLE
setState is not called for pages which are enabled and have no passkeys, doesn't respect frames

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#1494]
The background page messages all frames and

* asks them whether they are enabled, and what passkeys they have (`getActiveState`)
* calculates whether the tab's url should be enabled, and whether it should have passkeys
* messages the frame back if it's current enabled state/passkeys don't match what was calculated (`setState`)

Consequences:
* this request tells the tab whether it is incognito (so only tabs where vimium is disabled/has passkeys know if they're incognito)
* the listener for this request triggers the new `FindModeHistory.init()` function, so some (a lot) of the time `FindModeHistory` is uninitialised.
* ~~frames get the enabled/passkeys state of the top level url, rather than for the url of their frame, which makes very little sense, and is confusing for users.~~ The behaviour is more confusing than I thought: if one frame in the tab changes, then passkeys for all other frames are reset to the passkeys for the top frame. There's also a nice race condition here `checkIfEnabledForUrl`.

**Comment by smblott-github** [comment]
You beat me to this.  I've been looking at it and thinking it's all very odd (and broken) too.  It's related to #1453, too.

**Comment by smblott-github** [comment]
Closing.  See #1534.
