### ISSUE TITLE
github default keybinding conflict

### ISSUE THREAD

**Issue by ipmsteven** [philc/vimium#1497]
Since github has its own keyboard shortcuts, one shortcuts that is pretty useful is [`Press *y* to permalink to a file in a specific commit`](https://help.github.com/articles/getting-permanent-links-to-files/#press-y-to-permalink-to-a-file-in-a-specific-commit).

However, if I enable vimium in browser, the github default keybinding will be override. :cry: 

Is there any work-around that I can keep some github's key bindings working and use vimium at the same time?

**Comment by mrmr1993** [comment]
You can register 'passkeys' for `https://github.com/*` by
* clicking the Vimium icon and
  - entering `y` into the 'keys' box,
  - pressing 'save changes', or by
* opening the options page (via the link in the help dialog, which is accessible via `?`) and
  - pressing 'Add rule' under 'Excluded URLs and keys',
  - entering `https://github.com/*` into the 'patterns' box that was added
  - entering `y` into the 'keys' box that was added, and
  - pressing the 'Save Changes' button at the bottom of the screen.

You can add more keys (currently only single characters work) by entering them into the 'Keys' box in either of those places and pressing the corresponding save button.

To bypass the passkey, you can type `1` before the key that would have been blocked. So `y` will trigger the github action, but `1yt` will run Vimium's duplicate tab command.

Hope this helps!

([The wiki](https://github.com/philc/vimium/wiki/Disabling-Vimium) could probably do with having some of this info added. I'll try to do that when I get some time.)

**Comment by ipmsteven** [comment]
wow, that's exactly what I need, thanks so much @mrmr1993

**Comment by smblott-github** [comment]
> To bypass the passkey, you can type 1 before the key that would have been blocked.

I hadn't realised that that would work!

**Comment by mrmr1993** [comment]
> I hadn't realised that that would work!

I'd assumed it was an intentional feature! I discovered it while I was working on #1275/#1315, I use it a lot. Can I assume that it's something we're planning to keep and mention it in the wiki?

**Comment by smblott-github** [comment]
It was added deliberately, but not for that case.  It was added for the case where `t` is a passkey, but `gt` is mapped to a command.  I knew it would work for `2t`.  I hadn't thought of using it for `1t`.

**Comment by mrmr1993** [comment]
Okay, cool! I'll add it to the wiki when I'm putting the rest of this information there :)

**Comment by rrsahutwo** [comment]
They give best alternatives without striking their commitment. One of the best aspect of choosing best packers and movers, is that they would create you stress 100 % free. You did not have to do any labor after choosing experts. You will encounter totally 100 % free all around you, as you did not have to do their best while moving and moving to your new house or workplace.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
You will get all the perform done promptly. You just have to tell them when to start and finish perform according to your need. If you want to shift all the factors to some remote place, you have to pay additional according to variety of items. Charges they charge are absolutely affordable and affordable.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
Moving or moving to another place can really be an exciting and pleasant factor for people if they seek the services of expert packers movers Coimbatore. The concept of going to the new position fills them with imagination of residing in new environment with new people. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
It seems exciting as they think that they are migrating to a new position where they will enjoy the new place and new atmosphere. But on the contrary, moving from one position to another is bit a hectic affair because you need to shift your qualities with you to the new place. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
