### ISSUE TITLE
Open in new tab sets focus on new tab

### ISSUE THREAD

**Issue by khebbie** [philc/vimium#1498]
If I do a cmd+shift+f which is open in new tab, the browser sets focus on the new tab.
It used to just open a new tab and let me stay on the current page.
I am not sure when this behaviour changed, but it has been so at least for a month.

**Comment by mrmr1993** [comment]
This sounds a lot like #1279. Which Chrome version are you running?

**Comment by chriskjaer** [comment]
@khebbie it should be fixed in the latest Chrome Canary build (I'm using 43.0.2337.0 and it's working again here.)

**Comment by smblott-github** [comment]
Closing.  See #1279.
