### ISSUE TITLE
invisible garbage tag in inline rich html editor (XpressEditor)

### ISSUE THREAD

**Issue by noisia04** [philc/vimium#1499]
1. go to the site which is using “XpressEngine” CMS
2. click [write] button or add comment
3. write some text in the WYSIWYG editor (XpressEditor)
4. check HTML code (click [HTML 편집기])
5. you can find some garbage tag at last paragraph

![image](https://cloud.githubusercontent.com/assets/8155307/6282991/2d390f74-b921-11e4-97a7-e90cd2744488.png)

**Comment by mrmr1993** [comment]
This is going to get worse next version with the `UIComponent` iframes. I don't know what we can do about this. Maybe a new default exclusion rule for XPressEngine's iframe URL (presumably it has one, since we don't inject into `about:blank`/`data:` URIs)?

**Comment by noisia04** [comment]
this problem is getting worse!

![image](https://cloud.githubusercontent.com/assets/8155307/6389268/f03ccff6-bde5-11e4-8d45-1195d7495a15.png)

**Comment by smblott-github** [comment]
That's doesn't look like it's coming from Vimium...?

**Comment by noisia04** [comment]
sorry, you right. in the new profile, garbage tag is same.

**Comment by smblott-github** [comment]
Should be resolved by iframes.
