### ISSUE TITLE
Youtube video on vimium.github.io not showing up

### ISSUE THREAD

**Issue by yath** [philc/vimium#1501]
Hi,

the Youtube video on https://vimium.github.io/ is not showing up as the iframe links to http://www.youtube.com/embed/... rather than https://www.youtube.com/embed/ (or just protocol-relative: //www.youtube.com/embed/...).

**Comment by mrmr1993** [comment]
Ping @philc

**Comment by philc** [comment]
Thanks for the report @yath! This is now fixed.
