### ISSUE TITLE
Opening links using Shift-f behaving erratically.

### ISSUE THREAD

**Issue by singhkushagra** [philc/vimium#1502]
Shift-f and key combination sometimes open links in a new tab and sometimes in the same tab.

**Comment by smblott-github** [comment]
Can you give a concrete example of both cases?

**Comment by singhkushagra** [comment]
Recreating this issue is kind of a hit and miss.
I opened a google search result and using Shift-f viewed the keybinding for a particular link. Then I opened the link multiple times. All of them opened in a new tab but soon one opened in the present tab. Have tried this repeatedly  with varying degree of success. 
Using chrome Version 40.0.2214.115 (64-bit) on Mac OSX 10.10.2

**Comment by binaryphile** [comment]
I don't have erratic behavior, but Shift-F now opens the new tab in focus rather than in the background.  I relied on the old behavior.

**Comment by smblott-github** [comment]
@bernardofire Thanks.  But, see the latter posts in #1279.  Closing as dup.

(This is getting serious.  We're seeing a lot of people having this issue.  There may be some quick-fix/hacks we could do to mask some of these cases.)
