### ISSUE TITLE
Searching for the selected text 

### ISSUE THREAD

**Issue by tarek2** [philc/vimium#1503]
Searching the default search engine for the selected text is a very frequently used function. I propose to add it as a new command in vimium.

**Comment by smblott-github** [comment]
On Linux, when you create a selection with the mouse, it's copied to the clipboard.  So `p`or `P` is what you're looking for.  Not sure about other systems.

Separately, we hope to have a beta version of "visual mode" in the next release.  In that case, `v` then `p` will do what you want.

**Comment by tarek2** [comment]
Copying and then using p or P is indeed an alternative. I was not aware of it. It may still be worth considering making one single command for the two actions.
