### ISSUE TITLE
searching without changing the viewport.

### ISSUE THREAD

**Issue by mohitleo9** [philc/vimium#1504]
hey,
First of all thanks for implementing the visual mode, its really useful.
But to begin selecting text I usually start by /<word> and then motions, the problem is that as soon as I start searching I loose the viewport and the page scrolls to the top and then I have to find the correct match to start selecting. So it would be really awesome if one could start searching and not loose the viewport, (it would also enable to search from the beginning by navigating to the top of the page)
Thanks

**Comment by mrmr1993** [comment]
Over in #1467, Steve proposed:

> Viewport find mode:
>
> * The same as normal find mode (and not labelled differently to the user), except...
>
> * A collapsed selection is first established at the top of the viewport. Therefore, matches above the viewport are found only if the search wraps, and matches within the viewport are favoured.

I think we should implement this and use it for all searches (not just those from in Visual mode, as proposed there). Or have it as a default-on option, so people used to/dependant on the old behaviour can go back to it.

**Comment by smblott-github** [comment]
Locking the search to the viewport is great if that's what the user wants, but a pretty bad UX if it's not what the user wants.  The user may know that what they're looking for is just out of the viewport, and not letting them find it is pretty weird.

An alternative (possibly only in visual mode), would be to restore the scroll position on a mismatched search character.

**Comment by smblott-github** [comment]
(I'm going to try the *return to viewport* idea out for a few days, see [here](https://github.com/smblott-github/vimium/commits/return-to-viewport), 7e0af264d7c50f7fe50dc086bde1011330d3be9a.)

**Comment by mohitleo9** [comment]
True that not being able to find what you want defeats the whole point of having search. But what I meant was something like vim , it starts searching from the cursor position tries to find something, if there is no match in the current viewport then it takes you to where it can find the next match (and changes the viewport). In my opinion it is pretty awesome as most of times when I try to find with <D-f> then I have no clue where the search is going to start from, this becomes seriously worse if you searched for something and then scrolled page and then you try to search for the same thing again by <D-g>.
Having matches first highlighted in the current viewport (assuming there is one, otherwise taking you to one changing the viewport in the process) makes it predictable. I can scroll to the begining of the page by pressing gg and then start search over again or go to the end of the page and start there.
It is specifically useful in cases where I read an article and then I remember that I found some word after some image. The image acts as a mental anchor which I can navigate to quickly and then I can start searching for something (url or code snippet or something).

**Comment by majkinetor** [comment]
> Locking the search to the viewport is great if that's what the user wants, but a pretty bad UX if it's not what the user wants.

Perhaps a modifier to the `/` function, such as `<shift> /` to start searching from the current viewport ?
