### ISSUE TITLE
Feature Request: Disable vimium for 5 seconds key

### ISSUE THREAD

**Issue by togakangaroo** [philc/vimium#1509]
Sometimes a site offers a built-in shortcut that I would like to use not often enough to add a site-level exception to vimium, but often enough that disabling vimium manually and re-enabling is a pain. This is worse when the *only* way to enable the functionality is via shortcut key.

A case in point is the bitbucket code review screen where `Shift+T` is needed to bring up the task list but vimium gets in the way.

I would like to propose a key that will disable vimium for a short periods of time (5 seconds should be more than enough) so that you can use these site-shortcuts.

**Comment by mrmr1993** [comment]
Have you tried the insert mode feature (the `i` key), which lets you pass keys to the page, and then esc` to return to the default Vimium mode?

**Comment by togakangaroo** [comment]
Ah, that does work, thanks

**Comment by smblott-github** [comment]
... or, if it's a page key you use all the time in preference to Vimium's binding, then you can add it as a pass key.  (Click the vimium icon, and add the key to the "Keys" box.)

**Comment by smblott-github** [comment]
I'm guessing we can close this, now...
