### ISSUE TITLE
Map a key to move focus to location bar

### ISSUE THREAD

**Issue by daz** [philc/vimium#151]
Like F6 in Firefox and IE, it would be nice to have a mappable key to get straight to the bar, instead of the standard control+L or command+L.

**Comment by leezu** [comment]
This may be implemented in the Firefox WebExtension API. For reference, https://bugzilla.mozilla.org/show_bug.cgi?id=1295400 https://bugzilla.mozilla.org/show_bug.cgi?id=1215061
