### ISSUE TITLE
Command to open history page in new tab when going back/forward

### ISSUE THREAD

**Issue by d125q** [philc/vimium#1512]
Middle-clicking Chrome's "back" arrow goes back in history, but opens the page in a new tab. Vimium does not have the same command, although I believe it should be easy to implement them with a combination of duplicating the current tab and normally going back in history (I did not find a way to make a "composite mapping" using `map`).

**Comment by xged** [comment]
I second that

**Comment by mrmr1993** [comment]
This appears to be a dup of #1070.
