### ISSUE TITLE
Can't select Facebook search bar

### ISSUE THREAD

**Issue by tthanh** [philc/vimium#1513]
Chrome: 40.0.2214.115 (Official Build)
OS: Ubuntu 14.04
Vimium: 1.49

select facebook search bar but nothing happen, the cursor not appear like insert facebook status

**Comment by smblott-github** [comment]
You mean the "Search Facebook" input here...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/6457061/79a82d9c-c167-11e4-94bb-71e5f480ea07.png)

Selecting it with the mouse seems to work fine, for me.  With `gi`, it's the second selected input.  The tiny red rectangle left of the search box is the first selected input.  Not sure what that is.

**Comment by tthanh** [comment]
@smblott-github what gi mean? I'm new with this extension and I didn't see g mapping in help

**Comment by smblott-github** [comment]
> gi	:	Focus the first text box on the page. Cycle between them using tab

But if that's not what you're using, then don't worry about it.

I'm not seeing any issue selecting the search bar.  What exactly are you doing?  And what exactly is going wrong?

**Comment by tthanh** [comment]
@smblott-github I found I can use  f to select the status box for writing my status, so I think I can do it with search bar. I press f and keymap for status bar. With gi, I can use search bar, thank you

**Comment by smblott-github** [comment]
Ah.  OK.  So the problem is possibly just that the hint is appearing in an odd place.  It's the `11` here:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/6457466/175d86b2-c16e-11e4-95b7-13270aac0eaf.png)

**Comment by tthanh** [comment]
@smblott-github you right, now I see the hint for it @@ thank you so much. This extension help me a lot when web dev with Vim.

**Comment by tthanh** [comment]
@smblott-github One more question. How can I tick a checkbox or radio button with Vimium

**Comment by smblott-github** [comment]
Should work with link hints (`f`).

**Comment by tthanh** [comment]
@smblott-github Thank you so much. My website use Materialize for design, it's hide checkbox and draw box with laber. Now I know why link hints not show :cry:

**Comment by rrsahuone** [comment]
Now you don’t have to finish each and every procedure by yourself. You just have to explain your need to the final Company and take a moment as your perform will always be finished promptly.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by rrsahuone** [comment]
You can also instruct the hired persons how to package and fill the products so everything could be done as per your needs and expectations. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers in Delhi">Packers and Movers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by rrsahuone** [comment]
Once they have noted down all the specifications, everything will be done in the same way only. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers in Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a>

**Comment by rrsahuone** [comment]
The most responsible procedure for you is choosing best product packaging and moving Company for effective results.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
