### ISSUE TITLE
Open a link in a new tab (background tab) is broken after a recent Chrome update

### ISSUE THREAD

**Issue by andrewpsy** [philc/vimium#1520]
This is the current mapping:
F	:	Open a link in a new tab (LinkHints.activateModeToOpenInNewTab)
but it functions like:
	:	Open a link in a new tab & switch to it (LinkHints.activateModeToOpenInNewForegroundTab)
This command is not mapped to anything.

Mac Chrome Version 41.0.2272.76 (64-bit) Let me know if you need more info.

As always, thanks for the great tool.

**Comment by Gpx** [comment]
Have the same problem Mac Chrome Version 41.0.2272.76 (64-bit).

Let me know if you need some help with testing.

**Comment by smblott-github** [comment]
This is a dup of #1279.  Closing this. suggest moving discussion there.
