### ISSUE TITLE
LinkHints.activateModeToOpenInNewTab opens new tabs in the foreground

### ISSUE THREAD

**Issue by wocala** [philc/vimium#1523]
LinkHints.activateModeToOpenInNewTab opens new tabs in the foreground which shows the same function as LinkHints.activateModeToOpenInNewForegroundTab.
I have reopened the Chrome and disabled all other extensions but didn't work.
Vimium Version: 1.49, Chrome 41.0.2272.76 m (32-bit) windows 7 enterprise
Thans a lot!

**Comment by smblott-github** [comment]
Thanks @wocala.  This looks like a dup of #1279, yes?  Suggest you read the bottom part of that thread.

**Comment by wocala** [comment]
@smblott-github Sorry about that. Thanks!
