### ISSUE TITLE
Cannot close chat windows in Gmail whilst Vimium is installed

### ISSUE THREAD

**Issue by bonstio** [philc/vimium#1525]
In Gmail, 'esc' closes an open chat window. With  Vimium installed, this no longer works, even when explicitly disabling vimium for mail.google.com.

**Comment by smblott-github** [comment]
Try adding an exclusion rule (on the options page) for:

    https://talkgadget.google.com/u/*

(If it's like Google Inbox, then the chat is in an iframe.)

**Comment by bonstio** [comment]
Right... I had previously added this URL to the exclusion list, apparently without effect. However, I just checked and this addresses the problem. Great. Marking is closed. Thanks.
