### ISSUE TITLE
smooth scrolling does not stop if element loses focus during scroll

### ISSUE THREAD

**Issue by fent** [philc/vimium#1526]
To see what I mean you can go to this page
http://jsbin.com/hucasosapo

With smooth scrolling on, right after pressing a scrolling key, like `j` or `d`, immediately press `space` so that it focuses the input box and doesn't get the `keyup` event. It will continue to scroll down the page.

**Comment by smblott-github** [comment]
Yes.  You can get a similar effect by going to a long page, press and hold `j`, with the mouse change tab, release `j`, change back to the original tab.  It's still scrolling.

**Comment by smblott-github** [comment]
Thanks, @fent.  Fixed in #1527.

**Comment by philc** [comment]
Nice find guys =) that was wonky.
