### ISSUE TITLE
New feature: search history

### ISSUE THREAD

**Issue by coutotyler** [philc/vimium#1528]
I'd like to propose implementing a search history function in Vimium. I imagine it could work in a similar fashion to the vim search history or the bash command history in vi mode. That is it could work in the following way: 
1. Press '/' to enter search mode.
2. Press up-arrow and down-arrow to navigate previous searches.
Maybe this could be extended to include predictive typing based on previous search history. 

I'd love to know what people think of this. I don't have any experience with coffeescript but would be happy to give it a go.

**Comment by smblott-github** [comment]
Thanks @coutotyler.  Turns out that was added just a few weeks ago (#1454).  It's in `master`, and will be in the next release.

**Comment by coutotyler** [comment]
Great! Thanks.
