### ISSUE TITLE
Behaviour problem in opening link in new tab

### ISSUE THREAD

**Issue by davinellulinvega** [philc/vimium#1531]
Hello everyone,

Since the last update of chromium Version 41.0.2272.76 Ubuntu 14.10 (64-bit), both the LinkHints.activateModeToOpenInNewTab and the LinkHints.activateModeToOpenInNewForegroundTab, open the selected link in a new tab and focus this tab.
Whereas in the previous chromium version, the behaviour of the former command was to open a new tab in the back ground.
I have other extensions that allow the opening of new tabs in background and they are all working find for the moment. Thus, I think that the problem may come from the way vimium handles opening new tabs.
I tested with the version 1.49 and 1.44 of vimium and the result was the same for both versions.

Sincerely

**Comment by mrmr1993** [comment]
This is a dup of #1279. It's a chrome issue, and should be fixed in the next version of Chrome.

**Comment by davinellulinvega** [comment]
Thank you very much for the quick answer.
I am very sorry for not seeing this other thread before commenting.

Sincerely
