### ISSUE TITLE
New tabs opening in foreground instead of background

### ISSUE THREAD

**Issue by mapmike** [philc/vimium#1535]
After using Vimium for a few years with no problems, suddenly today the behavior of LinkHints.activateModeToOpenInNewTab has changed and new tabs open in the foreground. This happens on every webpage I've tested. Using the mouse to select "open link in new tab" opens background tabs like normal. My current version of Chrome is Version 41.0.2272.89 m.

**Comment by smblott-github** [comment]
Thanks @mapmike.  Dup of #1279, I think.  See the latter posts there.
