### ISSUE TITLE
Compatibility with bilingual Keyboards - Problem with opening a link in a background tab 

### ISSUE THREAD

**Issue by tarek2** [philc/vimium#1539]
People with bilingual keyboards find it tedious having to switch back and forth between the two layouts because vimium understands by default only the english shortcuts and not the characters of the other language on the same keys. Of course one can go through all the commands and map the other character for each command. Can this be done by default in future versions?

**Comment by smblott-github** [comment]
> Previously opening a link in a new tab behaved normally and opened it in the background.

@tarek2: This part or your post is probably a dup of #1279.

**Comment by tarek2** [comment]
@smblott-github Thanks, I removed it from my post to make it focus on the first issue.

**Comment by janek-warchol** [comment]
Something like vim's `langmap` would be very nice!
