### ISSUE TITLE
Vimium does not seem to work at all in Google Chrome for Mac

### ISSUE THREAD

**Issue by axman6** [philc/vimium#154]
After installing the plugin and restarting Chrome, this plugin seems to take no effect whatsoever. Tested using Google Chrome 5.0.375.55 and Vimium version 1.17.

**Comment by rajeevksahu** [comment]
Bangalore ! Whenever we heard about this town, one factor always comes in our mind and that is desire town. Yes, Bangalore is the desire town not only for the Expert fans but also for the company and education sectors. In this active environment, Bangalore is regarded as one the busiest town in the world.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
Everyone in Bangalore , are too stricken in their lifestyle that they don’t have a chance to take a crack. In such condition, moving from one position to another is tremendously difficult. Shifting is one of the toughest projects, but the concerned point is to take a lengthy crack from your perform and then package and shift all the loads from your present position to the new one. Shifting for job, studies and others creates it essential.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
Packing moving Bangalore can be always simple but you just have to take an essential step and this is to believe in on packers & movers Bangalore . They are so qualified and expert in their perform that you don’t have to take issues about your useful items. They handle all the items as finely as are their own.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
Proper methods are used to provide your fill to your position. In Bangalore , moving of workplaces, workplaces, houses, etc. is daily perform. Clients believe in create the experts so experienced that now, you don’t have to tell them anything. They perform so neatly that client does not have any disappointment while payment.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by jingpengwu** [comment]
I updated to the latest chrome, still not working. works in my ubuntu workstation though.
the chrome version is 58.0.3029.110 (64-bit).

```
system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.4 (16E195)
      Kernel Version: Darwin 16.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
```

**Comment by mrmr1993** [comment]
@jingpengwu I suggest opening a new issue; yours is probably not the same one that people were experiencing in 2010.

**Comment by jingpengwu** [comment]
thanks, reported in a [new issue](https://github.com/philc/vimium/issues/2511)
