### ISSUE TITLE
about local page

### ISSUE THREAD

**Issue by Justforfei** [philc/vimium#1540]
Vimium is absolutely great!
But why it doesn't work on local page?And also doesn't work on pdf which open in chrome though I add some rules...

**Comment by mrmr1993** [comment]
* There should be a checkbox next to Vimium in `chrome://extensions` to enable for local pages.
* Presumably psd files use a plugin rather than html/javascript, so we have no way of listening for key events while it is focused.

**Comment by Justforfei** [comment]
Thank you very much!

**Comment by philc** [comment]
Regarding local pages, it's worth adding to the FAQ on the wiki.

**Comment by smblott-github** [comment]
Done: https://github.com/philc/vimium/wiki/FAQ#how-can-i-use-vimium-on-file-urls
