### ISSUE TITLE
Open a link in a new tab command doesn't work in Chrome 41 on Mac

### ISSUE THREAD

**Issue by viix** [philc/vimium#1541]
Previously, Open a link in a new tab (which is default the key F) opens a new tab on background, but now it opens in a new tab on foreground, which means after open new tab, it switches to new tab directly.

the environment is:
Mac OS 10.9.5
Chrome 41.0.2272.89 (64-bit)

**Comment by smblott-github** [comment]
Thanks @viix. This is a dup of #1279.  See there.
