### ISSUE TITLE
An ugly trick to open chrome-extension:// urls in the incognito mode

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#1544]
#1532 said `pages/newtab.html` can not be opened in an incognito window, which is `true`.
But I want to say, there is a trick to show normal tabs in any incognito window - althought I don't think it should be merged to vimium - just for information and fun.

In Chrome <= 38 (just for I have only 33, 38 and 40):
* `chrome.tabs.create` a tab with `selected: false` # will be open in a normal window
* `chrome.tabs.move` the tab created to `{index: ~, windowId: $incognito_target}`

As for Chrome 40, move across incognito modes is forbidden, but there is still a trick:
* `chrome.tabs.create` a tab with `selected: false`
* `chrome.windows.create` a window with `incognito: true, tabId: $tab_created.id`
* `chrome.tabs.move` the tab created to `{index: ~, windowId: $incognito_target}`

Such a tab is `incognito: false`, but indeed in a `incognito: true` window.
Urls like `chrome://options` can be shown on this way, too.
Note:
* `chrome://downloads/` has a specific incognito version
* `chrome-search://local-ntp/local-ntp.html` can be opened directly
* `chrome.windows.create` is used to move tabs across incognito modes, but unfortunately it may be treated as a bug and removed by Chrome in the future.

**Comment by mrmr1993** [comment]
According to [the docs](https://developer.chrome.com/extensions/manifest/incognito), we can use split incognito mode, and then we'll be able to open our pages in incognito tabs too. We'll probably have to tweak the find history and Vomnibar tabs code slightly, but everything else should transfer over fine. 

Only tangentially related, but we seem to rely on the background page to discover whether we're in incognito mode or not; [chrome.extensions.inIncognitoContext](https://developer.chrome.com/extensions/extension#property-inIncognitoContext) does this synchronously and natively in content scripts.

**Comment by smblott-github** [comment]
From [the docs](https://developer.chrome.com/extensions/manifest/incognito).

> chrome.storage.sync and chrome.storage.local are always shared between regular and incognito processes. It is recommended to use them for persisting your extension's settings.

It's not clear whether `localStorage` is shared.

**Comment by mrmr1993** [comment]
> It's not clear whether `localStorage` is shared.

It isn't. `localStorage` is in-memory only and is cleared each time incognito exits. So we'd be stuck with defaults until the incognito background page loads `chrome.storage`. Maybe this idea might need more of a rewrite than I had expected.

**Comment by gdh1995** [comment]
I don't like splitting incognito mode. For me, Vimium is another layer of Chrome UI, without considering if itself is in the incognito mode.

**Comment by mrmr1993** [comment]
@gdh1995 with split incognito mode, all settings are persisted via `chrome.storage`. There should be no perceptible change to an end user. 

I was also incorrect earlier; all code will function correctly, apart from the few (3-4, if memory serves) lines of code that rely on synchronous settings. Soon I'll get my housemate to push the `chrome.storage`-based settings implementation I wrote, and then, if that gets merged, it should be trivial to move to completely async settings, so this isn't a problem either.

**Comment by gdh1995** [comment]
Althoug we can use "split" mode, this trick is still useful if we need to move tabs like "chrome://*" or other extensions'.
Close, because I have no more different idea.

**Comment by rrsahuone** [comment]
It reduces chances of errors and products will be shifted to correct position without any harm.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by rrsahuone** [comment]
Movers and packers Bangalore assist you in shifting and moving through appropriate preparing, organizing, and execution. They also provide you with product packaging and movers in Bangalore for car transportation and moving of other automobiles. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers in Delhi">Packers and Movers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by rrsahuone** [comment]
For moving car, car providers are available to carry automobiles of different size and shapes. Now you can bring your automobiles to new location in straight forward manner.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers in Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a>

**Comment by rrsahuone** [comment]
Make moving and product packaging much easier than it was regarded in previous. You will feel less burdened and can focus on other effective projects easily. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by gdh1995** [comment]
@frederickk Sorry but I think it's necessary to give a tip here: Chrome has completely dropped the trick of moving normal tabs to incognito windows, since version 52. In 2017 I hadn't found any new trick to do so.
