### ISSUE TITLE
Key press for "open link in new tab" (f) should not be dynamically re-bound 

### ISSUE THREAD

**Issue by tecfu** [philc/vimium#1546]
When pushing the f key, Vimium users see a map of tooltips displayed that show keycodes bound to an "open link in new tab" event.

The f key should not be bound to any of those tool tips - because double tapping the f key leads to unexpected navigation. The user will unexpectedly be sent to whatever link was mapped to "f" directly after pressing "f" to trigger the tooltip display.

Instead, the f key or whatever key triggers the tooltip display for "open link in new tab" should be held back from the keycodes that are generated in the display.

**Comment by biswanaths** [comment]
I assume you can avoid this problem by removing "f" from the "characters used
for link hints" in the advanced options. I personally though never had this problem.

**Comment by tecfu** [comment]
Did not know this feature existed. Fix works a treat. Thanks.
