### ISSUE TITLE
LinkHints.activateModeToOpenInNewTab and LinkHints.activateModeWithQueue will jump to the new tab

### ISSUE THREAD

**Issue by kalokng** [philc/vimium#1548]
Using Vimium 1.49.
Click on the link with <F> (LinkHints.activateModeToOpenInNewTab) or <a-f> (LinkHints.activateModeWithQueue) will make the active tab to be the newly opened tab. Which in prev version the current tab will stay as the active tab.

**Comment by smblott-github** [comment]
Thanks @kalokng.  This looks like a dup of #1279.  See there.

**Comment by kalokng** [comment]
yes, you are right.
