### ISSUE TITLE
 vimium 1.45 does not work normally on some website; 

### ISSUE THREAD

**Issue by zhbmath** [philc/vimium#1551]
vimium 1.45 does not work normally on some website; 
such as: http://www.2345.com
if you press j or k , the web page don't scroll down or scroll up
if you press x , the web page was not closed
what 's the reason ?

chrome version 41.0.2272.89 m
OS: windows xp sp3

**Comment by smblott-github** [comment]
1.45 has been superseded by 1.49.  You might start by upgrading Vimium.

That site scrolls correctly for me with 1.49 and with `master` (although it's possible that there's an internationalisation issue at play).
