### ISSUE TITLE
if a port is disconnected, we may re-connect it

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#1552]
I think the current ports' onDisconnect is not good enough (not suitable for developer).

As far as I have tested:
* `keyPort` will be disconnected, if the background page closes
* if we refresh the background page, in the frontend, we may call `chrome.runtime.connect` to make a new `keyPort`
* if the extension is reloaded, old content scripts will fail to call `runtime.connect`, because it throw an error
* if the background page calls `window.close()` and there's no onConnect handler, then frontend can still call `connect` and get a valid port - this port will be disconnected auto & soon

So, here are my solutions:
* add an `onDisconnected` listener for each port
* if a port is disconnected, call `connect`
* if okay, we can use Vimium as before
* if re-connecting fails, turn off `isEnabledForUrl` and destroy UIs

Then, we may refresh the background page if there are changes only in main.coffee.

**Comment by smblott-github** [comment]
We don't have that, but we do have this: https://github.com/philc/vimium/pull/1521.  It's imperfect, but better than nothing.

**Comment by gdh1995** [comment]
Although #1521 works, just reloading the background page will make all Vimium frontends turn off, and this is what I want to change.

`onDisconnect -> try connect() -> catch { then turn off }`

PS: This process is easy to code

**Comment by smblott-github** [comment]
No.  The original frontends are disabled, and new frontends are injected.

**Comment by gdh1995** [comment]
I know, but such a way is expensive and wastes computing resource

**Comment by smblott-github** [comment]
That's no big deal for development.

**Comment by gdh1995** [comment]
All right. I close this issue now.
