### ISSUE TITLE
can't open private domain sites.

### ISSUE THREAD

**Issue by thalligan** [philc/vimium#1553]
When opening a private domain website (ie where the domain is not registered and so not resolvable publicly by internet), vimium fails to open page as it looks like it does a search in goolge first.

eg 

:o mysite.privatedomain

will end up with a google search for mysite.privatedomain, whereas it should just be resolved locally via DNS as per what happens when typing into Chrome's navigation bar.

**Comment by smblott-github** [comment]
Thanks, @thalligan.  Vimium's test for whether a query is a URL isn't perfect.  However, If we interpreted `mysite.privatedomain` as a URL, we would also interpret `string.length` as a URL (which would be incorrect).

(Oddly, we currently interpret `string.len` as a URL.)

**Comment by smblott-github** [comment]
Can't fix.
