### ISSUE TITLE
LABEL aren't listed as a click-able item in f mode

### ISSUE THREAD

**Issue by SRachamim** [philc/vimium#1554]
When pressing f to see all available links, LABEL tags are not listed.

**Comment by smblott-github** [comment]
Thanks @SRachamim.  Could you give more detail, please?  Which site?  What do expect to happen?  What does happen?  And so on.

**Comment by SRachamim** [comment]
Yes, sorry for not giving more details.

When I press f I expect to see not only <a> and <button> tags, but all click-able items on the page. <label> is one of them. You can visit http://www.tipranks.com to see an example to a web site that uses <input> tags inside <label> tags instead of using for attribute (in order to avoid id attributes).

When you pressing  f in order to see all click-able items on the page, I don't see any <label> tag.

**Comment by smblott-github** [comment]
It's the "Trending" labels you're interested in, @SRachamim, right?

On first inspection, it looks like we're not picking these up because we're concluding (incorrectly) that they're not visible (In `DomUtils.getVisibleClientRect`).  They are reported as having zero height.

(Temporarily removing [this test](https://github.com/philc/vimium/blob/master/lib/dom_utils.coffee#L64) fixes the problem.)

**Comment by mrmr1993** [comment]
There isn't currently any code in `LinkHints` that marks `<label>` elements as clickable, unless they satisfy some other condition. I threw together [this JSFiddle](http://jsfiddle.net/mhwa9zep/1/) with all the obvious configurations I could think of.

Some thoughts:
* It's probably too heavy handed and confusing to always show a link hint for `<label>`s which are associated with an `<input>`.
* It's not unreasonable that a webdev might use a label and a hidden native checkbox/radio button to create their own custom checkbox/radio button.
  - This means that visible `<label>`s associated with a hidden  `<input>` should probably have a link hint.
* A `<label>` not associated with an `<input>` (its `for` attribute doesn't correspond to the `id` of any element, or there's no `for` attribute *and* it doesn't wrap an `<input>`) shouldn't have a link hint.

(Sorry if this is over-analysis or I misunderstood the issue.)
