### ISSUE TITLE
Missing "pause" button

### ISSUE THREAD

**Issue by Atcold** [philc/vimium#1555]
Sometimes it is necessary to just "pause" *vimium* without necessarily adding a new rule.

**Comment by smblott-github** [comment]
Perhaps "Insert Mode" is what you're looking for, @Atcold.  Press `i`, Vimium is "paused".  Pres `Esc` to resume.

**Comment by Atcold** [comment]
Hum... not really.
Upon pressing `i`, the cursor jumps into the first text box and then I can type stuff.
I have a Chinese dictionary plug-in which "jumps" to the grammar about the word that is under the mouse cursor if the letter `g` is pressed. So, on Chinese websites I would like to temporarily disable *vimum* for using the dictionary (and relative grammar section) without conflicts.

Edit: pressing `i` and clicking away from the editing box does the trick. Nevertheless, I think it could be helpful a *pause* button.
