### ISSUE TITLE
Exclude all keys except ____

### ISSUE THREAD

**Issue by truth1ness** [philc/vimium#1560]
You can easily disable All Keys or Individual Keys for a site, it's difficult to disable All Keys Except Keys x y z. For example, mail.google.com has all keys disabled by default. I would like to use the "f" command from vimium in Gmail. How would I do this? I would have to copy every single Gmail shortcut into the box and take out f which seems very tedious and inneficient. 

A better method would be to put a plus sign in front of the keys you want to use from Vimium. ie "+f" would mean "Keep disabling all keys but allow 'f' from Vimium to be used".

**Comment by dradetsky** [comment]
I just did exactly this 3 minutes ago. I went through the list of shortcuts and set the gmail-excluded keys to jkhlgGzduryivVabceoOTbB[]m`nNHLKJtxXW<>? (this may not work for you; i've already made other config changes)

I'm not sure OP's proposed solution is the best though. A simpler solution that would cover most cases and not require a bunch of parsing code is: have a switch which changes the field from 'disable these keys' to 'only enable these keys'. That's more the kind of thing you could do in an hour if you knew the vimium codebase.

**Comment by mrmr1993** [comment]
Some considerations:
* Does this disable keys with modifiers?
  - If so, there'd be no way to re-enable them; we currently don't recognise these in the passkeys field (although #1368 could be refreshed to fix that).
  - If not, how do we communicate this concisely to users so they're not taken by surprise?
* If we use a `+` before exclusive keys, how do you disable a mapping on `+`?
* How do we give users this choice on each rule (and allow them to see what choice they've already made) clearly without overrunning the limited space in the icon popup?
  - Maybe a `<select>` with "disable" and "allow only" as options? Would that be too big?
* Would a more powerful text-based config like the one in #1188 be an acceptable/good/better alternative?

The actual backend code changes should be reasonably easy, very little would need to change there to support this.

**Comment by dradetsky** [comment]
1. i actually completely forgot about mod keys, so well-spotted. i'm happy
for the relevant feature to ignore mod keys entirely. trend on web apps
seems to be towards vim-style keybindings anyway, so that's where we need
to avoid clashes.

2. this is another great reason not to use +-syntax. or at least not until
a user has an actual use-case.

3. one checkbox labelled 'invert' above, possibly with a 'wtf is this
shit?' link to documentation.

4. it would be a way-more-complicated and not-clearly-required alternative.
"I want to use only a few vimium functions in gmail/twitter/other-app" is
probably something lotsa power users would want (we have 2 already; and
total isn't huge to begin with).

I don't oppose fancy text config per se, but is there a simpler feature
request that covers 90% of the cases? given that i'm asking somebody i've
never met to write code for me for (as far as he knows) free, i feel it's
incumbent upon me to check.

**Comment by mrmr1993** [comment]
> i'm happy for the relevant feature to ignore mod keys entirely

But is this the right thing to do? Personally I'd feel happier landing #1368 (I'll ping Steve and see if that's a possibility) and making the feature "only the keys and combinations in the passkeys field will be recognised by Vimium", so we don't take anyone by surprise.

> one checkbox labelled 'invert' above, possibly with a 'wtf is this shit?' link to documentation.

For the most part people won't read the documentation, so the UI has to be pretty self-explainatory. I'll try it with an 'invert' checkbox when I get round to doing this.

> it would be a way-more-complicated and not-clearly-required alternative.

Agreed. I'd wanted it a few times to *change* some mappings on pages where our and the page's mappings overlap, and *both* are useful &mdash; but it's probably overkill here.

**Comment by dradetsky** [comment]
1. maybe it's not, but i don't see why we can't start out by supporting
non-mod keys and then add support for modkeys later.

2. we can disable the checkbox and require you to enable it via a setting,
but in general i don't agree. we're not talking about software for
everyone. this is a program for people who are upset their browser isn't
enough like vim. they have higher-than-average tolerance for reading
documentation.

**Comment by mrmr1993** [comment]
This isn't my project, and I'm not an official contributer, so I'm just trying to keep within the [design goals](https://github.com/philc/vimium/blob/master/CONTRIBUTING.md#vimium-design-goals) with this feature. But this might be a good candidate for Vimium Labs (#1542) while the details are worked out.

**Comment by smblott-github** [comment]
On the idea of an exclude/include toggle... Would that (re-)introduce the issue that the ordering of multiple matching rules would matter?

**Comment by mrmr1993** [comment]
> Would that (re-)introduce the issue that the ordering of multiple matching rules would matter?

If we take them as "disable" vs "allow only", then we could apply all the "allow only" rules first and subtract the "disabled" rules from the result, so the order shouldn't matter.

**Comment by dradetsky** [comment]
I'm not familiar with the previous discussion of the issue, but can you
think of any reason why specifying a disable rule and an allow-only rule
for the same url isn't a user error? I would think the correct thing to do
would be to warn the user that they had done something bizarre, and then
either

a. order them to fix it.
b. resolve it by ignoring the disable rule.
c. resolve it as Matthew suggests.

I mean, I suppose *maybe* a user wants to ignore W for all google apps, but
not other urls, and then additionally wants to enable only f on gmail, or
something, but this seems weird. But if we're allowing for strange
possibilities, I might want to disable W on all google apps *except* gmail,
and also enable f in gmail.

I suppose it wouldn't be too much additional development work to make the
resolution rule configurable (compared to parsing a key-specification
syntax or a more complicated config file), But (b) still seems like the
best solution to me. When I say "allow only" I probably want "allow
exactly."

Can anyone think of a realistic counterexample to the above? Maybe "I never
want to run certain command on https urls" or something? I dunno.
only=exactly seems best to me.

**Comment by mrmr1993** [comment]
> can you think of any reason why specifying a disable rule and an allow-only rule for the same url isn't a user error?

Seems entirely reasonable when a user only wants some keys enabled for a whole site, and further wants to drop some keys for a specific page/part of the site. For example:

allow only:

```
https?://your.domain.tld/* fJKjki
```

disable:

```
https?://your.domain.tld/a-particular-page jk
```

**Comment by dradetsky** [comment]
oh yeah

**Comment by rrsahutwo** [comment]
We are known as a worldwide company operating through a neighborhood specialists or a nation head that is in charge of every individual request and dispatch. We likewise provide other related transportation features, similar to cargo sending, traditions freedom management, transportation by air, strategies administrations to provide some examples. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
Our experts perform for our clients and create them relieved from the pressure or worry of unwanted happenings with their useful factors.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
Our moving alternatives also cover the company sectors and take their items to their partners and Expert regional stores. For moving enormous devices our Bangalore packers and movers can use wood made containers. The expert packers have operating encounter in packaging and moving devices. On the off chance that our clients have mechanical merchandise to be sent crosswise over universally, they ought to believe in on our wood made box packers for devices and equipment. Wooden containers are accessible in mixture of size and shapes can be altered or purchased by sort and weight apparatus. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
The wood made containers we use help in ensuring against temperature extremes, any scraped spot or mischief and improve secure stockpiling. We select trailers and transportation compartments which can tackle your exceptionally reason for protected, secure and prompt reposition of items. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by christianrondeau** [comment]
A good use case for this is using JIRA. I use most shortcuts for JIRA (which is a lot), but I'd still like <kbd>o</kbd> to search a new tab, and <kbd>f</kbd> to follow links. I can type the whole alphabet in the box and that's ok, but a reverse rule would be simpler :)

**Comment by DamirCiganovic-Jankovic** [comment]
Please do this, I would like to use Vimium only for "f" functionallity, as I already know many chrome shortcuts, this is the only thing I need

**Comment by smblott-github** [comment]
@DamirCiganovic-Jankovic.  You can unmap the keys you never use on the options page.

**Comment by mgalgs** [comment]
@smblott-github I see this was closed due to lack of interest.  Is there any chance of reopening this if enough interest is generated? 😄

<sub>(Future readers, please give a thumbs up on the top-level comment on this thread to register your interest!)</sub>

**Comment by gdh1995** [comment]
Seems #3272 also reports this problem, and there're quite a few similar issues. Is there someone interested in my idea in https://github.com/philc/vimium/issues/3272#issuecomment-475296695?

**Comment by MikeMajara** [comment]
I find this an esential feature and think this should be reopened. I am glad to go through the code but did not have the time yet. So, here is the workaround I'll try to use to avoid all the clashing while not having to completely disable vimium all over the place.

Here are all the keys that vimium uses, to my best of knowledge -
**with spaces**: ? h j k l g G d r s f F o O b B J K 0 $ ^ y t x X T W p m a A ` i u U e E z H L v V
**trimmed**: ?hjklgGdrsfFoObBJK0$^ytxXTWpmaA`iuUeEzHLvV

1. Go to your fav text editor (e.g. Vscode)
2. paste the string
3. search and remove the keys you want to enable in Vimium.
4. Paste whats left of the string as an exclude pattern in Vimium pop up

**Comment by Jasha10** [comment]
> Here are all the keys that vimium uses, to my best of knowledge

@mikemajara, I've expanded your list to a bigger subset of ascii keys. This way, even if vimium adds more keyboard shortcuts in the future, the list should still be fairly complete.

```
!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
```

**Comment by mikemajara** [comment]
Just use Vimium-C

**Comment by nitayderei** [comment]
Instead of going through the list of keys, I configured to unmap all keys and re-map my favorite (`f`) to `~`:
```
unmapAll
map ` LinkHints.activateMode
```

It works great for a small number of keys :)

**Comment by Susensio** [comment]
> Instead of going through the list of keys, I configured to unmap all keys and re-map my favorite (`f`) to `~`:
> 
> ```
> unmapAll
> map ` LinkHints.activateMode
> ```
> 
> It works great for a small number of keys :)

But this works globally, right? I mean, it cannot be applied to only one website.

**Comment by nikhilweee** [comment]
Came here to show interest about this feature. This would be really helpful.

**Comment by Susensio** [comment]
I ended up using [Vimium C](https://chromewebstore.google.com/detail/vimium-c-all-by-keyboard/hfjbmagddngcpeloejdejnfgbamkjaeg)
You can do a negative exclusion with `^`.
For example, if I only want to move between tabs in github, I would do something like:
```
^ J K
```

**Comment by S1lander** [comment]
> Just use Vimium-C

Damn, I should have found this earlier. Thank you.

**Comment by cBournhonesque** [comment]
I would also like this feature
