### ISSUE TITLE
Press f second time to escape from Open Link mode

### ISSUE THREAD

**Issue by truth1ness** [philc/vimium#1561]
Why not allow exiting of Link-Hints by simply pressing f again? For the Link-Hints all that needs to be changed is to have it skip over the use of F in the links-hints. It feels very natural to turn them on and off by pressing f repeatedly. 

This is related to this request for a mappable general escape key command https://github.com/philc/vimium/issues/1463 but creating a new one because it's a separate solution that simply uses the existing command.

**Comment by mrmr1993** [comment]
You can get the behaviour you want by removing `f` from the "characters used for link hints" box in the options (and then pressing save). Although it would be nice if it was this way by default.

This is a dup of #577, #638, #917, #972, #991, #1488, and #1546. The discussion (involving the project owner) related to not making this change is over in #638, if you or anyone else is interested.
