### ISSUE TITLE
Turn home row (asdfghjkl) into number row (1234567890) when link hinting

### ISSUE THREAD

**Issue by leoj3n** [philc/vimium#1562]
I currently use [Karabiner.app](https://pqrs.org/osx/karabiner) to turn my home row into a number row by holding SPACE:

![homerow](https://cloud.githubusercontent.com/assets/990216/7126288/afa918c8-e1fd-11e4-8cfd-3f633427a2a3.png)

In Vimium I set link hints to numbers so I can hit `f` then hold SPACE and press f.ex `a`+`h` for `16`. This way my fingers never move off the home row.

This could be a builtin Vimium setting, then I wouldn't have to hold SPACE.

**Comment by smblott-github** [comment]
Closing.
Lack of interest.
