### ISSUE TITLE
Shorten & Save link hint

### ISSUE THREAD

**Issue by truth1ness** [philc/vimium#1565]
On many pages there is one or two links I use almost all the time. It's annoying when a commonly used link gets a two-letter link hint (as far as I can tell it's luck of the draw), especially ones that need to be pressed over and over. It would be great if the user could manually 1) shorten and 2) save that shortened hint for future visits/pages. 

Implementation details:

1) Allowing the user to flip the desired link hint to a one letter link hint while on the page
Could be done by holding down control while pressing the combination. That will tell VIM to re-assign it a single letter

2) Remember that change
Store manual changes so they get the same single letter link hint next time the user visits. Over time a user could navigate common sites without looking purely from memory/muscle memory

3) Use the same link hint on other pages on the same domain
For example, if you are going through a wizard and manually assign a link hint to the Next button, Vim will automatically try to assign the same link hint on the next page. 
I realize it won't be able to do this with 100% accuracy, but it would work decently well by having VIM record the text of the link and/or any semantic information in the link's html such as its class/id attribute. 

This would be useful for any pages where there is repetitive clicking on the same/similar element. Wizards, quizzes, forms, multipage articles, search results, web apps, and a lot of other stuff. Youtube's html5 player, for example, has no shortcuts for full screen and the above would allow the same two stroke key sequence to always activate that link.

**Comment by smblott-github** [comment]
Closing.  Move to #2083.
