### ISSUE TITLE
when i press i(insert mode),vimium cannot locate the input box

### ISSUE THREAD

**Issue by Wang-Kangjin** [philc/vimium#1566]
You can test this in www.baidu.com .i am chinese :).
But it works at github.com.As this page,when i press 'i' ,vimium shows that i entered the insert mode,but it cannot  input directly.Then, i press 's',it locate at the 'Search' input box.
Is it normal?
My vimium's version is 1.49 and my chrome's version is 41.0.2272.118 m

**Comment by smblott-github** [comment]
Do you perhaps rather mean `gi` to enter the insert box?

(Insert mode is arguably a misleading name.  It just means Vimium gets out of the way, and passes all of your keystrokes through to the page.)

**Comment by Wang-Kangjin** [comment]
Done  THANK YOU so much!
But the information about `gi` is not given in the Vimium Help.
