### ISSUE TITLE
Navigation history with ctrl+o

### ISSUE THREAD

**Issue by mohitleo9** [philc/vimium#1568]
Hey ,
I was wondering if there is any way to go back to the page I was last on.
A lot of times I have quite a few windows open and then I switch to some tab using T, but then I have to use T again to back to the previous page, instead it would be really cool if there was some ctrl-o and ctrl-i like commands to scroll through the jumplist (navigation history).

**Comment by azat** [comment]
+1

**Comment by remyo** [comment]
Great idea.

**Comment by smblott-github** [comment]
Closing.
Using `T` is the current approach.
