### ISSUE TITLE
I can't enter Korean after I enter '/'(find mode)

### ISSUE THREAD

**Issue by cypicaso** [philc/vimium#1573]
Hi.

I can enter only English in find mode.
I want to enter Korean(2-byte characters) in find mode.

Thanks.

**Comment by smblott-github** [comment]
@cypicaso.  Thanks for the report.  Afraid I don't know much about non-English keyboards.  Could you perhaps go to [this site](http://jsfiddle.net/mrcoles/5TJc9/light/), focus the bottom-right frame, press the key you want ot enter and post back the results?

**Comment by cypicaso** [comment]
I entered 8 Korean character: "가너도루"----Click here and start typing to see
how keyboard events are triggered. Hover over a field to see the event
property. (via mrcoles.com <http://mrcoles.com/keys/>)
evt:which:keyCode:charCode:modifier:

2015. 4. 20. 오후 7:30:36 >keyup78780

2015. 4. 20. 오후 7:30:36 >keypress110110110

2015. 4. 20. 오후 7:30:36 >keydown78780

2015. 4. 20. 오후 7:30:36 >keyup70700

2015. 4. 20. 오후 7:30:36 >keypress102102102

2015. 4. 20. 오후 7:30:36 >keydown70700

2015. 4. 20. 오후 7:30:35 >keyup72720

2015. 4. 20. 오후 7:30:35 >keypress104104104

2015. 4. 20. 오후 7:30:35 >keydown72720

2015. 4. 20. 오후 7:30:30 >keyup69690

2015. 4. 20. 오후 7:30:30 >keypress101101101

2015. 4. 20. 오후 7:30:30 >keydown69690

2015. 4. 20. 오후 7:30:28 >keyup74740

2015. 4. 20. 오후 7:30:28 >keypress106106106

2015. 4. 20. 오후 7:30:28 >keydown74740

2015. 4. 20. 오후 7:30:27 >keyup83830

2015. 4. 20. 오후 7:30:27 >keypress115115115

2015. 4. 20. 오후 7:30:27 >keydown83830

2015. 4. 20. 오후 7:30:23 >keyup75750

2015. 4. 20. 오후 7:30:22 >keypress107107107

2015. 4. 20. 오후 7:30:22 >keydown75750

2015. 4. 20. 오후 7:30:18 >keyup82820

2015. 4. 20. 오후 7:30:18 >keypress114114114

2015. 4. 20. 오후 7:30:18 >keydown82820

**Comment by smblott-github** [comment]
Hmm.  Your very first keystroke seems indistinguishable from `r`:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7228547/12abd376-e752-11e4-9bd2-ed980f6f0acd.png)

(Does anyone who knows anything about international keyboards know what's going on?)

**Comment by mrmr1993** [comment]
Wouldn't (rebasing and) merging #1474 be the easiest fix for this?

For dealing with key events directly, the [spec](https://dvcs.w3.org/hg/dom3events/raw-file/tip/html/DOM3-Events.html#widl-KeyboardEvent-key) indicates that we should be able to get the correct character from `KeyboardEvent.key` when [Chromium issue 227231](https://code.google.com/p/chromium/issues/detail?id=227231) is resolved.

> (Does anyone who knows anything about international keyboards know what's going on?)

`event.keyCode` is derived from [this algorithm](https://dvcs.w3.org/hg/dom3events/raw-file/tip/html/DOM3-Events.html#legacy-key-models). Usually, this means that the `keyCode` represents the ASCII character code of the symbol that *would have been* in that position in `en-US` when the actual character is Unicode-only. This information is effectively useless for non-Latin layouts, and often misleading in Latin ones too.

**Comment by smblott-github** [comment]
> Wouldn't (rebasing and) merging #1474 be the easiest fix for this?

Right enough.  I didn't spot that this and #1474 are related.

**Comment by smblott-github** [comment]
Should be fixed (iframes).
