### ISSUE TITLE
Smooth scrolling does not work if you enable chromes experimental smooth scrolling.

### ISSUE THREAD

**Issue by Darksonn** [philc/vimium#1576]
Chrome has an experimental feature enabling smooth scrolling with the mouse. If you enable it, the smooth scrolling in vimium stops being smooth.

It can be enabled at the following link if you use linux
chrome://flags/#enable-smooth-scrolling

I use vimium 1.49, chrome 42.0.2311.90 on debian sid.

**Comment by smblott-github** [comment]
That flag doesn't affect Vimium's smooth scrolling for me (41.0.2272.89-1).  Could it be a 42 issue?

**Comment by smblott-github** [comment]
Update.  I'm not seeing this issue on 42.0.2311.90-1 either.

**Comment by mrmr1993** [comment]
@darksonn, do you have any other flags enabled? We've had issues with them before.

**Comment by Darksonn** [comment]
The only other flag I have is scroll prediction. However I already had enabled this before I got an issue.

**Comment by mrmr1993** [comment]
Does disabling it fix the issue?

**Comment by Darksonn** [comment]
No. It also doesn't happen on my laptop.

**Comment by mrmr1993** [comment]
Okay. Can you open a chromium issue with the details you posted here, and post your OS, Chrome version, etc.?

**Comment by Darksonn** [comment]
Reinstalling google chrome and removing `~/.config/google-chrome` fixed the issue, it must have been some weird issue with the chrome installation. Do you still want me to post the issue?

**Comment by mrmr1993** [comment]
If it's a corrupt Chrome config, they won't be able to do anything anyways; I wouldn't create an issue for it.
