### ISSUE TITLE
Broken exclusion rules (possibly related to web navigation)

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1578]
With the exclusion rule: `https?://www.facebook.com/ jk`, `j` and `k` are excluded on the Facebook home page, but not on any other Facebook pages.

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7312972/5ae19426-ea4c-11e4-9e20-4d01636fa139.png)

Clicking on "Stephen", the URL changes, but our active exclusion rule does not.  Changing tab and coming back fixes things (because we check the active exclusion rule on `focus`).  Similarly, now clicking on "Home", the exclusion rule isn't picked up until there's a focus event on the window.

This might have something to do with Web Navigation.

**Comment by mrmr1993** [comment]
@smblott-github I've pushed #1579, which fixes this.
