### ISSUE TITLE
Grey box at bookmarks bar with Hacker Vision after 1.50 update

### ISSUE THREAD

**Issue by Sebelino** [philc/vimium#1583]
I use the [Hacker Vision](https://chrome.google.com/webstore/detail/hacker-vision/fommidcneendjonelhhhkmoekeicedej) extension together with Vimium. After upgrading to 1.50, a huge grey box appears when bringing up the bookmarks/URL/history bar. It worked fine in 1.49.

With 1.49:

![selection_031](https://cloud.githubusercontent.com/assets/837775/7348198/cf519c98-ecef-11e4-8002-25e53389ae8b.png)

With 1.50:

![selection_032](https://cloud.githubusercontent.com/assets/837775/7348205/d79a7a32-ecef-11e4-95d2-432507a660d6.png)

**Comment by smblott-github** [comment]
Thanks @Sebelino.  The Vomnibar's implementation has indeed changed in several ways.  It's now an iframe with `background-color: transparent`.  Hacker Vision is diddling with the CSS, arguably when it shouldn't.

**Comment by smblott-github** [comment]
OK, @Sebelino.  Thanks for the report.  @mrmr1993 fixed this in #1590.
