### ISSUE TITLE
<input type="submit"> buttons activated but steal focus

### ISSUE THREAD

**Issue by medawar** [philc/vimium#1584]
#1342 fixed the clickability issue (with [f]) of \<input type="submit"\> buttons but these buttons still steal the focus once clicked with [f]. Pressing [Esc] is required to return to normal input flow.

Prior to the 1.47 regression and loss of clickability this was not the case.

**Comment by smblott-github** [comment]
Thanks @medawar.  Could you provide an example site, please?

**Comment by medawar** [comment]
http://oaa-accessibility.org/testsuites/test/11/

Please try 'Submit control' and 'Reset control' buttons.

**Comment by smblott-github** [comment]
@medawar.  Are you saying the issue goes beyond "Submit" buttons (but perhaps is just showing up there, for you)?

**Comment by medawar** [comment]
@smblott-github I meant to say it seems to be narrower than the class of all \<input type="submit"\> buttons. So far I have only seen it happen in case of \<input type="submit" onclick="return somefunction()"\> buttons. There many cases of \<input type="submit"\> buttons, for example 'Change Content' button on [this W3Schools example](http://www.w3schools.com/ajax/ajax_example.asp), which don't seem to present the same issue.

In the OAA example provided earlier it's a simple onclick="return false". I have also seen it happen for onclick="return loadHtml([arguments])" in case of two search engines.
