### ISSUE TITLE
Vimium 1.50: Excluded keys string collapses spaces

### ISSUE THREAD

**Issue by infokiller** [philc/vimium#1585]
For example, if I set the string "j k" to site-specific excluded keys, after saving the options and opening them again it becomes "jk".

**Comment by smblott-github** [comment]
@infokiller.  Right enough.  That's not necessary.

**Comment by infokiller** [comment]
You mean that the parsing is not affected by the whitespace?

**Comment by smblott-github** [comment]
No, I mean collapsing the whitespace is not necessary.  We'll fix it.
