### ISSUE TITLE
Vimium 1.50: Alt+[jkl;] doesn't work for sites with excluded keys

### ISSUE THREAD

**Issue by infokiller** [philc/vimium#1586]
I've set custom keyboard bindings as following:

```
map j scrollLeft
map ; scrollRight
map k scrollDown
map l scrollUp

map <a-j> previousTab
map <a-;> nextTab

map <a-k> goBack
map <a-l> goForward
```

In sites where I defined excluded keys (like GMail and Trello), only <a-;> works while the other Alt bindings don't.

**Comment by smblott-github** [comment]
Confirmed.  That's a regression.  Thanks for the report, @infokiller.
