### ISSUE TITLE
'b' and 'w' work differently with Chinese in visual mode

### ISSUE THREAD

**Issue by depctg** [philc/vimium#1592]
After pressing 'w',the cursor goes to the next **English character**
After pressing 'b' ,the cursor goes to the previous **Chinese word**

---

For example
>Git是一个分布**[式]**的版本控制系统，最初由Linus Torvalds编写

after pressing 'b'
>Git是一个**[分]**布式的版本控制系统，最初由Linus Torvalds编写

after pressing 'w'
>Git是一个分布式的版本控制系统，最初由**[L]**inus Torvalds编写

---

the sentence :
>Git是一个分布式的版本控制系统，最初由Linus Torvalds编写

**Comment by smblott-github** [comment]
Ah, @depctg.  How Anglo-centric!  We're using this for word movements...

```
regexp = /[A-Za-z0-9_]/
```

Any idea what it should be?

**Comment by depctg** [comment]
In my view 'b' works perfectly and I think 'w' should work like 'b'....

发自我的 iPhone

**Comment by smblott-github** [comment]
@depctg: Yes. `b` uses a native Chrome movement.  `w` does not (because the native Chrome equivalent is `e`, which isn't quite right for `w`).
