### ISSUE TITLE
Visual Mode Search Ambiguity

### ISSUE THREAD

**Issue by dhalima3** [philc/vimium#1593]
Google Chrome version: 42.0.2311.90 (Official Build) m (32-bit)
Vimium version: 1.50

Does the search command for visual mode (p/P in visual mode) mean that we will be able to search through the selected text or that the text will be searched on a search engine (basically activating the 'opening contents of clipboard' command)?  

Currently, the behavior I experience when I press p/P in visual mode, the command 'opening contents of clipboard' activates.  Is this correct?

**Comment by majkinetor** [comment]
It searches selected text on a search engine here.

**Comment by smblott-github** [comment]
Updated the explanation in the release notes: 2de9bf879792b4be50efc09ee26d16008bb73ae7.

**Comment by dhalima3** [comment]
Thanks @smblott-github !
