### ISSUE TITLE
In v1.50, the vomnibar is always visible and won't close on certain sites

### ISSUE THREAD

**Issue by ManiacalAce** [philc/vimium#1594]
I am on Chrome Version 39.0.2171.71 (64-bit) on Arch Linux.
When I open this site: http://motorbeam.com/, the vomnibar is always visible and won't close or even work.

**Comment by smblott-github** [comment]
Yikes.  Confirmed.
What's more, `Ctrl-r` doesn't event get rid of it...

**Comment by mrmr1993** [comment]
If we create the Vomnibar (and probably all UIComponents, or even the whole Vimium UI) in a shadow DOM and just inject vomnibar.css there, we can stop competing with page css altogether.

**Comment by smblott-github** [comment]
#1613 seems to fix this.
Not sure if it's the best approach.
