### ISSUE TITLE
Activating visual mode while scrolling doesn't stop scrolling

### ISSUE THREAD

**Issue by zacharydenton** [philc/vimium#1596]
To reproduce: go to a long web page, hold down `j`, press `v` while `j` is held down, then release all keys. The browser will continue scrolling until you press `v` again, or `esc` a couple times.

**Vimium** 1.50

**Google Chrome Revision**	42.0.2311.90 (Official Build) m (32-bit) 5d28207cac889976c94107da36f69ae01ff0223e-refs/branch-heads/2311_82@{#2}
**OS**	Windows 
**Blink**	537.36 (@193294)
**JavaScript**	V8 4.2.77.14
**Flash**	17.0.0.169
**User Agent**	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by philc** [comment]
Interesting behavior. Nice find =)

**Comment by mrmr1993** [comment]
PR #1597 seems to fix this.

**Comment by smblott-github** [comment]
Thanks @zacharydenton.  This is fixed with #1597.
