### ISSUE TITLE
Feature Request: Increment last number in current URL

### ISSUE THREAD

**Issue by hyh1048576** [philc/vimium#1602]
There are lots of URL's like

http://example.com/pics/1.png
http://example.com/pics/2.png
http://example.com/pics/3.png

or

http://example.com/article_part_2.html
http://example.com/article_part_3.html

So it might be a good idea to have `<C-a>` and  `<C-x>` implemented. 

Obviously `<C-a>` should take one from http://example.com/article_part_2.html to  http://example.com/article_part_3.html and `<C-x>` goes the reverse way.

[Personally I prefer more newbie-friendly keys, like `+` and `-`, but `<C-a>` and `<C-x>` are also good.]

**Comment by mrmr1993** [comment]
@hyh1048576 this looks to be dup of #664. You might want to try and resurrect the discussion there instead, to try and flesh out how this could/should be implemented.
