### ISSUE TITLE
Selecting with 'v' gets at most one character

### ISSUE THREAD

**Issue by joshzimmerman** [philc/vimium#1603]
I'm on Chrome 42.0.2311.90 and Vimium 1.50.

When I use '"v" to select text and then vim motions to move around, I can only select one character. Similarly, if I hit "shift + v" and then start moving around I can only get one character.

Interestingly, if I hit any combination of two presses (e.g. "v" then "v",  "v" then "shift+v", etc), I get the expected behavior.

This behavior happens both in and out of incognito mode (the only extension loaded in incognito mode was vimium).

If there are any more details you need to help you track down the issue, I'd be more than happy to help get them!

**Comment by smblott-github** [comment]
If there's no initial selection, then Vimium starts in caret mode.  You can move the caret with vim-like movements or find (`/`).  When the caret's where you want it, `v` enters visual mode.  (If we didn't do it this way, you'd have to move both ends of the selection separately.)

This shouldn't happen if there *is* a (visible) existing selection.  Then visual mode launches directly with that selection.

**Comment by joshzimmerman** [comment]
Ah ha, okay. That makes sense; I hadn't considered the fact that there's no cursor by default in the browser. Thanks for the quick response!
