### ISSUE TITLE
Excluding key also excludes alt-key

### ISSUE THREAD

**Issue by romgrk** [philc/vimium#1606]
My personnal mapping stopped working in the last 2-3 days.
e.g.: map <a-j> go-next-tab
But only on pages where 'j' is excluded. Also, removing the exclusion restores the map.

**Comment by smblott-github** [comment]
Thanks, @romgrk.  Might this be a dup of #1586?  If so, it's a bug in 1.50 and has been fixed in `master`.

**Comment by romgrk** [comment]
Yep, duplicate.
