### ISSUE TITLE
Customize scroll page size for d, u in the same manner as customizing scroll step for j, k

### ISSUE THREAD

**Issue by x-ji** [philc/vimium#1612]
Coming from Vimperator, I can't help but feel `d` and `u` don't scroll the page enough. For me, `j`, `k` are already good enough for small amount of scrolling, so `d` and `u` should be used to do much greater scrolling. Maybe at least we can put in an option in the options page in the same way as we put an option for `j` `k`? I'd be happy to do a pull request if that's possible.

**Comment by smblott-github** [comment]
As an alternative, you could do:

```
map u scrollFullPageUp
map d scrollFullPageDown
```

which should scroll a bit faster.

**Comment by x-ji** [comment]
Thank you. That's cool. I can use that for now. But I would still like to have a finer control if possible. Also it seems that a remapping in the style of vim map d 2d etc. would not work.
