### ISSUE TITLE
Open link in new tab workflow has changed

### ISSUE THREAD

**Issue by ic80** [philc/vimium#1617]
Hi Folks,

Has the open link in new tab workflow changed?

Prior to 1.50 I performed the following to open a new link:

> press 'f' > press 'shift' > press link hint > tab opens in background

However since 1.50 the workflow has changed to:

> press 'shift+f' > press link hint > tab opens in background

The difference here, at least for me, is that in previous versions the act of opening a new link was decided after pressing 'f'. Specifically, the action of opening a link hint was bound to 'f' and didn't require you to decide which action you're taking before hand. I feel that this is a much better way to work.

If the intention was to change the functionality, is it possible to make it an option of choosing between the new way and the old way. If not, then could you please let me know how to revert to (and keep) 1.49 which allows the previous way of working.

Incidentally, love this extension, been using it for ages and for a vi lover it's great.

Thanks much :)

**Comment by mrmr1993** [comment]
@ic80 I can't tell from your comment; has changing mode after link hints are active stopped working for you?

Choosing the mode early (`f` vs `F`) has always been an option, but changing mode once link hints are open (by pressing `shift` or `ctrl`) should still work too. If it has stopped working, it certainly isn't intentional.

**Comment by ic80** [comment]
@mrmr1993 Thanks for such a quick reply.

At the moment you can press 'f' and hold shift while choosing a link hint, and the link will open in a background tab but it's not always consistent as sometimes it will open in the same tab. Quite a while back I noticed this in a much earlier version of vimium as it used to show the action rapidly cycling between "open in new tab" and "open in current tab" in a small dialog at the bottom left of the browser window.

This previous issue got me in the habit of pressing and releasing shift before selecting a link hint which always opened in a background tab consistently and is how I noticed it no longer working as soon as the 1.50 update came through.

So, holding shift works but not always, and pressing shift beforehand doesn't seem to work at all anymore.

Thanks :)

**Comment by ic80** [comment]
Small Update: I just checked and when pressing f, holding shift will still show a rapid cycling between "open link in current tab" and "open link in new tab". So depending on when the link hint event catches your entry you might get a new tab or the current tab.

**Comment by mrmr1993** [comment]
@ic80 I can't repro this on Linux; I presume you're in Windows? I've opened PR #1618, which I expect will fix this.

Just to clarify: the intended behaviour is that holding the modifier key keeps the new mode active. This should work for you again once the fix lands in a release.
