### ISSUE TITLE
Visual select text nodes

### ISSUE THREAD

**Issue by xged** [philc/vimium#1620]
Unable to visually select text from an insert box (normal mode).

**Comment by smblott-github** [comment]
Thanks, @xged, but more detail would help.

What do you do?  What do you expect to happen?  What does happen?

**Comment by xged** [comment]
Eg in [stackoverflow](http://stackoverflow.com/questions/ask) `v` does not select enything in the top frame, but does it in the bottom one.

**Comment by smblott-github** [comment]
On stackoverflow, I get this...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7410265/1a5a97d0-ef25-11e4-8288-7e1288af0bc1.png)

... which looks ok.

More generally:
- Visual mode only selects text from text nodes, not inputs (like text areas).
- Visual mode also looks for a certain minimum length of text in a text node.  This is a heuristic to avoid selecting text in banners and headers.

**Comment by xged** [comment]
@smblott-github skip threw tips ;)
