### ISSUE TITLE
f/F always opens link in new tab... but only on Google.com

### ISSUE THREAD

**Issue by horak** [philc/vimium#1625]
For some odd reason `Cmd-f` and `Cmd-F`, when activated only on links on google.com, always open that link in a new tab. I've disabled all other extensions and it persists. Here is the catch: it doesn't happen in incognito ugh :persevere: 

Any idea what's going on?

**Comment by mrmr1993** [comment]
Sounds like your google settings are set to open links in a new tab (and incognito is back to normal because the cookie with your settings isn't present). You can check this by seeing whether clicking a link with the mouse also opens it in a new tab.

**Comment by horak** [comment]
Doh. Thanks for the quick reply!
