### ISSUE TITLE
On restart, content scripts only reinjected into main/top frame

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1628]
Notwithstand this:

```Coffeescript
allFrames: contentScripts.allFrames
```

when Vimum restarts and we reinject the content scripts, only the main/top frame seems to restart.  Try it [here](http://www.quackit.com/html/templates/frames/frames_example_2.html).

(Separately, I wonder whether we wouldn't be better moving the reinjection code to the bottom of `main.coffee`, after everything else is initialised.)

**Comment by gdh1995** [comment]
It seems that this line should be:
``` js
allFrames: content_scripts.all_frames
```
Here is an example of `chrome.runtime.getManifest().content_scripts[0]`:
``` json
{
    "all_frames": true,
    "css": [
        "content_scripts/vimium.css"
    ],
    "js": [
        "lib/frontend_utils.js",
        "lib/keyboard_utils.js",
        "lib/dom_utils.js",
        "lib/handler_stack.js",
        "content_scripts/link_hints.js",
        "content_scripts/vomnibar.js",
        "content_scripts/scroller.js",
        "content_scripts/marks.js",
        "content_scripts/vimium_frontend.js"
    ],
    "matches": [
        "<all_urls>"
    ],
    "run_at": "document_start"
}
```

**Comment by smblott-github** [comment]
Excellent.  Thanks for that, @gdh1995.
See https://github.com/philc/vimium/commit/9fdb630d891019620041041001b9dff022008ee0.

**Comment by gdh1995** [comment]
Firstly, `main.coffee` usually runs much faster than so many `content_scripts/*.coffee`.

So, if we keep it at the top, nothing will go into an error - moving it to the bottom also does not do any harm, though.

**Comment by mrmr1993** [comment]
@gdh1995 the actual injection code is inside an asynchronous callback, so it shouldn't slow down the normal initialisation of `main.coffee` at all. Or am I missing something?

**Comment by gdh1995** [comment]
Sorry I forgot this. Yes, it is indeed executed in 0 ms or 16ms in my tests. So nothing should be changed.
