### ISSUE TITLE
Map d to the down arrow key

### ISSUE THREAD

**Issue by koalazen** [philc/vimium#1631]
I noticed that on some pages 'd' does not necessarily scroll down if the focus is not on the scrollable content part. I need to click on that part of the page before being able to use 'd' to scroll down.

I also noticed that most of the time on these pages the 'down arrow' key does the scrolling. So could we map 'd' to 'down arrow' (and 'u' to 'up arrow') for a more effective vimium scrolling ?

**Comment by smblott-github** [comment]
Thanks, @koalazen.  That can happen.  Picking the right thing to scroll is not always obvious.  Could you post a link to the page you're having difficulty with, and I'll take a look.

**Comment by koalazen** [comment]
I am sorry I am facing this issue on an internal page of my company. I don't know any other examples. But I use this internal page a lot and it is very annoying :) It is a code browsing app with a file browser on the left and the file's code occupying the rest of the screen. The code part is not focused by default which forces me to click every time I load a file. On that app down arrow scrolls down the code but I would rather do it with vimium keys.

**Comment by smblott-github** [comment]
@koalazen.  Do you know whether the right-hand side is in a separate frame?  If it is, you'd be able to select it with `gf`.

**Comment by koalazen** [comment]
I tried gf and it doesn't work. So I guess this internal app is not using frames.
