### ISSUE TITLE
Partially disabling Vimium in Gmail

### ISSUE THREAD

**Issue by horak** [philc/vimium#1633]
I'd like to be able to access all native gmail keybindings but still make use of `f`. 
![screenshot at may 02 14-27-40](https://cloud.githubusercontent.com/assets/1111424/7442247/68163b06-f0d7-11e4-947c-c085913e840d.png)

unfortunately, `f` isn't registering. I've also disabled any `f` related gmail keybindings but it's a no go.

Love the extension :+1:

**Comment by smblott-github** [comment]
@horak.  Currently, the best we can do is to list all of the gmail shortcuts you want to use. (So, you list the gmail shorcuts you want to use, *not* the Vimium shortcuts you *don't* want to use.)  My own gmail exclusions look like...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7442363/8741bd50-f106-11e4-9e74-c59d5671dc50.png)

Tip, you can edit your exclusion rules by clicking on the Vimium icon...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7442372/e03e9d74-f106-11e4-90c4-a4f2d5d6cca3.png)

**Comment by horak** [comment]
:+1: Thanks so much :)
