### ISSUE TITLE
A race condition about `borderWas` when highlighting body

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#1634]
In vimium_frontend.coffee +341: @@ window.`focusThisFrame`
```
borderWas = document.body.style.border
document.body.style.border = '5px solid yellow'
setTimeout((-> document.body.style.border = borderWas), 200)
```
Then it's easy to make body's border stay yellow:
* quickly click `gF` (`mainFrame`) again and again

After a while, a new `borderWas` will become '5px solid yellow', which is set by `focusThisFrame` before.

Fix:
* record `borderWas` as a global variable, and clean it everytime timeout is triggered

**Comment by mrmr1993** [comment]
Alternatively:
use `document.body.className.add("vimiumHighlightedBody")` and `document.body.className.remove("vimiumHighlightedBody")`, and add 

```css
body.vimiumHighlightedBorder {border: 5px solid yellow !important;}
```

to vimium.css, so we don't have to track the old style at all.

**Comment by gdh1995** [comment]
Good idea!
> use `document.body.className.add("vimiumHighlightedBody")``

**Comment by mrmr1993** [comment]
Since the border is always applied to the body, it will only show on the edges of the body which are visible. I've made [a JSFiddle](http://jsfiddle.net/1cjd7xfa/) which illustrates the problem (the red border), and my proposed solution (the yellow border).

In essence, to make sure we always show the border flash, I think we should overlay an element (in a shadow DOM) on the body, using the style:

```css
position: fixed;
top: 0px;
left: 0px;
width: calc(100% - 10px);
height: calc(100% - 10px);
padding: 0px;
margin: 0px;
border: 5px solid yellow;
pointer-events: none;
```

**Comment by gdh1995** [comment]
LGTM. And it is indeed better than adding a border to `<html>`, which is proved to not work.
> In essence, to make sure we always show the border flash, I think we should overlay an element (in a shadow DOM) on the body

**Comment by smblott-github** [comment]
@mrmr1993.  You proposal also works better if the content doesn't file the viewport...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7494499/dbbe2cd2-f3ff-11e4-96d2-343806033415.png)

**Comment by gdh1995** [comment]
commit #14b8370dcd87a969ebd5a521877d4c52e18b4b14

**Comment by smblott-github** [comment]
We should keep this open til it's sorted.

**Comment by gdh1995** [comment]
One question: in a XML page, like http://qz.com/feed/ in #1640 , will an overlay node (in a shadow DOM) still work?

An advice:

>  I've made a JSFiddle which illustrates the problem (the red border)

I replace `body {}` with `html {}` in this page, and then the border works.

So, we can use both `.classList.add` and an overlay.

**Comment by mrmr1993** [comment]
> I replace `body {}` with `html {}` in this page, and then the border works.

I can't reproduce that; in the JSFiddle, I'm getting the same problem on `html` as on `body`:

![screenshot_2015-05-06-17-58-57](https://cloud.githubusercontent.com/assets/1847343/7498571/ca207588-f419-11e4-86f7-b28efa2d66f5.png)

> will an overlay node (in a shadow DOM) still work?

I expect so, but I have no way of testing for the next few days.

**Comment by gdh1995** [comment]
Um, I made a mistake: `<html>`'s border is not in the one of `<div>`, which is good, but depressingly, it is still overlayed by the yellow.

**Comment by gdh1995** [comment]
Test in XML pages:
``` javascript
var shadowDOM = shadowWrapper.createShadowRoot();
var dom1 = document.createElement("div");
......
console.log("mask:", dom1.style);
shadowDOM.appendChild(dom1);
document.documentElement.appendChild(shadowWrapper); // or document.body
```
Then, log shows `mask: null`, and nothing is visible.

**Comment by mrmr1993** [comment]
@gdh1995 I meant that we should set the `class` attribute directly on the `<div>` and have that style applied from vimium.css.

The only potential sticking point is if vimium.css doesn't apply to XML pages; then all of our UI is unstyleable and we'll have to stop injecting any of it on such pages.

**Comment by gdh1995** [comment]
Adding class to a XML document's body works:
![image](https://cloud.githubusercontent.com/assets/5547703/7515586/d8c1ec2a-f4fa-11e4-8361-d9c5a4ed75c3.png)

* vimium.css is injected by adding it to `manifest.json`, not `appendChild('<style>')`
* classes and id both work

**Comment by mrmr1993** [comment]
> Adding class to a XML document's body works

But `document.body.style != null`, and we're not looking to style the body. Can we style a `<div>` in the same way?

> vimium.css is injected

I know. My question should have been:

Will those injected styles apply to elements we create and inject, even though `Element.style` is `null`?

**Comment by gdh1995** [comment]
> Will those injected styles apply to elements we create and inject
Maybe it's Yes:
![image](https://cloud.githubusercontent.com/assets/5547703/7515756/5322bbce-f4fc-11e4-9bfe-ab54240e1446.png)

**Comment by mrmr1993** [comment]
> Maybe it's Yes:

Looks like it is to me. Thanks @gdh1995.

**Comment by gdh1995** [comment]
Error:
If I add only class names, nothing will be applied!

**Comment by gdh1995** [comment]
An ugly fix is to add `.vimHide` and '#vimHUD.vimHide, #vimOmni.vimHide, #vimLinkHints.vimHide, ...' - looks terrible.
So, a switch may be a must.

**Comment by mrmr1993** [comment]
@gdh1995 I'm struggling to follow what you're saying. I'm proposing changing `window.focusThisFrame` in vimium_frontend.coffee to:

```coffee
window.focusThisFrame = do ->
  highlightedFrameElement = document.createElement "div"
  _shadowDOM = highlightedFrameElement.createShadowRoot()

  # Inject stylesheet.
  _styleSheet = document.createElement "style"
  if _styleSheet.style?
    _styleSheet.innerHTML = ""
    _shadowDOM.appendChild _styleSheet
    # Load stylesheet.
    xhr = new XMLHttpRequest()
    xhr.onload = (e) -> _styleSheet.innerHTML = xhr.responseText
    xhr.open "GET", chrome.runtime.getURL("content_scripts/vimium.css"), true
    xhr.send()

  _frameEl = document.createElement "div"
  _frameEl.className = "vimiumReset vimiumHighlightedFrame"
  _shadowDOM.appendChild _frameEl

  (request) ->
    if window.innerWidth < 3 or window.innerHeight < 3
      # This frame is too small to focus. Cancel and tell the background frame to focus the next one instead.
      # This affects sites like Google Inbox, which have many tiny iframes. See #1317.
      # Here we're assuming that there is at least one frame large enough to focus.
      chrome.runtime.sendMessage({ handler: "nextFrame", frameId: frameId })
      return
    window.focus()
    shouldHighlight = request.highlight
    shouldHighlight ||= request.highlightOnlyIfNotTop and not DomUtils.isTopFrame()
    if shouldHighlight
      document.documentElement.appendChild highlightedFrameElement
      setTimeout (-> highlightedFrameElement.remove()), 200
```

and adding to vimium.css:

```coffee
div.vimiumHighlightedFrame {
  position: fixed;
  top: 0px;
  left: 0px;
  width: 100%;
  height: 100%;
  padding: 0px;
  margin: 0px;
  border: 5px solid yellow;
  box-sizing: border-box;
  pointer-events: none;
}
```

As far as you can see, will this cause any problems?

**Comment by gdh1995** [comment]
I's sorry that I was too impatient to finish a whole test before reporting it.

The main problem is: (in a XML document)
* any dom node created by javascript has no style, which does not include `document.body`
* `className` almost does not work at all, except that:
* rules like `#id {}` and `#id.className {}` can be applied to nodes

The new `focusThisFrame` has some bugs:
* `.vimiumHighlightedFrame` should be `#vimiumHighlightedFrame`
* `if not _styleSheet.style`, then we should not `_shadowDOM.appendChild _frameEl`, but `highlightedFrameElement.appendChild _frameEl`

Then:
``` coffeescript
window.focusThisFrame = do ->
  highlightedFrameElement = document.createElement "div"
  _frameEl = document.createElement "div"
  _frameEl.className = "vimiumReset"
  _frameEl.id = "vimiumHighlightedFrame"

  # Inject stylesheet.
  if highlightedFrameElement.style?
	_shadowDOM = highlightedFrameElement.createShadowRoot()
	_styleSheet = document.createElement "style"
    _styleSheet.innerHTML = ""
    _shadowDOM.appendChild _styleSheet
    # Load stylesheet.
    xhr = new XMLHttpRequest()
    xhr.onload = (e) -> _styleSheet.innerHTML = xhr.responseText
    xhr.open "GET", chrome.runtime.getURL("content_scripts/vimium.css"), true
    xhr.send()
	_shadowDOM.appendChild _frameEl
  else
    highlightedFrameElement.appendChild _frameEl

  (request) ->
    if window.innerWidth < 3 or window.innerHeight < 3
      # This frame is too small to focus. Cancel and tell the background frame to focus the next one instead.
      # This affects sites like Google Inbox, which have many tiny iframes. See #1317.
      # Here we're assuming that there is at least one frame large enough to focus.
      chrome.runtime.sendMessage({ handler: "nextFrame", frameId: frameId })
      return
    window.focus()
    shouldHighlight = request.highlight
    shouldHighlight ||= request.highlightOnlyIfNotTop and not DomUtils.isTopFrame()
    if shouldHighlight
      document.documentElement.appendChild highlightedFrameElement
      setTimeout (-> highlightedFrameElement.remove()), 200
```

``` css
#vimiumHighlightedFrame.vimiumReset {
  position: fixed;
  top: 0px;
  left: 0px;
  width: 100%;
  height: 100%;
  padding: 0px;
  margin: 0px;
  border: 5px solid yellow;
  box-sizing: border-box;
  pointer-events: none;
}
```

**Comment by gdh1995** [comment]
Another crash:
``` coffeescript
node = document.createElement "div"
node.innerHTML = "test 1"         # Then node is "<div>test 1 </div>"
node.innerText                           # it's undefined
node.innerText = "hello"             # Then node is still "<div>test 1 </div>"

document.body.innerText           # non-empty text
document.body.innerText = ""    # the page content is cleaned
```

This means, `HUD.displayElement().innerText = text` will not work, and we have to escape `text` by ourselves and then set `innerHTML`

**Comment by mrmr1993** [comment]
@gdh1995 I've pushed #1648 using my solution above. Trying to support XML documents correctly is a lost cause, as I discovered trying to solve #1640. Since the Vomnibar, link hints, the HUD, and input hints are all broken on XML pages, I don't think it's worth the effort to fix the border flash and have it our sole functional bit of UI.

**Comment by gdh1995** [comment]
> Trying to support XML documents correctly is a lost cause
Um, so is it. Then when #1648 is closed, I will close this.

**Comment by rrsahuone** [comment]
We must have to pay attention while choosing a correct company, because we are going to deal with all our costly valuables to them. We are here to help you, so you do not have any need to concern about movers and packers. When you once join with packers & movers in Bangalore , you will never reckon to go with other movers and packers.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by rrsahuone** [comment]
When you are thinking to shift your useful and costly products, then this become essential to select best packer and moving service support agency. Otherwise you may get great reduction, and we know that it is not tolerable. Packers and movers solutions are available all around us. We just have to discover it. Cost-effective and reasonable provides are offered by trustable movers and packers companies.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers in Delhi">Packers and Movers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by rrsahuone** [comment]
You can get best solutions by certified movers and packers companies; you just have to see best in your locality. Few methods which can help you to discover packers and movers organization of your locality are as:

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers in Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a>

**Comment by rrsahuone** [comment]
You have to surf for the best companies of your locality and look for their email address and variety. We can discover their status feedback from their official sites; it can help you to select from a long record.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</
