### ISSUE TITLE
Make the Vomnibar more useful ("omni" mode)

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1639]
There are some usability issues with the vomnibar...

- We should be filtering out duplicate URLs.  For example, querying "Facebook", I get the domain, a history entry and a bookmark, all of which point to the same URL.  Two of the top slots are therefore wasted.

- Many history entries are useless.  For example, query "Google Drive", and see a long list of documents which are otherwise indistinguishable from one another.  It's not clear what we can do about this.  Chrome's omnibox does not offer these suggestions.

- Search (on Google) creates two new history entries each time.  Three searches create six new history entries.  In the example below, this is what I get after searching for "Vimium&ttt" three times.  In a live Chrome instance (where the same search is often used again and again) the history becomes populated with junk...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7471590/d9a7157e-f320-11e4-9d2d-edadb66f5825.png)

- We could make use of the "topSites" API.  Chrome does not a bad job of deciding which pages the user visits frequently.

- I'd also like to see search completion (#1635, although that's very much still a WIP).

Some of the above may require filtering the history based on specific URL patterns for specific sites.  Doing that wouldn't be so bad.  Google is a great search engine not because of PageRank, but because of 1001 customised  tricks they apply to improve the UX.

**Comment by mrmr1993** [comment]
For the history completer, we might be able to use transition types to filter some of these less useful suggestions.

Related: we might want to add history entries with type `generated`, `typed`, `keyword`(/`keyword_generated`?) or `auto_bookmark` for navigations made from the Vomnibar, depending on the completer. I think all of ours are currently `auto_toplevel`, which isn't really ideal.
