### ISSUE TITLE
A memory leak in Exclusions.RegexpCache

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#1641]
`Exclusions.RegexpCache` is to cache regexps, but it hasn't been cleaned anywhere!

If opening the popup page and editing patterns a lot times:
* Everytime a key is up, `initPopupPage.updateState` is triggered in `options.coffee`
* `Exclusions.getRule` calls `RegexpCache.get` many times
* No regexp will be removed, even if it only means a temporary `rule.pattern`

So , here is a memory leak in `RegexpCache`. Its cost is not large, but it's indeed a waste.

**Comment by smblott-github** [comment]
Yes, @gdh1995.  We need a cache implementation of some kind (like the one in #1635, [here](https://github.com/philc/vimium/pull/1635/files#diff-9d24083a8251f08044c0aa4871e4574cR213)).  There is a substantially worse space leak in `HistoryCompleter`.  There, I get at least two new entries for every search (even repeat searches).  We really need a proper, general-purpose LRU cache.

**Comment by gdh1995** [comment]
Maybe we can set an interval to clean `HistoryCompleter.*` inserveral minutes.

`Exclusions.RegexpCache` is easy to rebuild: just clean it whenever a popup page closes

**Comment by smblott-github** [comment]
Thanks, @gdh ... 0b0ca954d568505934576c2c138a371b48dabbca.
