### ISSUE TITLE
Caret mode

### ISSUE THREAD

**Issue by joshmccall221** [philc/vimium#1642]
Stumbled upon caret mode accidentally but would like to figure out how to get to reliably work. 

Hit 'v' receive "no useable selection, entering caret mode.."

Or

If visual mode selects to much text how can you modify your selection?
* v + l /k will increase selection left or down, maybe shift+ l/k de-selects text from the from the top of the selection in a left / down movement. 

Workflow / use case: 

* Using the caret to track along when reading an article.  
* Using visual mode to select a paragraph but the visual mode picks the wrong spot/ too much/little text

**Comment by smblott-github** [comment]
Thanks @joshmccall221.  Your *track along when reading an article* use case wasn't really one which was considered.  Caret mode was originally intended as a bridge to visual mode in the absence of an existing selection.  It might work for you, it might not.  It really depends on the web site.

Some tips...
- In caret mode, `v` (or `V`) take you visual (line) mode.
- In visual mode, `c` takes you to caret mode.
- In visual mode, `o` focuses the opposite end of the selection (as in vim).  This allows you to position one end of the selection, hit `o`, then position the other end.
- Find (`/`) works in caret and visual modes.

The most common use case (for me) is to first establish a selection with find (`/`), then enter visual mode.

**Comment by aemonge** [comment]
Hey! This tips should be on the "?" help screen xD

Cheers!

**Comment by fabriziobertoglio1987** [comment]
clear explanation [in the wiki][1]

[1]: https://github.com/philc/vimium/wiki/Visual-Mode

**Comment by misraelson** [comment]
@smblott-github When in visual mode pressing 'c' does not enter caret mode. It would be great to have a key to simply enter caret mode because it is SO useful. Maybe 'c' could enter caret mode? It's really nice to know where your cursor is and move it around in the page.
Thanks for making Vimium btw. Its so great
![Kapture 2021-11-03 at 19 26 18](https://user-images.githubusercontent.com/17835964/140247699-9ce11485-952a-4ee3-b2cc-3ef1c51b3fb7.gif)
e

**Comment by gdh1995** [comment]
@misraelson It's a known typo bug and will be fixed by #3877 .

**Comment by hasufell** [comment]
I have a non-standard keyboard layout. How do I redefine the movement keys in visual/caret mode etc?

**Comment by gdh1995** [comment]
@hasufell you may use `mapKey` to map a key to another one (only in Vimium) - see https://github.com/philc/vimium/wiki/Tips-and-Tricks#key-mapping .

If you need to use different `mapKey` rules in different modes (LinkHints / Visual / Find / Normal / ...), then you may try my customized version of Vimium, Vimium C (https://github.com/gdh1995/vimium-c), and it support a much more powerful `mapKey` (https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout)

**Comment by hasufell** [comment]
> @hasufell you may use `mapKey` to map a key to another one (only in Vimium) - see https://github.com/philc/vimium/wiki/Tips-and-Tricks#key-mapping .
> 
> If you need to use different `mapKey` rules in different modes (LinkHints / Visual / Find / Normal / ...), then you may try my customized version of Vimium, Vimium C (https://github.com/gdh1995/vimium-c), and it support a much more powerful `mapKey` (https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout)

`mapKey` doesn't work well. The link characters will not match what you type. I want to only change the mapping for the visual mode etc. `mapKey` changes it for everything, including "input" for the main feature: following links.
