### ISSUE TITLE
Not working on MHTML files

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#1645]
From [this comment](https://github.com/philc/vimium/issues/246#issuecomment-100489130) by @jmn on #246:

> Testing MHTML files in chrome canary (chrome://flags #save-page-as-mhtml) I noticed that vimium does not work for browsing these files. Chrome version 44.0.2396.0 canary (64-bit) and Chromium 44.0.2396.0 on Windows 8.1. For other local files, vimium does seem to work fine having enabled the option mentioned above ["Allow access to file URLs" checkbox].

**Comment by mrmr1993** [comment]
@jmn I've opened an issue for you here. Are you seeing any errors in the console (`F12` to open developer tools, `<esc>` to show the console if it's not already visible)?

**Comment by mrmr1993** [comment]
This issue is entirely caused by [Chromium issue 485457](https://code.google.com/p/chromium/issues/detail?id=486457). Since there is no possibility of a fix from our end, I'm going to close this.

@jmn, you can go and star [the Chromium issue](https://code.google.com/p/chromium/issues/detail?id=486457) if you want to help raise it's priority and/or to receive updates on it.

**Comment by smblott-github** [comment]
@mrmr1993.  Might it not be better to leave this issue open?  It gets better visibility that way, should other users come along with the same issue.

(Re-close if you'd prefer it that way.)

**Comment by philc** [comment]
Do we intend to act on this? Assuming not since it's a bug in chrome, let's
close so it doesn't clutter up the issue queue and add an FAQ if people
continue reporting it.
