### ISSUE TITLE
Implement feature toggles / flags for testing experimental code

### ISSUE THREAD

**Issue by dragon788** [philc/vimium#1646]
Per #1307 and mrmr1993's comments about feature toggles, if this isn't already on the radar I would heartily suggest placing it there. 

>We could certainly do with some kind of 'experimental options' in the options page, to allow enabling more controversial fixes like #1167, #1211, etc. either per-URL or globally. I especially feel like #1167 should be available for those who want it — it fixes a lot of annoyances on a lot of sites — but is perhaps too risky to ship and run everywhere by default.

>I don't like the idea of site-specific hacks very much. In some cases they might prove the only option (#1295 specifically springs to mind) though. I suggest a hacks folder, where each hack is a content script, enabled on new URLs by adding them to the matches in manifest.json. It nearly sounds too clean and easy.

**Comment by mrmr1993** [comment]
This looks like a dup of #1542. Although it might be worth quoting that comment (with a link to it, so we can see the context) there.

**Comment by dragon788** [comment]
Moved comment to better ticket and closing.
