### ISSUE TITLE
How to inject scripts to an iframe without `src`

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#1650]
In this page http://output.jsbin.com/raxorevane/1/edit?html,output :

Vimium can switch between two frames: the top  and the bottom-right. But there's an iframe for output content which has no `src` attribute, and its links are not selectable for LinkHints.

I used F12 and found no extension script was loaded, and so was it even when I delete the frame's `sandbox` attribute.

Is there any trick to inject any scripts - even manually triggered by executing something on window.top ?

**Comment by mrmr1993** [comment]
In general, adding [`"match_about_blank": true`](https://developer.chrome.com/extensions/content_scripts#match_about_blank) to all the places where we inject scripts or styles (including `manifest.json`) should do what you want. However, this might not work for your specific example @gdh1995, since (from the linked page):

> Content scripts cannot be inserted in sandboxed frames.

**Comment by gdh1995** [comment]
Thanks. Now my custom Vimium does work on a normal blank page.

While the sandboxed frames are annoying:
* content scripts may be injected. Then frameId is registered and "DOMContentLoaded" is fired.
* no Vimium's listener can be triggered.
* Vimium's onunload function is not called, which causes the frameId not cleaned
* then `nextFrame` does not work...

Anyway, `match_about_blank: true` works well at most websites. Then this issue has closed.

**Comment by mrmr1993** [comment]
Can you reopen this? This isn't fixed in `master` here.


> Now my custom Vimium does work on a normal blank page.

If you submit a PR with those changes, then we can get them included in `master`, so this issue can resolved for everyone else too.

**Comment by gdh1995** [comment]
I've pushed two commits to /gdh1995/vimium. They are:
* [ignore sandboxed iframes for the command "nextFrame"](https://github.com/gdh1995/vimium/commit/4b94b04124a4b298edc9553b9d9b9f9fa4a9c08c)
* [inject to iframes without "src"](https://github.com/gdh1995/vimium/commit/23716a9b43c38761aa2123e6df6d65880be7b354)

I'm not sure whether they are enough, so haven't created a PR for them.

**Comment by mrmr1993** [comment]
Thinking on this a little more: we need to be careful arbitrarily injecting our content into these kind of frames. Lots of WYSIWYG editors use `src`-less `<iframe>`s, and we don't want to pollute the DOM in those. A `document.body.isContentEditable` check should mostly suffice, but are there other similar edge cases?

Also (minorly), the code to inject our code and CSS on install (`background_scripts/main.coffee`) probably wants to have `matchAboutBlank: true` in its options, if we are to implement this.

Otherwise, @gdh1995 the code looks good.

**Comment by gdh1995** [comment]
> Lots of WYSIWYG editors use src-less <iframe>s, and we don't want to pollute the DOM in those

Yes, we shouldn't. What I really want is just the ablity to jump out of an iframe without "src" - Chrome's UX  is not so good if without Vimium. Then, there's another way to switch focus: using `chrome.commands`.

Commands' shortcuts are global for Chrome, and seem to have to be directly set by users. We may suggest uses to set `Ctrl+M` or `Alt+M` for command `mainFrame`.

But, since one extension can only have at most four commands, give one to `mainFrame` seems a waste.

**Comment by gdh1995** [comment]
Another question is  
In an `iframe` without `src`, `location.href` is `window.parent.location.href`, not "blank", and only when `.attr('src', "about:blank")`, the iframe is reloaded and gets a location of "blank".

This prevents content scripts to recognize if itself is in an iframe without `src`. I have no idea...

**Comment by gdh1995** [comment]
It seems we should not care about injecting to an iframe without src - there's no need.
Closed.

**Comment by rajeevksahu** [comment]
Either you have to shift within Bangalore or close by location; Bangalore packers and movers are always prepared to help you with best packaging movers. We deal with all your requisites and help you in all possible ways. We deal with everything from initial stage to final deployment of items.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
We check everything carefully that items are packed, packed or unloaded as per specifications or not. If there is a unique request from client, packaging and movers always respect your priorities. The expert alternatives assure that items are handled with appropriate care and it is transported to the new position without even only one the beginning.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
The time that you are wasting in packaging or moving your lengthy items can be invested in other meaningful factors like shopping, see your loved ones, explore the present place and many other factors. The best aspect is that packaging and movers are truly affordable and quickly comes in your price range. The packages can also be personalized based on your needs and specifications.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
So choosing experts for best packaging and movers is not a wrong concept. They will handle your all valuables either it is large or light in weight. They will neat all the factors, it will be packed properly, packed to truck and it will be unloaded to new position immediately.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>
