### ISSUE TITLE
Search-engine completion

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1651]
As of #1635, we have search-engine completion both for custom search engines, and for the vomnibar in "omni" mode.  Here are some notes...

- This is an experimental feature.  Please be patient, and provide feedback (both positive and negative) here.  The UX still requires some tweaking, but we need experience using the feature to get that right.

- Completion is supported whenever we have a completion engine for the search engine being used.  See [here](https://github.com/philc/vimium/blob/master/background_scripts/completion_engines.coffee#L2).  Currently it's (English-language) Google, Youtube, Wikipedia, DuckDuckGo, Bing (why?) and Amazon.

- Contributions of new completion engines would be greatly received, including in particular for non-English search engines.  They're easy to write (see [here](https://github.com/philc/vimium/blob/master/background_scripts/completion_engines.coffee#L2), again) and add almost no memory or runtime costs.

- There's a considerable amount of caching and re-use of previous results, so we're not generating a massive amount of traffic.

- What are the privacy issues?  For custom search engines, privacy seems moot. However, for general vomnibar queries, there may be an issue.  Currently, there's a new option at the bottom of the options page which allows search completion to be tuned (and even disabled).

- There is a very big change in how custom search engines work if we have a completion engine.  In that case, no suggestions from other (Vimium) completers are displayed.  Try it out and provide feedback.

Here's what it looks like for the vomnibar...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7566875/50b9c132-f7f1-11e4-91ab-218c887c9443.png)

And for a (Youtube) custom search...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7566905/85f1c6d8-f7f1-11e4-868b-2313ce178b6f.png)

**Comment by smblott-github** [comment]
This seems to work particularly well for custom search engines.  For the default search engine, the biggest issue I'm finding is getting the balance right between the relevancy scoring of search completions and the relevancy scoring of rest of the suggestions (history, bookmarks, etc).  One group or the other tends to dominate.

**Comment by smblott-github** [comment]
I'm experimenting with an alternative scoring approach which is intended to get around the "clumping" effect described above:
- https://github.com/smblott-github/vimium/tree/search-completion-with-regular-relevancy
- eb0e2964fca5ef2eccc06607944df6b208b2b99f

**Comment by smblott-github** [comment]
eb0e2964fca5ef2eccc06607944df6b208b2b99f has been merged.  It is indeed considerably better.

**Comment by smblott-github** [comment]
Search completion UX issues.

**UX Issue 1** -  *The relative ordering of suggestions should not change.*

If two suggestions matching the current query have been presented to the user and the user types more text which continues to match both suggestions, then the relative order of the two suggestions should not change.  (Well, it should not change unpredictably.)

**UX Issue 2** - *Respect the existing Vimium matching rules.*

- The user types: `Lake Vict`.
- Amongst the suggestions is `Lake Victoria Hotels`.
- The user continues `Lake Vict Ho`.

The "Hotels" suggestion must remain in the list, even if the completion engine doesn't suggest it with the longer query -- because it still matches by Vimium's matching rules.

**Observation**

The search-completion UX is considerably better for custom search engines than it is for general vomnibar searches.  We should consider *only* using completion for custom search engines.  That way, in as sense, the user has to *ask* to use completion.

(This would also circumvent the two UX issues, above.)

**Comment by smblott-github** [comment]
Update:

Merge #1666. This inserts the text of previous searches (custom and default) into the vomnibar input when such a suggestion is selected, and makes it very easy to tweak previous queries.  Note also the (undiscoverable) `Tab` binding on an empty (omni-mode) vomnibar.

Merge #1668. This tweaks the search-completion UX in a couple of ways: better relevancy scoring (see "UX Issue 1", above) and always promote the top suggestion to top spot (experimental).

TODO:
- Consider reinstating the small visual indicator for suggestions for which text will be inserted into the vomnibar input.
- Continue to tweak the search-completion UX (particularly scoring).
- Consider restricting the use of completion engines to custom searches only:
 - There's no need to be hammering Google for completions when the user knows what they're looking for.
  - Completions seem to give a better UX in custom-search mode (because there the user has already told us something about the kind of thing they want to do).

**Comment by smblott-github** [comment]
In addition to the status report (above), I'm experimenting with indicators to indicate when a suggestion's text will be inserted into the vomnibar input.  E.g., the second suggestion here:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7682097/4247421a-fd6d-11e4-9155-4a996d645748.png)

**Comment by smblott-github** [comment]
Look at this...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7735171/650d1e1a-ff33-11e4-9b77-e7d7b6b98b2a.png)

Currencies don't seem to work, but this does...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7735242/e70a2c0a-ff33-11e4-9b76-cb73b9cebd25.png)

**Comment by smblott-github** [comment]
Here's how to try this out.
- Use a very recent `master` or install [this version](https://drive.google.com/file/d/0B-PWDBroAYxrOEdCSjdwWEJzd1k/view?usp=sharing) (there was an important bug fix 2015-05-21, 208270b58e7e4dd18407ea8c176f0518df6051d1).
- The following applies only to `o` and `O` (so, **not** to bookmarks or tabs).

##### Default Search

Set your default search engine to `https://www.google.com/search?q=` (or anything which matches [this](https://github.com/philc/vimium/blob/master/background_scripts/completion_engines.coffee#L40) regexp).  If Google bounces you to `www.google.co.uk`, say, then set your default search engine to point there, instead. Your default search engine should match where your searches actually land.

Try these vomnibar searches (`o`):
- `longest river in af`
- `longest riv in af`
- `edinb ca` (Edinburgh Castle)

Tab down the completion list.  The completion text is added to the vomnibar (so the user can edit a completion).

Run a couple of those searches.

Next, open the vomnibar (`o`) and hit `Tab`:
- The vomnibar should open with history entries listed by recency.  Again, you can `Tab` down and either re-run or edit a previous query.

##### Custom Search

Add the following custom search engines (on the options page):

```
# Wikipedia.
w: http://en.wikipedia.org/w/index.php?title=Special:Search&search=%s Wikipedia

# Google.
g: https://www.google.ie/search?q=%s Google
l: https://www.google.ie/search?btnI&q=%s I'm feeling lucky...

# Youtube.
y: http://www.youtube.com/results?search_query=%s Youtube

# DuckDuckGo
d: https://duckduckgo.com/?ia=about&q=%s DuckDuckGo

# Vimium issues.
vi: https://github.com/philc/vimium/issues?utf8=%E2%9C%93&q=is%3Aopen+sort%3Aupdated-desc+%s Vimium issues
```

Things to try:
- `w lake vict`
- `w lake vict pe` (observe, we keep the "Lake Victoria Perch" suggestion, although Wikipedia no longer proposes it)
- `g longest riv af` (so, direct access to Google)
- `g 300 * 3`
- `l capit of swit` (capital of Switzerland)
- `d crianl` (Crianlarich - a place in Scotland)
- `vi vomnibar` ( "vi" = "Vimium Issues"; no completion here, but a useful custom search anyway; note that we don't filter out irrelevant history entries here)

Things to note:
- After running a search, you can again edit or re-run it using `o`, `Tab`.
- If we have a completion engine for a custom search, then we filter out history entries which don't match that completion engine.
- Custom searches in the history stay custom.  So, if you search for `w lake vict`, then come back (`o` and several `Tab`s) to search for `lake victoria pe`, you're back in Wikipedia mode.

(Note: I may come back and change this post without marking edits, ... because it might eventually end up in the wiki.)

**Comment by philc** [comment]
I played with it and the editing experience feels good. What I don't have a feel for is how much the completion results crowd out the other results I might care about.

Two things I noticed:

* The completion marker is ugly on Mac. If we're going to use an arrow, I suggest one of these: [one](http://www.fileformat.info/info/unicode/char/25B7/index.htm) [two](http://unicode-table.com/en/25B6/) [three](http://unicode-table.com/en/21AA/) [four](http://unicode-table.com/en/290D/), or ellipses.

![image](https://cloud.githubusercontent.com/assets/8598/7805881/0002a21a-032f-11e5-9b33-4130e533dc55.png)

* For me, the completion suggestions only appear on file:// pages; they don't appear on html:// pages. This is why I was unable to test this out earlier. No errors were logged in the content script or background page.

**Comment by smblott-github** [comment]
Status report.  I expect to merge #1687, which supports search completion on custom search engines only, soon.

**Comment by smblott-github** [comment]
#1687 has been merged.  See [here](https://github.com/philc/vimium/pull/1687#issue-81340417) for the rationale.  This is a substantial change to the UX, and a big improvement (IMHO), primarily because it overcomes the "crowding" problem.

**Comment by smblott-github** [comment]
As of #1717, completion-engine specifications have been changed to look like this...

```Coffeescript
class Wikipedia extends BaseEngine
  constructor: ->
    super
      engineUrl: "https://en.wikipedia.org/w/api.php?action=opensearch&format=json&search=%s"
      regexps: "^https?://[a-z]+\\.wikipedia\\.org/"
      example:
        searchUrl: "http://www.wikipedia.org/w/index.php?title=Special:Search&search=%s"
        keyword: "w"

  parse: (xhr) -> JSON.parse(xhr.responseText)[1]
```
