### ISSUE TITLE
Rename current tab (change document title)

### ISSUE THREAD

**Issue by mreq** [philc/vimium#1660]
Would be nice to have such an option. In plain javascript (using `prompt`):

    document.title = prompt();

Vomnibar ?could? be used instead instead of `prompt`.

**Comment by mrmr1993** [comment]
@mreq you could create a bookmarklet with a distinctive name (eg. `tabTitle`) containing

```js
javascript:void(document.title = prompt("Enter a new title for this tab:", document.title));
```

and then trigger it with `btabTitle<enter>`. Is there a common enough use case for this to justify having a dedicated command?

**Comment by mreq** [comment]
@mrmr1993 Thanks for pointing that out, didn't realize I could use `b` for that (already have the bookmarklet, but triggered it via ctrl+l + typing). That's much faster :)
