### ISSUE TITLE
`^` For switching between alternate tabs

### ISSUE THREAD

**Issue by xdl** [philc/vimium#1664]
I noticed that when I have a lot of tabs open, I'd search for an open tab with `T`, sometimes I'd want to jump back to the tab I was previously on.

Wondering what people think about whether it's a good idea/feasible to have this Vim functionality implemented: Switch between the current tab and the last tab you were on with `^`

**Comment by smblott-github** [comment]
Thanks, @xdl.

The tabs are ordered by recency in the vomnibar.  Try `T<Enter>`.

**Comment by xdl** [comment]
I hadn't realised this - thanks, this is really convenient!
