### ISSUE TITLE
Keymap to open custom url

### ISSUE THREAD

**Issue by alex-cory** [philc/vimium#1665]
I'm looking to be able to add a map that does this.

`map e openUrl chrome://extensions/`

Can this be done in the `Custom search engines` section of the Vimium Options page?

`e: chrome://extensions/`

**Comment by smblott-github** [comment]
> Can this be done in the Custom search engines section of the Vimium Options page?

You could do that.

I achieve the same effect by:
- Bookmark `chrome://extensions/`.
- Ensure the bookmark's "Name" is "Extensions (e)".

The way Vimium does its scoring, `b` (open vomnibar in bookmarks mode) then `e` will almost certainly pull the bookmark to the top. 

(Vimium assigns a high score to whole-word matches -- the `e`, here.)

**Comment by smblott-github** [comment]
Closing.
A combination of bookmarks and global marks achieves this quite well.
