### ISSUE TITLE
Not allowing to copy text from webpages.

### ISSUE THREAD

**Issue by alex-cory** [philc/vimium#1669]
I just disabled the vimium chrome extension, restarted chrome, and was able to copy text off of webpages.  I then turned it back on  (because I love this extension and don't want to get rid of it), restarted chrome, and now I can't copy anymore.

**Comment by smblott-github** [comment]
How are you "copying text"?

**Comment by alex-cory** [comment]
I'm not sure what the problem was, but it's working now.  I tried right clicking, and command + c.
