### ISSUE TITLE
Ability to paste into "find on the page"

### ISSUE THREAD

**Issue by mijoharas** [philc/vimium#1672]
`/` allows you to enter find on the page which is very helpful. sometimes I've wanted to find something that is quite long or is a symbol that is not easy to type (e.g. searching for a phrase or the character lambda). In these cases it would be good to be able to paste something in to search for it. So far in these cases I've had to resort to chromes default "find on page".

I am unable to paste using C-v or S-Insert. I think allowing the ability to do that with one of those or something similar would be useful.

**Comment by smblott-github** [comment]
Yes, @mijoharas.  This is a deficiency.  As too is the omission of the ability to do real movements and edits like `<Alt-Del>`, or `<Ctrl-Left>`.

**Comment by mijoharas** [comment]
good point. Have you got any ideas? I haven't looked at the current implementation, but couldn't we switch `/` to adding a text box that is positioned where we want it to the dom and moving the cursor into it. Then adding a handler to perform the search upon typing in, shouldn't that give us copy-pasting out of the box along with `C-Left` e.t.c.

How is it implemented at the moment? I haven't dug into the code for it yet.

**Comment by smblott-github** [comment]
@mrmr1993 is looking into some changes vis-a-vis how the HUD works.  There are some difficulties with just making it a text input... because then it has the focus, ... and then the page does not have the focus, ... and that seems to mess with finding text within inputs on the page.

**Comment by mijoharas** [comment]
that makes sense. @mrmr1993 have you got any thoughts about how we should go about this?

**Comment by mrmr1993** [comment]
@mijoharas It'll come for free from what I'm working on (using a `contentEditable` element for HUD text entry).  I'll try to get a PR through later today.

**Comment by mijoharas** [comment]
Awesome! thanks @mrmr1993.
