### ISSUE TITLE
\ in regex searches requires double escaping to search for the raw character

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#1673]
* Searching for `\w` works as in normal regexps
* Searching for `\\w` works the same as searching for `\w`
* Searching for `\\\w` and `\\\\w` work how `\\w` works for normal regexps.

This behaviour seems wrong and counter-intuitive, but we also need to support `\I`, `\r` and `\R` as our own special escape sequences, which is how this problem arose. The obvious fix is to only replace `\\` with `\` when it precedes `I`, `r` or `R`.

**Comment by smblott-github** [comment]
Good find.

If you split on (literally) `\\` (two backslashes), parse our escape sequences, then join on `\\`, would that work?
