### ISSUE TITLE
Enable process iframe  Program crashes 

### ISSUE THREAD

**Issue by yangyaofei** [philc/vimium#1677]
Enable process iframe  Program crashes 
eidt: enable out-of-box process #enable-site-per-process

win7 x64  chrome32bit 43.0.2357.65 m
i need enable it to view some website

**Comment by smblott-github** [comment]
Thanks @yangyaofei.  Could you give some more in formation?  What does "enable process iframe" mean?
- What do you do?
- What do you expect to happen?
- What actually happens?

**Comment by yangyaofei** [comment]
eidt:  enable out-of-box process #enable-site-per-process

i enable chrome://flage  enable out-of-box process//in chinese 启用进程外iframe  #enable-site-per-process
then vimium is crash when restart the chrome

**Comment by smblott-github** [comment]
I can't find a flag, but running `google-chrome --process-per-site` things seem fine (and it *is* running process-per-site, you can see it on the "task manager").

What are you seeing?  What is failing?

**Comment by yangyaofei** [comment]
i just enable Out-of-process iframes#enable-site-per-process .
it require restart chrome ,so i restart it .then some of the site is crash and chrome show some masage say vimium is crash and turn off this app.
i use win7 64bit running a chrome 32bit(lot of bugs in 64bit),i think may be its the problem.
ps: i just reinstall win7 from 32bit to 64bit.

**Comment by smblott-github** [comment]
OK.  I see it now.  Had to upgrade Chrome (now to 43).

Confirm.  Catastrophic failure on opening any page (on which Vimium runs).  Nothing useful in the console.

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7764587/38d1288c-004b-11e5-8137-83fb6ba8672a.png)

"Highly experimental".  So not becoming the default next week.

What are your thoughts, @mrmr1993?  Chromium bug?

**Comment by yangyaofei** [comment]
i think its maybe a chromium bug,
i used iframe in the past ,its good. but today its not work anymore ,when i use js to change the iframe's src is display blank.so i think i set something wrong.i change every related settings in chrome://flags .so i find this.....

i dont know its useful or not that i write up here,maybe  its helps.

**Comment by smblott-github** [comment]
A little investigation and, as probably expected, everything goes belly up on [this line](https://github.com/philc/vimium/blob/master/content_scripts/ui_component.coffee#L25)...

```Coffeescript
document.documentElement.appendChild shadowWrapper
```

**Comment by mrmr1993** [comment]
> What are your thoughts, @mrmr1993? Chromium bug?

Definitely a Chromium bug; anything that crashes browser processes is. Have either of you opened an issue with Chromium? Mentioning OOPIF in the title might be sensible, so the issue can be picked up by the relevant team more quickly.

**Comment by smblott-github** [comment]
I've not opened a bug.
