### ISSUE TITLE
Is this the right place? How do I play videos on pages and how to clear marks

### ISSUE THREAD

**Issue by drwl** [philc/vimium#1678]
I searched through issues, the wiki, and google with no avail. If I missed them, please feel free to link me to the issues.

On http://vimium.github.io/ there is a youtube video showing how it works. Are there keys/commands that can be invoked to play the youtube video? Also, is there a way to clear local marks that are set?

**Comment by mrmr1993** [comment]
@drwl you can change frames on a page with `gf`, and from the YouTube frame you should be able control it (if you're using HTML5 YouTube).

We currently don't have any mechanism for clearing marks . Is there a use case you have in mind to support deleting them.

**Comment by drwl** [comment]
I believe I'm using the HTML5 youtube. I press gf to change frame and then neither 'space' nor 'k' work to play the video, even in insert mode. Would you mind sharing what you use?

**Comment by mrmr1993** [comment]
@drwl I think I remember YouTube having a double/triple frame for embedded videos (I'm not at a computer, so I can't check). Do things work as intended if you `gf` once/twice more after the first flash in the frame?

**Comment by drwl** [comment]
I wasn't able to get `gf` to work on `vimium.github.io`, but vimium still works great nonetheless. Thank you for the support and response!
