### ISSUE TITLE
unmapAll for everything

### ISSUE THREAD

**Issue by fommil** [philc/vimium#1681]
I was quite disappointed that `unmapAll` doesn't really unmap everything.

I'd really like to disable **everything**, including the default `C-s`, `C-z`, `C-w` behaviours.

Is this possible?

**Comment by smblott-github** [comment]
Afraid that's not possible, @fommil.  `unmapAll` really means unmap all **Vimium** commands.

**Comment by fommil** [comment]
I've found https://github.com/vincekd/Chrome_Emacs_Keys which seems to be able to do this actually. Given that I was setting up Emacs bindings anyway, I think I'll stick with it and run away from this Vim-tainted evil :stuck_out_tongue:
