### ISSUE TITLE
Feature Request: '' takes you to the last viewed part of the page

### ISSUE THREAD

**Issue by alex-cory** [philc/vimium#1682]
Use Case:
You're on a page, you want to scroll to the top.  You type `gg`.  Then you want to go back to the previous spot on the page.

**Comment by gdh1995** [comment]
If you jump by an anchor (like clicking special '<a>'s), "go back" will work. Otherwise, we can hardly tell Vimium if it's time to remember the current spot.

**Comment by smblott-github** [comment]
We *could* remember the current spot for:
- `gg`, `G`, `n`, `N`, `/`, and marks.

**Comment by smblott-github** [comment]
This will be fixed if/when we merge #1714.

The default binding is: <tt>\`\`</tt>.

**Comment by smblott-github** [comment]
Closing. Fixed in #1714.
