### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by wildeyes** [philc/vimium#1696]
Cloned vimium from source, then followed the guide in teh CONTRIBUTING.md, getting an error on running tests:
```
Running unit tests...
Pass (135/135)
Running DOM tests...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
  at errnoException (child_process.js:1001:11)
  at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

**Comment by smblott-github** [comment]
Not seeing that here (on a fresh git clone).

Unfortunately, those error messages aren't too helpful...

(Possibly a phantomjs version issue? I'm 1.7.0, which may be old.)

**Comment by StephanePoirier** [comment]
I encountered a similar issue. In my case, installing PhantomJS globally solved the issue: `npm install -g phantomjs`
