### ISSUE TITLE
LinkHints.activateModeWithQueue doesn't always show hints for DOM mutations after clicks

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#1709]
In `LinkHints.activateModeWithQueue`, if a simulated click
* causes a DOM update that adds, removes or changes the attributes of elements; and
* the DOM update happens after the next round of link hints have been shown,

then we might miss or wrongly show link hints for the DOM changes.

[Chromium 490063](https://code.google.com/p/chromium/issues/detail?id=490063) describes a specific case on google.com. (The attached video there makes the problem obvious.)

Edit: looks like [`MutationObserver`](https://developer.mozilla.org/en/docs/Web/API/MutationObserver) would probably be the most useful thing for this.

**Comment by gdh1995** [comment]
I think we may use `<tab>` to refresh current hints when `LinkHints` is on.

That is, call `deactivateMode` and then call `activateMode` with the same `mode` if `onKeyDownInMode` grab a `tab` key.

**Comment by smblott-github** [comment]
That's a possibility, @gdh1995.  It's a bit undiscoverable, though.

Also, a more natural use of `Tab` would be the case where you're down to two or three hints, and you want the second or third one.  So `Tab` would change the hint that would be activated if you hit `Enter`.

**Comment by gdh1995** [comment]
> Also, a more natural use of Tab would be the case where you're down to two or three hints, and you want the second or third one. So Tab would change the hint that would be activated if you hit Enter.

Yes, so we may refresh hints ONLY if no `a-z` keys has been typed - `hintKeystrokeQueue` is empty.

If it's not empty, we deal with `tab` differently.
