### ISSUE TITLE
[edit: only a misunderstanding] keypress is not triggered for a PDF page

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#1718]
Well, I met a problem when reading a PDF page: `keypress` is never triggered.
* Vimium doesn't receive any `keypress` event, even when I have removed `keydown` and `keyup` listeners from the extension source code and remove the `<embed>` PDF object.
* No other extension; the Developer Tools does not show any other listeners.
* In `["keydown", "keypress", "keyup"]`, `keydown` and `keyup` will be dispatched to `window` and then trigger Vimium's listeners (vimium_frontend.coffee:196), which does work.

I've searched other issues, but those reports only said about the `insert` mode. In my case, insert mode is on when page finishs loading, and `<esc>` makes it exit successfully (because `keydown` event still works).

This problem makes most key maps invalid, except those with "<[acm]-".

More Information:
*Chrome Version: 42.0.2311.135 (stable)
* PDF plugin: its name is "Chrome PDF Viewer"; no version info shows in chrome://plugins
* my most other plugins have been disabled
* In the Developer Tools, I find `document does not have `head`, but there's indeed a `body` with nodeName `BODY`, and PDF `<embed>` is `document.body`'s first child.

**Comment by gdh1995** [comment]
Well, it seems `keydown` events are `preventDefault`ed. Although I've no idea about where it's stopped, we may move the key map handler to `keypress` into `keydown` - a hard work... .

If no choice, I will begin to try this way in a few days.

**Comment by smblott-github** [comment]
Do you have a link to the viewer.  Googling exactly those terms doesn't seem to bring up an exact match.

**Comment by gdh1995** [comment]
I'm sorry that `keypress` did work when I turned off Vimium and listen `window`,

So, it's my modification to Vimium that caused this bug. Then this issue should be closed.

**Comment by smblott-github** [comment]
OK.

**Comment by gdh1995** [comment]
I've make another test without any extension running. It seems a bug of Chrome (or the PDF plugin ?).

Is there something I can do for further tests?

**Comment by smblott-github** [comment]
You need to tell us how to reproduce this.  Which PDF extension, what to do, etc?

**Comment by gdh1995** [comment]
The PDF plugin has a name "", but no version information, in `chrome://plugins`:

__Chrome PDF Viewer (2files)__
* name: Chrome PDF Viewer
* version: (here is blank)
* location: `chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/`
* type: browser plugin
* MIME type: [ "application/pdf", , ".pdf" ]

* name: Chrome PDF Viewer
* description: Portable Document Format
* version: (also blank)
* location: intrnal-pdf-viewer
* type: PPAPI (plugin out of process)
* MIME type: [ "application/x-google-chrome-pdf", "Portable Document Format", ".pdf" ]

My system is Windows 8.1 x64, Chrome is 42.0.2311.135 (32 bits), Blink is 537.36 (@194530).
When I was testing, all other plugins were also disabled.

**Comment by gdh1995** [comment]
Confirmed: it's a Chrome bug imported since 42. I've tried 37 and 41.0.2272.89, and both are OK.

The two viewer plugin above can be turned off.
* If I disable the first (mime is app/pdf), pdf files can not be shown.
  The whole page is just grey but Vimium will work well.
* If I disable the second, Chrome shows "Chrome PDF Viewer has been disabled. balabala".
* If turn off "#enable-out-of-process-pdf" in chrome://flags, PDF pages become grey...

So, it's `chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/` who prevents keypress events.

I will try 43 in a while.
Warning: My Chrome has been broken by an old version of 37... So attention is a must when some one switchs Chrome - `sandboxie` is recommended

**Comment by rajeevksahu** [comment]
Considering for needing moving alternatives in Thane, Bangalore , Bangalore , Bangalore , Bangalore , Bangalore , Bangalore , Bangalore and other places of Indian, EXPERT Packers offers most efficient and affordable moving and packaging alternatives. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
As EXPERT packers is one of the largest groups of expert packers movers Thane and has a different divisions in almost all the significant places of Indian, We create the transportation simple and convenient. We have all the in-house plants to create the moving actions a stress-free and stress 100 % free affair.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
Imagination of moving to a new position gives a new excitement. It can be much exciting for some people, but for many others, it can be a difficult decision because of the emotional attachment with the surrounding and the people residing around. The comfort of residing that we equate to the position where we with our family have been residing for years. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
Such type of emotional thoughts and feelings can be on our mind as a pressure. Apart from that, packaging and running items and useful items create moving and packaging an even more difficult and challenging process. But now fantastic news is that movers and packers in Thane at EXPERT Packers have a finish remedy of moving from one position to another. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>
