### ISSUE TITLE
Adding support for cycling through windows

### ISSUE THREAD

**Issue by nadeemahmad** [philc/vimium#1720]
I really enjoy vimium. I just have a small feature request, regarding the ability to cycle through open chrome windows. Currently there is great support for tabs, but no support for cycling through windows. 

Thanks in advance.

**Comment by smblott-github** [comment]
Thanks @nadeemahmad.

If you choose a tab in a different window (with `T`), then Chrome should focus the window.

I'm not sure whether a new command for this is a great idea.  An possible alternative would be a Tab-like vomnibar mode which restricts the listed tabs to the most recently active tab in each window.

**Comment by nadeemahmad** [comment]
Thanks @smblott-github. The `T` command works well enough!
