### ISSUE TITLE
Can I view more than 10 search results of history or bookmark?

### ISSUE THREAD

**Issue by ii0** [philc/vimium#1723]
When I use the following command, it displays only 10 search results, I think it's very limited.
o   :   Open URL, bookmark, or history entry
O   :   Open URL, bookmark, history entry, in a new tab 
b   :   Open a bookmark
B   :   Open a bookmark in a new tab 

How can I view all the search results?
Can anyone help me?

**Comment by smblott-github** [comment]
> How can I view all the search results?

No, you can't.  I'm not sure how useful this would be.  You'd have to hit `Tab` a lot of times.  Personally, if it requires more than three or four Tabs, then it's too far away for me.  And hitting `Tab` eleven times to find a suggestion that isn't yet visible (and might be useless) doesn't seem likely to be a useful feature.
