### ISSUE TITLE
The new method of defining search engines breaks some use cases.

### ISSUE THREAD

**Issue by mijoharas** [philc/vimium#1724]
```
down: javascript:location='http://www.downforeveryoneorjustme.com/'%20+%20escape(location.hostname)%20+%20'%20'%20;%20void%200
cache: javascript:location='http://webcache.googleusercontent.com/search?q=cache:'+location.href
```

Both of these are broken by the new requirement that you search with `keyword search_term` and can't just search with `keyword` (or in these cases `down` or `cache`).

The snippets will allow you to go to http://www.downforeveryoneorjustme.com/ or see googles cached page, automatically filling in the hostname for you.

This can be fixed by typing `down foobar` or `cache baz` to force the correct thing to be selected, but is poor from a useability perspective.

**Comment by smblott-github** [comment]
Those two use cases might be better implemented as bookmarklets.

**Comment by mijoharas** [comment]
Hmm... I suppose I can't argue with that. I guess it's just that I originally had it defined the one way.

Closing the issue.
