### ISSUE TITLE
Open multiple links in a new tab shifts tab focus instead of staying on queue tab

### ISSUE THREAD

**Issue by tehNYAZ** [philc/vimium#1725]
#when Open multiple links in a new tab is activated (default is <a-f>)
#a link is selected, but the tab focus immediately shifts to a new tab with the link selected
#as oppsed to instead of staying on the queue tab to select more link

**Comment by smblott-github** [comment]
Which Vimium and Chrome versions is that, @tehNYAZ? It could be you're seeing #1279 (which is a Chrome bug, and is fixed in later versions).

**Comment by tehNYAZ** [comment]
Version 41.0.2272.76 Ubuntu 14.04 (64-bit)
Vimium 1.51

Is the fix in #1279 to use a different version until the Chrome bug is fixed?

**Comment by smblott-github** [comment]
Yes, @tehNYAZ. That bug was first reported in Chrome 41.  Some versions of 42 contain the patch, but Chrome 43+ should be good.  That's the first thing to try.

**Comment by tehNYAZ** [comment]
Thanks for the quick reply.

**Comment by smblott-github** [comment]
Closing.  Assuming resolved.
