### ISSUE TITLE
Feature request: moveTabStart, moveTabEnd

### ISSUE THREAD

**Issue by sarkologist** [philc/vimium#1727]
VimiumPlus has these commands. Since there is `moveTabLeft/moveTabRight` corresponding to `nextTab/previousTab`, it makes sense to have `moveTabStart/moveTabEnd` to correspond to `firstTab/lastTab` :)

[for reference](https://github.com/jb55/vimium-plus/blob/master/background_scripts/commands.coffee#L112)

(love vimium btw, thanks for the work!)

**Comment by smblott-github** [comment]
Thanks, @sarkologist.  Perhaps we don't need a new command for this.  Perhaps, instead, we could make do with `99<<` and `99>>`.  But those don't currently work in all cases.  I think 91bbb3122b58e834cc5512768eb09046fac2b448 fixes things.

**Comment by smblott-github** [comment]
@sarkologist.  Merged #1728.  This should fix `99<<` and `99>>`, which is a lighter weight solution than a new command.

**Comment by sarkologist** [comment]
Thanks, @smblott-github. `99<<` and `99>>` should be a equivalent commands for my use case. But last I checked there is no way to map a key to a key sequence? i.e. I would love to be able to do something like `map W 99>>` so that i can just use `W` instead of typing `99>>` or at least something which achieves the same effect.
