### ISSUE TITLE
Vimium doesn't seem to see contents of a popup

### ISSUE THREAD

**Issue by quetzalcoatl** [philc/vimium#1730]
Please see this webpage: http://boli.blog.pl/ - for now that's the only example of that behavior I noticed. Please use incognito/etc mode, as it probably uses cookies and once dismissed the popup may not show up anymore for you.

This page loads and a short time afterwards it displays a "cover panel" that asks you to confirm being 18yr old. Vimium does not see this "popup". When F is pressed, Vimium presents key-labels for all links on the actual page beneath, but none of the contents in the popup (checkbox, etc) are reachable. I don't know how the "delayed popup" was implemented and I don't know if that's real input-type checkboxes or some stub, sorry.

**Comment by mrmr1993** [comment]
The pop-up is a separate frame, and our link hints (currently) only work per-frame. You can switch between frames using `gf`. Doing this once makes link hints work for me.

**Comment by quetzalcoatl** [comment]
Wow. I fell so dumb. I should have checked for frames. Thank you!!
