### ISSUE TITLE
Regular expressions stopped working on master

### ISSUE THREAD

**Issue by mohitleo9** [philc/vimium#1731]
Hi, regular expressions search stopped working on 532fa0779fd4733fc8a4bec963cd6c73a91b35f2

**Comment by mrmr1993** [comment]
Regexp search seems to work fine for me on 532fa07 on my phone's Arch install (`Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36`). Can you give more details of what's not working?

**Comment by mohitleo9** [comment]
hmm, I am using Chrome Version 43.0.2357.124 (64-bit), and the above mentioned commit.
(it has the new interface for settings page). On my settings page the option to use regex in find is enabled but as soon as I try to search using regex it does says no results found. The regular text search works though. It's almost the regex search is not enabled. If i revert back a few commits it starts working again. I will try to do a git bisect and narrow down the commit.

**Comment by mohitleo9** [comment]
I did a git bisect and found this is the culprit 0de6b076271b673d0e1dcc2b74b2ddd1646bf08e
. The commit does somethings to settings so I guess that might be breaking the regex search.

**Comment by mrmr1993** [comment]
Thanks @mohitleo9, great find. Looks like your settings aren't all being carried over once we switch to `chrome.storage` in the frontend. As a workaround, you should be able to re-enable regexp searching by disabling it in the options, saving, enabling it, and then saving again.

I'll push a PR in the morning to push settings from `localStorage` to `chrome.storage.sync` as necessary, which should fix the general problem.

**Comment by mohitleo9** [comment]
I tried the mentioned solution it didn't work for me. But I guess I can make the changes locally to get it working, I am really excited to use the new features!

**Comment by smblott-github** [comment]
@mohitleo9.  Is it only the regexp setting you're having an issue with, or is it other settings which are used in the front end too?

E.g. Try changing the "Scroll step size" option, and see if that is effective.

**Comment by smblott-github** [comment]
OK, @mohitleo9.  Got it: https://github.com/philc/vimium/commit/aa00e29dc2533b6701c65935223599671c5833b1 (which is so trivial, I just merged it directly).

@mrmr1993.  I wonder if we could write a test to verify that all of the settings on the options page have default values?

**Comment by mrmr1993** [comment]
> Any user who has migrated to the new settings system (and uses regex search) will have to untick that box on the options page, save, and tick it again

@smblott-github And any user who set any setting before #1029 was merged and hasn't changed it since. Which is a great way to piss of any long-time users.

Again, can I bump the version number in a PR to fix this, or should I add a workaround to the fix for `master` until the version bump happens at release time?

**Comment by smblott-github** [comment]
You're right.  Perhaps just add another migration to the bottom of `settings.coffee`.

**Comment by mrmr1993** [comment]
So no version bump?

**Comment by smblott-github** [comment]
You mean 1.51 to 1.52?  How would that help?

**Comment by mrmr1993** [comment]
Then we can just check if `previousVersion` is less than 1.52, and push `localStorage` if so.

**Comment by smblott-github** [comment]
But ....  If it's `true` in `localStorage` but not in `chrome.storage.sync`, then fix it.  How does bumping the version help?

**Comment by mrmr1993** [comment]
I'll push a PR with it shortly so you can see what I mean.

**Comment by mohitleo9** [comment]
The latest commit fixed it! Thanks!
