### ISSUE TITLE
Feature request: Close a tab in the "open tabs" view

### ISSUE THREAD

**Issue by cristianl** [philc/vimium#1735]
**EDIT:** Somehow this got posted before I could enter a description and I didn't even know it, so here's the rationale for this request:

You can view a searchable list of open tabs by pressing <kbd>Shift + T</kbd>, and then switch to an open tab.

My request is for a command to close the tab that's currently highlighted in that list.

Currently, you can close a lot of tabs quickly by navigating between tabs (<kbd>Shift + J</kbd> and <kbd>Shift + K</kbd>) and then pressing <kbd>x</kbd>, but that's inefficient, as it requires multiple context switches (you must switch to a tab before closing it).

**Comment by mrmr1993** [comment]
+1 this would be great for tab management.

**Comment by smblott-github** [comment]
I wondered about this when looking at the vomnibar recently.  You could have `<Delete>`:
- Remove tabs.
- Remove bookmarks.
- Remove history entries.

(Each as appropriate.)

**Comment by smblott-github** [comment]
Off topic.  @cristianl... Do you know that there are commands to close *all* tabs left and right of the current tab?  See advanced commands.

**Comment by mrmr1993** [comment]
> You could have `<Delete>`:

`<Delete>` and `<c-Delete>` are useful text-editing commands, so we probably shouldn't override them and 'surprise' people by deleting their tabs rather than their text. And `<shift-Delete>` is cut, so that's probably off the cards too

> * Remove bookmarks.
* Remove history entries.

I recon bookmarks and history should be harder to delete by accident, because there's no way of restoring them. I wouldn't rush into adding these.

**Comment by smblott-github** [comment]
Yes, @mrmr1993. So all of the obvious key bindings (`Ctrl-X`, etc) are useful and important for the vomnibar input.  So, unless somebody comes up with a good user interface, we probably can't do this.

Did you have something in mind, @cristianl?

(Perhaps `Ctrl-D`?)

**Comment by edrex** [comment]
`Ctrl-Shift-Delete`?

**Comment by edrex** [comment]
Possibly a more idiomatic/clean option would be to introduce a top-level "delete any tab" action, maybe mapped to `R` for proximity to `T`.

**Comment by edrex** [comment]
Otherwise it seems like the most user-friendly thing would be to have a `Normal` mode with extra tab-oriented commands (move up-down etc) and only enter into the current omnibar mode if the user presses `/`. I actually think this would be a fantastic addition to Vimium, but it would take some work.

**Comment by rrsahutwo** [comment]
As we have our own in-house built employees and other features so we do not need to seek the services of employees, automobile and other equipment for fulfilling our customers’ moving needs. That is the purpose why our moving solutions are much more cost-effective than others in your locality. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
You from any aspect of India can seek the services of our solutions for the enjoyable moving. We are sure that if you once seek the services of our solutions, you will discover your decision the wisest one in concern of moving needs and you will be a permanent client of EXPERT Packers.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
If you are looking for the best movers and packers in Bangalore , you have come to the right position. Here we are a leading moving and packaging company in Bangalore and facilitate our clients within the town and from across the nation. We are well-known for providing great quality, quick, affordable and reliable moving alternatives throughout the nation. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
We are excellent and well-known moving organizations in Indian and our knowledgeable packers movers Bangalore can assist you with our outstanding features in your transportation and moving needs. Thus we create all the process affordable, simple and stress-free. It is most essential that you have to approach only the well-known and efficient company to shift the particular place. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by afilp** [comment]
@smblott-github Can you please review my suggestion on the other issue? I think it `SHIFT-DELETE` could work if we just detect the "selected status" of the text:

https://github.com/philc/vimium/issues/2078#issuecomment-455538424
