### ISSUE TITLE
Add viw motion to visual mode

### ISSUE THREAD

**Issue by Zenadix** [philc/vimium#1737]
A motion that I use a lot in vim is `viw` (select inner word). Basically, you place the caret in any part of the word, type `viw` and it will select the whole word. I think it would be really useful in Vimium.

**Comment by smblott-github** [comment]
Thanks, @Zenadix. Yes, "inner" would be a good one to have.  I'll look into it when I get a chance (not soon, unfortunately!).

In the meantime, `o` works.  So `boe` has the same effect.
