### ISSUE TITLE
Typing in textarea that has focus set by javascript still fires function keys

### ISSUE THREAD

**Issue by mmclar** [philc/vimium#1738]
If I open a file that has a textarea that gets focus automatically, I think the expected behavior should be that you can type in that textarea, since the text entry cursor shows, and the field is indicated as having focus.

Keys that aren't mapped DO type into the textarea, but keys that are mapped to function will perform the function instead.

Some example HTML to demonstrate:
```html
<textarea id="focusme"></textarea>
<script>document.getElementById('focusme').focus();</script>
```

If you open a page with that code, then type, e.g., 'x', it will close the tab, rather than putting the 'x' where the text entry cursor is.

**Comment by smblott-github** [comment]
Confirmed.  That's pretty bad.  It's not in 1.49, so it looks like a modes bug (so my bad).

**Comment by smblott-github** [comment]
Thanks for the report, @mmclar. #1740 will fix this.
