### ISSUE TITLE
imap jj <ESC>

### ISSUE THREAD

**Issue by krzkrzkrz** [philc/vimium#1741]
Possible to trigger ESC by hitting jj twice in insert mode?

**Comment by gdh1995** [comment]
A function key is better, like `F1` and `F2`.

**Comment by krzkrzkrz** [comment]
Ideally you can map it to whatever key you want. But the key feature is being able to do so when in `insert` mode.

**Comment by Zamicol** [comment]
+1

**Comment by patrickmcelwee** [comment]
+1, though I would map `jk`
