### ISSUE TITLE
Add support for ngClick to link hints

### ISSUE THREAD

**Issue by poacher2k** [philc/vimium#1742]
There's quite a lot of Angular sites around these days, that use the ngClick directive instead of the native JS onclick.

Supporting ngClick to link_hints would allow Vimium to work on Angular sites, and is quite easy to implement.

I've added a suggestion that I've tested to work properly here: https://github.com/poacher2k/vimium/blob/patch-1/content_scripts/link_hints.coffee

**Comment by smblott-github** [comment]
Thanks, @poacher2k.  @mrmr1993... What do you think?  This your realm.

**Comment by mrmr1993** [comment]
Sounds reasonable and looks like an easy/clean way to do it.

@poacher2k could you submit a PR with that code? I have a few minor tweaks to talk over, and then it'd be great to get this in the codebase.

**Comment by poacher2k** [comment]
Closed as of #1745.
