### ISSUE TITLE
Is it right that "Chrome might reuse the tab ID of a recently removed tab"

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#1746]
In main.coffee:364, there is:
``` coffeescript
  # Chrome might reuse the tab ID of a recently removed tab
```
I'd like to check whether it is true. So, any evidence or document about this?

**Comment by smblott-github** [comment]
I believe it's false.

> Tab IDs are unique within a browser session. 

(From [here](https://developer.chrome.com/extensions/tabs).)

**Comment by gdh1995** [comment]
Then `updateOpenTabs` in `main.coffee:363` does not need to check `tabInfoMap[tab.id]?.deletor`. Am I right?

In fact, I think there're a lot of such code having been no longer useful, although nothing is influenced.

**Comment by smblott-github** [comment]
> In fact, I think there're a lot of such code having been no longer useful, although nothing is influenced.

Yes.  I think there's redundant (but harmless) code in there.

**Comment by gdh1995** [comment]
You said that, in some days Vimium would change and support Chrome with `chrome.sessions` only. I think those parts of code won't be cleaned until then, so this issue can be closed now.

**Comment by smblott-github** [comment]
Yup.
