### ISSUE TITLE
Vimium Wrongly Captures Input

### ISSUE THREAD

**Issue by chasingtheflow** [philc/vimium#1748]
I've been having issues with Vimium lately where it frequently wrongly captures keyboard input when I'm typing into multiline text fields so I'll be typing like a paragraph into a text field and all the sudden vimium takes over and i'll end up redirected to a different page before I realize what happened. This only became an issue for me in on of the more recent versions and I never had an issue with this before. It seems to happen most frequently when the page loads (or reloads) and my cursor is already captured by a text box but vimium seemingly has not realized that.

**Comment by smblott-github** [comment]
Thanks @chasingtheflow.

I think we caught that one just last week (#1738).

A workaround until the next release (which may or may not be to your taste) would be to enable *Don't let pages steal the focus on load* on the options page (under advanced options).  That way, at least you get consistent behaviour.

**Comment by chasingtheflow** [comment]
Thanks! Will try that in the interim. Best,
