### ISSUE TITLE
Cannot Exclude Alt-P (Pin Tab) keybind

### ISSUE THREAD

**Issue by aripley** [philc/vimium#1752]
I'm on a mac using chrome. 
I have a site that uses alt+p for something else. I have the rule entered for my domain as "<a-p>" the same way it's shown when you hit ? and see the keybinds.

I've also tried it by clicking, alt+p, which creates a "π" character. I tried typing in "Alt+p" "Alt-p," and a few more. Most likely user error, but could be a bug.

**Comment by smblott-github** [comment]
@aripley... alt-p is not supported as an excluded key.  It's simple keys only.

**Comment by aripley** [comment]
@smblott-github thanks!

**Comment by smblott-github** [comment]
@aripley...

Actually.  I dislike the the default alt-p binding.  It's not vim-like, and is likely to interfere with window-manager bindings.  I map pin/unpin tab to `gp`, which seems more natural.  If you do the same, and unmap alt-p, then your problem goes away.

**Comment by aripley** [comment]
@smblott-github good call. I had just picked up learning that one and was falling in love. But we use alt a lot in our internal tools, so conflicts. I don't ever use t for new tab, still so used to cmd+t from chrome shortcuts I think. So, I removed both t & <a-p> and added tp for tab pin or toilet paper, come to think of it.

**Comment by smblott-github** [comment]
I guess we can close this, @aripley?

**Comment by aripley** [comment]
@smblott-github yes, thank you all!
