### ISSUE TITLE
Follow previous/next links and save the url parameters

### ISSUE THREAD

**Issue by arieljannai** [philc/vimium#1753]
Hi! :smiley: 

I don't know if that's the way it supposed to be, but when I used the `]]` shortcut to move to the next page, some url parameters were omitted from the next page link.
For example, that's a site I was using at the moment:
`http://society6.com/tshirts?style=men&count=100&page=2`, and after using `]]` I got:
`http://society6.com/tshirts?style=men&page=3`.
The count parameter was omitted.

Is it something with the specific website? I see that here in GitHub it does not happen.
If It's not the website problem, is there anyway to avoid it?

Thanks, 
Ariel

**Comment by gdh1995** [comment]
It depends on websites. `]]` only finds one dom node whose text is `"next"` or something else. If the page you are visiting does not add `count=100` to the link, no one except its developer can fix it.

**Comment by smblott-github** [comment]
@arieljannai... `]]` isn't too smart.  It just looks for a link on the page with certain keywords ("next", "more", ">" and so on) and clicks it.  A lot of the time that works; sometimes, as in the example you quote, it doesn't.  It depends on the site.

**Comment by arieljannai** [comment]
Ok, thanks!
So I'll have to deal with it :smile:
