### ISSUE TITLE
Basic bash/vim like movement in input fields (ctrl-e,ctrl-w,ctrl-a, ctrl-u)

### ISSUE THREAD

**Issue by fogine** [philc/vimium#1754]
As title says I would like propose this feature. I miss these key bindings a lot when I'm in input text field (eg. google search input box):
`ctrl-e` - move to end of text line
`ctrl-w` - delete one word backwards
`ctrl-a` - place cursor to the beginning of line
`ctrl-u` - delete text in field

**Comment by gdh1995** [comment]
`Ctrl-Backspace` will delete one word backwards. If you are using a Windows-style keyboard, there are `Home` and `End`, because of which I hate Mac laptops.

It seems that `Ctrl+U` is a global hotkey for Chrome of Windows version, so `<ctrl-u>` will never work.

**Comment by fogine** [comment]
Thank you for the information, I've not known about <c-space>. But as far as I know, it's not possible to remap those shortcuts in vimium...? It would be really helpful for me.

**Comment by gdh1995** [comment]
I think it's possible: the `Modes` mode has provided us with two different `InsertMode`, one for `entrInsertMode` and the other for inputing. We may change actions of the second `InsertMode` when it meets a `keydown` event with `.ctrlKey is true`.

But if so we had better invent a logic to judge which types of events will be handled, which needs a lot work, trying and tests.

BTW: it seems to be emac like to using `ctrl-e`...

**Comment by fogine** [comment]
@gdh1995  is that recent feature which is not included in 1.51 ? Or isn't it documented at all and one need to go through code? Could you please provide link to a doc page if possible? Or could you show example of setup, please?
`map` command can only map key combination to one of the available commands, right?

**Comment by smblott-github** [comment]
@fogine.  I think @gdh1995 is just describing the standard Chrome bindings for inputs.  There's nothing special in 1.51.

The code base does, however, include a vim-like edit mode.  It's wholly disabled at the moment though.  You can try it out, however, by reverting 325ebc88fe3e1b79e5165bbc35db119e58609932.  It's not clear what the future of this edit mode is.  It may never be released.

**Comment by rrsahu** [comment]
They will take all your pain and providing 100 % reliable protection for customers.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by rrsahu** [comment]
You can believe in packers and movers Company blindly. The job of packer movers in Bangalore is to fill content, unload the same to shifted place and also product packaging most fragile factors wisely. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers Delhi">Packers and Movers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>

**Comment by rrsahu** [comment]
You just enjoy your shifting initiatives and keep the rest on us. In last few days in that particular area, you can party with your friends and family without taking any stress of moving. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers Chennai">Packers and Movers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers Noida">Packers and Movers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers Navi Mumbai">Packers and Movers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers Thane">Packers and Movers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers Ghaziabad">Packers and Movers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers Faridabad">Packers and Movers Faridabad</a>

**Comment by rrsahu** [comment]
Now you must have got an concept why packers and movers Companies have become so essential for you.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>
