### ISSUE TITLE
tab automatically closes after ~1 second using 't' shortcut

### ISSUE THREAD

**Issue by aaronharding** [philc/vimium#1756]
hey,

this happens quite irregularly so it's hard to diagnose or find out the real symptons, but what happens is that i use 't' to open a new tab and then it will close after about a second. my new tab page is the Google Art Project, so I am not sure if it's conflicting with this. my main question is how can i debug this myself? any error logs, or console logs that i can look into?

i'm running Chrome 43.0.2357.130 on osx 10.10.3.

the extensions that I have currently installed are:

adblock
antisocial
broswerstack local
ghostery
google art project
livereload
reddit enhancement suite
vimium

**Comment by gdh1995** [comment]
Just my personal ideas: Can you open the url by typing it into Chrome's address bar manually?

If it's opened, then this is a crash that Chrome treats Vimium's `chrome.tabs.create()` as a popuped ad page and closes it.

If not, then please disable `AdBlock` and try again - I think AdBlock may prevent some urls.

**Comment by aaronharding** [comment]
> Can you open the url by typing it into Chrome's address bar manually?

i'm not sure i understand what you mean by this :p i'm not opening any urls, i'm just opening a new tab (and from there trying to navigate to wherever).

what is happening is that either I am on the new tab screen, or have already browsed to a different website within this ~1 second window and then the tab closes.

**Comment by gdh1995** [comment]
If it occurs for a new tab opend by pressing `Ctrl+T` or clicking the most right button in the tab bar?

Besides, what's your Vimium's version? From master or Chrome webstore?

**Comment by smblott-github** [comment]
@aaronharding. Vimium doesn't do anything particularly special when you use `t`; it just opens a new tab with the URL you've provided.  So it seems unlikely (though not impossible) that Vimium is the problem here.

Could you try to eliminate all of the other possibilities?

- Does the tab still close if you visit the Google Art URL by typing it into Chrome's omnibox?

- Does it close with Vimium disabled?

- Does it close with all of your other extensions disabled?

(I tried adding [this](https://www.google.com/culturalinstitute/u/0/project/art-project) as my new-tab page, and I'm not seeing a problem.)

**Comment by aaronharding** [comment]
@gdh1995 i'll be debugging that now: i use the vimium shortcut `t` to open a new tab, i'll try just using `ctrl + t`. but first..

@smblott-github thanks for the suggestions, i've disabled vimium and will see what happens for the rest of the day. also the link you referenced is not the ~exact~ tab page i was talking about, the google art project [is a Chrome extension](https://chrome.google.com/webstore/detail/google-art-project/akimgimeeoiognljlfchpbkpfbmeapkh?hl=en)

**Comment by aaronharding** [comment]
okay, I think it's now something else. today I opened a new tab from a link, so subverting the Google Art Project new tab page, and it kept switching back to my previous tab (and not closing it). i was using `alt+tab` to switch back to the new tab, and it kept reverting me to the previous tab. this happened 3 times, and the delay was about 200ms, way less than the second delay i was experiencing before (and the different too that the tab was staying open, it was just switching tabs back again).

this was all with vimium disabled so the issue must lay somewhere else. i will close this issue later on if no-one has anything to add.

**Comment by smblott-github** [comment]
OK.  Thanks for the update, @aaronharding.
