### ISSUE TITLE
Some link does not show when pressed "f"

### ISSUE THREAD

**Issue by tayk045** [philc/vimium#1758]
First of all, love Vimium and thank you for creating such a wonderful product.

However, I found out that for some web such as gizmodo or engadget the link does not show when pressed "f" or "F"; especially, with their recommended link (in the picture below). 

I don't know whether this is a bug or it is neglected because of the nature of their web but please take a look into it.

Chrome version: 43.0.2357.130 m
Vimium version: 1.51

Thank you,

![capture](https://cloud.githubusercontent.com/assets/13112458/8423727/38d6109a-1f18-11e5-8733-c0340f1f01d6.PNG)
![capture1](https://cloud.githubusercontent.com/assets/13112458/8423728/38dfe4b2-1f18-11e5-951a-d76f06bfc043.PNG)

**Comment by smblott-github** [comment]
Thanks, @tayk045.  Could you post the actual links, please?

**Comment by tayk045** [comment]
Here are the 2 links:
http://gizmodo.com/would-you-try-3d-printed-meat-1714745092
http://www.engadget.com/2015/06/29/google-hangouts-ios-update/?ncid=rss_truncated

**Comment by smblott-github** [comment]
Thanks, @tayk045.  On Gizmodo, the "Recommended stories" seem to be in a separate frame.  Currently, Vimium only handles links within the current frame.

(And it's the same on the engadget page.)

**Comment by tayk045** [comment]
Oh okay. Thank you very much for your quick response.
So, now I should closed this issue, right? because it is currently not supported by Vimium?

**Comment by smblott-github** [comment]
Yes.  We know that the limit of link hints being in a single frame is an issue.
Closing.
