### ISSUE TITLE
Feature request: make goUp and goToRoot background

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#1760]
The two commands now use `window.location.href`, but I think we may not want to go up for an iframe. If we get the current tab's url, things would be better.

**Comment by gdh1995** [comment]
Here's my code in Javascript:
``` javascript
goUp: function(tab) {
  var url, urlsplit;
  url = tab.url;
  if (url.indexOf("://") === -1) { return; }
  if (url.endsWith("/")) {
    url = url.slice(0, -1);
  }
  urlsplit = url.split("/");
  if (urlsplit.length > 3) {
    urlsplit = urlsplit.slice(0, Math.max(3, urlsplit.length - commandCount));
    chrome.tabs.update(null, {url: urlsplit.join('/')});
  }
},
goToRoot: function(tab) {
  var url;
  url = tab.url;
  if (url.indexOf("://") === -1) { return; }
  url = (new URL(url)).origin;
  chrome.tabs.update(null, {url: url});
},
```

**Comment by smblott-github** [comment]
Good point, @gdh1995.  We might achieve the same thing by handling these two commands in the main frame only (and always) -- much like we do with the Vomnibar.

**Comment by gdh1995** [comment]
Oops, I've met a situation in which these two commands should work on current page. Says there's a top frame with only one child frame, `goUp` should do on the child frame only.

The top frame is just a trick to hide real page URL on Chrome's omnibox, but it's really inconvenient.
