### ISSUE TITLE
Doesnt work at all in Chrome Canary

### ISSUE THREAD

**Issue by lmartins** [philc/vimium#1762]
This has become an essential extension for me, so im sad to say it doesn't work at all in Chrome Canary.
Is there anything it can be done to make it work?

**Comment by mrmr1993** [comment]
Thanks for letting us know. I'll try to get canary installed to test this.

A few questions that would be useful to get answered:

* Which Chrome version are you currently running?
* Which Chrome version do you last remember Vimium working on?
* Is Vimium still broken if you start Chrome with a blank profile (using the `--user-data-dir` command line flag)?
* Do any errors show up in the developer tools console on webpages, or in the background page's console?
* Does the version from `master` here work any better?

**Comment by remyo** [comment]
Works fine for me. Canary updates so frequently that when this does happen it's usually temporary.

**Comment by lmartins** [comment]
Just updated and is working now yes.
