### ISSUE TITLE
Text box focusing

### ISSUE THREAD

**Issue by wj-zhe** [philc/vimium#1765]
The <gi> function works actually really well, and I appreciate how much time it saves. However, whenever focusing action happens, the cursor always appears in the very front of text box, and it quite often requires pressing END additionally for normal editing. So, it there any possibility to change this behavior?

**Comment by mrmr1993** [comment]
@wj-zhe the code should actually already be doing this! Could you try again with your other extensions disabled, to see if another extension is causing this?

**Comment by wj-zhe** [comment]
@mrmr1993 took your advice and tried on variable sites, the issue still exists. w or w/o all other extensions disabled, the code works differently on different sites, on google, yahoo, youtube, tumblr, it still jumps to the very front, though everything seems to be fine on github, twitter, pinterest. 
BTW, check and uncheck "Don't let pages steal focus on load" appears to have no affect on this.

**Comment by mrmr1993** [comment]
I can't repro this on Google with the webstore version or master on Chromium 43.0.2357.134. Some questions that might help provide some answers:

* which Chrome version are you running (chrome://version)?
* do you have any flags turned on (in chrome://flags), and if so, does the problem persist when they're disabled?
* does the problem still persist if you start chrome with a blank user data directory (using the `--user-data-dir` command line flag)?
* can you provide a specific URL and indicate a specific textbox where this happens?

**Comment by wj-zhe** [comment]
tried your advises, but nothing really changed
answers to your questions:
* 43.0.2357.134 (Official Build) m (64-bit) on Win7 Ultimate w SP1
* all flags are reset to default
* tried with blank user data directory, but no change
* URLs, problem occurs after new search or simply refreshing page
    www.google.com, www.yahoo.com, www.youtube.com, www.reddit.com
* on following sites, everything seems to be fine:
    www.yandex.ru, www.vk.com, www.twitter.com, www.pinterest.com

I'll keep trying on other computers and sits and return with test results :)

**Comment by wj-zhe** [comment]
@mrmr1993 seems to be the same on other devices.

**Comment by mrmr1993** [comment]
@wj-zhe It works fine for me under arch (chroot on my phone) and 2 Ubuntu boxes, so I'm wondering if it's an OS thing. Were they all Windows machines?

I'll try and get hands on a Windows box tomorrow to see if I can repro this.

**Comment by gdh1995** [comment]
Vimium works on https://www.google.com.hk for me, and I'm using Chrome 43 on Windows 8.1 x64.

**Comment by wj-zhe** [comment]
@mrmr1993 both my machines run Windows 7 Ultimate, one is 64-bit version. I did several tests afterwards, and sometime it works just fine on www.google.com, or .ru or .hk, but with www.flickr.com, www.yahoo.com, www.reddit.com, it just doesn't work. @gdh1995 could you try these sites too?

**Comment by gdh1995** [comment]
Correct: What I tested 7 hours ago was my custom Vimium (much earlier than the webstore version) - sorry!

For https://search.yahoo.com/search?p=123, the master version does fail to set the caret position. Also for https://www.google.com.hk/search?q=abc. As for flickr.com, sorry again: I'm in China and it seems to be banned.

I check source of `focusInput`. From `vimium_frontend.coffee`'s line 424:
``` coffeescript
  keydown: (event) =>
    ...
    visibleInputs[selectedInputIndex].element.focus()
...
visibleInputs[selectedInputIndex].element.focus()
if visibleInputs.length == 1
  @exit()
```

So @mrmr1993 here Vimium does not move the caret. Shall we reuse `DomUtils.simulateSelect`?

**Comment by mrmr1993** [comment]
Apologies, it seems as though I'd misunderstood the issue; I've been testing link hints instead of the focus input command. Sorry for any confusion I've caused with that.

>So @mrmr1993 here Vimium does not move the caret. Shall we reuse `DomUtils.simulateSelect`? 

@gdh1995 that seems like the way to go. Are you happy to make a PR for this?

**Comment by wj-zhe** [comment]
@mrmr1993 @gdh1995 Thank you guys.
