### ISSUE TITLE
One shortcut to go to open tab or history or bookmark

### ISSUE THREAD

**Issue by AminaG** [philc/vimium#1766]
Sometimes I want go back to a recent tab I used.
I don't remember if it is already opened or not.

I want a shortcut that combine all the result of 'o' and 't'.
If the tab of what i search opened it will move to that tab.
If the tab doesn't exists it will create new tab.

What do you think? Is it clear, or to try explain it in other words?

**Comment by mrmr1993** [comment]
I like the sound of this too. My main concern is the UI: how do we present the history/bookmark entry and the tab entry. The two options I can think of:
* show both
  - this can push the desired results off the bottom of the list (in worst case halving the number of relevant entries)
* overload a single result
  - how do we make this discoverable?
  - what keyboard shortcuts/interface would make sense for it?

Any suggestions for how this would work?

**Comment by AminaG** [comment]
I think to overload a single result.
Show altogether (view the attached image)
Start with results from opened tabs, after that other results.

'e' can be a good shortcut for it.

![image](https://cloud.githubusercontent.com/assets/3584317/8736311/eea873cc-2c1f-11e5-91f1-8e9a7d058d67.png)

**Comment by mrmr1993** [comment]
I think I misunderstood your original issue, sorry:

> If the tab of what i search opened it will move to that tab.
> If the tab doesn't exists it will create new tab.

I had assumed that people might want either the tab *or* the history entry, and that we were discussing a UI to show both.

I personally don't like the idea of changing/adding a mode which disallows some history entries in favour of focusing a tab, but I think having a UI that supports both options in a clear, intuitive way would be good to have. Sorry for any confusion.
