### ISSUE TITLE
Scroll by a custom amount?

### ISSUE THREAD

**Issue by dbb** [philc/vimium#1767]
Is it possible to bind a key to scroll by a custom amount? I can't seem to find any documentation on this. I've tried binding different keys to things like `5j`, `jjjjj`, `window.content.scrollBy(0,300)`, `scrollDown scrollDown`  etc., basically any random thing that I could think to try.

**Comment by smblott-github** [comment]
@dbb... The only control you have (for `j`/`k`) is via the (global) `scrollStepSize` setting on the options page.  Page scrolls depend on the size of the window.

**Comment by zgana** [comment]
I would also be interested in finer tuning of scrolling.  My use case is aligning paragraph start (end) with viewing area top (bottom).  I'm just a bit OCD like that.  Before I found vimium today, I'd usually use mouse scroll and arrow keys to get two different step sizes, which can achieve arbitrary text alignment after alternating application.  I can still do that with mouse scroll and j/k, but it would make me extra happy if I could do it all with the keyboard.

Based on a quick scan of scroll-related code, I guess I could try hacking on the source to create scrollUpSmall and scrollDownSmall commands or something, but I'd certainly rather stick with official releases.

Would it be possible to extend the `map` configuration directive to support counts?
