### ISSUE TITLE
Feature: Ability to F or f behavior but with .focus()

### ISSUE THREAD

**Issue by davidrenne** [philc/vimium#1773]
I want to be able to navigate the same things that F will find, but I want to just focus an element instead.

There are sometimes on facebook and other sites that I do not see an appropriate keystroke to click something with F, so a work around could be that we can ESC out when we are in that scenario and click some sort of alternate tab thing.

Then we focus on the element and then just tab our way into something in the DOM.

I have seen this with facebook comments, but I will add more comments again to this issue later if I find another website that is publicly available to in which I could use such a focus thing

**Comment by smblott-github** [comment]
This is a candidate for adding to #1948.

**Comment by philc** [comment]
I understand the request to focus an element on the page, but I don't yet get the rationale. @davidrenne, could you explain with a concrete use case?

**Comment by davidrenne** [comment]
You basically should be able to see an element on a page such as a hyperlink or an input element and jump your cursor toward it and focusing on it.

There are so many use cases where vimium lovers could possibly use this.

Example is mostly with form inputs I thought originally thinking back at it.  But I suppose a standard f command can navigate slightly.

I just hate at the time I wrote this some kind of scenario with an interface that runs completely useless when f clicks on things.

There are cases where highlighting something in the DOM can help you get some things done.

Either way I dont use vimium full time so I can just pick up my mouse and click or move.  It would be fun to try a function out like this in a fork and see if I can come up with a proper use case on an  unstable branch!

**Comment by smblott-github** [comment]
Closing.
This can probably be solved with existing link hints or with `gi`.
