### ISSUE TITLE
not work~~

### ISSUE THREAD

**Issue by hgati** [philc/vimium#1776]
not working site.

http://demo.designwall.com/#dw-question-answer

anything not working...

**Comment by mrmr1993** [comment]
It seems to work fine for me, but you have to switch frame (`gf`) to interact with the main page. Can you try that and see if it helps?

**Comment by gdh1995** [comment]
On my Chrome, on the top frame `f` works like:
![1](https://cloud.githubusercontent.com/assets/5547703/8923804/40616708-3528-11e5-8c38-38d06033ef88.png)

And the main page is in an `<iframe>`.

**Comment by hgati** [comment]
Okay, "gf"
works every fine.

**Comment by mrmr1993** [comment]
@hgati can you close the issue if everything is fine?

**Comment by hgati** [comment]
YES, Thanks !
