### ISSUE TITLE
korean/japanese/chianese text (find mode)

### ISSUE THREAD

**Issue by hgati** [philc/vimium#1777]
find mode(/) can't input korean/japanese/chainese text.

![snap1](https://cloud.githubusercontent.com/assets/6913728/8924899/a5488f7e-353d-11e5-810c-ddb5a5be4d9f.png)

**Comment by mrmr1993** [comment]
Looks like #1693 should have resolved this; it should be fixed in master and will work correctly in the next release.

**Comment by gdh1995** [comment]
I'm sorry but if it's Chinese (a language spoken mainly in China) ?

**Comment by hgati** [comment]
no, it's Korean.

**Comment by hgati** [comment]
My keyboard is Korean Keyboard not Chinese Keyboard.

![snap2](https://cloud.githubusercontent.com/assets/6913728/9734736/8145c570-5670-11e5-9ee3-30e9c3057a48.png)

**Comment by smblott-github** [comment]
@hgati.  This should be fixed in the next release, which should happen in the next week or so.
