### ISSUE TITLE
Scrolling is painful on the help screen

### ISSUE THREAD

**Issue by sid-kap** [philc/vimium#1781]
On my computer, Vimium's help screen doesn't completely fit in one window, so I need to scroll to see all of the options.
Unfortunately, <kbd>j</kbd> and <kbd>k</kbd> don't work to scroll through the help screen.

Can we add a feature so that <kbd>j</kbd> and <kbd>k</kbd> adjust the scroll of the help page, not the main page, when the help page is open?

**Comment by mrmr1993** [comment]
A fix for this (95f0df630783274b686ee530816a842565413cf2) is already in master.

**Comment by sid-kap** [comment]
Excellent!
