### ISSUE TITLE
Vomnibar size changes with page zoom

### ISSUE THREAD

**Issue by sid-kap** [philc/vimium#1782]
Currently the size of the vomnibar and the help screen vary based on the current zoom setting in Chrome.

I think it might be a better idea to make this size fixed (and possibly adjustable in vimium settings).

Chrome's zoom feature is useful: when you visit a site with text that is too small or large, you can, for this site only, adjust the text size. However, I don't see the need to adjust the Vomnibar's size ad-hoc. If you set the size in vimium settings to a comfortable size, you should not need to adjust it on a per-website basis.

**Comment by natestemen** [comment]
Same here. I'm on Firefox and since my screen resolution is relatively high, I zoom in on most webpages to make the readable for me. This means the vomnibar is constantly changing sizes on quite a few webpages.

**Comment by devnoname120** [comment]
Unfortunately I couldn't find a way to override page's zoom just in shadow DOM. I couldn't find either a reliable way to obtain page's zoom which would allow to resize the omnibar to compensate for it.

If you find a way to do either of those, I'd be happy to do a pull request.

**Comment by devnoname120** [comment]
Note that it should actually be possible using [`vh` and `vw` units](https://web-design-weekly.com/2014/11/18/viewport-units-vw-vh-vmin-vmax/) which work for everything [including text](https://css-tricks.com/viewport-sized-typography/).

See here an example where zooming in and out doesn't change the text size: https://css-tricks.com/examples/ViewportTypography/

Pitfall would be that the box size and the text size would now depend on the size of the viewport. This means that resizing the window would change the size of the text (try resizing the window of the link above). It's not an issue for my usage, but I can see how it could bother other people.

**Comment by gdh1995** [comment]
`vw` and `vh` means font size will change if only window size is changing (e.g. <kbd>Win+ArrowLeft</kbd> to move Chrome window to the left half of a screen).

BTW, there's no API to get a real zoom ratio from content scripts (`devicePixelRatio` = system DPI * zoom ratio), so considering the system DPI, we may have to use `chrome.tabs.getZoom` from background scripts to get a real zoom and then override it.

As for overriding it, `<html>.style.zoom` in vomnibar.html will be enough.

**Comment by devnoname120** [comment]
> As for overriding it, `<html>.style.zoom in vomnibar.html` will be enough.

Would not work in Firefox, though.
https://caniuse.com/#feat=css-zoom

**Comment by gdh1995** [comment]
@devnoname120 Well, on Firefox `rem` and `<html>.style.fontSize` can work well.

You may try my custom version of Vimium - [Vimium C](https://github.com/gdh1995/vimium-c) - it will try to force `page zoom >= 1`, and in those cases on Firefox, it will apply `fontSize` to zoom in the whole vomnibar iframe.
