### ISSUE TITLE
Is there a key mapping for "repeat last command"? 

### ISSUE THREAD

**Issue by janacm** [philc/vimium#1785]
In regular vim, if you press "." (period) then it will repeat the last command you executed. Does Vimium support this?

**Comment by gdh1995** [comment]
No, it doesn't now.

`performFind` and `performBackwardsFind` will remember the last position.

For other commands, you may use `3<<` and `<<` will be repeated for 3 times.

**Comment by smblott-github** [comment]
Closing.
Lack of interest.
