### ISSUE TITLE
Please make goto bookmark window to search in bookmarks folder

### ISSUE THREAD

**Issue by AminaG** [philc/vimium#1786]
For example, if I have folder named "Free aps"
I want easy search for all my apps by tying

"Free"

In the bookmark chooser UI.

What do you think?

**Comment by gdh1995** [comment]
you need to type "/" to tell Vimium folder names should be considered about. Like "/Free".

**Comment by AminaG** [comment]
Awesome!!!
Is it documentated  anywhere?

**Comment by gdh1995** [comment]
Here: https://github.com/philc/vimium/wiki/Tips-and-Tricks#searching-bookmarks-by-folder
