### ISSUE TITLE
When I hode 'd' key and change focus, the tab scrolls page down until reach bottom

### ISSUE THREAD

**Issue by Lw-Cui** [philc/vimium#1788]
When I hode `d` key to look through a page and change my focus (such as clicking other application window) , my chrome tab scroll page down until reach bottom of the page and I cannot stop it. Could this be fixed?
my `Google Chrome`	44.0.2403.130  and `Vimium` 1.51
Thanks.

**Comment by smblott-github** [comment]
Yes, @Lw-Cui, that will happen.
We use the `keyup` event to stop scrolling, and - if the focus changes - then we don't see the `keyup` event.

I guess we could also stop scrolling on `blur`.

**Comment by gdh1995** [comment]
> stop scrolling on `blur`

This is not enough, since sometimes a costly event listener (like a heavy`onscroll`) in some websites may cause `keyup` is skipped. But I'm sorry that I have no example page on hand.

**Comment by mrmr1993** [comment]
I think this is fixed in #1775 by commit 98e7095 (but I'll test later to make sure).

**Comment by smblott-github** [comment]
#1794 should fix your issue, @Lw-Cui.
