### ISSUE TITLE
Vomnibar loads results slowly

### ISSUE THREAD

**Issue by n-simone** [philc/vimium#1790]
I'm running Vimium 1.51 in Chrome 44.0.2403.155 in Chrome OS on a Toshiba Chromebook 2 (4 GB version).

When I start typing in the vomnibar, it takes 4 to 5 seconds to start loading results. I really like the functionality that the vomnibar provides over Chrome's omnibar, but the delay is fairly annoying. I have a friend who uses Vimium on a computer that's no more powerful than mine, and he says results load immediately for him. Is there anything I can try on my end to resolve this?

**Comment by mrmr1993** [comment]
The Vomnibar searches the history and bookmarks for results, so if you have a large history or a lot of bookmarks that could be slowing it down. Is the response time more reasonable if you run Vimium in an empty profile?

**Comment by n-simone** [comment]
I wouldn't think it would have too much to search through, since Chrome automatically deletes history that's over 90 days old. Unfortunately I can't install extensions in a guest session in Chrome OS, so I don't think I can test it in an empty profile.

When I use b, it loads results instantly, even though I have way more bookmarks than I need.

I'm considering clearing my history to see if that helps.

**Comment by mrmr1993** [comment]
I think you can create a new user, and that will have the same effect as creating a blank profile in other OS's, so you can test the baseline performance without deleting your history first.

**Comment by n-simone** [comment]
I tried vimium as a new user (well, technically it was a work account), and results loaded instantly.

I then deleted my history in my main account, and results now load instantly here as well.
