### ISSUE TITLE
Unselect off highlighted tool bar

### ISSUE THREAD

**Issue by davidrenne** [philc/vimium#1792]
I dont know if it is possible to control the focus of the highlighted URL bar.  But it would be great if somehow when using J/K to navigate tabs if we could control whether we always wanted our URL bar to unfocus.

This way you can continue to navigate without being interrupted.  

I would love this option and also an option to systematically unfocus from textboxes if I am not typing in them for some period of time.  This way the keystrokes are more ready to fire.

Currently I get a sad emoticon in my head when I am trying to navigate with vimium and one of these scenarios hits.

**Comment by smblott-github** [comment]
@davidrenne.  If the focus is in Chrome's Omnibox (navigation bar?), then Vimium doesn't receive keyboard events, so there's no a lot we can do.  (I use this ... https://chrome.google.com/webstore/detail/new-tab-url/njigpponciklokfkoddampoienefegcl ... to avoid the focus ending up in the Omnibox at all.)

**Comment by davidrenne** [comment]
Thanks for the reference.  Closing now!

**Comment by davidrenne** [comment]
Ya the one thing I need is sometimes I go into the nav bar after I am in a page, if I move off a tab, I want it to unfocus the URL bar.  New tabs usually dont cause me issues.  It's when I am not paying attention and leave my focus on the bar.

I just need to pay more attention where my focus is left before changing to another tab.
