### ISSUE TITLE
[QUESTION] What does <a-p> mean?

### ISSUE THREAD

**Issue by danthareja** [philc/vimium#1799]
I really like vimium but I have no experience with actual vim or vim documentation so I'm a little confused about the command for pin/unpin tabs

What is the keypress sequence for `<a-p>`?

**Comment by smblott-github** [comment]
Means press-and-hold `Alt` then press `p`.

(Don't really like that binding, myself.  I remap it to `gp` on the options page... `map gp togglePinTab`.)

**Comment by danthareja** [comment]
How wonderful, thank you!!
