### ISSUE TITLE
Feature: switch to next/previous tabs in the order they had been viewed, not the order they are listed on the tabbar

### ISSUE THREAD

**Issue by lolmaus** [philc/vimium#1800]
Hey.

Sometimes you open a tab with a link and you want to go back to the previous tab without closing the new tab.

Using J/K commands might force you to flip through a dozen of tabs before you get to the desired one.

I suggest that we have another pair of hotkeys that would flip tabs in the order they had been viewed by the user, not the order they appear on the tabbar.

**Comment by smblott-github** [comment]
Thanks, @lolmaus.  This tip from the wiki might help... https://github.com/philc/vimium/wiki/Tips-and-Tricks#recently-visited-tabs

**Comment by lolmaus** [comment]
@smblott-github, thank you for the awesome workaround!

I suggest we keep this feature request open, so that it will be able to go to the previous tab with one click instead of three.

**Comment by smblott-github** [comment]
I swap `t` and `T` to make "previous tab" just two keystrokes....

```
map t Vomnibar.activateTabSelection
map T createTab
```
