### ISSUE TITLE
Possible to specify an order for Next/Previous (>>/<< vs literal "Next" and "Previous")?

### ISSUE THREAD

**Issue by dragon788** [philc/vimium#1801]
On my new favorite forums (Geekhack and Deskthority, yes the mechanical keyboard bug has bitten me in addition to my "Vim all the things" compulsion) the Next/Previous text leads to the next thread, not the next page. It does have >> and << for previous and next page as well as the typical page numbers, but it seems that 'next' matches before >> and so when I try to use the awesome ]] shortcut, it throws me way off by jumping to a new thread.

Just wondering if it already works or is possible to do an order matching, where I can rearrange the match order per site or globally.

**Comment by smblott-github** [comment]
Hmm.  Not sure what we can do about this.  The links for next thread and next page both look like reasonable choices for `]]`.

(Unsatisfactory workaround... In `master`, you can paste into the "find" box.  If you paste in `next »`, then `n`-`Enter` takes you to the next page.)

**Comment by mrmr1993** [comment]
> Just wondering if it already works or is possible to do an order matching, where I can rearrange the match order per site or globally.

Rearranging the previous patterns/next patterns in the options page will normally do this.

**However**, Vimium tries to find an element with `rel=next` before it applies those patterns, and so picks the first (and only) element in `document.querySelectorAll("link[rel=next], a[rel=next], area[rel=next]")` on Geekhack, which points to the next thread. (I can't seem to repro the issue on Deskthority.)

You could work around this by putting `<link rel="next>` and `<link rel="prev">` with the URLs you want at the top of the document, and then `[[` and `]]` will work as you wanted. For example, the following could be put in a tampermonkey script/chrome extension/etc. that runs on the Geekhack:

```js
var pageNavigationLinks = document.querySelectorAll("a.navPages"),
    pageLinks = {};
for (var i=0, l=pageNavigationLinks.length;i < l;i++) {
  var navLink = pageNavigationLinks[i];
  if (navLink.textContent == "\xab") { // "«"
    pageLinks.prev = navLink;
  }
  else if (navLink.textContent == "\xbb") { // "»"
    pageLinks.next = navLink;
  }
}
for (var i in pageLinks) {
  var linkRel = document.createElement("link");
  linkRel.rel = i;
  linkRel.href = pageLinks[i].href;
  document.head.insertBefore(linkRel, document.head.firstChild);
}
```

**Comment by dragon788** [comment]
Thanks for the workarounds guys! I know I was on geekhack when I experienced the issue but I've got like 100 tabs open to each of these forums so I kind of lost track whether it happened on both. I'll definitely have to try that grease monkey script as that shouldn't affect other pages negatively and will make my vimium experience that much more smooth.

**Comment by dragon788** [comment]
Thanks @mrmr1993 I threw this together based on your snippet and it's working wonderfully.
```
// ==UserScript==
// @name         Geekhack Vimium fix
// @namespace    https://github.com/philc/vimium/issues/1801/
// @version      0.1
// @description  This fixes the ]] and [[ shortcuts for next page (in a thread) which hits the next thread shortcut first on Geekhack
// @author       mrmr1993
// @match        https://geekhack.org/index.php*
// @grant        none
// ==/UserScript==

var pageNavigationLinks = document.querySelectorAll("a.navPages"),
    pageLinks = {};
for (var i=0, l=pageNavigationLinks.length;i < l;i++) {
  var navLink = pageNavigationLinks[i];
  if (navLink.textContent == "\xab") { // "«"
    pageLinks.prev = navLink;
  }
  else if (navLink.textContent == "\xbb") { // "»"
    pageLinks.next = navLink;
  }
}
for (var i in pageLinks) {
  var linkRel = document.createElement("link");
  linkRel.rel = i;
  linkRel.href = pageLinks[i].href;
  document.head.insertBefore(linkRel, document.head.firstChild);
}
```

**Comment by gdh1995** [comment]
I agree that there should be an order. On some websites, they has an index list like:

`<<    <    3    4    5    6    7    >    >>`

Then Vimium always finds `<<` and `>>`, which is annoying.

Besides, I think we may use `element.innerHTML == word || element.title == word` instead of matching `innerHTML` using a regexp `exactWordRegex`. `.textContent` is also not bad.

**Comment by dragon788** [comment]
I think I found the cause for the issues. It appears that SMF (simple machine forum) by default leaves the Previous|Next thread links above the pages of the current thread. I'm going to see about adding more matches to my version of the script, otherwise I'll probably have to duplicate it for each site I want to match.
