### ISSUE TITLE
Allow <A-Enter>  to open in a new tab in Vominibar opened by `o`(lowercase)

### ISSUE THREAD

**Issue by BohrShaw** [philc/vimium#1804]
Similar to Chrome's Omnibar, in which pressing `<A-Enter>` could open in a new tab, I like to see this available in Vomnibar.

From time to time, I pressed `o`, then realized it should be `O`, so I would `<Esc>`, then `O`. This is not ideal and the reason I open up this issue.

**Comment by smblott-github** [comment]
Thanks @BohrShaw. `<Ctrl>-<Enter>` does that.
(I guess we could add your suggestion, if that's the Chrome way.)

**Comment by BohrShaw** [comment]
Oh, I didn't realize `<Ctrl>-<Enter>` can make it.
`<A-Enter>` is actually cross-browser and I would love to see it's available.

**Comment by smblott-github** [comment]
Hmm. `<Alt>-<Enter>` doesn't seem to open in a new tab (from the omnibox) for me. ???

**Comment by BohrShaw** [comment]
@smblott-github Strange! Then what does it do?
I usually press `<A-Enter>` when there are at least _some text_ in the omnibar.

**Comment by smblott-github** [comment]
> Then what does it do?

Nothing.  Like no key was pressed. (And I don't think it's a window-manager binding.)

**Comment by BohrShaw** [comment]
I'm pretty sure the behavior of `<A-Enter>` is available in vanilla browsers like Chrome/Chromium, Firefox, IE/Edge. (I don't use OS X though.)

**Comment by mrmr1993** [comment]
The [official keyboard bindings list](https://support.google.com/chrome/answer/157179?hl=en-GB) (under address bar shortcuts) seems to indicate that Chrome for Windows has the shortcut, but Chrome for Linux doesn't

**Comment by BohrShaw** [comment]
@mrmr1993 I'm using Chromium on Ubuntu, which has this shortcut.

**Comment by smblott-github** [comment]
Doh!
I took a closer look and (apparently) I do have a window manager binding. `<Alt-Enter>` does indeed open in a new tab from the omnibox, as @BohrShaw stated.  Sorry for the confusion.

If that's what Chrome does -- and since we don't anything else with the binding -- we should probably do the same, as originally suggested.

**Comment by philc** [comment]
Agree.

**Comment by smblott-github** [comment]
Closed in light of #1805 (which is merged).

**Comment by mrmr1993** [comment]
Late to the party, but I did too. Sorry all!
