### ISSUE TITLE
XML display in Chrome produces a large block of vimium comments

### ISSUE THREAD

**Issue by NickHibma** [philc/vimium#1807]
When browsing to an XML page produced by a web app we use I get a large block of Vimium at the bottom. Vimium does not seem to work (which makes sense).

![image](https://cloud.githubusercontent.com/assets/572576/9770008/de305c92-572d-11e5-9cb3-087ac96d4f9d.png)

**Comment by smblott-github** [comment]
Thanks @NickHibma.
I think we have this one fixed (see #1798, and there are some other older issues).
It'll be in 1.52, which should be released within the next week or so.
