### ISSUE TITLE
Can't close the blank page

### ISSUE THREAD

**Issue by lichenhao** [philc/vimium#1810]
RT

**Comment by emaniacs** [comment]
In the blank page, vimium is not active, you can close with Ctr+w. :smile:

**Comment by smblott-github** [comment]
Thanks, @lichenhao.
If you mean `chrome://newtab`, then @emaniacs is correct: https://github.com/philc/vimium/wiki/FAQ#how-can-i-get-vimium-to-work-on-chromes-new-tab-page

Please report back if you mean another page.

**Comment by lichenhao** [comment]
Thank your, I resolved that problem, how can I open the link rendered by ajax.

**Comment by mrmr1993** [comment]
> how can I open the link rendered by ajax.

Which link? Which site?

**Comment by lichenhao** [comment]
Like the http://caniuse.com/#info_news .

**Comment by lichenhao** [comment]
I can't open the links in article , because that rendered by ajax content.

**Comment by mrmr1993** [comment]
@lichenhao They all seem to be working for me.

Which link/links in particular? A screenshot could be helpful.

**Comment by lichenhao** [comment]
I saw that, when I scroll the page, the vimium just refreshed. It works for me now. THX fully.
