### ISSUE TITLE
Omnibar relative link feature request (forked! need little help)

### ISSUE THREAD

**Issue by PickRelated** [philc/vimium#1812]
Would be nice to have an opportunity to visit internal pages instead of having to type full hostname.
Today I just instinctively typed in relative path to site page and it did not work out. I thought many people did so too.
For example:
I am on page **https://github.com/settings/profile**
I open **omnibar** and type in **/philc/vimium** and I am directed to **https://github.com/philc/vimium**
What now happens is totally useless. I can not imagine someone googling something starting with a "/".

Can we hope you are implementing this feature soon?
Or may be someone wants to fork for this feature?
Thanks!

**Comment by PickRelated** [comment]
I have forked but obviously I am not professional enough to find function that visits the link. I have tried to alert and console.log, like, everywhere where location.href is present.
If someone can point me the direction - I will implement this feature myself.

**Comment by PickRelated** [comment]
Okay help needed! I am on the final of the first stage. I detect relative link and am ready to change query to desired one. But I do not know how to get current URL from inside function to create that query. window.location.href and document.location.href point to extension instead of browser URL.

**Comment by PickRelated** [comment]
Okay looks like half of job done.
I need a consultation. Here is what I have done so far (sorry for js, I do not know coffeescript YET):
```javascript
//pages/vomnibar.js starting from line 167
      } else if (action === "enter") {
        isRelativeLink = (this.input.value.substr(0, 1) == '/');
        isCustomSearchPrimarySuggestion = ((ref = this.completions[this.selection]) != null ? ref.isPrimarySuggestion : void 0) && (((ref1 = this.lastReponse.engine) != null ? ref1.searchUrl➝
        if (this.selection === -1 || isCustomSearchPrimarySuggestion) {
          query = this.input.value.trim();
          if (!(0 < query.length)) {
            return;
          }
          if (isCustomSearchPrimarySuggestion) {
            query = Utils.createSearchUrl(query, this.lastReponse.engine.searchUrl);
          }
          this.hide(function() {
            return chrome.runtime.sendMessage({
              handler: openInNewTab ? "openUrlInNewTab" : "openUrlInCurrentTab",
              relativeLink: isRelativeLink,
              url: query
            });
          });
        } else {
```

```javascript
//background_script/main.js before each chrome.tabs.update or chrome.tabs.create
        if (request.relativeLink) {                                                                                                                                                            
          var parsedUrl = tab.url.match(/^[\w-]+:\/*\[?([\w\.:-]+)\]?(?::\d+)?/);
          request.url = parsedUrl[1] + request.url;
        }
```

But what's missing is dropdown suggestion (history/bookmark/relative url).
How should I do next? Should I make it in coffeescript and make a pull request so you could take a closer look?
Or should I first add suggestion (category) to dropdown?
Or perhaps my code is not good? I am ready for your suggestions/critics.

**Comment by mrmr1993** [comment]
Nice idea. Makes me wonder if a similar thing with `./` and `../` to start from the current and parent directories would also be useful.

> what's missing is dropdown suggestion (history/bookmark/relative url).

To get those, you'll need to change the query sent to the background page to have the prefix too. By which point, I would be tempted to change the url before sending to `openUrlInNewTab`/`openUrlInCurrentTab` and completely avoid touching background code.

> How should I do next? Should I make it in coffeescript and make a pull request so you could take a closer look?

What you've got looks pretty good to me so far. Making a PR is probably the best way to go, then it'll be easy to see what changed and to test the code.

**Comment by smblott-github** [comment]
A couple of thoughts...

- This would prevent the user for searching for `/usr/bin/env`.  And would be pretty confusing if they tried.

- To work well, this would need completion for URLs (which we can't do).  On github, it's not so hard to guess URLs, but on many sites it's next to impossible.

- For the specific use case described, just typing `philc` into the vomnibar works pretty well already.

- For most cases, just using `ge` and then editing the URL would probably work better (because then at least you'd get completion for the URLs in your history).

**Comment by mrmr1993** [comment]
As an alternative, the current url's origin could be exposed (say, as `%o`), and then this could just be a search engine `%o%s`. It would also give us powerful options like searching the current site (`google.com/search?q=%o+%s`). Is that something we could consider adding?

To work well (and in general anyway) we might also want to look at applying omni completions to search engines we don't match any specific completers for.

**Comment by smblott-github** [comment]
Still seems pretty niche, @mrmr1993. `gU` then `ge` is usually pretty close to this.

(Also, it turns out Google provides reasonable results is you search for `%O`, so we probably wouldn't want to lose that either.)

**Comment by PickRelated** [comment]
@smblott-github gave me a great idea which leads me to changing the way my feature works. Looks like `ge` is what I really needed from start. In this case I think it would be perfect to add a key binding,like, say, `gr` (for go relative) and use `ge` functionality except for deleting prefilled text and making some kind of uneditable placeholder, showing hostname. Or leaving only hostname.
Using `gU` then `ge` is way too uncomfortable because it makes you load index page which you do not want. Not all sites are fast like github.
This approach would not confuse users who want to search for `/usr/bin/env` and users who do not want to research this plugin. And at the same time more advanced users will easily understand and use this feature.
Pls share your thoughts.

**Comment by smblott-github** [comment]
You could use prefix counts (which currently have no meaning in this context).

- `2ge` would strip everything after the last `/` (yes, 2 here is a bit unfortunate/misleading).
- `99ge` would string everything up to the host name (and port).

**Comment by PickRelated** [comment]
@smblott-github Exactly. Except for it is not too intuitive and makes you leave your home row for digits. I did not know about this feature for example.

And for some reason when I type `2ge` I get switched to another opened tab. A bug may be?

**Comment by smblott-github** [comment]
This is a very niche idea; probably not above threshold for a new command.  If the logic is simple and self contained, then it may be above threshold for a few lines of code and a description in the Wiki.

**Comment by PickRelated** [comment]
I am not quite sure I understand what you mean. Correct me if I am wrong: this relative link idea is not worth new command/description in Wiki?

**Comment by smblott-github** [comment]
Not worth a new command.  Is worth description in the Wiki.

**Comment by PickRelated** [comment]
Yes I agree that logic is simple and simmilar to `ge`. But how do I reach for opening `ge` window with only hostname but without using digits?

**Comment by smblott-github** [comment]
You probably need to look at how count prefixes work.

The count prefix is in the request [here](https://github.com/philc/vimium/blob/master/content_scripts/vimium_frontend.coffee#L239).  It needs to be passed along, then used [here](https://github.com/philc/vimium/blob/master/content_scripts/vomnibar.coffee#L50).

**Comment by PickRelated** [comment]
Yep, I do understand how count prefixes work. I am a vim user.
Could you please try yourself `2ge` and confirm it works? Because it does not strip anything for me. I just get current url in vimium omnibar. I do this on non-dev browser (release version of vimium without my code).

**Comment by smblott-github** [comment]
Ah.  Sorry.  Misunderstanding, @PickRelated.

I was just floating the idea of implementing it that way.  It's not implemented currently.

**Comment by PickRelated** [comment]
Sorry, @smblott-github . My bad. Your idea is also good.
I have one more thought which seems to me the best one. If `o` omnibox input starts with `/` - the default action would be to visit relative link. But in the dropdown there should be "search" option (just like in google chrome if you type something like `chrome://extesions` but want to search it). And if omnibar input starts with anything else - you do not need to show "search" option in dropdown. This would correlate with google chrome logic that people are used to. Also this would allow for history completeon. In addition this excludes additional command and count prefix, which to my opinion is preferable to newbee or lazy users.
