### ISSUE TITLE
Problems with switching frames of focus

### ISSUE THREAD

**Issue by Snorlock** [philc/vimium#1818]
I'm trying to use vimuim with scrolling in chat windows like hipchat. But unfortunately its very difficult to get the focus to the right frame. It has a scrolling frame for rooms and people you are talking to, a frame for the chat, and a window for users available in that room. I would like to target focus properly and being able to scroll in the window/frame of choice.

I have tried gf without any luck, maybe its based on old technology.

Maybe same function as detecting different scrollable windows and being able to choose focus.
Or maybe you can do a search of text and choose which window you want focus.

Any ideas or feedback?

**Comment by smblott-github** [comment]
This is a problem.  There's been the idea floating around for a while of using a link-hints-like interface for this.  I think @mrmr1993 has a PR somewhere.

Here are a couple of other thoughts:

- `gf` should not select frames which aren't in the viewport.

- An alternative UI would be to have `gf` behave a bit like `gi` (show the available/visible frames, tab to move to next, anything other than tab to select).

**Comment by Snorlock** [comment]
It would be nice to have! Maybe @mrmr1993 could pull it up? If its not done maybe he could show branch and someone could continue on it?

The show frames like gi could work, or show frames like the linking and select with buttons?

**Comment by Snorlock** [comment]
@smblott-github closed because? Has it been done?

**Comment by andradei** [comment]
I still experience that problem on Gitter where `gf` doesn't let me focus on the right window to focus. Another place I can't scroll all scrollable panels/views (whatever they should be called) is the Google Inbox's left panel.

If this can be fixed (or I be educated, if this feature already exists) I'd be very happy. If not, this is an amazing extension that I use everyday anyways.

Thanks.

Info:
OS X 10.11.5
always on latest Chrome

**Comment by AaronLieb** [comment]
Sorry for the necro, but I am also confused on the status of this issue, is there a feature in place to solve this problem?

**Comment by Eternex49** [comment]
@AaronLieb I was wondering too... Has someone found a solution?

**Comment by slacksystem** [comment]
Wondering why this issue is still closed. It's still comething that almost never works for me. Is it only me that's having this issue? Or is there some other issue tracking it now? Google led me here

**Comment by Eternex49** [comment]
@philc Could you clarify the state of this issue? Were some fixes pushed?

**Comment by sh00kti** [comment]
I am facing this issue too, google led me here.

**Comment by AaronLieb** [comment]
For anyone curious, [vimium-c](https://github.com/gdh1995/vimium-c) has a great implementation of frame switching. When pressing `f`, frame hints appear in red. If the frame isn't appearing, you can go to the top frame with `gF` and then select the frame from there. 

cc: @Eternex49 @sh00kti @slacksystem
