### ISSUE TITLE
[URGENT BUG] New bug with new version

### ISSUE THREAD

**Issue by Sydney-o9** [philc/vimium#1820]
You see that new weird window bottom left corner, that's a new bug introduced in the latest update.

Note: it appears and disappears on every page load but is only seen all the time when creating a new empty tab. 

## With Vimium

![screen shot 2015-09-13 at 2 39 17 pm](https://cloud.githubusercontent.com/assets/1480617/9835260/5b048834-5a25-11e5-8888-28bdde17d3c1.png)

## When Vimium is disabled

![screen shot 2015-09-13 at 2 40 44 pm](https://cloud.githubusercontent.com/assets/1480617/9835262/811f82b2-5a25-11e5-8608-cc55e63df9bb.png)

**Comment by mrmr1993** [comment]
This looks like a dup of #1817.
