### ISSUE TITLE
[Improve] When I press `/`, show the current word somewhere.

### ISSUE THREAD

**Issue by lichenhao** [philc/vimium#1823]
RT, When I press the `/` and going to search some word, There's no place show the word I have put in.

**Comment by mrmr1993** [comment]
Do you mean that the HUD(in [this image](https://cloud.githubusercontent.com/assets/379823/5165879/9a33951c-73ea-11e4-965e-c569cdee2618.png) showing `/ (6516 Matches)` from #1266) isn't displayed when you press `/` to search?

Or is there another time we should be showing that information? (I can easily see the argument for showing it for `n` and `N`, if that's what you mean.)

**Comment by lichenhao** [comment]
Yeah, I saw a mini box in the bottom. It's too small and can't attract attention.

**Comment by smblott-github** [comment]
There doesn't seem to be a case for revisiting the styling of the HUD at this point.
