### ISSUE TITLE
Disable by default, enable by hotkey

### ISSUE THREAD

**Issue by dwelle** [philc/vimium#1824]
Currently, you can temporarily disable vimium using `i` hotkey, but what if I want to do the opposite → 90% of the time use the website without vimium, and sometimes enable it temporarily.

It would be nice if there was some master key for toggling on/off state (e.g. via `F7`). So I'd have the domain in exclusions list (keys left blank), and sometimes hit a master key to enable it for a session.

**Comment by smblott-github** [comment]
Closing.
Lack of interest,

**Comment by flancian** [comment]
FWIW, I'd love to have this. I'm about to remove Vimium for the second time in recent history because I find that it disrupts my workflow more often than it aids it; I know, of course, that this is likely not a problem for long standing users, but as someone that wants to use Vimium in specific scenarios to begin with (while ramping up?) such a feature would be definitely useful.

**Comment by gdh1995** [comment]
@flancian For who want such a feature, here's another choice: I have a customized version of Vimium, named Vimium C, to provide some extra useful features.

Vimium C supports global shortcuts, exclusions passKeys only for hooking and command URLs for switching passKeys:
* Vimium C handles URLs like `vimium://status <enable|disable|toggle>` specially
  * `enable` will make Vimium C enabled (just like no exclusion rules matched), on all iframes of a current tab
  * `disable` does conversed actions (just like `Pass Keys` is empty)
  * `toggle` can switch a current status to another
* Its `passKeys` can be used to specify an allow list of usable key mappings
  * if `passKeys` starts with `^ `, then following keys means an allow list
  * if not, the `passKeys` means a list of "composed keys", separated by space characters
* It provides some global shortcuts (those on `chrome://extensions/shortcuts`), and their function can be configured arbitrarily
  * `shortcut userCustomized1 command="openUrl"` (in custom key mappings) means to open a new tab when the shortcut `User Customized 1` gets triggered.

So I think the 3 above can satisfy most needs.

**For example**: `map <f7> openUrl url="vimium://status\u0020toggle\u0020^\u0020<f7>"` in key mappings

**Explain**:
* `openUrl` means to execute specified URL / URLs, and following `url=` is a JSON-encoded URL
* the url above is `vimium://status toggle ^ <f7>` (each `\u0020` means a space character)
* `vimium://status` means to switch / setup working status of Vimium C for a current tab
* `toggle` means to switch among `enabled`, `disabled` and `reset`
* `^ <f7>` means that, when a next status is `disabled`, Vimium C will still hook `<f7>` and trigger commands.
  * you may also write multiple keys here, like `^ <f7> <f8> <c-i>`

**Expected effect**: you can press <kbd>\<f7></kbd> and then Vimium C will turn off on a current tab; while a second <kbd>\<f7></kbd> will re-enable Vimium C.

There're also `vimium://status enable` and `vimium://status disable` to force a new working status, regardless of the current status.
