### ISSUE TITLE
make global mark easier

### ISSUE THREAD

**Issue by duqcyxwd** [philc/vimium#1825]
I do really enjoy the global mark but I think the Capital for global is little bit redundant. I also understand it is better separate global marks and local marks. 

Can we have on option that we can have 'qwertyuiop' as global mark and rest of the keys as local mark?

**Comment by smblott-github** [comment]
Interesting.

My own experience is: I *never* use local marks, and having to use shift for global marks slows things down.

It's difficult to see how you could do this without a new option of some kind, as it would change the existing interface.  We could add an (advanced) option to switch upper/lower case for global/local marks.  Or an option to make all marks global.

What are your usage patterns, @mrmr1993, @philc?

**Comment by mrmr1993** [comment]
I don't use them, sorry.

**Comment by mariomaric** [comment]
@smblott-github If you could implement "option to switch upper/lower case for global/local marks. Or an option to make all marks global.", that would be really appreciated, a lot!

BTW, Vimium totally rocks, thank you all!

**Comment by xerebz** [comment]
If anyone is still looking for this feature, you can use lowercase marks as global if you remove the `event.shiftKey and ` condition from [here](https://github.com/philc/vimium/blob/master/content_scripts%2Fmarks.coffee#L30) like I've done in my branch [here](https://github.com/xerebz/vimium/blob/master/content_scripts/marks.coffee#L30). You can then build and install your own Vimium using their instructions [here](https://github.com/philc/vimium/blob/master/CONTRIBUTING.md#installing-from-source).

**Comment by isovector** [comment]
Just because this issue is the top result for this search, the correct way to enable this feature is:

```viml
map ` Marks.activateGotoMode swap
map m Marks.activateCreateMode swap
```
