### ISSUE TITLE
Try to guess the relevant input field for quick navigation

### ISSUE THREAD

**Issue by moviuro** [philc/vimium#1830]
`f f` should focus the input field that most closely resembles "search"

Rationale: you usually want to enter a search on a wiki, not always try to guess/read the keycode to reach the search field. E.g. today on:
 * en.wikipedia.org `f cd`
 * fr.wikipedia.org `f md`
 * wiki.archlinux.org `f ph`
 * linguee.com `f c`
I think that by now you get the idea.

**Comment by smblott-github** [comment]
Perhaps `gi` is what you're looking for, @moviuro?

**Comment by moviuro** [comment]
Oh, I feel stupid now.
Thanks @smblott-github
