### ISSUE TITLE
Tests on Travis are failing...

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1832]
![snapshot](https://cloud.githubusercontent.com/assets/2641335/9953073/3678d1ba-5dd5-11e5-98a7-b10f116fa01a.png)

**Comment by mrmr1993** [comment]
I pushed #1827 to fix this a couple of days ago.

The actual issue is that the new version of path uses node features (`process`) that PhantomJS didn't provide, so there's not much we can do except downgrade.

**Comment by smblott-github** [comment]
Ah.  Thanks, @mrmr1993.  I'd missed that.
