### ISSUE TITLE
New-tab page UI issue.

### ISSUE THREAD

**Issue by mcg** [philc/vimium#1834]
This appeared with a recent Vimium update. Linux, Chrome 46.0.2490.33 beta.

![selection_102](https://cloud.githubusercontent.com/assets/305/9992167/295791f4-603e-11e5-9fb7-1d54d0eb65d7.jpg)

**Comment by mrmr1993** [comment]
This is a dup of #1817. It's been fixed by #1833, which will be in the next version.

You can find the Chrome issue responsible [here](https://code.google.com/p/chromium/issues/detail?id=466876).

**Comment by mcg** [comment]
Sigh... I did search for this before posting. Sorry about that.
