### ISSUE TITLE
Bookmarklets run from the Vomnibar have the popup blocker applied

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#1840]
Running `javascript:window.open("https://www.google.com")` from the Vomnibar, either as a bookmarklet or entered directly in omni mode, causes the popup blocker to trigger and the `window.open` to fail.

![pop-up blocked](https://cloud.githubusercontent.com/assets/1847343/10118495/94693e20-6471-11e5-83ba-e8dbe8d6cd3b.png)

I've reported this as [Chromium issue 536527](https://code.google.com/p/chromium/issues/detail?id=536527).

@felixfoertsch I think this should cover your issue [over on #1611](https://github.com/philc/vimium/issues/1611#issuecomment-143464078). If so, you might want to star the Chromium issue to let the devs know that it's important to you.

**Comment by smblott-github** [comment]
This seems to be related (kind of) to [this issue](https://code.google.com/p/chromium/issues/detail?id=454222&can=1&q=extension%20popup%20blocker&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified).  It's to do with the relationship between extensions and the popup blocker.

Might it be worth referencing that issue over on the new Chromium issue?

**Comment by felixfoertsch** [comment]
@mrmr1993 Yes, this looks like the issue.
@smblott-github For me this was a core functionality of vimium. It basically enabled shortcuts for bookmarklets.

I'm not a developer, just a user missing a really nice feature.
