### ISSUE TITLE
Excluded keys should be excluded from `f` Open links hotkeys

### ISSUE THREAD

**Issue by dsernst** [philc/vimium#1844]
If a URL has certain keys disabled, they should not be options to select links when using the `f` "Open a link" command. The current behavior causes hitting these keys to both open the link and pass through to the original page, which then causes undesired results.

**Comment by smblott-github** [comment]
Thanks, @dsernst.  If that's happening then it's a bug.  Link-hint keys should be being "consumed" by the link-hints mode.  I'll take a look.

(Are you using "filtered" link hints [hints are numbers] or normal hints [hints are letters]?)

**Comment by dsernst** [comment]
Thanks for the quick response. Hints are letters.

The particular situation I'm running into is I have `s` excluded on `gmail.com`, but one of the links in an email was mapped to a two letter combo including `s`. When I opened the link, it also starred the thread.

**Comment by smblott-github** [comment]
OK.  Thanks.
That is a bug.
I'll take a look (but it'll be a few days).

**Comment by dsernst** [comment]
Thanks. This is Vimium version `1.53` on OS X, Chrome Stable `45`

**Comment by smblott-github** [comment]
@dsernst...

I can't reproduce this.  However, we are leaking `keyup` events in this case, and it could be that the page is listening to these.  If that's the problem, then #1849 will fix it.
