### ISSUE TITLE
text input becomes unusable

### ISSUE THREAD

**Issue by winmillwill** [philc/vimium#1847]
After focusing a text input element, all text input elements become unusable. Focus is lost on the one that had focus and it becomes impossible to focus any of them. I had to disable vimium in order to file this.

Google Chrome (Ubuntu Linux): Version 44.0.2403.125 (64-bit)
Vimium: 1.53

**Comment by smblott-github** [comment]
Can you give an example of a page where you're seeing this, @winmillwill?  Or is it *all* inputs.

**Comment by winmillwill** [comment]
Welp, my computer crashed for an unknown reason and on reboot I can no longer reproduce the problem.

I noticed in particular that this was happening on inputs that had js behaviors attached to them, but of course in hindsight, I just didn't encounter any non-js inputs 'in the wild' on that day because this is the state of modern web applications.

I had this issue with google search, with the github issue comment field I'm typing in right now, and with the comment input in Jira.

**Comment by smblott-github** [comment]
OK.
Looks like close for now.
