### ISSUE TITLE
Mapping using numeric keycodes?

### ISSUE THREAD

**Issue by infokiller** [philc/vimium#1851]
Is it possible to map using numeric key codes so that the keyboard shortcuts will work in multiple language layouts?

**Comment by nkgm** [comment]
+1
Was wondering the exact same thing, or whether there's a way to contribute individual languages.

**Comment by smblott-github** [comment]
> or whether there's a way to contribute individual languages

Some people have contributed mappings for various keyboards, if that's what you mean, @nkgm.  Here: https://github.com/philc/vimium/wiki/Key-Mappings.
