### ISSUE TITLE
Bind keys to other literal keys

### ISSUE THREAD

**Issue by infokiller** [philc/vimium#1852]
Some websites (like Google Drive) has built in keyboard shortcuts that can't be customized. Vimium could be used to customize these bindings if:
1. It would be possible to define URL-specific key bindings
2. There would be an option to map an arbitrary key sequence to another arbitrary key sequence. I'm thinking of something like `map x "y"` with the result that when I press x the page receives a key press of y.

It it currently possible to do what I want? and if not and if not, will it be possible to implement this feature?

Thanks!

**Comment by smblott-github** [comment]
So, if I get the idea, @infokiller, it's like this.

Google Drive (GD) defines its own mapping for `gp` (go to parent directory).  You're proposing

    map https://drive.google.com/drive/u/0/* p "gp"

So now `p` goes to the parent directory on GD.  That's it, right?  And we would implement this by injecting "fake" keyboard events.

(Almost) everything is possible. But this seems a bit complicated for fairly marginal benefit -- the majority of page shortcuts are just `j` and `k` (and a couple of other single keys).  And Vimium accommodates those via exclusion rules.

**Comment by infokiller** [comment]
Yes, you got the idea perfectly right. I personally need this because I defined custom keyboard shortcuts in Vimium and all the other software I'm using (vim, i3, tmux, etc). Specifically, I'm using ijkl for navigation (instead of hjkl). This created an inconsistency with these webapps that I thought I might be able to fix using Vimium. 
Thanks for your response!
