### ISSUE TITLE
why can't vimium be used under tabs like "chrome://" or "https://chrome.xxxx"

### ISSUE THREAD

**Issue by xkfz007** [philc/vimium#1854]
I am using vimium, and I like to map some keys to switch between tabs. However, when I enter the "chrome://" or "https://chrome.xxx" tabs, vimium is disabled. It is very annoying. How can I solve this problem?

**Comment by smblott-github** [comment]
Thanks, @xkfz007.

Chrome simply *does not run* extensions on those pages.  So there's nothing we can do about it.

**Comment by philc** [comment]
I've updated the [FAQ](https://github.com/philc/vimium/wiki/FAQ) to mention this.
