### ISSUE TITLE
Gmail keyboard shortcuts using "*" don't work

### ISSUE THREAD

**Issue by infokiller** [philc/vimium#1855]
When Vimium is active in Gmail, I can't use the Gmail `*` keyboard shortcuts (for example `*a` to select all the threads in the inbox). This doesn't work when Vimium is even enabled for a single keyboard shortcut, but does work when Vimium is completely disabled.
Using Vimium 1.53 on Chrome 45.0.2454.101 (Official Build) on Linux.

**Comment by smblott-github** [comment]
Thanks, @infokiller.

Could you post a screenshot of what appears in the Vimium popup (click on the Vimium icon) when you're on GMail?

**Comment by mrmr1993** [comment]
@smblott-github `DomUtils.getKeyChar` gives shift-modified numbers as the numbers themselves, and so we suppress the `keydown` event based on the key being a number. So this is another manifestation of #1757.

@infokiller you should be able to add `2` as a passkey for Gmail (presuming `"` is `shift+2`), and then the shortcuts should work as normal.

**Comment by infokiller** [comment]
Sorry, didn't see the markdown preview- I actually meant a star (`*`). Updated the first comment.

**Comment by infokiller** [comment]
Thanks @mrmr1993 , indeed it works when I added `8` as a passkey.
