### ISSUE TITLE
Suggestion: Temporarily enable/disable vimium

### ISSUE THREAD

**Issue by gdavtor** [philc/vimium#1856]
I've noticed that, while I am on a blacklisted domain, I would like to temporarily use a vimium key. For example, I have the domain "youtube.com/watch/?v=" blocked because I want to use the youtube video player shortcuts (f, j,k,l mostly). However, sometimes I would also like to use f,j,k,l vimium commands on a youtube video page, but can't because they are taken by the youtube player. I think it would be cool to have a prefix (say, ctrl) that would temporarily enable vimium keys (i.e. crl+f, crtl+j, ctrl+k, ctrl+l) on a blacklist.

**Comment by mrmr1993** [comment]
FYI: This sounds like a simpler version of #1188.

**Comment by smblott-github** [comment]
@gdavtor.  Do you know how exclusion keys work?  You don't have to wholly disable Vimium on GMail, say, you can just disable certain keys; for example, just disable Vimium's `j` and `k`, and use GMail's bindings for those, but keep all of Vimium's other bindings.

Another trick is to have *several* bindings for important keys.  I bind `J` and `K` to scrolling too.  So, GMail's `j` and `k` is available, and Vimium scrolling is available too.  (For me, switching tabs is bound to something else.)

More info here: https://github.com/philc/vimium/wiki/Disabling-Vimium

**Comment by gdavtor** [comment]
@smblott-github Thank you, your second suggestion helps.
