### ISSUE TITLE
Exclude multi-characters keys

### ISSUE THREAD

**Issue by BohrShaw** [philc/vimium#1858]
Currently, if the key `g` is excluded on https://github.com, pressing `gu` equals pressing `u`.

So it would be nice to be able to exclude multi-characters keys like `gi`, `gc`, `gw`, etc. in the above case.

**Comment by smblott-github** [comment]
Thanks, @BohrShaw.  So, your idea is to exclude sequences; e.g. `gu`, therefore:

- `g` is always excluded
- `u` is excluded *only if it follows* `g`

There are certainly some use cases for this.  I find I just exclude `u` to in these cases (e.g. `gp` on Google drive).  I'm not sure how we'd fit the idea into the UI without creating quite a bit of extra complexity.

**Comment by BohrShaw** [comment]
@smblott-github We are on a different idea.

I mean to treat a key like `gi` as a unit. And if it's the only key excluded, other keys prefixed with `g` like `gg`, `gu`, `gf` are _not_ excluded.

As for the UI, I think a comment like "Separate keys with spaces" above the Input Box is enough.

**Comment by smblott-github** [comment]
> As for the UI, I think a comment like "Separate keys with spaces" above the Input Box is enough.

Except, users may already have spaces in their excluded keys.

(In a previous release, we were stripping spaces when the user hit "save", and somebody raised that as an issue.)

**Comment by BohrShaw** [comment]
`|` may be a better key separator as it's less frequently binded by a site.
