### ISSUE TITLE
dynamically enable/disable vimium

### ISSUE THREAD

**Issue by aljosa** [philc/vimium#186]
i often find myself in situation where i just need to "pause" vimium but not permanently disable it.
first it would be nice to have a toolbar icon like other extensions to indicate if vimium is enabled/disabled and a shortcut that enables/disables vimium on current page without reloading page.
vimium would still be loaded on current page but would simply ignore all events until enabled again.

**Comment by rrsahutwo** [comment]
Time management is specialty of movers and packers in Bangalore . You just have to tell us, when you need all the perform finished. We finish all the perform sometimes, without any harm. We provide all kind of moving solutions like, workplace moving, house moving, automobile transportation, pet moving, domestic and international relocations, etc.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
We comprehend your love towards your pets. If you want to shift your pets, then we are perfect remedy. We manage them with highest appropriate care, and shift your pet where you want. We know how much sensitive pets are. So our best group going to deal with your pets and shift them. Transport medium is chooses according to the pet.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
We shift all kinds of birds and animals like parrots, cats, dogs, rats, cows, peacock, etc. we cope with their health and take them as our responsibility. You can completely believe in us for our pet moving solutions.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
We comprehend how much effort you do to earn. Your hardly earned cash, value for us too. Every automobile belonging to you is very valuable. Several outstanding memories belong to it. We transportation automobiles from one position to another without putting minute scratch over them. Special car providers help us to transportation cars. These providers are effective to deliver automobile on required position.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
