### ISSUE TITLE
Cannot set custom style to vimiumHUD

### ISSUE THREAD

**Issue by tgckpg** [philc/vimium#1860]
It works before. But after the update I can't set it. How do I fix this ?

**Comment by gdh1995** [comment]
Vimium's "CSS for link hints" and other extensions' injected CSS use the same Chrome's API, and this API injects CSS to website' pages. But Vimium has changed to use `shadowDOM`s which refuse outside style code, as well as such injected CSS code.

Now Vimium's HUD is wrapped as: `#shadowDOM > iframe > HUD node`. so as far as "CSS for link hints" is not injected to the HUD iframe, you will still be not able to customize your vimiumHUD. This seems to be a feature request but not bug report.

Keyword for more information: `shadowDOM CSS` and `chrome.tabs.insertCSS`.

**Comment by smblott-github** [comment]
So we forgot to inject the user's custom css into our UI components, yes?

**Comment by tgckpg** [comment]
I still think this is a bug since it broke something existing in next version. But who am I to complain?
Thanks for the information.

My current solution is directly modifying the extension and load it from unpacked extension in developer mode.

**Comment by gdh1995** [comment]
@smblott-github  Yes. But in my option, CSS code inner or outer the shadowDOM are for different uses, so it'll be useful to split `userDefinedLinkHintCss` into `userDefinedInnerCss` and `userDefinedOuterCss` - for example, I want:
* Inside Vimium's iframes, customize HUD / Vomnibar's UI
* Injected to the normal pages is something like `img,input[type=image] {min-width: 3px; min-height: 3px;}` to force `LinkHInt` recognize `<img>`s as clickable links even when I've disabled all images.

**Comment by smblott-github** [comment]
> So we forgot to inject the user's custom css into our UI components, yes?

@mrmr1993... Is this correct?

**Comment by mrmr1993** [comment]
> we forgot to inject the user's custom css into our UI components, yes?

Not forgot, no. Since we're talking about the "CSS for Link Hints" option, I didn't think that it was necessary to inject it into non-link hint UI. I'll also note that it would need to be injected into both the frame and the shadow DOM for each.

If we rename the setting to "style override" or similar (and change the default value to give references to the HUD and Vomnibar as well), then it would seem much more reasonable to inject it in those places.

**Comment by smblott-github** [comment]
> If we rename the setting to "style override" or similar (and change the default value to give references to the HUD and Vomnibar as well), then it would seem much more reasonable to inject it in those places.

If we're keeping this option, then that seems to be the way to go.  Those who argue for retaining it seem to like the ability to diddle with any old CSS, not just link hints.

**Comment by rrsahuone** [comment]
Packers movers Bangalore take guarantee that your valuables and products are 100 % safe with well-known companies and it will be shifted to desire position without causing any harm or reduction. Our detailed Packers movers always give superior stage of solutions in comparison to other similar vendors in Bangalore or close by places.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by rrsahuone** [comment]
Make moving and product packaging much easier than it was regarded in previous. You will feel less burdened and can focus on other effective projects easily. Reputed Companies always create sure that experts will shift your valuables without any damage or harm. Professionals are providing unique attention to fragile products that are extremely susceptible to harm.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers in Delhi">Packers and Movers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by rrsahuone** [comment]
Either you are interested in moving house, best packers and movers Companies in Bangalore is outstanding remedy to manage your needs. Everything will settle down depending on your time and effort and effort schedules and availability. Packing and movers are available twenty four hours a day and our expert group assists you in best possible way.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers in Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a>

**Comment by rrsahuone** [comment]
This discussion has already been clear that you have been come to the right position. Fill simple enquiry form available at our site and get estimates from certified suppliers right now.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by leoj3n** [comment]
:+1: please
