### ISSUE TITLE
Feature request: Dedicated horizontal scroll step size

### ISSUE THREAD

**Issue by degill** [philc/vimium#1862]
Since the heights of almost all webpages are significantly larger then their respective widths it would be useful to define a seperate Scroll Step Size for horizontal scrolling.

I have a tiling window manager and usually have two windows side by side, one of them usually being a browser window. My laptop screen is exactly narrow enough so that the browser window cant display the usually centered webpage-content so I try to center the page by using the h and l keys, but I fail because these keys over step the content because I have set the scroll size to a large value,

What do you think? (Or maybe is this already available but I have overseen it?)

**Comment by smblott-github** [comment]
Thanks, @degill. That seems reasonable.  I wonder if there's a way to achieve the same thing without adding a new option.  For example, we could ignore the scroll-step size for horizontal scrolling, hard-wiring it to a value that seems to work well.

**Comment by gdh1995** [comment]
I customize my Vimium project on this way:
* `scrollStepSize` is 100 set on the options page
* usually, horizontal scroll step size is `0.6` * `scrollStepSize` (hard-coded)
* this above `0.6` works except `element.clientWidth > element.clientHeight * 2`, which is hard-coded in `Scroller.scrollBy`
* `width > height * 2` means often several code lines on github, or horizontal images.

Of course, `0.6` and `2` may be changed to a more convenient number.

**Comment by smblott-github** [comment]
Closing.
Lack of interest.
