### ISSUE TITLE
Feature request: Close tabs when searching through open tabs

### ISSUE THREAD

**Issue by gqqnbig** [philc/vimium#1863]
I press T and vimium shows a list of open tabs. I can type to filter the tabs.

Is it possible to let me close unwanted tabs from the list?

For instance, add a close button "X" to the right of each item, or do it by shortcut which is more in vim way.
![2015_10_22_15_32_11_new_issue_philc_vimium](https://cloud.githubusercontent.com/assets/614159/10680200/62f9beb2-78d2-11e5-8d9d-239317d5b242.png)

**Comment by mrmr1993** [comment]
This seems like a dup of #1735. I like the idea of an 'X' button, and that should be easy to implement, though.

**Comment by gqqnbig** [comment]
Oh.. I'm sorry for duplication. I didn't search existing issues.
