### ISSUE TITLE
Scrolling doesn't work in http://google.github.io/dagger/

### ISSUE THREAD

**Issue by txomon** [philc/vimium#1868]
Hello,

I don't know why but scrolling (using j/k) doesn't work in http://google.github.io/dagger/

**Comment by zoner14** [comment]
it looks like scrolling fails when the focus of your cursor is on the header (default). If you click on the body of the website, scrolling starts working again.

**Comment by txomon** [comment]
Not for me... I select text to be sure that I am in the proper place, but it doesn't move...

**Comment by txomon** [comment]
Scrolling just works if I click outside of the text column or in the scroll bar... the thing is that clicking on the text should be trigger enough

**Comment by gdh1995** [comment]
It seems that only way to get one node's correct "parent for rendering" is to dispatch a `UIEvent` to last activated element and get `event.path` as its ancestors.
