### ISSUE TITLE
GMail # shortcut not working 

### ISSUE THREAD

**Issue by mjauvin** [philc/vimium#1870]
When completely disabling Vivium for a website (like GMail), the "#" shortcut does not work.

The only way to make GMail's "#" shortcut work was to disable all known shortcut manually in a rule for GMail URL.

Also, if using Vivium "Custom key mappings", using "unmap all" also does not restore "#" shortcut in GMail.

Note: "#" default GMail shortcut deletes the current opened email (or selected email in mailbox view)

**Comment by mrmr1993** [comment]
This has the same root cause as #1855. You can set `3` as a passkey (assuming you're on `en_US`) to pass `#` to the page.

**Comment by mjauvin** [comment]
You misread my bug report. I *can* disable "#" by including it in a rule.
The problem is that it should be disabled when COMPLETELY disabling vivium
for a URL, or when using "unmap all" in the custom key mapping option.

On Thu, Oct 29, 2015 at 10:05 AM, Matthew Ryan <notifications@github.com>
wrote:

> This has the same root cause as #1855
> <https://github.com/philc/vimium/issues/1855>. You can set 3 as a passkey
> (assuming you're on en_US) to pass # to the page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/philc/vimium/issues/1870#issuecomment-152191046>.
>



-- 
Marc

**Comment by mrmr1993** [comment]
> You misread my bug report.

Sorry, my mistake. Could you talk me through the issue?

* Is `#` blocked if you have no rules for the page?
* Do you have a key mapping that starts with `#`?
* Does setting `#` as a passkey stop it from being blocked?
* Does setting a rule to disable Vimium on GMail stop `#` from being blocked?
* Does setting `3` (or whatever key you press to give `#`) as a passkey on GMail stop `#` from being blocked?

FYI: I would expect yes, no, no, yes, yes if #1855 is at play here.

**Comment by mjauvin** [comment]
On Thu, Oct 29, 2015 at 10:27 AM, Matthew Ryan <notifications@github.com>
wrote:

1 - Is # blocked if you have no rules for the page?

Yes

2 - Do you have a key mapping that starts with #?

No

3 - Does setting # as a passkey stop it from being blocked?

Yes

4 - Does setting a rule to disable Vimium on GMail stop # from being
blocked?

Yes (Somehow, I could not make this work earlier, and now it works.)

5 - Does setting 3 (or whatever key you press to give #) as a passkey on
GMail stop # from being blocked?

No


>
> FYI: I would expect yes, no, no, yes, yes if #1855
> <https://github.com/philc/vimium/issues/1855> is at play here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/philc/vimium/issues/1870#issuecomment-152196756>.
>



-- 
Marc

**Comment by mrmr1993** [comment]
I can't work out what's going on here from the code. If you can tell me what keyboard layout you're using, I'll try and run some tests.

What I can infer (which makes no sense):
* 3 - yes implies that we're detecting `#` correctly at the event GMail is capturing on
* 1 - yes implies that normal mode is blocking `#`
* so normal mode has `"#" in currentCompletionKeys` or `isValidFirstKeys "#" `
  - presumably `#` is a valid first key, if it is always blocked
* so `#` must be mapped (but not because 2 - no).

**Comment by mjauvin** [comment]
Hello Matthew, I'm using English(US) keyboard layout under Gnome.

Thanks.

On Thu, Oct 29, 2015 at 12:08 PM, Matthew Ryan <notifications@github.com>
wrote:

> I can't work out what's going on here from the code. If you can tell me
> what keyboard layout you're using, I'll try and run some tests.
>
> What I can infer (which makes no sense):
>
>    - 3 - yes implies that we're detecting # correctly at the event GMail
>    is capturing on
>    - 1 - yes implies that normal mode is blocking #
>    - so normal mode has "#" in currentCompletionKeys or isValidFirstKeys
>    "#"
>       - presumably # is a valid first key, if it is always blocked
>    - so # must be mapped (but not because 2 - no).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/philc/vimium/issues/1870#issuecomment-152228351>.
>



-- 
Marc

**Comment by mrmr1993** [comment]
Under English(US) in XMonad with Gnome, I that `#` as a passkey **does not** work, but `3` as a passkey does, as expected.

Can you post the output of typing `#` in the input box on [this page](http://www.asquare.net/javascript/tests/KeyCode.html)?

**Comment by smblott-github** [comment]
Closing.
No response from OP.
