### ISSUE TITLE
Add a binding to quit the browser

### ISSUE THREAD

**Issue by Reilithion** [philc/vimium#1872]
I'd like to be able to bind a key to quit the browser completely. Equivalent to Alt-F4, Ctrl-Shift-Q, or closing the window.

**Comment by smblott-github** [comment]
Thanks, @Reilithion.  I don't think there's an Chrome API for that, is there?

**Comment by Aleroniponi** [comment]
https://developer.chrome.com/extensions/windows#method-remove

**Comment by Reilithion** [comment]
Was this feature added?

**Comment by smblott-github** [comment]
No, @Reilithion -- sorry.

I did a long troll of the outstanding issues today, closing issues that seemed unpromising... and this was one.

**Comment by Reilithion** [comment]
Where in the Vimium code would I need to modify if I wanted to implement this myself using @Aleroniponi 's suggestion?

**Comment by smblott-github** [comment]
If there are multiple windows, then it's really a window manager issue.

If there's just one window, then `99x` probably does the trick already.

**Comment by Reilithion** [comment]
Ah, ok. Thanks!

**Comment by Reilithion** [comment]
I tested `99x` and dislike it for two reasons:

1. Since it closes tabs instead of the whole window, when I reopen my browser it doesn't restore my last session. :-(
2. It asks for confirmation (at least by default)

**Comment by smblott-github** [comment]
Sorry, @Reilithion.

This isn't really above threshold; window managers usually provide bindings for these types of things.

**Comment by qiuxiaomu** [comment]
to be honest we probably we don't need one for that until the 'f' key occupied, constantly. alt+x, f worked well for me until I started to enjoy vimium. Probably consider a way to temporarily turn off the master 'f' (give control of f back to the keyboard)?
