### ISSUE TITLE
`moveTabRight` should move the last tab to be the first

### ISSUE THREAD

**Issue by BohrShaw** [philc/vimium#1875]
Similarly, `moveTabLeft` moves the first tab to be the last.

These adjustments make the two commands consistent with `nextTab` and `previousTab`.

**Comment by smblott-github** [comment]
Thanks @BohrShaw.
Not sure about this idea, though.

I use `99<<` to move a tab all of the way to the left -- which would break with your idea.

Perhaps it's not necessary that `moveTabLeft` and `previousTab` are consistent.  Moving tabs seems like a more dramatic intervention to me.  Also, these behaviours -- correct or incorrect -- could create quite some confusion if changed.

**Comment by BohrShaw** [comment]
> I use 99<< to move a tab all of the way to the left -- which would break with your idea.

We could avoid the loop if the count is not 1. Or we just consider all tabs to be circular and avoid recursion, if it could be efficiently implemented.

I actually have the itch to move a tab in a circular way _quiet frequently_.

**Comment by gdh1995** [comment]
> Similarly, `moveTabLeft` moves the first tab to be the last.
> We could avoid the loop if the count is not 1

Well, it's unpleasant for me. I seldom use `count`, but I press '<' continuously to move the current tab to the most left (I map `'<'` as `moveTabLeft`). If by your idea, I'll see a tab moving and moving without a stop.

**Comment by BohrShaw** [comment]
> I press '<' continuously to move the current tab to the most left.

I just tried this. It seems far less efficient than using a `count`.

**Comment by gdh1995** [comment]
Yes, it's not fast. I just like its animation and the state that I needn't consider what count I need。

**Comment by BohrShaw** [comment]
> I needn't consider what count I need.

`9<`(or `99<`) also frees your mind to come up with a proper `count` in most cases.

As for the animation, for example, `3<` is better than `<<<` IMO.

**Comment by gdh1995** [comment]
Well, as you like.

In fact, I prefer to keep pressing some keys, comparing to move my fingers.

**Comment by BohrShaw** [comment]
A side note:
VimFx in Firefox loops when moving a tab, but only when no count is specified(or the count is 1).
