### ISSUE TITLE
Documentation inconsistency about "open link"

### ISSUE THREAD

**Issue by james64** [philc/vimium#1876]
Hey,

Reality
f - open link in new tab
F - open link in current tab

Documentation (by ? key)
f - open link in current tab
F - open link in new tab

This should be fixed either in documentation or in a code.

I love this plugin!!!

**Comment by mrmr1993** [comment]
This sounds suspiciously like #761; are you holding `<shift>` while you type the hint chatacters?

Doing so toggles between those two modes, which can make them seem inverted, since the intention was that the characters would be entered in lower case by default.

**Comment by james64** [comment]
I am not sure what "while you type the hint characters" means but this is what I tried right now step by step:

1) f + <link code>  =>  link opened in new tab
2) ?  =>  hint table opened
3) shift pressed  =>  no visible effect
4) <esc>  =>  hint table closed
5) f + <link code> => link opened in new tab

Please let me know if I misunderstood or if there is anything else I can try for you to see if it is an issue or not.

**Comment by mrmr1993** [comment]
> I am not sure what "while you type the hint characters" means

I meant while you are in link hints mode typing the characters that appear in a hint to select it.

I don't understand what that list means, sorry. Although, this line:

> 3) shift pressed => no visible effect

seems like an issue; the mode should change, and the HUD's text should be updated accordingly.

**Comment by james64** [comment]
The list is a description of what I do with the plugin and the effects what I see. More verbose version:
1) I press f and choose a link. Then the link is opened in new tab
2) Then I press ? which opens hint table
3) Then I press shift which has no visible effect
4) Then I close hint table by escape key
5) Then I press f and choose a link which again opens the link in new tab as in number 1

Now I have noticed that some words were removed from my first list so it makes less sence. Sorry for that. I hope this verbose version is more readable. I would like to take this to a point were we confirm a bug or not. So again, if I can help...

**Comment by james64** [comment]
alôskdjfladsj

**Comment by james64** [comment]
sorry, I closed the issue by accident. Reopened now...

**Comment by mrmr1993** [comment]
> 1) I press f and choose a link.

This is the stage where `<shift>` is relevant. Breaking it down:

* Press `f` to show link hints
* Type the characters shown in the hint to select a link
  - if `<shift>` (or `<ctrl>`) are pressed *at any point* during this stage, the effective mode is change, signalled by a different message in the HUD
* The link gets clicked

Are you pressing `<shift>` at any point while activating a link hint?

**Comment by james64** [comment]
ok we have it :)
The marks are displayed as capitals so I typed them as capitals therefore pressing shift. It works now. Thank you for your activity. Now I am closing this...
