### ISSUE TITLE
Bundle/concatenate files for less footprint in devtools

### ISSUE THREAD

**Issue by KnutHelland** [philc/vimium#1877]
Hello!

I use Vimium a lot and have become completely addicted! So thank you very much for the very useful project.

I happen to be a web developer as well, and I don't like that vimium has so big footprint in the devtools `network`-tab due to it's content scripts. See screenshot:

![screen shot 2015-11-05 at 12 08 56](https://cloud.githubusercontent.com/assets/183461/10966785/3b787ede-83b6-11e5-9dbc-9fadb8abfd8b.png)

One suggestion would be to concatenate all of these files with webpack or whatever so that only a single `vimium.js` is loaded with all js, css and icons bundled in.

**Comment by mrmr1993** [comment]
This seems to be covered by #1838
