### ISSUE TITLE
Vimium and chrome's definitions of scrolling don't match

### ISSUE THREAD

**Issue by antoine-levitt** [philc/vimium#1878]
Vimium exposes two types of scrolling: page up/down and full page up/down. Neither matches chrome's "almost one page but not quite", which is bound by default to page up/down and space. To be more precise, Vimium's page down scrolls less than chrome's page down which scrolls less than vimium's full page down. I find chrome's default scrolling much more pleasant (especially on websites with annoying borders on the bottom of the page, where scrolling a full page down breaks continuity). Vimium's full page down should match chrome's, or at least vimium should expose chrome's way of scrolling for the user to customize.

**Comment by smblott-github** [comment]
For *full page up.down*, that makes a lot of sense.
