### ISSUE TITLE
[Help] <esc> in excluded keys

### ISSUE THREAD

**Issue by babygau** [philc/vimium#1879]
Hi guys,

How to exclude `<esc>` in excluded keys when I want to disable `<esc>` key at Rust playground site because Vimium `<esc>` conflict with Rust editor vim binding.

**Comment by mrmr1993** [comment]
I'm afraid it's not possible with the current version of Vimium. I created #1372 to address this, but it didn't get merged and now needs a rebase.

**Comment by babygau** [comment]
Tks @mrmr1993  for your reply. Hope this will be implemented in future :+1:

**Comment by roachsinai** [comment]
Hi, there, seems exclude esc still not work.

**Comment by SinisterSup** [comment]
Even I have the same Issue Please help out! How do exclude <esc> key in any given URL
