### ISSUE TITLE
CSS leaking into vomnibar (on BBC News)

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1881]
I'm seeing CSS from the BBC News site ([here, in particular](http://www.bbc.com/news/world-europe-34753464)) leaking into the vomnibar.  (The stylling is chunkier that it should be.)

![snapshot](https://cloud.githubusercontent.com/assets/2641335/11014761/cd954202-853c-11e5-9f4c-786326e747d9.png)

**Comment by gdh1995** [comment]
Any two comparable images?

I don't see any difference today, with Vimium of latest master branch on Chrome 47 beta x64.

**Comment by mrmr1993** [comment]
@smblott-github I'm fairly sure this can't happen, since styles can't penetrate a cross-origin `<iframe>` like the Vomnibar.

Did you have a second image so we can see the issue?

**Comment by smblott-github** [comment]
![snapshot](https://cloud.githubusercontent.com/assets/2641335/11318449/24926cfc-904a-11e5-9af1-69b9327266a4.png)

Here's a comparison.

I notice this often on BBC News.  Don't recall seeing it elsewhere.

**Comment by mrmr1993** [comment]
Are you slightly zoomed in on the affected page?

**Comment by smblott-github** [comment]
> Are you slightly zoomed in on the affected page?

Doh!

Sorry for the noise.
