### ISSUE TITLE
Turn off Ctrl-Shift-O map

### ISSUE THREAD

**Issue by sid-kap** [philc/vimium#1885]
Hi,

Usually Ctrl-Shift-O in chrome opens up the bookmark manager, but it looks like vimium overrides this to open up the vimium settings popover.
Is there a way to disable this?

**Comment by smblott-github** [comment]
I don't think Vimium does do that.  Perhaps take a look at your "Keyboard shortcuts" settings (on the extensions page (chrome://extensions/) at the bottom, on the right?

**Comment by sid-kap** [comment]
That fixed it, thanks!
