### ISSUE TITLE
Scrolling doesn't work at chrome 46.0.2490.80

### ISSUE THREAD

**Issue by 0neSe7en** [philc/vimium#1887]
Google Chrome	46.0.2490.80 
	c6bfd1395b9449cb59180d45944a8cb56799bd9c-refs/branch-heads/2490@{#549}
	Mac OS X 
Blink	537.36 (@c6bfd1395b9449cb59180d45944a8cb56799bd9c)
JavaScript	V8 4.6.85.28

Vimium 1.53

`h,j,k,i,gg,G,d` doesn't work. `x, X, f` is working.

**Comment by smblott-github** [comment]
Thanks, @OneSe7en.  You mean doesn't work *at all*, yes?  And on all sites?

Is anything showing up in the console?

**Comment by 0neSe7en** [comment]
I disable all extensions except Vimium, and it doesn't work al all on all sites..

no output in the console.

**Comment by mrmr1993** [comment]
Do you have any flags enabled in chrome://flags? Some of those can stop scrolling from working.

**Comment by 0neSe7en** [comment]
Thanks @mrmr1993 , you are right. Scrolling is working after I reset all flags.

**Comment by 0neSe7en** [comment]
scrolling is working after I disable `enable-experimental-web-platform-features` flag.

**Comment by 0neSe7en** [comment]
However, I can't use `CSS Grid Layout` after disable this flag...
