### ISSUE TITLE
CSS spilling over to help dialog from sceneaccess.org

### ISSUE THREAD

**Issue by spillevink** [philc/vimium#1890]
Help box is taller than usual and text looks fuzzy.

Comparison screenshot (sceneaccess.org to the right): https://jakob.su/screenshots/2015-11-15_54Xap.png

Text-shadow on the options link is shown in the inspection window.

CSS: https://sceneaccess.eu/d_cuprite.css

**Comment by spillevink** [comment]
Maybe something like this could be useful for this issue and #1881: https://github.com/anderspitman/chrome-extension-css-isolation-example

**Comment by mrmr1993** [comment]
> Maybe something like this could be useful

The solution there boils down to using an `<iframe>`, which we already do for the Vomnibar and HUD using [`UIComponent`](https://github.com/philc/vimium/blob/master/content_scripts/ui_component.coffee). All that needs to be done is to turn the help dialog into a standalone page, and then `UIComponent` can be used for the help dialog too (although it will exacerbate #1877/#1838).

**Comment by gdh1995** [comment]
Do you mean links at the bottom which are too "thick"? I think it's because of special fonts. I find that if a page use 3D transform on some nodes, then text with fonts like Consolas will look thick and obscure.

**Comment by spillevink** [comment]
Yes, seems to be because of text shadow though.

**Comment by smblott-github** [comment]
Closing this, because it's already on our radar elsewhere to move the help text to an `iframe`.
