### ISSUE TITLE
New Requirement: easy navigation among bookmarks

### ISSUE THREAD

**Issue by hatelove85911** [philc/vimium#1894]
If you're like me, you also have a huge collection of bookmarks which sitting on the bookmark bar. I like vimium very much because it  frees me from the damn slow mouse. But sometimes I still find myself need to move mouse and point to open some bookmark folder to open the a website I saved. 

I know vimium provides the bookmark Vomnibar to quickly search among all the bookmarks. But that's for those who can remember the key words of the bookmark they want to open. If you're like me, it's completely blank in your head.  But, I know where the bookmark is located, that's when I move the mouse to point.

So, I come up with the idea about this new requirement:

I'd like some key mapping which can bring up visually some keystrokes aliigning with the bookmarks on the bookmark bar like below:
![image](https://cloud.githubusercontent.com/assets/2359121/11264147/442fe69a-8ecc-11e5-9789-af15676ea5a4.png)

When I type `c` it will open the corresponding folder for me, and again bring up some keystrokes which can furture open bookmarks inside.
![image](https://cloud.githubusercontent.com/assets/2359121/11264152/4c58fa46-8ecc-11e5-925c-40dc20003957.png)

Of course, when the target is a url, it will open that url in a new tab.

**Comment by smblott-github** [comment]
Is this what you're looking for, @hatelove85911? ... https://github.com/philc/vimium/wiki/Tips-and-Tricks#searching-bookmarks-by-folder

**Comment by hatelove85911** [comment]
@smblott-github , thanks very much, the tips is really awesome, I didn't know. But I think the requirement is still valid:
1. it's more intuitive
2. I don't need to remember any keyword.
