### ISSUE TITLE
Feature Request: Heading Navigation

### ISSUE THREAD

**Issue by gqqnbig** [philc/vimium#1895]
For example I'm browsing https://www.visualstudio.com/en-us/news/vs2015-vs.aspx.
![2015-11-19 18_36_58-visual studio 2015 rtm _ release notes](https://cloud.githubusercontent.com/assets/614159/11290542/9fe300e2-8eec-11e5-80fe-2e7d61e270bf.png)

I'm not interested in Visual C++. I want to look at C# stuff. Instead of searching, I believe C# is in another heading, can we have a function to show the heading structure of the page and navigate between headings?

**Comment by smblott-github** [comment]
Thanks, @gqqnbig.

Sorry, but that sounds too niche to me.

Many users (e.g. me) only use features that they use often (because I can't remember the others).  And that use case doesn't sound like it would come up enough to be memorable.
