### ISSUE TITLE
Comment links not hinted in the Ghost blogging platform

### ISSUE THREAD

**Issue by matthew-cline** [philc/vimium#1896]
When trying to follow links in a page rendered by the [Ghost](https://ghost.org/) blogging, Vimium doesn't catch links in the comments section.  An example is [anything a the Coding Horror blog](http://blog.codinghorror.com/xp-automatic-update-nagging/).

**Comment by smblott-github** [comment]
Looks like it's in a separate frame.

Not great UX, but `gf` will select the comments frame (and `gF` takes you back to the main frame).
