### ISSUE TITLE
visual mode bug

### ISSUE THREAD

**Issue by ilaipi** [philc/vimium#1902]
First time I press the `v` to get into `visual mode`, I can move my cursor.
And if I press `v` again I can begin select text.

After I press `esc`

I press `v` to re-enter `visual mode`, I can't move my cursor, just start select directly

**Comment by smblott-github** [comment]
Thanks, @ilaipi.

That's actually an intended feature.

There are two modes, caret mode and visual mode.  When you type `v` and there is an existing selection, then you enter visual mode directly.  If there is no existing selection, then you first enter caret mode.  In your example, there's no existing selection the first time (so caret mode), but there is the second (so visual mode).

A couple of tips:

- you can enter caret mode from visual mode by using `c`
- in visual mode, you can use `o` to swap the focus and the anchor (so, to move the other end of the selection).

**Comment by ilaipi** [comment]
Thanks for your response! 

The caret mode is great! And also is the `o`!
So why not put all these into the `help document`?

This plugin is very helpful, thank you!

**Comment by smblott-github** [comment]
> So why not put all these into the help document?

Good idea: https://github.com/philc/vimium/wiki/Visual-Mode
