### ISSUE TITLE
Can't use Vimium in some pages

### ISSUE THREAD

**Issue by LQYMGT** [philc/vimium#1903]
For example this page: https://bbs.sjtu.edu.cn/frame2.html .

**Comment by smblott-github** [comment]
There are multiple frames on that page.  Hit `gf` a couple of times to get the frame you want focused, then `j`, `k`, etc should work as expected.

**Comment by LQYMGT** [comment]
Thx. Work fine now. But maybe we can refer to VimFx, which can detect the frame.
