### ISSUE TITLE
How to disable browser auto-focus in text fields?

### ISSUE THREAD

**Issue by a93ushakov** [philc/vimium#1904]
By default, if open some new sites browser auto-focus on text field - and vimium becomes unusable.
The simplest example - new tab.
Is here any way to disable in chrome settings auto-focus feature?

**Comment by mrmr1993** [comment]
There's an option called "Don't let pages steal the focus on load" in the advanced options that should do this.

**Comment by a93ushakov** [comment]
Thank you!

It works on all pages with text fields, but how make `vimium` work on new tab page?

**Comment by guludo** [comment]
It would be great to have that info in the FAQ. That was the first place I looked.

By the way, thanks! I loved this extension. I have some ideas and might be able to contribute.

**Comment by Kha** [comment]
In Firefox it's `browser.autofocus` in `about:config`.
