### ISSUE TITLE
x and u auto scroll

### ISSUE THREAD

**Issue by epolar** [philc/vimium#1905]
when i pressed x or u, i want the webpage scroll half page, but sometime is auto scroll and not stop. esc can exit scroll, press shift + / make it right opt

**Comment by smblott-github** [comment]
Thanks, @epolar.  There's another issue on this somewhere.

We (I) can't figure out what's causing this at the moment, unfortunately.  And we don't yet have a consistently repeatable example.

So thanks for the report, but there's not an immediate fix.
