### ISSUE TITLE
exclude ctrl-alt key

### ISSUE THREAD

**Issue by mihkell** [philc/vimium#1906]
I need to use ctr-alt key for some of the special characters in my language.
I have custome made this key binding. But Vimium doesn't let me use that key combination.(ctrlAlt + [)

how could I exclude it from all of the sites? What kind of exclusion pattern should I use?

**Comment by code-hunger** [comment]
Going to insert mode should solve your problem, I think. Just press `i` and then enter your key-combination.

**Comment by mihkell** [comment]
If focuse is on text area and I press 'i' it will type 'i'. If I'm out side of text area and press 'i' then how can I get focuse to text area without leaving insert mode?

**Comment by smblott-github** [comment]
For the specific key combination you're talking about, this looks like a bug. `C-[` is intentionally `Escape`.  Unfortunately, the code isn't checking that `Alt` isn't depressed too.
