### ISSUE TITLE
Feature Request: Custom Search Engine on Highlighted Text

### ISSUE THREAD

**Issue by risk00** [philc/vimium#1910]
In addition to entering the custom search engine shortcut plus the search string in the Vomnibar, it would be useful if we highlight some text on the page then enter the custom search engine shortcut in the Vomnibar to search for highlighted text.

Thanks for a great extension.

**Comment by gdh1995** [comment]
You may try my custom [Vimium++](https://github.com/gdh1995/vimium-plus) with such settings:
* Mappings: `map Cb autoOpen keyword=dict`
* Custom search engine: `dict: http://www.bing.com/dict/dict?q=%s Bing Dict`

And if no text is selected, `autoOpen` will get text from clipboard and try to open it as a url or search it using `"dict"` engine

**Comment by smblott-github** [comment]
Your proposal can't be the default @risk00; so it would need a new command (and new bindings for each custom search engine of interest).  Since *copy-and-paste* is available, it's not obviously worth it.
