### ISSUE TITLE
Scroll gets stuck until page refresh

### ISSUE THREAD

**Issue by jamespullar** [philc/vimium#1911]
Once you get vimium in this state, any scroll command (j,k,u,d, etc) does not release so scrolling never stops. Refreshing the page corrects the issue. Otherwise you end up limited to using the spacebar and arrow keys to page up and down.

OS: OSX 10.10.5
Browser: Chrome 47.0.2526.80

Steps to reproduce:
1. Open any website
2. Press f
3. Open a background tab using shift + link shortcut
4. Go to new tab using shift + k
5. Close tab (Doesn't matter how, but I use cmd + w)
6. Use any scroll command (j,k,u,d) and notice scrolling does not stop

**Comment by jamespullar** [comment]
This is a new issue instead of adding to #1549 because the title is referencing an older version.
Just noticed this has the same steps to reproduce as #1174. Most likely the same as #1905.

**Comment by smblott-github** [comment]
Thanks, @jamespullar.  Yes, this does look like a different issue.

**Comment by jdpopkin** [comment]
I tried adding console.log statements in the keydown/keyup handlers in `scroller.coffee` and the keyup event isn't firing at all after I follow @jamespullar's steps to reproduce.

I've also noticed that pressing the shift key solves this problem.

**Comment by WChargin** [comment]
Ooh, neat, thanks for fixing! I had gotten used to just pressing shift all the time :)
