### ISSUE TITLE
request for a feature to copy search text

### ISSUE THREAD

**Issue by joseph-ortiz** [philc/vimium#1912]
In my workflow, i copy and past text. I would like to suggest the feature to search text and copy it.

I'm thinking the search and copy command would be like:
"/searchText%yy"

What are your thoughts on this? Do you think it would be helpful? does the command seem logical from a vim like approach?

**Comment by smblott-github** [comment]
Seems pretty cryptic and hard to discover, @joseph-ortiz, if you don't mind me saying.

If we assume you *found* the text you're looking for in the most recent search then visual mode may help.  For example, on this page:

    /workflow<Enter>
    vy

**Comment by joseph-ortiz** [comment]
Thanks! I overlooked this in the advanced features. 

Sorry for the cryptic suggestion, I'm still learning Vimium and Viim and not entirely sure what commands would be ideal.  i'll close this issue.  

By the way, awesome job! This changed the way I'll browse frover
