### ISSUE TITLE
can't use link text and numbers for filtering

### ISSUE THREAD

**Issue by wang-d** [philc/vimium#1914]
Vimperator/Pentadactyl have a nice feature where I can type a unique prefix of the text of a link to select it.  I thought that in Vimium the equivalent option would be "Use the link's name and numbers for link-hint filtering" but I get the same behavior whether or not that option is on.  Either way, my link hints are capital letters (no numbers), and if I start typing the link text I either follow some other link (depending on the alphabetical link hints) or exit the follow-link mode (if what I type isn't any hint).  
![options](https://cloud.githubusercontent.com/assets/3472168/11875956/2ffe7c50-a4b5-11e5-9737-04783defe793.png)
![hints](https://cloud.githubusercontent.com/assets/3472168/11875967/3c1c9d5a-a4b5-11e5-9b8c-b1c8714fff2f.png)

Does Vimium let me follow links by typing the text?  How do I do that?

**Comment by mrmr1993** [comment]
That option should do what you want, and I'm not really sure why it's not working. If you refresh the options page, does it stay checked? Does anything change if you uncheck it, save, re-check it, and save again?

**Comment by smblott-github** [comment]
This should work as you expect, @wang-d.

What happens if you do the things @mrmr1993 suggests?

**Comment by wang-d** [comment]
I've switched to cVim, so this isn't a problem for me any more.  Thanks for
following up, though.

2016-01-30 7:26 GMT-05:00 Stephen Blott <notifications@github.com>:

**Comment by idano** [comment]
had the same issue but @mrmr1993's suggestions worked (unchecking, saving changes, rechecking)

Ubuntu 17.10, Chromium 62.0.3202.89
