### ISSUE TITLE
Feature request: move to previously active tab

### ISSUE THREAD

**Issue by jdpopkin** [philc/vimium#1919]
When I have a lot of tabs open and I check a pinned tab like Gmail, I often waste time finding my way back to the tab I was in previously, especially when it's one of many similarly-titled tabs. So it'd be nice if Vimium had a command to go back to whatever tab I was in before the current one - something like `:b #` in Vim.

I've got this working locally and will submit a pull request soon.

**Comment by mrmr1993** [comment]
`T<enter>` should achieve this (tabs are listed in order of recency). There is some discussion about this in another issue, where the verdict was not to add a new dedicated command for now.

**Comment by jdpopkin** [comment]
Fair enough. I'd like to have this command be remappable (without messing with my `T` binding) but it's not very important.

Would there be more interest in commands analogous to Slack's Cmd-[ and Cmd-], which navigate backwards and forwards in tab history (such that calling the back command twice wouldn't put you back on the original tab)?

**Comment by smblott-github** [comment]
> Would there be more interest in commands analogous to Slack's Cmd-[ and Cmd-], which navigate backwards and forwards in tab history (such that calling the back command twice wouldn't put you back on the original tab)?

We get feature requests for everything, and for every variation on everything.  At some point we have to pick what is most generally of interest.  Sorry -- but  I'm not sure that ideas is above threshold.
