### ISSUE TITLE
`find mode` not work.

### ISSUE THREAD

**Issue by iahu** [philc/vimium#1923]
Hi, I just find that the find mode view not show, when i press '/'.  I can't find any option on the setting page. Does anybody know if there a option to turn off the 'find mode' ? or it's a issues?

**Comment by smblott-github** [comment]
There is no option to turn off find mode, other than removing the binding.

You can check your binding with `?`, binding should be about the middle of the right-hand column.

Nothing has changed in Vimium recently which should cause this problem.

**Comment by iahu** [comment]
Yes, I can find the binding, it's `/`. but nothing happened when I press `/`.
I have no idea why all other bindings work will, but not `/`.

**Comment by smblott-github** [comment]
@iahu. Are you seeing this on *all* pages?  For example, on this page?

**Comment by iahu** [comment]
I see. I have checked the ` Hide the Heads Up Display (HUD)` option. and that cause the issue. Thank you @smblott-github .
