### ISSUE TITLE
Feature Request: Add the ability to blacklist a site from the extention button

### ISSUE THREAD

**Issue by Aleroniponi** [philc/vimium#1927]
For example, If I were to go to a site, I would like the ability to right-click the "V" icon and set the parameters from there if possible.

**Comment by smblott-github** [comment]
Currently you can disable Vimium completely from the "V" icon, or disable just selected keys.  What else do you have in mind?

(Left click, not right click.)

**Comment by smblott-github** [comment]
Closing.

See [here](https://github.com/philc/vimium/wiki/Disabling-Vimium) and in particular [here](https://github.com/philc/vimium/wiki/Disabling-Vimium#tip).
