### ISSUE TITLE
F/f help information is reversed

### ISSUE THREAD

**Issue by keke9036** [philc/vimium#1928]
Version: 1.53
Help information shows 
" f	:	Open a link in the current tab
F	:	Open a link in a new tab"
But f is actually open a link in a new tab and F is open a link in the current tab

**Comment by smblott-github** [comment]
This works as specified here.

Do you perhaps have caps lock on?

**Comment by mrmr1993** [comment]
It sounds like you're holding shift while typing in the link and characters. Try typing in nothing except the Lincoln characters themselves when selecting a link, and see if that works.

@smblott-github this is an issue that keeps coming up. There should probably be a message (that covers the page for a second or two, so it's not ignored like the HUD) shown when a user holds shift while typing hint characters during the first few (~5?) times a user uses link hints. Is this an idea that could make it into the codebase?

**Comment by smblott-github** [comment]
@mrmr1993... We have a lot of users, and it comes up only from time to time.  I'm not sure there's a case for any new UI elements.

An alternative would be to display the hints in lower case, since that's what the user actually types (and possibly that's the source of the confusion).

**Comment by mrmr1993** [comment]
> display the hints in lower case

That is the easiest option, but it's not as attractive and may upset some current users. Perhaps there's a way to entice more users into searching the open and closed issues before opening a new one, so these stop popping up.

**Comment by keke9036** [comment]
@mrmr1993 @smblott-github 
Oh, yes. The link hints cause this confusion. So actually it's
1. When I typed f, the page shows the link hint characters which are in uppercase. I  typed characters in uppercase, the link is opened in a new tab; in lowercase, the link is opened in current tab.
2. When I typed F, it's just the opposite.
