### ISSUE TITLE
add visible find mode

### ISSUE THREAD

**Issue by Muffasa** [philc/vimium#1929]
when i enter find mode with / and search for a word (usually for copy) I find myself most of the time in a whole diffrent part of the page pressing 'n' several times until i reach my target.

any chance to add somthing like find mode only on the VISIBLE text?
/word - will find all accurrrensec of "word" in the entire page.
suggestion*:
/-word - will find all the accurrensec of "word" in the current visible text of the page (scroll disabled)

**Comment by smblott-github** [comment]
I agree.  In my view, the *default* behaviour (in the absence of an existing selection) should be to start the search at the top of the current viewport.

(This is particularly important when find is used with visual mode to select text.  I can see the text I want, so find shouldn't zip me off to an entirely different part of the page.)

**Comment by smblott-github** [comment]
Alternative approach:

- first enter visual mode
- then use find

That way, the search (usually) starts at the top of the viewport.

Closing:
In light of this workaround, the case for changing the established behaviour of find isn't so strong.
