### ISSUE TITLE
yank multiple links

### ISSUE THREAD

**Issue by rachmadaniHaryono** [philc/vimium#1936]
is it possible to yank multiple links without, press the yank buttons (default 'yf') multiple times?

e.g. when press 'ymf' (or other keys) the hint to link is shown, and after pressing the keys to a link, the hint still shown up until escape is pressed, and that link is copied to clipboard

**Comment by smblott-github** [comment]
This would be addressed by (a revised) #1291.
Closing.

**Comment by AvidSeeker** [comment]
@smblott-github
This feature is really helpful for researchers or for people who fill their browsers with tabs like me.

I hope you consider adding this simple feature. The clipboard basically is appended with links that are separated by newlines.

Thank you

**Comment by Drowze** [comment]
would love to see this feature as well. As fair as I understand, currently only [Vimium C](https://github.com/gdh1995/vimium-c) can do it (through `copyWindowInfo`).
