### ISSUE TITLE
Switch tab doesn't work on tab with PDF open

### ISSUE THREAD

**Issue by jcouv** [philc/vimium#1940]
The J and K shortcuts for switching tabs works on most tabs, but if you switch to a tab with a PDF opened, then you cannot switch out. The default Chrome shortcuts (Ctrl-Tab and Ctrl-Shift-Tab) do work however?.

**Comment by smblott-github** [comment]
Chrome does not run extensions on PDF tabs.  So Vimium doesn't run in this case.

Unless something changes with Chrome, there's nothing we can do to fix this.

**Comment by jcouv** [comment]
Makes sense. Thanks!
