### ISSUE TITLE
Tests fail/hang with latest PhantomJS (2.1.1)

### ISSUE THREAD

**Issue by stephanepoirier** [philc/vimium#1944]
With the latest PhantomJS (2.1.1), running `cake test` fails then hangs:

``` bash
Running unit tests...
Pass (136/136)
Running DOM tests...
Fail "Mode utilities: not exit on escape if not enabled" -  function (message) {
  this.name = AssertionError;
  this.message = message;
}: Expected 0 but received 2
Fail "Normal mode: not suppress escape" -  function (message) {
  this.name = AssertionError;
  this.message = message;
}: Expected 0 but received 2
```

Execution hangs when the test named "Focus each input when its hint text is typed" indirectly invokes: `page.sendEvent "keypress", request.key` (phantom_runner.coffee: line 32)

I started investigating. I'm currently unsure about the root cause and how to fix. In the meantime, I'll update the CONTRIBUTING.md file to recommend using version PhantomJS 1.9.8, which works fine.

**Comment by StephanePoirier** [comment]
Progress update: issue reproduced on both Windows 10 and Debian Jessie.

The hanging issue is specific to the HTML "color" input component. Under Windows, running tests opens the OS-native color picker dialog and waits for an user input to resume and complete tests. Under Debian, no dialog is shown, but PhantomJS still waits for the user input without showing the dialog.

**Comment by smblott-github** [comment]
Thanks, @StephanePoirier.

Yup.  I reproduced this (although the `npm` version I get still seems to be fine).

So, there are two issues:

- The tests hang due to the HTML5 `color` input, as you've identified.  We can fix this just by dropping `color` from the `inputTypes` list.  That case isn't particularly adding much.
- And the two tests listed above now fail.  This needs more work.

Suggest we hold off on #1945 for a few days until we've had a better chance to look into this.

**Comment by StephanePoirier** [comment]
Progress update:
- Color input: I'll file a bug on PhantomJS. As you suggest, @smblott-github, I'll remove the color input test for the moment.
- The 2 failing tests with 2.1.1 are a valid concern. Those same tests pass in 1.9.8, as a side-effect of the `setup`/`tearDown` invocation from `PostFindMode`. I'll be start working on this test isolation problem.

**Comment by smblott-github** [comment]
Thanks, @StephanePoirier.

**Comment by StephanePoirier** [comment]
Root issue for the hanging problem: https://github.com/ariya/phantomjs/issues/13979

**Comment by smblott-github** [comment]
Fixed (well, workaround) in #2015.

**Comment by stephanepoirier** [comment]
Pull request #2015 addresses the hanging part of the issue. Tests are still failing. I suggest re-opening until it's fully fixed.

**Comment by stephanepoirier** [comment]
I suggest reworking the test framework before addressing the failing tests. See my [mailing-list post](https://groups.google.com/forum/?hl=en#!topic/vimium-dev/5LrA8ZEO4UA) for details.

**Comment by philc** [comment]
This is now defunct since we've switched from phantomjs to puppeteer.
