### ISSUE TITLE
can it add a feature to switch to recent tab with one key

### ISSUE THREAD

**Issue by qwIvan** [philc/vimium#1946]
i am using this extension to do it.
https://chrome.google.com/webstore/detail/toggle-switch-recent-last/odhjcgnlbagjllfbilicalpigimhdcll

in vimium, i can press shift+t then press enter to do this, can i do it with only one key?

**Comment by smblott-github** [comment]
Not currently.

This has been much discussed, and the current decision is to stick with the approach you already described.

**Comment by smblott-github** [comment]
Closing, because this is discussed extensively elsewhere.
