### ISSUE TITLE
Find mode broken if HUD display is disabled

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1953]
Try it.

(I guess it's been like that for a while, and nobody's noticed.  Do we even need to option to disable the HUD?)

**Comment by gdh1995** [comment]
So we may remove the option to disable HUD, and add a command to hide the HUD on current page temporarily.

**Comment by smblott-github** [comment]
Definitely no knew command.  We should make it work or remove the option.  I favour the latter.

Perhaps fixing it would be to implement #487.
