### ISSUE TITLE
New features...

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1955]
@mrmr1993 ... As you probably gathered, I did a long troll of the open issues and PRs today (ten hours, and I didn't even look at them all!).

In any case, here are the two things which stood out and that we might act on...

- Implement *pass-next-key* in normal and insert modes. (A bit like `Ctrl-v` in vim.)
- Implement *go-to-previous-tab* (with count).  We have the argument about using the vomnibar in tabs mode; however, reviewing the issues, this really stands out as something which people want.

**Comment by philc** [comment]
Steve, that was epic. I woke up with 250 emails in my inbox this morning =) Looking through them all now.

+1 for both of those suggestions.
