### ISSUE TITLE
Make the help menu searchable

### ISSUE THREAD

**Issue by nfischer** [philc/vimium#1957]
I think there are enough commands (#1269) that it would benefit users to make the help menu searchable. I'd like to see something along the lines proposed by @mrmr1993 in #1948. The default focus when pressing `?` could be put into a search box. Then users can search for a command, either based on the description or the key binding.

I think the best UI would be if commands/description pairs that **don't** match grey out as you search, thus emphasizing commands that match the search.

This would solve two issues:

 1. *Command -> description.* If I stumble upon pressing `yf` one day, but I don't know what it does, I can press `?` and type "yf" and I'll see that it means "Copy a link URL to the clipboard". This would resemble vim's help menu (ex. `:h gq`).
 2. *Description -> command.* If I know I want to go to scroll all the way to the top of the page, I can search "scroll top" and I'll see "gg : Scroll to the top of the page"

These are two nice cases, where the search gives me exactly what I want. One issue is that someone may want to "go to the next tab" and search "next tab," when he/she really needs to type in the query "tab right." It may be worth it to have words like "next" match "right" and "left," since it may be better to return slightly too many results than not enough. That's just my opinion though.

Also, as proposed by @mrmr1993, it might be nice to let the user press `Enter` to launch the command that pops up in the search results. If multiple commands pop up, you might want to allow users to navigate through them with the arrow keys to select the command before pressing `Enter`. Then users don't need to memorize obscure commands like "scroll all the way left."

**Comment by mrmr1993** [comment]
> The default focus when pressing ? could be put into a search box

I was thinking ? again in the help dialog (so ?? from anywhere) would do this. Otherwise it becomes labourious to activate links in the help dialog, and we end up with a hard decision on what to do when exiting the search box's focus.

> One issue is that someone may want to "go to the next tab" and search "next tab," when he/she really needs to type in the query "tab right."

Verbose, unambiguous descriptions should deal with this easily (eg. "**Focus** *(select; move to; go to)* **the next tab to the right**"). I can't think of any commands that couldn't be easily described in this way in 3-4 lines. For these results, I'm really envisioning a google-style results list of about 5 results, not a comprehensive list akin to the current dialog.

Another related thought was contextualised search(/help dialog?), so eg. `?`/`??` from a link hints mode shows only link hint commands, or at least prioritises them (and enter on the list switches mode cleanly). This could entirely replace #1948, and, IMO, for the better.

Otherwise, beautifully put.

**Comment by nfischer** [comment]
> I was thinking ? again in the help dialog (so ?? from anywhere) would do this.

I agree, this might be a cleaner implementation. It'd be nice to only have to press `?` once, but I agree it could be hard to decide on what happens when the user presses `escape`. I think `escape` should remove focus from the search box, and then if pressed again, let the help menu disappear (like it does now). That would be intuitive enough for me.

> Verbose, unambiguous descriptions should deal with this easily (eg. "Focus (select; move to; go to) the next tab to the right").

I could see this making sense if each command has a mapping, short description, and long description. The short description gets displayed with `?`, and the long description gets displayed as a search result (or is at least searchable). This is probably a nicer way to solve the problem I described.

> For these results, I'm really envisioning a google-style results list of about 5 results, not a comprehensive list akin to the current dialog.

I see no reason to limit it to 5 results. Most search queries will cut it down to 5 or fewer anyway. If you prioritize the order of the results, it should be good enough.

Also, it might be nice if a message pops up at the bottom, along the lines of "Press Enter to activate the selected command" once in the `??` mode, just so that users know that's an option available to them.

**Comment by mrmr1993** [comment]
As an example, this is the kind of layout of results I was imagining:
![screenshot from 2016-02-03 16 13 51](https://cloud.githubusercontent.com/assets/1847343/12788396/3ab47ca6-ca91-11e5-8fc5-a2fe71c7a8cd.png)

**Comment by lydell** [comment]
#1869

**Comment by nfischer** [comment]
I'd be in favor of something more along the lines of #1868 actually. It'd be great if we had the same help menu, just with a search box on the bottom. Searching the existing help menu would be much more intuitive than switching context to a search results page.
