### ISSUE TITLE
Unable to use with local files

### ISSUE THREAD

**Issue by JamesValero** [philc/vimium#1959]
The extension is disabled when opening a local file (file:///private/tmp/test.htm) on OS X. I don't have any rules set.

**Comment by JamesValero** [comment]
Solution: Go to manage extensions, in the list go to Vimium, enable "Allow access to file URLs"

**Comment by smblott-github** [comment]
Also, see [here](https://github.com/philc/vimium/wiki/FAQ#how-can-i-use-vimium-on-file-urls).
