### ISSUE TITLE
Hint/input mode "bug".

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1964]
Take a look at this situation, here on Github...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/12710070/72d32fee-c8aa-11e5-88c3-f66020069de5.png)

"Click" the link numbered `22` here.  The link is activated correctly, however, we also drop into insert mode, because there's a `focus` event and `DomUtils.isFocusable event.target` is true.

**Comment by gdh1995** [comment]
In my Vimium, I use this to detect `isEditable`:
``` javascript
notEditableInputs: {
  button: 1, checkbox: 1, color: 1, file: 1, hidden: 1,
  image: 1, radio: 1, range: 1, reset: 1, submit: 1
}
```
