### ISSUE TITLE
vimium doesn't work with file protocol

### ISSUE THREAD

**Issue by coutotyler** [philc/vimium#1976]
I like to download docs for offline reading on the train when I don't have connection. Vimium doesn't work when I open local files on chrome. 
I would like to request this feature. Is this a simple mod? Or something more involved? 

Thanks!
Tyler

**Comment by innaterebel** [comment]
It's a simple... design of Chrome.
[https://github.com/philc/vimium/wiki/FAQ](url)

However be noted that PDF pages will still not work since PDF viewer itself is sort of an extension, and Chrome doesn't allow extensions run on extensions.

**Comment by coutotyler** [comment]
Thank you!

**Comment by N46AN** [comment]
I encountered the same problem, ended up serving the content on localhost apache.
