### ISSUE TITLE
Link hints doesn't show hints for many elements on web.whatsapp.com

### ISSUE THREAD

**Issue by meain** [philc/vimium#1978]
[Whatsapp](https://web.whatsapp.com/).

Unable to enter into a chat using the command 'f', **only some links are shown, none of chats though**.
Cannot exit out of the bottom textfield in the chat using 'Esc' key

**Comment by BlitzKraft** [comment]
I noticed that too. Not only on whatsapp, but on some websites, js links are not reachable using the 'f' key.

**Comment by Sanmoo** [comment]
is there any workaround for getting rid of having to use the mouse in these cases?

**Comment by smblott-github** [comment]
There are two things causing this...

1. The element has a `tabindex` of `-1`, which we're [excluding](https://github.com/philc/vimium/blob/1.54/content_scripts/link_hints.coffee#L227) for some reason.

2. Nevertheless - and unfortunately - if we remove the condition above and "simulate click" the element, then it doesn't seem to respond anyway.

#1859 doesn't seem to find the clickable element either.

**Comment by mrmr1993** [comment]
> The element has a `tabindex` of `-1`, which we're excluding for some reason.

Specifically, we're excluding it because it doesn't make an element respond to clicks, whereas a non-negative `tabindex` does.

I'm at work so I can't check, but are there any non-site-specific features that distinguish the clickable elements from the others?

**Comment by smblott-github** [comment]
> are there any non-site-specific features that distinguish the clickable elements from the others?

Looks like they're using [React](http://facebook.github.io/react/), but you better look yourself.

**Comment by donotnoot** [comment]
I know this is an old issue, but it's still happening. Is there anything that can be done other than not using whatsapp web?

**Comment by AjayBrahmakshatriya** [comment]
The only thing that I found to work is pressing <TAB> twice instead of <ESC> from the input box. The first tab takes the cursor to the chat search box and the second one takes it to the window where there is a list of all chats. All the commands work there.

**Comment by moltenlava16** [comment]
The same problem exists 7 years after this issue was discovered, looks like Ajay's workaround doesnt work anymore either.

**Comment by haridsv** [comment]
One workaround to avoid using mouse is to use browser find to find the chat and then pressing <Enter>.

**Comment by anders2D** [comment]
of course @haridsv, i going to share the steps:

1.- if you are in a chat box, then use tab key either you only go to the next step
2- Use vimium key "f" to know what letter we can use to go to search box
3- select the key
4- write down the name
5- press enter 

READY

**Comment by Enzodtz** [comment]
Hi, is the tabindex problem still what is causing this issue?

If I run:
```
document.querySelectorAll('*').forEach(function(el) {
    if (el.tabIndex == 10) {
        el.tabIndex = 50;
    }
});
```

In the console, `f` still doesn't bring any chats.

Maybe this has to be ran before vimium loads the page content?

My idea would be to write a custom adblock filter to remove those properties that conflict with the extension. Should be something easy, but I'd just need to know what are those. 

Thank you

**Comment by astr0n0mer** [comment]
The right solution at this point is to use WhatsApp Web's shortcut (`Cmd` + `K`) to search and open chats

Press `?` on [web.whatsapp.com](https://web.whatsapp.com/) (_when logged in_) to open the shortcuts table

<img width="864" alt="Screenshot 2024-01-06 at 5 06 20 PM" src="https://github.com/philc/vimium/assets/42691857/67d61651-4513-484a-98fd-027605d992d1">

**Comment by philc** [comment]
Great discussion everyone.

@Enzodtz I checked whether the -1 tab index check is what is preventing many of the links from showing, and it's not. The rows in the list of chats are failing to be detected as links for some deeper reason, which I didn't fully investigate.

While web.whatsapp.com is a popular page, I'm going to close this issue because @astr0n0mer's workaround (use Cmd-K on Mac) is a good solution for this particular issue, and I don't think there's much that can easily be done to make this intricate webapp work better with Vimium. If anyone discovers some changes which can significantly improve Vimium's UX on this site, feel free to reopen this.

Related: WhatsApp also has a desktop app (Mac and PC) which works well. This is what I use rather than visiting the website.
