### ISSUE TITLE
feature request?: scroll by page

### ISSUE THREAD

**Issue by dragonxlwang** [philc/vimium#1982]
Sorry if this issue has been brought before: In vim one can use ctrl+f/b to scroll by (half) page.
In Chrome, equivalent keys are "space" or "shift+space". Can I remap it to ctrl+f/b in vimium?

Thanks,

**Comment by smblott-github** [comment]
Is `u` and `d` what you're looking for?

You can remap them on the options page: `scrollPageUp` and `scrollPageDown`.

**Comment by dragonxlwang** [comment]
thanks! Didn't spot them first time.
