### ISSUE TITLE
Add calculator

### ISSUE THREAD

**Issue by yuntas** [philc/vimium#1983]
# Aim
when we watch stock info, I wanna make a calculation dividend.
therefore, I want you to add calculator function.

for example, when we press this key `=`,

```
=123*456
56088
```

**Comment by smblott-github** [comment]
Thanks, @yuntas.

I'm not sure that's a suitable Vimium feature.

However, if you use Google as your default search engine, then you kind of have a calculator already:

- `o`, `3+4`, `<Enter>`

Also, you can edit and resubmit your calculation:

- `o`, `<Tab>`, ...

**Comment by yuntas** [comment]
Thank you very much, Mr. smblott-github.
