### ISSUE TITLE
Feature Request: Double shift keyboard shortcut

### ISSUE THREAD

**Issue by danielyli** [philc/vimium#1987]
Though the double shift (tap shift twice) isn't a Vim feature, it would be great to make this one exception and to have it be an option to opening the Vomnibar or the Open Tabs search bar, much like Intellij (yes, an IDE, I know....).  Would this be possible?

**Comment by gdh1995** [comment]
Shift key does not make any printable char, so considering the current key mapping logic, it's too hard to implement this feature.

BTW, it's difficult to tell double "press"s from some casual "press"s.

**Comment by smblott-github** [comment]
Thanks, @danielyli.  But, hmm... My fingers hover over `<Shift>` all the time.  I'm guessing this would be more often triggered in error than intentionally.

**Comment by smblott-github** [comment]
Closing.
Interesting idea @danielyli, but could also generate quite some confusion (for users like me whose fingers hover on shift).

**Comment by danielyli** [comment]
Alright, thanks for letting me know.
