### ISSUE TITLE
Scrolling not working anywhere

### ISSUE THREAD

**Issue by adamk33n3r** [philc/vimium#1992]
Both `j` and `k` are not scrolling up and down the page and `G` and `gg` are not going to top or bottom. This even happens on a clean install in incognito mode.

**Comment by adamk33n3r** [comment]
Hmmmmmm. I just tried another extension, cVim, and the scrolling doesn't work there either.....what could be causing that???

**Comment by mrmr1993** [comment]
This sounds like a problem with your Chrome flags. A likely candidate is "Enable experimental web platform features".

**Comment by adamk33n3r** [comment]
That worked! I don't remember why I had that flag set. It's not default is it? Do you know why that flag is actually causing the issue?

**Comment by Neats29** [comment]
Hi, I'm using vimium on a mac and the j and k buttons stopped working (well they switch between tabs instead).
Can't find "Enable experimental web platform features", if that's the fix?

Btw, I LOVE vimium, it's my favourite tool. Thank you.

**Comment by smblott-github** [comment]
@Neats29... Sounds like Caps Lock?

**Comment by Neats29** [comment]
oh, silly me. you're right. 
Thank you.

**Comment by os101** [comment]
Same problem here, enabling "Experimental Web Platform features" didn't solve the problem. It occurs when I'm using Jira tickets. Otherwise, j k are working fine. Can't use G and gg as well. For some reason, the scroll does not work from any vimium shortcut. Should I open a new ticket?
