### ISSUE TITLE
Asterisk is not being passed through as an excluded key

### ISSUE THREAD

**Issue by peterdutton** [philc/vimium#1996]
Hi,

When I want to pass asterisk through to the underlying page it doesn't seem to work. Here is an example of what I have set up for gmail:
![screenshot from 2016-02-18 11 35 01](https://cloud.githubusercontent.com/assets/942130/13142340/4638885c-d634-11e5-94cd-2fac7b9bd195.png)
Other keys are being passed through, just not the asterisk.
I'm on Chrome 48.0.2564.109 (Official Build) (64-bit) on Ubuntu; vimium is version 1.54.

Thanks!

**Comment by smblott-github** [comment]
@peterdutton.  I'm guessing this is the same as #1757.  Perhaps adding `8` as a passkey might be a workaround?  (Or whatever number is on your asterisk key.)

**Comment by peterdutton** [comment]
Thanks @smblott-github  - adding 8 does work.
