### ISSUE TITLE
! and gmail

### ISSUE THREAD

**Issue by rpietro** [philc/vimium#1998]
first and foremost, this is an awesome plugin, thanks a ton for putting this together. question about gmail: i've set ! as an excluded key on the gmail site as it is used to declare a certain msg as spam, but it still can't recognize it. Also tried to escape it and didn't work. Am probably doing something wrong, but not sure what it is

would appreciate any input, thanks

**Comment by smblott-github** [comment]
Thanks, @rpietro.  This is probably the same as #1996 and #1757.  Try adding `1` as a passkey.

(I just pushed #1997 which should fix this.)
