### ISSUE TITLE
chrome.tabs.onActivated doesn't work when switching Chrome window

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#2005]
I'm using Chrome 43/47/48 x32 on Windows 8.1 x64, and after many tests I confirmed that `chrome.tabs.onActivated` won't be triggered when I switch from one Chrome window to another.

This problem makes `TabRecency` not work perfectly, and one work-arount is to use `chrome.windows.onFocusChanged` to grab the event.

I also wonder if this problem could be considered as a Chrome's bug.

**Comment by smblott-github** [comment]
Excellent.  Nice catch, @gdh1995.

Do you want to push a PR?

**Comment by gdh1995** [comment]
#2006 metioned a similar problem of `tabs.onFocusChanged`, so I think these functions are limited by design.
