### ISSUE TITLE
chrome.tabs.onRemoved nearly never works

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#2012]
This api worked well before Chrome 37 (stable version), on which `chrome.sessions` was imported.

In my tests, `tabs.onRemoved` will never be triggered if you close a normal page with a "https?://" url, and the only situation I find it will be called is:
* open a tab which opens another tab and then `close` itself at once on loading
* added: in my tests, the page opens another tab using `chrome.tabs.create url: ...`

So I think this api makes no sense at all.

**Comment by smblott-github** [comment]
I can't seem to reproduce this.  I tried various ways of opening and closing tabs, and `chrome.tabs.onRemoved` was always called as expected.

Chrome 48.0.2564.109.

**Comment by gdh1995** [comment]
Really? In my daily using, it always disappoint me. Let me test again.

**Comment by gdh1995** [comment]
@smblott-github I've found the reason: I enabled "#enable-fast-unload" on chrome://flags.

When I disabled this option, `chrome.tabs.onRemoved` worked well.

**Comment by smblott-github** [comment]
We should add a page to the wiki listing Chrome flags which break Vimium.

**Comment by gdh1995** [comment]
`chrome.tabs.onRemoved` is used only at 4 places:
* main.coffee#L422 / L676: clean `tabInfoMap` and `frameIdsForTab`
* main.coffee#L665: check if there's an incognito window
* bg_utils.coffee#L15: remove `tabId` from `TabRecency`

But, `tabInfoMap` can be cleaned in `main.coffee#L594`: `unregisterFrame`
* the frontend post `frameId`, and if `request.frameId == 0`, `del frameIdsForTab[tabId]`

it can be executed on `chrome.windows.onRemoved` to check incognito windows.

If we rework `TabRecency`, tabIds of removed tabs may have little influence.
