### ISSUE TITLE
j / k scroll up and down keys do not work

### ISSUE THREAD

**Issue by teamblubee** [philc/vimium#2027]
Hi I am on debian jessie and I enjoy this plugin.

I am using chrome browser: Version 48.0.2564.116 (64-bit), Vimium 1.54

all the other keys are working, even using shift and j, k to switch tabs. Just scrolling down the page doesn't working.

How can I debug this?

**Comment by innaterebel** [comment]
Remembering have seen quite a few duplicates that ended up being caused by some of the experimental flags of Chrome. Such as... #1992.

**Comment by os101** [comment]
Same issue here. j/k do not work on some web pages. Specifically on Jira tickets. I'm on vimium 1.63.3, iOS 10.13.4 and Chrome 66.0.3359.139(official).

**Comment by AhmedSdiri** [comment]
My case J/K works on chrome only when zoom is >= 100%
