### ISSUE TITLE
Placement of the HUD covers chat textarea

### ISSUE THREAD

**Issue by jimmycleveland** [philc/vimium#203]
See: http://imgur.com/B0TGV.png

The placement of the HUD obscures the text area in GMail's chat. I would suggest the ability to apply transparency to, or adjust the positioning of the HUD. 'Vimium Options' has the ability to add CSS for link hints, perhaps this capability should be duplicated for the HUD.

Love this extension. Thanks!

**Comment by ddickstein** [comment]
Is there a way to hide it when `f` is pressed?  It seems to cover link hints.
