### ISSUE TITLE
Link hints, a larger refactor

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#2032]
@mrmr1993.  I'm about to merge #2029 (a small link-hints refactor).

However, the link-hints code is in need of a larger refactor. Specifically, each mode should be an object with:

- a `name` (as currently)
- a `linkActivator` method
- a `filter` method (to reject some clickable elements)
- (possibly) an `isClickable(element)` method (to pick elements which would wouldn't otherwise be clickable).  @mrmr1993 - you have an example of such a thing in your link-hints for frames PR.

The idea is that we do this now, and freeze other link-hints activity until it's done.  The work should be a no-op functionality wise.  It may add LoC, but not new logic.

Is that something you'd be interested in contributing, @mrmr1993?

**Comment by mrmr1993** [comment]
Yes, I can do that.
