### ISSUE TITLE
Help dialog/Vomnibar focus issue

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#2038]
Try this in `master`:

- `?`, `o`, `Esc`, `Esc`, `j`

The problem is that the focus is ending up in the help dialog.

@mrmr1993.  I'm stuck as to how to fix this.  See [this comment](https://github.com/philc/vimium/pull/2037#issue-138689677) and [here](https://github.com/smblott-github/vimium/commit/864b72756840b2d99bf437e55d3bb959dcfd59c2#diff-464a415c972610524ac9c8c9fb8ff040R85).

Edit: `git bisect` tracks down this commit: bfe91c609ef9886cfeb5d45bfa1557a9d00faeb2.  But it looks harmless?

**Comment by mrmr1993** [comment]
Seems [this comment](https://github.com/philc/vimium/commit/71d33fdeaa5c081de5041a6a0909d452e1564633#diff-464a415c972610524ac9c8c9fb8ff040R67) was a lie.

Add an `else if sourceFrameId == frameId` branch in `refocusSourceFrame` that refocuses the current frame and that should do it. (Also shouldn't need to check `@showing`, and should just `return unless sourceFrameId?` at the top of the function.)

**Comment by smblott-github** [comment]
> refocuses the current frame and that should do it.

Unfortunately not.  Sometimes the frame Chrome chooses to focus is focused *after* the frame we focus.  We need to wait until after Chrome focuses its frame.  But we've no good way of knowing when that is.

**Comment by mrmr1993** [comment]
> But we've no good way of knowing when that is.

I'm not going to be near a computer to check for a while, but `keyup` and `mouseup` seem the likeliest candidates IMO.
