### ISSUE TITLE
About visual mode

### ISSUE THREAD

**Issue by GeneDockAkira** [philc/vimium#2039]
When enter a new page, press 'v' will let me move the caret(let's call this 'initial' visual mode), press 'v' again will enter the 'real' visual mode to select text. That's cool, but after press 'esc' return to normal mode and do someting, then press 'v' again, it dosen't enter the 'initial' visual mode for moving caret, I can just select text from its last location. Is it a bug? or my understanding was wrong? thanks a lot, after all, Vimium is Cool

**Comment by smblott-github** [comment]
> then press 'v' again, it dosen't enter the 'initial' visual mode for moving caret

`c` takes you from visual mode to caret mode, and `v` takes you back.  Also, `o` (in visual mode) is pretty useful.  Tips [here](https://github.com/philc/vimium/wiki/Visual-Mode).

**Comment by GeneDockAkira** [comment]
@smblott-github thanks a lot! It's that's what I need!

If vimium can support EasyMotion(https://github.com/easymotion/vim-easymotion) feature in the future, it'll pretty cool(:P, I'm so greedy.)
