### ISSUE TITLE
Vimium seems to require javascript to be enabled

### ISSUE THREAD

**Issue by bingaman** [philc/vimium#2046]
I want to whitelist domains that can run javascript, however vimium doesn't seem to work unless javascript is enabled on a domain. Is it possible to use vimium on pages that have javascript blocked?

**Comment by smblott-github** [comment]
Thanks, @bingaman.

> Is it possible to use vimium on pages that have javascript blocked?

That's a "No", I think.
Closing - because there's not a lot we can do.

**Comment by mrmr1993** [comment]
The relevant chromium issue is [here](https://bugs.chromium.org/p/chromium/issues/detail?id=69250). You might want to star it to register your interest in it being fixed.
