### ISSUE TITLE
Tab Extract in vomnibar

### ISSUE THREAD

**Issue by ralesi** [philc/vimium#2047]
Is it currently possible to extract tabs to a separate window?  I would like an option to move all tabs showing after getting filtered in the Vomnibar into a separate window.  An extension already providing this is TabExtract: https://chrome.google.com/webstore/detail/tab-extract/iphchnegaodmijmkdlbhbanjhfphhikp

**Comment by ralesi** [comment]
I would have to get familiar with the source,  but I was thinking a separate vomnibar similar to when T is pressed.  We can filter and then on enter,  instead of just going to the selected tab,  all tabs are grabbed and split off into a separate window.

**Comment by smblott-github** [comment]
Don't rush into this, @ralesi.  This may be a bit too niche.

Separately, in the next full release, `moveTabToNewWindow` (`W`) will take a count prefix.  So `3W` will move three (adjacent) tabs to a new window.  That might go some way towards solving your problem.
