### ISSUE TITLE
Gmail delete shortuct (#) does not work even when excluded

### ISSUE THREAD

**Issue by MichaelAquilina** [philc/vimium#2051]
It seems like vimium prevents me from using the delete keyboard shortcut in gmail (#) even when I've explicitly excluded. Disabling vimium entirely for gmail works but there are certain vimium features I'd still like to have while using gmail (like the goto command - F).

My current exclude filter is as follows:

```
https?://mail.google.com/*    jkgisx?u#
```

**Comment by smblott-github** [comment]
If your `#` key is on a digit key (just shifted), then try adding the digit key to the exclusion rule.

**Comment by MichaelAquilina** [comment]
That worked. Thanks for the quick reply. Do you still consider this a bug or should I close this issue?

**Comment by smblott-github** [comment]
It's known issue, @MichaelAquilina, and it's related to [this](https://bugs.chromium.org/p/chromium/issues/detail?id=227231) Chrome bug.  We'll fix it when we can.
Closing.
