### ISSUE TITLE
Unable to disable smooth scrolling in Chromium

### ISSUE THREAD

**Issue by Zamicol** [philc/vimium#2057]
I have the smooth option deselected and the browser does not smooth scroll, but vimium still does.  

Vimium 1.54
Chromium: Version 48.0.2564.116 Built on Ubuntu 14.04, running on LinuxMint 17.3 (64-bit)

![image](https://cloud.githubusercontent.com/assets/5232965/13858521/a967c048-ec44-11e5-9017-af42109ea4f5.png)

![image](https://cloud.githubusercontent.com/assets/5232965/13858549/c5bb42d8-ec44-11e5-8374-2afb022b0c4f.png)

**Comment by smblott-dcu** [comment]
There's a separate Vimium option on the Vimium options page for that, @Zamicol...

![snapshot](https://cloud.githubusercontent.com/assets/17931286/13884318/6db0adee-ed25-11e5-9111-3df866913628.png)

**Comment by Zamicol** [comment]
Please see the screenshots attached to the previous comment.  Also, I've attached another screenshot to this comment.  

The smooth scrolling option in the Vimium options page is disabled, as well as the Chromium flag option.    Vimium (not Chromium) continues to use smooth scrolling.  

This issue should probably be reopened.  



![image](https://cloud.githubusercontent.com/assets/5232965/13886817/604d3978-ecfe-11e5-85b7-1a3981c28f85.png)

**Comment by zamicol** [comment]
This appears to have been a bug with Chromium.  It is now working as expected.
