### ISSUE TITLE
FR: search texts only in links

### ISSUE THREAD

**Issue by BohrShaw** [philc/vimium#2060]
I find this handy when for example I want to find a download link by searching "download".

**Comment by csalv5** [comment]
f

**Comment by gdh1995** [comment]
You may try another mode of LinkHints - on the options page, click "Use the link's name and numbers for link-hint filtering"

**Comment by BohrShaw** [comment]
@gdh1995 Search in links is locating, which is different from link hints.

**Comment by smblott-github** [comment]
This is probably a bit too niche, @BohrShaw.
