### ISSUE TITLE
How can I make vimium work on github?

### ISSUE THREAD

**Issue by jonahx** [philc/vimium#2061]
Vimium doesn't work for me at all on github presumably because of github's own shortcut keys.

Is there a setting that will allow Vimium to take precedence over github's shortcut keys, so that it works?  Is there a general setting so that this behavior is the default on any site with its own (possibly conflicting) shortcut keys)?

**Comment by smblott-github** [comment]
Does `b` work, @jonahx?  `b` is mapped by default by Vimium but not by GitHub.

If `b` **does not** work, then it sounds like you might have an exclusion rule for GitHub.  Check on the options page.

If `b` does work, then I'm not sure.  Vimium works fine on GitHub here.

**Comment by jonahx** [comment]
You were right, I had an exclusion.  I must have entered it a long time ago and forgot.  Sorry for the false alarm.
