### ISSUE TITLE
Feature Request: Link hint for bookmark bar

### ISSUE THREAD

**Issue by N46AN** [philc/vimium#2068]
I saw there are simimar issues aleady opened, but I think this feature is very important. In my case the bookmark bar contains the most accessed links.

Is this currently possible?

The current 'b' vomnibar is not working well for me because I have thousands of bookmarks, most time the bookmark bar item will not even appear. 
Also, to save space I've left the bookmark title blank,(I guess a lot of people will do this) so I cannot search for its title.

So maybe a new key for bookmark bar link hints?

Thanks!

**Comment by smblott-github** [comment]
[This](https://github.com/philc/vimium/wiki/Tips-and-Tricks#searching-bookmarks-by-folder) might help, @N46AN.

**Comment by N46AN** [comment]
@smblott-github Thank you! This certainly helps. 
Now if I want to open 'forum.ubuntu.org.cn' in the bookmark bar I have to type:
b /boo ub enter

But it will be significantly faster if there is a new shortcut key for bookmark bar link hints.
So please consider my suggestion.
Thanks!

**Comment by N46AN** [comment]
Temporarily worked around this issue by creating my own bookmark webpage and assigning it to the new tab key 't'
Now I can just press 't f' and then follow the link hints.
;-)
