### ISSUE TITLE
There is a memory leak caused by `lastHoveredElement`

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#2077]
I think `lastHoveredElement` in `lib/utils.coffee`:L241 might cause a memory leak.

For example, if I click a `<button  data-dismiss="modal">` button of a modal dialog created dynamically, the `<button>` will be remembered until the next `LinkHints::activateLink`.

Even worse is on a SPA page, like one using angular:
* click a link which is designed to navigate to another page,
* the whole page's DOM tree is then hold by `Utils.simulateMouseEvent`

**Comment by smblott-github** [comment]
That's not really a memory leak, @gdh1995.  Arguably it's inefficient use of memory in some cases, but it's at most one object, so not a memory leak.

**Comment by gdh1995** [comment]
@smblott-github It's not only one object but the entire DOM tree - `lastHoveredElement.parentNode` is often another valid DOM node.

**Comment by smblott-github** [comment]
Yes.  But it's bounded to one element (or one entire DOM tree); not two DOM trees, or more.  It's arguably inefficient use of memory in some cases, but it's not a memory leak.  And in the common case, it's virtually no memory overhead at all.

(Separately, we do the same thing [here](https://github.com/philc/vimium/blob/master/content_scripts/vimium_frontend.coffee#L339), and probably elsewhere).

As of March/April 2016, anybody looking for information about a memory leak should see #2055.

**Comment by gdh1995** [comment]
Um... You are right.

I fail to iter a `WeakMap`, so I've no idea to store it without a leak now.
