### ISSUE TITLE
A heavy command like "1000000j" crashes the tab

### ISSUE THREAD

**Issue by deslee** [philc/vimium#2080]

**Comment by smblott-github** [comment]
Does it "crash the tab", @deslee, or just take a very long time?

If it's the latter, then ff6dee4a3f5d49ae4ea7ae037f6e0df78b65eb31 (which is in `master`) should fix it.  Instead of scrolling by `scrollStepSize` one million times, it scrolls once by one million times `scrollStepSize`.

**Comment by bennyty** [comment]
I just tried 999999j (6 9s), 1000000j (one more), and 9999999j (9 times more). The first two causes the page to scroll down eventually but 7 9s causes Chrome to decide the page has become unresponsive. If told to wait the page produces the same dialog 6-8 times then the page actually crashes with the "Aww snap" page.

**Comment by smblott-github** [comment]
Thanks, @bennyty.  I'm not too worried about this.  It should be fixed in `master` (and in the next release).  The old implementation called scroll 1000000 times.  With ff6dee4a3f5d49ae4ea7ae037f6e0df78b65eb31, we call scroll once.  That should do the trick.

Closing.
