### ISSUE TITLE
Introduce CTRL-P to focus on URL bar

### ISSUE THREAD

**Issue by vveleva** [philc/vimium#2085]
Chrome's shortcut for focusing on URL bar is CMD+L (on Mac) and it would be nice to be able to assign new shortcut to it.

Just in general, it'd be great to have the option to overwrite default commands with custom vim ones.

**Comment by smblott-github** [comment]
Thanks, @vveleva.  I'm not sure re-mapping Chrome's keys is really a Vimium design goal.  Furthermore, in this case I don't think what you propose is supported by the Chrome API.
