### ISSUE TITLE
Hotkey to go to next page

### ISSUE THREAD

**Issue by zaz** [philc/vimium#2086]
One really useful feature that Vimium lacks is a hotkey to go to the next page. This could be done by following `<a rel="next">` links, or, if none exist, by more complicated methods such as using class names to guess which is the link to the next page.

**Comment by smblott-github** [comment]
Thanks, @zaz.  Are `[[` and `]]` what you're looking for?

(Implementation [here](https://github.com/philc/vimium/blob/master/content_scripts/vimium_frontend.coffee#L603).)

**Comment by zaz** [comment]
Holy boa of samoa! I'm sorry, I hadn't noticed the advanced command listing. These commands are a life-changer!

Thanks a lot! I'll be sure to search the source code in the future.

I think those "advanced" commands should be shown by default because most of them seem just as useful as the basic commands.
