### ISSUE TITLE
enable on chrome:// URLs

### ISSUE THREAD

**Issue by Dmitra** [philc/vimium#2090]
There is an experimental setting at chrome://flags called "Extensions on chrome:// URLs" which enables running extensions on chrome:// URLs, where extensions explicitly request this permission.

Could you please utilize this ability to make vimium work on those pages?

**Comment by gdh1995** [comment]
Like num: +1.

But I can not find any document about it in developer.chrome.com.

**Comment by smblott-github** [comment]
Yes.  If anybody knows how to do this, then a PR would be welcome.

**Comment by Dmitra** [comment]
https://developer.chrome.com/extensions/experimental

**Comment by smblott-github** [comment]
Looks like a non-starter...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/14485007/2d3e6f72-014c-11e6-907d-cafbf1f2b78c.png)
