### ISSUE TITLE
[Enhancement] Support bookmark searching by folder

### ISSUE THREAD

**Issue by kawing-chiu** [philc/vimium#2096]
Hi. Vimium is really a great extension. Thank you developers for making it! From my experience with it, I have the following suggestion regarding the bookmark search functionality:

I've been organized all my bookmarks by using many levels of folders and renaming the bookmarks at will. However, this scheme dosen't work well with vimium's current bookmark searching method at all. Because the searching is done against the full url, not the full folder path to the bookmark. I don't mean that the current method used by vimium is problematic, it is good for most users. But it would be great if an option or something can be added to enable the other usage.

**Comment by smblott-github** [comment]
This might be what you're looking for, @kawing-chiu: [https://github.com/philc/vimium/wiki/Tips-and-Tricks#searching-bookmarks-by-folder](https://github.com/philc/vimium/wiki/Tips-and-Tricks#searching-bookmarks-by-folder).

**Comment by kawing-chiu** [comment]
No, not really. What I really want is the almost exact behavior of vim's CtrlP on the full bookmark path. For example, consider the following folder structure:
```
> /python/numpy/arrays/
      Array creation basics
      arange
      linspace
      (more bookmarks...)
```
When I type `'numarr'`, in CtrlP, it would have already listed ANYTHING under the folder '/python/**numpy/arr**ays/' to hint me (and highlighted just like this). Then I further type `'numarrlin'`, the search narrows down to a single result 'python/**numpy/arrays/lin**space'.

**Comment by smblott-github** [comment]
OK, @kawing-chiu, but that's a different idea.  That defines how we decide whether a query matches a *thing* (be that "thing" a bookmark, a history entry or a tab).  Basically, CtrP doesn't require consecutive characters in the query to be consecutive in the "thing", whereas Vimium does.

I don't think we'll be changing Vimium's behaviour in that regard; and it's probably too niche to add as an option.

**Comment by kawing-chiu** [comment]
So, @smblott-github , how can I do the same search in Vimium© 's way? What search string should I use?

**Comment by smblott-github** [comment]
Probably something like `/n /a lin` would work.  It depends what bookmarks you have.

**Comment by kawing-chiu** [comment]
Thank you @smblott-github , this kind of works. I have another idea, which is even a better solution of bookmark management IMHO. That is, a NERDTree-like interface. How do you think about it?

**Comment by smblott-github** [comment]
Everything is possible, @kawing-chiu.  However, we have an established mechanism for selecting bookmarks, and we don't really need another one.  One of the Vimium design goals is to provide a simple and intuitively-obvious extension to Chrome's UI.  I'm not sure something NERDTree-like would be a win in that regard.
