### ISSUE TITLE
Tab Navigation not Working on Pinned Tabs or chrome[-extension]:// URLs

### ISSUE THREAD

**Issue by skorlir** [philc/vimium#2098]
Hello,

First of all, I love vimium. However, I can't cycle through my tabs very efficiently, because currently the next tab / previous tab operations don't work on pinned tabs. It doesn't seem to depend on the URL loaded in the pinned tab.

Also interesting is that tab cycling seems to break on chrome:// and chrome-extension:// URLs.

Since I always have pinned tabs, and fairly often have chrome:// and chrome-extension:// URLs, this makes vimium a lot less fluid. I have to switch to Ctrl+[Shift]+Tab on those tabs.

Seems like this should be an easy fix?

If you're interested in having the help, I'd be willing to look into it and make a PR. Just point me in the right direction.

**Comment by smblott-github** [comment]
> because currently the next tab / previous tab operations don't work on pinned tabs.

That shouldn't be the case (and it's not the case for me).  You're talking about the `nextTab` and `nextTab` commands (`K` and `J`, by default), right?  From Vimium's perspective, there's nothing special about pinned tabs.

> Also interesting is that tab cycling seems to break on chrome:// and chrome-extension:// URLs.

This problem is fundamental.  Chrome doesn't run extensions on (most of) those pages.  Full stop.  So there's nothing we can do about it.

**Comment by sheenp333** [comment]
I'm not able to navigate through pinned tabs on Firefox 55.0.3 running Vimium 1.60

**Comment by sheenp333** [comment]
Actually, it appears there are no vimium functions working on pinned tabs.  BTW, thanks for such a great product.

**Comment by smblott-github** [comment]
> Actually, it appears there are no vimium functions working on pinned tabs. BTW, thanks for such a great product.

Is that a GMail tab, by any chance?  Vimium is disabled on GMail by default, you can change that on the options page.

**Comment by sheenp333** [comment]
No, not gmail. twitter, feedly and some others

**Comment by sheenp333** [comment]
However, it does work on my 55.0.3 running on Linux

**Comment by sheenp333** [comment]
Well, a new day and all is working well.  I'd just installed vimium-ff yesterday.  Maybe I needed to restart.  Sorry for any inconvenience.
