### ISSUE TITLE
Vimium loses focus after find mode

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#2099]
Try [this page](http://gothamist.com/2016/04/14/nypd_cyclist_cops_bike_lane.php) or [this one](http://www.thejournal.ie/brothel-owner-dublin-jailed-2715951-Apr2016/).

- Wait for the page to load.
- `/`, `Escape`, `j`
- The page doesn't scroll.

What's happening is that the focus is ending up in a frame other than the originating frame.  In fact, it's ending up in a frame that hasn't previously received the focus.

The effect is that Vimium seems broken.  `gF` recovers, but there's no reason why an average user should think (or even *know*) to do that.

This commit fixes things: d24f0500a5f2fa720cf00af0295a87f9377a590e (not merged).  However, I'm nervous about d24f0500a5f2fa720cf00af0295a87f9377a590e, because the UI-component exit sequence is already pretty complicated and d24f0500a5f2fa720cf00af0295a87f9377a590e could have unintended side effects.

Instead, I think we need to entirely rework the UI-component exit sequence.  And that will require some thought.  What makes things tricky is that, when a UI component closes, Chrome does "something" with the focus "sometime".  And we don't always know what Chrome is going to do or when.

I'd label this as a release blocker, except the issue exists in 1.54 too -- so it's not a new problem.

**Comment by gdh1995** [comment]
When I refreshed the second page the third time, Vimium suddonly worked well.

No other `focus`/`blur` listener was found on the page, so I don't know what happened.
