### ISSUE TITLE
New commands for moving tabs within and between windows

### ISSUE THREAD

**Issue by bibach** [philc/vimium#210]
Moving tabs around is one of the big things in Chrome that I still needed the mouse for.  Vimium provided some great tools for the other big thing (clicking on links, etc.), so I decided to take a crack at adding commands for moving tabs.

    gh    move current tab to first (or n-th) position to the left
    gl    move current tab to first (or n-th) position to the right
    gp    move current tab to last (or n-th) position in window
    gP    move current tab to marked position (may be in another window)
    gm    mark position of current (or n-th) tab in this window
    gM    discard marked tab position (next gP will tear tab into new window)

The _gP_, _gm_ and _gM_ commands are intended mostly for moving tabs between windows by marking a position within a given window as the destination for a tab moved with _gP_.  By specifying a count on _gm_, it's possible to mark a position beyond the last tab, which is useful for quickly moving one or more (with a count on _gP_) tabs to the end of another window.  If no position is marked, such as just after startup or after a _gM_, _gP_ will just "tear" the tab off into its own window of the same size and location, but will mark the tab's previous position so it can be put right back where it was with another _gP_.

I had to modify handling of counts a bit, allowing them to be passed to background page commands and allowing count to be NaN if none was specified, so that certain commands can behave differently if there is no count vs. a count of 1.  For example, _gp_ defaults to moving a tab to the last position in the window, if no count is specified.

I'm pretty happy with how these turned out, but I welcome thoughts and ideas about how these commands might work differently and any alternative key mappings for them.  This is my first significant foray into both Chrome Extension development and git, so I welcome critiques on any aspect of this potential contribution.

http://github.com/bibach/vimium/commit/6e3adbd2005e4a519e8decad119b27fabb58f795

**Comment by brillout** [comment]
+1

@philc 
is this commit merged into master?

**Comment by smblott-github** [comment]
Currently, we have:
- `moveTabLeft`
- `moveTabRight`
- `moveTabToNewWindow`

We don't have the stuff about marking tab positions and moving tabs between existing windows.

**Comment by brillout** [comment]
ah, nice!
I didn't see the "show advanced commands" link and therefore missed these commands, sorry.

**Comment by deiga** [comment]
Would be great if there'd be a command to move a tab to the next window!

**Comment by coutotyler** [comment]
I would also like to be able to move tabs among current windows. Is there any update on these features?

**Comment by pekcheey** [comment]
In case you don't know, the functionality to move tabs in the current windows is already in.

**Comment by deiga** [comment]
Since this never made it to the PR stage should it just be closed? This is very misleading in it's current form.
