### ISSUE TITLE
Any chance of a mute tab binding?

### ISSUE THREAD

**Issue by gerrywastaken** [philc/vimium#2102]
One of the things I find myself still needing to go to the mouse for is muting a tab to stop a random ad playing in the background. Any chance of a binding being added for this?

**Comment by smblott-github** [comment]
Thanks, @gerrywastaken.  I'm not sure this is of sufficiently-general interest for a whole new command.  It would be something for #1980, if we ever get around to doing that properly.

**Comment by smblott-github** [comment]
See also #2109 and [this comment](https://github.com/philc/vimium/pull/2109#issuecomment-212921117).  The [demo](https://github.com/smblott-github/vimium-external-commands-demo) was in part inspired by this issue.

**Comment by gerrywastaken** [comment]
@smblott-github Oh that's perfect! I love the flexibility. That certainly addresses this issue and others I'll likely encounter as I use vimium more. 👍

**Comment by danielyli** [comment]
“not sure this is of sufficiently-general interest” — well, here’s +1 for this feature

**Comment by dogancelik** [comment]
Implemented in 641378f58002a4c2314a53eae401e26acc46907c, I think this issue can be closed.
