### ISSUE TITLE
Do not support File protocol Page.

### ISSUE THREAD

**Issue by zhanggang807** [philc/vimium#2104]
Like this : 
file:///x:/jdiff-1.1/jdiff-1.1.1/jdiff.html

**Comment by smblott-github** [comment]
Perhaps [this](https://github.com/philc/vimium/wiki/FAQ#how-can-i-use-vimium-on-file-urls)?

**Comment by zhanggang807** [comment]
Oh! Sorry, You are right！ Thank you!
