### ISSUE TITLE
Just switched to chrome

### ISSUE THREAD

**Issue by bitterjug** [philc/vimium#2106]
Just switched to Chrome 50 (from chromium) and despite setting duckduckgo as my default search engine, vomnibar searches use google (whereas chrome omnibar searches use duckduckgo) am I missing a configuration or something?

Vimium: 1.54

```
Google Chrome	50.0.2661.75 (Official Build) (64-bit)
Revision	ffad3c52452e415ab24c9cad1bae22eeb7428092-refs/branch-heads/2661@{#573}
OS	Linux 
Blink	537.36 (@ffad3c52452e415ab24c9cad1bae22eeb7428092)
JavaScript	V8 5.0.71.32
Flash	21.0.0.216
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36
Command Line	/usr/bin/google-chrome-stable --window-depth=24 --flag-switches-begin --flag-switches-end https://plus.google.com/hangouts/_/ytl/sSPRzi9D_lUdy6ElpwS_qOO9PzfepEA5g7ZXjRfjAss=?hl=en_GB&authuser=0
Executable Path	/opt/google/chrome/google-chrome
Profile Path	/home/marks/.config/google-chrome/Default
Variations	92fb4fc2-f23d1dea
6345b824-3d47f4f4
7c1bc906-f55a7974
770a425-f23d1dea
cf5ed6e1-3f4a17df
775ebbd7-3f4a17df
31362330-ca7d8d80
f15c1c09-ca7d8d80
7d382cde-50a9700
9e5c75f1-e1c7cd46
f5dd6118-3d47f4f4
f79cb77b-3d47f4f4
4ea303a6-ecbb250e
4117e878-84bdb43e
9736de91-ca7d8d80
dbffab5d-ca7d8d80
3ac60855-486e2a9c
f296190c-c09932cb
4442aae2-6e3b1976
ed1d377-e1cc0f14
75f0f0a0-6bdfffe7
e2b18481-92bb99a9
e7e71889-4ad60575
b39ea213-d1372334
6ab14220-3f4a17df
9f0ebdd7-3f4a17df
a70306ec-3f4a17df
```

**Comment by smblott-github** [comment]
The Chrome default search engine and the Vimium DSE are different.  You can set it on the (Vimium) options page (under "Advanced", near the bottom).

**Comment by bitterjug** [comment]
Awesome thanks. I missed Advanced options

**Comment by smblott-github** [comment]
Tip (if you're interested)...

Add a custom search engine for DDG:

    d: https://duckduckgo.com/?ia=about&q=%s DuckDuckGo

And add a custom command for it; for example:

    map gs Vomnibar.activate keyword=d

And you should get search completion.

Details [here](https://github.com/philc/vimium/wiki/Search-Completion) and [here](https://github.com/philc/vimium/wiki/Tips-and-Tricks#keyboard-shortcuts-for-custom-search-engines).

**Comment by Powersource** [comment]
Would it be possible to unify this option somehow (what restrictions do we have?), maybe by simply getting the chrome setting or by opening a new tab with the text and chrome maybe figuring out that it should use the default search engine?

**Comment by smblott-github** [comment]
Chrome does not provide an API for accessing the Chrome-configured search engines.

**Comment by bs** [comment]
At the least shouldn't this be under the top level options?

**Comment by sangeet** [comment]
> Would it be possible to unify this option somehow (what restrictions do we have?), maybe by simply getting the chrome setting or by opening a new tab with the text and chrome maybe figuring out that it should use the default search engine?

Hey, I know this is two years old thread, but there actually is a shell script for this very same thing. It finds Chrome's search engine settings and generates text which you can copy over to vimium's advanced settings and have your search engines there.

Leaving this here in case someone comes looking for something similar : https://gist.github.com/philc/e849b48e6c5f32592d62
