### ISSUE TITLE
Problem when navigating Reddit.

### ISSUE THREAD

**Issue by JoelMon** [philc/vimium#2110]
Hello,

When navigating reddit and you press the _f_ key binding it produces shortcuts, for a lack of a better term, that overlap each other. For example, I press _f_ and want to open an article. It would have two shortcuts for the same link, maybe AG and FG. Sometimes the shortcut at the back would be the correct one I need while the one in the front is a dud and doesn't do anything.

I've included a screenshot below of what I'm talking about.

![reddit](https://cloud.githubusercontent.com/assets/6587811/14712741/5ac8eae2-07ac-11e6-8e0b-51f6d77cf240.png)

Thanks

**Comment by smblott-github** [comment]
There's a hint rotation idea that's floating around to address this problem.

However, in the next release there's also a pruning stage for false positives.  It gets rid of most of your problem cases...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/14712939/13d05992-07d7-11e6-8b8b-7d6fd80c3e83.png)
