### ISSUE TITLE
Mapping Multiple commands to a key or Key Combo 

### ISSUE THREAD

**Issue by Sibicoder** [philc/vimium#2115]
Is it possible to map multiple commands to a single key or key combo?
For example, mapping a  single character to move three lines down and delete that line. We would do something like :nmap x  3jyy in vim.
Here, j and yy are two different actions. 
Is there a way to combine multiple actions to a single key?

**Comment by Sibicoder** [comment]
more info

**Comment by smblott-github** [comment]
Thanks, @Sibicoder.

Answer: not currently.  And I'm not sure this is a priority.  It would probably be trickier to implement than you might imagine (because with JS so much happens asynchronously), and it's not clear that there's a compelling use case.

**Comment by NHDaly** [comment]
Hi, not sure this is compelling, but I came here hoping to do this because I wanted to map

map <c-o> goBack
map <c-O> duplicateTab \| goBack

In other words, I wanted <c-O> to do the same thing clicking the back button while holding down Cmd does on a mac, namely: open a new tab with a shared back/forward history and go back in that new tab.

**Comment by shippy** [comment]
Came here for the exact same reason as @NHDaly, but I see how acting on two tabs would be problematic.

**Comment by desgua** [comment]
I too miss this feature.

**Comment by michalakadam** [comment]
+1
I would use this feature for two combos:
- open in new tab + go to this tab (F + gt)
- close current tab and open new one to have cursor placed in browser search bar (x + t)

**Comment by EddieNhat** [comment]
After some trouble, I could do it, but in qutebrowser. Very happy if it were on Vimium!

**Comment by notDavid** [comment]
Just an FYI for macOS users stumbling upon this;

a workaround is to use the [BetterTouchTool](https://folivora.ai/) app to achieve this: create a 'Keyboard trigger' to map 1 key to your 2 (or more) vimium keyboard shortcuts, for the Firefox app. These will then be executed sequentially.

Works perfectly... - note that this shortcut will be executed regardless of vimium's context/even if vimium is not even installed anymore. So pick a unique keyboard shortcut for this, using modifier keys or whatever.

**Comment by allanwind** [comment]
x and ctrl-w does the same thing, so I would like x (or maybe gx) do removeTab; previousTab.
