### ISSUE TITLE
Is it possible to switch scroll area?

### ISSUE THREAD

**Issue by perqin** [philc/vimium#2119]
For example in this page [http://mongoosejs.com/docs/api.html](http://mongoosejs.com/docs/api.html) I can only scroll the main area but unable to scroll the left side content. Is it possible to choose scroll area?

**Comment by smblott-github** [comment]
@perqin... Not currently, but there will be in the next release...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/14893371/02cf9e6a-0d67-11e6-916b-1ffeff5a2920.png)

See also [here](https://github.com/philc/vimium#release-notes).

Closing.  I've tested it on your example page and it works.
