### ISSUE TITLE
False mapping of API invocation

### ISSUE THREAD

**Issue by Edenhofer** [philc/vimium#2121]
Triggering `LinkHints.activateMode` does not open a link in the current tab like the documention suggests, however `LinkHints.activateModeToOpenInNewTab` does. The statement is also true the other way aroung. Both invocations are simply switched in their meaning.

Chrome Version: Linux 50.0.2661.94
Vivaldi Version: 1.1.453.47
Vimium Version: 1.54

**Comment by innaterebel** [comment]
Caps lock? :)

**Comment by Edenhofer** [comment]
To be honest, this was my first thought as well. But after double checking that, I can say for sure that caps lock is turned off.

**Comment by mrmr1993** [comment]
Pressing `<shift>` while typing the link hint characters inverts the mode (so you can decide to open a new tab while already in link hints mode). If you're holding `<shift>`, don't, and the commands should work as expected.

#1928 and #1867 are relevent.

**Comment by Edenhofer** [comment]
Apologies for my stupidity! Thanks @mrmr1993 for the hint. The capital letters next to each link led me to think I needed to press `<shift>`.
