### ISSUE TITLE
compatibility problem with Markticle

### ISSUE THREAD

**Issue by dgeibi** [philc/vimium#2123]
chrome: 52.0.2716.0 dev
vimium: 1.54

I know vimium has a feature for marking, but it is too simple. 
Markticle is a extension which use "M" key to mark.
I have unmapped M, but I can't make Markticle work until I disable vimium.

**Comment by smblott-github** [comment]
Insert mode might help, @dgeibi (`i`).  Then all keys are passed to the page (or another extension) until you hit `Esc`.

**Comment by dgeibi** [comment]
Thanks!
