### ISSUE TITLE
KeyboardEvent.keyIdentifier is deprecated

### ISSUE THREAD

**Issue by lucianoar** [philc/vimium#2128]
'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016.
See [here](https://www.chromestatus.com/features/5316065118650368) for more details.

It must be changed to this:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

https://github.com/philc/vimium/blob/0ddc7a28d17e94296f209d3d8d06357de281e1d1/lib/keyboard_utils.coffee#L35

Chrome version: Chromium - 52.0.2726.0 (Developer Build) (64-bit)
Vimium version: 1.54

**Comment by smblott-github** [comment]
@lucianoar...  I took a look at this: #2133.

**Comment by lucianoar** [comment]
Fixed by #2133
