### ISSUE TITLE
Link to commands.coffee from Readme

### ISSUE THREAD

**Issue by rbalicki2** [philc/vimium#2130]
It is not obvious that the full list of commands is available on commands.coffee. This should be linked from the README.md, or from one of the other readme files. Right now, when I look to create a custom mapping for an obscure gesture, I search the repo for 'activateModeToCopyLinkUrl' and locate commands.coffee.

Happy to make a PR with this.

Thanks! I love vimium and honestly can't browse the web without it.

**Comment by smblott-github** [comment]
Thanks, @rbalicki2.

Actually, there's already a link showing the available commands on the options page:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/15170506/56e2b394-173e-11e6-9f42-0695e3ad71fc.png)


And in the next version, you'll be able to click on command names to copy them to the clipboard.

**Comment by rbalicki2** [comment]
Thanks! I thought that was a partial list.
