### ISSUE TITLE
Add an option to not uppercase letters in LinkHints

### ISSUE THREAD

**Issue by dimonomid** [philc/vimium#2135]
Hi. First of all, thank you very much for your work on Vimium, it's awesome!

There is a rather annoying issue however: as you might expect, I use Vim with EasyMotion plugin, and I trained myself to distinguish between lowercased and uppercased letters. But, vimium always shows uppercased letters, so my fingers keep automatically typing letters while holding the shift key, which results in a different behaviour w.r.t. whether the link should be opened in a new tab. This is distracting and annoying.

I'd be happy if it's possible to add an option not to uppercase the letters in LinkHints. Please, let me know what you're thinking.

Thanks.

**Comment by mrmr1993** [comment]
I think you should be able to use "CSS for link hints" (under advanced options) by adding `text-transform: lowercase;` under `div > .vimiumHintMarker`.

**Comment by dimonomid** [comment]
@mrmr1993, cool, thanks!

Just a little correction: it should be added under `div > .vimiumHintMarker span` to make it work.
