### ISSUE TITLE
Closed tabs re-opening upon relaunching Chrome

### ISSUE THREAD

**Issue by altern8tif** [philc/vimium#2136]
Tabs which were previously closed via `removeTab` are opened again (in the same window) upon Chrome relaunch.  It's usually up to 4-5 previously closed tabs that do that.  Not sure if it's based on timing or number of tabs.

Chrome Version 50.0.2661.102

**Comment by smblott-github** [comment]
Thanks, @altern8tif.  It's not clear that this is a Vimium issue, or that there's anything Vimium could do about it.  All Vimium does is call `chrome.tabs.remove()`: [spec](https://developer.chrome.com/extensions/tabs#method-remove).

**Comment by altern8tif** [comment]
@smblott-github looks like you're right.  Tried it with Vimium disabled and the closed tabs still opens when Chrome launches.  It's probably a Chromium bug.  Thanks.
