### ISSUE TITLE
Vimium stops working when JavaScript is disabled.

### ISSUE THREAD

**Issue by mbwe** [philc/vimium#2137]
Chromium version: Version 50.0.2661.102 (64-bit)
Vimium version: 1.54
OS version: Archlinux(64bit)

Vimium stops working when i disable JavaScript.

**Comment by smblott-github** [comment]
Thanks @mbwe.  Dup of #753.  See there.

(The bottom line: there's not a lot we can do, it seems to be a Chrome bug.)
