### ISSUE TITLE
The first time the help dialog is opened on a page, it flickers

### ISSUE THREAD

**Issue by philc** [philc/vimium#2141]
If you open it again before refreshing the page, it displays smoothly.

**Comment by innaterebel** [comment]
The favicon of the active tab inhabits the same phenomenon when link hint is activated on the page the first time.

**Comment by smblott-github** [comment]
We could fix this by pre-loading the help dialog.  That's what we do with the Vomnibar (to avoid a similar flicker).  However, once a user is familiar with Vimium, they rarely use the help dialog, so we would be doing a lot of work (and using a lot of memory) in every frame for no reason.

A better approach would be to make the help dialog visible only after it is fully rendered.  I'm adding a "Help wanted" label for now.

**Comment by philc** [comment]
I believe this is no longer an issue. The help dialog looks snappy to me.
