### ISSUE TITLE
Space key modifier?

### ISSUE THREAD

**Issue by diego-alvarez-hs** [philc/vimium#2142]
Is it technically possible to add the space key `SPC` modifier?

Something similar to spacemacs.org

**Comment by gdh1995** [comment]
The space key is not a normal modifier key, so it's not easy to remember it and check the next keystoke.

**Comment by smblott-github** [comment]
@diego-alvarez-hs... As @gdh1995 says, the space key is not a modifier.

You can map it, though; e.g.

    map <space>j scrollDown
    map <space>k scrollUp

**Comment by diego-alvarez-hs** [comment]
thanks @smblott-github that's what I was looking for!
