### ISSUE TITLE
Visual line mode key (V) not working in v1.55

### ISSUE THREAD

**Issue by mariomaric** [philc/vimium#2146]
Hi!

After automatic update to v1.55 today, if I press "**V**" key it doesn't invoke anymore Visual line mode.

Workaround is to first invoke visual mode (by pressing "**v**" key), and then press "**V**" key for visual line mode. Is this how it should be or?

I'm using Google Chrome 50.0.2661.102 (Official Build) m (32-bit)

Thanks for all the great work -- this extension is totally irreplaceable and undoubtedly awesome! ;)

Cheers.

**Comment by smblott-github** [comment]
Shoot!  Sorry @mariomaric.

That's a typo by me ....4826d1cf01accf47f71335ce5f93bc51ca556737.

**Comment by mariomaric** [comment]
Hey, no problem at all, thank you for such a quick reponse and fix!
