### ISSUE TITLE
Alt/meta key no longer working

### ISSUE THREAD

**Issue by danielyli** [philc/vimium#2149]
Key bindings that use the alt/meta key worked in 1.54 but now are silently ignored in 1.55.  E.g., I've bound `<a-p>` to the `togglePinTab` command, but pressing `<a-p>` doesn't toggle.

I'm running Chrome 51.0.2704.63 (64-bit)

**Comment by danielyli** [comment]
Seems like if I map `π` (the character that's entered when I press `<a-p>` on a Mac) to `togglePinTab`, it works again.

I'm running OS X 10.11.5 El Capitan.

**Comment by smblott-github** [comment]
Thanks, @danielyli.  I'm guessing this is related to #2147.

**Comment by kelly-apollo** [comment]
+1 for <a-f>

**Comment by smblott-github** [comment]
Closing; probably the same as #2147.

Shout if that's not the case.

**Comment by leoj3n** [comment]
Also related: #2169 and #2161 (which are subsets of #2147 as mentioned above)
