### ISSUE TITLE
Ctrl-f has become scrollUp

### ISSUE THREAD

**Issue by anriseth** [philc/vimium#2151]
The last week Ctrl-f has stopped invoking Find... in Google Chrome, and instead calls scrollUp.
If I disable Vimium, the behaviour disappears.

Google Chrome	51.0.2704.79 (Official Build) (64-bit)
Revision	e300a2fe0cfcf2cc3bb5d753043e73967c33c749-refs/branch-heads/2704@{#690}
OS:	Linux (Ubuntu 16.04)
Vimium: 1.55

**Comment by smblott-github** [comment]
Do you happen to be using a non-standard keyboard layout, @anriseth?  If so, take a look at #2147.

**Comment by anriseth** [comment]
Ah yes, that's the issue. Using Dvorak.

**Comment by hotpxl** [comment]
I'm using Dvorak and I have this problem as well.

Solved by adding
```
unmap <C-y>
```
in the settings.

`y` is the key for `f` on Dvorak.

**Comment by smblott-github** [comment]
@hotpxl could you go [here](http://smblott.org/keyboard.html), enter `<c-y>` and post back here please?  E.g., screenshot.  Do you see the correct `key` for the `keypress` event?

**Comment by hotpxl** [comment]
@smblott-github I'm using a Dvorak layout on a Qwerty hardware keyboard (by `setxkbmap`)

So you want me to enter `<C-y>` in Dvorak or just press the `y` key printed on the keyboard?

**Comment by smblott-github** [comment]
Use the key you would usually use to get a `y`.  I suspect that we see the wrong `key` on the `keydown` event, but the right one on the `keypress` event.  Currently, Vimium uses the `keydown` event.  Hence this issue.

**Comment by hotpxl** [comment]
http://imgur.com/a/UCbPd

I use Dvorak and also have caps lock and control swapped.
I pressed control (marked caps lock on keycap) -> press y (marked t on keycap) -> release y -> release control

**Comment by smblott-github** [comment]
OK, thanks.  So we would have liked to see `y` in the right-hand column, but didn't.  Back to the drawing board.
