### ISSUE TITLE
Facebook steals focus on "load more replies" links

### ISSUE THREAD

**Issue by s0ph0s** [philc/vimium#2153]
Browsing any comment thread on facebook, if you choose to dynamically load more comments from a reply chain, focus is stolen by the resulting reply comment input.

**Comment by leoj3n** [comment]
Do you mean when you click this?
![image](https://cloud.githubusercontent.com/assets/990216/17284620/f27c9bac-5781-11e6-94e3-365c65fc802e.png)

Doesn't focus the comment input for me; nor would I think it was a Vimium "feature" if it did; most likely Facebook's JavaScript doing that at the time when you posted this issue; doesn't seem to do that now.

**Comment by leoj3n** [comment]
Should probably be closed with #1295.

**Comment by s0ph0s** [comment]
I was actually referring to this:
![capture](https://cloud.githubusercontent.com/assets/2958268/17311797/d259a74e-5802-11e6-8bb8-401c144a6c7f.PNG)

But now that you mention it, it is Facebook's javascript auto-focusing the comment box after you click it. Closing out this issue.
