### ISSUE TITLE
disable vimium temporarily

### ISSUE THREAD

**Issue by cptMikky** [philc/vimium#2154]
Hi, I miss a feature to completely disable vimium temporarily.

My specific use case is when I open a remote management console for a server in Chromium and have to edit a file using vim, I'm unable to control it as even if I put vimium to insert mode, the esc key is always caught by vimium before it's propagated to the console in the website, which makes using vim inside a website impossible. 

I'd like to have either a clickable feature to disable vimium via the bar icon or having a special (configurable) non-vim key binding to disable and re-enable vimium.

**Comment by smblott-github** [comment]
Vimium can be disabled temporarily on a site temporarily very quickly:

- Go to `chrome://extensions/`
- at the bottom click "Keyboard shortcuts"
- and set a shortcut for Vimium (I use `Ctrl-Shift-V`).

Now, to disable Vimium: `Ctrl-Shift-V`, `Ctrl-Enter`.

And to re-enable Vimium: `Ctrl-Shift-V`, `Tab`, `Enter`, `Ctrl-Enter`.

It looks complicated written out like that, but it's actually quite natural.

**Comment by innaterebel** [comment]
The "go to `chrome://extensions/` and set a shortcut as you like" part is Chrome's native mechanism to call up an given extension's toolbar popup. **By default the shortcut is not set**.
It should work as long as you have set an applicable shortcut and have **not** set the icon of the extension hidden. If it really doesn't work it most likely a Chromium bug.

The rest part of `Ctrl-Enter` and `Tab`, `Enter`, `Ctrl-Enter` are in fact the actual steps to disable a site in Vimium's toolbar popup.
So yes, the whole process is visually visible, you just have to set the browser shortcut right first.

**Comment by eromoe** [comment]
Shortcut no longer work because : 
![image](https://user-images.githubusercontent.com/3938751/57191092-55448280-6f54-11e9-9e43-be5e6529d072.png)
this is same as click the vimium icon .

I am usually working on jupyter notebook which has its own shortcut conflicted with vimium, vimium would take the charge . However I don't tend to exclude jupyter host , because I like to use vimium for navigation .
So is there any way can disable vimium temporarily ？

**Comment by eromoe** [comment]
Oh, I understood what smblott-github said ...  
`Ctrl-Shift-V` used to click the icon, then use other keys to  `exculde ` and `remove exclude` .
That's not so straight forward . One shortcut `Ctrl-Shift-V` would be nice .

**Comment by yingshaoxo** [comment]
Hey, guys.

Just look this: https://github.com/philc/vimium/wiki/Disabling-Vimium#wholly-disable-vimium-on-a-site

It shows you how to temporary disable vimium.

**Comment by fazlizekiqi** [comment]
The tool is really good but sometimes i would really appreciate if there was a key for disabling that.

**Comment by gdh1995** [comment]
@fazlizekiqi Have you tried the `enterInsertMode` command?
