### ISSUE TITLE
UX Feature: highlight selected link hint

### ISSUE THREAD

**Issue by sesas** [philc/vimium#2155]
Hi there, 

First of all thank you for this extension, it has saved me countless hours of having to switch between keyboard and mouse while surfing the web. 

I sometimes mistype the link hints (after pressing **F**), but because the hints don't linger after being selected I don't know which part of the screen I just 'clicked' on (e.g. "Did I press the submit button or the home link at the top?").

A quick way to solve this would be to have the selected link hint linger a big after selection and have it go through an animation, or be highlighted, bolded, shaken, etc. Anything that catches the eye and that is relatively quick. (don't want to add extra latency for loading the next page) 

A second way to solve this would be deterministic when creating link hints, so that I can go back to the previous page, press **F** and find out which link I pressed (assuming I know how I mistyped the link hint).  Currently this cannot be done because the link hints vary w/ the number of links on the page or other non-visible reasons (afaik).

I don't know if it is possible to create link hints deterministically in a way that they are also ergonomic (I believe Vimium creates an internal order of 'easy to type hits' that it uses in order)

Let me know if the problem described or anything else is clear, and if not I'll add more info.

**Comment by leoj3n** [comment]
Don't you see a highlight around the selection?

![vimium](https://cloud.githubusercontent.com/assets/990216/17284500/d57b66ec-5780-11e6-8ed0-11afa40b012c.gif)

If it's really that big of a deal to you, it's probably something you could accomplish in a separate plugin with the help of the message passing proposed in #2109.

Alternatively you could make the element focus animation more obnoxious along the lines of http://n12v.com/focus-transition-2/

**Comment by smblott-github** [comment]
It would be possible to add a delay (to ensure that the blue flash is visible).  However, that would likely annoy more users than it would please.

Closing.
