### ISSUE TITLE
Mark feature could be extended to work across tabs

### ISSUE THREAD

**Issue by harshayburadkar** [philc/vimium#2158]
Essentially then if you are working with few different tabs you could actually mark positions on those tabs at the proper scroll level and voila. 

For e.g. I would like to mark the keys 1 2 3 4 to my four tabs that I am using frequently. It could be a lot of productivity gain.

**Comment by smblott-github** [comment]
Do global marks (with capital letters) not meet your needs, @harshayburadkar?

Separately, the observation that the number keys have no meaning in marks mode is interesting.

**Comment by harshayburadkar** [comment]
Great that it's there. Would highly recommend to have it in the /? help. This could be one of my prime shortcuts if I can make it a little easier to use using some customization of keys.

On a separate note, I do find it a bit difficult to use and since it mandates capital letter, it adds a extra Shift key which is a bit difficult to press.

**Comment by smblott-github** [comment]
> On a separate note, I do find it a bit difficult to use and since it mandates capital letter, it adds an extra Shift key which is a bit difficult to press quickly.

On my live installation, I swap capital and lower-case marks (global marks are just way more useful for me).  However, it's probably unlikely that we'd actually make any change to the status quo (including adding an option).
