### ISSUE TITLE
Keybinding question

### ISSUE THREAD

**Issue by Daan-B** [philc/vimium#2160]
Hello,

I am well aware that a question like this doesn't belong in an issue tracker, but I could'nt fing another place to ask it.

When Vomnimbar is opened you start typing and can then go down to select a website with the down arrow key. Is there a way that I can change this to Ctrl+j? Or is there a better way to go through the vomnibar results?

**Comment by smblott-github** [comment]
`Ctrl-j` should work already.

But, to answer your question... No, there's no way to change it.

**Comment by Daan-B** [comment]
It works indeed. Another shortcut for my window manager messed it up. Than you very much
