### ISSUE TITLE
Pinning tab <a-p> seems to be broken in the latest release

### ISSUE THREAD

**Issue by agzam** [philc/vimium#2161]
It used to work, somehow stopped (?)

**Comment by 0mp** [comment]
It doesn't work for me as well.

I cannot pin tabs in Google Chrome on OS X. It works in Chromium on Linux though.

**Comment by smblott-github** [comment]
@agzam, @0mp... Could you go [here](http://smblott.org/keyboard.html), hit `Alt-p` and report back the result, please.  Disable Vimium on that page first, of course.

**Comment by 0mp** [comment]
I just entered the webpage and hit <kbd>alt</kbd>+<kbd>p</kbd>. This is what I got:

|`evt:`|`which:`|`keyCode:`|`charCode:`|`modifier:`|`keyIdentifier:`|`key:`|
|---|---|---|---|---|---|---|
|keyup|80|80|0|alt|undefined|Ļ|Ļ|
|keypress|315|315|315|alt|undefined|Ļ|Ļ|
|keydown|80|80|0|alt|undefined|Ļ|Ļ|
|keydown|18|18|0|alt|undefined|Alt|Alt|
```

**Comment by smblott-github** [comment]
@0mp ... thanks!  That's helpful.  This is looking like the same as #2147.

I'm assuming you're using Vimium 1.56:

- What Chrome versions (Mac and Linux).
- Is the `keyIdentifier` property defined when you try the test page on Linux (I'm guessing yes).

**Comment by 0mp** [comment]
@smblott-github 

#### Linux

- Chromium
- Version 51.0.2704.79 Built on 8.4, running on Debian 8.5

|evt:|which:|keyCode:|charCode:|modifier:|keyIdentifier:|key:|
|---|---|---|---|---|---|---|---|
|keyup|18|18|0|undefined|Alt|Alt|
|keydown|18|18|0|alt|undefined|Alt|Alt|

I'll update this comment in a minute with the information about OS X.

**Comment by smblott-github** [comment]
Here's what I get...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/16068112/0cb00928-32bb-11e6-8ced-7a7de2162211.png)

(Chrome 51.0.2704.63, Debian).  Here, Vimium uses the second `keydown` event (reading bottom to top), and uses the `keyIdentifier` property.  In your case, @0mp, Vimium would use the `key` property.  However, there seems to be issues with Chromium's `.key` implementation; see #2147.  I suspect that's what you're seeing, in which case it's a Chromium bug.

**Comment by wcpines** [comment]
Any suggested work-around?

**Comment by antoniocapelo** [comment]
Yes, a work around would be good, pinning tabs from the keyboard is super handy :)

**Comment by smblott-github** [comment]
I don't use that binding myself (I find it clunky).  I prefer:

    unmap <a-p>
    map gp togglePinTab

**Comment by antoniocapelo** [comment]
@smblott-github that works, I'll go with that for now, thanks!

**Comment by wcpines** [comment]
@smblott-github that is beautiful.  Thank you for the suggestion.

**Comment by arcaartem** [comment]
Just tried it. It's weird but apparently I can use <alt-p> to type a `π` (Pi) sign after the `map` command, and the shortcut would work as expected (I'm on Mac OS, Chrome 51)

For example:

```
unmap <a-p>
map π togglePinTab
```

**Comment by leoj3n** [comment]
Related to #2169

**Comment by Nesze** [comment]
I have the workaround in my config, but recently something must have changed as it does not work anymore.

Chrome: `Version 61.0.3163.91 (Official Build) (64-bit)`
Vimium: `1.60.3`

Custom mapping:
```
unmap <a-p>
map π togglePinTab
```

Has the problem come back for anyone else as well, or is it just me?

**Comment by arcaartem** [comment]
Yeah, just tried and I can't use those shortcuts anymore.

**Comment by agzam** [comment]
@Nesze 
unmap <a-p>
map gp togglePinTab

still works for me

**Comment by mrmr1993** [comment]
@nesze We've moved to a new key handling method now Chrome is depreciating the old one. It's generally much better, but it doesn't tell us which modifier keys do or don't contribute to the resulting character, so we can't distinguish eg. pressing `alt` and a `π` key from pressing a combo including `alt` that generates `π`.

Does the binding work if you explicitly include the modifiers you have to press (presumably `<a-π>`)?

**Comment by mrmr1993** [comment]
@smblott-github do you think it would be worth including a different notation for using `en_US` for a single binding (eg. `<@a-p>`), now you've built support for it? This would certainly remove a lot of friction for users of different keyboard layouts if we used them for the default binding.

(I'm more than happy to work on this is it's of interest.)

**Comment by Nesze** [comment]
@mrmr1993 I can confirm that setting the mapping key to `<a-π>` does the fix. Thank you!

**Comment by smblott-github** [comment]
> @smblott-github do you think it would be worth including a different notation for using en_US...

Not too keen on that, myself.  It could add complexity for little gain.

**Comment by orschiro** [comment]
Was facing the same problem on my Mac, thanks @atsalolikhin-spokeo !

**Comment by pascowl** [comment]
I can confirm that this simple custom mapping worked for me too. 🥳

```
unmap <a-p>
map <ap> togglePinTab
```

**Comment by pascowl** [comment]
I can confirm that this simple custom mapping worked for me too. 🥳

```
unmap <a-p>
map ap togglePinTab
```
