### ISSUE TITLE
Highlight all matches in find

### ISSUE THREAD

**Issue by gibm** [philc/vimium#2162]
Currently the find in vimium highlights the current match (in orange):

![image](https://cloud.githubusercontent.com/assets/9949336/16046846/c14c7784-3245-11e6-9812-681e0882a1e3.png)

It would be great if it could also highlight the other matches on the page, the way the built-in find does in Chrome:

![image](https://cloud.githubusercontent.com/assets/9949336/16046820/ac70aef2-3245-11e6-9dfe-1b62280aa92a.png)

**Comment by wcpines** [comment]
+1

**Comment by Alok** [comment]
Chromium-vim has this feature, so I'm curious to see it in vimium.

**Comment by leoj3n** [comment]
I think I remember something about performance concerns in a previous issue/request.

**Comment by smblott-github** [comment]
This would require a fairly major rewrite of the "find" code (for fairly limited benefit) - and might raise performance issues, as @leoj3n says.

Currently, we just use `window.find()` and let Chrome do the work.  Chrome does not provide an API for using it's built in find feature.
