### ISSUE TITLE
Link hints disappear after opening a link in background

### ISSUE THREAD

**Issue by mallove** [philc/vimium#2165]
Until recently, link hints used to stay rendered on the page, which allowed for multiple links to be opened in the background (without having to press `F` twice).  It seems they are now disappearing after one link is opened.

**Comment by smblott-github** [comment]
The behaviour you describe is the normal and the established behaviour, @mallove.

To open multiple multiple links, try either:

    map F LinkHints.activateModeWithQueue

or:

    map F LinkHints.activateModeToOpenInNewForegroundTab count=999

**Comment by mallove** [comment]
Perfect.  Sorry for the bogus ticket!
