### ISSUE TITLE
Vimium doesn't work on chrome tabs

### ISSUE THREAD

**Issue by dkrieger** [philc/vimium#2167]
Vimium doesn't work on Chrome tabs
============================
Examples:
--------------
- Sign in tab
- New blank tab
- chrome://version/

Version:
-----------
- Chrome: 51.0.2704.84
- OS: Linux Mint 17.3 "Rosa"
- Vimium: 1.56

**Comment by mrkishi** [comment]
A possible solution is currently being discussed in #2152.

**Comment by smblott-github** [comment]
@dkrieger.  Chrome just doesn't run extensions' JavaScript on those pages, so there's nothing Vimium can do about it.  (#2152 addresses only a small part of the deficiency.)

This can not be fixed.
