### ISSUE TITLE
How to use <a-f> in mac

### ISSUE THREAD

**Issue by whcn** [philc/vimium#2169]
Hello, just as title said, i'd like to use < a-p > and < a-f > in mac osx, how should i do?

**Comment by smblott-github** [comment]
Thanks, @whcn.  I suspect this is a dup of #2147.

(Closing for now; shout if that's not right.)

**Comment by arcaartem** [comment]
As a workaround, I redefined the key mapping by entering `<alt-f>` on the keyboard to type a `ƒ` sign after the map command. It's weird but it works for me (I'm on Mac OS, Chrome 51):

```
unmap <a-f>
map ƒ LinkHints.activateModeWithQueue
```

**Comment by whcn** [comment]
Thank you very much, this problem have troubled me for a long time

**Comment by kbdluv** [comment]
As for `<a-p>`, this fixed it for me:

https://github.com/philc/vimium/issues/2161#issuecomment-330984319

```
unmap <a-p>
map <a-π> togglePinTab
```

It bothers me that a workaround is needed for each Alt/Option keybinding though. It doesn't scale in case Vimium adds more of those. Hopefully a general solution for MacOS can be found.

**Comment by 8tq** [comment]
In reply to @arcaartem's comment above:

Wonderful thanks so much, this has been extremely helpful. However it didn't work for me, so I modified it by removing the `unmap` line and following the format of the second line @kbdluv 's comment above:

    map <a-ƒ> LinkHints.activateModeWithQueue

**Comment by jamesguo71** [comment]
It's really weird. I met the same problem. You guys' workarounds work wonderful. But now I am super curious what things happened that led to this (inelegant) workaround .

**Comment by srgsanky** [comment]
In Mac, when the alt key is held, most of the keys output an alternate symbol. For e.g. alt + p will output the symbol pi. You can view the list of all symbols from keyboard viewer provided by Mac. Hold alt and the keyboard viewer will show the alternate symbol.

<img width="636" alt="Screenshot 2024-10-05 at 11 49 32" src="https://github.com/user-attachments/assets/202fbf03-601b-4cf0-926f-dae4e1c8c2a3">

I couldn't find a way to turn off this behavior. So if we remap all alt based shortcuts to use the alternate symbol, it will work in Vimium.

```
map <a-ƒ> LinkHints.activateModeWithQueue
map <a-π> togglePinTab
map <a-µ> toggleMuteTab
```

Reference on keyboard viewer: https://www.reddit.com/r/MacOS/comments/152njki/why_does_option_p_no_longer_give_me_pi/
