### ISSUE TITLE
how to add a bookmark in vimium?

### ISSUE THREAD

**Issue by cmal** [philc/vimium#2178]
how to add a bookmark in vimium? thanks

**Comment by intre4si32** [comment]
Why did you closed it? Solved? I am looking for the answer to this

**Comment by smblott-github** [comment]
There's no Vimium shortcut for this, but you can always use the native Chrome shortcut (for me that's `Ctrl-d`.

**Comment by cmal** [comment]
Thanks.

**Comment by pscofield** [comment]
The limitation with chrome shortcut (`cmd-d`) is that you can't select the folder you want to put the bookmark in. You need to use the mouse for that dropdown.

I imagine an experience of this sort through Vimium:
1. Press the key (`c-b` or something).
2. A dropdown (like the `O` shortcut appears) and you can search through your folders with the default folder already being selected.
3. So the default experience remains the same whether you use chrome default, or vimium key; BUT now you can conveniently search through the folders, and select without mouse.

WDYT about this?

**Comment by pscofield** [comment]
In Mac, the focus doesn't leave the textbox for Bookmark name. `Tab` doesn't do that either. Even if that worked, we still have the searchability problem.
