### ISSUE TITLE
Is there a way to get google search completion in the vomnibar?

### ISSUE THREAD

**Issue by nkmathew** [philc/vimium#2182]
Or alternatively a way to take focus to the omnibar with a single character command instead of Ctrl+L. VimFx has this feature

**Comment by mrmr1993** [comment]
You can add a custom search engine for google (eg. for queries starting `g `) in the options page. #1687 has some brief justification on why this was not added by default.

> Or alternatively a way to take focus to the omnibar with a single character command instead of Ctrl+L. VimFx has this feature

This is not possible due to chrome limitations.

**Comment by nkmathew** [comment]
Ok, thanks. Btw, can we have gitter for this repo? For little questions like this

**Comment by smblott-github** [comment]
Info on [search completion](https://github.com/philc/vimium/wiki/Search-Completion).

Info on [mapping keys](https://github.com/philc/vimium/wiki/Tips-and-Tricks#keyboard-shortcuts-for-custom-search-engines) to custom search engines.
