### ISSUE TITLE
Can't type [ in input fields

### ISSUE THREAD

**Issue by Styrke** [philc/vimium#2187]
Hi.

I can't type **[** in any input fields. Instead when I try, the input field that I am typing in looses focus.

I can type the character correctly in other programs and copy it into the input fields in the browser when I need it. I can use the `]]` command from Vimium to go to the next page, but `[[` doesn't seem to do anything.

If I disable the Vimium extension or add a rule to exclude all keys (by leaving the "keys" field blank) I can type [ again without problems.

I am using a danish keyboard on Windows 10.

Vimium version: 1.56
Chrome version: 51

**Comment by smblott-github** [comment]
Ouch.  That's pretty nasty.

Do you press `Ctrl` to enter `[`?  Vimium treats `Ctrl-[` as `Escape`.

**Comment by Styrke** [comment]
Hi @smblott-github, thanks for responding!

No, I don't use `ctrl` for typing `[`.

When I want to type `[`, I usually hold the `Alt Gr` key to the right of the space bar while pressing the `8` key. You can see the typical danish keyboard layout I'm using here:

![My keyboard layout](http://fontmeme.com/images/danish-keyboard-550x183.png)

**Comment by smblott-github** [comment]
According to [here](http://stackoverflow.com/questions/10657346/detect-alt-gr-alt-graph-modifier-on-key-press), `Alt Gr` sets `ctrlKey` and `altKey`. #2215 should fix this (#2215 will merge soon).

**Comment by oskarkv** [comment]
I have the same issue. I type [ by AltGr+F. Please hurry, it's super annoying.

**Comment by smblott-github** [comment]
#2215 has been merged.  This should be fixed.  Closing this.

**Comment by Styrke** [comment]
I just got the update and can confirm that the problem is solved for me now. Thanks a lot! 🎉

[[[ 👍
