### ISSUE TITLE
Extension stops working when page content is replaced by extensions

### ISSUE THREAD

**Issue by Zyst** [philc/vimium#2190]
I use a reading extension (Namely the now defunct [Clearly](https://help.evernote.com/hc/en-us/articles/212952747-Discontinued-support-for-Clearly)) although I also tried using [Just Read](https://chrome.google.com/webstore/detail/just-read/dgmanlpmmkibanfdgjocnabmcaclkmod?hl=en), and that doesn't work either.

Basically these extensions make the current page more readable, they are very useful all around for reading online. I recently installed Vimium, but sadly when you enter the reading mode with either of the extensions Vimium completely stops working, none of the hotkeys work, help doesn't work, it's just like not having it installed at all. All of the Chrome-native hotkeys still work.

I figure the page state change might be what destroys the extension functionality, but I am nowhere near familiar enough with Vimium to be of real help debugging it. It could also be that both of those extensions somehow intercept all key presses to handle events (Escape in particular closes the article in both so that might be it, found [here](https://github.com/ZachSaucier/Just-Read/blob/master/content_script.js#L80) + [here](https://github.com/ZachSaucier/Just-Read/blob/master/content_script.js#L167) in Just Read, would this break it?), but if it is something on Vimiums' side having it fixed would be awesome.

EDIT: Vimium also doesn't work after pressing escape in either extension and returning to the normal website interface, however refreshing makes Vimium work again.

**Comment by smblott-github** [comment]
I'm guessing that clearly Creates an iframe with a `chrome-extension:` URL (or something like that).  Chrome does not run other extensions within such frames.  There's probably nothing we can do about this.

**Comment by Zyst** [comment]
You are right, it does make a `chrome-extension:` iframe:

```html
<iframe id="evernote_clearly__reformat" frameborder="0" allowtransparency="true" scrolling="auto" src="chrome-extension://iooicodkiihhpojmmeghjclgihfjdjhj/front/in_isolation/reformat.html" style="top: 0px; left: 0px;">
    (Content)
</iframe>
```

It's a shame that nothing can be done about it. But this issue should be considered closed with this @smblott-github
