### ISSUE TITLE
Feature Request: UTF-8 support

### ISSUE THREAD

**Issue by Altantur** [philc/vimium#2199]
Hi there, I have been using vimium for last couple of years. I love it!

Only problem is changing the keyboard language layout vimium stopped working.

Is it possible to implement for chrome extension? If Yes where should look first.

I believe there is many non-english users out there.

Thank you.

**Comment by smblott-github** [comment]
Could you be more specific about what doesn't work?  You can map your own keys on the options page, see examples [here](https://github.com/philc/vimium/wiki/Key-Mappings).

**Comment by Altantur** [comment]
Oh my bad, I could use it in my language(mongolian) now. Can I add my language layout to vimium?

Thank you.

**Comment by smblott-github** [comment]
Sure, if you produce a reasonably complete Mongolian mapping, then go ahead and add it to the [wiki](https://github.com/philc/vimium/wiki/Key-Mappings).
