### ISSUE TITLE
After copy in visual mode, doesn't change to caret mode again

### ISSUE THREAD

**Issue by proggga** [philc/vimium#2200]
If I select text, and copy it by 'y', after pressing again 'v' I work in visual mode, not in caret mode
I can move start cursor to other part of page
Thanks you very much, pls help if I do it wrong
Sorry for my english

**Comment by innaterebel** [comment]
https://github.com/philc/vimium/wiki/Visual-Mode
> `v` and `c` can be used to move back and forward between visual and caret modes.

**Comment by proggga** [comment]
Thanks you very much, It hard to find any information about it
