### ISSUE TITLE
Selected text steals the cursor

### ISSUE THREAD

**Issue by kungpaocow** [philc/vimium#2201]
I noticed that when I'm using Vimium to switch between tabs if I come across a tab that has A Google Doc open, it starts typing in the Google Doc and there is no way to escape without using the mouse. 

Is there an option to get out of this using Vimium's keys?

**Comment by leoj3n** [comment]
I wrote a script as part of an extension to deselect focus of input when focusing any tab... I'll see if I can find the code and post it here (it's a very small snippet to the effect of window.focus)

**Comment by leoj3n** [comment]
OK, I was close; it actually blurs all inputs when switching to a different tab, but you could modify it to basically do the reverse and then limit it to specific domains in a manifest.

https://github.com/leoj3n/content-scripts/blob/master/app/sites/global/global.js

**Comment by smblott-github** [comment]
I'll close this.  We probably wouldn't add an option for this, nor would we make the requested behaviour the default.  This is something that could be handled by another extension (or a TamperMonkey script).

**Comment by kungpaocow** [comment]
Thanks for looking into this. I'll try your suggestions.
