### ISSUE TITLE
Vimperator convert help needed

### ISSUE THREAD

**Issue by jflorian** [philc/vimium#2205]
I am very new to chromium and thus vimium but I had too many 2-minute freezes with firefox+vimperator despite new profiles, etc. that I just couldn't live with it anymore.  Now I'm having to retrain myself.  I find it annoying that vimium is disabled on chrome::// pages, but I get the gist and sadly have to agree it's correct behavior.  However, there are other things maybe longtime users can help me with:

1. Most missed feature is the equivalent of "set complete=slbfS" to set the completion search order.  Is there anything equivalent for the vomnibar?  It seems to almost completely ignore my bookmarks.  Any trick for providing an equivalent for keywords?

2. I have muscle memory for y=yank URL and find yy annoying.  Is there any other use for y, if not why make this unnecessarily cumbersome?  Can I remap myself happy?

3.  Likewise, I really miss t=:tabopen bla bla bla.  I have the New Tab URL extension which helps a bit, but t and T seem backwards to me.  What good is a new tab without an URL?  With vimperator, t prompted for something (be it URL, search engine, keyword, bookmark, etc.) and T did the same but provided a default of the prior tab's URL ready to edit, or as I used it, to fork my browsing history.  Any way to get something similar from vimium?

Please don't take any of this as criticism, but rather an old dog trying to relearn his old tricks on a new course.  I'm really glad vimium exists because I couldn't bear to use chromium without it.

**Comment by innaterebel** [comment]
Take a look at the [readme.md](https://github.com/philc/vimium/blob/539cc1969f173171a21bc659f700a317d6f8dc4d/README.md) should answer half of your question, and [commands.coffee](https://github.com/philc/vimium/blob/539cc1969f173171a21bc659f700a317d6f8dc4d/background_scripts/commands.coffee) for all available commands.
You may want to just `unmapAll` as it seems you have quite a different practice from the defaults of Vimium.

Sorry this is the best I can offer, I am just another casual user. The contributors of this project have gone total missing in the past month.

**Comment by jflorian** [comment]
@innaterebel Thanks for the info.  I had already looked through the readme and didn't feel it really answered my Qs, which is why I asked them here.  Anyway, I've since discovered cVim and find it more to my liking so far.
