### ISSUE TITLE
"Custom key mappings" does not work.

### ISSUE THREAD

**Issue by scb20100708** [philc/vimium#2207]
The  chrome version I using is 52.0.2743.82－32 bit.
I want to make pressing "backspace" in the keyboard to go back in history，just like press "H".
So I add a rule--map backSpace goBack.
But It does not work.
So What's the right rule?
Can you help me?

**Comment by gdh1995** [comment]
No, there isn't. Now Those supported are only: `left`, `up`, `right`, `down`, `space`, and `F1` to `F12`, according to `lib/keyboard_utils.coffee`.

**Comment by scb20100708** [comment]
I have read the file--lib/keyboard_utils.coffee and find that @gdh1995  are right .Thanks @gdh1995 .

**Comment by gaving** [comment]
I can see this being a huge feature request now that Chrome 52's removed the binding with no configuration option.

**Comment by smblott-github** [comment]
Google have published [this](https://chrome.google.com/webstore/detail/go-back-with-backspace/eekailopagacbcdloonjhbiecobagjci), which might help.
