### ISSUE TITLE
scrollFullPageUP & scrollFullPageDown, a bug?

### ISSUE THREAD

**Issue by akokak** [philc/vimium#2209]
hi, 
thanks for you works! I have used vimium for years. I like it , and I love it.

I found a bug: When i use the "scrollFullPageDown" function, on some web pages, it will scroll a full page down, but scroll down more ONE or Two lines. the scrollfullPageUp is the same, will scroll full page up, but will scroll up more one or two lines. So I would miss some lines to reading.

chrome's hot keys: Space and Shift+Space. when I press "space" , the web page will scroll a full page down, but will reserve One line(I have read) on the top of the screen. the shift+space is the same, reserve one line(I have read) on the bottom of the screen.

please,

let scrollFullPageUP = (shift+space)

and

let scrollFullPageDown = space

and who can give me a way to do that ?

thanks, again.

**Comment by smblott-github** [comment]
Closing. This was also posted elsewhere.
