### ISSUE TITLE
vimium does not work in built-in page

### ISSUE THREAD

**Issue by zhouyangnk** [philc/vimium#2211]
Hi.
vimium does not work in chrome's built-in page, like newtab page or settings page.
how can I fix it?
Thanks!

refer to #2090

**Comment by innaterebel** [comment]
For security reasons, no extension is allowed on internal pages, by design of Chrome.

**Comment by zhouyangnk** [comment]
Thanks for reply. 
I know this reason, but I found "Enable Experimental Extension APIs" and "Enable Extensions on chrome:// URLs" in chrome://flags. 
Is there a way to use these options to achieve my intention?

**Comment by innaterebel** [comment]
Unfortunately, no. Please kindly refer to #2090.
