### ISSUE TITLE
How do I assign 'backspace' to goBack?

### ISSUE THREAD

**Issue by rikkilake** [philc/vimium#2214]
Hello,

In it's on-going power trip Google Chrome in an overnight update has stopped my backspace being used as Go Back... this shortcut has been around since the year dot.  Idiots!

How can I correctly map this key?  Thank you.

PS. Yes, I've looked at the Wiki, but cannot find any information on how to do this.

**Comment by gdh1995** [comment]
#2207 also mentioned this. Vimium hasn't supported mapping `backspace` now.

**Comment by jaekyeom** [comment]
How about using [this](https://chrome.google.com/webstore/detail/go-back-with-backspace/eekailopagacbcdloonjhbiecobagjci)?

**Comment by gdh1995** [comment]
> How about using this?

So I've written a PR to implement mapping `<backspace>`, which borrows some code from the extension `Go Back With Backspace`.

**Comment by smblott-github** [comment]
What @jaekyeom said (and I'll take a look at #2223 soon).

**Comment by iahu** [comment]
+1
