### ISSUE TITLE
Vimium's History is not always in sync with Chrome's chrome://history/

### ISSUE THREAD

**Issue by AlexIvasi** [philc/vimium#2216]
O = Open URL, bookmark or history entry
Doesn't list all history items available in Chrome's native History page i.e. chrome://history/ - that issue is sporadic. Observation is observed in the same Google Account instance / search test is performed based on URL and Title - both fails to return results for some URL's.

What setting governs history sync / search / or are there parameters to control the history?

Thank you.

**Comment by gdh1995** [comment]
On the first time Vomnibar is open, Vimium will pull up to 20000 history items from Chrome, and get a list each item in which has a unique url. And then, Vimium will listen history changes and insert/update new items into the list.

The first issues is that the Chrome API `chrome.history.search` may filter out some special urls, which mainly includes `chrome://` ones. And the second problem is that:
* if you visit one url for the first time, the API `chrome.history.onVisited` will reports this action at once.
* so Vimium receives a new history item with an empty `title` the moment at which Chrome doesn't know the page's title, neither.
* therefore, Vimium will know more and more new history items with empty titles, and one item's title keeps empty until you refresh the page and generate a new history item of the same url.

These're why Vimium has a history list containing different (less) info compared with Chrome's.

**Comment by AlexIvasi** [comment]
Hi Dahan, 

Appreciated your detailed explanation!
have a great day.
