### ISSUE TITLE
Idea: making yellow hints more predictable

### ISSUE THREAD

**Issue by JAStanton** [philc/vimium#2219]
Hey so I've been using Vimium all of 1 hour now. So please excuse my ignorance.

When searching for a link to click on (`Shift + F`) it would make me much faster if the yellow tags were more predictable. Instead of being assigned an incrementing letter combination for every link on the page what if we prioritized buttons with text by using the first few letters in the button. For example on this submit issues page there is a giant green button that says "Submit new Issue". When I'm done typing I could `Shift + F` and intuitively know that most likely situation is that the yellow text will most likely start with "SU" for "**su**bmit". 

Just thinking out loud, I don't know how usable this would actually be, or if I would actually like it until I started using it for a while. Has anyone else thought of this? 

Thanks!
- Jonathan

**Comment by sco-tt** [comment]
Try out the option 'Use the link's name and numbers for link-hint filtering' in Vimium options.

**Comment by smblott-github** [comment]
I haven't yet seen a good idea for *making hints predictable*.  I think it's hard.

Ass @sco-tt said, with filtered hints you know what to type before hitting `f`.
