### ISSUE TITLE
Remove focus from search bar

### ISSUE THREAD

**Issue by shubhiD** [philc/vimium#2226]
If the focus is on search bar then it gets difficult to shift the focus back on page thus I would request to add a key binding of ESC key to toggle focus between page and address bar. Currently it is F6 to toggle the focus in chrome

**Comment by smblott-github** [comment]
Thanks, @shubhiD.  Unfortunately, though, there's no Chrome API for doing that.

**Comment by chuan137** [comment]
I think you can type Tab and click 'Skip to content', maybe combining both and creating a shortcut will do the job?

**Comment by shubhiD** [comment]
Pressing tab is working fine now previously it was taking me to the bookmark bar
