### ISSUE TITLE
(Open a link) User experience mismatch with the user guide.

### ISSUE THREAD

**Issue by HavenYang** [philc/vimium#2239]
The user guide (Vimium help) said:

```
f. Open a link in the current tab	
F. Open a link in a new tab
```

But when i use it, the truth was

```
F. Open a link in the current tab	
f. Open a link in a new tab
```

I'm using Chrome, version 53.0.2785.89

**Comment by smblott-github** [comment]
Are you holding down the `Shift` key while typing the hint characters?

**Comment by vyp** [comment]
Or maybe caps lock is accidentally enabled?

**Comment by HavenYang** [comment]
@smblott-github 
Yes, I'm holding down the `Shift` since the hint characters shown capital.

**Comment by smblott-github** [comment]
Just don't hold `Shift` (obviously).

`Shift` toggles the link-hint behaviour.  Some (including me) would like to drop that feature because it seems to cause a considerable amount of confusion.  Alternatively, we could show the hints in lower case.

**Comment by HavenYang** [comment]
Yeah it make me confuse, show the hints in lower case is a better way.
Thank you for your explaintation.
