### ISSUE TITLE
Why vimium is not preloaded?

### ISSUE THREAD

**Issue by shubhiD** [philc/vimium#2240]
Why vimium needs internet to be loaded everytime? So if the internet connection drops in between then we dont have vimium controls to play with. Is it chrome policy or am I missing something?

**Comment by smblott-github** [comment]
That is not the behaviour I see:

- Turn off my network connection.
- Load a `file://` URL.
- Vimium works just fine.

**Comment by shubhiD** [comment]
In my case if my net connection turns off in middle of loading a page then vimium doesn't works or if i open a new tab while my net is off. Strange if you don't have this issue. What it could be?

**Comment by gdh1995** [comment]
If a page is loading but the connection turns off, then Chrome may "disable" the whole page - that is, a previous snapshot of partly downloaded page is shown, but you can not do anything on the page, except going to another page or reloading.

**Comment by shubhiD** [comment]
@gdh1995 Then it means vimium is to be reloaded and requires internet connection? Can't we preload it? I have no such issue while using vimfx on firefox. Is the issue related to chrome then?

**Comment by gdh1995** [comment]
Have you tested a `file:///...` page and did Vimium work on that?

What I metioned above is a special edge case: Chrome prevents all javascript and native interactions on such pages, although the page's snapshot is still showing on the screen, and then we have no method to interact with the page.

Another more common case is that Chrome throws the old page snapshot and shows a inner error page to tell you "Connection Reset / Aborted / You address has changed / ...", and this kind of error pages are strictly protected by Chrome - no extension can run on it.

**Comment by shubhiD** [comment]
@gdh1995 Yes you are right vimium does work on `file:///... ` and not on the error pages thrown by chrome

**Comment by gdh1995** [comment]
Then there's no way to run extension commands except using a Chrome's API named `chrome.commands`, which is designed to add (at most 4) global shortcuts to Chrome.
See #2152 for more discussions.

**Comment by shubhiD** [comment]
Okay thanks for the information
