### ISSUE TITLE
Does Vimium have an opinion on the future of Coffeescript?

### ISSUE THREAD

**Issue by greghuc** [philc/vimium#2245]
Hi guys,

A quick heads up that there's a pretty active discussion going on over at [coffeescript6/discuss](https://github.com/coffeescript6/discuss) about possible next steps for Coffeescript.

Thought you might want to comment, given Vimium is a heavy Coffeescript user. Discussed issues are [here](https://github.com/coffeescript6/discuss/issues).

There's also a survey that's relevant to you: [Survey for devs/teams with maintained Coffescript codebases: happy with CS, or considering migrating?](https://github.com/coffeescript6/discuss/issues/32)

**Comment by smblott-github** [comment]
> e.g. via decaffeinate

I tried this a good while ago, and it was riddled with errors.  Maybe it's better now.
