### ISSUE TITLE
[feature-request] Skip [F] and [FX] labels when in 'f' or 'F' mode

### ISSUE THREAD

**Issue by cwkx** [philc/vimium#2246]
As a new user, when i'm viewing labels in 'f' or 'F' mode I often by mistake click 'f' again intending to cancel, only to go to some random link, whereas what I meant to do was press escape or backsapce to cancel the 'f' mode. 

I think it would be much better if 'F' as well as 'FX' labels were removed from the alphabet, and then make it such that pressing 'f' has the same effect as pressing escape if the labels are open. Labels such as 'AF' would still be good.

**Comment by smblott-github** [comment]
On the options page, under *Advanced Options*, remove `f` from the list of link-hint characters:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/18415341/255d3b4c-77e6-11e6-8c40-b65b9212bea1.png)

That should have the effect you want.

**Comment by cwkx** [comment]
That's awesome thanks, I didn't even know there were advanced options. I think 'f' should be removed by default but otherwise fantastic, thanks.
