### ISSUE TITLE
(Question) Is there a way to disable 2j faster scroll?

### ISSUE THREAD

**Issue by DavidLGoldberg** [philc/vimium#2247]
I just installed the new version and was really confused with my j,k scrolling.

I think it's the note about 2j mapping to a faster scroll?

I'd really like to turn this off as it's confusing to me.  The old way was perfect for me.

(HUGE lover of vimium btw)

**Comment by smblott-github** [comment]
The direct answer to your question is "No".

But what do you want `2j` to mean?  If you just tap the `j`, then `2j` takes you to the same place as `j`, `j`.

**Comment by DavidLGoldberg** [comment]
Hmm.  Very sorry, I should have been much clearer.  I'm not actually entering:

<key>2</key><key>j</key>
or:
<key>2</key><key>k</key>

Actually, it's more like when I let go of j or k for a second or so, and press them again, instead of line scrolling, I seem to be getting large jumps/jolts the size of page downs.

I'm running this on Chrome Canary btw.  An older vimium + Chrome used to do scrolling similar to native chrome's with the arrow keys.

**Comment by DavidLGoldberg** [comment]
A little more investigation:
(I've never needed to tweak anything in vimium really, forgot it had all of these options)

Both my chrome and canary are set to 60px smooth scrolling.

**Comment by DavidLGoldberg** [comment]
So this is embarrassing but I can no longer reproduce this after upgrading and relaunching my canary...

Maybe it was a really broken build or something broken on my system?  I *have* seen Canary fail me before.  

The other variable introduced is that I saved settings (with default values already there)

Anyway, can't reproduce it, so closing it.  Sorry about that!
