### ISSUE TITLE
gi doesn't find first text input field in a page when the input is out of view

### ISSUE THREAD

**Issue by tobimensch** [philc/vimium#2256]
gi works correctly as long as the input field (for example for google) is visible,
but if you scroll down (ie. using G) and try gi again, the first input field
on the page will not be found.

**Comment by smblott-github** [comment]
That is the intended behaviour.

(I guess one could make a case for scrolling if no inputs are visible.)

**Comment by tobimensch** [comment]
Why is that the intended behaviour?

It says "Focus the first text input on the page", which (if taken literally) means
on the whole webpage, not just on the currently visible parts of it.

In my opinion it should scroll to the first text input field on the (whole) page,
but if there's none, it should do anything (just like now).

**Comment by smblott-github** [comment]
I changed the text in the README to make it clearer: 4b1654f820b645a339f98160a1607c042217bf9d.

**Comment by tobimensch** [comment]
Ok, I still would like to have a feature that always jumps to the first text input on a page. I think it would be useful on all web pages that have a search box at the top (all search engines, amazon, etc.).

**Comment by sflip** [comment]
Agreed. This is what I want quite often.

**Comment by tobimensch** [comment]
@sflip 
I'm agreeing with you agreeing with me.

@smblott-github 
See, this feature is wanted by more than one person. I bet there are many who think the same way.

I'm not begging for this feature at all. Not at all.
