### ISSUE TITLE
Vimium cannot "click" select elements

### ISSUE THREAD

**Issue by daemedeor** [philc/vimium#2257]
Previously when I used vim on Chrome 51 or thereabouts the dropdown used to open when I hit f and then the associated tag that vimium tagged the field with. Now vimium still tags the field but it doesn't seem to open the select boxes. I tried it on several pages by adding my own select boxes but I'm not quite sure why its not working. Any workaround?

**Comment by smblott-github** [comment]
@daemedeor... Could you provide an example page?

(This works on Facebook, for me.)

**Comment by daemedeor** [comment]
Here: http://store.steampowered.com/agecheck/app/234140/?snr=1_239_4__122, if you have steam. also note: I'm on Chrome 53, Seirra, macOS. 

<img width="1285" alt="screen shot 2016-09-19 at 7 10 30 am" src="https://cloud.githubusercontent.com/assets/6037411/18631579/6a02df4c-7e38-11e6-8ed2-a0863333969d.png">

**Comment by daemedeor** [comment]
Ah, the thing is. Even when I go to other pages (not just this one, this is just one of the examples) it seems to do it. Even when I just make my own select box. I'll test on facebook one minute.

**Comment by daemedeor** [comment]
Hmmmm Wait... its not the drop down at the top of the page on the dropdown menu, I mean like where it says "Feburary" or the date picker.

**Comment by romgrk** [comment]
Hello,
I have been seeing warnings pop up in the console (when clicking through vimium), saying that some non-standard behaviors would be removed from Chrome sometime during September, so I'm guessing that this is it. I'm using version 54 and those warnings have disappeared, along with the ability to click through vimium.

**Comment by romgrk** [comment]
After a bit of investigation, it seems that it is indeed unstandard to be able to open a select element through javascript. Given that Chrome/ium is lately pushing to more standardization, I think it is unlikely they will go back to the old behavior. I would recommend at least triggering a 'focus' event on such elements, so the user can trigger it with space subsequently.

**Comment by smblott-github** [comment]
@romgrk... If you're referring to the following console message regarding `keyIdentifier`, then we already have code in place to cover its removal:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/18655817/d452fcfa-7ee3-11e6-9e76-f7f84d3ef2ef.png)

Regarding Chrome 54... I tried it, and didn't have any issues with link hints.  Please post a link and a description of the steps to reproduce.

**Comment by romgrk** [comment]
Oh, well,
1. Find any select element
2. `f` + xx
3. No reaction; the vimium flash shows up but then nothing more.

And no, it was a similar warning but it was triggered when "clicking" a select element. Unfortunately I can't give you any data because it doesn't show up anymore.

**Comment by smblott-github** [comment]
OK.  I see now.  It's the same in Chrome 53.

**Comment by gdh1995** [comment]
Before Chrome 52/53, `<select>` element is "opened" on a `mousedown` event, but the Chrome developers changed this behavior into:
* only those `default browser actions` triggered by `click` events are allowed to be called by `untrusted` events (which are usually created by JavaScript code)
* so clicking `<a download="">` will trigger the File Save Dialog
* while we have no methods to "open" a `<select>` popup menu.

Some ones have pulled a request to add `.open()` and `.close()` methods to `<select>` elements, but it's not accepted yet.

You may see https://www.chromestatus.com/features/5718803933560832 for more explanations.

**Comment by IamGianluca** [comment]
This happens also when browsing the [python documentation](https://docs.python.org/3.5/library/csv.html). If you try to move to the same page for a different version of python using the drop down menu on the top left of the page. 

Browser: Google Chrome Version 53.0.2785.143 (64-bit)
OS: GNU/Linux Ubuntu 16.04 LTS 
Vimium: 1.57

**Comment by daemedeor** [comment]
@IamGianluca It's important to note that some "drop down boxes" are not really drop down boxes. Like the upper part where "Watch" is, even though the behavior is similar to a drop down, its actually a link. Probably so they could have an easier time to stylize it. Overriding the default select boxes are a world of pain

**Comment by nilskaspersson** [comment]
Running `focus()` on the `<select>` when it's clicked through Vimium is probably the best solution to this issue.

**Comment by jlevitt** [comment]
I've also hit this issue, used to work, now no selects work with vimium. I see #2338 may fix this issue? Is there a way to get the update? (I don't see a new release).

**Comment by smblott-github** [comment]
I think we'll push the new stuff in the coming week or two; just need to check with @philc.

**Comment by AndrewSouthpaw** [comment]
Any chance we can get a version bump? Not having access to dropdowns reduces the usefulness of this (otherwise excellent) extension.

**Comment by philc** [comment]
+1, let's release. No need to hold back the fixes in master.

**Comment by smblott-github** [comment]
> let's release

Will do.
