### ISSUE TITLE
return focus to page after text input and UI interaction

### ISSUE THREAD

**Issue by chairmank** [philc/vimium#226]
Text input boxes within web pages and the address input box of the browser GUI  (Ctrl-L) steal focus and there is no way to return to "command-mode" scrolling, etc. It would be nice to be able to use Ctrl-C or Esc to escape from "insert mode".

To reproduce:
1. Go to http://www.google.com, tab to the search query input box, start typing a query. No way to escape the query input box to scroll through the search results.
2. Type Ctrl-L to enter a URL (is there any other vim-like way to do this?). No way to navigate the loaded page with keys.

I am using chromium-browser 6.0.472.62 (59676) Ubuntu 10.04

**Comment by xavierchow** [comment]
Though we all understand it's out of vimium's scope, another nice hack is here: http://superuser.com/questions/324266/google-chrome-mac-set-keyboard-focus-from-address-bar-back-to-page/324267#324267, it needs less key strokes and doesn't change the position of page(html).

**Comment by jkryanchou** [comment]
And now my solution is to ctrl+f to search page return to the page content.

**Comment by GoTop** [comment]
I find using @jb55 method, press "Tab" key is the best.

**Comment by nivv** [comment]
> I found using @jb55's method, press "Tab" key is the best.

This doesn't work for me, pressing tab focuses the next extension:

![image](https://user-images.githubusercontent.com/4033930/72501482-344c6500-3837-11ea-8092-632e2b970628.png)

**Comment by alon91** [comment]
I'm asking for the same feature in the wonderful [Shortkeys](https://github.com/mikecrittenden/shortkeys) extension (complements Vimium wonderfully).

Here's my (annoying, slow, but consistent) workaround to get focus from URL bar back to the page as I also describe [here](https://github.com/mikecrittenden/shortkeys/issues/125):

> For the last several years I've been using the solution in [this](https://superuser.com/questions/324266/google-chrome-mac-set-keyboard-focus-from-address-bar-back-to-page/324267#324267) thread: I created a [Chrome custom search engine](https://www.ghacks.net/2018/03/30/custom-search-engines-in-google-chrome/) that points to the Query URL `javascript:` and mapped it to the letter 'u'. When I'm in the address bar and want to exit I remove anything in the URL bar, and hit `u` + `enter`.
> 
> If Shortkeys can run javascript via a shortcut while the cursor is in the URL bar then perhaps this is an answer?
> 
> ![image](https://user-images.githubusercontent.com/35006176/74494064-c8d2d300-4e88-11ea-8940-00c76e1d699e.png)
>

**Comment by minhlong** [comment]
> I found using @jb55's method, press "Tab" key is the best.

it works with me, just press 'esc' and 'tab' key.

Thanks,

**Comment by mcp292** [comment]
As mentioned by [philc](https://github.com/philc/vimium/issues/226#issuecomment-458455) this is a browser issue since Vimium cannot access strokes out of the page focus. 

For anyone who came here from firefox the browser key to return focus to page is [F6](https://support.mozilla.org/en-US/questions/1210451). Now to figure out how to bind this.

**Comment by alanhg** [comment]
```
tell application "Google Chrome" to set URL of active tab of window 1 to "javascript:"
```

**Comment by aalvarado** [comment]
ctrl+F works for me after making a tab a window with `W`

**Comment by bek9** [comment]
I recommend `Command` + `Option` + `Up Arrow`. It's only a key combo, no incidental works and no additional settings. It works fine on macOS but I haven't checked if it works on Windows yet.
