### ISSUE TITLE
Feature request: Force unblur on tab navigation

### ISSUE THREAD

**Issue by krokofant** [philc/vimium#2267]
So sometimes I have one tab in which I have a focused input. Suppose I want to go 3 steps to the left I'd to JJJ but if I have a input focused in one of the tabs it blocks.

*Wish*
Add option to force unblur (command mode) on tab navigation

**Comment by innaterebel** [comment]
You can do `3J` instead, though. 
Yea, you can't always be conscious of that there is an input in the way, still for this particular case.
