### ISSUE TITLE
Feature request: Highlight tabs matched by T search [Need input]

### ISSUE THREAD

**Issue by krokofant** [philc/vimium#2268]
So the tabs matched by T search would be viewed as this in the tab bar where the one to the far right is the active one.
![image](https://cloud.githubusercontent.com/assets/5908498/18768783/e8d39522-8127-11e6-8a08-6aca55f46c3c.png)

Are more then me interested in this?

Things to take into consideration:
- Multiple windows

Crappy example code:

``` js
setTimeout(function(){
  chrome.tabs.query({}, function(tabs){
    chrome.tabs.query({active: true},function(currentTabs){
      chrome.tabs.highlight({windowId:tabs[0].windowId, tabs: [currentTabs[0].index,1,2,3]}, null)
    })
  })
}, 2000)
```

**Comment by smblott-github** [comment]
If I understand correctly, you're proposing that we visually highlight the tab-bar tabs of the tabs which match the current query, yes?

Unfortunately, `chrome.tabs.highlight()` doesn't seem to do that.  It seems to focus the tab (I tried it).

**Comment by krokofant** [comment]
@smblott-github The highlight focuses on the first tab it highlights so the first tab (*currentTabs[0].index* in example) must be the active tab in the window.

**Comment by smblott-github** [comment]
Ah.  OK.

Here's what it looks like with `chrome.tabs.highlight {tabs: [1, 2, 4]}`:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/18773914/9263003c-814b-11e6-98e7-7dba1608907e.png)

It's not particularly striking.

And here it is in another profile:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/18773995/6d9c54fa-814c-11e6-9d66-ec9d46d3c0fc.png)

Slightly better.

An alternative would be to highlight just the tab which would be activated if the user were to hit `Enter` now.

And we'd have to figure out what to do if the user changes tab (with the mouse, or `<Alt-PageUp>`) while the Vomnibar is active.  (In fact, there might be a race condition.  What if the Vomnibar is active in two tabs and we switch between them.  One tab would be unhighlighting tabs, and one highlighting them, and we probably can't control the order in which those things happen.)

**Comment by krokofant** [comment]
To highlight only the top search would be nicer since one can navigate up and down the list.

It could just work the way as when the window, tab and Vomnibar is in focus then that search sends out it's highlight and if any other Vomnibar takes focus then that'll resend the highlight.

The unhighlight (highlight all active tabs) could occur when the Vomnibar loses focus in any way which would happen naturally in a single window if the user navigates tabs.

**Comment by tobimensch** [comment]
> An alternative would be to highlight just the tab which would be activated if the user were to hit Enter now.
That would definitely be an improvement!
