### ISSUE TITLE
Feature Request: Automatically Select the First Item in VomniBar dropdown

### ISSUE THREAD

**Issue by aswinmohanme** [philc/vimium#2271]
I was wondering if the first Entry in Vomnibar was automatically selected so that we won't have to select the entry manually.

**Comment by luanpotter** [comment]
What if we want to access exactly what we typed, and not any of the suggestions? It would be impossible then. Maybe there could be another shortcut to do that, but I think ctrl+j + enter is very good already.

**Comment by 2tolik** [comment]
T has it, but O should not.

**Comment by smblott-github** [comment]
I agree with what @2tolik said.
Closing.

**Comment by jakubgs** [comment]
I think this should be an option.

>What if we want to access exactly what we typed

Well, the either exactly what you typed isn't in suggestions, so you open that. Or it is in suggestions, and you also open that. I don't get that objection.
