### ISSUE TITLE
Feature request: Search box (optionally) at top.

### ISSUE THREAD

**Issue by tobimensch** [philc/vimium#2275]
I'm used to search boxes being at the top right in chrome/chromium. When I type / it can happen that I think for a few seconds that it didn't work, because I expect the search input box in the upper right corner from years of getting used to that work flow.

It would be much appreciated if there was an option to set the location of the search box.

**Comment by sergeyzozulya** [comment]
Best option would be to use nice vomnibox

**Comment by smblott-github** [comment]
I'm not sure there's a strong enough to add an extra option for this.  Arguably, bottom-left would be the correct place (a la vim), but the status quo seems ok for most users.

**Comment by sergeyzozulya** [comment]
Yes, right now it's similar to vim but looks a bit ugly comparing to vomnibox

**Comment by smblott-github** [comment]
> bit ugly comparing to vomnibox

I agree.  I'd like to see it restyled to better match the look of the vomnibar.

**Comment by philc** [comment]
Closing in favor of #3468, which more narrowly captures the latest proposal by @ghost and @smblott-github.
