### ISSUE TITLE
Incorrect order of script loading on internal pages (e.g. the options page)

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#2277]
I'm seeing the following error on the options page:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/18869464/5ccbe446-84a4-11e6-8516-43e7d172c98b.png)

The problem is that scripts loaded by the [content-script loader](https://github.com/philc/vimium/blob/master/pages/content_script_loader.coffee) are loading asyncronously, so after `options.coffee` on the options page.  This affects all of Vimium's internal pages which use the content-script loader.

The effect (luckily) isn't too serious on the options page, but other extension pages are broken (e.g. the logging page).

Could somebody else confirm this (or otherwise) with the configuration below (or similar), please?

Chrome: 53.0.2785.92.
Vimium: 1.56

(`master` currently contains a temporary patch to fix this: 8601edd71e74ba522e32658309cb2e7acca8aeeb, so you won't observe the effect there).

**Comment by gdh1995** [comment]
Um.... I think we just need to do this:
* add an `extend` function to `loader.coffee`. 

This uncaught error occurs on my Chrome 50..53. I don't know why Chrome make such a change - maybe they want to prevent dynamically inserted scripts from blocking loading of the page?
