### ISSUE TITLE
Scrolling does not work

### ISSUE THREAD

**Issue by samclearman** [philc/vimium#2279]
I'm running Chrome 53.0.2785.116 on Ubuntu and the scrolling commands (hjkldu) don't work at all.  Everything else seems to be working fine.  Scrolling works on my mac (which has the same Chrome profile loaded)

**Comment by innaterebel** [comment]
Most likely due to a certain flag is being enabled on your Linux installment, see #2227. (flags setting is installation-level and stored outside profiles)

The potential issue is just being addressed on `master`, though, yet to be published to Chrome Web Store.

**Comment by samclearman** [comment]
Duplicate of #2227
