### ISSUE TITLE
Build error: Unexpected =

### ISSUE THREAD

**Issue by krokofant** [philc/vimium#2281]
`mode_visual.coffee:32:17: error: unexpected =` which is [this line](https://github.com/philc/vimium/blob/master/content_scripts/mode_visual.coffee#L32)

I tried building master, 1.56 and 1.55. When I remove the `=` the build works. Why is this?

I cloned the repo, switched to corresponding branch and ran `cake build`.

**Comment by smblott-github** [comment]
Thanks @krokofant.

Looks like this is related to #2273.  Try downgrading Coffeescript to 1.10: https://github.com/philc/vimium/commit/ba7302fd7b486a06ac9721287c88a6b4daf0eb1e.

**Comment by krokofant** [comment]
@smblott-github Thank you!
