### ISSUE TITLE
'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M54

### ISSUE THREAD

**Issue by Long-Summer** [philc/vimium#2288]
'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M54, around October 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.

**Comment by smblott-github** [comment]
Thanks @Long-Summer.  We have code in place already to handle this.

There are issues for some keyboard layouts, though; see #2147.
