### ISSUE TITLE
Bug: Link hints not in correct position

### ISSUE THREAD

**Issue by tobimensch** [philc/vimium#2291]
See here:

http://debbugs.gnu.org/

I'm attaching a screenshot in case you can't reproduce it.
![screenshot-vimium-link-hint-bug](https://cloud.githubusercontent.com/assets/9920531/19022237/d36d5dfe-88d3-11e6-8813-81fcce7a3147.png)

**Comment by smblott-github** [comment]
That's weird.  Help wanted...

**Comment by gdh1995** [comment]
It's `<html style="position:relative">` which makes the base position offset of Vimium's nodes not zero.

**Comment by tobimensch** [comment]
Thank you @gdh1995
