### ISSUE TITLE
An issue while switching tabs with different keybinds

### ISSUE THREAD

**Issue by light2yellow** [philc/vimium#2294]
I'm using
```
map <a-right> nextTab
map <a-left> previousTab
```
When I switch tabs with these commands my monitor goes fully black (like being disconnected) for half a second, then blinks a few times and then finally shows me the switched tab. If I relaunch the browser everything works as before (and everything did work at least few days ago and like forever) for some period of time, than it gets broken again.
Note: default Shift+J/K work normally.
I think this somehow conflicts with chromium's bindings: back and further. Race conditions? Because it becomes broken not right from the start.

**chromium 53.0.2785.143
vimium 1.57**

**Comment by smblott-github** [comment]
@light2yellow...

This is a very unusual bug report.

On the one hand, there was a Vimium release last weekend (1.57), so reports of a behaviour change aren't too surprising.

On the other hand, Vimium really shouldn't be able to trigger the effect you describe at all.  And there really shouldn't be a race condition with one key binding but no race condition with another binding.

Let's leave this here for a bit and see if there are any more reports.

**Comment by light2yellow** [comment]
@smblott-github and now everything works again. It's strange. Probably it has something to do with Xorg and xfwm but I'm not sure. Maybe there was a system upgrade and I didn't restart Xorg. Shouldn't be a vimium issue.
