### ISSUE TITLE
`Commands.parseKeySequence("<a>")` returns `["<a>"]`

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#2299]
But I think it should return `["<", "a", ">"]`.

This case is caused by the regexp `/^<((?:[acm]-)*(?:.|[a-zA-Z0-9]{2,}))>(.*)/i` which can match `"<a>"`.

**Comment by smblott-github** [comment]
Right enough.  Thanks.

**Comment by gdh1995** [comment]
Oh, it seems that I misunderstood the meaning of `right enough`. Sorry.

So any ideas about tell `["<", "a", "b", ">"]` from `["<ab>"]`?

**Comment by smblott-github** [comment]
Thanks again, @gdh1995.

This should be fixed in 71612af7eb81fa77c0be98a2a69e4852f4003e66.

That regexp is just too complicated, so I broke it into parts.  Also added some more tests.
