### ISSUE TITLE
'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M54.

### ISSUE THREAD

**Issue by ilvsx** [philc/vimium#2302]
In the Chrome DevTools Console:
'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M54, around October 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.

**Comment by smblott-github** [comment]
Thanks, @ilvsx.  We already have code in place to handle this.

**Comment by zaz** [comment]
Duplicate of #2288.
