### ISSUE TITLE
Vimium Breaks Chrome 54

### ISSUE THREAD

**Issue by jlevitt** [philc/vimium#2316]
Just started up my computer this morning and chrome no longer works. All websites are hung on "Processing Request". Disabling extensions pointed to Vimium as the culprit. I assume chrome auto-updated and no longer works with Vimium.

Google Chrome	54.0.2840.59 (Official Build) m (32-bit)
Revision	5b2f167ccdaed3f1a90ec1084715fbb91b8d25b0-refs/branch-heads/2840@{#726}
OS	Windows 
Vimium 1.57

Please let me know if there's any other info needed.

**Comment by smblott-github** [comment]
Could you create a new clean profile, @jlevitt, and install Vimium there, please?  Just to confirm that Vimium is in fact the problem.

**Comment by jlevitt** [comment]
> Could you create a new clean profile, @jlevitt, and install Vimium there, please? Just to confirm that Vimium is in fact the problem.

@smblott-github It works in a new profile. Any idea why it would have stopped working in my old one? I didn't make any changes (installing extensions, etc). I'll try uninstalling and re-installing in my main profile.
