### ISSUE TITLE
Insert mode visual indication

### ISSUE THREAD

**Issue by ZaytsevArtem** [philc/vimium#2317]
Is there any easy way to add the subj? Like the vimium icon change or maybe add a fixed html indicator element in the page corner with the use of css (is it possible? IDK) or js? It could help to know if i pressed the «i» button accidentally.
Pardon my english.

**Comment by smblott-github** [comment]
We have that (bottom right)... 

![snapshot](https://cloud.githubusercontent.com/assets/2641335/19483769/68cf2d16-954d-11e6-8d50-9a87b5ad6287.png)


Is that what you mean?

**Comment by ZaytsevArtem** [comment]
Yes, sorry, i guess i'm blind.
