### ISSUE TITLE
What `passNextKeyKeys` does now?

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#2325]
I think this setting item now is not needed any more.

**Comment by smblott-github** [comment]
Not sure I understand, @gdh1995.  It could be transported via `chrome.storage.local` instead of settings, but it is needed (in insert mode).

**Comment by gdh1995** [comment]
But in my tests, the normal `KeyHandlerMode` handles those keys mapped to command `passNextKey`.

The `passNextKeyKeys` array is used only when:
* first, enter insert mode, which means calling `enterInsertMode` or starting to edit a text box
* press a single key which has been bound to `passNextKey`
* and then the next one key is passed to web page
* BUT without `PassNextKeyMode`, all next keys are still passed.

Any other use case?

**Comment by smblott-github** [comment]
> first, enter insert mode, which means calling enterInsertMode or starting to edit a text box

But insert mode is *always* active (and above normal mode in the handler stack). [Here](https://github.com/smblott-github/vimium/blob/master/content_scripts/vimium_frontend.coffee#L153).  So it's always available to see keyboard events (before normal mode).

E.g. I use `<c-]>` for `passNextKey`.  On this page, `l` does nothing (there's nothing to scroll), but `<c-]>l` opens the "Labels" menu.

**Comment by smblott-github** [comment]
> - press a single key which has been bound to passNextKey
> - and then the next one key is passed to web page

That's actually a bug.  I'll fix that.

> BUT without PassNextKeyMode, all next keys are still passed.

No, not if they're mapping (e.g. `l`).

**Comment by smblott-github** [comment]
Sorry, @gdh1995.  Those previous two posts (by me) are wrong.

If an input is focused or if we're in insert mode because the user pressed `i`, then `Escape` is not passed to the page.  So, in insert mode, `<c-]>Escape` passes `Escape` to the page, whereas `Escape` on its own exits insert mode.

(So, `passNextKeyKeys` is still needed.)

**Comment by gdh1995** [comment]
Oh I see. Thanks.
