### ISSUE TITLE
Feature request: No-op command

### ISSUE THREAD

**Issue by neil-s** [philc/vimium#2336]
I'd like to map my backspace key to do nothing at all. Not go back in history (default Chrome behaviour) or any of the existing Vimium actions. 

Is there a way to map a key to doing nothing? Alternatively, would it be possible to add a command that literally does nothing, in order to stick with the current syntax of `map <key> <command>`?

**Comment by innaterebel** [comment]
Chrome has removed that "default behaviour" since version 52, though?
`Backspace` already natively does nothing now except in an input field.

**Comment by neil-s** [comment]
Whoops, that's embarrassing, totally didn't realize that.

**Comment by smblott-github** [comment]
For the record, you should be able to get a no-op with something like...

    map X createTab count=0
