### ISSUE TITLE
Document the P key

### ISSUE THREAD

**Issue by Mingling94** [philc/vimium#2337]
If I understand correctly, P causes "Search clipboard text on current tab" behavior. It's a bit jarring and disruptive since it's a single-key shortcut that you can easily press while typing. 

I didn't know what was causing this until I did a bunch of testing and realized that it didn't repro on my other browsers nor my vimium whitelisted sites. You should document it cuz it is absent everywhere right now and this was not easy to realize.

**Comment by smblott-github** [comment]
It's documented on the help page (`?`).  Perhaps we should add it to the quick-start text on the README too?

**Comment by Mingling94** [comment]
Oh I see, it's under "Show advanced commands". Yeah it, and other commands, should be in the README for easy Google searching access (although I should have first checked the `?` thing.

I did unmap it eventually...
