### ISSUE TITLE
Vimium not work when the internet is down

### ISSUE THREAD

**Issue by Princu7** [philc/vimium#2341]
Hello everyone. I am using vimium on Vivaldi browser on Ubuntu 16.04.  The extension is great and I am loving it so far. 

Sorry for asking really dumb question but it seem like vimium doesn't work when the internet is down or the network connection is slow. Suppose I have some tab unopened for quite some time. When I revisit that tab, it will try to reload and if there is no internet connection present at that moment, there will be a an internet connection error and the vimium won't work. I will have to use the inbuilt shortcuts of the browser or the trackpad to navigate between the tabs.

I don't know whether this is the normal behaviour or a bug in either the browser or the vimium. Any help is appreciated. Thank you so much!!!.

**Comment by innaterebel** [comment]
See #2240.
And if you are talking about the error page that says your internet connection is off, it's likely that Vivaldi, which is a fork of Chromium, disallowing extensions to run on such browser internal pages for security reason, similar to Chrome.

**Comment by smblott-github** [comment]
Yup.  That @innaterebel says.
