### ISSUE TITLE
Feature request: vomnibar font size and position adjustable

### ISSUE THREAD

**Issue by mcevzar** [philc/vimium#2342]
The font size in chromes omnibox is too small for me and many others that is why I love the omnibox.

I would love the option to set the font size to be even bigger and that I could choose where the vomnibox will appear on my screen. For me the middle would be optimal.

In general I would like something like the Vivaldi command line.

Thank you.

**Comment by mrmr1993** [comment]
Since #2683, this has been possible by changing the CSS in the options. It still says for link hints, but I've opened #2815 to (hopefully) make things a bit clearer.
