### ISSUE TITLE
Link hint (f) mode: multiple ways to cancel 

### ISSUE THREAD

**Issue by 2tolik** [philc/vimium#2344]
Problem: only way to exit "Link hint" mode is to hit ESC or symbol(s) corresponding to a link.
Expected: there should be faster way to exit this mode if user changed his mind. Spacebar / Enter / else?

**Comment by innaterebel** [comment]
Any character that's not in your preferred hints list (configurable in Vimium settings) effectively cancels link hint mode.
`Space` has recently been assigned to bear the function to change the stacking order of hints when hints are crowded, nevertheless.

**Comment by 2tolik** [comment]
Spacebar (just like Esc/Enter/Tab) sounds more like "anykey" in comparison to "try to hit anything other than your common keys". 
Plus, "stacked hints" sounds like a problem that needs a fix* instead of workaround. 
Someday, maybe. 

* duplicate or false elements, like github's "Watch" over there.
