### ISSUE TITLE
Tab switch doesn't work when vimium enabled

### ISSUE THREAD

**Issue by peteyy** [philc/vimium#2347]
When I enable vimium my tab switch backward shortcut ( CTRL + SHIFT + TAB) does not work.
When I try switching forward (CTRL + TAB) it works fine.

I'm sure there is a builtin way to fix this but I couldn't figure anything out. How can I disable these shortcuts in vimium?

**Comment by gdh1995** [comment]
As far as I know, Vimium can not prevent Chrome from handling `<Ctrl+Shift+Tab>`. Maybe you need to do  more search.
