### ISSUE TITLE
Labels on deventer.live don't get link hints

### ISSUE THREAD

**Issue by raboof** [philc/vimium#2350]
https://deventer.live uses hidden checkboxes with labels. It'd be great if those labels could get link hints.

This probably has some relationship with #1554, though I haven't been able do dig sufficiently deeply.

**Comment by smblott-github** [comment]
Could you show exactly where you mean please, @raboof.  Not these, right?

![161118-01-snapshot](https://cloud.githubusercontent.com/assets/2641335/20431064/e9cc3d50-ad8f-11e6-8222-0bb518a8b6af.png)

**Comment by raboof** [comment]
Ah - I was accidentally stuck on Vimium 1.51, indeed this works just fine now! Sorry for the noise :)
