### ISSUE TITLE
How can I access chrome toolbar within vimium shortcuts?

### ISSUE THREAD

**Issue by ahmedmohiduet** [philc/vimium#2352]
Feature Request:
I am not sure if this can be done within vimium but would be nice. Can I focus or select specific extension on chromes extensions icons toolbar?

Best Regards
---
Mohiuddin

**Comment by dragon788** [comment]
@ahmedmohiduet I don't think that any extension has the ability to manipulate the toolbar directly, but if you open the chrome://Extensions page and scroll to the bottom there is a "Keyboard Shortcuts" link that allows you to set keyboard shortcuts for many extensions.

**Comment by smblott-github** [comment]
@ahmedmohiduet... @dragon788 is right.  I don't think Chrome has an API for this.
