### ISSUE TITLE
some problems with pressing keyword H or K

### ISSUE THREAD

**Issue by marksnoopy** [philc/vimium#2355]
when a page is a chrome-extension page or a chrome page such as history page  , keyword H or K can not change  tab .

**Comment by smblott-github** [comment]
Nothing we can do about that, @marksnoopy, unfortunately... https://github.com/philc/vimium/wiki/FAQ#why-doesnt-vimium-work-on-the-chrome-store-or-urls-starting-with-chrome

**Comment by marksnoopy** [comment]
thanks
