### ISSUE TITLE
Feature request: focus to search bar or address bar or current page

### ISSUE THREAD

**Issue by bluer-hu** [philc/vimium#2358]
if  vimium can focus to search bar  or  address bar ,  and  can return to  current  page,   it   will have  better user experience.

**Comment by smblott-github** [comment]
I don't think there's a Chrome API for this.

**Comment by FiveOfSeven** [comment]
On my chrome browser with vimium I can go to the address bar by typing alt+d, and I can return back to the regular page by pressing the tab button. Once I am on the page again, I can use all the vimium commands.

**Comment by haridsv** [comment]
Getting focus back to the page requires pressing tab several times, at least in my case, as it cycles through controls, plugins and bookmark bar, but there is a trick that uses a "no-op" search engine that is described here that works really well: https://superuser.com/a/324267/26006
