### ISSUE TITLE
After YouTube updated its site, some Vimium shortcuts are unreadable

### ISSUE THREAD

**Issue by nick-s-b** [philc/vimium#2363]
Hi all,
I've used Vimium for a while without any issues and one of the things I did on YT is to set player into full-screen mode by hitting the "f" key and then picked the proper shortcut key. However, after the recent update, YT player now looks like this when I hit the "f" key:

![yt mess](https://i.imgur.com/Hqdqnuc.jpg)

and it's impossible to tell what the proper key is for full-screen.

Unfortunately, the full-screen key under YT is "f" key so when I disabled it, Vimium doesn't open links anymore.

Any idea why YT is messed up so much now? Thanks!

**Comment by smblott-github** [comment]
@nick-s-b...  I'm going to guess it's `LD`, but that doesn't answer your question.  Unfortunately, I don't see YT the same, so it's difficult to figure out what's going on...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/20954804/452966b4-bc36-11e6-9d9d-404bf1611b43.png)

As a workaround, if you have...

    map <c-]> passNextKey

Then `<c-]>` `f` should get you full screen mode too.  And that's better in that the keys you have to hit are predictable.

**Comment by afuous** [comment]
I am not sure about your question, but a nice workaround for youtube is using the `passNextKey` feature which lets you send the next key directly to the web page without using vimium bindings. If you bind `<c-k>` to `passNextKey`, then you can press `<c-k>f` to enter fullscreen mode in youtube.

**Comment by nick-s-b** [comment]
Thank you for replying @smblott-github ! That worked well... now I can bypass Vimium easily.

BTW, how did you change your links to numbers?

**Comment by sco-tt** [comment]
@nick-s-b 

Vimium Options -> Advanced Options -> Use the link's name and numbers for link-hint filtering

**Comment by bora89** [comment]
I found next short cut more handy:
```
map ew passNextKey
```
So you would press `ew` then `f`
