### ISSUE TITLE
J and K keys to switch tabs stop working on suspended tabs

### ISSUE THREAD

**Issue by finix14** [philc/vimium#2364]
I have Great Suspender installed which suspends idle tabs to save RAM. The J and K keys work fine on unsuspended tabs but stop working as I reach a suspended tab.

**Comment by finix14** [comment]
I guess Ctrl+Tab, Ctrl+Shift+Tab would do then. Thanks anyway. Absolutely brilliant extension though :)

**Comment by dohsimpson** [comment]
Hi @smblott-github. Thanks for the reply. But would the Chrome Flag `#extensions-on-chrome-urls` work? It is documented as "Enables running extensions on chrome:// URLs, where extensions explicitly request this permission"

**Comment by skrat** [comment]
amazing how many times this was requested. so there's this guy who's claiming his got it working in vimium c. if that's true why don't you merge his work and finally solve this? how many opened issues do you need?

**Comment by gdh1995** [comment]
@skrat Sorry but Vimium C runs on another extension only when the target extension makes some changes in its code and sends a request actively. So it can only work with a limited set of (published) extensions.
 
When I want a extension to run Vimium C, I usually find its released package, edit its files and then load it in the "developer mode" on `chrome://extension`.

**Comment by gdh1995** [comment]
Or if you only want shortcuts to switching among tabs, then it's indeed possible to implement it without modifying other extensioms. Chrome/Firefox supports "global commands" for extensions - a extension can provides some names to a browser, a user assigns some shortcut keys to some of the names, and then when the user press such a key, Vimium will get the bound name to execute some actions.

**Comment by skrat** [comment]
@gdh1995 good point, too bad Vimium doesn't provide those commands.
