### ISSUE TITLE
Quora's search field captures movement keys

### ISSUE THREAD

**Issue by begriffs** [philc/vimium#2366]
Whenever I view a page on Quora I always end up with `jjjjj` in the search field as I try to scroll down. I can press escape to release the cursor from the search box but nearly always forget to do so. Is there a way to customize vimium per-site to prevent this?

**Comment by smblott-github** [comment]
@begriffs... The following option (on the options page) might be what you're looking for...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/21072682/98be6bec-bec2-11e6-96d7-f918fa3cebf4.png)

**Comment by begriffs** [comment]
Aha, it's in advanced options! Thanks.
