### ISSUE TITLE
can bookmarks gradually show ? similar to the  effect after pressing the key 'f' 

### ISSUE THREAD

**Issue by chouway** [philc/vimium#2375]
I suggest the function can let the bookmark gradually show through some key; 

It should be frequently-used.

Thank you for your sharing vimium;

**Comment by smblott-github** [comment]
I don't understand what you mean, @chouway.

**Comment by chouway** [comment]
Sorry that my english is not fluent.

i mean,  if someone choose some bookmark, he should be click in bookmarks bar step by step  with mouse , so , i think it can be with  keyboard .

by the way ,press the  key 'B' to open bookmark , it  is cool. thank you;

**Comment by chouway** [comment]
chrome provides:
ctrl + alt + b, 
then  'left'   'up'  'right'  'down'  'home'  'end'  key , choose bookmark,  
at last press the 'enter' to choose the target bookmark.   


so ,i close the issue
