### ISSUE TITLE
Link Hints "click" doesn't focus button/role="button"

### ISSUE THREAD

**Issue by nicholasguyett** [philc/vimium#2378]
When using link hints (`f`) to "click" a `button` or `[role="button"]` the element does not have focus afterwards.  When using the mouse to directly click, the mouse does have focus.

Is there a particular reason why vimium's link hints deviate from natural clicks in this instance or could this be corrected?

**Comment by smblott-github** [comment]
> Is there a particular reason why vimium's link hints deviate from natural clicks in this instance or could this be corrected?

Not sure, @nicholasguyett. Vimium does not actively blur the element, the element just doesn't get the focus when we simulate clicking it.

Do you have a positive reason for why that would be the *right thing to do*?

**Comment by nicholasguyett** [comment]
@smblott-github I think consistency with a real click is a positive reason for giving focus to the clicked element.  It also helps tab navigation as the focus means that you'll be able to tab from that button after clicking on it.

**Comment by smblott-github** [comment]
Somebody (not me) made a decision in the past that a button should not receive the focus: [here](https://github.com/philc/vimium/blob/master/content_scripts/link_hints.coffee#L396).  I wonder why.

**Comment by gdh1995** [comment]
@smblott-github The first person who decided not to focus an `input[type=button]` is @philc in [the initial commit of Vimium](https://github.com/philc/vimium/blob/f33de347f0de1448446eac462892addbe7a3c461/content_scripts/link_hints.coffee#L193), so maybe it's just a typo?

I think it's quite reasonable to actively focus any visible `input` element, but we can not know if an `[role=button]` needs focus. Therefore, I suggest focusing those with `[tabindex] >=0` .

**Comment by smblott-github** [comment]
That sounds reasonable, @gdh1995.  Do you fancy putting in a PR?

**Comment by philc** [comment]
Thanks for the sleuthing guys. I think the element should get focus for the
reasons mentioned.

**Comment by gdh1995** [comment]
OKay I'll make two PRs about this issue and the 351489c7c5e093531aa8cd5870a3f78c99fb2923 some hours later.

**Comment by nicholasguyett** [comment]
Resolved by #2383
