### ISSUE TITLE
solution for switching tabs and running into tabs in insert mode

### ISSUE THREAD

**Issue by shibumi** [philc/vimium#2381]
Hello,
Is there any solution for the issue when you switch tabs and run into a tab with insert mode? Especially when the URL-Bar is in insert mode I can't switch this off without the mouse..

Is there a way to exit the insert mode of the url bar? Any chance to implement a hotkey for an exit?

**Comment by smblott-github** [comment]
> Is there a way to exit the insert mode of the url bar? Any chance to implement a hotkey for an exit?

There's no Chrome API to do this.  I think `Escape` then `Tab` gets you back into the page.  (Best avoid getting the focus in the omnibox in the first place, if you can.)

> Is there any solution for the issue when you switch tabs and run into a tab with insert mode?

It would be odd to exit insert mode when returning to a tab.

**Comment by shibumi** [comment]
@smblott-github  thanks! `Escape` and then `Tab` works indeed. You should add this to the `README`.

I will close this issue
