### ISSUE TITLE
Shortcuts doesn't works in non-English languages

### ISSUE THREAD

**Issue by 123yagel** [philc/vimium#2389]
I'm using also Hebrew beside English in my computer, and the shortcuts doesn't works.

It very good add-on now, and it will be even greater with that change.

**Comment by smblott-github** [comment]
Might this help, @123yagel... on the [wiki](https://github.com/philc/vimium/wiki/Key-Mappings#hebrew-language-keyboards)?

**Comment by 123yagel** [comment]
It helps in the regular shortcuts, but not with opening links (by f or F key) - If I want to open a link, I press f, then some letters, but if I on Hebrew, It doesn't work.

another problem is for more langs. I was lucky that Hebrew exist in the list there, and I need to search for it. I think it need to be included automatically.

I very like vimium, but it can be better.

**Comment by smblott-github** [comment]
> but not with opening links (by f or F key)

You can set the characters to use on the options page (under *Advanced Options*, at the bottom).

**Comment by 123yagel** [comment]
I can change everything, even editing the source code, but I think that every program has to be easiest to use and setup.
For example, when I want to copy, I use Ctrl+c and without any especial setup, ctrl+ב also works (ב is the same key as c in the keyboard) on most of the programs.

I didn't read the source code, but I can guess that vimium can use key-codes instead of regular chars.
For example this works the same for 'c' and 'ב': 
http://keycode.info/
(disable vimium to use it..)

I can give some help for this - just tell me what to code.

**Comment by lydell** [comment]
[VimFx](https://github.com/akhodakivskiy/VimFx/) has the following option:

> - [x] **Ignore keyboard layout**  
>   Pretend that the en-US QWERTY layout is always used.

It's great for people who use several keyboard layouts! You might want to "steal" that :)

(There's also an advanced options called [translations](https://github.com/akhodakivskiy/VimFx/blob/85b5ab7794814636e09a2c5f6034c69c7257d2d8/documentation/options.md#translations) in case you want VimFx to pretend that some other layout than en-US QWERTY is always used.)

**Comment by sorsdt** [comment]
Unfortunately currently using digits for that purpose

**Comment by iocanel** [comment]
+1

**Comment by OrDuan** [comment]
+1 This is a must-have feature

**Comment by tmwatchanan** [comment]
Agree with @123yagel  and @lydell. Any update here?

**Comment by lydell** [comment]
@tmwatchanan This was added in #2626, but it seems closing this issue was forgotten. You need to click “Show advanced options” to find the checkbox, I believe.

**Comment by tmwatchanan** [comment]
Alright. This issue can be closed now. BTW. Thank you @lydell.
This extension appeals to me.
