### ISSUE TITLE
Request: Send escape key to webpage in insert mode

### ISSUE THREAD

**Issue by spenthil** [philc/vimium#239]
Would be nice to have a way to send an escape to the actual page in insert mode
instead of going back to normal mode?

The most important motivation for me is being able to close chat windows in gmail from the keyboard - which necessitates sending an escape in insert mode. Yes, I am aware you could simply disable vimium for gmail - but I like being able to use vimium *and* gmail shortcuts.

**Comment by smblott-github** [comment]
Fixed: #1985.
