### ISSUE TITLE
map a key[sequence] to the enter #13 key

### ISSUE THREAD

**Issue by dtschmitz** [philc/vimium#2391]
Thank you so much for all of your work on Vimium.
I have set up the 'Characters used for link hints' with the following array:

fdsartgbvecwxqyiopmnhzulkj

It works well for the most part.

Now, for example, if I want to open a tab and then goto youtube, a simple key sequence using the 'left hand' is:

yt

However, to select the chrome browser url for youtube.com, one must press enter or use the mouse to click with the 'right hand'.

My thinking is this: map a key or key sequence to the 'left hand' to result in enter (0x13) being pressed.

The efficiency would obviate the need for the right hand in many situations.

Is there a way to accomplish this through options?  If so how?

Otherwise, let this issue serve as a 'feature enhancement request'.

Kind regards,
Dietrich

**Comment by 2tolik** [comment]
In ulr-bar or omnibar user can type anything with Enter as confirmation. Link hits - finalized list. Even "open bookmark" mode is waiting for user to check that filtered selection is right.
workaround: Enter could be additionally mapped on a system level. CapsLock or ~ is good candidate.

For windows10 there is free tool that creates .reg to re-map keyboard using built-in mechanism:  https://www.howtogeek.com/howto/windows-vista/map-any-key-to-any-key-on-windows-xp-vista/
or directly https://github.com/randyrants/sharpkeys

**Comment by dtschmitz** [comment]
Thank you for your reply.
