### ISSUE TITLE
Completely disabled 

### ISSUE THREAD

**Issue by jeremiahlukus** [philc/vimium#2392]
I have installed this however i cannot get it to work. It is disabled on the toolbar. I restarted my browser, and gave it permissions for everything enabled it then disabled it restarted the browser then enabled it again and restarted the browser. When I click on the extention there is a gray box around it but nothing changes. The logo is also gray all the time. I am unsure what else i can do. I am on a mac running el caption. 

Thanks for all your work on this.

**Comment by smblott-github** [comment]
Sorry, @jeremiahlukus.  No idea what the problem here could be.  What version of Chrome are you using? Is this the Chrome Store version of Vimium?

**Comment by jeremiahlukus** [comment]
Yes it is from the Chrome store. It only works on very few websites. Is this normal?

**Comment by jeremiahlukus** [comment]
After a few weeks i reinstalled it now it works perfectly.
