### ISSUE TITLE
Vimium can't initialize icons with chromium --disable-reading-from-canvas option

### ISSUE THREAD

**Issue by xatier** [philc/vimium#2397]
It seems like Vimium relies on canvas to draw icons during initialization [1]. The icons will not be initialized correctly if `--disable-reading-from-canvas` option is set in chromium.

[1] https://github.com/philc/vimium/blob/849829d41469e113fc81cbe1b65d32b511e59905/background_scripts/main.coffee#L257

**Comment by smblott-github** [comment]
We have to draw the icons dynamically to work around a Chrome bug.  See discussion in #2055 and #2070.  See also [here](https://bugs.chromium.org/p/chromium/issues/detail?id=596605&q=setIcon&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&sort=-id).

I checked quickly, and the chrome bug has not yet been fixed (Chrome 55), so we're still stuck with that workaround.

**Comment by xatier** [comment]
I see. Thanks for your prompt response.
