### ISSUE TITLE
Drop-down menu doesn't open (but it worked fine some time ago)

### ISSUE THREAD

**Issue by zzaponka** [philc/vimium#2398]
Hi!

Thanks for the extension, I use it heavily. On Zimbra mail service's web-client there is a drop-down menu called "Move to..." where you can choose folder where the letter currently open has be moved to. It worked well some time ago, but now doesn't. How can I check where the changes are what changed this?

Thanks in advance.

**Comment by smblott-github** [comment]
You could be seeing this: https://github.com/philc/vimium/issues/2257.

**Comment by zzaponka** [comment]
Oh, I'm sorry for the duplicate, if so. This can be closed, then?

Thanks.
