### ISSUE TITLE
Is there a way to open multiple links at once?

### ISSUE THREAD

**Issue by rahidelvi** [philc/vimium#2402]
<kbd>Shift</kbd> + <kbd>F</kbd> allows us to open links in a new tab. Is there a way to open several links on a page at once?

**Comment by innaterebel** [comment]
Add count prefix before hitting `f`/`F`.
For example, `3` then `F` allows you to open three links in new tabs at once.

Or you can use `Alt`+`f` to open indefinite links in new tabs, but you have to manually cancel with `Esc` in this mode.

**Comment by rahidelvi** [comment]
Thank you for the tip @innaterebel, exactly what I was looking for!

**Comment by ixnv** [comment]
https://www.youtube.com/watch?v=0-bDBMwcm10
https://www.youtube.com/watch?v=oJ4huVMPcGg
https://www.youtube.com/watch?v=SeAAi7jWOl8
https://www.youtube.com/watch?v=sz-yVfChwNU
https://www.youtube.com/watch?v=4ihnp6UPtmQ
https://www.youtube.com/watch?v=pZgnhXn7tW0
https://www.youtube.com/watch?v=BLJZnJe7KgU
https://www.youtube.com/watch?v=VyuVnr77IoU
https://www.youtube.com/watch?v=R_u-FsCo57o
https://www.youtube.com/watch?v=l3_dedjucgM
https://www.youtube.com/watch?v=IBdISuGnxpQ
https://www.youtube.com/watch?v=iJFSrlpcFUI
https://www.youtube.com/watch?v=Tr8ZgF4Dc0E
https://www.youtube.com/watch?v=7wGnoEvbptk
https://www.youtube.com/watch?v=Txa-pIj6SCA
https://www.youtube.com/watch?v=oAXrRWLKzko
https://www.youtube.com/watch?v=mQAfG3DgG7M
https://www.youtube.com/watch?v=8lIiuU10OQc
https://www.youtube.com/watch?v=gyJCjbXzcKc
https://www.youtube.com/watch?v=BU8HEzAcKGc
