### ISSUE TITLE
Help tips for f and F are backwards

### ISSUE THREAD

**Issue by ddickstein** [philc/vimium#2405]
When I bring up the help dialog it says

<kbd>f</kbd> Open a link in the current tab
<kbd>F</kbd> Open a link in a new tab

In my experience, the opposite happens.  Either the help text needs to be updated or there is a bug.

**Comment by ddickstein** [comment]
Update:  It seems like these work correctly on facebook.com but reversed on github.com?

**Comment by smblott-github** [comment]
Are you pressing `Shift` when typing the last hint character?

**Comment by ddickstein** [comment]
Ah that must have been it.  My mistake, thank you!
