### ISSUE TITLE
createTab not working with specified URL?

### ISSUE THREAD

**Issue by ddickstein** [philc/vimium#2408]
It's possible that the comment for the syntax is out of date, but when I tried adding

    map c createTab http://www.bbc.com/news

as per [this suggestion](https://github.com/philc/vimium/blob/849829d41469e113fc81cbe1b65d32b511e59905/background_scripts/main.coffee#L149), when I press <kbd>c</kbd> a new tab is opened but it opens to the general new tab URL I specified in my options instead.

**Comment by smblott-github** [comment]
That feature hasn't been released yet, as noted [here](https://github.com/philc/vimium/wiki/Tips-and-Tricks#creating-tabs-with-urls).

**Comment by ddickstein** [comment]
Ah okay, eagerly awaiting then :)
