### ISSUE TITLE
Feature Request: regular expression search

### ISSUE THREAD

**Issue by monking** [philc/vimium#2411]
I'd like to search with regular expressions in the search prompt that appears when `/` is pressed. Even limited search that matches only within one text node would be helpful.

Google Chrome	55.0.2883.95 (Official Build) (64-bit)
Revision	a97b1aab33877677c4734c58ed41246aa40942b7-refs/branch-heads/2883@{#738}
OS	Mac OS X 
Vimium version: 1.57

**Comment by smblott-github** [comment]
That's already available, @monking.

See the options page, under *Advanced Options*:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/22321600/101d2530-e38e-11e6-92f3-4dd0568b9253.png)

**Comment by monking** [comment]
Excellent! I hadn't noticed that button.
