### ISSUE TITLE
unmapAll does not unmap numbers

### ISSUE THREAD

**Issue by ddickstein** [philc/vimium#2412]
I used `unmapAll` followed by a few mappings I wanted to preserve and the rest of the keys seem to get through fine but Vimium seems to capture numbers.  My current work-around is to exclude them on all websites (see image), but I'm pretty sure this is a bug.

<img width="554" alt="screen shot 2017-01-26 at 9 47 36 pm" src="https://cloud.githubusercontent.com/assets/802511/22361728/643ef35e-e411-11e6-9124-331403797ec7.png">

**Comment by smblott-github** [comment]
I'm not sure I'd consider it a bug, @ddickstein, because the number keys aren't really something we map and unmap.  Your workaround is what I would suggest for this case.

**Comment by ddickstein** [comment]
Hmm, well if not a bug then maybe surprising behavior :)
