### ISSUE TITLE
Feature request: Use the link's name and capital letters for link-hint filtering

### ISSUE THREAD

**Issue by Tunous** [philc/vimium#2414]
This is a request for a feature similar to *"Use the link's name and numbers for link-hint filtering"* with a difference that it would be possible to use capital letters instead of numbers to follow hints. I didn't find any existing setting for that and setting only capital letters as characters used for link hints didn't give expected results.

How this feature would work is that typing in lower case would follow links by text matching and use of capital letters would follow links by hints. It is the exact behavior that I am using in [VimFx](https://github.com/akhodakivskiy/VimFx) extension for Firefox.

**Comment by asmer** [comment]
really I need at least same keybindings for same URLs in <a href='url_here'> This will associate in mind something like 'go' - google, 'im' for instant messages in some social network, 'gm' for gmail, so on. No matter.

or fork && pull request? :-)

**Comment by smblott-github** [comment]
Unfortunately, `<Shift>` already has a meaning.  It changes `f` to "Open in a new tab".  So capital letters aren't available.

(I'm not completely wedded to that meaning for `<Shift>`.)

**Comment by Tunous** [comment]
VimFx uses `f` to open link in the current tab and `F` to open link in a new tab. You can also hold control and press last hint character to toggle whether to open in a new tab or not and alt + last hint character to toggle whether to open a link in a background or foreground tab.

All of this and more is explained in detail in its [documentation](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/commands.md#the-hint-commands--hints-mode). It's definitely worth a read as this behavior works really, really well for me when using Firefox and VimFx.

**Comment by ahstro** [comment]
Is anyone looking into this? I wouldn't mind getting my hands dirty, since this is the one feature I miss the most from VimFX and that I'd like to get back before my muscle memory is all messed up. 😅

**Comment by smblott-github** [comment]
Sure, go ahead and have a look.  Contrary to my comment above, `<Shift>` does not currently have a special meaning for filtered link hints.  (Or, at least, it's broken, and has been for some time.)

**Comment by ahstro** [comment]
Yeah, I tried using it but couldn't get it to work. Plain `F` works as expected though, so regardless, I don't think dropping the supposed `<Shift>` functionality would be too big of a loss.

**Comment by mrmr1993** [comment]
> Or, at least, it's broken, and has been for some time.

@smblott-github it still works for me, and I've been using it. I'll check it when I get home, just to make sure we haven't broken it recently. I think the other people from e.g. #1096 would be annoyed by it disappearing too.

> Is anyone looking into this?

I've been thinking about implementing this (with `/` to enter filter mode, rather than using `shift`) for a while, but I haven't done anything proactive about it. Feel free to work on this.

**Comment by smblott-github** [comment]
> @smblott-github it still works for me, 

It's broken for filtered hints only.  Should be fine for alphabet hints.  It's because we're using `event.key` and, for filtered hints, the shifted character is unrelated to the unshifted character.

**Comment by ahstro** [comment]
>It's broken for filtered hints only.

So it should be okay to implement this feature without stepping on anyone's toes?

**Comment by smblott-github** [comment]
I understand @mrmr1993's edited comment to mean `<Shift>` is working for alphabet hints but not for filtered hints.  And nobody seems bothered that it's broken for filtered hints.

So, for filtered hints only....

- No new setting on the options page.
- If the hint character is a letter, then `<Shift>`-letter selects the character.

**Comment by mrmr1993** [comment]
> > It's broken for filtered hints only.
>
> So it should be okay to implement this feature without stepping on anyone's toes?

Filtered hints have it implemented already, just without needing shift. Implementing it for alphabet hints by removing the existing shift behaviour steps on toes.

**Comment by smblott-github** [comment]
Fixed in #2701.
