### ISSUE TITLE
Request: Add 'Duplicate tab' feature

### ISSUE THREAD

**Issue by wcbeard** [philc/vimium#242]
I don't even know how to get Chrome to duplicate a tab without using the mouse (right-clicking on the tab), so I think this command would be another great niche for Vimium.

Not sure what the default key should be, but perhaps something like 'p'? Since yy copies the current URL, it'd be like pasting the current url in a new tab. It might make more sense to have 'p' open a new tab and paste in whatever's on the clipboard, but something along those lines?

**Comment by rrsahutwo** [comment]
We are best packers and movers in Bangalore who comprehend the nature of your content or items and therefore, help you accordingly. Our expert packers package your baggage with top great high quality of content. The way of packaging and the content we use for the process better suits the nature of the product. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
The encounter of packaging different types of items with their nature creates them secure during their transportation. Our alternatives are known for excellent packaging and transportation. The efficient alternatives create us apart from our competitors. It is the proof of our efficient packaging and movers of our company entitled #Expert5th.in. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
Apart from that, our great quality moving alternatives also assure top great quality, protection of your useful items during transportation.
However, as per the need of people, the process of moving is divided into two different Expert categories. These two Expert categories consist of personal moving and professional moving. You can contact the corporate moving also for the professional moving. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
When people need to shift their workplaces, company and shops, they need to moving and transportation features. Our Bangalore packers and movers are knowledgeable to deal with all the actions and process of professional moving Expert categories. Our group can handle all factors such as moving like corporate moving, company moving, workplace moving, commercial items moving, shop moving and so on. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by ajwadjaved** [comment]
You can do this with `yt` now
