### ISSUE TITLE
Feature Request: Temporary faster scrolling 

### ISSUE THREAD

**Issue by zyklotomic** [philc/vimium#2422]
I'm not sure if many people would be interested in this. I am interested in implementing a feature so that when you double h,j,k,l, you can temporarily scroll faster. For example, `jj` will initiate a faster scroll down than just `j`.

**Comment by smblott-github** [comment]
Or, try `4j`.

**Comment by zyklotomic** [comment]
I know that works, but I think it is not as intuitive/convenient to use. I was thinking of double hit `jj` and hold. Having the option to have this shouldn't harm I think. Should I go ahead and make a pull request?

**Comment by dinhnv** [comment]
@zyklotomic Have you try `u` for UP and `d` for down? It is the same feature with Ctrl+U & Ctrl+D in Vim

**Comment by zyklotomic** [comment]
Not until now. Thank you for pointing that out. Exactly what I was looking for. Really appreciate the tip!
