### ISSUE TITLE
Select Element - Options not appearing with f command

### ISSUE THREAD

**Issue by sco-tt** [philc/vimium#2423]
I've noticed that when I use the `f` command on a `<select>` elements, the options no longer open up. I've tested on the latest version of Chrome Canary and Chrome on OSX, and Chrome on Windows 10. 

An example to test on: http://codepen.io/search has four select lists across the top.

**Comment by gdh1995** [comment]
This issue is the same as #2257 . Now we have no methods to open select dropbox since Chrome 53.
