### ISSUE TITLE
[Future] add shortcut for copy decoding current url

### ISSUE THREAD

**Issue by dima74** [philc/vimium#2430]
There is a shortcut "yy" for copy the current url to the clipboard. It copies encoding url, for example on page https://ru.wikipedia.org/wiki/Заглавная_страница it will copy https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0

It would be nice if you add shortcut for copying decoding url, "yd" for example.

Thanks for vimium!

**Comment by smblott-github** [comment]
I would have thought this is rather a bug with `yy`, no?

**Comment by dima74** [comment]
I think so too, but default behaviour of chrome when copying from omnibar is copy encoding url, so I thinked that vimium just follow chrome default behaviour. I will be happy if yy will copy decoding url (but I don't know will others like it too)

**Comment by philc** [comment]
Closing, because I think a separate command for this is too niche given the lack of interest since this was opened.
