### ISSUE TITLE
Use one letter for simple page having less than 26 links?

### ISSUE THREAD

**Issue by xnsua** [philc/vimium#2431]
The screen short is here
![screenclip](https://cloud.githubusercontent.com/assets/5655454/23124606/df463134-f7a8-11e6-94eb-c7abcc66bf1c.png)

we can see there is less than 26 links, but several links have two letters like 'SA'

**Comment by xnsua** [comment]
duplicated

**Comment by smblott-github** [comment]
You can set the keys to use for link hints on the options page (under advanced options).  If you add all 26 characters, then that's what you'll get.  By default, only the home row is used.
