### ISSUE TITLE
Not all commands need to wait for DOM ready

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#2432]
From the Chrome Store:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/23265415/67d77104-f9dc-11e6-924c-6800c842f203.png)

Commands like switching tab should be usable earlier than DOM ready.

**Comment by philc** [comment]
Yes, agreed, this can be very annoying.

**Comment by jamespullar** [comment]
+1 to this!

**Comment by mrmr1993** [comment]
AFAICT, there's nothing in the codebase that makes command listening wait for DOM ready. Testing (using "Network Conditions" in Chrome dev tools) seems to indicate that:
* we can (and do) successfully handle keys long before `DOMContentLoaded`
* we don't receive any events before the connection to the remote page has completed.
  - Our scripts are not run during this time, and the old page has been unloaded, so we can't do much here.
  - This is the most significant source of any delay -- especially when Chrome already has the maximum (10?) concurrent connections open.

The only places *we* introduce any delay (consistently <100ms on my machine) are:
* waiting for the `isEnabledForUrl` message to the background page to round-trip; and
* waiting for `chrome.storage.local.get` in the `NormalMode` constructor (to fetch the user's key bindings).

I think the current situation might be as good as it gets.
