### ISSUE TITLE
Port to WebExtensions

### ISSUE THREAD

**Issue by tecfu** [philc/vimium#2433]
[Vimperator](https://github.com/vimperator/vimperator-labs) (the leading Vim plugin for Firefox) is undergoing an end-of-life transition as the Firefox based XUL-type add on support is ending in that browser. 

There's a discussion at [Vimperator](https://github.com/vimperator/vimperator-labs/issues/705) about porting to the WebExtension API. Since "To a large extent the system is compatible with the extension API supported by Google Chrome and Opera." - https://developer.mozilla.org/en-US/Add-ons/WebExtensions it would seem desirable to unify the existing vim-like addon community into a project using this shared architecture. 

It also may be the case that Chrome inevitably forces its own add ons to conform to the WebExtension API. 

Regardless, I'm creating this issue to bring attention to the previously mentioned effort. Feel free to join the discussion [here](https://github.com/vimperator/vimperator-labs/issues/705).

**Comment by philc** [comment]
Thanks for the heads up @tecfu. We're tracking the work required to support Firefox in #2425 and Edge in #2076.
