### ISSUE TITLE
Enable Vimium for file:// URIs

### ISSUE THREAD

**Issue by bjornfor** [philc/vimium#2435]
Hi,

It seems that Vimium is disabled when browsing the local filesystem with ```file://``` URIs. Is it possible to enable it?

```
Vimium 1.57
Chromium	56.0.2924.87 (Developer Build) (64-bit)
Revision	b169b9a1cc402573843e8c952af14c4e43487e91
OS	Linux 
```

**Comment by bjornfor** [comment]
Hm, looks like that feature was implemented before (from README.md):


```
1.18 (2010-06-22)

Vimium now runs on pages with file:/// and ftp:///
```

But it doesn't work anymore.

**Comment by innaterebel** [comment]
For all extensions to start a life on file:// or in incognito windows...
[https://github.com/philc/vimium/wiki/FAQ](url)

**Comment by bjornfor** [comment]
Thank you! It works!
