### ISSUE TITLE
Separate scroll step setting into "vertical" and "horizontal"

### ISSUE THREAD

**Issue by 4lex1v** [philc/vimium#2436]
I'm was looking for a way to set different scroll steps for horizontal scrolling (`h` / `l` keys) and vertical one (`k` / `j` ones). The reason is that when my window size is halved, i want to have a small horizontal scrolling step (for precision) while the vertical one remain the same. Is there anything like that already?

**Comment by smblott-github** [comment]
Not currently.

I guess the idea is valid, although there doesn't seem to be much demand for it.

You might be able to work around by setting a small scroll-step size  (which applies to both cases) and then setting:

    map j scrollDown count=4
    map k scrollUp count=4

on the options page.  Tweak the constant.

**Comment by JohannesPertl** [comment]
> Not currently.
> 
> I guess the idea is valid, although there doesn't seem to be much demand for it.
> 
> You might be able to work around by setting a small scroll-step size (which applies to both cases) and then setting:
> 
> ```
> map j scrollDown count=4
> map k scrollUp count=4
> ```
> 
> on the options page. Tweak the constant.

works great, would you reconsider integrating it by default? I see no downsides

**Comment by philc** [comment]
hey @JohannesPertl, closing this as the demand is low (I've only heard about it twice in the last 8 years). Hopefully the work around on this thread is sufficient.
