### ISSUE TITLE
Feature request - automatically deselect text entry

### ISSUE THREAD

**Issue by KVohra95** [philc/vimium#2439]
Is it possible to automatically deselect all text entry elements on a page on load. I have quite a few websites I visit that automatically select elements on load which then mean that vimium cannot be used unless I press escape first.

Thanks

**Comment by smblott-github** [comment]
This is probably what you want, @KVohra95, on the options page...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/23457470/0ddd1706-fe70-11e6-9f7b-51bf1ac1042b.png)

**Comment by KVohra95** [comment]
Ah sorry that is exactly what I wanted, didn't see it the first time :)
