### ISSUE TITLE
LinkHints.activateModeWithQueue broken

### ISSUE THREAD

**Issue by kseyhan** [philc/vimium#2445]
Hi, since a couple of days vimium wont work as expected anymore. The LinkHints.activateModeWithQueue Mode started to behave like the LinkHints.activateModeToOpenInNewTab Mode where it just opens one link in background and the hints disapear after. This new behaviour is reproducable on multiple machines with different OS's varring from Windows to some Ubuntu Maschines.

This is the keymapping that i'm using:

unmap F
map F LinkHints.activateModeWithQueue
unmap J
map J scrollPageDown
unmap K
map K scrollPageUp

**Comment by smblott-github** [comment]
Thanks @kseyhan -- and sorry about that.  My bad.

That's fixed [here](https://github.com/philc/vimium/commit/10dcaa389958483a988a5bd86d3fd3d4e2799a77).

**Comment by kseyhan** [comment]
oh.. you made my day! thanks! :+1:
