### ISSUE TITLE
Key mappings: Cannot map modifiers to movements. 

### ISSUE THREAD

**Issue by tecfu** [philc/vimium#2449]
Example:
```
map h 10j
```

Should work but does not. 

OS: Ubuntu 14.04.3
Chrome Version: 49.0.2623.112
Vimium: 1.58.1

**Comment by smblott-github** [comment]
The Vimium way of doing this is...

    map h scrollDown count=10

**Comment by tecfu** [comment]
Thank you very much for the speedy response. If this isn't documented, can we add it somehow? Especially helpful would be an example in:
```
chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/pages/options.html
```
Perhaps in the examples.

**Comment by smblott-github** [comment]
It's documented on the wiki (along with quite a number of other features): [link](https://github.com/philc/vimium/wiki/Tips-and-Tricks#custom-key-mappings-with-a-count).

**Comment by tecfu** [comment]
Got it. Thank you for that.
