### ISSUE TITLE
Can't use all command after type '/[search word(multi byte str)]'

### ISSUE THREAD

**Issue by yuntas** [philc/vimium#2451]
|chrome version|vimium version|
|:---:|:---:|
| 57.0.2987.110 (64-bit)|1.58.1|

**Comment by yuntas** [comment]
when type '/ [search word(LANG=EN)]' , Can use all command.

But, Can't use after type [multi byte word]...

**Comment by gdh1995** [comment]
The find HUD works well after typing Chinese search words, on my Chrome 57 x64.

You might forget to exit `find` mode - press `<esc>` or `<enter>` to exit the mode and return to normal command mode.

**Comment by yuntas** [comment]
thanks for answer, @gdh1995

I resolved this problem.
Due to IME(Input Method Editor), I wasn't able to all command after `find` mode.

1.  `/`
2. IME on
3. type `[search word(multi byte str -> ex.) JP)]`
4. IME off
5. can use `n` or `N`
