### ISSUE TITLE
can't disable keys for ssh.cloud.google.com ssh web client

### ISSUE THREAD

**Issue by baracoder** [philc/vimium#2458]
Somehow i can not disable the plugin for the ssh client on google cloud console. I tried to add differnt rules but the keys stay active. I have to disable the plugin completely.

**Comment by smblott-github** [comment]
Please provide either a link, or instructions on how to reproduce.

**Comment by smblott-github** [comment]
Actually, I guess this is some kind of SSH terminal running in the browser.

Do you mean "disable keys" (as in, just some keys) or disable Vimium on the site?  I guess the latter.

The problem might be that the SSH/terminal part is running in an iframe or something.  The exclusion rule you'd need would have to match the URL of the iframe (not the URL of the tab).

**Comment by dusu** [comment]
@baracoder Solution: Add a new rule for vimium, set it's patterns as "about:blank", then save changes, that's it.

As @smblott-github  said, the terminal is running in an iframe, finally i found this iframe's url is "about:blank". You can check it by typing "document.getElementById('terminal').getElementsByTagName('iframe')[0].contentWindow.location.href" in the Chrome DevTools' console.

**Comment by benjaminvdb** [comment]
@dusu: such a coincidence that you posted about this 6 hours ago! It's definitely working for me. Thanks for the fix!

**Comment by baracoder** [comment]
sorry for the lack of details on how to reproduce the issue.

@dusu thanks, adding a rule for `about:blank` works!
