### ISSUE TITLE
Feature request: Vomnibar add tab searching & priority

### ISSUE THREAD

**Issue by rtgoodwin** [philc/vimium#2459]
Vomnibar is fantastic, and already covers URLs, history, and bookmarks. But "T" is still required to search your open tabs. It would be great if:

1. tabs could be searched in Vomnibar
2. you could assign a priority to Vomnibar search. Example, "tabs, bookmarks, history" vs "history, bookmarks, tabs". This may not be needed if "tabs" was an option to add, if it had priority over history. But, as with all things, giving the user choice is often best. 

Quick Tabs has idea 1 and I find it reduces the mental load when I can't remember if I have something open in my 90 tabs or if it's off in a history or bookmark (which may already be open...now I have 91 tabs :) ). I use Great Suspender to suspend tabs and reduce Chrome memory, so it's quite often that I'll have a tab open already and have forgotten about it. 

It seems probably trivial, but I couldn't quite grasp the source enough to make a PR.  Thanks to everyone who contributes to this amazing extension!

**Comment by mklinga** [comment]
I would love to see priority option on the vomnibar. Often I just press `O` instead of `B` and all I can find is history results from a page that I have also bookmarked, so I need to `<Esc>` out and press `B`.

**Comment by zakvdm** [comment]
I think the single place where you can search all things, be it currently open tabs or bookmarks/history is very powerful from a usability perspective.

**Comment by philc** [comment]
With #2656, we'll now show tab search results in regular Vomnibar, just like Chrome's Omnibar. That will go out in the next release of Vimium. Thanks for filing the idea!
