### ISSUE TITLE
Doesn't work on local files

### ISSUE THREAD

**Issue by spenthil** [philc/vimium#246]
Doesn't work on local files. 

Reproduce by:
1. open html file from local disk in chrome with vimium extension
2. try using vimium shortcuts

from a bit of googling, it seems "file://" needs to be in the match pattern - although I have no clue what that means :)

**Comment by jmn** [comment]
Testing MHTML files in chrome canary (chrome://flags #save-page-as-mhtml) I noticed that vimium does not work for browsing these files. Chrome version 44.0.2396.0 canary (64-bit) and Chromium 44.0.2396.0  on Windows 8.1. For other local files, vimium does seem to work fine having enabled the option mentioned above.

**Comment by mrmr1993** [comment]
@jmn can you open a new issue for this so the discussions don't get confused and this doesn't get overlooked?

**Comment by rrsahu** [comment]
Once we create sure that they are best to cope with then next come enquiry section. Through this enquiry form, you would be able to examine information of all popular Companies in your town.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by rrsahu** [comment]
The objective of this simple form is to get an concept about your specifications. Once we are sure about it, we will record you best Company information within few minutes only. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers Delhi">Packers and Movers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>

**Comment by rrsahu** [comment]
Quotations are usually available from all major Companies and it is simple to get concept about their solutions. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers Chennai">Packers and Movers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers Noida">Packers and Movers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers Navi Mumbai">Packers and Movers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers Thane">Packers and Movers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers Ghaziabad">Packers and Movers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers Faridabad">Packers and Movers Faridabad</a>

**Comment by rrsahu** [comment]
These Information mill not only providing product packaging and movers in Bangalore but other significant places as well.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by Strangehill** [comment]
a different workaround, depending on the use case, is to use a server. a one-liner such as `python -m http.server 1234` can do the trick.

**Comment by fabriziobertoglio1987** [comment]
solved with vimiumc
