### ISSUE TITLE
The selected text can not be unchecked

### ISSUE THREAD

**Issue by Bpazy** [philc/vimium#2461]
Google Chrome: `57.0.2987.110`
OS: `Windows10`
Vimium Version: `1.58.2`

I am having trouble while using vimium and the problem disappears after disabling vimium.
Here is the problem gif(The selected text can not be unchecked unless click the other line):
![problem](https://cloud.githubusercontent.com/assets/9838749/24355833/0836ba68-132a-11e7-8c7c-f2d5b209d27a.gif)
<br>
Here is the gif after I disable vimium:
![normal](https://cloud.githubusercontent.com/assets/9838749/24355878/3b13a6e4-132a-11e7-859f-6aeb414f9136.gif)

After many attempts I found this is the problem of vimium, the problem still exists after reinstalling Chrome And Windows10. But there's no problem with my other Windows device even though they have same extension.

**Comment by smblott-github** [comment]
Cannot reproduce on Debian with Chrome 57.0.2987.110.

Anybody else?

**Comment by Bpazy** [comment]
No one else has this problem.

**Comment by gdh1995** [comment]
In my tests on Chrome 57...88 x64, Vimium has no influence on the selection behavior. And it only depends "what pixel" you click whether a selection range will collapse.

My meaning of "what pixel" is, I can not tell where to keep or where to collapse clearly, but all 4 cases have been found.

**Comment by Bpazy** [comment]
This issue has disappeared in the `Chrome x64 64.0.3282.119`
