### ISSUE TITLE
Make vomnibar suggestion URLs editable in the vomnibar input.

### ISSUE THREAD

**Issue by suptimal** [philc/vimium#2464]
i want to use the highligthed entry. for example i type "git" -> [TAB] -> [CTRL+SPACE]:
![108d7d0f-25f2-45d4-8582-20be6ebc96ef](https://cloud.githubusercontent.com/assets/4957651/24695027/7afd7080-19e4-11e7-816c-17e70ac707dd.png)
and get 
![c154ff97-00ea-428a-959b-6af7824193cb](https://cloud.githubusercontent.com/assets/4957651/24695509/68c74b8c-19e6-11e7-81c0-d6271d1ea042.png)

**Comment by smblott-github** [comment]
I don't understand the problem.

> i want to use the highligthed entry

So hit `<Enter>`?

**Comment by blendi-93** [comment]
enter opens the url. I want a update of the input field, to modify the url.
for example.
after visiting github.com/baskerville/bspwm i have github.com/baskerville/bspwm in my history, if i want to visit github.com/baskerville/xdo for the first time i have to retype the whole url.

but i want to "reuse" to old entry and modify it by searching for bspwm select github.com/baskerville/bspwm hit [ctrl+space] and have github.com/baskerville/bspwm in the textfield so i can remove bspwm and replace it with xdo.

**Comment by smblott-github** [comment]
Ah.  That makes more sense.

**Comment by blendi-93** [comment]
thx for fixing my title ;)

i dont think its a widely used feature but i would like something like that (used ff and vimperator before)

**Comment by gdh1995** [comment]
+1

BTW, my [Vimium++](https://github.com/gdh1995/vimium-plus) has implemented this feature.

**Comment by Gu1nness** [comment]
Can I take this one ?

My expected behaviour for this would be that as soon as tab is used, the input in the vomnibar is modified accordingly with the url (the way I used to do when using VimFX in firefox).

**Comment by smblott-github** [comment]
@mrmr1993 What do you think about this?

- For searches, populate the input with the previous search terms (as it does currently).
- For URLs (bookmarks and history), populate the input with the URL.

In both cases, the user can continue editing.

**Comment by mrmr1993** [comment]
@smblott-github sounds good to me!

**Comment by smblott-github** [comment]
@Gu1nness Have a look, if you like.  Make sure and look how things work at the moment for search suggestions.  Try to use the existing infrastructure.  (As I recall, that bit of the code is pretty tangled.)

**Comment by Gu1nness** [comment]
Ok, I'll have a look as soon as I finish my exams :)
I agree for the <c-Space>, I don't like it either.

@smblott-github Just to be sure, when you are speaking of searches, do you mean custom searches like Wikipedia, or duckduckgo ( `w potato` for example)?

**Comment by Gu1nness** [comment]
Hi.
Sorry for the long delay.
Here is my proposed patch, if it suits you, I will do a MR :)

**Comment by smblott-github** [comment]
Well that's nice and concise, @Gu1nness.  Submit a PR and I'll try it out.

Looking at it now, however, how does the user get back to the input to edit the URL (without clicking)?

**Comment by Gu1nness** [comment]
Hi @smblott-github , did you have the time to test the patch ?

**Comment by fabrei** [comment]
+1 but what about the status now? this feature is not working for me in firefox 67.0.4

**Comment by gdh1995** [comment]
@fabrei The PR has not been merged. Vimium developing is a bit slow in recent months.

**Comment by philc** [comment]
I wish this was easier to discover. It would be cool to somehow have an opt-in cheat sheet built into Vomnibar, in the same spirit as typing "?" in Vimium. For now, I've documented this feature on [this wiki page](https://github.com/philc/vimium/wiki/Tips-and-Tricks).
