### ISSUE TITLE
Switching between spaces on Mac causes Vimium to spam keys

### ISSUE THREAD

**Issue by jamespullar** [philc/vimium#2467]
I've been encountering this bug for quite a while now. I use full-screen spaces on Mac very frequently. I also use keyboard shortcuts `ctrl+h` and `ctrl+l` for navigating between spaces on my desktop.

When I navigate between spaces and eventually return to Chrome, the first key I press on the tab will get stuck and spam. Most commonly, I press `f` and the link hints flicker on and off repeatedly. The easiest way to resolve this is to use `cmd+r` to refresh the page. If I use Vimium shortcuts to scroll on the page, it will also get stuck and continuously scroll until the top/bottom of the page.

* macOS Sierra 10.12.3
* Chrome 56.0.2924.87 (64-bit)
* Vimium 1.58.2

If you would like a video of this in action, let me know!

**Comment by smblott-github** [comment]
That sounds really weird.

If it's not too much trouble, then a video might be helpful.

(Separately, 1.59 is rolling out at the moment.  1.59 does make changes to key handling.)

**Comment by jamespullar** [comment]
![](https://i.imgur.com/gEYxSE5.gif)  

I'm most successful in recreating this when I open a new Chrome window and have another application using a space in between the two windows.

You can see initially link hints and scroll with `j` and `k` are working normally. Then I open a new window with `ctrl+n`, visit a new site, and return to the original Chrome window. I'm navigating between the spaces using `ctrl+h` and `ctrl+l`.

**Comment by jamespullar** [comment]
Closing as newest version of vimium seems to clear this up!
