### ISSUE TITLE
Quickly select and copy text on screen

### ISSUE THREAD

**Issue by Armagedoom** [philc/vimium#2469]
I have been using VimFx for a while, and there is a feature which I really miss here, but perhaphs there is another way to do it.
When I press "v", a lot of taggs appear on the screen, same as with "f", but when pressed, locate a caret there, so you can shift-right and then copy your selection.
How could I match this behavior (IE: quickly select something on the screen) with vimium?
Thanks!

**Comment by smblott-github** [comment]
I usually use visual mode for this.

First, put the selection where you want with `/`, then `v`.  Most basic vim movements work, as does `o`.  Use `y` to yank.

**Comment by Armagedoom** [comment]
awesome, thanks!
