### ISSUE TITLE
How to disable ctrl-[

### ISSUE THREAD

**Issue by bigeagle** [philc/vimium#2473]
Hi there,

I was using jupyter notebook, where `ctrl-[` is a required keyboard shortcut, but it is hijacked by vimium.
I tried to `unmap <c-[>` but this does not work.

So what should I do to disable it?

Cheers,
Justin

**Comment by smblott-github** [comment]
See [here](https://github.com/philc/vimium/wiki/Tips-and-Tricks#key-mapping).

**Comment by bigeagle** [comment]
It works! Thanks a lot!
