### ISSUE TITLE
Feature request: make 'o' (and maybe some other similar) shortcuts available in 'new tab' window

### ISSUE THREAD

**Issue by karolis-k** [philc/vimium#2479]

**Comment by karolis-k** [comment]
Maybe this could be configured in Extensions Keyboard shortcuts configuration window. 

This could apply for shortcuts most shortcuts in 'Using the vomnibar' and 'Manipulating tabs' sections.

For me most useful would be 'Open URL, bookmark or history entry'.

**Comment by karolis-k** [comment]
Maybe this could be configured in Extensions Keyboard shortcuts configuration window. 

This could apply for shortcuts most shortcuts in 'Using the vomnibar' and 'Manipulating tabs' sections.

For me most useful would be 'Open URL, bookmark or history entry'.

**Comment by smblott-github** [comment]
The omnibar is available on `chrome://newtab`:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/25118128/ccb6e168-240c-11e7-8aec-bf839f30f955.png)

The problem might be that the focus ends i[ in the omnibox.

Off topic... I (wrote and) use [this](https://chrome.google.com/webstore/detail/new-tab-url/njigpponciklokfkoddampoienefegcl) to get this problem.

**Comment by karolis-k** [comment]
You're right. 

Thanks for info!

I am closing the issue.

**Comment by gaving** [comment]
@smblott-github Cheers for the heads up about the extension, solved a major annoyance!

**Comment by david-gretzschel** [comment]
This is awesome. Please make this more findable and/or part of the vimium documentation. Without it, vimium is really broken, if you're used to open the 'new tab'-page to open a new tab, instead of using "O" (which I usually don't want, bcs. I don't want to be distracted by the old site, when thinking about the correct new site/search, I want to open).
