### ISSUE TITLE
Hard Refresh

### ISSUE THREAD

**Issue by MrJadaml** [philc/vimium#2486]
I find that I regularly want to perform a hard refresh `Shift+Command+r`. That 🖕 claw style binding really pulls your hands away from the home row. `Shift+r` aka `R` would be more comfortable. 

**Useful for lots of Vimium users**
- There are many times (especially for developers) where you want to make a request from the server and not potentially what is cached in the browser.
- Chrome does not allow for creating this binding.

**Require no/little documentation**
- just a single line

  F       open a link in a new tab
  r       reload
  **R       hard reload (not from cache)**
gs      view source

**Useful without configuration**
- no configuration required

**Intuitive or leverage strong convention from Vim**
- leverages the existing lowercase `r` keyword pattern

**Work robustly on most/all sites**
- MDN shows full browser compatibility
- same as `r` implementing `.reload()` but with `true` passed in to force request to server

| Feature | Chrome | Edge | Firefox (Gecko) | Internet Explorer | Opera | Safari |
|---|---|---|---|---|---|---|
| Basic support | (Yes) | (Yes) | (Yes) | (Yes) | (Yes) | (Yes) |

**Comment by krlooss** [comment]
I'm working on this issue, can you assign it to me?

**Comment by arizzubair** [comment]
I am using following configuration in vimium:
map R reload hard
map r reload

When I try to test whether R clears cache from this website (http://refreshyourcache.com/en/cache-test/ ) , pressing R does not clear cache. 
Chrome version: Version 64.0.3282.140 (Official Build) (64-bit)
Vimium Version: 1.62.4

**Comment by innaterebel** [comment]
And borrow the question, how do I exactly map the lower case `r` to do hard reload? Do I have to unmap `r` for normal reload first? Thanks in advance.

**Comment by smblott-github** [comment]
> pressing R does not clear cache.

Confirmed. However, that is just the behaviour of `window.location.reload(true)`.

As it happens, I just tried that [test page](http://refreshyourcache.com/en/cache-test/) with #2951 and it seems that, coincidentally, #2951 fixes this issue.

> how do I exactly map the lower case `r` to do hard reload?

    map r reload hard

> Do I have to unmap r for normal reload first?

No.

**Comment by arizzubair** [comment]
Hard reload issue is fixed in version 1.63. I have tested it.

**Comment by philc** [comment]
This was added as an advanced command under the keybinding "R" in #4445, which should make it more discoverable.
