### ISSUE TITLE
Firefox Vimium

### ISSUE THREAD

**Issue by eejdoowad** [philc/vimium#2490]
Just a heads-up. The firefox extension review process is slow and backlogged. You'll probably want to submit the firefox version of Vimium for review sooner rather than later. You can still submit revisions to extensions that are awaiting review.

I submitted my own Vimium-like [extension](https://github.com/lusakasa/saka-key) 5 weeks ago... and am 1/3 of the way through the queue.

**Comment by smblott-github** [comment]
Thanks.  I'll do that.
