### ISSUE TITLE
Make link hints instantaneous through pre-computation and caching

### ISSUE THREAD

**Issue by eejdoowad** [philc/vimium#2493]
Link hints are critical to the Vimium experience. Currently, every time the user hits F, link hints are calculated from scratch using the current DOM and viewport, which can be slow. Fortunately, it's possible to make them near instantaneous through pre-computation and caching. A speed up would allow supporting features that providing higher quality link hints but are expensive in terms of computation like #2410.

A few questions need to be answered first:
1) How expensive is each component of link hint computation?
1) What can be cached and when?
2) When should the cache be invalidated?

I'll leave those questions open.

The current link hint algorithm is something like this:

document
  .allNodes()
  .filter(isVisible and isClickable)
  .forEach(renderLinkHint)

Note that both visibility and clickability are always computed from scratch. But why? Although visibility changes often because the user usually scrolls, the overall document coordinates stay constant unless an element other than the document is scrolled. DOM mutations and window resizing are less common events that cause visibility to change. Clickability changes only on DOM mutations, which are less common, and only affect nodes in some subtree.

Here is one simple pre-computation/caching scheme:

When the document loads, compute and cache 1) the clickability of all elements and 2) their document coordinates. When the user hits F, use the current scroll coordinates to filter the clickable elements to determine those that must have hints rendered. Invalidate the hintability cache if a DOM mutation occurs. Invalidate the visibility cache if a DOM mutation occurs, the viewport changes, or 3) an element other than the document scrolls. Consider adding special logic to account for when the scrolling element is not the document element. Don't pre-compute hintable elements more than once a second. Pipeline computation so that the event loop isn't blocked for too long. Possibly segment the document into horizontal strips and assign clickable elements to horizontal strips to speed up determining which are in the viewport. Consider offloading computation that doesn't require DOM access to a web worker.

**Comment by mrmr1993** [comment]
> The current link hint algorithm is something like this:
> 
> document
> .allNodes()
> .filter(isVisible and isClickable)
> .forEach(renderLinkHint)

The algorithm is slightly more complex, resembling:
```
document.allNodes()
.filter(isVisible and inViewport)
.filter(isObscuredByAnotherElement)
.filter(isClickable)
.forEach(renderLinkHint)
```
which is painful, as it requires us to consider every element. (See #1355 for the PR, and surrounding conversation/context.)

> Although visibility changes often because the user usually scrolls, the overall document coordinates stay constant unless an element other than the document is scrolled.

Not if CSS styles change. Think [mobile wikipedia](https://en.m.wikipedia.org/wiki/Clean_room_design) with show-/hide-able sections, for example. The [attribute](https://developer.mozilla.org/en/docs/Web/CSS/Attribute_selectors), [sibling](https://developer.mozilla.org/en/docs/Web/CSS/General_sibling_selectors) and [decendent](https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_selectors) css selectors also mean that minor changes can have large and far-reaching consequences for styles.

> Note that both visibility and clickability are always computed from scratch. But why?

* The page may change drastically (eg. github, where navigation is done with JSON), or even just enough that our link hints are wrong (eg. different size advert/image, image finishes loading, size of a video player is adjusted, etc.)
* The computations are already slow, even though we don't perform the more expensive ones ([getComputedStyle](https://developer.mozilla.org/en/docs/Web/API/Window/getComputedStyle)) for elements outside the viewport. Precomputing everything means
  - potentially doing calculations we won't use (eg. for parts of the page the user doesn't visit/use link hints on), and may even throw out (on style/DOM/element scroll change).
  - doing the work when the user *isn't* expecting us to. So Vimium makes tab loading slow, randomly spikes CPU, etc. as far as the user is concerned.
  - using [MutationObserver](https://developer.mozilla.org/en/docs/Web/API/MutationObserver), which itself can be [expensive](http://stackoverflow.com/a/39332340)

**Comment by eejdoowad** [comment]
Thanks for the feedback. You're right... caching information seems to be insanely challenging and what I've described as is isn't very feasible.. You seem to have explored this in detail and considered many corner cases and exceptions that never crossed my mind.

I'll need to further examine what is realistic at some point in the future
