### ISSUE TITLE
permissions ask for too much

### ISSUE THREAD

**Issue by haroldcarr** [philc/vimium#2499]
Is there a technical reason why this needs:

- Read and change all your data on the websites you visit
- Read and change your browsing history on all your signed-in devices

?

**Comment by mrmr1993** [comment]
> * Read and change all your data on the websites you visit

We need access to every webpage you load so we can listen for keys on it, and to show the Vomnibar, HUD, and help dialog. The extension is useless without this.

> * Read and change your browsing history on all your signed-in devices

This is used for showing history in the Vomnibar. We don't necessarily *need* this, but `o` and `O` are pretty useless without it.

**Comment by haroldcarr** [comment]
Thanks for the clarification.

**Comment by DanielGGordon** [comment]
Wait why do you guys need to MODIFY the data I copy and paste? That's a new one...

**Comment by philc** [comment]
@DanielGGordon see discussion in #3489.
