### ISSUE TITLE
Firefox: opening link in new tab ('F' button) do not work.

### ISSUE THREAD

**Issue by mayanksuman** [philc/vimium#2510]
## Version
Vimium from github with commit 400602e (most recent)
Firefox: 53.0.2 (64 bit)

## Current Behavior
Opening link in new tab using 'F' button do not work. Firefox stop the page from making new tab/pop up.

## Expected Behavior
Using 'F button the link should open in new tab.

**Comment by mrmr1993** [comment]
[Firefox bug 1356309](https://bugzilla.mozilla.org/show_bug.cgi?id=1356309) is responsible. See also [Firefox bug 1348213](https://bugzilla.mozilla.org/show_bug.cgi?id=1348213), which is more active, related.

**Comment by steimntz** [comment]
The same behavior with Firefox 57.0b1 (64-bit)

**Comment by naclander** [comment]
@philc  Pull request #2602 is supposed to fix this? Can anyone confirm a fix? Firefox 57 hit beta so I expect the numebr of people affecting by this to suddenly increase ( vimium is the only viable alternative to vimFX which is no longer supported )

**Comment by smblott-github** [comment]
@naclander... I'll merge and release #2602 soon.  More feedback as to its efficacy would be appreciated.

**Comment by mrmr1993** [comment]
@smblott-github it doesn't seem like anyone apart from me is running a non-store version of Vimium on Firefox; at least, if they are, they're not being very vocal about it.

Since it doesn't make the situation worse, might it be worth pushing it out sooner and getting some testing in the field?

**Comment by smblott-github** [comment]
OK, @mrmr1993. I'll merge and push a new FF version in a couple of days.

**Comment by mrmr1993** [comment]
@smblott-github thanks, much appreciated.

**Comment by ronjouch** [comment]
Fix confirmed in 1.60.4 in Firefox Nightly 58.0a1 (2017-09-26). That settles making me a fully happy VimFx convert 🙂. Thanks for the continued maintenance!
