### ISSUE TITLE
visual studio online contenteditable

### ISSUE THREAD

**Issue by farmergreg** [philc/vimium#2523]
Vimium remains active inside content editable fields in Visual Studio Online. For example it mis-interprets keypresses inside this element as vimium commands instead of as text that I want to type: 

(inside an iframe):
`<body contenteditable="true" role="textbox" aria-multiline="true" aria-label="Description">text entered by the user</body>`

**Comment by mrmr1993** [comment]
Can't manage to repro this using current master. Can you provide some more detailed steps?

**Comment by farmergreg** [comment]
I think this might be related to something else going on in my Chrome install - I've seen misbehavior in other plugins too (specifically the plugin that re-enables the backspace key to go back in history.) Closing this for now since it's probably not a vimium bug. Thanks for the quick response!
