### ISSUE TITLE
Reorder tabs by moving current tab left or right

### ISSUE THREAD

**Issue by HaleTom** [philc/vimium#2526]
I'd like to be able to change the ordering of the tabs.

Eg, if I have tabs (* denotes the current tab):
`1   2   3*`

I'd like to be able to press a key, say `{`, and have the order be:

`1   3*   2`

And again press `{`  and get:

`3*   1   2`

**Comment by smblott-github** [comment]
You need the `moveTabLeft` and `moveTabRight` commands.

For a full list of commands go to the options page and click *Show available commands*...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/26520429/50cdb324-42ca-11e7-82f8-d4abd70e4cee.png)

Then click *Show advanced commands*...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/26520433/6bfde93e-42ca-11e7-9443-34c098c70d46.png)

**Comment by HaleTom** [comment]
Thanks! Adding:
```
map < moveTabLeft
map > moveTabRight
```
Doubled the speed at which I can reorder tabs.

**Comment by MatthewP-Prosper** [comment]
It would be awesome if this supported wrapping! i.e. if you move the last tab right it becomes the first tab and vice-versa
