### ISSUE TITLE
[Feature Request] Passthrough mode in Vimium.

### ISSUE THREAD

**Issue by SkyDiploma** [philc/vimium#2530]
Hi,
I personally love Vimium and have been using it for a while now. 

One problem that I always face is when I try to browse websites that also has shortcut bindings. Eg: inbox.google.com . If Vimium is on I cannot be thoroughly productive. So I essentially whitelist this entity there and have a monkeyscript that opens a new tab as an exit strategy.

I was wondering if we would be open to a new mode "passthrough mode". Where we disable the vimium key bindings on pressing a particular sequence of characters. That way, I would be able to use the native key shortcuts and exit from "passthrough mode" with <esc> or another key combination. 

I am not sure, how complicated this is to actually build into vimium. But I can definitely give this a shot in implementing this. 

Just to add precedence to this: i3wm a keyboard based window manager also does this to disable their bindings while gaming for example.

Thanks for all the great work!

**Comment by SkyDiploma** [comment]
While reading more documentation. This is essentially insert mode :). Closing this.

**Comment by pigeon-999** [comment]
iasdf
