### ISSUE TITLE
Can't use on full screen mode in chrome59.0.3071.86 (Official Build,64bit)

### ISSUE THREAD

**Issue by yuntas** [philc/vimium#2531]
1. use normal mode. -> can use vimium
1. use full screen mode [F11] -> can't use
1. back to normal mode [F11] -> can't use
1. reload page [F5] -> can use

**Comment by smblott-github** [comment]
@yuntas... Is this on just one particular page?  I cannot reproduce this behaviour.

**Comment by yuntas** [comment]
@smblott-github thanks for reply.
In my case, I cannot use all page...
- Vimium 1.59
- windows10 pro(1607)

**Comment by smblott-github** [comment]
Perhaps, as a side effect of going into full-screen mode, the window is losing the focus.

Try `F11`, then click anywhere on the page, then try Vimium bindings.

**Comment by yuntas** [comment]
I was able to do ixt.
thanks.
