### ISSUE TITLE
disable by html meta tag ?

### ISSUE THREAD

**Issue by zhengkai** [philc/vimium#2532]
Hi, I'm a contributor of a html5 game which called "Slay One" https://slay.one/

I know how to exclude it in vimium, but for incoming players(and use vimium), I don't want each of them to do it yourself, Is there any way to automatically disable it? 

for example, noindex meta tag in html page:

    <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">

Maybe we need a novimium tag ?

Thanks

**Comment by mrmr1993** [comment]
Duplicate of #2399.
