### ISSUE TITLE
Disable multi-key shortcuts

### ISSUE THREAD

**Issue by tgrosinger** [philc/vimium#2535]
Google Chrome: 58.0.3029.41
Vimium: 1.59

Is it possible to disable a pattern that consists of multiple keys? For example, I would like to pass through the "gd" keyboard shortcut. Attempting to surround with quotes just disables the quotes.

I could not find another issue with this question, but please feel free to close and just refer me if there is one.

**Comment by gdh1995** [comment]
No, it's not possible to disable only `gd` without disabling other mappings starting with `g` (like `gf`).
You may exclude only `g`, and then `gd` and `gf` are both disabled.

Reason: Vimium need to pass the keyboard events to your pages if an key is excluded. That is, if `gd` shortcut works, then neither `g` nor `d` would be passed to the page; if `gd` shortcut doesn't work, then both `g` and `d` should be passed . So Vimium can not know whether to pass `g` if it must disable not `gf` but `gd`.

**Comment by tgrosinger** [comment]
That makes sense, and I think I could live with all "g" base shortcuts disabled on this one page. 

I did think I tried disabling "g" though and the "gd" I was trying to use on the page still didn't work. I'll try again though. Thank you.

**Comment by gdh1995** [comment]
You need to disable both `g` and `d` by settings "keys" to "gd", so that Vimium will pass `g` and then pass `d` to the page's host scripts.
