### ISSUE TITLE
Button generates two hints.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [philc/vimium#2539]
A `<button>` generates two links upon pressing `f`, which is very distracting:

<img width="158" alt="screen shot 2017-06-14 at 11 16 25 pm" src="https://user-images.githubusercontent.com/5187404/27157007-84d102fc-5157-11e7-8187-1412189913de.png">

Example HTML:

```html
<button type="button" class="btn btn-default"><span>Cancel</span></button>
```

Is there a way to avoid this?

**Comment by gdh1995** [comment]
Um, your example HTML only results in one hint, if it's all the content of a HTML file.

As a common case, the real `<span>` should be more complex than what you give, and include some tags telling Vimium itself is clickable, so Vimium makes two hints - one for `<button>`, and the other for `<span>`.

**Comment by AndrewSouthpaw** [comment]
Oh! I omitted a class name because I thought it was irrelevant:

```html
<span class="rc__button">Cancel</span>
```

Apparently vimium searches for the keyboard "button" in class names?

**Comment by gdh1995** [comment]
Yes, it uses `0 <= element.getAttribute("class")?.toLowerCase().indexOf "button"` to check classNames.

**Comment by AndrewSouthpaw** [comment]
Mystery solved. Thanks!

**Comment by gdh1995** [comment]
Many many pages don't use `<button>` or `<a>` and add tons of `<span>` elements into their DOM trees. Then we have to apply other rules to know what's clickable, including `role=button` / `role=link` / `onclick` / `tabindex` and `.button` (although it's not enough, of course).

**Comment by AndrewSouthpaw** [comment]
I see. Thanks! :)
