### ISSUE TITLE
Password saver on Chrome 59 may make InsertMode exit unexpectedly

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#2549]
Well, there's a new use case where Chrome breaks Vimium: its password saver will dispatch trusted focus/blur events to every `<input>` before/after setting saved value, so after auto-filling Vimium returns to normal mode and suppresses keyboard inputs to focused `<input>`.

Reproduce:
* find a website with a form including at least 2 fields, fill its form and save to the password saver
* refresh the page, and focus the first `<input>` - let's say `input#username`
* type some alpha chars to ensure Vimium is in InsertMode
* click it to make Chrome password saver popup a select box, and then click one
* now you can press `f` to activate `LinkHints`, although `input#username` is still focused
* if press a shortcut to make Vimium enter InsertMode, then you can type in the input box again

The password saver  of Chrome 59 does this:
* keep the "current" element focused and fill it with new value
* while there's another element to fill:
  * dispatch a trusted `FocusEvent#focus` to it
  * fill it with new value
  * dispatch a trusted `FocusEvent#blur` to it
* during the step above, the first element keeps focused, and `document.activeElement` does not change.

So I think Vimium can work around this bug by checking whether `insertModeLock` is still `document.activeElement` when receiving a new `FocusEvent#focus` event, before really exiting InsertMode. Or we can wait Chrome to fix this bug by dispatch one more `focus` event to the original focused element.

Tested on Chrome 59.0.3071.109 stable x64 on Windows 10 Creator x64.

Added:
* `<input>`s inside ShadowDOMs won't be auto-filled by Chrome (ver 59)

**Comment by Frederick888** [comment]
If the form in a page is auto-filled automatically after the page is loaded, even if I click the input box and try to enter something different, it still triggers Vimium commands.

Is it related to this issue?

**Comment by smblott-github** [comment]
@Frederick888 ... Please provide an example.

**Comment by Frederick888** [comment]
@smblott-github I just tried to reproduced and I can somewhat confirm that it's the same issue.

My steps to reproduce:
1. Open a page with username and password that Chrome auto-fills for you (e.g. https://prezi.com/login/, I was preparing a presentation so just an example)
2. Double click the password box, choose a remembered password (now the input box has focus)
3. Type e.g. "shift + h"

**Comment by mrmr1993** [comment]
Filed a [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=780834) for this, since I couldn't find one.

**Comment by gdh1995** [comment]
Status update: still exists on Chrome 69 and its master branch.

BTW, Chrome Password Saver also dispatched events whose class are `Event` and types are `keydown` and `keyup`, while `KeyboardUtils.getKeyChar` returns `""` and avoids further potential harm.

**Comment by gdh1995** [comment]
This has been fixed for quite a while, since now InsertMode checks the active element everytime there's a keydown.
