### ISSUE TITLE
Firefox: Google Inbox: clicking on some elements does nothing

### ISSUE THREAD

**Issue by vozhyk-** [philc/vimium#2561]
Clicking on the "2" or the line to its right (in the screenshot below) doesn't do anything when Vimium is enabled. It shows more messages (as in the second screenshot) when the extension is disabled.

![screenshot_20170707_083352](https://user-images.githubusercontent.com/3051708/27946017-1518811a-62f0-11e7-94f8-d658646f5fc7.png)

The expected result:
![screenshot-2017-7-7 inbox vitaut bayaryn gmail com](https://user-images.githubusercontent.com/3051708/27946192-da5a73de-62f0-11e7-9522-ab8d6ec288de.png)

Firefox version: Nightly 56.0a1 (2017-07-06) (64-bit) on Linux.
Vimium version: 1.59 (from addons.mozilla.org).

This doesn't happen with the same version of Vimium on: Chromium Version 59.0.3071.86 (Developer Build) (64-bit).

**Comment by bartlibert** [comment]
I have the same issue. I don't see any errors when clicking those elements, but when I reload the page, I get several iterations of the errors below:

```
firefox.desktop[2892]: Extension error: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone
 :: line 52"  data: no] undefined 52                                                                                                                          
firefox.desktop[2892]: [[Exception stack
firefox.desktop[2892]: runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:52:14
firefox.desktop[2892]: inject/cssPromise<@resource://gre/modules/ExtensionContent.jsm:306:13
firefox.desktop[2892]: Current stack                     
firefox.desktop[2892]: runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:54:129
firefox.desktop[2892]: inject/cssPromise<@resource://gre/modules/ExtensionContent.jsm:306:13                                            
firefox.desktop[2892]: ]]
```

**Comment by stormwatch** [comment]
In my case, it is not enough to add an exception for "https?://inbox.google.com/*". I have to disable Vimium completely in order to be able to expand an email.

**Comment by gwenzek** [comment]
I'm impacted by this bug with FF 55.0.2.

I'm also having #2655.

I don't understand why with Vimium disabled on "https?://inbox.google.com/*" it's still not working.
Also does Vimium listen to mouse events ? Why does it interfere here ?

**Comment by rohin28** [comment]
Any updates or advice to address this issue?

**Comment by frewsxcv** [comment]
This might be ressolved, can someone check?

**Comment by smblott-github** [comment]
Resolved for me.

One more confirmation and we can close the issue.

**Comment by gwenzek** [comment]
Works fine for me.
