### ISSUE TITLE
Issues with Minimal Winow

### ISSUE THREAD

**Issue by mogthesprog** [philc/vimium#2562]
Hey guys,

I'm not sure on the exact terminology here, but i'll have a go :) 

I've just installed vimium and it's awesome! I'm having an issue with the google cloud shell though. The shell is opened in a new window by default, and the domain is "shell.cloud.google.com". so i've aded a rule as followS:

```
http*://ssh.cloud.google.com/*   | *no keys, so disable everything
```

But when i open the page it still seems to be active. The only difference i can see between this and other sites is the minimal browser window it opens? I'm not really sure, and can't find any other similar issues, so it may be something i'm doing. 

any ideas?

**Comment by mrmr1993** [comment]
It could be that the page contains a frame that doesn't match that pattern, in which case Vimium will still be active.

When you've noticed that Vimium is still active, try clicking the Vimium icon in the toolbar, and the dialog that shows should suggest an exclusion rule that will block it in that frame (which you can add by pressing the button). Does that work for you?

**Comment by mogthesprog** [comment]
yeah figured it out,

once the shell was being loaded, it thought the iframe was at about:blank...

I needed the following rule if that helps anyone :) 

```
about:blank*
```

**Comment by mrmr1993** [comment]
@smblott-github do you think it would be worth inheriting exclusion rules from the parent frame for `about:blank` frames?

**Comment by smblott-github** [comment]
> do you think it would be worth inheriting exclusion rules from the parent frame for about:blank frames?

Maybe, maybe not.  Let's keep it as an idea.

**Comment by eramdam** [comment]
Upon request, I'm posting another example of this issue, coming from #2589 

> <details>
> <summary>Chrome version</summary>
> 
> Google Chrome | 60.0.3112.90 (Official Build) (64-bit)
> -- | --
> Revision | 6ee4392c6cef820c64ff50b5fd5eeb8596cd0394-refs/branch-heads/3112@{#702}
> OS | Mac OS X
> JavaScript | V8 6.0.286.52
> Flash | 26.0.0.151 /Users/Damien/Library/Application Support/Google/Chrome/PepperFlash/26.0.0.151/PepperFlashPlayer.plugin
> User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
> </details>
> 
> Vimium version: 1.59
> 
> https://glitch.com is a live-coding environment, as a feature they provide a web-based terminal. So naturally I wanted to disable Vimium so it doesn't interfer.
> However, it seems like that even after adding `*://*.glitch.com/*` as a disable rule in Vimium, Vimium is still being loaded onto the page.
> 
> Here are a few screenshots of what's happening:
> 
> <img width="1484" alt="screen shot 2017-08-08 at 11 37 06 am" src="https://user-images.githubusercontent.com/1409924/29088496-12115c4c-7c2e-11e7-8ce7-d6025115e6af.png">
> <img width="651" alt="screen shot 2017-08-08 at 11 38 46 am" src="https://user-images.githubusercontent.com/1409924/29088553-43e3f662-7c2e-11e7-9ecb-067ecbd0647b.png">
> 
> You can access the console page here https://api.glitch.com/shy-quit/console/89748d98-fc6e-466a-9a11-ed7af85509e3/ (It's on a sample project anyway so it's alright)
> 
> FWIW, it seems like Vimium is detecting the page as `about:blank`, if I put a rule on `about:blank`, Vimium is correctly disabled but it doesn't feel right 😅 It's probably the main bug, feel free to rename > the issue accordingly.

**Comment by smblott-github** [comment]
OK, @mrmr1993... Your idea is sounding better.

What would be the rule?

1. The window's URL is `about:blank` (anything else too?).
2. There is no rule matching the window's URL.  (Otherwise, we'd be breaking things for the two users posting above).
3. We use any rule for the parent window's URL, or for the root window's URL?  Usually these would be the same, I guess.

**Comment by mrmr1993** [comment]
> What would be the rule?
>
> 1. The window's URL is `about:blank` (anything else too?).

I think `about:blank` is the only special page that webpages can do anything significant with.

> 2. There is no rule matching the window's URL. (Otherwise, we'd be breaking things for the two users posting above).

I'd imagined the rules cascading; do they have to be mutually exclusive?

> 3. We use any rule for the parent window's URL, or for the root window's URL? Usually these would be the same, I guess.

I'm more inclined to go with the parent window's URL.

A slightly more sophisticated solution might look like
* `about:blank` matches all `about:blank` pages
  -  we should also match `about:blank*`, which we erroneously suggest in the popup
* `about:blank@https?://github.com/*` (joining `about:blank` and some other URL pattern with an `@`) matches all `about:blank` pages whose *innermost* non-`about:blank` ancestor window matches the URL pattern.
