### ISSUE TITLE
Navigating text in input fields

### ISSUE THREAD

**Issue by DenLilleMand** [philc/vimium#2564]
Hey guys this extension is CRAZY awesome!

When looking through PRs and Issues i couldn't find anything about navigating text in input fields like e.g. when you set your terminal as `set -o vi ` . Is this already a feature, or is it something that is going to come in the future??  i am specifically looking   to go to a input field, write something, go to normal mode, use b, w, 0, $  forexample if i wanted to change my browser url from http to https then it would be nice just to do a 0 cmd.

**Comment by gdh1995** [comment]
There's some other extensions to make text box act as VIM, such as https://chrome.google.com/webstore/detail/wasavi/dgogifpkoilgiofhhhodbodcfgomelhe .

Vimium has a "VisualMode" (enter it by "enterVisualMode" command), but it does not include functions like EditMode. The latest explanation is in #1961 .

**Comment by DenLilleMand** [comment]
Oh, that is one awesome plugin ! thanks a lot :)

**Comment by ZYongjie** [comment]
j

**Comment by esfox** [comment]
fjsdklfdjk

**Comment by itsonlycode** [comment]
sdfsdfsdfsd sdfsdfsd
