### ISSUE TITLE
How can I bind the "navigate to next page" command to an other key?

### ISSUE THREAD

**Issue by ffplayer** [philc/vimium#2565]
I have try 
`map d navigate to next page`
to bind the "next page"function to d but it doesn't work.

What's the exact command of  "Next patterns" and "Previous patterns" ?

**Comment by mrmr1993** [comment]
`map d goNext` should do the trick. Similarly, the previous patterns command is `goPrevious`.

You can click the "Show available commands" link in the options page (next to the mappings textbox) to show a version of the help dialog with the command names next to the commands.

**Comment by ffplayer** [comment]
@mrmr1993 Thanks! 
I do searched in the  "Show available commands" link but just not found the goNext command. But just now I find it in the "advanced commands" which is hided default
