### ISSUE TITLE
chrome://downloads/ disables vimium keys

### ISSUE THREAD

**Issue by SiliconKite** [philc/vimium#2568]
Opening chrome://downloads/ makes chrome to ignore vimium hotkeys, so it is needed to manually use the mouse to change or close tab. Clicking on the page's frame does not help either, and any vimium key (navigate, close, etc) does not work.

**Comment by tobimensch** [comment]
Unfortunately extensions don't work in chrome:// pages.

**Comment by zzh1996** [comment]
Even if I turn on chrome://flags/#extensions-on-chrome-urls
```
Extensions on chrome:// URLs Mac, Windows, Linux, Chrome OS, Android
Enables running extensions on chrome:// URLs, where extensions explicitly request this permission.
```
Vimium still doesn't work on chrome:// pages.
Please explicitly request this permission!!!

**Comment by innaterebel** [comment]
Extensions which request that permission are not allowed to be published on Chrome Web Store.
The permission and the flag are only exist for developers, as for the entire chrome://flags page is intended...

**Comment by Vaisakhkm2625** [comment]
brave://flags/#extensions-on-chrome-urls enable this

**Comment by USAMAWIZARD** [comment]
I have a PR for this it should solve this issue problem is that the first tab that is by default in chrome it comes under chrome://newtab and chrome does not allow extensions to run on this tab you will need to enable some flag in chrome for this to work [here](https://github.com/philc/vimium/pull/4583) is the pr that should solve this issue
