### ISSUE TITLE
Vomnibar via "o" or "O" crashes Vimnium

### ISSUE THREAD

**Issue by sternmull** [philc/vimium#2574]
I am on Arch Linux and using Chromium Version 59.0.3071.115 (Developer Build) (64-bit). When i open the Vomnibar via "o" or "O" i just have to wait around a second (without typing anything) and then Vimium crashes. When i open it with "b" or "B" it works fine.

**Comment by smblott-github** [comment]
That's very odd.

Could you try creating a new profile, installing Vimium there and seeing whether you still have the problem?

**Comment by sternmull** [comment]
The symptom disappears  when i use a fresh profile.

**Comment by smblott-github** [comment]
So, since `b` works but `o` crashes Vimium, there could be something in your history which is causing a problem.  Is there anything useful on the background-page console?

**Comment by sternmull** [comment]
Nothing on the console. But if i check "Collect errors" for the extension then there is some information:

Vimium logging URL: chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/pages/logging.html
...
      var loggingPageUrl;
      loggingPageUrl = chrome.runtime.getURL("pages/logging.html");
      if (loggingPageUrl != null) {
        **console.log("Vimium logging URL:\n  " + loggingPageUrl); <-- this line is marked**
      }
      if (localStorage.autoLaunchLoggingPage) {
        chrome.windows.create({
          url: loggingPageUrl,
          focused: false
        });
...

Stack trace:
background_scripts/bg_utils.js:114 (anonymous function)
background_scripts/bg_utils.js:162 (anonymous function)
background_scripts/bg_utils.js:226 (anonymous function)

I played around with the development tools of chrome but was unable to break into the extension code when the error happens. It seems i can only debug the "popup" and the actual site but not the extension code that is responsible for the vomnibar. If you can tell me how i can get a useful debugger session then i could provide you with more information.

**Comment by sternmull** [comment]
I have no idea why, but i don't have the crash anymore.
