### ISSUE TITLE
Omnibar search completion does not work in firefox

### ISSUE THREAD

**Issue by matclab** [philc/vimium#2576]
- Firefox 54.0.1 on Arch linux
- Vimium 1.59 from mozilla plugin repo

When typing o and the a configured search engine letter plus space plus a query (for example `w search`), firefox open a tab with a google search for the query including the shortcut (i.e  `w search`).

**Comment by smblott-github** [comment]
Confirmed.

Help in figuring out what's going on would be appreciated.  I don't know Firefox well (can't even figure out how to get a console on the background page).

**Comment by mrmr1993** [comment]
> can't even figure out how to get a console on the background page

@smblott-github I think `about:debugging` is the place to look. I can take this to look at tomorrow, if you'd rather not wrestle with Firefox's under-developed WebExtension tools.

**Comment by mrmr1993** [comment]
Haven't been able to repro with 1.59 (from [here](https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/)), my private fork, or master on:
* Ubuntu, FF 54.0
* Arch (ARM64), FF 54.0.1.

I've tried `ow search<enter>`, `Ow search<enter>`, as well as different search terms and <kbd>tab</kbd>-ing around in the suggestions before hitting <kbd>enter</kbd>. Are there any steps I'm missing here?

**Comment by jonasws** [comment]
I've looked into this as well, on Firefox 57. The completions are indeed generated, but appearently the extension only calls the "cancel" completionHandler, which seems a bit odd.

**Comment by smblott-github** [comment]
This fixes the problem... 1bc9c34aab8c953ff4fe2a96e85fb9edec55fd26.

As noted in the commit, a better solution would to to figure out what (in `response`) is causing the problem.  I haven't done that yet.  Debugging in Firefox is painful.

**Comment by smblott-github** [comment]
I fixed this with https://github.com/philc/vimium/commit/e0bbc1370abe6d27b78745ce87983055ba1bfdc3, and have pushed 1.59.1 to the Mozilla Add-On site.

I'm not pushing 1.59.1 to the Chrome Store because nothing particularly significant has changed for Chrome.

**Comment by matclab** [comment]
Thanks a lot !

Le mar. 15 août 2017 à 15:02, Stephen Blott <notifications@github.com> a
écrit :

**Comment by b1ackfa1c0n** [comment]
I have faced the same problem while using ungoogled-chromium is it related, or I'm using it wrong?

**Comment by b1ackfa1c0n** [comment]
> I have faced the same problem while using ungoogled-chromium is it related, or I'm using it wrong?

Sorry my bad, the custom search engines are commented by default in extension options.
