### ISSUE TITLE
Highlight existing text when selecting input field

### ISSUE THREAD

**Issue by mastertinner** [philc/vimium#2578]
The default behavior in Chrome is that the existing text in an input field is highlighted when the user tabs into said field. In Vimium, the cursor is simply placed after the existing text. To me, this is confusing and not consistent. In my opinion, when pressing F and then selecting an input field with existing text, the text should be highlighted. This should not apply for textareas.

In addition to being more consistent with Chrome, this behavior would also increase the usability of Vimium since it's faster to replace existing text (the user wouldn't have to press Ctrl+A anymore before typing).

**Comment by smblott-github** [comment]
I agree, @mastertinner, that consistency with Chrome behaviour is desirable.  We should consider doing this.

(Help would be welcome.  Basically, we'd need a new routine in `DomUtils` for focusing elements.  Then we'd look for everywhere `XXX.focus()` is called and decide whether to use the new routine.)

**Comment by mrmr1993** [comment]
> I agree, @mastertinner, that consistency with Chrome behaviour is desirable.

Can I vouch for the status quo?
* The current behaviour is closer to clicking (albeit less fine-grained with the position of the caret)
* it's more ergonomic to press `<c-a>` to establish a selection than pressing an arrow, `<home>` or `<end>` to get to append text
* I find myself appending text far more often than replacing it completely

>  Basically, we'd need a new routine in `DomUtils` for focusing elements.

This already exists in `DomUtils.simulateSelect`.

**Comment by mrmr1993** [comment]
See also issue #19.

**Comment by smblott-github** [comment]
OK, @mrmr1993.  I agree.

**Comment by mastertinner** [comment]
Thanks for looking into this, guys. That the current behavior is closer to clicking is a very good point indeed.

**Comment by gdh1995** [comment]
> I find myself appending text far more often than replacing it completely

Agree. I think Vimium does not need to keep all of its behavior the same with Chrome - e.g. Chrome doesn't let `esc` blur elements, but Vimium makes and it's very convenient.
