### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by rudrab** [philc/vimium#2588]
Hi,
thanks for the hugely required plugin.
Is it possible to take time to explain why it needs permission to read data from the websites I visit?

**Comment by mrmr1993** [comment]
This is a duplicate of #2499. Please [search past issues](https://github.com/philc/vimium/issues?utf8=%E2%9C%93&q=is%3Aissue%20permissions) before opening a new one.

**Comment by rudrab** [comment]
Thanks and sorry.
