### ISSUE TITLE
Disabling Vimium on Glitch.com doesn't seem to take effect on their console component

### ISSUE THREAD

**Issue by eramdam** [philc/vimium#2589]
<details>
<summary>Chrome version</summary>

Google Chrome | 60.0.3112.90 (Official Build) (64-bit)
-- | --
Revision | 6ee4392c6cef820c64ff50b5fd5eeb8596cd0394-refs/branch-heads/3112@{#702}
OS | Mac OS X
JavaScript | V8 6.0.286.52
Flash | 26.0.0.151 /Users/Damien/Library/Application Support/Google/Chrome/PepperFlash/26.0.0.151/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
</details>

Vimium version: 1.59

https://glitch.com is a live-coding environment, as a feature they provide a web-based terminal. So naturally I wanted to disable Vimium so it doesn't interfer.
However, it seems like that even after adding `*://*.glitch.com/*` as a disable rule in Vimium, Vimium is still being loaded onto the page.

Here are a few screenshots of what's happening:

<img width="1484" alt="screen shot 2017-08-08 at 11 37 06 am" src="https://user-images.githubusercontent.com/1409924/29088496-12115c4c-7c2e-11e7-8ce7-d6025115e6af.png">
<img width="651" alt="screen shot 2017-08-08 at 11 38 46 am" src="https://user-images.githubusercontent.com/1409924/29088553-43e3f662-7c2e-11e7-9ecb-067ecbd0647b.png">

You can access the console page here https://api.glitch.com/shy-quit/console/89748d98-fc6e-466a-9a11-ed7af85509e3/ (It's on a sample project anyway so it's alright)

FWIW, it seems like Vimium is detecting the page as `about:blank`, if I put a rule on `about:blank`, Vimium is correctly disabled but it doesn't feel right 😅 It's probably the main bug, feel free to rename the issue accordingly.

**Comment by mrmr1993** [comment]
This looks like a duplicate of #2562. You might want to post this as an example there, rather than creating a storage issue.

**Comment by eramdam** [comment]
Done!
