### ISSUE TITLE
Custom CSS doesn't apply to link hints inside iframes

### ISSUE THREAD

**Issue by giogziro95** [philc/vimium#2594]
I use [this](https://gist.github.com/giogziro95/63d99e826a63689d6182130bae299eb0) custom CSS to style the Vimium link hints, but it doesn't apply to hints inside iframes.

Screenshot:
![Link hints](https://user-images.githubusercontent.com/2781117/29220498-43f4f57a-7ecc-11e7-8572-93edab72b418.png)

- Chrome version: 60.0.3112.90 (Stable channel)
- Vimium version: 1.59

**Comment by mrmr1993** [comment]
Looks like [this line](https://github.com/philc/vimium/blob/c0a9f3fe9139ff2ad89fe7ba5253d347f3b074b1/background_scripts/main.coffee#L250) should be using `chrome.webNavigation.onDOMContentLoaded.addListener` instead.

**Comment by smblott-github** [comment]
Or, perhaps each frame should request that the CSS is injected (when it registers itself).

**Comment by mrmr1993** [comment]
Won't that make it a race between iframes being injected and the CSS being applied?

**Comment by smblott-github** [comment]
As each frame is injected (and Vimium initialises), it registers with the background page.  We know the frame ID, so the background page can use the `frameId` option to `chrome.tabs.insertCSS` to insert the CSS into exactly *and only* the new frame.  No race condition.  No possibility of inserting the CSS multiple times.

(I'm reading [this spec](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/insertCSS)).

**Comment by mrmr1993** [comment]
> No possibility of inserting the CSS multiple times.

That's not the race condition I meant; I was worried about our CSS being applied before *our* frames are inserted. On further reflection, it's probably a non-issue, since user styles can't do anything interesting with our iframes

> perhaps each frame should request that the CSS is injected (when it registers itself).

Is there a good reason for making this change vs. swapping out `tabs.onUpdated` for `webNavigation.onDOMContentLoaded`?

**Comment by smblott-github** [comment]
> Is there a good reason for making this change vs. swapping out tabs.onUpdated for webNavigation.onDOMContentLoaded?

Yes.  Every time `onDOMContentLoaded` fires (which may be several times), we're inserting the CSS into every frame.  We may end up inserting the CSS into the same frame several times.

**Comment by mrmr1993** [comment]
`onDOMContentLoaded` (and `onCommitted`, which is probably better to use for this) both return the frame id, so we should be able to use that and have each frame get the CSS only once.

I like that `onDOMContentLoaded`/`onCommitted` keeps the user style conceptually similar to the other styles included by `manifest.json`, but either is fine AFAIC.

**Comment by smblott-github** [comment]
Sounds fine.

**Comment by gdh1995** [comment]
What about a custom `<style>` element by Vimium's content scripts? Since frontend can access storage.local.
