### ISSUE TITLE
Firefox: vimium keys don't work with service pages

### ISSUE THREAD

**Issue by wladmis** [philc/vimium#2595]
e.g. about:addons etc.

Tested on Firefox 54.0.1 on Linux, Vimium-FF 1.59.

**Comment by lydell** [comment]
WebExtensions can’t run on such pages. Only legacy Firefox add-ons can.

**Comment by lindhe** [comment]
Does https://addons.mozilla.org/en-US/firefox/ also count as a service page? Because I can't get Vimium to do a thing there...

**Comment by mrmr1993** [comment]
Yes

**Comment by philc** [comment]
I think we should be able to reduce the occurrence of questions like this
before they hit github issues by adding more detail to the FAQ and make the
FAQ more prominent/visible to new users.

**Comment by wladmis** [comment]
That's sad. They don't work with Mozilla addons web-pages as well. Maybe we should open FR to support this in Mozilla Bugzilla.

**Comment by lindhe** [comment]
I think that would be reasonable. Here are some pointers on how to do that: https://wiki.mozilla.org/WebExtensions/NewAPIs

**Comment by innaterebel** [comment]
Mozilla here is just mimicking Google's behavior for Chrome Web Store, which as well is not really an internal service page.
For security concerns, they said.

**Comment by wladmis** [comment]
I think this issue can be related with this [1].

--
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1418016

**Comment by mrmr1993** [comment]
That sounds like a duplicate of [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1310082), closed as WONTFIX. From a [comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1310082#c24) there:

> Since Firefox 57, we can work around the problem by setting the "privacy.resistFingerprinting.block_mozAddonManager" pref to true.

Naturally, less wholesome extensions may try to e.g. block you from uninstalling them or install other extensions, and so I can't recommend using the option unless you are happy taking that risk.

**Comment by onetom** [comment]
It doesn't work https://support.mozilla.org either...
I find this a little bit ridiculous.
Is there a way to disable such safety in Firefox?
This "protecting my privacy" directive at Mozilla is going a little too far and it's starting to limit my freedom... :/

**Comment by onetom** [comment]
Thanks to @mrmr1993, the thread he linked, mentions the `extensions.webextensions.restrictedDomains` setting, which you can find amongst the `about:config` settings.

If I remove `support.mozilla.com` from the list of that setting and reload the tab with a support.mozilla.com page, Vimium will start work on it!

The same thread mentions a `privacy.resistFingerprinting.block_mozAddonManager` setting too. It seems to be deprecated and not necessary anymore.
