### ISSUE TITLE
Could we add a "Disable on this page" for Vimium?

### ISSUE THREAD

**Issue by Alevale** [philc/vimium#2599]
It often happens to me that I land in a page and that Vimium for some reason behaves very strange, and has issues with the input fields (still triggering actions) or with some other things.

The question is. I **love Vimium** and that you can disable one by one the keys you don't need, but, Is it possible to add a **"disable all" button** on the plugin configuration page?

Something in here I mean.

![screen shot 2017-08-14 at 11 24 14 am](https://user-images.githubusercontent.com/6860659/29266088-b50bdf26-80e3-11e7-9551-42b617013cfb.png)

Something like adblock has.

![screen shot 2017-08-14 at 11 29 15 am](https://user-images.githubusercontent.com/6860659/29266122-d92b0e90-80e3-11e7-8214-94d79c4a79fd.png)

Hope this is not creating a duplicate, and really really **VIMIUM IS GREAT!!**, so fast I can't actually browse without it ^^

**Comment by smblott-github** [comment]
Just leave the `Keys` box empty and hit `Save`.  That disables Vimium entirely for URLs matching the pattern.  The icon goes grey.

**Comment by Alevale** [comment]
😓  Ok, my bad, sorry for not reading or knowing that, and thanks for the answer! :)

**Comment by philc** [comment]
Believe it or not, I often forget how to disable vimium on a specific page
because this UI isn't explicit. I think it could be clearer with something
like this ascii mock -- it's more verbose but very clear:

Pattern                Keys
[  google.com ]    ( * ) Disable all   (  ) Specific keys: [      ]
