### ISSUE TITLE
Latest version on AMO is 1.59.2 while latest version here is 1.59.1

### ISSUE THREAD

**Issue by ctype** [philc/vimium#2611]
Hi! I just saw that the latest version on AMO is 1.59.2, while the latest version bump commit here is to 1.59.1. Is there something wrong?

https://addons.mozilla.org/en-GB/firefox/addon/vimium-ff/

**Comment by smblott-github** [comment]
Oops.  I forgot to push the final commit: 3125664816e427ea19285d3f1e4b85af95548431. There's nothing significant in it, and -- for Chrome users -- there's nothing of interest in 1.59.2 that is not already in 1.59.

**Comment by ctype** [comment]
Ok, thank you! I just panicked a little bit when I saw it, because I've read last week that the 'web developer' addon was hijacked and somebody uploaded an infected version. :smile:
