### ISSUE TITLE
Firefox: keybindings do not load on some sites

### ISSUE THREAD

**Issue by willsALMANJ** [philc/vimium#2613]
I have noticed that on Firefox Vimium does not always load its keybindings. For example, when I open https://github.com/philc/vimium/issues, none of the keybindings work -- `j` and `k` for example get handled by the GitHub shortcuts. If I switch to another tab and then switch back, Vimium's keybindings are loaded.

I am new to Vimium (coming from similar XUL addons), so I am still getting used to what is different vs. what is broken (can't wait for `F` and `yy` to work...), but I am pretty sure I have seen this on some sites other than GitHub. I am still learning about WebExtensions but my suspicion is that Vimium key handling is interacting poorly with the site's own key handling (if I understand correctly that WebExtensions load content scripts into pages in the same context as the sites' own code).

**Comment by mrmr1993** [comment]
I can't reproduce this. Do you have steps I can follow?

**Comment by smblott-github** [comment]
If you're new to Vimium, @willsALMANJ, could you check on the (Vimium) options page that you haven't accidentally added an exclusion rule for Github?

**Comment by willsALMANJ** [comment]
Here are the steps that reproduce it for me (I am being very specific mainly to clarify things that I am not doing like changing the settings):

1. Download Firefox Nightly (I used 57.0a1 (2017-08-24) (64-bit) for Linux)
2. Run Firefox Nightly and create a new profile
3. Put https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/ into the location bar and then click "Add to Firefox"
4. Open a new tab.
5. Put github.com/philc/vimium/issues into the location bar
6. Try to use `j`/`k` -- see that these select different issues instead of scrolling the page.

I played around with it a bit more and made these discoveries:

1. Reloading the page repeatedly with `<C-l>` and `<Enter>`, I found that occasionoally (1/8 times) Vimium keybindings would work right away.
2. Switching tabs back and forth would allow Vimium keybindings to work.
3. Switching to another window (of another program) and back would allow Vimium keybindings to work.
4. After selecting the setting to prevent sites from stealing the focus on load, Vimium's keybindings always work.

So perhaps you tested with the setting to prevent stealing focus on? And GitHub is stealing focus to its keyboard shortcuts?

**Comment by mrmr1993** [comment]
Repo'd.

* When the page is first loaded it focuses an element `<input id="user_login_issue" type="text" autofocus="autofocus">`
* When you press a key, we (rightly) notice that an input has the focus, and don't do anything
* Github handles the key as a keyboard shortcut. I haven't looked into why this happens.

As you mentioned, this works as normal with the "Don't let pages steal the focus on load" option. Otherwise, I don't see what we could or should do differently without changing our semantics around inputs being focused. Sorry.

**Comment by mrmr1993** [comment]
I should probably also note that the `<input>` is `display: none`. A `display: none` element shouldn't be able to have focus, making the root cause a Firefox bug. You might want to open an issue in [their tracker](https://bugzilla.mozilla.org).

**Comment by willsALMANJ** [comment]
Okay, thanks for looking into it more and commenting on the bug. I'll close this for the time being. I know I have seen similar behavior on sites other than GitHub but not ones that I go to consistently enough to notice a pattern. On the other hand, I'm going to leave the preference to disable autofocus set so maybe that will solve those cases as well.
