### ISSUE TITLE
Action for contextual menu/right click on browser tab

### ISSUE THREAD

**Issue by GlassGruber** [philc/vimium#2616]
Hei there,
is it possible to bind a key to open current tab context menu?
Just to be sure this is what I'm talking about:

![tab-cmenu](https://user-images.githubusercontent.com/1172428/29738802-260d80e6-8a2e-11e7-9d88-eb53ae7592ce.gif)

I've tried looking around but wasn't able to find much on this, hope it's not a RTFM issue.

Thank you!

**Comment by smblott-github** [comment]
Unfortunately not.  There's no API for that.

**Comment by GlassGruber** [comment]
Oh that's unfortunate! 
Just to not open another similar issue, is there a way to bind a key or maybe something like the `f` key function that highlights links, to click/interact with extensions icons in the tool bar?
(either by num position or name but I guess that again an API for this is not available)

Anyway thank you for your answer and your time in developing this extension! 
If you wish close this issue :)

**Comment by smblott-github** [comment]
There's no API for that either.

**Comment by mvrozanti** [comment]
Is there a way to open context menu for images and links?
