### ISSUE TITLE
INSERT MODE in full screen problems

### ISSUE THREAD

**Issue by jeopsh** [philc/vimium#2617]
Don't show the Insert Mode character in full screen.
It's will shelter playing video.

ESC key function in full screen's Insert Mode Problem:
When press ESC key, it will exit full screen, but I just want to exit the Insert Mode, so I had to press ESC again to exit Insert Mode.
It should first press ESC key to exit Insert Mode, then exit full screen when press the key again. Or using other key to exit Insert Mode like CTRL + ESC?

For example: 
YouTube's F key is enter full screen, to active YouTube's shortcut, I enter Insert Mode, and press F key to enter full screen watching video, but is showing the Insert Mode character. 
If I want to exit Insert Mode, I press ESC key, but is just exit full screen.

**Comment by mrmr1993** [comment]
We have an option (in the advanced options) for "Hide the Heads Up Display (HUD) in insert mode", which should give you the behaviour you want. You could also map `passNextKey`, and then use that to pass `f` to the page.

It's not clear to me that we should never show the insert mode HUD when an element is fullscreen. It can be useful to use Vimium commands in a fullscreen context, and to be in insert mode; it seems reasonable to be that we should (offer to) report the difference.

**Comment by jeopsh** [comment]
@mrmr1993 Thanks! I am not pay attention to the HUD.

**Comment by jeopsh** [comment]
k

**Comment by nagy135** [comment]
Using option mentioned hides it but it hides it always ...That is for sure better than seeing it all the time, but the ideal case would be see it always unless in fullscreen mode. I m not really sure what that term means in context of browser, but I also use [qutebrowser](https://github.com/qutebrowser/qutebrowser) and it works exactly like that there. Its always visible but allows you to visit youtube video page, press `i f` and be in insert mode where video is "on top of the HUD".
