### ISSUE TITLE
Beginning of line in visual/caret mode

### ISSUE THREAD

**Issue by matejaputic** [philc/vimium#2619]
How do I go to the beginning of a line in visual or caret mode? I tried typing '^' but it is ignored.

**Comment by mrmr1993** [comment]
`0` should do the trick. You can find the mappings [here](https://github.com/philc/vimium/blob/master/content_scripts/mode_visual.coffee#L180) (and a few [here](https://github.com/philc/vimium/blob/master/content_scripts/mode_visual.coffee#L227)).

**Comment by mrmr1993** [comment]
`0` should do the trick. You can find the mappings [here](https://github.com/philc/vimium/blob/master/content_scripts/mode_visual.coffee#L180) (and a few [here](https://github.com/philc/vimium/blob/master/content_scripts/mode_visual.coffee#L227)).

**Comment by matejaputic** [comment]
That's a useful link, thank you!
