### ISSUE TITLE
Vimium's hotkeys don't work on pages that are opened from hard drive

### ISSUE THREAD

**Issue by sorsdt** [philc/vimium#2624]
I've tried to navigate through javadoc unpacked on hdd from zip archive but can't do it with Vimium. Version 60.0.3112.113 (Official Build) (64-bit) of Google Chrome

**Comment by sorsdt** [comment]
Version 60.0.3112.113 (Official Build) (64-bit) of Google Chrome

**Comment by mrmr1993** [comment]
You need to let Vimium access `file://` URLs by clicking the checkbox for it in `chrome://extensions`.
