### ISSUE TITLE
[Firefox] Following link hints in a new tab does not work

### ISSUE THREAD

**Issue by v1kn** [philc/vimium#2625]
In Vimium for Firefox, following link hints in a new tab (`F`) does not work. However, following hints in current tab (`f`) works as expected.

Xubuntu 17.04
Firefox 55.02
Vimium 1.59.2

**Comment by smblott-github** [comment]
This is probably the popup blocker: #2613, #2603, #2602.

(Closing.)

**Comment by hyiltiz** [comment]
Any workaround about it? It is quite annoying.

**Comment by mrmr1993** [comment]
You could disable the pop-up blocker and it will work properly. Naturally this isn't recommended, and the next version of Vimium should fix this for most cases.

**Comment by hyiltiz** [comment]
Ah, then I'll eagerly wait for the next version.
