### ISSUE TITLE
Travis builds failing

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#2630]
Travis builds have been failing for all commits since they've [updated their default backend](https://blog.travis-ci.com/2017-08-31-trusty-as-default-status) from Ubuntu Precise to Ubuntu Trusty. (The same test-cases have also been consistently failing for me on Ubuntu Xenial, the next LTS release.)

We can keep using the Precise build by setting `dist: precise` in `.travis.yml` (until April 1st 2018), by which time we should presumably have fixed the tests.

**Comment by smblott-github** [comment]
This fixes it too:

    sudo npm install -g phantomjs@1.9.20

(Or whatever the equivalent Travis fix is.)

Submit a PR of whichever you think is better, @mrmr1993.
