### ISSUE TITLE
Links rendered when display is scaled are not rendered in correct place

### ISSUE THREAD

**Issue by mkobit** [philc/vimium#2633]
When scaling the display in my OS it causes the links to be rendered incorrectly. I tested this on both Windows 10 and Ubuntu 16.04.

Chrome Version: **Version 61.0.3163.79 (Official Build) (64-bit)**

See this GIF for an example:

![Chrome example on Ubuntu when scaling display up](https://user-images.githubusercontent.com/1447148/30236277-a2a74224-94db-11e7-816f-7a0d649193b5.gif)

**Comment by wchargin** [comment]
I noticed this immediately after upgrading from Chrome. I have downgraded to google-chrome-stable_60.0.3112.90-1_amd64.deb, fixing the issue, but I will not be able to remain pinned indefinitely. Please consider this a vote for a quick fix of core functionality.
