### ISSUE TITLE
Vimium is corrupted on latest version of Chrome

### ISSUE THREAD

**Issue by niftylettuce** [philc/vimium#2634]
With simple usage browsing GitHub, the extension becomes disabled and upon repair, the same issue happens.

**Comment by smblott-github** [comment]
Which Chrome version?

**Comment by niftylettuce** [comment]
60.0.3112.113 official build x64

**Comment by terudon** [comment]
Same on Version 61.0.3163.79 (Official Build) (64-bit) on Ubuntu 16.04.
When pressing f when page is still at the top, the navigation hints appear and show up on the right spot.
Scroll down a bit, press f and the highlights are out of sync and don't show up on newly visable links.

**Comment by mrmr1993** [comment]
@terudon your issue sounds like #2635, which is fixed in master and will be in the next release.

**Comment by terudon** [comment]
Yes that can definitely be it. Thanks #mrmr1993

**Comment by anavarre** [comment]
Same version here (61.0.3163.79 (Official Build) (64-bit)) on Ubuntu and same issues. Now waiting for the next release to confirm it fixes the issue.

**Comment by niftylettuce** [comment]
Any update on this? @philc @mrmr1993

**Comment by mrmr1993** [comment]
@niftylettuce apart from [this comment](https://github.com/philc/vimium/issues/2634#issuecomment-328895194), for which the fix is in the current version (1.60.3, available from the Chrome store), there isn't any information here I can use to identify or try to resolve an issue.

**Comment by smblott-github** [comment]
This could be an `event.key` issue.  What type of keyboard and keyboard layout are you using, @niftylettuce?

What happens if you enable this setting on the options page...

![snapshot](https://user-images.githubusercontent.com/2641335/30801245-950637fe-a1da-11e7-8620-a21c3179582e.png)

**Comment by niftylettuce** [comment]
@smblott-github I just re-enabled the extension, will report back if I have issues.  Testing `Version 61.0.3163.100 (Official Build) (64-bit)`.

**Comment by niftylettuce** [comment]
I have not been able to reproduce on the latest versions of Chrome, closing this.  Thanks @ilya @philc

**Comment by niftylettuce** [comment]
FYI @smblott-github was using standard Mac keyboard
