### ISSUE TITLE
Increasing browser font size makes link hints appear in the wrong place

### ISSUE THREAD

**Issue by larsks** [philc/vimium#2639]
- Chrome version:  61.0.3163.79 (Official Build) beta (64-bit)
- Vimium version: 1.59

When I increase the browser font size (using CTRL-+), link hints show up in the wrong place, making them useless...so either my eyes are sad, because I have to strain to read small text, or my fingers are sad, because I have to grab for the mouse.

Is there any way to fix this?

**Comment by llacom** [comment]
Chrome: Version 59.0.3071.86 (Official Build) (64-bit)
Vimium: 1.60

As soon as Vimium upgraded to 1.60 I got this same issue, which effectively prevents me from using Vimium.

**Comment by llacom** [comment]
With vimium 1.60.2 the bug due to zoom level is gone, thanks!

**Comment by decadent** [comment]
Still off after scrolling:

![screenshot.](https://i.imgur.com/CKCt7QI.png)


(Also, comments to the other issue mention that the glitch shouldn't occur with 1.59, but both the OP here and I had the version 1.59.)

**Comment by henrik-jensen** [comment]
@llacom I agree with @decadent . Position still off after scrolling v 1.60.2.

On top of page - no problem:
(Browser Zoom 150%.)
<img src="https://user-images.githubusercontent.com/9413242/30460734-fb30276c-99b8-11e7-89ce-4022cd9abf7e.png" width="500">

After scrolling (7 keydown) - link hints move further and further away from link. :
<img src="https://user-images.githubusercontent.com/9413242/30460774-42b0252e-99b9-11e7-8263-a045170cd8cb.png" width="500">

Vimium: 1.60.2
Chrome: 61.0.3163.91 (Official Build) (64-bit)

**Comment by mrmr1993** [comment]
I think PR #2649 finally does the right thing with this. Would you mind testing it to see if fixes the problem?

**Comment by jandk008** [comment]
Now, in my case, there is no problem at the top, but after scrolling down, the link hints disappear even there is links obviously, which prevents me from using it.

**Comment by larsks** [comment]
@mrmr1993 It looks like my browser picked up 1.60.3 this morning, and now link hints appear correctly regardless of zoom level, at least on the various stackexchange sites on which I've been encountering this issue.

**Comment by henrik-jensen** [comment]
@mrmr1993 1.60.3/#2649 also fixed it for me
Thanks a bunch.
