### ISSUE TITLE
Avoid creating iframe until it's required

### ISSUE THREAD

**Issue by printercu** [philc/vimium#2641]
Hi!

With the last update of Chrome all page's iframes are always shown in "Elements" tab of developer tools. So "Frame vomnibar.html" is shown for all sites where vimium is enabled. This is distracting, and I have faced several times that opening console opens it for vomnibar frame instead of main document.

Is it possible for vimium to add this iframe only when it's required (hud is shown)?

Thank you!

**Comment by smblott-github** [comment]
We have had that in the past, and there then is a noticeable delay opening the Vomnibar.

(And this does not seem to be above threshold for a new setting on the options page.)

**Comment by printercu** [comment]
This is sad. Thanks anyway!
