### ISSUE TITLE
1.60 regression `f`

### ISSUE THREAD

**Issue by troglotit** [philc/vimium#2643]
After the update `f` seems to have issues with positioning.
It works ok while at the top of the page:
![image](https://user-images.githubusercontent.com/10955264/30428899-08a3e38a-995e-11e7-8f61-0157ddcbdcc3.png)
But after a little bit of scrolling:
![image](https://user-images.githubusercontent.com/10955264/30428923-1dc24ba8-995e-11e7-8297-5dbcaf586fc1.png)

Google Chrome | 60.0.3112.113 (Official Build) (64-bit)
-- | --
Revision | 95c454326a7a3153e984e50a4719924968490717-refs/branch-heads/3112@{#744}

Vimium: 1.60

**Comment by smblott-github** [comment]
@troglotit Do you have your browser zoomed in/out at all?  See #2639.

**Comment by troglotit** [comment]
@smblott-github that issue is really similar, but no, I don't have zoomes. But on the other hand
it show wrong positioning consistently at zoom-in and zoom-out 😄.
![image](https://user-images.githubusercontent.com/10955264/30429412-04e3f71a-9960-11e7-91ab-c133391b7ac9.png)
![image](https://user-images.githubusercontent.com/10955264/30429436-18dd61ca-9960-11e7-9e88-6ada8577b1bb.png)

**Comment by troglotit** [comment]
I bisected, and found that the commit in #2636 is the first place where it starts working incorrectly. 
I'm on on Retina display, and `devicePixelRatio` is 2

**Comment by smblott-github** [comment]
Dup of #2639; see there.

**Comment by smblott-github** [comment]
Eh, actually not a dup of that.  Re-opening.

**Comment by troglotit** [comment]
The problem is I think devicePixelRatio is coupled to being Retina, and also to zoom level. So to one of the options which I could think of quickly is maybe add an additional numerical option which gets into account Retina or not. But adding an option is, of course, not a perfect solution.

**Comment by floscr** [comment]
Ugh an chrome does not make it easy to switch versions 😢 

I've built a 1.59 version, you can disable the current one and install this one by having 'developer tools' enabled on your extensions page.

[vimium.zip](https://github.com/philc/vimium/files/1303089/vimium.zip)

(Ideally you shouldn't trust me and build your own 😉)

**Comment by yubo56** [comment]
Also seeing this! +1 for a fix, though I think that I was also affected by #2639, so I'm probably one of your most troublesome users :joy:

**Comment by troglotit** [comment]
1.60.2 version with #2645 does indeed fix this issue. But it breaks those closed issues, so I'm not closing this issue to not to lose track of issues. But of course, feel free to close this issue.

**Comment by szebrowski** [comment]
I've got the same regression even on 1.59. I'm using 4k monitor. Zooming doesn't make a difference.

**Comment by smblott-github** [comment]
There are several zooming issues at play:

1. style
2. Chrome zoom
3. some Chrome zoom flag (forget the detail)
4. (some window manager zooming, I think too)
5. HiDPI (possibly you, @szebrowski)

We added some code intended to fix the HiDPI issue, but it turns out it broke some of the other cases, so I reverted it.

I think 1, 2 and 3 might be fixed. 4 I'm not sure. 5 is known broken.

**Comment by alepez** [comment]
Hi, I'm having the same issue with zoom. (And this is bad for me, my zoom is always enabled at 150%.)

**Comment by troglotit** [comment]
Yeah, to be totally clear, 1.60.2 fixes this issue for 100% zoom. But #2639 gets broken for me.

**Comment by troglotit** [comment]
Works with 1.60.3
