### ISSUE TITLE
no functionality on local html files

### ISSUE THREAD

**Issue by nimafazeli** [philc/vimium#2654]
It seems that the plugin does nothing whenever I open a local html file. e.g whenever I compile a markdown file into html and try to preview it in chrome. I do it from sublime text markdown preview and I use chrome.

**Comment by smblott-github** [comment]
Probably [this](https://github.com/philc/vimium/wiki/FAQ#how-can-i-use-vimium-on-file-urls).

**Comment by nimafazeli** [comment]
yes it worked! 
Thanks.
