### ISSUE TITLE
Firefox: Issues with Google Inbox

### ISSUE THREAD

**Issue by frewsxcv** [philc/vimium#2655]
Thought these were issues from Firefox, but it turns out to be from this extension:

https://bugzilla.mozilla.org/show_bug.cgi?id=1400309

https://bugzilla.mozilla.org/show_bug.cgi?id=1400312

**Comment by smblott-github** [comment]
Could you please provide details of how to reproduce, expected behaviour and actual behaviour.

The links you posted are quite cryptic.

**Comment by frewsxcv** [comment]
Here's an example of one issue:

1. Go to https://inbox.google.com
2. Expand an email
3. Attempt to do an inline reply
4. Notice that, even after you enter text, the 'Send' button doesn't enable

![untitled2](https://user-images.githubusercontent.com/416575/30496434-5ca10e3a-9a1d-11e7-92f5-d8be47e9dcec.gif)

**Comment by smblott-github** [comment]
Thanks for that, @frewsxcv.

What makes you think that this is a Vimium issue?

(I'm just trying to figure out what might be the problem.)

**Comment by frewsxcv** [comment]
> What makes you think that this is a Vimium issue?

If I enable Vimium, the problem I outlined in my previous comment exists. If I disable Vimium, the problem goes away. For what it's worth, I'm using Firefox Nightly. The problem has existed for a couple weeks now at least with each of the nightlies. I haven't checked if this problem exists on the beta/stable channels.

**Comment by mrmr1993** [comment]
Repro'd. Bug presents with Vimium, doesn't without.

I'm going to take a look now, see if I can find anything glaringly obvious.

**Comment by mrmr1993** [comment]
I wasn't able to make any progress with this, sorry.

**Comment by bartlibert** [comment]
Could this be related to https://github.com/philc/vimium/issues/2561 as well?

**Comment by smblott-github** [comment]
I wonder if #2640 might be related too.

**Comment by mrmr1993** [comment]
I've just tried to have another look at this, again to no avail.

My basic strategy was:
* install selenium (via `selenium-webdriver` and `geckodriver` in `npm`)
* use [this script](https://gist.github.com/mrmr1993/a4a912d79fd4b132898fc40cb8347cd1) to drive selenium running the steps from [this comment](https://github.com/philc/vimium/issues/2655#issuecomment-329853800)
* manually modify Vimium, removing files from `manifest.json` and ripping out/simplifying code to see what changes the outcome
* run the script with `nodejs inbox_test.js; echo $?` (in bash). A `0` exit status is success, `1` is a failure.

Problems:
* The script isn't as reliable as it could be.
* The test steps don't always succeed (either manually or through the script) when Vimium isn't added.
* The test steps don't always fail (either manually or through the script) when Vimium is added.

The amount of noise in the test makes it difficult to find anything concrete, but I'm throwing it out here in case anybody else is interested in trying or improving it. I think I may be admitting defeat on this issue.

**Comment by mrmr1993** [comment]
I found that removing `"all_frames": true` and `"match_about_blank": true` seems to fix the issue, so I suspect this is something to do with frames.

I am not actively working on this.

**Comment by bartlibert** [comment]
Just FYI; in Firefox 57.0b3, I don't see this behaviour anymore, but I guess more confirmation is needed.

**Comment by gwenzek** [comment]
I'm impacted by this bug with FF 55.0.2.

I'm also having #2561  which is more annoying.

For this bug (send button greyed out) I use Ctrl+enter to send the email.

**Comment by frewsxcv** [comment]
This seems to be resolved for me. Can anyone else confirm?

**Comment by gwenzek** [comment]
I can't reproduce it anymore. So looks like it's fixed !
