### ISSUE TITLE
Feature request: ctrl-f/b to scroll forward/back pages

### ISSUE THREAD

**Issue by trevordmiller** [philc/vimium#2660]
First off, fantastic extension! I'm really liking it.

I'd like to request a feature be added to scroll by page as you can in vim with `ctrl + f` to go forward and `ctrl + b` to go backward. This is much more efficient than holding `j` and `k` when you need to scroll pages but `gg` and `G` are too far.

Thank you!

**Comment by smblott-github** [comment]
On the options page, you can add your own custom key mappings...

    map <c-f> scrollFullPageDown
    map <c-b> scrollFullPageUp

**Comment by trevordmiller** [comment]
Awesome! Thank you.
