### ISSUE TITLE
Doesn't exist: github.com/philc/vimium/wiki/Search-Completion

### ISSUE THREAD

**Issue by HaleTom** [philc/vimium#2661]
The page:
* https://github.com/philc/vimium/wiki/Search-Completion

Doesn't exist.

This page is linked to from:
* chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/pages/completion_engines.html
* https://github.com/philc/vimium/wiki
* https://github.com/philc/vimium/blob/master/README.md

**Comment by smblott-github** [comment]
Thanks for the report, @HaleTom.  It seems the page was destroyed by user recorded as @gabasch01 on the 27th of August.  I've no idea why.

**Comment by HaleTom** [comment]
Thanks!
