### ISSUE TITLE
Bookmark vomnibar (b or B) displays but has no content

### ISSUE THREAD

**Issue by patkujawa-wf** [philc/vimium#2663]
This recently changed. I'm using Chrome 61 with Vimium 1.60.3. Using `o` or `O` still works, and includes bookmarks, it's just the specific bookmark-only vomnibar that seems to be broken.

**Comment by patkujawa-wf** [comment]
When I inspect the extension page, there are no errors when the vomnibar opens, but as soon as I type anything, each keypress causes an exception:

```
vomnibar.js:262 Uncaught TypeError: Cannot read property 'customSearchMode' of undefined
    at VomnibarUI.onInput (vomnibar.js:262)
    at HTMLInputElement.<anonymous> (vomnibar.js:4)
```

**Comment by patkujawa-wf** [comment]
Looks like [`if 0 <= @selection and @completions[@selection].customSearchMode and not @customSearchMode`](https://github.com/philc/vimium/blob/4f4abdadfb283ee296bb4f4d286923eaca41cd13/pages/vomnibar.coffee#L213) is failing because `@completions` is empty.

**Comment by patkujawa-wf** [comment]
Oh, also, compared with how that code handles `o` or `O`, `@selection` is `0` for bookmarks but `-1` for the others.

**Comment by patkujawa-wf** [comment]
It seems that, for reasons unknown, `options.selectFirst` is being set to `true` instead of the default of `false`, but only for bookmarks. Then the code mentioned above is choking because there are no completion items to select-first of.

![image](https://user-images.githubusercontent.com/6391742/30762663-1d080af2-9fa0-11e7-90e6-9a27f084dd76.png)

**Comment by patkujawa-wf** [comment]
Well... it looks like https://github.com/philc/vimium/blob/bd06c7ccfbfcf36e6d15fba72b7af90254b05da2/content_scripts/vomnibar.coffee#L26-L34 has been around for a while, so I guess the initial value is a red herring.

My next best guess is that the completions just isn't being populated, for some reason.

**Comment by smblott-github** [comment]
I cannot repro this, @patkujawa-wf, and I don't think there has been any recent change affecting that code path.  And others are not reporting the issue.

So it's not clear what we can do.

**Comment by patkujawa-wf** [comment]
Bummer, but good to know. It's possible it's a race condition. I have a **lot** of bookmarks (almost 8000), so many that Chrome often pauses when I add a new bookmark.

However, vimium didn't seem to have any issues in the previous version.

**Comment by patkujawa-wf** [comment]
:man_facepalming: and now this morning I also cannot repro! Maybe because I finally closed chrome on Friday and starting it up new today. Well, problem solved! :)
