### ISSUE TITLE
Letter "i" does not work when following links

### ISSUE THREAD

**Issue by happyGNU** [philc/vimium#2668]
Vimium version: 1.60
SO: Arch Linux
Firefox: Nightly 58.0a1 (2017-09-25) (64-bit)

Expected behavior:  When using letter "f" to highlight links, if any link has letter "i" that link should be opened by pressing "i"

Actual behavior: Nothing happens.

What I do is move page a little with "j" or "k" so link order changes to a different letter and after pressing "f" again it has a different letter and then I can open it.

**Comment by happyGNU** [comment]
After enabling and saving "ignore keyboard layout" the behavior did not change. I know because my layout is completely different, I use dvorak-spanish. 

It is odd because even with Qwerty-en the letter "i" was still not working. All the others still work.

**Comment by mrmr1993** [comment]
That is odd! Do you have any OS-level keyboard tweaks? It might be worth seeing what values the `keydown` event returns when you press `i`. (There are tools for this online, or I think @smblott-github has a webpage set up to test this, of you're not sure how to get the information.)

I'd like to have a look on this, but I probably won't have a chance until Friday.

**Comment by happyGNU** [comment]
This is my mistake :/ is actually a letter j not an i. Sorry for the wrong issue.
