### ISSUE TITLE
Firefox: Cannot open links in the body of Medium posts

### ISSUE THREAD

**Issue by jamesgecko** [philc/vimium#2672]
Firefox Developer Edition version: 57.0b3 (64-bit)
Vimium version: 1.60
OS: macOS Sierra 10.12.6 (16G29)

I cannot open links in the body of Medium posts.

**Reproduction:**
1. Go to https://medium.com/firefox-test-pilot/say-hi-to-send-1-10-6dd20c39feb0
2. Press `f`
3. Press the appropriate letters for one of the three links in the body of the post. These links are, `Send 1.1.0`, `results may vary with receiving on iOS`, and `raft of minor fixes`.
4. A blue rectangle appears and disappears around the link, but nothing else happens.

If I open the developer console and edit the links to remove the `target="_blank"` attribute, they become openable with Vimium. Every other link on the page appears to work fine with no modification.

**Comment by happyGNU** [comment]
One thing I noticed is that all those 3 links try to open a window. Do you have pop-ups disabled or enabled? 

In Arch-Linux with Firefox Nightly 58.0a1 (2017-09-26) (64-bit) and Vimium 1.60 all the links worked.

**Comment by mrmr1993** [comment]
We hit the pop-up blocker anyway when trying to open new tabs, so this is probably the cause. I don't recommend disabling your pop-up blocker, for the obvious reasons.

We could probably work around this using a variation on #2602. I'll run some tests and try to create a fix when I next get a chance.
