### ISSUE TITLE
Firefox 57: Vimium does not seem to work on Facebook 

### ISSUE THREAD

**Issue by hungrymonkey** [philc/vimium#2675]
Firefox: 57.0b3 
Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0
E10 and stylo enabled

I am currently using a custom build of 1.59.9 due to #2612 but it also does not work on 1.6 as linked https://addons.mozilla.org/en-GB/firefox/addon/vimium-ff/.

Description: Vimium commands seems to be ignored in Facebook.com

Desire behavior: I can use Vimium commands.

**Comment by mrmr1993** [comment]
> I am currently using a custom build of 1.59.9 due to #2612

That issue should now be fixed in the most recent release. Please try again using that.

I haven't been able to repro this.

**Comment by hungrymonkey** [comment]
I updated to 1.60.4 and facebook still intercept my commands before Vimium

**Comment by vmfhrmfoaj** [comment]
It works well for me on Facebook.
My environment is:
- OS: macOS 10.13
- Firefox: Nightly, 58.0a1 (2017-10-01) (64-bit)
- Vimium-FF: 1.60.4

**Comment by vmfhrmfoaj** [comment]
On Firefox Dev Edition (57.0b3, 64-bit), I confirmed it is not working.

**Comment by hungrymonkey** [comment]
oh, i wonder what is wrong with firefox dev edition then

**Comment by mrmr1993** [comment]
Firefox is making a lot of changes at the moment: they're adding multiprocess support, implementing WebExtensions, and switching over to a new UI framework.

Like the Google Inbox issue (#2655 and others), this is probably the interplay of one or more of these large groups of changes, and there's probably not much we can do on our side. I'm not planning to investigate this.

**Comment by hungrymonkey** [comment]
Ok, do whatever you think takes less work. Thank you for your efforts

**Comment by mrmr1993** [comment]
This still isn't fixed in Firefox trunk, so I decided to have a look. I've opened [this Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1410642), which is at least part of the underlying problem. It's difficult to debug much further without that fixed, so I'm going to wait on that.
