### ISSUE TITLE
Vimium displays XML as plaintext with Firefox 55.0.3 (possibly other versions)

### ISSUE THREAD

**Issue by rbjorklin** [philc/vimium#2690]
Viewing a Maven POM in the browser such as: https://search.maven.org/remotecontent?filepath=io/airbrake/logback/0.1.0/logback-0.1.0.pom is broken with Vimium enabled. Everything is shown as a long single line string.

Expected behavior can be seen by viewing the page source.

**Comment by mrmr1993** [comment]
This is a result of the HTML for our UI being injected into the document. I've pushed PR #2691 to fix this.
