### ISSUE TITLE
Custom key mapping for open certain URL

### ISSUE THREAD

**Issue by blurm** [philc/vimium#2695]
Hi:

like `ge` open `chrome://extensions`
Is this possible? I went through the command list and didn't find any command can open given URL.

**Comment by smblott-github** [comment]
> Is this possible?

[this](https://github.com/philc/vimium/wiki/Tips-and-Tricks#creating-tabs-with-urls) would probably work.

**Comment by blurm** [comment]
That's exactly what I'm looking for. Thanks.
