### ISSUE TITLE
How to focus on address bar? (and mapping ctrl-enter)

### ISSUE THREAD

**Issue by pluto439** [philc/vimium#2710]
Hello. I need to map < c-v > to opening address bar, and escape (or <c-,>) to leaving address bar.

And I'd like to map < c-enter > to focusInput, and escape to leaving input field.

Don't quite understand why opening this mini input field (on o or b) is necessary, if there is address bar for that already. Api limitations?

Interesting how github hides text if it's inside < >, without spaces.

**Comment by smblott-github** [comment]
There is no API for an extension to focus the omnibox.  And, once the focus is in the omnibox, vimium does not see any events (and so can do nothing).  That is why the vomnibar was added.

**Comment by pluto439** [comment]
I'm probably willing to recompile chromium just to teach address bar to give focus back to main page on pressing escape. Hints on where I should look for first?

**Comment by vinpublic** [comment]
hm, VimFx could do that on o. XUL API was better?

**Comment by pluto439** [comment]
I guess I'll use Waterfox and keep using VimFx.

https://superuser.com/questions/1257267/firefox-fork-that-allows-to-use-old-addons-but-still-keeps-new-vulnerabilities-p

Being able to hack Chromium would be awesome, but I doubt it will even compile on my laptop. I wish somebody uploads object files for it, just to not recompile absolutely everything.

**Comment by rsw0x** [comment]
> There is no API for an extension to focus the omnibox.

wow.

**Comment by pluto439** [comment]
Probably wouldn't be able to compile Chromium either, too heavy.

https://github.com/henrypp/chromium/issues/27
