### ISSUE TITLE
f and F mapping in Firefox 57 are not accurate

### ISSUE THREAD

**Issue by billsykes** [philc/vimium#2715]
Firefox Developer Edition 57.0b6 (64-bit) on macOS Sierra 10.12.6

Using 'f' is opening links in a new unfocused tab.
Using 'F' is opening links in the same tab.

Attempting to override this behavior in the key mappings has no effect:

```
# Insert your preferred key mappings here.
unmap f
unmap F
map f LinkHints.activateMode
map F LinkHints.activateModeToOpenInNewForegroundTab
```

**Comment by smblott-github** [comment]
I assume this is Vimium v1.60.4.

Are you holding `<Shift>` while you type hint characters?  If so, don't.

**Comment by billsykes** [comment]
Ah that was problem, thanks!
