### ISSUE TITLE
Cannot enter link-hint mode if typing 'f' in old version chrome browser

### ISSUE THREAD

**Issue by taisetna** [philc/vimium#2716]
Previous version(1.59) works well in old version(ex. 42.0) chrome browser, but new version(1.60) doesn't work.

**Comment by smblott-github** [comment]
Yes.  We have moved to using `event.key` for keyboard events because Chrome removed what were using previously.  You'll need to upgrade your Chrome, I'm afraid.

**Comment by gdh1995** [comment]
`event.key` occurs since Chrome 51, and I think it's better to use a version newer than 54 stable.

Or you may try my custom version of Vimium: https://github.com/gdh1995/vimium-plus - it supports Chrome since version 36, though some features are only available since Chrome 4x / 5x.

**Comment by taisetna** [comment]
@smblott-github Thank for your answer.  I should upgrade mine.
@gdh1995  I installed and use vimium-plus when that problem happened. But that has also problem that some page wasn't shown properly on chrome. I will attach the link If you are interested in..
