### ISSUE TITLE
Ability to load configuration from the remote link

### ISSUE THREAD

**Issue by Gonzih** [philc/vimium#2719]
Hi, would it be possible to load configuration from a remote url (like for example gist on github). Keybinding would be enough, I saw this feauture in cvim and I think its very handy one. I use custom configuration (programmer dvorak problems) and share it between 5 different machines in different locations. What do you think?

Thanks!

**Comment by quintrino** [comment]
Also keen for this, as I have to maintain multiple chrome profiles between Work and Home it would be great to be able to update one place and have it reflect on all of them, either through a gist or through a file on our computer (I'm not sure what's easier from a technical point of view)
