### ISSUE TITLE
Map <c-[> to a command?

### ISSUE THREAD

**Issue by cedric-sun** [philc/vimium#2722]
Since
```
unmap <c-[>
map <c-[> previousTab
```
doesn't work, I've searched the issues, find #2473 and hack it like:
```
map <c-{> previousTab
mapkey <c-[> <c-{>
```
It works, but I wonder whether there is a direct way to remap <c-[> to a command?

Warm regards,
Cedric

**Comment by smblott-github** [comment]
`<c-[>` is hardwired.

But you might be able to get what you want like this...

    map x someCommand
    mapkey <c-[> x

For `mapkey`, see [here](https://github.com/philc/vimium/wiki/Tips-and-Tricks#key-mapping).

**Comment by cedric-sun** [comment]
@smblott-github Thank you. Anyway, the workaround is still acceptable : )

**Comment by smblott-github** [comment]
See #2723.

**Comment by cedric-sun** [comment]
@smblott-github Wow, Thank you! It's so conscientious of you to fix it in a flash!
