### ISSUE TITLE
[Firefox] Shift-F behavior triggers Firefox pop-up blocker

### ISSUE THREAD

**Issue by alanhdu** [philc/vimium#2726]
A lot of times when I browsing a page, when I use `SHIFT-F` to open a link in a new tab, I instead get a notification from Firefox telling me that it blocked a pop-up from the website that I'm on (see image below).

![image](https://user-images.githubusercontent.com/1914111/31589481-2184aac6-b1d0-11e7-9101-79b6f57d66cc.png)

I'm using Firefox nightly (58.0a1 2017-10-13) on Ubuntu 16.04 with Vimium `1.60.4`.

I'm not sure if this is a Firefox problem or a Vimium problem -- if it's a Firefox problem, let me know and I'll file a bug on Bugzilla instead!

**Comment by mrmr1993** [comment]
[Relevant Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1356309), which is duped into [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1348213). Please vote on both issues.

Our workaround (#2602) currently lets the pop-up blocker fire and opens a window manually when it does. There's no other way we can duplicate our behaviour in Chrome. This isn't an issue we can fix on our end.
