### ISSUE TITLE
[Firefox] Copy URL does not work (`yy`)

### ISSUE THREAD

**Issue by xuhdev** [philc/vimium#2727]
Visit a webpage and use `yy` to copy URL. The prompt `Yanked https://github.com/...` is shown, but the actual copy did not occur.

I'm on Firefox 57 beta 8 and Vimium 1.60.4. (BTW, the tag 1.60.4 is not available in the repo). My OS is Debian.

**Comment by smblott-github** [comment]
This is a known issue (#2601), we're just not sure what to do about it.
