### ISSUE TITLE
The command 'f' always opens a link in a new tab

### ISSUE THREAD

**Issue by ndrizza** [philc/vimium#2744]
If i use the 'f' command, and I type the letters for the link, then the page always opens in a new tab (that is opened in the background). Is there some way i can look at the click event that vimium does? I can't explain myself this behaviour.

**Comment by smblott-github** [comment]
Are you holding the `Shift` key?  If so, don't.

**Comment by shixuguo** [comment]
there are three kinds of command to open a link
map keys to whatever you want

` Open a link in the current tab (LinkHints.activateMode)`
` Open a link in a new tab(LinkHints.activateModeToOpenInNewTab)`
`Open a link in a new tab & switch to it`

**Comment by ndrizza** [comment]
Thanks smblott-github. You are right, that was because i was holding shift. The uppercase letters as hints are misleading - they should be changed to lowercase.

**Comment by smblott-github** [comment]
> they should be changed to lowercase.

I implemented that a while back (and for the same reason), but it turns out that it looks terrible.  Very difficult to tell the difference between some characters.

**Comment by ndrizza** [comment]
i see. you could exclude the indistinguishable letters from the set of options. but anyways, now that i know that i need to write uppercase it won't happen again. thank you!
