### ISSUE TITLE
How to default to insert mode instead of normal mode?

### ISSUE THREAD

**Issue by a-eid** [philc/vimium#2760]
can I default to insert mode instead of normal mode ? if so how ? 
thanks.

**Comment by smblott-github** [comment]
You can disable Vimium for a site, but you cannot default to insert mode.

**Comment by a-eid** [comment]
Thanks

**Comment by foodornt** [comment]
bro add a default insert mode option, that'd be really helpful for youtube

**Comment by collinvandyck** [comment]
I adore Vimium and would also like to voice my support for such a feature. Thanks!

**Comment by AMGMNPLK** [comment]
+1

**Comment by DeepReef11** [comment]
Insert mode by default please

**Comment by McBruno712** [comment]
+1
It happens too often that I want to write something or use some of the website's commands and I end up triggering Vimium because I forgot to enter insert mode.
