### ISSUE TITLE
Can we disable Vomnibar?

### ISSUE THREAD

**Issue by ShirajG** [philc/vimium#2765]
Is there a user setting to disable the Vomnibar from loading? It's causing an issue when inspecting a page with the Chrome Dev Tools. Focus jumps to the Vomnibar HTML, instead of staying put on the element I was trying to inspect. I don't use the Vomnibar much, so I'd be happy to just be able to stop it loading.

**Comment by smblott-github** [comment]
This is not possible currently.

**Comment by smblott-github** [comment]
Actually, sorry, that's wrong.

If you wholly disable Vimium on the page/site you're working on, then the Vomnibar frame is not loaded.
