### ISSUE TITLE
Bind shortcut with enter key.

### ISSUE THREAD

**Issue by schvabodka-man** [philc/vimium#2769]
How do i bind shortcut with enter key? For example i want to bind <a-enter> as new tab. I was trying <a-return>, <a-ret>, <a-Enter>, <a-Return>, but nothing worked. I can't find anything useful in documentation about ret key. How to do that?

**Comment by smblott-github** [comment]
This is not currently supported.  (Although I see no reason why it shouldn't be.)

**Comment by schvabodka-man** [comment]
> Although I see no reason why it shouldn't be.

That's very edgy and radical.

**Comment by schvabodka-man** [comment]
But anyway, thx for response
