### ISSUE TITLE
Mapping combination of multiple commands to a single key

### ISSUE THREAD

**Issue by Mehradzie** [philc/vimium#2776]
Say I want to create a new `removeTab` combination that closes the tab and also moves back in the tab orders rather than landing on the tab right after.

This is what I had in mind
`map <a-x> removeTab + previousTab`

Is there a way to do this and if so what separator I need to use between two commands `removeTab` and `previousTab`

**Comment by smblott-github** [comment]
This is not currently possible.

**Comment by gdh1995** [comment]
Yes currently it's neither possible nor badly needed.

But just in this case, Vimium may add an option to `removeTab` - the result should be like `map <a-x> removeTab left`.

**Comment by Mehradzie** [comment]
Thanks @smblott-github 👍 
and thanks @gdh1995 The way you started I thought you gonna ban me from using it as well. was just asking. lol 😋

**Comment by just2d** [comment]
> Yes currently it's neither possible nor badly needed.
> 
> But just in this case, Vimium may add an option to `removeTab` - the result should be like `map <a-x> removeTab left`.

I think this is a needed feature, which cVim offers.
Chrome opens new links at the right of the current tab, when I close the new tab, I want to land on the previous page where I just visit.
For example, I'm visiting page A, and click a link and open a new page B which is at the right of page A, when I'm done visiting page B, I want to continue my visiting on page A, but not other pages at the right of page B, which are totally irrelevant to the page A.
A --> B, B --> A ✅ continue the visiting context
A --> B, B --> C*** ❌ break the visiting context
please consider of this feature @smblott-github , thanks :)
