### ISSUE TITLE
What is the difference between "y" and "yf" ?

### ISSUE THREAD

**Issue by rackstraw** [philc/vimium#2778]
**v**       enter visual mode; use p/P to paste-and-go, **use y to yank**
**yf**      copy a link url to the **clipboard**

1) Isn't "yank" the same as "copy to the clipboard"?
2) Doesn't visual mode have to be used in either case to select a link?

Any other examples?

**Comment by smblott-github** [comment]
`yf` uses link-hints mode to select **a link** on the page (and yank it).

Your other example uses visual mode to select **any text** on the page then either yank it, or paste and go.

**Comment by rackstraw** [comment]
I found by experimentation that "yf" will yank the link address, but "yF"
will open the link in a new tab.

It is curious that the output of "?" implies that  a naked "F" will perform
this action. In fact it should be stated explicitly that the command is
actually "yF".

Confusing.

**Comment by smblott-github** [comment]
`yF` is not a command.  `F` is a command.  When you type `yF`, Vimium sees that there is no command bound to `yF`, then checks just `F` on its own.

**Comment by WestFlame** [comment]
Will "yf" actually copy link to clipboard? When I type "Ctrl+v" in any editor, the clipboard does not contain the link...

**Comment by mrmr1993** [comment]
If you're using Firefox, we don't currently support copy/paste, because the APIs are broken. See #2601 for more info.

If you're using Chrome, this is a new issue and we should investigate it.

**Comment by WestFlame** [comment]
Oh... thanks, that explains it. (yes, I'm using Firefox :) )
