### ISSUE TITLE
Feature Request: Button support on site navigation

### ISSUE THREAD

**Issue by BogBel** [philc/vimium#2779]
Is it possible to develop functional which allows user to click on buttons? possible this will be the same functional like for links-navigating.
Thanks

**Comment by mrmr1993** [comment]
Which website isn't working?

**Comment by BogBel** [comment]
oh, at least gmail.
I can't select few messages, or star them etc.

**Comment by mrmr1993** [comment]
#2762 has been merged to master and will be in the next version, which makes more elements clickable on Gmail. You can try this out by following the steps in [CONTRIBUTING.md](CONTRIBUTING.md), and those changes will be in the next version.

However, some of the buttons are difficult/impossible to distinguish from non-buttons. The ideal fix would be if they used the [ARIA](https://www.w3.org/WAI/intro/aria) attributes more extensively; you might want to send a bug report/feature request to the Gmail team for that.

**Comment by BogBel** [comment]
Okay, can be closed. Thanks.
