### ISSUE TITLE
Modifiers are resolved strangely

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#2786]
Since #2772 has been merged, <kbd>ctrl</kbd> and <kbd>alt</kbd> are resolved as `<c-control>` and `<a-alt>`. Presumably the OS X behaviour is similar for <kbd>meta</kbd>.

Should we special-case these? How about `<a-c-control>`, `<a-c-alt>`, etc.?

Relatedly, should we have a modifier prefix for <kbd>shift</kbd> so that we can use that in non-printing key combos (e.g. `<s-F1>` for <kbd>shift</kbd> + <kbd>F1</kbd>)?

**Comment by lydell** [comment]
Why are lone modifiers allowed at all? To me, that’s sounds like an antipattern. If you bind `<ctrl>` to open a new tab, you can no longer use any standard ctrl-shortcut without also opening a new tab. FWIW, VimFx didn’t support this: https://github.com/lydell/vim-like-key-notation/blob/59ae1965c2589bdd3322fe21ecbe735e9e0cbe12/index.js#L58

**Comment by mrmr1993** [comment]
Steve [has already said as much](https://github.com/philc/vimium/pull/2785#issuecomment-343392394). This was introduced by #2772.

I could imagine a modifier mid-binding might be useful for discriminating similar commands, but getting rid of them probably isn't a deal-breaker for anyone.
