### ISSUE TITLE
[Firefox] Can't reset "Characters used for link hints" to default

### ISSUE THREAD

**Issue by erikw** [philc/vimium#2787]
I have set a custom value for this field before, "0123456789". Below the input field in the the settings page it says "Leave empty to reset this option.". But when do this, and hit the save button, the field is re-populated with the previous value. 

Thus it's not possible to reset this setting to default! :(

Firefox: 56.0.2
Vimium-ff: Latest, don't know how to see the current version being installed.

**Comment by mrmr1993** [comment]
Do you have the "Use a link's name and characters for link-hint filtering" option set? (You may need to press the "Show Advanced Options" button to see it.) That *is* the default value if that's set.

**Comment by erikw** [comment]
Yes this option is set! Should it? 

This is what is looks like before I hit the save button. When I do, the text field gets re-populated

![screenshot_2017-11-11-205211_866x519](https://user-images.githubusercontent.com/175286/32692964-3d4dead0-c722-11e7-9ab5-80904175445c.png)

**Comment by mrmr1993** [comment]
Yes, that's the expected behaviour

**Comment by erikw** [comment]
I think the text "Leave empty to reset this option." is confusing then, as it's not clear that you have to uncheck "Use the link's name and characters..."  do do reset-to-default, and not empty the field as  it says. :)
