### ISSUE TITLE
Hebrew related issue

### ISSUE THREAD

**Issue by yossioulu** [philc/vimium#279]
International users, often switch the keyboard between English to the local language (e.g. Hebrew). This creates annoying issue when using Vimium. The shortcuts are in English so English must be selected as the current language. If Hebrew is the current language then clicking on e.g. the key 'n',  will produce some other character and will not do Page Down. 
Since we have to switch a lot between Hebrew and English it is always confusing, which language am I know. It would be great if Vimium would ignore the current language and work regardless.

possible solutions:
- A solution might be to let the user map more then one character for an operation. e.g. for PageDown the user can ask it to be: 'n' or 'מ'. 
- or maybe to check which key was pressed rather than which character it was.
- or one the user keys a character, check the current language and if it is not English, calculate what character would have been produced if English was the current language and use that as the character input by the user for vimium. (I think this is the simplest and clean solution)

This will make life much easier using it for users working with more than one language.
Thank you

**Comment by AminaG** [comment]
שלום לכל דוברי העברית. הוספתי קובץ הגדרות בשביל שזה יעבוד גם כאשר עוברים לעברית.
כל מה שצריך לעשות זה להיכנס להגדרות, שם יש מקום שנקרא
Custom key Mapping
ושם להדביק את הקוד הבא.

map ח scrollDown
map ל scrollUp
map יh scrollLeft
map ך scrollRight
map עע scrollToTop
map זH scrollToLeft
map זL scrollToRight
map ג scrollPageDown
map ו scrollPageUp
map ר reload
map עד toggleViewSource
map ו enterInsertMode
map ה enterVisualMode
map עו goUp
map עU goToRoot
map ען focusInput



map כ     LinkHints.activateMode
map . enterFindMode
map מ performFind
map טט copyCurrentUrl
map טכ LinkHints.activateModeToCopyLinkUrl
map פ openCopiedUrlInCurrentTab
map עא nextTab
map עT previousTab
map ע0 firstTab
map ע$ "lastTab
map א createTab
map טא duplicateTab
map ס removeTab
map ם Vomnibar.activate
map נ Vomnibar.activateBookmarks
map עק Vomnibar.activateEditUrl
map עE Vomnibar.activateEditUrlInNewTab
map עכ nextFrame
map צ Marks.activateCreateMode
map ; Marks.activateGotoMode

**Comment by wildeyes** [comment]
+1

Another suggestion:
 - have . List with checkboxes with language specific mappings contributed by people that one can simply turn on or off.

Such a solution would remove the need to create your own mappings and would easily support international users. Similar to the activation of. The international ad-blocking lists in the popular adblock extension. 

It can even be started with the above mapping that adds support of hebrew-vimium.

**Comment by AminaG** [comment]
In open-source project, you don't give ideas, or suggestion, you just have to do it, and then pull request....

**Comment by mrmr1993** [comment]
> Another suggestion

Instead of storing all the mappings in the codebase itself, it might be easier to create a wiki page ([wiki here](https://github.com/philc/vimium/wiki)) where people contribute international mappings. Anyone can do this then, and it removes the barrier for entry that creating a PR and compiling code requires.

> In open-source project, you don't give ideas, or suggestion, you just have to do it

I'm going to disagree; some people have really good ideas that will help people, but don't have the time/knowledge to implement them, and other people might have the time and skills, but the idea didn't occur to them.

Just my $0.02.

**Comment by wildeyes** [comment]
@AminaG Sure, that was the way it worked, before there were 'issues'. Now that we can discuss the idea before implementing it, not only people with time on their hands can influence the codebase...
