### ISSUE TITLE
not working for chrome@mac

### ISSUE THREAD

**Issue by HaoranYi** [philc/vimium#2790]
here is the error logs. any idea for working around the issue?

20 extensions::uncaught_exception_handler:8 Error in event handler for webNavigation.onCommitted: Error: Invalid value for argument 2. Property 'frameId': Unexpected property.
    at chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/background_scripts/main.js:538:24

**Comment by mrmr1993** [comment]
Without more information, it's nearly impossible to say.
* Which version of Chrome are you running? (`chrome://version`)
* Which version of Vimium are you running? (`chrome://extensions`)
* What isn't working?
* Which (if any) settings have you changed the value of?
* Does it start working again if you clear your Vimium options?
* Does it start working again if you remove and reinstall Vimium?

**Comment by HaoranYi** [comment]
more info

chrome version: 49.0.2623.112
vimium version: 1.61.1
nothing seems working
no setting changes
not working after clearing vimium setting
not working after removing and reinstalling

**Comment by smblott-github** [comment]
For what it's worth, it looks like it's the first mention of `frameId` here:

```Javascript
  chrome.webNavigation.onCommitted.addListener(function(arg) {
    var cssConf, frameId, tabId;
    tabId = arg.tabId, frameId = arg.frameId;
    cssConf = {
```

**Comment by mrmr1993** [comment]
Try upgrading Chrome. There have been over 10 versions released since, and I'm pretty sure we don't officially support versions that old.
