### ISSUE TITLE
Scroller sometimes doesn't find the right element to scroll

### ISSUE THREAD

**Issue by mrmr1993** [philc/vimium#2795]
For example, on [this page](https://www.indy100.com/article/people-amazed-apple-iphone-4-x-jimmy-kimmel-live-video-funny-reaction-technology-8048011), scrolling with Vimium seems to do nothing, whereas scrolling with the up and down keys scrolls the article as expected.

**Comment by smblott-github** [comment]
Are you sure, @mrmr1993?  On your [example page](https://www.indy100.com/article/people-amazed-apple-iphone-4-x-jimmy-kimmel-live-video-funny-reaction-technology-8048011), Vimium scrolling scrolls the body of the article as expected for me, whereas the arrow keys and space bar scroll nothing at all.

**Comment by mrmr1993** [comment]
I've tried again, and now the article doesn't scroll with the arrow keys or Vimium's scroller. For reference, I'm getting a page that looks like this:
![screenshot from 2017-11-12 16-33-48](https://user-images.githubusercontent.com/1847343/32701097-51df0c90-c7c7-11e7-931a-6f5f2529a22c.png)


`firstScrollableElement` is returning `null` for me, and so it's falling back to `getScrollingElement`, i.e. the `<html>` element, which doesn't scroll.

**Comment by smblott-github** [comment]
Yes.  I have the same page.  It still scrolls fine for me.  I tried it in a clean profile too, with grab-back focus both enabled and disabled.  I cannot imagine which other setting could be creating problems.

(I'm running `master` as of Nov. 5th.)

**Comment by mrmr1993** [comment]
I can still repro on 56c2a89613199bc0369a66d19bf848e14b019671 (`master` from November 5th).

By setting a breakpoint in `Scroller.scrollBy`, I get:
* `getScrollingElement() == document.documentElement`
* `firstScrollableElement() == null`:
  - it checks all the children of `element` (`document.documentElement`)
  - `document.body` reports its height as 0, so `DomUtils.cropRectToVisible` returns `null`
  - the `children` array in `firstScrollableElement` filters out `document.body` for having a `null` rect
  - since there are no children left to check, it returns `null`
* the code falls back to `document.documentElement` (via `getScrollableElement()`) and tries to scroll that
* `document.documentElement` can't scroll, and so nothing happens.

Any ideas where you're getting the different behaviour?

**Comment by gdh1995** [comment]
I have also reproduced this case on Chrome 61/62 x64 and Windows 10 x64, and it's mainly because `DomUtils.getVisibleClientRect(document.body)`'s `testChildren` is default to `false`.

But on Chrome 60, the page's `document.scrollingElement` is `document.body`, and `DomUtils.getVisibleClientRect` succeeds in finding visible rects, so Vimium Scroller works on it.

Therefore, I thinks a simple solution is to change `content_scripts/scroller.coffee:L102` from `children = ({element: child, rect: DomUtils.getVisibleClientRect(child)} for child in element.children)` to `... DomUtils.getVisibleClientRect(child, true) ...`

**Comment by GFernie** [comment]
Perhaps a better example:
https://nodejs.org

**Comment by toraritte** [comment]
Scrolling also doesn't seem to work on sites generated with [pdf2htmlEX](https://github.com/pdf2htmlEX/pdf2htmlEX), not sure why.
