### ISSUE TITLE
vimium interferes with devtools Execution Context Selector

### ISSUE THREAD

**Issue by Strangehill** [philc/vimium#2805]
on page load, Execution Context Selector in chrome dev tools console set to "vomnibar.html", rather than leaving it on "top" (like all other chrome extensions I use). This slows down my development as I have to manually set it back to "top". I still find use for vimium while developing so I'd rather not have to exclude localhost in vimium settings though. Are there easy interim solutions to this bug? 
Perhaps related to #2781 ?

**Comment by mrmr1993** [comment]
This isn't something that we're doing/have control over. I suggest filling a bug against Chromium.

**Comment by Strangehill** [comment]
done! 
https://bugs.chromium.org/p/chromium/issues/detail?id=785692
