### ISSUE TITLE
Feature Request: Implementing a provision to select elements from the drop down box.

### ISSUE THREAD

**Issue by ambi88dex** [philc/vimium#2810]
Hello All, I am a regular vimium user. One of the feature I found missing is that the elements in the drop-down box in the navigation bar cannot be selected. It will be really great if this feature gets included as well.

**Comment by mrmr1993** [comment]
> the elements in the drop-down box in the navigation bar

Do you mean the suggestions in the address bar? There's no API for the address bar, so we can't do anything (and that's why the Vomnibar exists in the first place).
