### ISSUE TITLE
Font size preferences

### ISSUE THREAD

**Issue by wavexx** [philc/vimium#2814]
Although it's possible to style the current hint css, I cannot see any way to increase the font size of the search box or the vomnibar. The search box is is completely unreadable for me. It's also disproportionate, as the vomnibar is huge by comparison, and has a very odd position on top of that (but I already see #2342 for that).

**Comment by mrmr1993** [comment]
Since #2683, this has been possible by changing the CSS in the options. It still says for link hints, but I've opened #2815 to (hopefully) make things a bit clearer.

**Comment by smblott-github** [comment]
#2815 is merged.  Closing this.
