### ISSUE TITLE
F and f inverted in Vimium

### ISSUE THREAD

**Issue by alexnewgen** [philc/vimium#2819]
It seems like using f and hitting the link shortcut actually opens a new tab, while F keeps it in the same tab. Is this desired behaviour, because this doesn't match up with the documentation? I'm using the latest version of Chromium on Chrome 62.

Thanks,
Alex

**Comment by mrmr1993** [comment]
Don't hold the shift key while you're choosing the link.

**Comment by alexnewgen** [comment]
Ah sorry. I thought it was case sensitive.
