### ISSUE TITLE
"p" redirects to default search engine URL

### ISSUE THREAD

**Issue by Geremia** [philc/vimium#2828]
In Firefox 57, pressing "p" (Open the clipboard's URL in the current tab) simply redirects to https://www.google.com/webhp , which is not even my predefined homepage, nor is Google my default search engine (although https://www.google.com/search?q= is specified in Vimium's options). In a blank tab, pressing "p" has no effect.

**Comment by smblott-github** [comment]
Paste is currently broken in Firefox, and we do not have a reliable way of fixing it.  So, the `p` command will probably be removed in FF.

Copy is broken in the currently release, but will be fixed soon.

**Comment by cgbahk** [comment]
Same situation occurs since recently, maybe one or two days ago?
- Ubuntu 20.04
- Chrome Version 105.0.5195.102 (Official Build) (64-bit)
- Vimium 1.67

Had no issue before last week.

**Comment by Wayne-Kao** [comment]
I've had this problem recently too.

- Windows 10
- Chrome Version 105.0.5195.127 (Official Build) (64-bit)
- Vimium 1.67

**Comment by gdh1995** [comment]
@Wayne-Kao Your issue may be related about #4120 .
