### ISSUE TITLE
Not working for timesofindia.indiatimes.com

### ISSUE THREAD

**Issue by manasthakur** [philc/vimium#2830]
I was used to VimFX and am using this post Quantum. I like the extension and that it runs quite lightly. However, it doesn't seem to work on `timesofindia.indiatimes.com`. Can you please check?

**Comment by mrmr1993** [comment]
Confirmed. This is caused by Firefox issue [1408996](https://bugzilla.mozilla.org/show_bug.cgi?id=1408996).

If you want to help get it fixed, please go to that bug, log in (you can use your GitHub account), and vote for it by clicking the "vote" button.
