### ISSUE TITLE
How to show hyperlinks URLs?

### ISSUE THREAD

**Issue by eyalev** [philc/vimium#2839]
Sometimes i'd like to know what is the URL of a hyperlink before I click it.

Today I'm doing it by hovering the mouse over a link so I could see the URL in Chrome's bottom window section.

Is there a way to do it with Vimium?

Maybe something like 'link hints', but instead of opening the link - just show the URL.

Thanks

**Comment by decadent** [comment]
BTW, this was previously discussed in #320, but seemingly ended nowhere.

**Comment by politicus** [comment]
@eyalev Take a look at [this](https://github.com/philc/vimium/wiki/Tips-and-Tricks#hovering-over-links-using-linkhints).

**Comment by eyalev** [comment]
Thanks @politicus!
