### ISSUE TITLE
Insert mode not activated on Github login

### ISSUE THREAD

**Issue by pjbruce** [philc/vimium#2841]
Logging in to the user interface on github, when I type "p" in the username text box, Chrome closes the current link and opens the Google link.

**Comment by smblott-github** [comment]
Reproduced.

Somehow `@insertModeLock` is being reset to `null`.

@mrmr1993 Might we not just get rid of `@insertModeLock` all together (and all the associated code), and just do a dynamic check instead (as we already do for content editable)?

**Comment by mrmr1993** [comment]
> Might we not just get rid of `@insertModeLock` all together

I'm pretty sure I proposed it before and you had an objection, but I can't remember what it was. I'm very happy to move in this direction.
