### ISSUE TITLE
No command / key works in empty tab in Firefox

### ISSUE THREAD

**Issue by sl8ar2rk** [philc/vimium#2845]
If I open a new blank tab so I can not use any command. Nothing works.

kind regards

**Comment by smblott-github** [comment]
Chrome just does not run Vimium on some pages.  I suggest using [this](https://chrome.google.com/webstore/detail/new-tab-url/njigpponciklokfkoddampoienefegcl) to get around this problem.  I'm the author, it has to be one of the smallest extensions ever.  The body of the extension is just [four lines of code](https://github.com/smblott-github/chrome-new-tab-url/blob/master/redirect.coffee).

**Comment by sl8ar2rk** [comment]
Thanks for answer. But I'm sorry I forgot to say I use firefox. Not Chrome. 
Do you have maybe a solution too.

**Comment by devnoname120** [comment]
When https://github.com/cadeyrn/newtaboverride/issues/92 is implemented, newtaboverride will be a good workaround for this issue.

**Comment by devnoname120** [comment]
Actually setting the "New tab URL" option in Vimium as "pages/blank.html" is enough to fix the issue.

**Comment by Taconut** [comment]
Anyway to get this working with new tab pages like Momentum? I know in Chrome you can screw around with chrome flags to allow Vimium to work on chrome-extension:// pages. Is there any analog of this in Firefox?

**Comment by wnereiz** [comment]
pages/blank.html do the work, but a featured new tab rather than blank is useful. Is it possible to "copy" default new tab pages to pages/blank.html as a work around?

**Comment by smblott-github** [comment]
>  Is it possible to "copy" default new tab pages to pages/blank.html as a work around?

As far as I know, no.

**Comment by AndrewSouthpaw** [comment]
@devnoname120 that solution worked for me and is so simple and elegant! Thanks for that! 🙌

**Comment by actionless** [comment]
setting both firefox newtab page and vimium start page to `about:blank` (instead of "Firefox Home") solved the problem for me

**Comment by btctrl** [comment]
> Actually setting the `New tab URL` option in Vimium as `pages/blank.html` is enough to fix the issue.

Is this in the vimium options where we remap keys? Is this done without any other new tab extensions?

Can't seem to find this setting anywhere

**Comment by actionless** [comment]
@btctrl not sure what you mean,
![2022-02-12--1644689132_1403x101_scrot](https://user-images.githubusercontent.com/1655669/153722840-7ca1d58e-8a58-4651-95a6-b701bc50ec6a.png)

**Comment by dvof** [comment]
@raffaem 
> Why isn't that the default option for that setting?
Because, for me, this does not have the same functionality as doing a `New tab` natively in Chrome. It would be better if that "about:newtab" page would just be working with Vimium. But I guess security is important as well.

**Comment by actionless** [comment]
>  It would be better if that "about:newtab" page would just be working with Vimium

i think neither in firefox nor chrome extension can't inject any js code into such pages (or Settings page for example)

**Comment by praimmugen** [comment]
> > Actually setting the `New tab URL` option in Vimium as `pages/blank.html` is enough to fix the issue.
> 
> Is this in the vimium options where we remap keys? Is this done without any other new tab extensions?
> 
> Can't seem to find this setting anywhere

If anyone else is also struggling to find this option, there's a bar at the bottom of the Vimium settings page to show advanced options. The bottom bar can be a bit hard to see if you're using a large screen.
