### ISSUE TITLE
Idea... provide feedback via the popup page

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#2850]
One of the most commonly-posted issues is *Why doesn't Vimium run on page X?* (where *X* is perhaps another extension page).

When we encounter such a page, we could populate the Vimium popup not with exclusion rules, but with a message stating why Vimium cannot run on the page instead.

**Comment by mrmr1993** [comment]
Nice, we should definitely do this!

**Comment by smblott-github** [comment]
I'm not sure how to detect that Vimium cannot run.  It turns out that this: e9fba3a6c1aa2979a4045f61c3d03ad9cefd9a4b, isn't good enough.

We may have to just match known-bad URLs.

For the record, e9fba3a6c1aa2979a4045f61c3d03ad9cefd9a4b looks like this...

![snapshot](https://user-images.githubusercontent.com/2641335/33516599-614018fe-d76d-11e7-91c8-9349246db5d7.png)

**Comment by mrmr1993** [comment]
I tried tweaking when we register ports from frames (43c7390f987fea063e7a97cd8b37c7b61d45f615) and then using that to detect when we're completely shut out of the tab (fb00eaa6bd4ee8889d10a9ef9d976fefd3be7879). My branch is [here](https://github.com/mrmr1993/vimium/commits/experiments/disabled-popup-message), which includes your commit, and seems to work in all the cases I've tested.

**Comment by smblott-github** [comment]
Excellent.  Merged.  Thanks.
