### ISSUE TITLE
[Firefox] Vimium doesn't work in reading mode

### ISSUE THREAD

**Issue by Priddles** [philc/vimium#2854]
**As far as I can tell, Vimium doesn't work in Firefox's reading mode.**

I've tried removing all the exclusion rules and setting everything to defaults but none of Vimium's keys are responding. Vimium's icon is not greyed out either, so I assume that Vimium is active but unable to capture input for some reason.

**Comment by smblott-github** [comment]
The URL of the reader seems to be `about:reader` (whatever that means).  It appears that firefox simply does not run Vimium on that kind of page.

**Comment by Priddles** [comment]
Damn. Extensions used to run correctly in reading mode before Quantum.

**Comment by erikw** [comment]
@smblott-github The URL looks the same in the URL-bar after clicking on the reader-mode button at least. Where did you se `about:reader`? :)

**Comment by ShehuAwwal** [comment]
I do hope this can be considered, Thanks to the team.

**Comment by anonimo0-0** [comment]
Is it possible to request it from the firefox dev team?
