### ISSUE TITLE
I want to pop current tab to a new window

### ISSUE THREAD

**Issue by shixuguo** [philc/vimium#2859]
I found the new function is interesting!
>  command options for createTab to create create new normal and incognito windows (examples).

now, I want to pop current tab to a new window,
I have known fucntion 'copyCurrentUrl' by pressed 'yy'
and I also known function 'createTab',
but how can I pass the copiedurl to 'creatTab'?

**Comment by smblott-github** [comment]
It looks like you need this command....

![image](https://user-images.githubusercontent.com/2641335/33796938-52d755be-dcf6-11e7-9ab9-c959622a26e6.png)

The default binding is `W`.

**Comment by shixuguo** [comment]
@smblott-github  great！ thanks！
