### ISSUE TITLE
createTab with multiple URLs no longer works in 1.62

### ISSUE THREAD

**Issue by kinclma1** [philc/vimium#2868]
After updating to 1.62, pressing a keybind to open multiple URLs with createTab opens just the first one.
Chrome version: 63.0.3239.84
FF version: 58.0b11
Vimium version: 1.62

**Comment by smblott-github** [comment]
Confirmed. Fixed in 4aa8d7fb21a26b0766ce32e3fab0cf1efcaa07fb.

**Comment by kinclma1** [comment]
Git tag 1.62.2 works fine, but 1.62.2 from the store doesn't.

**Comment by smblott-github** [comment]
I think you might be right.  I've somehow uploaded a version without the fix.

**Comment by kinclma1** [comment]
Works fine now, thanks again.
