### ISSUE TITLE
Vimium on tweetdeck.com (Google Chrome).

### ISSUE THREAD

**Issue by politicus** [philc/vimium#2872]
I wanted to use Tweetdeck keyboard shortcuts on https://tweetdeck.twitter.com/ to navigate/change the focus between the different columns and realised I had to exclude all the keys of the Vimium extension to be able to do so. Every time, I added a key, Vimium stopped working in the sense I couldn't navigate/change the focus between the different columns but I could favorite tweets using Tweetdeck keyboard shortcut.

Vimium 1.62.4
Google Chrome  63.0.3239.84
OS Mac OS X 10.12.6

**Comment by innaterebel** [comment]
Simply enter insert mode (<kbd>i</kbd>) is enough, isn't it?
Or you just don't want Vimium to be active at all times on Tweetdeck?

**Comment by politicus** [comment]
Your answer helped me find the solution which was excluding (0,...,9).
Thank you!
