### ISSUE TITLE
Vimium not working on Facebook

### ISSUE THREAD

**Issue by bad63r** [philc/vimium#2879]
When I press f or F nothing happens. Other than that seems to work fine (pressing t, yy and others are just working fine).
os: ubuntu linux 16.04 , Firefox 57.0.1

**Comment by smblott-github** [comment]
Thanks for the report, @bad63r.

Some very weird behaviour from Firefox, but fixed in d9b6d5e18839d1af509d859af5faed880f43fe1e.  Will release soon.
