### ISSUE TITLE
Feature request: checkbox mode

### ISSUE THREAD

**Issue by davidrthorn** [philc/vimium#2883]
Would be great to be able to have a mode whereby multiple checkboxes/radio buttons could be checked in the same way that links are followed, but without having to repeatedly enter link following mode in between checkboxes. Obviously, this can be achieved with 'f' followed by the relevant key combination, but this requires pressing 'f' between each selection. A checkbox mode could keep the relevant link codes active while in that mode.

**Comment by smblott-github** [comment]
If you want to check three boxes, then try `3f`.

**Comment by mrmr1993** [comment]
You could also use `LinkHints.activeModeWithQueue`, bound by default to `<a-f>`.

**Comment by davidrthorn** [comment]
`3f` worked perfectly, thank you! Love this add on.
