### ISSUE TITLE
Allow Exclusion of Escape Key

### ISSUE THREAD

**Issue by rogershijin** [philc/vimium#2889]
On some websites it is convenient to close some popup boxes with Escape (e.g. messenger boxes on Facebook/Google Hangouts).  With Vimium-FF enabled on these websites, pressing escape enters Normal Mode instead of closing these boxes.  Would it be possible to allow users to add <Esc> to the Excluded Keys list?

**Comment by rogershijin** [comment]
Resolved by passNextKey.
https://github.com/philc/vimium/wiki/Tips-and-Tricks

**Comment by orschiro** [comment]
Dear @rogershijin,

I am facing the same problem and added `map <c-]> passNextKey` to the `options.html` page in the field `Custom key mappings`.

Now, which keys do I need to press to trigger `<c-]>`?

This is not clear to me.

Thank you!

**Comment by smblott-github** [comment]
I don't understand the question.  What does "trigger `<c-]>`" mean?  Does it mean "execute the `passNextKey` command"?

**Comment by orschiro** [comment]
That's exactly what I want, great!

What do I need to press in which sequence to produce `<c-]><Escape>`?

**Comment by smblott-github** [comment]
`<c-]>` means hold down the control key and press `]`.

Then, `<Escape>` just means press Escape.

**Comment by orschiro** [comment]
Thank you so much!

I found it. 

The confusion arises from my German keyboard. There I need to press: `Ctrl + AltGr + 9`.

**Comment by MikeMajara** [comment]
If vimium only uses <Escape> to exit insert mode, and insert mode is disabled, would it not be easier to exclude this key too (either in code, or just allow to exclude keys specified like <Escape> or <c>)...

**Comment by johny65** [comment]
The `passNextKey` solution still needs to press several keys just to be able to use Escape... I prefer pressing Escape twice (one to exit insert mode, another to do what Escape does) than a weird combination... I think it should be possible to exclude Escape key directly.

**Comment by gdh1995** [comment]
Hello, I've got another solution: add a special option to specify some CSS selectors, and when a `Escape` is pressed on such matched input elements, auto pass the key and then call `element.blur()` and exit from InsertMode in 1 millisecond; when the CSS selector mismatches, run the old process (blur, exit from InsertMode and block the key).

I've implemented it in my customized version of Vimium, named Vimium C (https://github.com/gdh1995/vimium-c), and it's here: 
![image](https://user-images.githubusercontent.com/5547703/169567813-c6099fef-fc62-43c5-8b00-edc181a6a695.png)

**Comment by ViktorQvarfordt** [comment]
I don't see this as resolved since pressing escape doesn't send the key event to the underlying site. If the user is not in any mode, why cant Escape just be sent to the underlying site?

**Comment by thiago-gitlab** [comment]
The PassNextKey trick worked for me on FF 129.0 (64-bit) macOS to dismiss the gitlab.com/gitlab-org modal that is brought-up by pressing `/`.

It's inconvenient to use a combo for this but I'm thankful for the workaround.
