### ISSUE TITLE
[Feature request] Open link in new tab and move to this tab

### ISSUE THREAD

**Issue by deescuderoo** [philc/vimium#2892]
I looked for this on your repository and couldn't find anything about it. When I'm browsing with the mouse in chrome, if I hold the `shift` and `ctrl` keys and click on a link the browser open this link in a new tab and moves to this tab. Is there a way to do this with vimium?

Great app by the way! Thanks for your hard work :)

**Comment by innaterebel** [comment]
Hold <kbd>Ctrl</kbd> while you enter the last letter of a hint.

Also FWI, doing the same with <kbd>Shift</kbd> is to switch between the `open in new`/`open in current` behavior.
You can see these mode shifting indicated on the HUD while link hints is activating.

**Comment by deescuderoo** [comment]
I see, apparently the problem is that as I'm using vimium in a MAC, I was trying to use the command key for this purpose (which is the key I used with the mouse), but with vimium the control key is the one that must be used.

Thanks for the info!
