### ISSUE TITLE
Some websites have way too many hints

### ISSUE THREAD

**Issue by noreferences** [philc/vimium#2905]
For example [YouTube](https://imgur.com/a/TYM7f), I really do think that's a bit excessive. Is there any solution to this? There are so many hints that sometimes it's a gamble when typing things in.

About:
    Firefox 59.0a1 (2017-12-20) (64-bit)
    Vimium (version 1.62.8)

**Comment by ScottEfird** [comment]
It is interesting that the chrome version gives such a different result. https://imgur.com/a/ZJbrY

**Comment by krlooss** [comment]
@ScottyEfird the difference is that you scrolled down, so you don't have that many on the top bar. About the ones on top of the video, I don't get them either. 
Chrome 64.0.3282.167 (Official Build) (64-bit)
Vimium 1.63
https://imgur.com/a/4u8Fz

**Comment by ScottyEfird** [comment]
@krlooss Checked again, you're correct.

**Comment by no-references** [comment]
Here's another example

![2018-03-02-172657_1439x843_scrot](https://user-images.githubusercontent.com/13085275/36912551-fa0c40ea-1e3e-11e8-9553-2720f9b91683.png)

**Comment by no-references** [comment]
Here's another example:

![2018-03-02-172804_1439x841_scrot](https://user-images.githubusercontent.com/13085275/36912608-1e673080-1e3f-11e8-9830-5c738c2f5d01.png)

**Comment by ggoofer** [comment]
Prior to FF57 I used VimFx which somehow dealt with this issue. I don't know if this is useful at all for Web extensions, but just in case: https://github.com/akhodakivskiy/VimFx/blob/16d72926b11b8ed63b27a779047599b62eecaf62/documentation/commands.md#the-hint-commands--hints-mode

**Comment by noreferences** [comment]
The issue seems to have gone.
