### ISSUE TITLE
pass through unmapped keys to the page

### ISSUE THREAD

**Issue by introom** [philc/vimium#2906]
When I watch on youtube, I press spacebar to pause the video.

I'd like vimium enabled, but also be able to play/pause youtube videos (with spacebar).

Is that possible?

**Comment by smblott-github** [comment]
Vimium doesn't do anything with the space bar (unless you have that configured yourself, which you probably haven't).

On youtube, the space bar is pause/play *if the video has the focus*, otherwise it's scroll as usual (I think).

**Comment by introom** [comment]
thanks.   After your hint, I checked SPC is indeed a prefix of some mappings in my configure.

BTW, is it possible to emit a key code by some keys.

map somekyes emitKeyCode('SPC').

**Comment by smblott-github** [comment]
> BTW, is it possible to emit a key code by some keys.

No.
