### ISSUE TITLE
J and K do not work in pinned tabs in Firefox

### ISSUE THREAD

**Issue by Vinnl** [philc/vimium#2908]
I can use `J` and `K` to switch to the tab left and right of the current tab, respectively - _unless_ the current tab is a pinned tab, in which case nothing happens at all. This is in Firefox 57.

**Comment by ris58h** [comment]
@Vinnl Can't reproduce. I've just pinned a couple of tabs and J/K navigation works fine for me (Firefox 57.0.4).

**Comment by Vinnl** [comment]
Aargh allright, my apologies - this was a classic case of me being stupid. I'd forgotten I'd made an exception for the pinned tab because I use the website's native keyboard shortcuts. Sorry for wasting your time.
