### ISSUE TITLE
Cannot input successive Japanese/Chinese/Korean words on MacOS

### ISSUE THREAD

**Issue by regmarmcem** [philc/vimium#2915]
When I input some texts written in Japanese/Chinese/Korean, I cannot input any characters following a Japanese/Chinese/Korean word before searching.  These languages need to type `<enter>` key to convert characters to a word that makes sense, but I cannot search two successive words because of this problem.

This problem arises both in `find mode` and in search window.

Environment:
Mac OS: High Sierra 10.13.1
Google Chrome: 63.0.3239.132 (Official Build)(64 bit)
Vimium: 1.62.4

I put an example below. 

![output](https://user-images.githubusercontent.com/27683817/34937128-023dddaa-fa27-11e7-8b51-18e2e0108173.gif)

**Comment by smblott-github** [comment]
> These languages need to type `<enter>` key to convert characters to a word that makes sense,

Is it just `<Enter>` on its own, or is there also a modifier?

**Comment by regmarmcem** [comment]
Just `<Enter>` on its own.
In Japanese, only `<Enter>` key decides what Japanese words I type.
According to my trying to search in other languages, this rule appears to be applicable to Chinese/Korean.

**Comment by smblott-github** [comment]
How do other sites differentiate between `<Enter>` meaning *done*, and meaning *convert characters*?

E.g., [Whatsapp](https://web.whatsapp.com/), where `<Enter>` normally means *send*.

**Comment by regmarmcem** [comment]
Same problem occurs in sites like that.
(Actually I tried only in [Slack][1])

[1]: https://slack.com/

**Comment by innaterebel** [comment]
You mean when you entering CJK phonetics in a Vimium input and press <kbd>Enter</kbd> intending to confirm the words conversion, Vimium always immediately catches the <kbd>Enter</kbd> as `send`, right?

I cannot repro on Windows, tried Chinese and Japanese IME.

**Comment by regmarmcem** [comment]
@innaterebel 
Thank you for perfect explanation! That's right.

**Comment by gdh1995** [comment]
I'm using the Chinese Pinyin IME of Windows 10, and `<space>` is used to select a word, so I haven't seen such a problem. And when the IME is enabled, `<Enter>` only types letters to a Vimium input (not commits them).

**Comment by regmarmcem** [comment]
I tried on Windows10, but I cannot repro this problem. This problem seems to be unique to MacOS.
