### ISSUE TITLE
Has trouble trying to figure out what to scroll in pages with multiple scrollable divs

### ISSUE THREAD

**Issue by inducer** [philc/vimium#2918]
Consider this page:

https://www.khronos.org/registry/OpenCL/specs/opencl-2.2.html

* Click somewhere in  left pane, cursor up/down scrolls left pane, j/k scrolls left pane.
* Click somewhere in  right pane, cursor up/down scrolls right pane, j/k *still* scrolls left pane.

(This is in Firefox 57 with vimium 1.62.8)

**Comment by smblott-github** [comment]
Cannot reproduce, @inducer.  Everything j/k scrolls as expected for me.

Anybody else?

**Comment by inducer** [comment]
Hm. Now I can't reproduce it either. Weird. Sorry for the noise.
