### ISSUE TITLE
Move to higher URL command

### ISSUE THREAD

**Issue by ikneg** [philc/vimium#2920]
Thank you for providing a great add-on! I would like to request additional functions. I'd be happy if you let me move to higher URLs with commands.
current url: `https://www.example.com/aaa/bbbb`
url after moved: `https://www.example.com/aaa`

I'm sorry if adding a feature addition request to an issue is forbidden.

Thank you!

**Comment by smblott-github** [comment]
I think you're looking for the `gu` command (`goUp`).  There's also `gU` to go right to the top.

**Comment by ikneg** [comment]
@smblott-github Thank you for teaching me! I did not know that the command already exists. I had to click "Show advanced commands" when I pressed the help command. I also confirmed that I can move to the upper level with the gu command. Thank you very much!
