### ISSUE TITLE
how to use vimium in China

### ISSUE THREAD

**Issue by TomLongJoy** [philc/vimium#2928]
Now I can download vimium.zip from github,but I can not use it  in China,who can  help me!

**Comment by smblott-github** [comment]
Here are the instructions of [building from source](https://github.com/philc/vimium/blob/master/CONTRIBUTING.md#installing-from-source), if that's what you want to do.

**Comment by gdh1995** [comment]
If you can download a file from GitHub, here's the Chrome Web Store version:
[vimium_v1.62.4.crx.zip](https://github.com/philc/vimium/files/1670856/vimium_v1.62.4.crx.zip) . Unzip this file and you'll get vimium_v1.62.4.crx; then you can drag it to your Chrome window.

**Comment by TomLongJoy** [comment]
thank you floor 2！！
