### ISSUE TITLE
Vimium not working in latest chromium dev version

### ISSUE THREAD

**Issue by AnthonyWC** [philc/vimium#2931]
Even the icon doesn't light up, restart chromium doesn't help

I am on chromium dev version /w vimium 1.62.4:
```Version 64.0.3282.39 (Developer Build) Ubuntu 16.04 (64-bit)```

**Comment by smblott-github** [comment]
Cannot reproduce here (Chrome 64.0.3282.119).  Do you perhaps have any non-standard flags enabled, @AnthonyWC ?

**Comment by innaterebel** [comment]
And your version is far from being the latest, @AnthonyWC. Dev channel for all platforms are currently on M65 and are only few days away from being upgraded to M66.
I also don't notice there is a Dev version for Chrom_ium_. Chromium are just ever-changing snapshots, aren't they?

**Comment by AnthonyWC** [comment]
Turns out there were some zombie processes that must've caused Vimium to not load.
