### ISSUE TITLE
fixed keys

### ISSUE THREAD

**Issue by shiqizheng** [philc/vimium#2936]
is hitting f key then the corresponding letters the only way to perform enter a page every time? It seems that the page can become very cluttered and it's not very convenient. It would even more efficient if there are some keys that can be memorized. For example, the tabs in github shown above stay the same as we navigate to different pages, but the keys to access these tab change.

**Comment by innaterebel** [comment]
The established expedient solution is to use the `Use the link's name and numbers for link-hint filtering` option in Vimium settings.
See the likes of #2011, #2219, and #1850 for the rationale.

**Comment by smblott-github** [comment]
Yes.  Recommend using filtered hints, as @innaterebel said.

See also #2927.  Closing.
