### ISSUE TITLE
Case-insensitivity "\I" not working

### ISSUE THREAD

**Issue by shammellee** [philc/vimium#2937]
Example:

```
/test\I
```

Chrome: Version 63.0.3239.132
OS: Mac

**Comment by smblott-github** [comment]
Confirmed.  Thanks, @shammellee.

It looks like that has been broken for a *very* long time (which suggests that it is almost never used).

The `\I` flag was introduced before Vimium implemented smart case.

I'd propose just removing the `\I` feature.

**Comment by philc** [comment]
+1

**Comment by gdh1995** [comment]
Well, in my tests, the `\I` flag works well on Chrome stable x64 (51.0.2704.106, 63.0.3239.132 and 64.0.3282.140) and Windows 10 x64. So this issue may be a problem only occuring on Mac OS.

@smblott-github Therefore, I don't think we should remove this feature.

**Comment by smblott-github** [comment]
> Therefore, I don't think we should remove this feature.

I hear you, @gdh1995.  However, let's leave it removed for now, and see whether anybody else cares.  It's simple enough to put back later.
