### ISSUE TITLE
How to go to options from a binding?

### ISSUE THREAD

**Issue by nikitavoloboev** [philc/vimium#2938]
I couldn't find it in settings. I wanted to map `gg` to open Options so I can edit configuration of Vimium quickly.

**Comment by smblott-github** [comment]
Try...

    map gg createTab URL

(See [here](https://github.com/philc/vimium/wiki/Tips-and-Tricks#creating-tabs-with-urls-and-windows).)  Or create a global mark.

**Comment by nikitavoloboev** [comment]
This works. Thank you.
