### ISSUE TITLE
Use Firefox's "Find" feature instead of Vimium's own one

### ISSUE THREAD

**Issue by n-o-o-b** [philc/vimium#2943]
Why does Vimium need to have its own "Find" feature when Firefox already has one built in which is better than Vimium-FF's?

**Comment by ris58h** [comment]
@n-o-o-b You can take a look at Vimium's documentation about [Find Mode](https://github.com/philc/vimium/wiki/Find-Mode).
td;dr: regex support and query history.

**Comment by smblott-github** [comment]
Closing.

If you don't want to use Vimium's find mode, then don't:

```
unmap /
unmap n
unmap N
```

(In the *Custom key mappings* input on the options page.)
