### ISSUE TITLE
Add a feature that allows bookmarks to be created

### ISSUE THREAD

**Issue by ErikShiken** [philc/vimium#2945]
I've used Vimium for about a week now and decided to install it on all of my computers. Its really easy to use and simplifies a lot of stuff when interfacing with Chrome or Firefox. Something that could really simplify using a browser would be to allow bookmarks to be created. The less I can use a mouse, the better :)

**Comment by ris58h** [comment]
@ErikShiken Ctrl+D is a standard shortcut for both browsers.

**Comment by smblott-github** [comment]
Yes.  I think this is unlikely to be added.  Mainly because of the additional UI machinery required, all for fairly marginal benefit.

**Comment by ErikShiken** [comment]
I see. Thanks for pointing the shortcut out
