### ISSUE TITLE
Any way to reverse the direction of Shift+J/K?

### ISSUE THREAD

**Issue by JaneSmith** [philc/vimium#2948]
When scrolling a page, J scrolls down and K scrolls up. That's all fine. When switching between tabs, Shift+J moves to the previous tab (to the left), and Shift+K moves to the next tab (to the right).

I'm actually using Tree Style Tabs, which gives me a vertical list of tabs on the left side instead. Older tabs are at the top, and newer tabs are at the bottom. This means that when I press Shift+J, it moves _up_ to the previous tab, and when I press Shift+K it moves _down_ to the next tab. This is inconsistent with the behaviour when scrolling the page normally without Shift.

Is there any way to reverse the movement direction? I've had a look in the extension's options and I don't see anything, but maybe I'm missing it. If not, could an option be added?

**Comment by smblott-github** [comment]
You can remap keys on the options page...

    map K previousTab
    map J nextTab

**Comment by HarshalGunjalOp** [comment]
@smblott-github Thank you very much.
