### ISSUE TITLE
REQUESTS: go to address bar keybinding & enable escape from address bar

### ISSUE THREAD

**Issue by niemand** [philc/vimium#295]
In Vimprobable, UZBL, etc. you can go to the address bar with just a single key (e.g. <o>), which is a heck of a lot less awkward than Chrome's <c-l>. I'd love to see that incorporated into Vimium. Also, it'd be nice if I didn't have to tab out of the address bar every time I want to resume browsing. If anything, it'd really complete that modal feel!

**Comment by voddan** [comment]
Hey, guys!
Can you point me to the Chromium bug tickets that a relevant to this issue?
Just looked through the wiki page and didn't noticed any similar.
Thanks

**Comment by mrmr1993** [comment]
There are several relevant issues [here](https://code.google.com/p/chromium/issues/list?can=1&q=label%3Acr-platform-extensions+omnibox+focus&colspec=ID+Pri+M+Week+ReleaseBlock+Cr+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=tiles).

I think the one that we're hoping to be helped by (from the wiki) is [28084](http://code.google.com/p/chromium/issues/detail?id=28084).

**Comment by rrsahutwo** [comment]
Certainly there are several moving or moving companies in our nation India which can claim to be the best moving companies, but be careful about them. Most of them may be self claimed best solutions company so go through the company’s stability and stability in its solutions. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
Apart from other companies, EXPERT Packers is a authentic and licensed moving organization which provides profession customized and complete movers in all states of India. The elevated stage of stability and loyalty create us a leader in the industry. Due to our stability and cheap costs, we are the first option of those who look to take advantage of expert movers and packers solutions. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
Our complete movers include all kind of activities such as product packaging, transportation, putting in order, running, unloading, unpacking, etc. If you seek the services of our complete solutions of best packers and movers in Bangalore , we will help you an individual plan including everything from product packaging of all kinds household or workplace products and also other considerations to practical transportation of bike, car and furnishings, etc. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
Our expert moving solutions create the procedure of your shifting or moving of company, house, shop or workplace very easier and stress- 100 % free. EXPERT Packers, the expert movers has a group of dedicated employees who are expert in different jobs.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
