### ISSUE TITLE
How to disable the escape sequence in sites like "codepen"?

### ISSUE THREAD

**Issue by a-eid** [philc/vimium#2950]
I use vim on some sites like "codepen", when I hit "ctrl+[" vimium buts me in normal mode, which is not what I want, 

I'd like to completely disable vim on a certain site, but I realize that this is not an option right now. 
how do I  exclude `ctrl+[` from doing anything on "http?://codepen.io/*" ?

thanks.

**Comment by smblott-github** [comment]
> I'd like to completely disable vim on a certain site, but I realize that this is not an option right now.

You can completely disable Vimium via the Vimium popup...

![image](https://user-images.githubusercontent.com/2641335/36059627-bbeb6b80-0e33-11e8-86e8-4e82cfe3df6b.png)

Leave "Keys" empty and Vimium is completely disabled. See [here](https://github.com/philc/vimium/wiki/Disabling-Vimium).

See also [here](https://github.com/philc/vimium/wiki/Tips-and-Tricks#using-the-escape-key-in-inputs) and [here](https://github.com/philc/vimium/wiki/Tips-and-Tricks#key-mapping) (disabling `<c-[>`).

**Comment by a-eid** [comment]
@smblott-github  thank you, that really helped.
