### ISSUE TITLE
Search current site

### ISSUE THREAD

**Issue by pdoak** [philc/vimium#2956]
I have added the following code as a custom search engine to search the current site as described in the documentation but it doesn't work:

`cd: javascript:location='http://www.google.com/search?num=100&q=site:'%20+%20escape(location.hostname)%20+%20'%20%S'%20;%20void%200`

When I type `cd<space> search-terms` in Vimiums omnibar, I search Google for `cd search-term` and not the current site. Am I doing something wrong

**Comment by pdoak** [comment]
Thank you for your answer. I am surprised that it does not work as it is clearly stated as a an example on the [Vimium wiki](https://github.com/philc/vimium/wiki/Search-Engines).

Vimium ++ looks good but it doesn't seem to allow `Use the link's name and characters for link-hint filtering` which is a an option that I have set permanently.

**Comment by gdh1995** [comment]
Um, "site:" in the [wiki](https://github.com/philc/vimium/wiki/Search-Engines#ideas-for-search-engine-shortcuts) seems too old to use, @smblott-github .

Vimium++ is modified from Vimium and maintained by me, and because I usually visit Chinese pages, I doesn't migrate the feature "use link's names and characters". So, we may wait further changes of Vimium.

**Comment by smblott-github** [comment]
#2961 fixes this.

It'll have to wait for the next release, but the correct configuration is actually:

    cd: javascript:location='http://www.google.com/search?num=100&q=site:'+escape(location.hostname)+'+%s'

I've changed the Wiki accordingly.

**Comment by pdoak** [comment]
@smblott-github: That's great. Thank you. Do you know when the update will be available to download.

**Comment by smblott-github** [comment]
> Do you know when the update will be available to download.

I pushed a release last week, so it'll be a while.

**Comment by pdoak** [comment]
Okay. Thanks. I will look out for it. I really appreciate you making the change so quickly.

**Comment by pdoak** [comment]
Is this working yet? It doesn't work for me but maybe I am not using the correct version. My version is 1.64.2.
