### ISSUE TITLE
Can vimium open new tabs to the far right of the tab list?

### ISSUE THREAD

**Issue by iamFIREcracker** [philc/vimium#2957]
Right now the `createTab` command opens the new tab right after the currently focused one;  is there a another command I can use to add the new tab to the end of the tab list?  (pretty much like what CMD/Ctrl+t do)

Otherwise, can I maybe chain `lastTab` and `createTab` commands together?

**Comment by ris58h** [comment]
@iamFIREcracker Do you use Firefox? Take a look at https://github.com/philc/vimium/issues/2670

**Comment by iamFIREcracker** [comment]
@ris58h No, I am on Chrome.

**Comment by iamFIREcracker** [comment]
It looks like I am not the only one looking for this:

https://github.com/philc/vimium/pull/2895

**Comment by anowlcalledjosh** [comment]
fwiw, I really like the current behaviour – I can choose where the new tab goes by using <kbd>t</kbd> or <kbd>ctrl</kbd>-<kbd>t</kbd>.

**Comment by mmikeww** [comment]
can't you use Chrome's built-in `CTRL+T` to open a new tab on the far right?

**Comment by iamFIREcracker** [comment]
I can (and I am doing it already).  However, it's way simpler to use `t`, that's why I am asking for an additional command for that

**Comment by philc** [comment]
This is partially addressed with a new option to the createTab command in #2895, and will go out with the next Vimium version.

**Comment by iamFIREcracker** [comment]
Thanks @philc for the update -- any idea of when is the next Vimium version scheduled to be released?
