### ISSUE TITLE
 how to loop positioning in each picture(image)?

### ISSUE THREAD

**Issue by xmirager** [philc/vimium#2959]
chrome v65, the web page has multiple images arranged longitudinally, pictures are separated by blank lines and titles, I ask: How to set shortcut keys through vimium, loop positioning in each picture, and display it vertically in the page, thank you.

**Comment by smblott-github** [comment]
This is not something that Vimium can (or probably ever will be able to) do.

To much of what you're looking for would be custom for each individual site.
