### ISSUE TITLE
Exit insert mode while in fullscreen (Chrome)

### ISSUE THREAD

**Issue by ivangreene** [philc/vimium#2963]
Chrome version : `64.0.3282.167 (Official Build) (64-bit)`
Vimium version: `1.63`

YouTube is a perfect example of this issue:
1. Visit YouTube video
2. Press `i` to enter insert mode
3. Press `f` to enter fullscreen
4. Press Escape, expecting to leave insert mode, but fullscreen is exited (while insert mode remains active)

According to the docs, pressing Escape while in insert mode is supposed to block that keypress from registering with the webpage, but I believe Chrome may have a separate way to pick up Escape while a page is in fullscreen.

Is there any way to map another key to exit insert mode?

**Comment by innaterebel** [comment]
By default there is <kbd>Ctrl</kbd>+<kbd>[</kbd>.

> 1.13 (2010-01-21)
>- <c-[> is now equivalent to Esc, to match the behavior of VIM.

**Comment by ivangreene** [comment]
Thanks!

**Comment by jame-sparker** [comment]
This problem is now reoccurring. `c-[` exits the Youtube full-screen mode too.

**Comment by gdh1995** [comment]
`c-[` can be mapped, so `mapkey <c-]> <c-[>` will let `c-]` exit insert mode.
