### ISSUE TITLE
Rules by default do not work for IPv6 hosts

### ISSUE THREAD

**Issue by Morten242** [philc/vimium#2967]
When connected to e.g. http://[fe80::cce4:1680:e720:eacb]:8080/ when opening the small extension menu it will by default create this pattern: `https?://[fe80::cce4:1680:e720:eacb]:8080/*`

This pattern does, however, not work unless '[' and ']' is escaped (and this should be done by default).

Chrome: 65.0.3325.73
Vimium: 1.63

Thanks, great project :)

**Comment by gdh1995** [comment]
`[`] and `]` are also useful when not escaped. For example, a pattern may be `https?://video[0-9]+\.example\.com/*`.

In fact, only the character `*` is handled specially (always translated into `.*`), so I escaped `.` manually.

**Comment by smblott-github** [comment]
Fixed in #2968.
