### ISSUE TITLE
Feature Request: "gi" should highlight already existing input text

### ISSUE THREAD

**Issue by konstantinosftw** [philc/vimium#2969]
In pages that dynamically generate content, many times we use the same input field over and over again. Typing "gi" to get in the input field and then having to press also ctrl+A in order to overwrite the existing text would become faster if "gi" automatically selected the input text.

**Comment by gdh1995** [comment]
I suggest that we add an option to the command `focusInput` to implement this feature, instead of replacing the current behavior directly. Suggested option name is "select" - that will look like:
> map gi focusInput select

**Comment by smblott-github** [comment]
Or:

    map gi focusInput select=[all|start|end]

**Comment by gdh1995** [comment]
In tests, I found Chrome 64 focuses an `<input>` and selects all of its text by default, so I suggest a new enum value `"all-input"` - this means `select=all/all-input/start/end`.

Besides, Chrome 64 threw an error when I called `<input type=number>.setSelectionRange(end, end)`, so we may need to wrap new code with try-catch (`.select()` worked well).

**Comment by ris58h** [comment]
@smblott-github Will it be merged?
I would suggest to have `map gI focusInput select=all` by default.

**Comment by smblott-github** [comment]
> Will it be merged?

I don't think it's been implemented yet!

> I would suggest to have `map gI focusInput select=all` by default.

Changing the default behaviour is likely to be unnecessarily confusing to existing users (and for little benefit).

**Comment by ris58h** [comment]
Sorry, I thought that you've already implemented it in related PR.
As I see there is `gi` for `focusInput` and `gI` isn't used at all.

**Comment by philc** [comment]
IMO this idea is niche and thus isn't worth the extra complexity.

Can someone motivate the use case more, like with a specific site where using two keystrokes to focus an already-populated input box is really annoying and worth having the proposed extra option?
