### ISSUE TITLE
Close tabs on the left/right command not very useful?

### ISSUE THREAD

**Issue by av2000ii** [philc/vimium#2970]
Hello, I'v been use Vimium many years. IMO the advanced command **Close tabs on the left/right** are not very useful. I think the command are same as **Close all other tabs** in many situation. Do you think change the command to **Close tab on the left/right**(not tabs) will be more suitable for daily use. Thanks and best wishes.

**Comment by av2000ii** [comment]
Yes, it is what I mean.

**Comment by smblott-github** [comment]
You could get the existing behaviour with:

    map X closeTabsOnRight count=999

I don't like changing the established behaviour, but the proposal is indeed more vim-like.

**Comment by av2000ii** [comment]
Thanks for your explanation. 
With `count=1` + closeTabsOnRight
It works as I expected.
