### ISSUE TITLE
Feature Request:close right tab and close other tab shortcuts

### ISSUE THREAD

**Issue by awaken233** [philc/vimium#2972]

**Comment by innaterebel** [comment]
They already exist, but are unmapped by default. See all available commands by clicking the _show available commands_ on Vimium's options page.

**Comment by awaken233** [comment]
thx, bro @innaterebel

**Comment by innaterebel** [comment]
See also #2970, these commands will be modified to accept count prefix and by default close only one tab in near future (namely the next version of Vimium).
You will still be able to get the current behavior by pre-defining count prefix to a large number in the mapping, as demonstrated in #2970.
