### ISSUE TITLE
Snippets/Extended Clipboard Feature

### ISSUE THREAD

**Issue by danbush** [philc/vimium#2982]
Hello!

I have an idea for a new feature, not sure if it would be useful for enough people for this to be worth it, but figured I'd mention it just in case. The idea would be the ability to create snippets/an extended clipboard using vimium.

Example: 
* open the vomnibar and type any word that you set up in the options, just like custom search engines
* hit enter and it copies the snippet to your clipboard.

Does this make sense and/or would this be useful to others?

**Comment by smblott-github** [comment]
Thanks, @danbush.  While the idea of a snippet manager may have merit, it'd be pretty peripheral to Vimium's core functionality.  I think I'd prefer not to be dragged too far from that core.

**Comment by danbush** [comment]
Yeah that makes sense.
