### ISSUE TITLE
Is there a shortcut to go to google search textbox directly.

### ISSUE THREAD

**Issue by jadhravi** [philc/vimium#2986]
Quite a lot of times I find myself doing a google search on a term "ABCD", and then I want to search term "ABCE" instead. Is there a shortcut where I can jump to the google search bar, (not on the browser address bar, but the one available on google search result page)? I don't like to jump on the address bar because I have to type the whole term ABCE again.

**Comment by philc** [comment]
Try `gi`.

**Comment by smblott-github** [comment]
@philc... I think there's a better answer, but I don't have the time right now.  Reopening.

**Comment by smblott-github** [comment]
Ehhh.  Actually.  You're right.
