### ISSUE TITLE
Firefox 59 Issues

### ISSUE THREAD

**Issue by Stebalien** [philc/vimium#2989]
After upgrading to Firefox 59, I've noticed two issues:

1. `<c-d>` adds a bookmark instead of scrolling and `<c-u>` opens a view-source window. I can't seem to override these.
2. When `key` is bound, vimium also seems to bind `ctrl+key` (usually). I can *manually* bind `ctrl+key` to something else but this doesn't help in the case of `<c-l>` as I can't configure vimium to focus the locationbar.

Config (I've tried both enabling and disabling "Ignore keyboard layout").

```
unmapAll

map q removeTab
map u restoreTab

map j scrollDown
map k scrollUp
map h scrollLeft
map l scrollRight
map <c-d> scrollPageDown
map <c-u> scrollPageUp
map gg scrollToTop
map G scrollToBottom

map gs toggleViewSource

map r reload
map yy copyCurrentUrl

map i enterInsertMode
map v enterVisualMode
map V enterVisualLineMode

map gi focusInput

map <space> LinkHints.activateMode
map <s-space> LinkHints.activateModeToOpenInNewTab
map <c-space> LinkHints.activateModeToDownloadLink

map [[ goPrevious
map ]] goNext

map ` Marks.activateGotoMode
map m Marks.activateCreateMode

map / enterFindMode
map n performFind
map N performBackwardsFind

map H goBack
map L goForward

map u restoreTab
```

Note: Even before upgrading to Firefox 59, `<c-d>` would occasionally create a bookmark instead of scrolling unless I interacted with a page (e.g., clicked) before hitting `<c-d>`.

**Comment by Stebalien** [comment]
Note: binding `d` to scroll down appears to also bind `<c-d>`, overriding the add bookmark hotkey.

**Comment by Stebalien** [comment]
Yeah... I should have tried this in a fresh profile *before* submitting an issue (I tried disabling my other addons but apparently that wasn't sufficient). It appears to be an issue with my setup, sorry about that.

**Comment by Stebalien** [comment]
On a hunch, I disabled `privacy.resistFingerprinting` and that appears to have fixed this.

**Comment by Thorin-Oakenpants** [comment]
The ctrl key modifier events suppression (part of [1222285](https://bugzilla.mozilla.org/show_bug.cgi?id=1222285) ) was finally landed with FF59.0.2 (it would have been in 59 but got backed out at the last minute) - see [1433592](https://bugzilla.mozilla.org/show_bug.cgi?id=1433592)

When you have updated FF, you should be able to flip privacy.resistFingerprinting back on
