### ISSUE TITLE
QUESTION: Vimium dialogs not getting focus?

### ISSUE THREAD

**Issue by serussell** [philc/vimium#3001]
Since yesterday, Vimium dialogs (O, ?, ge, etc) are not getting focus and can't be focused, rendering them unusable.  Is it a known issue that sometimes happens that can be corrected?  I _suspect_ it's because of a Vivaldi upgrade (from 1.15.xxx.y to 1.15.1137.3).

Example behaviors:

* Press O to navigate; Vimium Open dialog box displays.  Start typing; text does not appear in the Open dialog, but rather executes Vimium commands directly on the underlying web page. E.g., if I try to type the sequence "Ofocus" I get the dialog, then link navigation on the page, then the link tagged with "o" and so on.

* Press ? to get help.  Vimium help dialog opens.  Press down to scroll; the background page scrolls.  Try to grab the help scroll bar; the help dialog dismisses.
* Press ? to get help.  Vimium help dialog opens.  Use mouse to click on "Options" -- help dialog dismisses.

It acts as if the event handling priority is wrong, like the dialogs are always in the input event handling queue behind the page.

vimimum 1.6.3 & vivaldi 1.15.1137.3

**Comment by gdh1995** [comment]
Firstly, this case has been reproduced on my PC.

It seems that your Vivaldi is a "snapshot" version, which means it may be not so stable as official release ones.

As far as I know, Vivaldi indeed has some bugs about the flag `#enable-site-per-process` (please see more in #2911 ), so you may have to wait for further fixes of the official Vivaldi.

**Comment by serussell** [comment]
This is correct, and as I suspected it's not a vimium issue.  Closing.

**Comment by serussell** [comment]
Follow-up: One of the recent snapshot upgrades fixed this, and re-broke "yank" at the same time.  Which was during the time that focus was not, so go figure.
