### ISSUE TITLE
Allow any key to mapped to "exit mode" instead of just <esc>

### ISSUE THREAD

**Issue by sture** [philc/vimium#301]
I have jj remapped to \<Esc\> in vim since its easier to type. Would it be possible to make a remapping such as this work to leave insert mode?

Thanks

**Comment by tecfu** [comment]
+1

**Comment by ewilazarus** [comment]
+1

**Comment by y2kbugger** [comment]
👎

**Comment by danijar** [comment]
Hi @smblott-github, just curious why this was labeled `won't-fix`? I started using insert mode more frequently with Vimium (rather than disabling the plugin for certain pages), but it would be nice if people could exit using their preferred binding, in my case `<C-c>`.

**Comment by smblott-github** [comment]
Reopening and removing *wont-fix* label.

This is indeed a feature that is requested *a lot*.  It was closed as part of a cull of long-standing open issues.

**Comment by smblott-github** [comment]
Folks, see #2253.

**Comment by danijar** [comment]
Thanks a lot, your efforts are appreciated!

**Comment by smblott-github** [comment]
Folks, see [here](https://github.com/philc/vimium/pull/2253#issuecomment-249100853).  PR #2253 has hit a little bit of a road bump.  Input would be appreciated.

**Comment by smblott-github** [comment]
Closing, see [this comment](https://github.com/philc/vimium/pull/2253#issuecomment-250969019).
