### ISSUE TITLE
VisitPreviousTab with ctrl+tab doesnt work

### ISSUE THREAD

**Issue by tobbbe** [philc/vimium#3012]
`map <c-tab> visitPreviousTab`

Doesnt work in chrome. Am I missing someting?

Thanks for an awesome plugin!

**Comment by smblott-github** [comment]
Looks like Chrome just isn't even giving Vimium the event.  It's using its own binding regardless.  (Which means that there is probably nothing we can do.)

**Comment by tobbbe** [comment]
Okey!
