### ISSUE TITLE
^ go to previously visited tab not working

### ISSUE THREAD

**Issue by orschiro** [philc/vimium#3019]
I may be doing something wrong. 

1. Opened two tabs
2. Switch from one tab to the other
3. Pressed `^` one time, two times, three times but it's not switching back

Can someone please clarify?

Thank you!

**Comment by smblott-github** [comment]
Is there anything unusual about your keyboard or your keyboard setup?

(Nothing has changed with `^` for quite some time.)

**Comment by orschiro** [comment]
Thanks for your help!

> What does the one, two ,three times part mean?

Just how often I press the ^ key.

> What is your OS and browser?

Fedora 28 and Chrome 66.

> What are the two tabs' URL?

Two times https://github.com/philc/vimium/issues/3019#issuecomment-386454651

> Is there anything unusual about your keyboard or your keyboard setup?

Not really. It's set to German and is a German keyboard. If I press ^ once, it produces nothing. If I press it twice, it produces ^.

**Comment by smblott-github** [comment]
> If I press ^ once, it produces nothing. If I press it twice, it produces ^.

Well, I've no idea what that means or why, but I'd say that's the source of the problem.

Try:

    map X visitPreviousTab

for some other (simple) key `X`.

**Comment by orschiro** [comment]
That's the solution. Thanks! Let's close as user error.

**Comment by fabrei** [comment]
it is already closed, but it seems to be a workaround and not a solution?! have you tried to press `g^` ?

`g^` as well as only `^` are working for me in firefox 60.7.2 esr..

**Comment by fabrei** [comment]
hm, but in a firefox quantum 68.0.1 `^` does not work. neither `g^`..it is also a german keyboard layout..the key mapping works like a charm.
