### ISSUE TITLE
j and k srolling do not work with the "new" reddit layout.

### ISSUE THREAD

**Issue by Noexpert** [philc/vimium#3025]
When you click on a story and the "pop-under" shows, you can't scroll.
Thanks

**Comment by ris58h** [comment]
@Noexpert Could you provide steps to reproduce? What is "pop-under"?
I've tried to reproduce this on [random reddit page](https://www.reddit.com/r/IAmA/comments/8i7e7f/im_chuck_tingle_two_time_hugo_award_finalist_and/) and everything works fine.

**Comment by Noexpert** [comment]
Hi,

you can only replicate on the newly redesigned pages.
Some users are opted in automatically, but others may need to do so manually.

Take a look at the top image here: https://imgur.com/a/mcH7tjD
Using j and k scrolls the background, not the foreground post.

Thanks

**Comment by matthewmichihara** [comment]
Scrolling with the up/down arrow keys also don't seem to work, so I'm hoping reddit just fixes this soon.

**Comment by DougBeney** [comment]
Hello,
I have reproduced reddit's behaviour [in this Codepen](https://codepen.io/DougBeney/full/VdemLd/).
You could tweak around with its source [here](https://codepen.io/DougBeney/pen/VdemLd)

**Comment by progandy** [comment]
Maybe add a way to set the scroll focus to a specific element?
Then automatically set the scroll focus to a new popup if it covers a rectangle in the center of the screen?

**Comment by marcotc** [comment]
Just an update on this:
> Scrolling with the up/down arrow keys also don't seem to work, so I'm hoping reddit just fixes this soon.

Up and down arrows now do scroll the main popup content properly, while j and k scroll the background.

**Comment by smblott-github** [comment]
Could somebody better explain exactly what the problem is here?

How does one enable the "new" Reddit layout.  Then, what do I do to observe this problem?  I've seen the screenshot, above, but didn't learn anything from it.  I've also seen the codepen demo.  That makes sense, I just need to find where that behaviour happens on Reddit.

**Comment by marcotc** [comment]
I have a PR with a proposed solution in the works: https://github.com/philc/vimium/pull/3119

**Comment by marcotc** [comment]
This issue has now been resolved, with #3119 being merged.
