### ISSUE TITLE
scroll keys don't work on bugzilla

### ISSUE THREAD

**Issue by lilydjwg** [philc/vimium#3026]
* open a bug page like this one: https://bugzilla.mozilla.org/show_bug.cgi?id=1401091
* try scroll either by lines / pages, or scroll to top / bottom
* it only scrolls somewhat like 1px on a keystroke

Firefox 61.0a on Arch Linux with latest Vimium release.

**Comment by smblott-github** [comment]
Moreover, after a "Vimium tap", the page scrolls by just one pixel at a time.

**Comment by gdh1995** [comment]
Hello, I think this issue has been fixed by #3111 .

**Comment by lilydjwg** [comment]
Yes this has been fixed, thanks!
