### ISSUE TITLE
Custom search engine is reset

### ISSUE THREAD

**Issue by gitschneider** [philc/vimium#3033]
Every now and then (probably after an update, but I could not determine a specific interval) my setting for a custom search engine is reset back to Google.
It would be great, if the `Default search engine` setting was saved permanently.

##### Versions
Vimium: 1.63.3
Firefox: 61.0b6 (64-bit)

**Comment by smblott-github** [comment]
That sounds unlikely to be a Vimium issue.  Vimium stores the user's settings in `localStorage` and in `chrome.storage.sync`.  If Firefox reset one of those for some reason (no idea what it could be), then the setting would be reset.

(The Vimium code for settings in general and this setting in particular has not changed for a long time, and seems to be working fine.)

Perhaps other users will be able to shed some light on what is happening.

**Comment by gitschneider** [comment]
This is useful information, and the error seems to be clearly on my side. Thank you for your help!
