### ISSUE TITLE
Feature request: Normal mode by default in input boxes (with highlighting)

### ISSUE THREAD

**Issue by sandeep-datta** [philc/vimium#3037]
Please use normal mode by default for input boxes and add a border around them to highlight the currently selected input box. Pressing i should clear the contents of the input box and place you in insert mode and pressing a should put you in append mode.

**Comment by smblott-github** [comment]
> ... add a border around them to highlight the currently selected input box

This happens already.  It's blue.

> Please use normal mode by default for input boxes

I'm not sure why that would be better.  However, regardless, it would be a *very* substantial change to the existing behaviour, and that means it is unlikely to happen (without a *very good* reason).

**Comment by sandeep-datta** [comment]
> I'm not sure why that would be better.

Right now moving focus to an input box places you at the end of the buffer and you have to use backspace to delete the previous content. 

Here's what I would have liked to see...
1. Change focus to input box (now we are in normal mode but the box is highlighted)
2a. Press 'i' clear contents of the box and enter insert mode
2b. Press 'a' move cursor to the end of the buffer and enter insert mode.

So starting with the normal mode we get the ability to choose how we want to deal with any preexisting text in the input box.

**Comment by sandeep-datta** [comment]
The blue boundary does not seem to work with google.com.

**Comment by sandeep-datta** [comment]
## One possible alternative
Select all text in the input box as soon as it is selected. Doing this will let the user replace the entire content with little effort and if the user just wants to append to the existing text they can use the right arrow key to de-select the selected text (effectively putting them in append mode).

**Comment by smblott-github** [comment]
> Select all text in the input box as soon as it is selected.

This has the side effect of losing the current cursor position if there is one.

Since `<c-a>` is available to select all text (and easy to type), I'm not convinced there is a case for changing the status quo.

The original proposal above would be something new for existing users to learn, and would be a substantial barrier to entry for new users.  Check out the Vimium [design goals](https://github.com/philc/vimium/blob/master/CONTRIBUTING.md#vimium-design-goals).

**Comment by sandeep-datta** [comment]
> <c-a> is available to select all text

This works for me. Thanks!
