### ISSUE TITLE
Vimium seems to work only randomly or not at all in recent Firefox nightly

### ISSUE THREAD

**Issue by jasontibbitts** [philc/vimium#3039]
I didn't see this reported and figured that someone would want to know even though I figure random issues with a nightly build probably don't carry much weight.

In any case, I have found that for the past day or so, vimium (1.63.3 installed from the "Vimium-FF" entry on the Firefox addons page) has been working only sporadically for me.  Sometimes it works, sometimes it doesn't.  It can work for one tab and not the next one.  Page complexity doesn't seem to matter; I just stuck "foo" in a file and loaded it; vimium there worked initially (I changed tabs with J and K, closed the tab with x and then re-opened it, and reloaded a few times.)  After a number of reloads, however, vimium just stopped working on the page, and further reloads didn't seem to make it appear.  Opening a new tab and entering the same URL also resulted in a tab with non-working vimium.  I closed the browser session, restarted it, entered that page with "foo" on it again, and was able to reload once using 'r' (which means vimium was working at that point).  After that reload, vimium was nonfunctional on the page.

In the Firefox dev tools, I see the event listeners present on the master <html> element, even on pages which don't work.  I don't see any obvious differences in the listeners between a page that works and one that doesn't.

I did fire up a completely clean profile to test this.  The nightly version today is calling itself 62.0a1 (2018-06-08).

Edit: to see if it was some major Firefox bug with event listeners, I removed vimium, restarted and installed saka-key.  It does *not* appear to have the same issue.  And of course the built-in firefox hotkeys for things like Ctrl-r and Ctrl-w always work even when vimium isn't working.

**Comment by SimonAB** [comment]
Seeing the same sporadic breakage in FFN 62. Wondered initially if it was caused by the new side view test pilot, but apparently not.

**Comment by t-hart** [comment]
Yup, I'm seeing the same issues. 
Using the dev tools to break on exceptions it seems that `obj` is undefined in the  `monitorChromeStorage` function in utils.js, and it also breaks in `add.js`, wherein the `q` variable of the `browser.storage.local.get` callback is undefined. Sometimes it hits both those exceptions, sometimes only one of them. What the root cause is, I don't know, however, and, as was mentioned, breakages in nightly versions shouldn't be surprising or the cause of a lot of worries. It might be resolved tomorrow, after all.

**Comment by smblott-github** [comment]
That's actually quite encouraging, @t-hart.  The storage API is pretty fundamental, so I'd be pretty confident that it'll sort itself out.

**Comment by t-hart** [comment]
Also worth noting that I had an update waiting, which I just installed, and now I can't seem to reproduce the issue anymore, so unless I've just been very lucky with my recent tabs, I think it's already resolved.

**Comment by SimonAB** [comment]
I can tentatively confirm that the latest FF nightly seems to have solved this issue...
