### ISSUE TITLE
Twitter pop up tweet frame not recognized

### ISSUE THREAD

**Issue by elig0n** [philc/vimium#3045]
Hi, when I try to scroll a pop up tweet it scrolls the page underneath it. 'gf' doesn't help to get inside that frame. I'm using Firefox Quantum 60.0.2 64bit and Vimium version 1.63.3

**Comment by gdh1995** [comment]
It's not a `<iframe>` but a `<div>` so `gf` doesn't help in this case.

You just need to click the popup box or a button in the box before scrolling it.

**Comment by smblott-github** [comment]
Twitter is very popular (of course), and the current behaviour is very bad.

I wonder if we might consider adding this as a special case?  Specifically, if a tweet "frame" is visible, the scroller should select element for scrolling.

Generally, we avoid site-specific code.  The only exception, I think, is some Vomnibar code which tidies up Google URLs.  Might we make an exception here too?

**Comment by gdh1995** [comment]
LinkHints has added a hint for the "frame", and after clicking it I can scroll the conversations. So it might be not so annoying that we have to add any ugly code:

![image](https://user-images.githubusercontent.com/5547703/44516600-1b9a5700-a6f8-11e8-9319-9ccdf34bcfae.png)

**Comment by smblott-github** [comment]
> LinkHints has added a hint for the "frame", and after clicking it I can scroll the conversations.

Yes.  I tried that too.  For me, it seemed to work sometimes, but not always.  I didn't investigate further.

However, whatever happens, the scroller's `activatedElement` needs to be set correctly.

This very-quick hack works (near the bottom of `scroller.coffee`):

```Coffeescript
# Hack to make expanded tweets scrollable on Twitter.
if DomUtils.isTopFrame() and window.location.host == "twitter.com"
  for method in ["scrollTo", "scrollBy"]
    do ->
      func = Scroller[method]
      Scroller[method] = ->
        element = document.querySelector "#permalink-overlay-body div.permalink-container div[role=main]"
        activatedElement = element ? getScrollingElement()
        func arguments...
```

We'd lose any existing `activatedElement`, but that seems like a small loss in comparison to the big win in terms of usability.

**Comment by gdh1995** [comment]
Um, it indeed works.
