### ISSUE TITLE
Shortcut to toggle filtered/regular hints

### ISSUE THREAD

**Issue by devenv** [philc/vimium#3046]
On technical pages, like spark jobs list filtered hints are useless (e.g. lots of links starting with `application-`).
What I thought might be a solution is a shortcut to temporary switch to regular hints, e.g. `f, Shift-Space`; or an additional hint key, e.g. `gf`.
I think it would be useful to a good chunk of vimium users :)

**Comment by smblott-github** [comment]
`Shift-Space` is already used (for rotating stacks of overlapping hints).

You can use letter characters with filtered hints too (e.g. the home row), then you just need to hold shift while typing hint characters.  That's slightly inconvenient, but is it worse than having to remember (and think to use) a different binding?

Otherwise, we could, I guess, add a new command option.  But I'm not sure whether the demand is/would be high enough.

**Comment by devenv** [comment]
Actually, holding shift is more than good enough for me :)
I couldn't find this in documentation or here in issues though...

**Comment by TroyFletcher** [comment]
If this request is for a hotkey to toggle "use the link's name and characters for link-hint filtering" option, then I support it. Some pages are more amenable to link name filtering than others. A shortcut to toggle this would be convenient.

That said, your workaround using capital letters in the link hints helps a lot.

What would the map command be for toggling an extension option?

**Comment by Madd0g** [comment]
Is there a secret special command that allows to trigger the alternate style of hints? i.e. I'm usually on random letters mode, but can push a different shortcut to type the link text. I would really like that for some difficult pages.

Also I did not really understand the advice about shift, I tried both modes and holding down shift (while typing the letters) didn't do anything different. Maybe I'm doing it wrong?

**Comment by TroyFletcher** [comment]
> Also I did not really understand the advice about shift, I tried both modes and holding down shift (while typing the letters) didn't do anything different. Maybe I'm doing it wrong?

The shift + space is for toggling the popup display of shortcuts when they overlap. Consider 3 links very close together. Pressing F (to pay respects) pops up letters for the shortcuts for these 3 links, but they're so close together they draw over the other shortcuts. Shift + Space rotates the order so you can see the ones that might be covered by other shortcuts.

**Comment by Madd0g** [comment]
@TroyFletcher - I meant this sentence:

>You can use letter characters with filtered hints too (e.g. the home row), then you just need to hold shift while typing hint characters.
