### ISSUE TITLE
Make switching tabs (`ngt`) like in VIM

### ISSUE THREAD

**Issue by alphaCTzo7G** [philc/vimium#3047]
in vim `1gt` goes to the 1st tab, `2gt` goes to the second tab and so forth. However, in `vimium`, `1gt` goes to the next tab and `2gt` goes to the 2nd tab to the right..

Can this be made more `vim` like, so that `ngt` goes to the `nth` tab?

**Comment by smblott-github** [comment]
I think `g0` is what you're looking for.

`1g0` goes to the first tab, `2g0` the second, and so on.

**Comment by alphaCTzo7G** [comment]
Ahh.. ok.. thanks for the information.. in future.. if possible.. it would be great if maybe we can use `1gt` instead of `1g0` to go to the first tab.. That would make it more similar to `vim` and we won't have to remember another set of key combinations.

**Comment by smblott-github** [comment]
We're unlikely to change the default; it would be too disruptive for existing users.

But...

    map gt firstTab

should get you the behaviour you want.
