### ISSUE TITLE
Is there a way to pay for Vimium? e.g. a Patreon?

### ISSUE THREAD

**Issue by rbalicki2** [philc/vimium#3048]
Is there any way to pay to support Vimium? I rely on this extremely heavily, and would love to not free-ride, now that I'm a functioning adult.

Otherwise, thanks for the labor of love!

**Comment by smblott-github** [comment]
Thanks for your interest.  Pay it forward!

**Comment by rbalicki2** [comment]
Will do! Thanks for the great software
