### ISSUE TITLE
Inputs are dropped during slow hint generation

### ISSUE THREAD

**Issue by ferreum** [philc/vimium#3050]
When pressing `f` to follow a link, the generation can take a moment on complex pages (easy to reproduce on `youtube.com`).

I use numbers as hints and type the link text to narrow them down, so I know what to type even before I see the hint. But, because inputs are dropped while the hints are generating, I have to wait even though I don't need to see the hints. This considerably reduces the responsiveness of the keyboard-driven browsing experience.

For example:
- open `youtube.com`
- press `f` to enter hint mode, directly followed by `d` before hints appear
- When the hints appear, the input is still empty. the `d` input has been dropped. Only the following keypresses are registered.

Browser: Firefox 60.0.2, same where I started using Vimium at version 56
OS: Arch Linux
Vimium version: 1.63.3

**Comment by smblott-github** [comment]
This is a good point.  We should cache keystrokes arriving which hints are being generated.
