### ISSUE TITLE
Close vomnibar when not focused

### ISSUE THREAD

**Issue by Troyciv** [philc/vimium#3054]
When I open the vomnibar with `o` and (by accident) loose focus of it (e.g. trying to click a link) I cannot close the vomnibar with `ESC`. I always have to click inside the vomnibar and then press `ESC`

Is there a way to change that?

**Comment by ris58h** [comment]
@Troyciv I didn't dig deep into it, but found a temporary solution: just use `tab` to focus Vombinar's input back. After that you can close it with `Esc`.

**Comment by innaterebel** [comment]
I found Vimium on Chrome already does the title? What's your system information?

**Comment by ris58h** [comment]
@innaterebel just middle click under Vomnibar to lose focus. I've fixed this in https://github.com/philc/vimium/pull/3057

**Comment by Troyciv** [comment]
@ris58h Thank you, `tab` is a working solution for now. How ever I'd still prefer automatic close when loose focus, or something similar.

**Comment by smblott-github** [comment]
This should be fixed with #3057.
