### ISSUE TITLE
In find mode (dot) should match all character except new line.

### ISSUE THREAD

**Issue by farhanmustar** [philc/vimium#3058]

**Comment by ris58h** [comment]
@farhanmustar Could you provide an example?

**Comment by jmg87** [comment]
I does for me. You have to enable the option "treat search as Javascript regular expressions", then dot matches a single character, [ ] matches sets of characters, etc. Isn't that what you want?

**Comment by farhanmustar** [comment]
Ya that is exactly what I want @jmg87 . But did you mean by adding '\r'. Is there any way to set it as default.

**Comment by jmg87** [comment]
If you select " Treat find queries as JavaScript regular expressions " the default when searching will be that. No need to go back to the other mode with '\r' if you don't want to. I only use that one.

**Comment by farhanmustar** [comment]
Thank you @jmg87. The solution is to enable "Treat find queries as JavaScript regular expressions" under Advance options as guided by jmg87. I will close the issue.
