### ISSUE TITLE
Add a command which is the same as clicking the Home button

### ISSUE THREAD

**Issue by has207** [philc/vimium#306]
It would be good to have a key to go the homepage (equivalent of hitting the Home button) or just a generic way of navigating bookmarks

**Comment by jdpopkin** [comment]
Chrome doesn't expose a user's homepage to extensions: http://stackoverflow.com/questions/27979202/chrome-extension-how-can-i-get-global-settings-in-preference

I'm not sure if there are any good workarounds for this problem.

**Comment by smblott-github** [comment]
Closing.
Not clear what if anything needs to be done.
