### ISSUE TITLE
Use semantic link hints

### ISSUE THREAD

**Issue by yanex** [philc/vimium#3064]
Currently, the link hint names are generated automatically based on the input character set and have nothing to do with the link text. In the attached screenshot the link to Vimium is named H.
I'd like it to be named "V" as it makes much more sense.
So the proposal is to tag at least some of (topmost?) links with its name.

<img width="393" alt="screen shot 2018-07-10 at 14 21 17" src="https://user-images.githubusercontent.com/95996/42507157-d0301eb2-844c-11e8-9055-8d68d7fe6885.png">

**Comment by innaterebel** [comment]
Implemented feature. There is an `Use the link's name and numbers for link-hint filtering` option under the `Advanced` section of Vimium options.

**Comment by yanex** [comment]
"Use the link's name and numbers for link-hint filtering" actually makes things even worse as it limits the allowed key set to [0-9].

<img width="846" alt="screen shot 2018-07-12 at 16 15 14" src="https://user-images.githubusercontent.com/95996/42635489-de1a599a-85ee-11e8-926f-483330e8d0d4.png">

**Comment by philc** [comment]
You do not need to type just the numbers -- you can also type the name of the hint. So if you typed "fo" in the linux.org screenshot you sent, you would navigate to the Forums link.
