### ISSUE TITLE
How to open multiple links to multiple tabs? 

### ISSUE THREAD

**Issue by tony-haibo-zhu** [philc/vimium#3065]
I found the <a-f> on the help page, but not any effect. So am i  use with wrong way? What the right way? Thank you.

**Comment by urielha** [comment]
Have you tried using `alt` + `f` ?
This should do

**Comment by innaterebel** [comment]
Or type the number of links you want to open before pressing <kbd>F</kbd>.
(say you want to open twelve links, then <kbd>1</kbd><kbd>2</kbd><kbd>F</kbd>)

**Comment by tony-haibo-zhu** [comment]
@innaterebel Thanks a lot. I will close this issue.
