### ISSUE TITLE
Feature Request: Expand Custom Search Engine Mappings for URL Navigation in Vomnibar

### ISSUE THREAD

**Issue by xoihiox** [philc/vimium#3066]
I am unsure if I am overlooking a way this can be done, but right now if I want to, say, translate english-to-japanese on Google Translate, I open the vomnibar and type: e2j + [space] + [translation query] + [enter].

Is it possible to similarly navigate to a desired webpage using keywords in the vomnibar?  For example, mapping Google Translate (translate.google.com) to gt + [space] + [enter], OR gt + [enter].

**Comment by smblott-github** [comment]
If you create a bookmark with the text "gt" as a standalone word in the title, then use `b` or `B`, then Vimium will likely find your page with `b + gt + [enter]`.  Vimium's scoring/ranking algorithm gives whole-word matches quite a high score.

Or, for sites you use frequently, I'd suggest a global mark...

Create mark... visit your site then "mT".

Use mark... "`T".

**Comment by xoihiox** [comment]
Thanks for the reply @smblott-github.  I had not been in the habit of opening bookmarks with anything other than vomnibar.open, but after reading your reply and seeing a similar discussion a couple of years ago where you said you use this method to open bookmarks by keyword, I gave it a try and it basically works as I'd hoped.

Feel free to close.
