### ISSUE TITLE
Change from f key???

### ISSUE THREAD

**Issue by woodgerb** [philc/vimium#3067]
Hello, 

I have many programs that use the f key, so I am wondering if I can set it to another key to open vimium. If so, how?

Thank you!

Ben

**Comment by innaterebel** [comment]
https://github.com/philc/vimium#custom-key-mappings

So,
map <kbd>the key you want here</kbd> LinkHints.activateMode

You may also want to remap other commands of link hint modes as every command is registered separately.
Hence if you have remapped only `LinkHints.activateMode`, other commands of link hint (e.g. `LinkHints.activateModeToOpenInNewTab`, `LinkHints.activateModeWithQueue`, etc.) will stay as combinations of <kbd>f</kbd> key, which may or may not still be a problem for you.
