### ISSUE TITLE
Frustrating IME leftover issue when press ESC in input

### ISSUE THREAD

**Issue by fangli** [philc/vimium#3068]
Hi there, I got an annoying issue when using this fancy plugin. After searched the whole internet, finally I realized that this issue was caused by vimium.

And here, I would like to re-explain the previous issue again: https://github.com/philc/vimium/issues/2768 , with more details.

OS: OS X 10.12
Chrome: Latest and most recent versions
IME: System built-in Chinese Pinyin (Simplified)
Details:

When we need to input some Chinese or Japanese words in form, we need to use corresponding IME, like Chinese Pingyin Input Method.

Usually, when we type a whole Chinese sentence, we key in many alphabet words, then they are converted to Chinese and show in the on-the-fly area of IME, then, after we press blank space,  the Chinese chars will be sent to input box.
Easy and simple, aha? Key in alphabet words, IME convert them to Chinese chars, press blankspace, IME send the buffered Chinese to input box. just as follow:

![ezgif-4-5a9f6be5d5](https://user-images.githubusercontent.com/3032639/42815346-b49b3b52-89f9-11e8-861f-03c7cd670f3a.gif)

(Please note that before Chinese were sent to inputbox, I pressed blank space)

If we want to give up(discard) the current buffered text(usually them are long), we just need to press ESC instead of blankspace, as follow:

![ezgif-4-b6c7788434](https://user-images.githubusercontent.com/3032639/42815652-9369315e-89fa-11e8-8a52-2693a1c9450f.gif)

Did you see that? when I want to discard whole buffered words, I just need to press ESC.

This is the good and normal behavior by default.

BUT, when I have vimium installed in Chrome, if I discard the buffered words by pressing ESC, the following annoying thing happened:

![ezgif-4-035edda4c6](https://user-images.githubusercontent.com/3032639/42816095-3a3476aa-89fc-11e8-8b1f-0ccdbf7ff25a.gif)

Did you see that? when I press ESC to discard the buffered text, the original alphabet was left over in the inputbox, which should be cleared or discarded. This is super annoying and frustrating when composing an email or something else, coz we need to use mouse to select those leftovers then delete, or delete them one by one.
------------

I hope I described the problem clearly, it took me 50 minutes to make GIFs and reproduce this issue. but since I'm a 6+ years vimium user, I don't think 50m is a waste of time.

More than that, then I writing this issue, I found another forked plugin which resolved this bug perfectly:
https://chrome.google.com/webstore/detail/vimium%2B%2B/hfjbmagddngcpeloejdejnfgbamkjaeg

Here is the screenshot when using vimium++:

![ezgif-4-1806c329a6](https://user-images.githubusercontent.com/3032639/42816723-548671dc-89fe-11e8-84f7-d0233289c6b6.gif)

But again, I'm still a vimium user and want to make it better, hope this helps.
Please take a look at this issue, thank you guys so much.

**Comment by innaterebel** [comment]
Vimium++ is actually forked by a Chinese contributor based in mainland China, and hence has many issues under Chinese condition resolved energetically.
With the fact that the development of Vimium is pretty much in halt currently (the main contributor has not been online for weeks), and this issue being OSX specific adds to the difficulty of debugging, I would really like to suggest you just go ahead and use Vimium++ in the meantime. Or SurfingKeys, also made by a Chinese developer.

**Comment by smblott-github** [comment]
What would be the solution to this?  Vimium exits insert mode on double `<Esc>`?

**Comment by fangli** [comment]
I don’t think vimium will enter insert mode by clicking input box. Vimium enters insert mode by pressing “I”.

So that’s two different scenarios.

**Comment by smblott-github** [comment]
Internally, when an input is focused, we call that insert mode too.

**Comment by fangli** [comment]
I see:)
I have done some experiments today and I found this issue was bring in at 1.60.

Actually 1.59(a527d355) was a good version, but 1.60(468faa28) was bad.

I'll help do more test and find out which commit exactly caused this issue.

**Comment by fangli** [comment]
Will keep you updated soon. here's the screenshot comparison between those two versions.

![ezgif-4-78aa78d2f5](https://user-images.githubusercontent.com/3032639/43962633-cf3fdb30-9cea-11e8-9b8f-b21123f160c1.gif)

**Comment by fangli** [comment]
Hi @smblott-github  I found commit d03845e3 brought the bug.
Screenshots:
![image](https://user-images.githubusercontent.com/3032639/43963615-646702fe-9ced-11e8-9d82-90e7f8a6c18c.png)
