### ISSUE TITLE
Wrong document for `f` and `F`

### ISSUE THREAD

**Issue by zhaoyao91** [philc/vimium#3070]
By reading the help:

![image](https://user-images.githubusercontent.com/3808838/43161115-c266abf2-8fb9-11e8-8166-0ae3c18c291d.png)

`f` is for opening link in current tab and `F` is for opening link in new tab.

But by using the latest version of vimium, I found their functions are reversed, `f` will open a new tab but `T` just open link in current tab.

**Comment by innaterebel** [comment]
Holding down <kbd>Shift</kbd> or <kbd>Ctrl</kbd> while typing the hint flips the opening mode you initiated. This is indicated in the HUD (located at bottom right of viewport).

If you initiate Link Hints by `f`, which meant to open in the current tab, holding <kbd>Shift</kbd> while typing the last letter of a hint will change it to be opened in a new tab.
If you initiate Link Hints by `F`, which meant to open in a new tab, holding <kbd>Shift</kbd> while typing the last letter of a hint will change it to be opened in the current tab.

Holding <kbd>Ctrl</kbd> while typing the last letter of a hint, on the other hand, shifts the mode to open a link in a new _foreground_ tab.

**Comment by alphaCTzo7G** [comment]
For me `f` and `F` work as in the documentation.. I just follow @innaterebel mentioned..
