### ISSUE TITLE
Brave browser support request

### ISSUE THREAD

**Issue by dlewand691** [philc/vimium#3071]
Would like to request support for the Brave browser. It's a great, fast browser and would love to have Vimium part of it. Thank you!

**Comment by snapfractalpop** [comment]
I concur!

**Comment by Beasta** [comment]
this can be closed. support exists. just download it from the chrome webstore in the current version of brave

**Comment by limakzi** [comment]
@philc You can close it.

**Comment by philc** [comment]
Thanks @limakzi
