### ISSUE TITLE
Small nitpick about location of certain shortcut options

### ISSUE THREAD

**Issue by alphaCTzo7G** [philc/vimium#3072]
It may help to place the `Copy the current URL to the clipboard` and `Copy a link URL to the clipboard` one after the other. This helps when you are looking for specific shortcuts and want to quickly scan through a list of options.

![chrome_2018-07-28_16-46-39](https://user-images.githubusercontent.com/29691914/43361545-112d3fb6-9286-11e8-89e7-bd8fa4e41681.png)

I personally would find this useful. If you you guys think that would be ok, I can do a PR and correct this in all the locations necessary..

What do you think?

**Comment by smblott-github** [comment]
I see your point.

However, `yf` is grouped with the other link-hints commands, so moving it would break that logical grouping.

**Comment by alphaCTzo7G** [comment]
Ok.. I see.. In that case.. its good to keep it at where its currently located.
