### ISSUE TITLE
Wikipedia and Github Issue preview popups remain open after using LinkHints.activateModeToOpenInNewTab

### ISSUE THREAD

**Issue by rnmhdn** [philc/vimium#3073]
when I use f to click on a Wikipedia link(within the text) and then I open it in a new tab using shift and the corresponding letter for that link. the preview is opened and I can't close it unless I click on the page with my mouse. Please fix that so the preview won't open when one opens a link in a new tab.

**Comment by smblott-github** [comment]
I can generate the same effect in Chrome.

The problem seems to be that we're generating a `mouseover` event, but not the corresponding `mouseout` event, [here](https://github.com/philc/vimium/blob/master/lib/dom_utils.coffee#L250).  Adding the `mouseout` event seems to fix the problem for me.

Might there be any unintended consequences if we add that event to the list?

**Comment by aranmohyeddin** [comment]
I can't really think of any unintended consequences.

**Comment by gdh1995** [comment]
Maybe we can add a keydown handler to grab the next `Esc` to dispatch `mouseout` to the last clicked, when LinkHints clicks someone and exits. All other keys the handler receives should exit the handler itself and continue to broadcast.

**Comment by smblott-github** [comment]
> Maybe we can add a keydown handler to grab the next `Esc`...

Yes.

**Comment by aranmohyeddin** [comment]
no news? :D

**Comment by BachoSeven** [comment]
Would the recently added Hover and Focus mouse events help with this, at least to be able to move away the focus using another keyboard shortcut? (see changelog for 1.66)

**Comment by gdh1995** [comment]
In Vimium, `action=hover` applies `hover` and `unhover` on an <kbd>Escape</kbd> key, but a normal `f` command (`LinkHints.activateMode`) won't dispatch unhover (`mouseout`) events.

I have made a customized version of Vimium, named Vimium C, and it supports `map f LinkHints.activateModeWithQueue autoUnhover` to auto dispatch `mouseout` events. If you don't like to "unhover at once", you may press <kbd>Escape</kbd> (even without `action=hover`), or map a key to `LinkHints.unhoverLast` and then trigger the command manually.

**Comment by ropery** [comment]
So y'all don't use `F` on Wikipedia or what? The preview pops up and stays there... Really there need not any hover to begin with (?).

(Sorry if the tone feels snarky &c. Nothing wrong with being blunt. Just asking a question...)

**Comment by philc** [comment]
@ropery I'm confirming that it's super annoying. I haven't looked into the ramifications of your suggestion, but on the surface it seems reasonable to me.

**Comment by gdh1995** [comment]
> so that menus that disappear on mouseout will work with link hints?

Yes some webpages use popup card to show secondary menus and buttons, so `unhovering` should be optional.
