### ISSUE TITLE
Is it possible to edit text in URL?

### ISSUE THREAD

**Issue by dilipm** [philc/vimium#3076]

**Comment by ris58h** [comment]
If you want to open the Vomnibar with the current URL there are `Vomnibar.activateEditUrl` and `Vomnibar.activateEditUrlInNewTab` commands. Default keybindings for them are `ge` and `gE`.
You can use CTRL+L if you want to focus browser's address bar.

**Comment by dilipm** [comment]
That's very useful...thanks..

Q: once we are in address bar with CTRL + L, how do we escape out of it (like to main frame?) :)

**Comment by ris58h** [comment]
You could google it. `F6` should work on most browsers.

**Comment by dilipm** [comment]
:+1: worked
