### ISSUE TITLE
sometime character marks do not appear on the right spot.

### ISSUE THREAD

**Issue by aranmohyeddin** [philc/vimium#3080]
In Wikipedia pages for comparison of things([example](https://en.wikipedia.org/wiki/Comparison_of_Linux_distributions)) There is this small button for sorting the table by the value of a specific column. the mark for clicking that button appears on the top left corner of the header cell. which is not good.
I'm on firefox.

**Comment by smblott-github** [comment]
> There is this small button ...

Actually, the entire cell is clickable, so the hint is arguably in the correct place.
