### ISSUE TITLE
some character marks appearing over and blocking other marks.

### ISSUE THREAD

**Issue by aranmohyeddin** [philc/vimium#3081]
for example in [this](https://en.wikipedia.org/wiki/Comparison_of_Linux_distributions)  in the section "Instruction set architecture support" the marks for sparc32 and sparc64 appear on top of the marks for those tiny buttons beside them and makes them unreadable. This is related to another issue that I raised about the mark not appearing on the right position. but still I think there might be other instances of this happening. I think it's good if we think about this and just keep it in mind. one solution could be not letting these marks collide but also it could become confusing what mark is for what button if two buttons are somehow around the same place. I don't think this is a priority I just thought it would be better if I point it out.

**Comment by innaterebel** [comment]
<kbd>Space</kbd> can rotate the layer of hints when they are stacked, though.

**Comment by aranmohyeddin** [comment]
Oh very simple and effective solution! thank you so much it didn't actually come to my mind:D
