### ISSUE TITLE
Distinguish between key and Tab+key

### ISSUE THREAD

**Issue by elliott-beach** [philc/vimium#3088]
Chrome version: 67.0.3396.99
Vimium version: 1.63.3

The Asana web app uses shortcut keys [beginning with tab](https://asana.com/guide/help/faq/shortcuts), e.g. `Tab - /`. Vimium captures `Tab - /` when listening for `/`.  It would be preferable if instead vimium only listened to the `/` and not `Tab - /`. 

The solution to this would be to do nothing or forward  the event when Tab + any key is pressed.

**Comment by smblott-github** [comment]
This seems too niche, @elliott-beach, and also too specific to one particular site.  Perhaps just add `/` as a passkey and accept that sometimes a page's shortcuts and Vimium's don't always work well together.

**Comment by elliott-beach** [comment]
OK
