### ISSUE TITLE
Feature Request: Tab moving 

### ISSUE THREAD

**Issue by Ynjxsjmh** [philc/vimium#3095]
Is there any shortkeys to `move current tab in focus to start `, `move current Tab in focus to end` .  Just similar with what command `moveTabLeft` and `moveTabRight` does.

supposing that I open below tabs in my firefox window.  I'm now in `Instagram` tab
| Stackoverflow | Google | Youtube | Facebook |  Instagram |

I want to move the `Instagram` tab to the start ,  just like below:
(cause sometimes you may open many many many tabs in one window , and it's a waste of time to drag the last tab to the start)
| Instagram | Stackoverflow | Google | Youtube | Facebook |

I have tried `>>`, but it didn't work for the last tab.

**Comment by innaterebel** [comment]
Many of Vimium's commands accept count prefix, <kbd>9</kbd><kbd>9</kbd> then `>>` will move the tab all the way to rightmost; well unless you have 100+ tabs, then you will need more than `99` :P

**Comment by Ynjxsjmh** [comment]
After adding key mappings `map >> moveTabLeft count=999999` and `map << moveTabRight count=999999`, it works fine for me now.

Thank you very much.
