### ISSUE TITLE
Gmail archive buttons not selectable

### ISSUE THREAD

**Issue by orschiro** [philc/vimium#3096]
Dear all, 

This [1] nifty Chrome extension adds archive buttons to every single message row in Gmail. 

However, Vimium is not able to select these buttons when I press `f`. 

Does anyone have an idea how to support those buttons and make them selectable?

Thank you!

![image](https://user-images.githubusercontent.com/170947/44260485-ce5c4800-a214-11e8-90d7-be0b90eac06f.png)

[1] https://chrome.google.com/webstore/detail/actions-for-gmail-beta/mclmmkhldnfokbgnhoibcgblghkmncem

**Comment by gdh1995** [comment]
The extension doesn't mark its buttons clickable:
![image](https://user-images.githubusercontent.com/5547703/44513491-13d6b480-a6f0-11e8-832c-830b250e58d3.png)

Maybe a `jsaction="..."` or `role="button"` is needed on its `<td>`s.

**Comment by orschiro** [comment]
Thanks @gdh1995! Appreciate your help.

That needs to be fixed on the side of the extension and not Vimium, correct?

**Comment by gdh1995** [comment]
Yes, and I suggestion a `role="button"` attribute on its node.

**Comment by orschiro** [comment]
Thanks, appreciate it. Will pass this on to the developers of the extension.
