### ISSUE TITLE
how to expand?

### ISSUE THREAD

**Issue by Georgeqhh** [philc/vimium#3104]
how to click "展开全部" to expand the left content use vimium? 
[
![1535213833 1](https://user-images.githubusercontent.com/16661018/44620518-68348c80-a8c8-11e8-8350-0aba877472ae.jpg)
](url)

**Comment by gdh1995** [comment]
In short, the `<div>` of `展开全部` has no signals to tell Vimium it's clickable, so Vimium can not click it unless #3063 is merged.

Chineses version: 简单来说，那个按钮做的不规范，没有告诉Vimium它可以被点击。现在没办法点它，除非3063这个PR被合并到Vimium里。

**Comment by Georgeqhh** [comment]
OK.Thank you for your detailed answer.
