### ISSUE TITLE
close vimium automaticly

### ISSUE THREAD

**Issue by Georgeqhh** [philc/vimium#3105]
When I use vimium in chrome,sometimes I will find vimium is disabled.When I try to restart it,I get the info as below:
Vimium is not running on this page.
Your browser does not run web extensions like Vimium on certain pages, usually for security reasons.
Unless your browser's developers change their policy, then unfortunately it is not possible to make Vimium (or any other web extension, for that matter) work on this page.

**Comment by Georgeqhh** [comment]
I  found it doesn't work chrome's pages?

**Comment by smblott-github** [comment]
Chrome just doesn't run extensions on these pages.  There's nothing we can do.

**Comment by Georgeqhh** [comment]
Got it.And the new created blank tab?I found it disabled,too.

**Comment by innaterebel** [comment]
Many modern browsers just don't run extensions on browser's built-in internal pages for security reasons.
Simply put, extensions are forced to be absent on all URLs that are not begin with `http(s)://` or `file:///`.

**Comment by smblott-github** [comment]
> And the new created blank tab?

[This](https://chrome.google.com/webstore/detail/new-tab-url/njigpponciklokfkoddampoienefegcl) might help.
