### ISSUE TITLE
focusing on certain elements makes search feature not functional.

### ISSUE THREAD

**Issue by aranmohyeddin** [philc/vimium#3106]
Open this [link](https://www.google.com/search?q=blot&ie=utf-8&oe=utf-8&client=firefox-b-ab) after the page is loaded, press <kbd>Tab</kbd> then press <kbd>/</kbd> the search box will show up but it won't be focused so if you type nothing gets typed in it, if you press <kbd>Esc</kbd> and then <kbd>/</kbd> again, it won't work. if you press <kbd>/</kbd> one more time the firefox search will appear and it will have the focus you can try many things but I could never make that search box have the focus again except by clicking on it with mouse and then pressing <kbd>Tab</kbd>.

**Comment by smblott-github** [comment]
Reproduced in Firefox.  Works fine in Chrome.
