### ISSUE TITLE
[Firefox] pref/addon/.. tabls breaks key binding

### ISSUE THREAD

**Issue by parisni** [philc/vimium#3120]
Hi

In FF, the built-in tabs break the key binding: 

For example: pressing J or K or x won't work in the "about:addons".
 That's annoying since equivalent Ctrl+PGleft or CTRL+PGright or CTRL+w
(= firefox built-in shortkey works on that kind of tabs)

**Comment by innaterebel** [comment]
Many modern browsers just don't run extensions on browser's built-in internal pages and pages created by other extensions, for security reasons.
Simply put, extensions are force-disabled on all URLs that are not begin with http(s):// or file:///.

**Comment by parisni** [comment]
> Many modern browsers just don't run extensions on browser's built-in internal
> pages and pages created by other extensions, for security reasons.
> Simply put, extensions are force-disabled on all URLs that are not begin with
> http(s):// or file:///.
> 

No way to rebind FF built-in shortkeys -- instead of using the plugin ?

**Comment by innaterebel** [comment]
That would depend on the individual browser, of course?
And as far as I know the recent developing approach of Firefox is not that customizing-friendly as it was.
Maybe there are other extensions specialized in customizing built-in hotkeys, but this is definitely not what Vimium designed to do.
