### ISSUE TITLE
[Wiki] http vs. https

### ISSUE THREAD

**Issue by dsh2** [philc/vimium#3121]
Dear Phil, the many good tips for custom search engines, etc. partially suggest http (as opposed to https) schemes, although the respective sites do support https. Maybe you could fix these? Thanks a lot! (As far as I know there is no way on github.com to create pull requests for wikis.)

**Comment by smblott-github** [comment]
Thanks, @dsh2.

Anybody can update the wiki.  Just clone, fix and push.

**Comment by marcotc** [comment]
[Addressed](https://github.com/philc/vimium/wiki/Search-Engines/_compare/60d2b3abf54839bc980f1e1e5b915870997bcbee...4d64e86f7383e11ab7089ad6c26ea8a3299818c4).
Removed a dead link too: Omniref.
