### ISSUE TITLE
Show quick result similar to chrome's omnibox in vomnibar

### ISSUE THREAD

**Issue by ShivanshuKantPrasad** [philc/vimium#3122]
It would be nice to see quick results in vomnibar similar to omnibox.

**Comment by ShivanshuKantPrasad** [comment]
For example when you search '2 + 3' in omnibar you get 5 as the top result and similar for some common tasks in google, i would like to have such a feature in vomnibar, i tried  [search completion](https://github.com/philc/vimium/wiki/Search-Completion) but it doesn't seem to do the job. Maybe i am missing a setting?

**Comment by smblott-github** [comment]
![image](https://user-images.githubusercontent.com/2641335/44979099-1ba21e80-af64-11e8-8289-556807ff11f3.png)

**Comment by ShivanshuKantPrasad** [comment]
Interestingly it only works if you put space between 2 + 4 and also it does not work for currency conversion.


![screenshot 4](https://user-images.githubusercontent.com/17960975/44979324-76e70780-af8a-11e8-9c2f-5ac21af2f2bc.png) ![screenshot 3](https://user-images.githubusercontent.com/17960975/44979353-87977d80-af8a-11e8-9968-9b52c274459f.png)
