### ISSUE TITLE
Copy email without mailto

### ISSUE THREAD

**Issue by orschiro** [philc/vimium#3123]
Dear all, 

When you press `yf` and select an email link, it copies the email as `mailto:email@domain.com`. 

Would it be possible for Vimium to recognise an email and only copy the `email@domain.com` part?

Yours, 

Robert

**Comment by smblott-github** [comment]
Good idea.

Fixed in 881a6fdc3644f55fc02ad56454203f654cc76618.

Thanks @orschiro.
