### ISSUE TITLE
HOTKEY | `map <C-A> openCopiedUrlInNewTab` no longer works (goes to bottom of page)

### ISSUE THREAD

**Issue by fohrums** [philc/vimium#3140]
```
UPDATED-STATEMENT: 20180921@171227 Post created
UPDATED-STATEMENT: 20180921@213132 Was reported back that I may be the only one experiencing this, going to continue testing
UPDATED-STATEMENT: 20180922@062150 [SOLVED], if using Autohotkey then remove conflicting lines (see below for exact issue)
```

# SPECIFICATION

* win10_v69.0.3497.100_x64
* ahk_v1.1.30.00

With the following hotkey I should be able to open clipboard to new tab. Although it was working fine the day before it doesn't seem to behave the same now (*see below for problem*). I'm using latest version and Vimium hasn't pushed another update in a month so it can't be Vimium's version.

## PROBLEM

* Unable to use CTRL+SHIFT+A to paste clipboard to a new tab anymore
  + Keymap `map <C-A> openCopiedUrlInNewTab`
    - instead, it behaves like CTRL+END which is bottom of page (*or in the case of Vimium `gg`*)

## SOLUTION

* Find any conflicting hotkeys used by other applications especially Autohotkey
  + removed `^+a::SendInput, {End} ; help with navigating` from ahk script(s) now working

**Comment by smblott-github** [comment]
Cannot reproduce.  Works fine here.

(And, without a mapping, `<c-A>` does nothing, for me.)

**Comment by fohrums** [comment]
[SOLVED]

Well, this is embarrassing. Autohotkey was conflicting with that keymap. It could be removed or changed; so, I decided to change it and it's working. Thanks for the input smblott-github.

```
^+a::SendInput, {End} ; help with navigating
```
