### ISSUE TITLE
support for changing the default search engine on omnibar

### ISSUE THREAD

**Issue by gleydsonsoares** [philc/vimium#3143]
Looks like there's no support for changing the default search engine on omnibar or i'm missing something? I know there's a way to enable "Custom search
engines", but would be nicer if there might be possible also change the default one.

**Comment by smblott-github** [comment]
It's on the options page, under advanced options:

![image](https://user-images.githubusercontent.com/2641335/45917412-71d0f600-be6e-11e8-95b0-76118c475fa3.png)

**Comment by gleydsonsoares** [comment]
Oops, really. thanks
