### ISSUE TITLE
vimium for Firefox doesn't seem to support link filtering

### ISSUE THREAD

**Issue by InconsolableCellist** [philc/vimium#3145]
The help pages for Vimium say that there's a filtering mode where you can type the text in links and activate the hints by using [0-9] instead of letters. However it doesn't seem that this option is vailable in Vimium-FF, at least as exposed by ? or in the options window.

Can it be enabled?

**Comment by smblott-github** [comment]
You enable filtered hints on the options page (under advanced options).

![image](https://user-images.githubusercontent.com/2641335/45936321-f6c22980-bfac-11e8-9f39-539e06aa8164.png)
