### ISSUE TITLE
Firefox: 'f' no longer works in GMail

### ISSUE THREAD

**Issue by raboof** [philc/vimium#3146]
Finding links with 'f' used to work fine for me in GMail, but now it has switched to the 'new layout' it no longer works for me.

Hitting 'f' I see a Vimium status message saying "Collecting hints...", then nothing.

Vimium version: v1.64
Firefox version: 61.0.1

**Comment by raboof** [comment]
Ah, spoke too soon: it works on the 'inbox' page, but when viewing an email/thread.

**Comment by raboof** [comment]
From the addons debugger console:
```
style is null dom_utils.js:369
getViewportTopLeft
moz-extension://8d5de73c-e1cb-42fd-a860-e1b730f78724/lib/dom_utils.js:369:1
getLocalHints
moz-extension://8d5de73c-e1cb-42fd-a860-e1b730f78724/content_scripts/link_hints.js:1141:14
getHintDescriptors/</<
moz-extension://8d5de73c-e1cb-42fd-a860-e1b730f78724/content_scripts/link_hints.js:124:88
onLoaded
moz-extension://8d5de73c-e1cb-42fd-a860-e1b730f78724/lib/settings.js:69:16
getHintDescriptors/<
moz-extension://8d5de73c-e1cb-42fd-a860-e1b730f78724/content_scripts/link_hints.js:121:18
DomUtils.documentReady
moz-extension://8d5de73c-e1cb-42fd-a860-e1b730f78724/lib/dom_utils.js:23:18
getHintDescriptors
moz-extension://8d5de73c-e1cb-42fd-a860-e1b730f78724/content_scripts/link_hints.js:119:14
linkHintsMessage
moz-extension://8d5de73c-e1cb-42fd-a860-e1b730f78724/content_scripts/vimium_frontend.js:279:14
init/<
moz-extension://8d5de73c-e1cb-42fd-a860-e1b730f78724/content_scripts/vimium_frontend.js:316:20
apply self-hosted:4613:5 applySafeWithoutClone
resource://gre/modules/ExtensionCommon.jsm:234:16
addListener/asyncWithoutClone/<
resource://gre/modules/ExtensionCommon.jsm:1918:20
```

**Comment by gdh1995** [comment]
Confirmed on Firefox 61.0.1 x64 on Windows 10, but Firefox 62 has no such a problem.

I think it's a bug of Firefox that `getComputedStyle` returns `null`, because according to https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle, **neither of the 2 specifications** says the API might return null .

**Comment by raboof** [comment]
I can confirm upgrading to firefox 63.0.1 solves the issue for me as well, and removes the need for the patch.

Feel free to close this issue and the accompanying PR.
