### ISSUE TITLE
Scroll not working on bugzilla.mozilla.org

### ISSUE THREAD

**Issue by orschiro** [philc/vimium#3149]
Dear all, 

Could someone please confirm that scrolling the page does not work on https://bugzilla.mozilla.org/show_bug.cgi?id=1398539?

Yours

**Comment by gdh1995** [comment]
Confirmed.

The reason of this issue: https://github.com/philc/vimium/issues/3041#issuecomment-415346708

Related PR: #3111

**Comment by orschiro** [comment]
Thanks for addressing it in your PR, @gdh1995!

Closing this. :) 

Yours
