### ISSUE TITLE
Yellow overlays are too close to each other

### ISSUE THREAD

**Issue by orschiro** [philc/vimium#3151]
Dear all,

Is there any solution to making those yellow overlays smaller?

In the below example, I cannot tell which overlay relates to which click action because they are overlaying each other too much. 

![image](https://user-images.githubusercontent.com/170947/46289087-5fd21000-c55e-11e8-8663-2e0e67d7b023.png)

[Source](http://www.feedbucket.com/?src=http%3A%2F%2Ffeed.informer.com%2Fdigests%2F520RAMSOKD%2Ffeeder.rss)

**Comment by innaterebel** [comment]
You can customize the appearance of link hints by CSS under advanced option.
But before that, <kbd>Space</kbd> has the function to rotate the layers of hints when they are overlaid. (although I understand your main issue as being unable to see tiny links that get covered by hints?)

**Comment by orschiro** [comment]
> You can customize the appearance of link hints by CSS under advanced option.

I may have to do that. Do you have an example for me?

> But before that, Space has the function to rotate the layers of hints when they are overlaid. (although I understand your main issue as being unable to see tiny links that get covered by hints?)

That doesn't really help: https://drive.google.com/file/d/1DFfU6DG4Uw0GBvd-r-l4XAshzABXmpTj/view

Yours

**Comment by innaterebel** [comment]
The CSS editing section in advanced option lists the current styles in use, including the default style, so you just need to edit the relevant lines.
However I am not really educated in coding stuff hence cannot give you a proper instruction on the editing, sorry.

**Comment by orschiro** [comment]
You were already of enough help, thank you, innaterebel!
