### ISSUE TITLE
Open Selected Link?

### ISSUE THREAD

**Issue by danieljsj** [philc/vimium#3152]
is there a way to open a selected link? Like, if I use `/` to enter "find" mode, and select a link... is there a hotkey I can use to open the link I've selected?

**Comment by innaterebel** [comment]
You do know Vimium has a link hint mode (default binding `f`), and are just asking for what you are asking, don't you?
Well in that case... <kbd>Enter</kbd> will do.
(and <kbd>Ctrl</kbd>+<kbd>Enter</kbd> to open the link in a new background tab.
        <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd> to open in a new foreground tab.
        <kbd>Shift</kbd>+<kbd>Enter</kbd> to open in a new window.
        <kbd>Alt</kbd>+<kbd>Enter</kbd> to download the link. these are browser's native hotkeys)

**Comment by smblott-github** [comment]
To clarify @innaterebel's comment.

Use `/` to search for some text within a link's text.  `Enter` to exit find mode.  Then `Enter` again to use the browser's own functionality to open the link.  (Or one of the other variations explained above.)

**Comment by danieljsj** [comment]
@smblott-github --- you answered my question -- `/` to find a link's text and then double-`Enter` does the trick! Thanks!
