### ISSUE TITLE
problems in my firefox pdf reader

### ISSUE THREAD

**Issue by Ynjxsjmh** [philc/vimium#3153]
When I open a pdf file in firefox, I can use vimium's `j` and `k` to move the file down and up normally.

But **the problem** is that if I click the button shown in the picture, my vimium's `j` and `k` won't work (other's like `J` and `K` is still work) unless I use `r` to refresh this page.  Even when I reopen the sidebar, vimium's `j` and `k` still don't work.
![default](https://user-images.githubusercontent.com/40143136/46474559-c7fe4b80-c815-11e8-8d99-717df6a04618.png)

And my vimium version is 1.64 and my firefox version is 59.0.2 (64 bits)

**Comment by smblott-github** [comment]
This sounds like a problem the the focus and/or frames.

If it's frames, then the `mainFrame` command might get you back where you started.

**Comment by Ynjxsjmh** [comment]
I tried in two ways:
Firstly, after I press that button to hide the sidebar, I couldn't use `j` and `k`. Then I use `gF` but I still couldn't use them.
Secondly, before I press that button, I use `gF`. After that I press that button, I still couldn't use `j` and `k`.  Then I use `gF` again, I still couldn't use `j` and `k`.

By the way, I tried to use `gf` to replace `gF`, but it doesn't work.

**Comment by gdh1995** [comment]
@Ynjxsjmh Sorry to bother your, but have you tried disabling Vimium? I think what you saied `j` and `k` did is because Firefox's PDF.js module also uses 'j' and 'k' to scroll by exact one page.

A simple test is to press `f` or `o` (when `j` works) to see whether LinkHints / Vomnibar shows.

**Comment by gdh1995** [comment]
Sorry for my poor representation. So, **do you** mean, with **Vimium enabled**, you can press `j` to scroll the PDF pages **little by little** (once 2~3 at a time)?

If you can, then it's indeed an issue about Vimium; if not, then it just belongs to Firefox.

I asked that because I could not run Vimium on a PDF webpage, when I opened a PDF file in my computer using Firefox, so I'm not sure whether Vimium key mappings took effects on your computer.

**Comment by Ynjxsjmh** [comment]
> So, do you mean, with Vimium enabled, you can press j to scroll the PDF pages little by little (once 2~3 at a time)?

With Vimium enabled, I **can** press `j` to scroll the PDF pages little by little. (Maybe I use Firefox extension Noscript? I don't know)

But if I click (no matter I use mouse or use `f` to 'click') the button circled below the picture, I couldn't use `j` and `k` anymore.
![46474559-c7fe4b80-c815-11e8-8d99-717df6a04618](https://user-images.githubusercontent.com/40143136/46535618-98ffdc80-c8de-11e8-8c52-dded7a469ac9.png)

**Comment by gdh1995** [comment]
Confirmed on Firefox 59; local Vimium can not work on PDF tabs on Firefox 62.

The inner reason is after clicking the top-left button, `activatedElement` in `scroller.coffee` will become it, and then `firstScrollableElement` will be skipped and `findScrollableElement activatedElement, ...` will only return `<html>`.

@smblott-github in my opinion, this means we need to re-check the result of `findScrollableElement` in case it returns `document.scrollingElement ? document.body`.
