### ISSUE TITLE
Is there a way to clear the history of Find mode?

### ISSUE THREAD

**Issue by innaterebel** [philc/vimium#3155]
Find mode seems to respect the nature of Chrome's incognito windows and won't preserve its history post-session.
However its history during a regular window session lasts forever. I guess this is the case as well for any other Vimium features that remember, no? (marks, tab closing history, etc.)

I do not dare to ask for a history removing section in Vimium option as it would be much work. But can we have some quick trick like <kbd>Del</kbd> removes a shown history entry? (quite unideal both design and code-wise though)
Or at least for Find, simply limit the history to be session-only (like it already does for incognito windows), if that makes sense.

**Comment by smblott-github** [comment]
Not really.

But maybe...

1. Do fifty *different* queries.  That'll push all of the existing queries out of the history.

2. Close all other tabs.  Go to the Vimium options page.  Open the dev console.  Do this...

```Javascript
chrome.storage.local.set({"findModeRawQueryList": []})
```

You can check with:

```Javascript
chrome.storage.local.get("findModeRawQueryList", function (x) {console.log(x);})
```

(So, the answer still is.... "not really".)

**Comment by innaterebel** [comment]
Wow, fifty? :flushed: That's a whole lot it can remember.
As I really only use incognito windows, I merely hope for one way to remove those ancient queries I made at beginning of time so they don't clutter with my incognito queries. So I guess DevTool is enough for me, thanks. :wink:

Feel free to close if you are certain you are not going to implement anything.
Apparently this is niche enough no past request had been made.
