### ISSUE TITLE
Feature suggest: Open a Menu of Recent Closed Tabs

### ISSUE THREAD

**Issue by Haozun** [philc/vimium#3160]
This feature appeared in _VimFx_.
I have searched the Issues, find no ones talks about it.
The Menu should sort links by closing time, And display likes to `"o":Vomnibar.activate`.
I often press `X` for many times, sometimes I still cannot find what I have closed carelessly

**Comment by gdh1995** [comment]
advertise：you may try my custom Vimium - https://github.com/gdh1995/vimium-c . It supports that "o" opens Vomnibar and shows recently closed tabs ("omni" mode), and Vomnibar shows recent history items (de-duplicated using current tabs' urls) on "history" mode.

**Comment by jab** [comment]
Looks like this was closed without explanation, presumably WONTFIXed.

For anyone else finding this issue who wants to stick with the official Vimium, I just found https://chrome.google.com/webstore/detail/recently-closed/khiocfdofmabcpofejbffpbocoabcjib and it seems to do the trick. (It allows restoring the 25 most recently closed tabs (which is apparently [Chrome's limit](https://chrome.google.com/webstore/detail/recently-closed/khiocfdofmabcpofejbffpbocoabcjib) but at least it's better than the only 10 available from the History menu.)

**Comment by gdh1995** [comment]
@jab Just for your information, Vimium C supports "PageDown" / "Shift+ArrowDown" and "PageUp" / "Shift+ArrowUp" on Vomnibar to traverse through all sessions and other search results.
