### ISSUE TITLE
Request to publish a new release

### ISSUE THREAD

**Issue by alexzorin** [philc/vimium#3165]
Hello,

Thank you for the fantastic addon.

Would it be possible to release a new patch-level release to Chrome Extension Gallery & AMO that includes the smooth scrolling fix?

Seems to be biting quite a few people lately.

Apologies if you already have a release planned - will run from source in the meantime.

**Comment by orschiro** [comment]
Dear @alexzorin, 

Thanks for raising this. I too am waiting for a fix and hope to seeing a new release any time soon. 

The last one 1.64 was from August 30, 2018.

Much appreciated. 

Yours
