### ISSUE TITLE
shortcut for detaching/reattaching tabs in firefox?

### ISSUE THREAD

**Issue by aranmohyeddin** [philc/vimium#3171]
so I have a firefox window with tabs A, B, and C. I'd like to press MAGIC while viewing tab C and get two firefox windows, one having A and B in it and the other only having C in it. then pressing MAGUC and have the window I'm in be merged with the last views window. is any of this possible through vimium-FF?

**Comment by hackel** [comment]
Did you even look at the help?  Press W to open the current tab in a new window.  There is no history stored recording which window a tab came from, so the second item you asked for is not possible.

This is a dupe of #2407.  Search first next time!

**Comment by ravindUwU** [comment]
In case anyone is after the name of the command to detach a tab, it's `moveTabToNewWindow`
