### ISSUE TITLE
[Firefox] Vimium-FF opens default search engine instead of link

### ISSUE THREAD

**Issue by lindhe** [philc/vimium#3174]
In [this article from SweClockers](https://www.sweclockers.com/nyhet/26501-hp-lanserar-barbar-dator-med-4g-lte-och-225-timmars-batteritid), I get an unexpected behaviour from clicking the article image. Instead of clicking the web page element, a new tab is opened with the default search engine. For me, https://duckduckgo.com/?q= is opened while my friend gets https://www.google.com/webhp when he tries on his computer.

![example of the image I click, and the hint](https://user-images.githubusercontent.com/7773090/47607442-4a96b700-da20-11e8-9e50-ebf4b15b43a5.png)

**My system**
Firefox: 62.0.3
OS: Linux 4.18.14-arch1-1-ARCH
Vimium: 1.64

Not sure of the versions that my friend tested with. But it was on Ubuntu, I believe.

I have not seen this behaviour on other sites. Not 100% that it is Vimium-FF's fault, but I think so. Don't get the same issue with Vimium on Chromium.

**Comment by gdh1995** [comment]
On Windows 10, confirmed on Firefox 62.0.2 (64 bit), but not on Chrome 70 x64.

**Comment by SimonAlling** [comment]
It's worth mentioning that the current behavior in Chrome isn't really optimal either. It would be even better if image links like the ones in SweClockers articles could actually be clicked using Vimium.

**Comment by lindhe** [comment]
@SimonAlling I think that's more of SweClocker's fault than Vimium's. It seems they don't include an href in their anchor tags, which is probably why Vimium is having a hard time with it. Here on Github, it works like one expects it to, and here there is an href attribute in the anchor tag which holds the img tag.
