### ISSUE TITLE
disable scroll effect

### ISSUE THREAD

**Issue by gitGksgk** [philc/vimium#3177]
hi awesome developers, thanks for this powerful vimium. 
I like "scrollpagedown" most. scrolling half page down is awesome!! However, it has some kind of scrolling effect lasting for 0.5s or so. Since this function is used very frequently, is it possible to make it "directly" there,  like the effect that you press pageup/pagedown,  instead of "scroll" there, like the effect that you press 10 times of down in an instant?

**Comment by innaterebel** [comment]
Suppose you are meaning the smooth scrolling...
![smooth scrolling option](https://cloud.githubusercontent.com/assets/17931286/13884318/6db0adee-ed25-11e5-9111-3df866913628.png)

**Comment by gitGksgk** [comment]
Great! closing smooth scrolling solved my problem. Many thanks!
