### ISSUE TITLE
Javascript bookmarks not working anymore

### ISSUE THREAD

**Issue by romgrk** [philc/vimium#3178]
My javascript bookmark use to work on Chrome 69, but it doesn't on version 71.0.3578.30.

Its content is:
`javascript:(function()%7B(function () %7Bvar i%2C elements %3D document.querySelectorAll('body *')%3Bfor (i %3D 0%3B i < elements.length%3B i%2B%2B) %7Bif (getComputedStyle(elements%5Bi%5D).position %3D%3D%3D 'fixed'||getComputedStyle(elements%5Bi%5D).position %3D%3D%3D 'sticky') %7Belements%5Bi%5D.parentNode.removeChild(elements%5Bi%5D)%3B%7D%7D%7D)()%7D)()`

https://github.com/philc/vimium/pull/3167 might solve this.

**Comment by shaymdev** [comment]
I use javascript bookmarklets all the time from the vomnibox and have really been missing them over the last little while. Here's to hoping the great minds can figure it out.

**Comment by wocala** [comment]
+1 here. Chrome V70 works, V71 fails.k
Failed to open javascript via Vomnibar.activateBookmarks and Vomnibar.activateBookmarksInNewTab
only clicking the bookmarklet works.

My javascript is (case-sensitive Find):
javascript:(function(){var text=prompt('Search for:','');if(text==null || text.length==0)return;var spans=document.getElementsByClassName('labnol');if(spans){for(var i=0;i < spans.length;i++){spans[i].style.backgroundColor='transparent';}}function searchWithinNode(node,te,len){var pos,skip,spannode,middlebit,endbit,middleclone;skip=0;if(node.nodeType==3){pos=node.data.indexOf(te);if(pos>=0){spannode=document.createElement('span');spannode.setAttribute('class','labnol');spannode.style.backgroundColor='red';middlebit=node.splitText(pos);endbit=middlebit.splitText(len);middleclone=middlebit.cloneNode(true);spannode.appendChild(middleclone);middlebit.parentNode.replaceChild(spannode,middlebit);skip=1;}}else if(node.nodeType==1 && node.childNodes && node.tagName.toUpperCase()!='SCRIPT' && node.tagName.toUpperCase !='STYLE'){if(node.tagName.toUpperCase() == "IFRAME"){ node = node.contentWindow.document.body; }for(var child=0;child < node.childNodes.length;++child){child=child+searchWithinNode(node.childNodes[child],te,len);}}return skip;}searchWithinNode(document.body,text,text.length);})();

**Comment by kevin349** [comment]
+1 to it not working on Chrome V71. Scriptlet works if I copy directly into the console or manually click.

**Comment by ntskl** [comment]
Been running into the same problem lately. Seems to have started being an issue only a couple days ago.

**Comment by freder** [comment]
looks like there is a fix. any chance this will be merged/released soon?

**Comment by dvygolov** [comment]
Guys, this is still not working?((

**Comment by jake1138** [comment]
Still not working in 76.0.3809.100.  Very frustrating.  You have to click on another bookmark first then it works.  See also: https://support.google.com/chrome/thread/3959468?hl=en

**Comment by alllex** [comment]
Still does not work on `77.0.3865.90`, please fix this!

**Comment by dvygolov** [comment]
Guys, if there is a fix, why don't you merge it? This thing drives me nuts( I've got a couple of great js-bookmarks, that help me automate my work, and this feature could boost my productivity a lot...

**Comment by gdh1995** [comment]
@philc Could you merge #3437 to fix this issue? I've tested it and it works well.

**Comment by philc** [comment]
Dahan thanks for the bump and the PR. I'll merge it this weekend!

**Comment by patkujawa-wf** [comment]
It doesn't look like it was merged, or am I missing something? Thanks guys!

**Comment by philc** [comment]
Sorry for the delay folks. I've merged the fix from @gdh1995 but haven't released a new version to the chrome store. I'll batch a few more changes together in the next week and create a new release.
