### ISSUE TITLE
global mark storage

### ISSUE THREAD

**Issue by Ynjxsjmh** [philc/vimium#3181]
Sometimes I need to check for the key binding of my global mark. But I don't know how to see that. 

I notice in [issue 1716](https://github.com/philc/vimium/pull/1716) you mentioned global mark is stored in `storage.sync`. I have searched for that keyword related with Firefox, but I don't have any idea on it.

So is there a way for me to see the key mappings of my global mark?

I use **Firefox 62.0.3 (64 bits)**

**Comment by gdh1995** [comment]
* Open Vimium's options page, open the developer tool and go to the Console panel.
* input `chrome.storage.sync.get(i=>console.log(i))` and press <kbd>Enter</kbd>
* then you'll see all configurations of Vimium
* those whose key starts with `vimiumGlobalMark` are what you want.

**Comment by Ynjxsjmh** [comment]
Thank you very much. I never thought about this way to view the configuration of the vimium.

Detail is use F12(for most brower's default key) to open the developer tool.

**Comment by thisdavej** [comment]
### Viewing and Removing Global Marks in Vimium

It would be great if global/local mark management could be handled through the Vimium UI. As an end user, here's some alternative ways I arrived at as an interim solution to handle global mark management:

To view the Vimium global marks that exist:

- Navigate to the `Vimium Options` page.
- Press the `F12` key to launch Developer Tools
- Select the `Console` tab.
- Paste the following lines together into the console and then hit Enter:

```js
chrome.storage.sync.get(null, function(items) {
    var keys = Object.keys(items);
    keys.filter(k => k.startsWith("vimium")).forEach(k => console.log(k))
});
```

To delete a specific Vimium global mark ("P" in this example):

```js
mark = 'P'
const regex = new RegExp(`^vimiumGlobalMark.*${mark}$`);
chrome.storage.sync.get(null, items => {
    var keys = Object.keys(items);
    keys.filter(k => k.match(regex)).forEach(k => chrome.storage.sync.remove(k))
});
```

To delete all Vimium global marks:

```js
const regex = new RegExp('^vimiumGlobalMark.*$');
chrome.storage.sync.get(null, items => {
    var keys = Object.keys(items);
    keys.filter(k => k.match(regex)).forEach(k => chrome.storage.sync.remove(k))
});
```

To accomplish the same goal with a more graphical approach:

- Install the [Storage Area Explorer](https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb?hl=en) Chrome extension.
- Restart Chrome to activate the extension.
- Navigate to the `Vimium Options` page.
- Press the `F12` key to launch Developer Tools
- Select the `Storage Explorer` tab (This was added when the extension was installed above.)
- Select the `chrome.storage.sync` tab
- Review the the Vimium global mark entries that are in the format of `vimiumGlobalMark|<shortcut_key>`.
  - For example, you would see `vimiumGlobalMark|P` if there is a global mark defined for "P".
- If desired, click the red delete icon on the far right of the row entry to delete the mark.

**Comment by thisdavej** [comment]
Also, to view the Vimium global marks and associated URLs that exist:

- Navigate to the `Vimium Options` page.
- Press the `F12` key to launch Developer Tools.
- Select the `Console` tab.
- Paste the following lines together into the console and press the Enter key:

```js
chrome.storage.sync.get(null, function(items) {
    o = Object.entries(items).filter(([k]) => k.startsWith("vimiumGlobalMark"))
    console.log("Mark URL");
    o.forEach(([k,v]) => console.log(`${v.markName}    ${v.url}`))
});
```
