### ISSUE TITLE
wrong text

### ISSUE THREAD

**Issue by hubertyuy** [philc/vimium#3186]
After I try those commends, I found 2 wrong text
"f" is for Open a link in a new tab
"F" is for Open a link in the current tab
may need to correct the text in the Vimium Help area.

**Comment by innaterebel** [comment]
You are probably unnecessarily holding <kbd>Shift</kbd> while typing the link hints.
While link hints are all displayed in uppercase, it is not an indication that they need to be typed uppercase.

<kbd>Shift</kbd>, combines with other modifier keys, actually acts as a feature to flip the mode of link hints. See #3070.
