### ISSUE TITLE
sheetcheat

### ISSUE THREAD

**Issue by Athesto** [philc/vimium#3191]
There is a fast way to show the command list?,
I have to open
menu Vimeum/Options/Show Available commands

**Comment by Athesto** [comment]
? | show the help dialog for a list of all available keys

**Comment by MushiTheMoshi** [comment]
what if I want to know all the available commands primitives/functions ? 
e.g. scroll  < which is the function for this one?

**Comment by gdh1995** [comment]
@MushiTheMoshi you may open Vimium Options page and then click "Show available commands".
