### ISSUE TITLE
Visual response to toggleMuteTab command

### ISSUE THREAD

**Issue by ferenczy** [philc/vimium#3192]
When I use the command `toggleMuteTab`, there's no visual response from Vimium. Which is not an issue when everything is working properly but it would be useful if Vimium shows a notification like "The current tab has been muted" or "All tabs have been unmuted" when debugging issues.

**Comment by smblott-github** [comment]
Thanks @ferenczy.  You're right.  Fixed in 070e4172b9fec44e796fc326f429ce6f1cac3c69.
