### ISSUE TITLE
conflict with leetcode

### ISSUE THREAD

**Issue by Jedore** [philc/vimium#3194]
@philc 
Hi,  when i practice leetcode, i want to use leetcode's edit mode of vim, but it may be conflict with vimium.
Can I disable vimium on leetcode page but enable on others page ? Thanks a lot.

**Comment by gdh1995** [comment]
On Vimium Options page, "Excluded URLs and keys" can support so.

**Comment by Jedore** [comment]
Yeah, cool, thx
