### ISSUE TITLE
Text-only plugins make link hints hard to read

### ISSUE THREAD

**Issue by mattrixman** [philc/vimium#3195]
First of all, thanks for vimium.  It's the first thing I install when I am faced with a blank-slate OS. I love it.  This is a suggestion for a minor usability improvement.  These two images really tell the whole story:

https://imgur.com/a/PPkARzp

It would seem that the yellow backdrop that makes the hints readable is implemented as an image.  Disabling images causes them to be transparent, so hints are hard to see. I'm using a plugin called "Text-only mode", I think there are other plugins like this, but I expect they all work the same way.

I imagine this could be addressed by putting something opaque (and also yellow) behind the yellow images, so that even when the images are removed, the layered effect remains.

**Comment by smblott-github** [comment]
> It would seem that the yellow backdrop that makes the hints readable is implemented as an image. 

Actually it's implemented in CSS (and you can change the CSS on the options page).

If there's a bug here, then it's either that Vimium is allowing the page to override its CSS, or that your plugin will of course generate unfortunate, unreadable results if it blindly diddles with a page's CSS.

I suggest you look into exactly what's the interaction between the plugin and Vimium's CSS is.

**Comment by MatrixManAtYrService** [comment]
Aah, good to know, thanks.  I had assumed that the plugin was blindly transparent-ing any img tags it finds.  It sounds like it's more complex than that.

I think this issue can be closed.  If I can later distill it to something useful that seems like a reasonable vimium change, I'll open a new one.  (My web-fu isn't quite strong enough, nor my schedule open enough for me to be confident that that will happen).

**Comment by mattrixman** [comment]
(oops... wrong github account....  I'm that guy too  ^^^)
