### ISSUE TITLE
Vimium not working on chrome webstore

### ISSUE THREAD

**Issue by channelx43** [philc/vimium#3196]
Hi, 
I couldn't find related thread, so opening this as a new thread. 
I am using Chrome/ Vimium and it doesn't work on the chrome web-store. 

thanks

**Comment by HachemiH** [comment]
Hi,
On the webstore page it's said : 

> *NOTE* Google does not allow Vimium to run on this Chrome Web Store page and the Chrome New Tab page, by design. Sorry about that!

> *NOTE* Chrome has some alarmist messaging around the permissions that Vimium needs to run. Really all it's asking for is that Vimium's javascript be loaded into every page. Don't be alarmed. Vimium never talks to any servers and does absolutely nothing with your data. Read the open source code if you're curious.

**Comment by channelx43** [comment]
Ah! okay. Thank you.
