### ISSUE TITLE
Comment breaks unmap

### ISSUE THREAD

**Issue by ferenczy** [philc/vimium#3199]
When I put both the keyword `unmap` and a comment on the same line in the _Custom key mappings_ configuration text box, then `unmap` is ignored. With the `map` keyword, it's working fine.

    unmap ? # doesn't work
    map ? showHelp # this works

**Comment by smblott-github** [comment]
Comments are only supported at the start of the line.

In your second example, `# this works` is not being treated as a comment, it's being treated as a command option, as in [these examples](https://github.com/philc/vimium/wiki/Tips-and-Tricks#muting-audio).
