### ISSUE TITLE
Feature: preview link URL before following it (like link hovering)

### ISSUE THREAD

**Issue by tobanw** [philc/vimium#320]
It would be nice to have a way to see the url before following a link. If you manually tab through links, the link hover brings up the status bar url. Maybe it could be implemented with a prefix before f, e.g., s-f then link hint.

Also, 'copy link address' would be a great feature. I'd suggest y-f then link hint.

**Comment by devasood** [comment]
It would actually be really helpful, allowing us to hover over links to simulate the hover or mouse over events

**Comment by snapfractalpop** [comment]
Is there a way to do this? It seems all the various issues / threads have been closed, but I don't see how it was ever resolved. Yanking is not a solution, as it clobbers the clipboard.

**Comment by JJPandari** [comment]
@snapfractalpop Sure yank is not, besides polluting the clipboard, one also has to *paste* the yanked link to see it.  

I wonder what the tag `closing-lack-of-interest` means, is it that too few people are interested in this feature so it won't be implemented, or no one is making a PR for this even many people have  shown need for this since 2011?

**Comment by snapfractalpop** [comment]
> There's a lot of interest in this issue.

...

> ```closing-lack-of-interest```

There was clearly a lot of interest at one point, and several threads about this very topic. There's a bit of a "runaround" with the threads making circular references to one another. Perhaps the lack of *progress* has been mistaken for a lack of interest. I'm confident there is still a lot of interest in this still.

**Comment by mcint** [comment]
Unless I misunderstand, a basic version of this is already available, try this:

Add to **Custom key mappings**
```
map D LinkHints.activateMode action=focus
```
Activating this brings the link into focus, showing the URL at the bottom left (/right) of the window. You can follow up with chrome-native <kbd>Shift-Enter</kbd> to open in a new tab, or <kbd>Enter</kbd> to follow in this tab.

Per https://github.com/philc/vimium/issues/2839#issuecomment-676917380, linking to [wiki Tips-and-Tricks#hovering-over-links-using-linkhints](https://github.com/philc/vimium/wiki/Tips-and-Tricks#hovering-over-links-using-linkhints) and a bit of testing.

---

I like this a lot, I only wish that vimium could present a little bibliography section of multiple links. Perhaps color gradient differentiated.

I've been wanting to record which links I follow and eventually train vimium to prefer those links, or to prefer half-keyboard following and hint-filtering of links.
