### ISSUE TITLE
How can I select autocomplete items without arrow keys?

### ISSUE THREAD

**Issue by ahmedmohiduet** [philc/vimium#3205]
So, at the time of inserting into a textbox my chrome provides some autocomplete items. Would there be some way I could select any of them without having to use arrow keys but from vimium keys?

**Comment by channelx43** [comment]
Hit control and then use j or k

**Comment by yugandharc9** [comment]
Type input give hit `esc` then `f` it will show links to auto complete

**Comment by ahmedmohiduet** [comment]
Closing... since from @channelx43 's answer CTRL+J/K working fine (y)
