### ISSUE TITLE
Feature: copy a link's URL

### ISSUE THREAD

**Issue by philc** [philc/vimium#321]
It would be nice to be able to copy a link's URL using Vimium. One approach would be to implement "yf" for yanking a link -- type, y, then use the normal link-follow UI to select the link.

Other ideas are welcome.

**Comment by jondubere** [comment]
+1 - this would be very handy to have

**Comment by innaterebel** [comment]
@jondubere It's already implemented. The command is `yt`, as the original comment suggested.

**Comment by smblott-github** [comment]
I think it does if you click "Show advanced commands"....

![image](https://user-images.githubusercontent.com/2641335/39263665-c8cffc8c-48ba-11e8-9643-0b27f424dac8.png)

**Comment by dm17** [comment]
> I think it does if you click "Show advanced commands"....
> 
> ![image](https://user-images.githubusercontent.com/2641335/39263665-c8cffc8c-48ba-11e8-9643-0b27f424dac8.png)

How do you show advanced commands? Looking for how to copy URLs without installing another chrome extension for it.

**Comment by gdh1995** [comment]
@dm17 open Vimium's Options page, press <kbd>?</kbd>, and then Vimium will show a help dialog, so you can find "Show advanced commands" at its bottom right corner.

**Comment by spiderlike** [comment]
That will be aWeSoMe!!!!! copying link from anchor tag! 😃😃

**Comment by bjourne** [comment]
I think the point I and others have made is that this feature is super useful but not very discoverable because it is "hidden" on the advanced commands page.

**Comment by braedonwatkins** [comment]
to save a future bozo such as myself from wasting 2 minutes... you obviously can't do this in visual mode! the normal 'y' command will shortcut this. just 'yf' by itself is sufficient :)
