### ISSUE TITLE
Feature request: scroll to {left,right} 

### ISSUE THREAD

**Issue by erjoalgo** [philc/vimium#3210]
Are there horizontal scrolling analogues to the "scroll to {top,bottom}" commands?

**Comment by smblott-github** [comment]
No, but this might approximate that behaviour:

```
map X scrollLeft count=99999
map Y scrollRight count=99999
````

**Comment by innaterebel** [comment]
Um, isn't there 

> `zH`　Scroll all the way to the left

> `zL`　Scroll all the way to the right

(though currently broken)? Or I misunderstand the request?

**Comment by smblott-github** [comment]
(Doh! my bad, thanks @innaterebel.)

**Comment by erjoalgo** [comment]
Thanks, I had missed that.
