### ISSUE TITLE
`n` command does not search for previous search term 

### ISSUE THREAD

**Issue by arizzubair** [philc/vimium#3217]
1. Search for `abc` in a tab using `/` command.
2. Go to other tab and press `n`.
3. It shows `no query to find` error.
4. It used to search for the term a week or two earlier.

Env:
vimium: Version 1.64.3
chrome on macos: Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by kschaab** [comment]
It is weird, this stopped working for me as of a few days ago.  I'm on 1.64.6 on chrome on Linux.  N works as expected but n doesn't do anything.
