### ISSUE TITLE
Have a reload button in the vimium extension icon that reinstalls the vimium js

### ISSUE THREAD

**Issue by gvteja** [philc/vimium#3221]
Usecase: I use the [Mercury reader extension](https://chrome.google.com/webstore/detail/mercury-reader/oknpjjbmpnndlpmnhmekjpocelpnlfdi) to remove all the distractions from a page and get a clean view. Unfortunately, after doing that all the vimium mappings no longer work. It would be great if there is a way to dynamically reload/re-register all the vimium mappings again.

**Comment by gdh1995** [comment]
Um, this seems a good idea.

I'd like to use "click the Vimium button" to re-inject vimium context to the page, if no active "chrome.runtime.Port" can be found in background scripts, otherwises continue to show the popup page.

**Comment by smblott-github** [comment]
The Mercury Reader extension seems to inject an iframe into the page...

![image](https://user-images.githubusercontent.com/2641335/51069579-ab9a5800-1629-11e9-92f2-538cbb7f946b.png)

and Chrome just won't run extensions like Vimium in such an iframe.

**Comment by gvteja** [comment]
Ah ok. Thanks for the information. 
Would have really loved to use the vimium shortcuts for navigating the page. Unfortunate that that is not possible :/
