### ISSUE TITLE
Keybinding for Homepage

### ISSUE THREAD

**Issue by Dentrax** [philc/vimium#3229]
I didn't see it on the documentation. Is there a keybinding to go to the home page?

**Example:** <kbd>gH</kbd> -> Redirect to the **default** _search engine_ page.

**Comment by smblott-github** [comment]
Not currently.

**Comment by Dentrax** [comment]
Could be added in the future?

**Comment by smblott-github** [comment]
It is not a frequently-requested feature, so I personally wouldn't be too keen on adding a new command for this.  It's a shame that the `history` API is so limited, otherwise...

    map gH goBack count=999999

would work.
