### ISSUE TITLE
Question: Is in vimium different marked link hints for scroll bar (on multiple scroll bar site)?

### ISSUE THREAD

**Issue by waldauf** [philc/vimium#3231]
Hello,

I had installed Vimium in FF and love it. Really great tool, many thx for that. 

I found out that I have problem with sites where is multiple scroll bars on one site. I found out that I should use _link hints_ to work with. I read doc on the web, read some forums but didn't find any manual how to use it. Can I ask you if you can advice me and kick in the right way, please?

**Comment by waldauf** [comment]
Hmm, bad asked question from me - I'm sorry. I know about `f` and `?`. But I'm trying to find out how to switch between different scrollbars on one site. I read [here](https://github.com/philc/vimium/issues/2359) and [here](https://github.com/philc/vimium/issues/2359) where is displayed `scroll: <number>` option which I can't find. So may be I got it bad. 

So I'll try to ask again and better: Are in vimium marked scroll bars different than links (via `scroll: `)?

**Comment by smblott-github** [comment]
The text "Scroll" only appears if you are using filtered hints:

![image](https://user-images.githubusercontent.com/2641335/51748380-280a4d80-20a4-11e9-8393-53201a96f63b.png)

The same elements are selectable with alphabet hints, but it's less obvious.

**Comment by waldauf** [comment]
Yes, yes... that's I'm searching for! And now I found it. It was hidden in the Hide Advanced Options which I could not find at all. The button `Hide Advanced Options` is not much easy to find.

Many thx! :]

**Comment by waldauf** [comment]
I checked it and tried it on this WEB (https://redux-form.com/6.7.0/docs/api/actioncreators.md/) and when I type `f` so the `scroll: ` option is not displayed.

**Comment by smblott-github** [comment]
Yes.  We're not able to detect all scrollable elements (just like we don't detect all clickable elements).

**Comment by waldauf** [comment]
Okey, now I understand. Thank you again for your answer.

**Comment by ryanhaining** [comment]
> The button `Hide Advanced Options` is not much easy to find.

took me a while to notice the `Show Advanced Options` button all the way at the bottom too

**Comment by aoot** [comment]
> I checked it and tried it on this WEB (https://redux-form.com/6.7.0/docs/api/actioncreators.md/) and when I type `f` so the `scroll: ` option is not displayed.

> Yes. We're not able to detect all scrollable elements (just like we don't detect all clickable elements).

Is there a reason that [this](https://github.com/philc/vimium/issues/2359#issuecomment-302864525) screenshot is able to detect the scroll bar, whereas I'm facing the same issue as @waldauf of not able to detect the scroll bar?

**Comment by gdh1995** [comment]
I agree with https://github.com/philc/vimium/issues/2372#issuecomment-841936399 - marking hints differently (like another color for scrollable elements) is very useful .

And as said in https://github.com/philc/vimium/issues/3134#issuecomment-1049531404, in Vimium, currently only clicking an element can notify Vimium it's scrollable, although this notifying can be easily imported into `LinkHints.activateMode` with `action=hover` (which means to "select" an element without clicking).

I have a customized version of Vimium, named `Vimium C` (https://github.com/gdh1995/vimium-c), and it have such features:
1. Its `LinkHints.activateHover` will auto mark an element (or an outer element) scrollable, and then `j` and `k` work.
2. Render hint markers for scrollable areas in **dark red**
- 1. an edge case is, when a scrollable area is also "clickable", its marker won't be dark red, but this should have little impact
