### ISSUE TITLE
Firefox 65: Scrolling is unreliable with smooth scroll disabled

### ISSUE THREAD

**Issue by progandy** [philc/vimium#3235]
Until Firefox 64.0.2 everything worked fine with smooth scrolling disabled. Since FF65, it has become unreliable. Sometimes it seems to work fine, and then suddenly some or all of this happens:

* half page scrolling scrolls just far enough to scroll past the first visible element.
    (at the very top of the page, scroll half down, half up, half down; repeat until it happens)
* when changing the scroll direction, the first key is ignored and has to be repeated
* the scroll distance is doubled
* A random scroll keypress is ignored.
* A scroll keypress repeats the previous scroll action instead or in addition to the desired action.

I think most can be somehow explained as some sort of combination with the previous scroll event, ~~but sometimes I get double distance scrolls directly after a direction change or ignored keys even though I just used the same scroll action.~~ (Can't reproduce that, maybe I imagined it)

I have smooth scrolling disabled, enabling it is not a solution since it makes me nauseous.

I could reproduce it in a new profile with just vimium installed. I think it happens on all webpages, but just in case one URL I tested: https://www.archlinux.org/

**Comment by juhovi** [comment]
I've also ran into this, or at least I'm fairly sure it's the same problem. Most noticable symptom is that when changing scrolling direction the first keypress is ignored, like @progandy wrote above. I have noticed the issue on every web page I've visited, including Github. 

I haven't noticed any difference whether smooth scroll is enabled or disabled. However, disabling multiprocess Firefox by setting _browser.tabs.remote.autostart_ to _false_ does seem to work around the problem.

I use and see the issue on both Firefox 65.0 release and 66.0b6 beta. Both are 64-bit builds, running on fully updated Windows 10 1809. Normally vimium isn't the only extension I use, but the issue appears even on a fresh profile with only vimium installed.

**Comment by gdh1995** [comment]
Confirmed.

The `browser.tabs.remote.autostart` in "about:config" does have influence on scrolling.

The line
> when changing the scroll direction, the first key is ignored and has to be repeated

requires a tester only presses "j" only once to scroll down and then presses "k" to scroll up - if "j" is pressed twice, then "k" works as expected.

Thereforce, it seems a bug of keydown/keyup events.

**Comment by juhovi** [comment]
I don't know which Firefox (or Vimium) version fixed this and how, but I don't have this problem any more.
Firefox 71.0, Vimium 1.64.6. _browser.tabs.remote.autostart_ is set to _true_ (which is the default, I believe)

**Comment by progandy** [comment]
It seems to be working for me as well now, I guess I'll close the issue.

I learned to ignore it and somehow never noticed that it was fixed.
