### ISSUE TITLE
Overlapping icons in Gmail

### ISSUE THREAD

**Issue by orschiro** [philc/vimium#3236]
Sometimes I am having troubles clicking the right keyboard combination because several icons are overlapping. 

Does someone else have a similar issue with the latest Gmail design?

![image](https://user-images.githubusercontent.com/170947/52161255-d32d8f00-26c2-11e9-9c04-0af5d3ec2680.png)

**Comment by innaterebel** [comment]
This happens on modern glorified pages easily and is hard to root out.
As a workaround, <kbd>Space</kbd> can rotate the layers of overlapped hints.

**Comment by orschiro** [comment]
Thanks for the tip!

I found another workaround. Switch from icon labels to text labels in the settings. :-)

Makes the whole thing a bit wider. 

![image](https://user-images.githubusercontent.com/170947/52192589-203c6d00-284b-11e9-8a1a-4021591d7ef4.png)
