### ISSUE TITLE
Feature request: move tab to the far end

### ISSUE THREAD

**Issue by orschiro** [philc/vimium#3241]
Hi all,

`>>` can move the current tab one to the right. This is great!

Would it be possible to add another similar shortcut that can move the tab to the far end?

That would be a great enhancement. 🤗

**Comment by smblott-github** [comment]
Try `99>>`.

Or...

    map X moveTabRight count=9999999

**Comment by orschiro** [comment]
`99>>` works great! Thanks. ❤
