### ISSUE TITLE
Focus switches randanly after using Vomnibar.activateInNewTab command in chrome 72.

### ISSUE THREAD

**Issue by terrell032** [philc/vimium#3242]
Issue appears on windows 10 64 bit chrome version 72.0.3626.96.
Previous version 71.0.3578.80 is OK.
After openning new tab through vomnibar, focus mostly stays on current tab, but also switch to the newly opened tab sometimes like previous version always do.

**Comment by gabrielcerteza** [comment]
I'm getting the same issue on Chrome Version 72.0.3626.96 (Official Build) (64-bit), macOS Mojave 10.14.3

**Comment by baotiao** [comment]
I'm getting the same issue on Chrome Version 72.0 macos Majave

**Comment by terrell032** [comment]
@gdh1995   @smblott-github 
Thanks!  Happy to see this issue fixed.
But... I just noticed that the dates in release notes are incorrect...
Finally, I can have my chrome up to date...
