### ISSUE TITLE
[Chrome]: Can't install extensions from the Chrome webstore

### ISSUE THREAD

**Issue by khoitd1997** [philc/vimium#3247]
When trying to install the extension today from the Chrome webstore I got the error of:

```
Package is invalid. Details: 'Could not load javascript 'lib/utils.js' for content script.'.
```

I think this is a recent issue because I tried a couple days ago and the extension installed fine. I also tested this issue on both Linux and Window and both show the same error. I'm on Chrome Version 72.0.3626.109. The vimium version would be 1.64.4.

**Comment by smblott-github** [comment]
Yikes!  It seems the 1.64.4 ZIP file I uploaded earlier was missing the JS files.

1.64.5 (pushed just now) will fix this.  Will take an hour or so to propagate.

**Comment by khoitd1997** [comment]
Confirmed installation works! Thank you for the quick response and keep up the good work.
