### ISSUE TITLE
Problems cycling through frames on some sites, like Oracle's javadocs

### ISSUE THREAD

**Issue by niemand** [philc/vimium#325]
I've noticed that on several websites, including http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.help.ase_15.0.utility/html/utility/utility86.htm, I can successfully focus into some of the other frames with <gf>, but that I can't focus on all of the frames, let alone cycle through them. Accordingly, I change two or three frames and then get stuck. To change to the frame I want I have to manually click on it with my mouse--which unfortunately defeats the purpose of keyboard navigation...

**Comment by smblott-github** [comment]
Think this looks to be fixed.
