### ISSUE TITLE
Installed but nothing happen when I press keys

### ISSUE THREAD

**Issue by MrMic** [philc/vimium#3258]
Hello,

After installation on Chrome, when I press key(s) , nothing happen.
When I press "f" for example, the scroll bar is highlighted, but nothing move  ...
Any idea what happen ?

Thanks for the reply.
Rgds,

**Comment by zurbrugc** [comment]
What website are you trying this on? The extension does not work on Chrome Store pages for security reasons.

**Comment by MrMic** [comment]
OK  it is working now.
