### ISSUE TITLE
URL copy/paste and Find mode focus issues in latest Chrome builds

### ISSUE THREAD

**Issue by innaterebel** [philc/vimium#3260]
Derived from #2833 now that Chrome also seems to have received bizzare changes in this area. (mainly [this](https://github.com/philc/vimium/issues/2833#issuecomment-464462596) comment)
I have waited four Dev releases (once a week) to conclude these regressions are likely to stick, so contributors may want to examine them early before they eventually reach Stable.

There are at least three issues emerged together in Chrome 74:
1. When `Find` is initiated, the HUD gets no focus. You have to click in it to start inputting.
2. `yy` is broken, fails to copy anything, despite the HUD says it succeeded.
3. `p` sends empty string instead of the string/URL copied in clipboard, resulting in default search engine being opened with no query. 

3 is tricky to reproduce, it most likely to repro when you don't `p` immediately after copy a link, e.g. copy a link via `yf`, scroll around to read the rest of page, then `p`.
If you `p` right after `yf` without any operation in between, the pasting will succeed.

**Comment by gdh1995** [comment]
All 3 points confirmed. I'll take a try in the next weekend / week.

**Comment by innaterebel** [comment]
Chrome 74 has entered beta phase without anything changed (if not worse. Now I am getting occasions even `yf` fails, not reproducible though), these are definitely going into stable.

**Comment by innaterebel** [comment]
@smblott-github Chromium M74 has just reached Chrome stable.

**Comment by alanhg** [comment]
how to solve it?downgrade chrome?

**Comment by gdh1995** [comment]
@alanhg There has been a PR to fix it, and just need to wait it to be merged .

**Comment by gdh1995** [comment]
@alanhg There has been a PR to fix it, and just need to wait it to be merged .
