### ISSUE TITLE
Can't focus on the login inputs for chase.com (anymore)

### ISSUE THREAD

**Issue by shammellee** [philc/vimium#3263]
I used to be able to focus on the login input fields for chase.com with `gi` but it stopped working a few months ago. I'm guessing Chase changed something.

**Comment by smblott-github** [comment]
Are you talking about the username/password inputs.

The problem seems to be that these inputs are in a separate iframe (and `gi` doesn't work across iframes).

Two workarounds...

- `gf` followed by `gi` seems to work
- link hints work across iframes, so `f` can be used to select the input

**Comment by shammellee** [comment]
@smblott-github both great workarounds! Thanks!
