### ISSUE TITLE
FF: vomnibar broken since firefox 65

### ISSUE THREAD

**Issue by Wonko7** [philc/vimium#3275]
Hi all,

I've been using vimium & the vomnibar without issues for a long time (probably since firefox made the switch to webextensions).
In firefox 65 & 66 `Vomnibar.activateTabSelection` is broken:
On first invocation it shows a list of tabs, but doesn't update on text input. On later invocations the tab list is empty, only the search text input is visible, and nothing happens on text input. 

Has anybody found a workaround? I've got too many open tabs to manually scroll through :P 

Thanks

**Comment by gdh1995** [comment]
* Maybe related with #3234 
* I can not reproduce this issue on my Win 10, Firefox 66.0.0.7012 x64
  * tested Vimium v1.64.3 and master (v1.64.5)
* could you provide more information about your Firefox's version and configurations?

**Comment by Wonko7** [comment]
yep, it was #3234, firefox is custom build (gentoo). But my bug disappeared with firefox 67.
