### ISSUE TITLE
When selecting multiple tabs, one "x" just closes the current tab. Should close all selected tabs.

### ISSUE THREAD

**Issue by fakeinc** [philc/vimium#3283]
Chrome version: Google Chrome | 73.0.3683.86 (Official Build) (64-bit) (cohort: Stable)
Vimium version: 1.64.5

For example, in Chrome, "Ctrl + W" will close all selected tabs. So I'd expect a similar behavior when using Vimium's "x".
If this is a feature, i'd like to see an option for "close all selected tabs instead of the current active one". Thanks.

**Comment by gdh1995** [comment]
Um, how do you select multiple tabs only using a keyboard? If you're using a mouse, then I think it's easy enough to use "Ctrl+W" to close those tabs.

**Comment by fakeinc** [comment]
Thank you for the reply. I'm using a mouse to do that, but I'm planning to make a Chrome extension which enables me to do that with only keyboard. So I think a single "x" is better than "Ctrl + W". Thank you.

**Comment by gdh1995** [comment]
In fact, up to now no commands in Vimium (which are related to tabs) care about the "highlighted" tab status, so it will be very hard to add support for it.

The "multi-highlighted" status is easy to lose - if only you go to another tab, all highlighted tabs lose their status. Maybe this is one possible reason why we haven't use the status.

If you need to close multiple near tabs, press a number before "x" is enough (e.g. <kbd>5x</kbd> closes 5 neighboring tabs).

If the tabs you want to close do scatter, I prefer a way to close them by pressing <kbd>Shift+Delete</kbd> on selected tab item, on Vomnibar with the "TabSelection" mode. Here's a discussion about it: #3170.

**Comment by fakeinc** [comment]
Thank you. I'll use another solution instead.
