### ISSUE TITLE
fishshell.com partial functionality

### ISSUE THREAD

**Issue by deanmaniatis** [philc/vimium#3287]
Hello,
I've been visiting http://fishshell.com/docs/current/index.html and vimium scrolling doesn't seem to be working with Firefox. The site seems to have two frames, a side menu and a main one. By default only side menu is chosen (which scrolling works) but any attempt to switch to main with `gf`or mouse tapping does not seem to be working.

**Comment by gdh1995** [comment]
They're not frames but just `<div>`s, so on my Chrome 73 x64, Win 10, mouse clicking makes Vimium scroll the main area.

**Comment by deanmaniatis** [comment]
Yeap, i just checked and indeed it works with Chrome but not with Firefox. Could it be the Firefox extension then that bugs out ?

**Comment by gdh1995** [comment]
It's because Vimium's logic to find a "scrollable" element relies on the "DOMActivate" browser event, which only exists on Chrome, but not on Firefox / MS Edge.

This is easy to fix by checking `Utils.isFirefox` before listening `DOMActivate`.
