### ISSUE TITLE
`map ь Marks.activateCreateMode` overrides "Open link in current tab"

### ISSUE THREAD

**Issue by lolmaus** [philc/vimium#3289]
Hi!

I'm using the official [Russian mapping](https://github.com/philc/vimium/wiki/Key-Mappings#russian-language-keyboards), it has the following entry:

    map  ь Marks.activateCreateMode

`ь` shares the key with `m`: <kbd>m/ь</kbd>.

When I use <kbd>f</kbd> to open a link, and the link label contains `m`, I'm unable to activate it with a Russian layout because when I press <kbd>m/ь</kbd>, the `Marks.activateCreateMode` command is triggered and link opening is cancelled.

I believe this is a bug in Vimium: when in link opening mode, keys should activate labels and not custom actions.

**Comment by smblott-github** [comment]
Have you tried changing the link-hint characters to Russian characters on the options page...?

![image](https://user-images.githubusercontent.com/2641335/55705327-74dc9f80-59d6-11e9-8f5b-98c378d4cd31.png)

**Comment by lolmaus** [comment]
@smblott-github When I do that, English labels get mixed with Russian ones. So I have to switch the layout in order to reach certain links.

My goal is to open links without having to be aware which layout is current.

***

I've just realized that in Russian layout link following is not working at all. Keys are not recognized.

Was it always like this? I'm surprised, I believe I had been using Russian layout to open links, but I'm not certain.

**Comment by lydell** [comment]
If you go to the options page, press "Show Advanced Options", check "Ignore keyboard layout" and remove the Russian mappings – do things work better then, by any chance?

**Comment by lolmaus** [comment]
@lydell It does work for Vimium shortcuts but not for labels in link opening mode.

**Comment by lolmaus** [comment]
Ah wait, I forgot to save. It works!

Thank you, @lydell.
