### ISSUE TITLE
Overrides Key-mapping of FastMail

### ISSUE THREAD

**Issue by cooperpellaton** [philc/vimium#3290]
FastMail provides a default key-mapping for interfacing with emails in the form `.x` where x can be `r, u, ...` and allows you to make an email as read, unread, move to folder, etc. When using Vimium on FastMail these commands are over-ridden and pressing `.r` will cause the page to reload. I believe that Vimium should be aware of the modifier and delegate to the page mapping rather than the global key-mapping.

**Comment by gdh1995** [comment]
Um, the "Excluded URLs and keys" on Vimium Options page should help.
