### ISSUE TITLE
support case-sensitive search

### ISSUE THREAD

**Issue by nosarthur** [philc/vimium#3291]
Right now `/Abc` could match `/abc` as well. I tried `/\CAbc` and it didn't work as expected. Is it possible to support `\C` for searching? Or maybe there is some other way around?

**Comment by gdh1995** [comment]
It's strange. When I tested today, "Abc" will only match "Abc", but neither "abc"  nor "aBc" (Vimium 1.64.5, Chrome 73 x64 for Windows).

According to the source code, if Vimium finds upper-case characters, it will set "ignoreCase = false" on finding.

**Comment by nosarthur** [comment]
On my chromebook, it indeed behaves as what you described. I recall the problem is in the mac in my office. I will confirm later

**Comment by nosarthur** [comment]
I cannot reproduce it. Must be my own error. Sorry for the false alarm
