### ISSUE TITLE
Find mode doesn't receive focus in brave

### ISSUE THREAD

**Issue by patosullivan** [philc/vimium#3292]
Hi, I've noticed in the last few weeks that when I try to use find mode (`/`) in Brave it doesn't actually receive focus automatically. If I want to use Vimium's find mode I have to manually select it with my mouse after it appears on the screen.

Brave build information:
Version 0.63.40 Chromium: 74.0.3729.61 (Official Build).

The same problem is occurring in both Windows and Linux. Chromium in both OSes still works fine.

Let me know if you need any other troubleshooting information.

**Comment by innaterebel** [comment]
So Chromium M74 have entered mass release at some place, @smblott-github.
This is #3260. It shall be fixed by the stable release of Chrome 74 itself at the latest. (An unwritten policy of Vimium is to not deal with not-stable releases as things are subject to change, and Chromium M74 is officially still in Beta, so sorry for the extra wait)

**Comment by eromoe** [comment]
`/` still doesn't work on  74.0.3729.10

**Comment by Beasta** [comment]
this is currently fixed in the stabel brave
Version 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)

still broken in brave-dev
Version 0.65.78 Chromium: 74.0.3729.108 (Official Build) dev (64-bit)

**Comment by jobor** [comment]
I can reproduce this issue with Chrome 74.0.3729.131 (Official Build) (64-bit) on Linux.

**Comment by eromoe** [comment]
Yeah, Chrome  74.0.3729.131  windows 10  is still broken

**Comment by BrianRamsay** [comment]
I also can reproduce this with Chrome official on Linux

**Comment by benjaminedwardwebb** [comment]
Reproduced with
Chrome Version 74.0.3729.131 (Official Build) (64-bit)
macOS Mojave Version 10.14.4
