### ISSUE TITLE
j and k scrolling doesn't work on reddit

### ISSUE THREAD

**Issue by sooriravindra** [philc/vimium#3295]
Google Chrome : 73.0.3683.103 (Official Build) (64-bit) (cohort: Stable)
OS : Windows 10 OS Build 17134.706

Scrolling on reddit posts doesn't work as expected. j and k scroll the background instead of the pop up post. There seems to be a PR #3119  already merged for this issue before. Seems to be a regression.

**Comment by philc** [comment]
This should be fixed by #3327.
