### ISSUE TITLE
[Chrome] yy not yanking current URL

### ISSUE THREAD

**Issue by degill** [philc/vimium#3297]
Chrome Version: Version 74.0.3729.108 (Official Build) beta (64-bit)
OS Version: MacOS 10.14.4 (18E226)
Vimium Version: 1.64.5

A couple of days ago I noticed that `yy` does not seem to work anymore. I still get the little bottom-right toast saying the URL has been yanked, but CMD+v still pastes the old clipboard content.

Same behaviour in incognito mode.

**Comment by XOKP** [comment]
I have the exactly same issue...

**Comment by andrewwxy** [comment]
I have the same issue as well...

This broke the same time as #3307 , search mode stopped working.

**Comment by Beasta** [comment]
also currently broken in brave
Version 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)

**Comment by JohnTravolski** [comment]
Also broken in Google Chrome:
Version 74.0.3729.131 (Official Build) (64-bit)

Is there any known fix yet?
