### ISSUE TITLE
[Chromium] / to search doesn't actually select the text box for you to type in

### ISSUE THREAD

**Issue by kohotli** [philc/vimium#3298]
Chromium | 74.0.3729.108 (Official Build) Arch Linux (64-bit)
Vimium version 1.64.5

https://i.imgur.com/uyApM4Q.png <- this is what it looks like for me at the moment.
Intended behavior: Pressing / automatically selects the textbox so you can immediately start typing to find text.
Currently, it doesn't do this. If I try to type immediately after pressing /, nothing happens. The only way to make the search work properly is to click on the box after it comes up, which seems to defeat the purpose.

**Comment by sooriravindra** [comment]
Similar behavior on Windows 10 Google Chrome Version 74.0.3729.108 (Official Build) (64-bit)

I think the latest chrome update broke it

**Comment by zdzolton** [comment]
I have this problem on macOS 10.12.6 with Chrome 74.0.3729.108 (Official Build) (64-bit) as well.
