### ISSUE TITLE
`/` search window not getting focus 

### ISSUE THREAD

**Issue by etmoore** [philc/vimium#3302]
Pressing `/` activates search, but it doesn't have the cursor's focus.
![image](https://user-images.githubusercontent.com/3310531/56815439-6207fe80-680f-11e9-8014-56ebf58b6d41.png)
I have to click on it before I can start typing. Seems like it started happening when chrome updated to v74. 

Google Chrome 74.0.3729.108 (Official Build) (64-bit)
Revision: daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS: Mac OS X

Vimium Version
1.64.5

**Comment by riftEmber** [comment]
Same issue on chrome Chromium 74.0.3729.108, Arch Linux, vimium 1.64.5. Never used vimium before chromium v74 so I have no comparison to previous.

**Comment by jcamp748** [comment]
same issue Google Chrome 74.0.3729.108 on Ubuntu 18.04

**Comment by hexxxx** [comment]
Same issue with search bar, also 'yy' to yank sometimes works, sometimes doesn't. Mashing 'yy' over and over can get text onto my clipboard, but not necessarily consistently. 

Google Chrome: 74.0.3729.108 (Official Build) beta (64-bit) (cohort: Beta)
Revision: daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS: Windows 10 OS Build 17134.706

Vimium Version: 1.64.5

**Comment by jdhao** [comment]
Same issue after updating Chrome to v74 on Windows 10.

**Comment by nncy** [comment]
Same issue on me 
Chrome v74.0.3729.108
OS:WIN 10 v1803
Vimium Version:version 1.64.5

**Comment by FirasSadiyah** [comment]
Same here: Version 74.0.3729.108 (Official Build) Arch Linux (64-bit)

**Comment by dsifford** [comment]
Dupe of #3298

**Comment by etmoore** [comment]
☝ closing since this is a duplicate of #3298 . thanks @dsifford ++
