### ISSUE TITLE
search mode stopped working

### ISSUE THREAD

**Issue by rdbox** [philc/vimium#3307]
focus in search mode does not work
**Chrome:** 74.0.3729.108
**Vimium:**  1.64.5
**GIF:** 

![0197](https://user-images.githubusercontent.com/18515862/56930372-1c845380-6ae5-11e9-9ce3-5b359d735c65.gif)

I did not notice this before, I can press the key ```/```
and everything worked fine.
maybe something I am doing so?
Or new changes appeared in the browser.

**Comment by smk291** [comment]
Same version of Chrome and Vimium, same problem. I just tested the behavior, saw that search focus worked as expected, upgraded my chrome from latest 73 to latest 74 (same as rdbox), and then discovered the focus no longer worked.

**Comment by smk291** [comment]
I just made a PR, which appears to fix the problem. Reusing the setTimeout fix from dc2bff8 fixed the behavior.

**Comment by rdbox** [comment]
@smk291 how soon will work? or do i need to update my vimium?

**Comment by andrewwxy** [comment]
> Same version of Chrome and Vimium, same problem. I just tested the behavior, saw that search focus worked as expected, upgraded my chrome from latest 73 to latest 74 (same as rdbox), and then discovered the focus no longer worked.

Same Chrome 74 update issue

**Comment by jhshi** [comment]
Same here. How do I upgrade Viminum the latest master?

**Comment by smk291** [comment]
The latest vimium master doesn't include this fix. Currently, if you want my particular fix (or the one in pull request #3277), you'll need to clone my repository, switch to the branch search-mode-stopped-working, build, and then load the unpacked extension. The readme provides instructions.

**Comment by gdh1995** [comment]
(Just an AD:) I'm writing my customized version of Vimium and it's in https://github.com/gdh1995/vimium-c . It includes many new commands and options (though lacking documents~) and performance improvements, and, has no such bug.

**Comment by rdbox** [comment]
@gdh1995 
Are there no backdoors in your build that control users?
I am already very demanding about browser applications.

**Comment by smk291** [comment]
@gdh1995, when you say C-style code, what do you mean?

**Comment by gdh1995** [comment]
@rdbox No, there's no damaging code. It's open sourced and has a very strong self restriction.

* It gives up the extension's Internet permission (by [`connect-src 'self' data:`](https://github.com/gdh1995/vimium-c/blob/master/manifest.json#L65) in [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)) to keep all your information local.
  * As a side effect, it does not support Vimium's query completion feature (which needs to send requests to Google, Youtube, Bing and so on).
* And you can even disable the Chrome's user settings syncing of Vimium C
* Here's its PRIVACY POLICY: https://github.com/gdh1995/vimium-c/blob/master/PRIVACY-POLICY.md

@smk291 The "C" in its name means "full-featured **C**hinese (CJK) support, global **C**ommands and inje**c**tion functionality, in **C**-style code for better speed and less resource **c**ost."

Vimium C uses less event listeners, shorter code (than this Vimium) and many lazy loading / cache techniques to run fastly and cost little.

**Comment by smk291** [comment]
@gdh1995 @rdbox I need to dig into the code a bit more, but I like what I've read so far. (And I don't see anything that looks remotely like a backdoor.) I'll take a closer look tomorrow :)

**Comment by rdbox** [comment]
@smk291 
 
thank you it's nice it calms me down
Build vimium is a great idea to work with the browser. I'm 30% faster work.
Thanks to the developers.

**Comment by smk291** [comment]
@gdh1995, I just tried vimium-c. On the first page I tried, when I pressed f, vimium-c missed a large number of links/buttons and seems not to have detected anything in the div that contained more of the page's content. I was using Canvas LMS's speedgrader.
