### ISSUE TITLE
Copy Link Not Working

### ISSUE THREAD

**Issue by davidmanjarrez** [philc/vimium#3310]
I may very well be doing this wrong, but I can't get yf to work.

**Comment by dubiousdavid** [comment]
`yy` is not putting the URL in the clipboard for me anymore :( I keep pasting random clipboard stuff in Slack instead of URLs :)

**Comment by davidmanjarrez** [comment]
This was, as I expected, user error. I made an unrelated change to my Vimium settings and neglected to reload the page. I typed out my comment, figured out what I had done wrong, and thought I had cancelled before posting, so I'm closing it out now.

**Comment by gdh1995** [comment]
Maybe related with #3260, which is because of inner changes of Chromium 74.
