### ISSUE TITLE
unable to input in find mode 

### ISSUE THREAD

**Issue by cslxiao** [philc/vimium#3315]
I enter the find mode by pressing `/`, but I cannot input the keyword unless I click in the edit box with the mouse. Is that normal?

**Comment by gdh1995** [comment]
It's because of an inner change of Chrome 74.

Duplicate of #3260.

**Comment by shammellee** [comment]
I found a less-than-ideal way around this:
1. Press `n` or `N` (highlight next or previous match)
2. Press `/`
3. Search normally
