### ISSUE TITLE
Pressing media key play/pause scrolls to top of the page

### ISSUE THREAD

**Issue by spamdr** [philc/vimium#3317]
When I press play/pause media key. Current page scrolls up to the top. 
It scroll only during pause not unpause. 
I could not find any settings which would prevent this in config.
It does not happen when i disable Vimium on that page.

**Comment by spamdr** [comment]
Anybody has idea how to prevent this from happening?

**Comment by gdh1995** [comment]
Can not find the reason directly. Please open http://gdh1995.cn/vimium-c/keyboard-test.html, turn off Vimium on it and reload page, and then press play/pause media keys to see what it will record.

**Comment by spamdr** [comment]
Hello sorry it took so long, it recorded this when I pressed it twice:

  | Event | Code | Key | Modifiers | KeyCode (legacy)
-- | -- | -- | -- | -- | --
1 | keydown | KeyG | MediaPlayPause |   | 179
2 | keyup | KeyG | MediaPlayPause |   | 179
3 | keydown | KeyG | MediaPlayPause |   | 179
4 | keyup | KeyG | MediaPlayPause |   | 179

**Comment by gdh1995** [comment]
It's because of the `Code: KeyG`: on every pause key, Vimium gets a `g`, and on the second the key sequence becomes `gg`, so it triggers `scrollToTop`.

You need to uncheck the option of "This forces the use of en-US QWERTY layout and can be helpful for non-Latin keyboards.", to let Vimium not use `keyboardevent.code`

**Comment by spamdr** [comment]
I see, thanks it worked.

**Comment by gdh1995** [comment]
I got an idea to fix this mismatch when keeping "QWERTY layout" enabled, so could you do me a favor and test such zip files?

I have a customized version of Vimium, named Vimium C, and I've compiled its https://github.com/gdh1995/vimium-c/commit/2f3d2552505b2a40cabe54e114f6f4635f8d768a and got 2 zip files: [vimium_c-1.86.2-chrome-2f3d255.zip](https://github.com/philc/vimium/files/5395882/vimium_c-1.86.2-chrome-2f3d255.zip), [vimium_c-1.86.2-firefox-2f3d255.zip](https://github.com/philc/vimium/files/5395883/vimium_c-1.86.2-firefox-2f3d255.zip). You may installed such a zip on `chrome://extensions` and then test your pause/resume keys on its option page, and here's a tutorial: https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package .

**Comment by spamdr** [comment]
Ok it works correctly for me with the Vimium C both in chrome and firefox
