### ISSUE TITLE
Getting out of form field

### ISSUE THREAD

**Issue by Mithrandir2k18** [philc/vimium#3320]
Getting out of "insert mode" when inside a form field doesn't always work. It works great here on github as I just found out but on web.whatsapp.com I cannot ESC out of the input fields.

I am using Firefox.

**Comment by DasHasan** [comment]
There's been an issue with whatsapp web for a while now. For now you need to press tab once or twice to get out of the input field and then you can start using the keys again

**Comment by Mithrandir2k18** [comment]
Yeah, I have just CTRL+TABbed out of it for the meantime. Not too big of a deal, but a nice to have for sure.
