### ISSUE TITLE
Request: Respecting named bookmarks and bookmark searches when opening tabs

### ISSUE THREAD

**Issue by Mithrandir2k18** [philc/vimium#3321]
So I have multiple searches bookmarked, e.g. if I type "wikien" in my url/searchbar my seach gets redirected to the english wikipedia, same for some others like "amazon" etc..

However when I open a tab with "o" or "O" the search is always redirected to my default web search engine. Would it be possible to search for matches in bookmarked searches and only upon no match use the default search engine?

**Comment by gdh1995** [comment]
Vimium can not access the custom search engines on chrome://settings/searchEngines, so you need to add those by yourself to the "Custom search engines" textbox on Vimium's options page.

And then you may use "w query..." to search in Wiki and "g query..." to search in Google.

**Comment by Mithrandir2k18** [comment]
Sorry I should note that I am using Firefox.

**Comment by gdh1995** [comment]
Nothing different - Vimium can not access those search engines of Firefox. So please take a try to configure them on Vimium's options page.
