### ISSUE TITLE
open link in current tab and new tab shortcut is flipped

### ISSUE THREAD

**Issue by jfyu** [philc/vimium#3329]
in the hint and readme, `f` is mapped to `open link in current tab` while `F` is mapped to `open link in new tab`. On my Mac (Mojave) this is flipped. So I explicitly went into the options and mapped them back. Turns out that the LinkHints do exactly the opposite of what they are supposed to do. The following mapping works as intended from the README (and pressing `?`)

I think the small ask is to either fix the mapping, or fix the README. Just to avoid the 5 minutes of confusion. 

```
map F LinkHints.activateMode
map f LinkHints.activateModeToOpenInNewTab
```

**Comment by gdh1995** [comment]
Normally, the `f` is `LinkHints.activateMode`, so I wonder if your "Caps Lock" is on.

If it's off and the `f` means always InNewTab on your Mac, then it may be a bug of Vimium about key 
events translation.

**Comment by jfyu** [comment]
yeah I found that interesting because the options seem to say exactly the opposite of what it does. I double checked though my cap lock is not on. Maybe Mac specific issue? Has anyone else been able to reproduce this?

**Comment by jfyu** [comment]
I found out the cause!!! Apparently when I type `f`, all the links show up in caps as `AA` for example. Then I just automatically reach for the `SHIFT` key, which ended up opening in a new tab. if I just type the link hint in lower case, it works as intended. I will close this issue now, but hopefully this serves as good docs for people searching for this

**Comment by nathgit** [comment]
I had the same issue, but @jfyu's last comment was the fix. It's confusing to have them all in caps because I assumed I should type capital letters to open the appropriate link.

**Comment by rddunphy** [comment]
This behaviour really confused me! Even now that I know how it works, I have to fight the urge to type the link reference in caps, as they're displayed on the screen.
