### ISSUE TITLE
'f' doesn't work in Brave

### ISSUE THREAD

**Issue by rvarbanov** [philc/vimium#3331]
The extension is working as expected in Chrome but in Brave you can't see the yellow boxes with the letters in them. If you press random letters the extension will "click" on the links and load the new pages, but you can't see the letter boxes.

The best way to reproduce this issue would be to open Brave, go to a google result page and press `f`.

You will see the message `Open link in current tab` in the lower right corner, but not the yellow boxes with letter.

Thank you for looking into that issue.

**Comment by rvarbanov** [comment]
I just found that it's a Brave issue. 

```css
tml > div ~ div:last-of-type {
    display: none !important;
}
```
That's hiding the `vimiumHintMarkerContainer`. I will post at the Brave support forum.

**Comment by ftmmohd2000** [comment]
Does this work now?

**Comment by rvarbanov** [comment]
Yes, I don't have that issue anymore.

**Comment by ihgann** [comment]
It appears this has started happening again.

**Comment by ihgann** [comment]
I've started to see this relatively frequently again. Any chance this is happening again / how we might be able to verify?

**Comment by rvarbanov** [comment]
I'm running vimium 1.66 and brave 1.24.82 and have no issues.
