### ISSUE TITLE
Multi word search terms in search query

### ISSUE THREAD

**Issue by pratyushtewari** [philc/vimium#3332]
I want to create a custom search query with multiple words from the search term, split and put  into different sections of the search query.
For example:
I want to search `FIRST LAST` and the url is like this
`https://url.com/?req=search&searchItem1=FIRST&searchItem2=LAST`

How can I achieve this? 

I was looking into this at [createSearchUrl](https://github.com/philc/vimium/blob/f2ab8bee6e1fa8d9b34837c934e6b8ec0cb7abc9/lib/utils.coffee#L133) method but the only way it does is merge the multiple words with a `+` sign into one search term.

I think this will a great addition to vinium, although very unique feature but great nonetheless.

**Comment by gdh1995** [comment]
Just an AD: I have a customized version of Vimium - [Vimium C](https://github.com/gdh1995/vimium-c), and it supports very complicated search engines and some advanced usages. With it, an example of search engine rules looks like:
```
# if only two words
keyword1: https://url.com/?req=search&searchItem1=$s{$1}&searchItem2=$s{$2}
# if the first and the last
keyword2|alias2: https://url.com/?req=search&searchItem1=$s{$1}&searchItem2=$s{$-1}
# if the first, and all others
key3\:|alias3|Name3: https://url.com/?req=search&searchItem1=$s{$1}&searchItem2=$s{$+2}
```

Document: https://github.com/gdh1995/vimium-c/wiki/Search-engine-rules#url-pattern .

**Comment by pratyushtewari** [comment]
Thanks @gdh1995 this is what I was looking for. How can I get this onto firefox?
Maybe you can send a PR it to @philc to merge it to the main Vimium repo and everyone can benifit.
