### ISSUE TITLE
[Feature Request] Be able to arrange tab order

### ISSUE THREAD

**Issue by hulucc** [philc/vimium#3335]

**Comment by gdh1995** [comment]
There're some commands: `moveTabLeft`, `moveTabRight` and `moveTabToNewWindow`.

**Comment by hulucc** [comment]
Oh, I see. It's documented in advanced commands.
Thanks.
![image](https://user-images.githubusercontent.com/4343900/58457451-533ba100-8159-11e9-96cb-72fe1237d0ae.png)
