### ISSUE TITLE
vomnibar to show last X(20) history in the current page

### ISSUE THREAD

**Issue by jefferyyuan** [philc/vimium#3338]
- vomnibar to show last X(20) history in the current page
- So the user can easily go check the history and go to the specific one.
Thanks

**Comment by gdh1995** [comment]
No, Vimium can't. Currently there's no API for extensions to access a tab's history on browsers including Chrome and Firefox.

**Comment by jefferyyuan** [comment]
- that makes sense: due to privacy concern.
- close the issue and thanks.
