### ISSUE TITLE
Feature request: allow the user to specify a list of sites on which to default to insert mode

### ISSUE THREAD

**Issue by jk5228** [philc/vimium#3341]
For a given url Vimium users currently have two options:

1. Allow Vimium entirely.
2. Disallow Vimium wholly or partially (key by key) using the "Excluded URLs and keys" list.

I have added many sites to category (2) because I'm already accustomed to using the site's own keyboard bindings (e.g., Gmail) and don't want to remember to hit "i" before using the site's keybindings. However, in many cases I would like to default to the site's own keyboard bindings while using Vimium keybindings as a fallback.

In essence, Vimium allows users to use vim-like keybindings to perform actions and uses insert mode to support fallback to the site's keybindings. This feature would simply support the converse: default to the site's own keyboard bindings while using Vimium keybindings as a fallback.

I think the most straightforward implementation would consist of another URL list in "Vimium Options" that would be interpreted in the way I described above.

I'd be happy to put up a PR for this if this sounds like a reasonable feature request.

**Comment by gdh1995** [comment]
The idea in https://github.com/philc/vimium/issues/3272#issuecomment-475296695 might be helpful. Other ideas are also welcomed.

**Comment by jk5228** [comment]
Ah, thanks. I'm going to close this issue as a duplicate and chime in over at https://github.com/philc/vimium/issues/3272.
