### ISSUE TITLE
Suspend all tabs in all windows doesn't suspend current tab

### ISSUE THREAD

**Issue by jefferyyuan** [philc/vimium#3342]
- Suspend all tabs in all windows doesn't suspend current tab, and verified that the current tab is not in any whitelist.
- Tested multiple times with different current page.
- Force suspend all tabs does suspend all tabs, it will also suspend tabs with unsave data due to the **Force**.

**Comment by gdh1995** [comment]
Is this an issue about "The Great Suspender"? As far as I know, Vimium has no commands to "suspender" all tabs up to now.

**Comment by jefferyyuan** [comment]
- oops, sorry for the mistake.
- no idea why I made the mistake.
- close it.
