### ISSUE TITLE
Close multiple tabs on the left 

### ISSUE THREAD

**Issue by jefferyyuan** [philc/vimium#3345]
- Sometime we want to close multiple tabs on the left (not close all tabs on the left)
  -  btw we can close multiple tabs on the right: count + x.

- This is also related with https://github.com/philc/vimium/pull/2971, but focus on `Close multiple tabs on the left `.

**Comment by gdh1995** [comment]
Just an AD: my customized Vimium - [Vimium C](https://github.com/gdh1995/vimium-c) - supports negative count numbers, so with it `-3x` will close the current tab and 2 tabs on the left. In the meanwhile, its `closeTabsOnLeft` and `closeTabsOnRight` only closed tabs of given count, not (Vimium's) any on one side.

**Comment by philc** [comment]
This has been completed in #4296.
