### ISSUE TITLE
does not work unmap arrow for a specific page

### ISSUE THREAD

**Issue by raingart** [philc/vimium#3352]
Browser: Chromium 75.0.3770.80 (Official Build) Arch Linux (64-bit)

I attached a screenshot conf:
![Screenshot from 2019-06-15 19-50-25](https://user-images.githubusercontent.com/13064767/59554178-c8a3d000-8fa7-11e9-9c7e-8042c969c898.png)

If you insert arrows in the "Excluded URLsand keys", then ALL Vimium hotkeys stop working on the site
I think this is due to incorrectly handling the characters ">" and "<"

**Comment by gdh1995** [comment]
Yes, Vimium's exclusion passing keys only support single characters (like alphabets, punctuation marks and numbers).

**Comment by raingart** [comment]
@gdh1995  Is there a way to disable arrows for a particular page? If globally they are mapping

**Comment by gdh1995** [comment]
Well, on Vimium there's no options to do so.

I've written a customized version of Vimium: https://github.com/gdh1995/vimium-c and it can exclude composed "keys" like `<a-f>` and `<left>`, while a key of `f` doesn't make it exclude `<a-f>`. You may have a try.

**Comment by raingart** [comment]
Thanks, I will try

**Comment by politicus** [comment]
@gdh1995 Do you think there is a way to unmap "," "<", ">" keys (in the official Vimium version or yours)? Thank you.

**Comment by gdh1995** [comment]
Vimium treats every character (of a key string in an exclusion rule) as an excluded target, so a string of "`,<>`" is enough.

@politicus  For Vimium C, it will split what string you input into small parts and joined with space characters, so if only you see `, < >` (notice the spaces) when you have clicked "save", then the 3 keys will be excluded.

**Comment by politicus** [comment]
Thank you very much!
