### ISSUE TITLE
Fontawesome as next/prev button

### ISSUE THREAD

**Issue by fikrimi23** [philc/vimium#3354]
I am unable to make it work with site that has next/prev button that use fontawesome i.e. 
`<i class="fa fa-chevron-right"></i>`

**Comment by gdh1995** [comment]
Well, it's almost impossible for Vimium to recognize such special fonts and find an icon "looking like a right arrow" - a classname may be (and is easy to) modified or even compressed.

**Comment by fikrimi23** [comment]
that's what I mean, how was the searching does? html tag content, or it also can find class/attribute/id or such ? because for fontawesome there's `chevron-right` and `chevron-left`

**Comment by gdh1995** [comment]
* firstly, query selector all by `:is(a,area,link)[rel="next"]`
* if no matches, query XPath by `.//a | .//*[@onclick or @role='link' or contains(@class, 'button')]`
  * iter the result list, and match pattern words in `element.innerText` and `element.value` (for `<input>`s)

Currently there's no option to adjust the class name matcher.

**Comment by fikrimi23** [comment]
Ok then, thank you
