### ISSUE TITLE
"Don't let pages steal the focus on load" option, firefox

### ISSUE THREAD

**Issue by Vancelot11** [philc/vimium#3358]
The way websites steal focus on load is very annoying and I've seen some talk about an option in vimium that disables it but I'm not able to find it in the options menu. Am I missing something or has this not been implemented in the firefox port?

**Comment by gdh1995** [comment]
"Don't let pages steal the focus on load" is in the area of "advanced options", so you may need to click the "Show Advanced Options" button at the bottom of VImium Options page.

**Comment by Vancelot11** [comment]
Ohhhhh my god. I saw people talking about that and didn't realize it was aaaalll the way at the bottom haha. I feel dumb, thanks a ton though.
