### ISSUE TITLE
Can I map <esc> key to a command?

### ISSUE THREAD

**Issue by xged** [philc/vimium#3359]

**Comment by gdh1995** [comment]
Currently, no. a <kbd>&lt;escape&gt;</kbd> will always trigger `Esc` behavior in normal mode.

**Comment by xged** [comment]
Should I Close, because question is answered or should I leave Open as a (little) feature request.

**Comment by gdh1995** [comment]
Some issues of mapping other keys to `<esc>` have been closed for a tag of "lack-of-interest", so I think this issue may also be closed directly.

AD: I have a customized version of Vimium - https://github.com/gdh1995/vimium-c , and it supports `mapKey <esc> ...`, so for this need you may write:

```
mapKey <esc> <c-s-f13>
map <c-s-f13> nextTab
# `<c-s-f13>` can be any key you're not using
# here "nextTab" can be replaced with what you want
```
