### ISSUE TITLE
Feature request: pre-filter links by char

### ISSUE THREAD

**Issue by matklad** [philc/vimium#3369]
Currently, link-hint mode highlights all the links on the page. Typically there is a ton of links on a single page though, so it may be hard to focus on the one you need and ignore others.

An interesting solution for "to many links" is implemented in Emacs ace-jump mode for jumping to any word. There after activating the hints, the user should first press the *first* letter of the word they want to jump to. After that, only words with matching first letter are highlighting, and usually one letter is enough in this case.

I *think* this can work in vimium as well: instead of highlighting all of the links, first wait until a letter is entered, and then hint only the links which start with the letter.

**Comment by innaterebel** [comment]
Are you describing the [filtered hints](https://github.com/philc/vimium/wiki/Using-Link-Hints) mode?

**Comment by matklad** [comment]
Not exactly, but I think filtered hints might actually solve my problem, I’ll try them out, thanks!
