### ISSUE TITLE
f and F no longer working on Chrome

### ISSUE THREAD

**Issue by misakimichy** [philc/vimium#3371]
## Problem

Pressing the `f` or `F` key no longer paints the page with letter links. The `Open link in current tab.` popup is still displayed in the bottom right of the browser, but that's it:

![image](https://user-images.githubusercontent.com/42012999/62817302-f9f0d600-bae8-11e9-9f20-5db8d0f41dc3.png)

Pressing `?` still pulls up help, and other buttons appear to work.

## Versions

Vimium version:

```
Version 1.64.6
```

Chrome version (latest):

```
Version 75.0.3770.100 (Official Build) (64-bit)
```

macOS version (latest):

```
10.14
```

**Comment by gdh1995** [comment]
Can not reproduce it on Win 10 /macOS 10.14. Does it work after reloading the page? Could you provide a snapshot of the page's console log messages (open "Developer Tools" for the page and click the "console" panel)?

**Comment by misakimichy** [comment]
`f` key doesn't work even after reloading the page. Here is the screenshot of the console log message:
Before pressing f key.
![Screen Shot 2019-08-11 at 3 36 40 PM](https://user-images.githubusercontent.com/42012999/62840334-ddba7980-bc4d-11e9-9456-b1be7c16ea3c.png)

After pressing `f` key:
![Screen Shot 2019-08-11 at 3 34 42 PM](https://user-images.githubusercontent.com/42012999/62840345-15c1bc80-bc4e-11e9-9fbf-2ade86036ed0.png)


I just realized that vimium.css returns 200 after I press `f` key. Let me know if you need more screenshot.

**Comment by gdh1995** [comment]
I guess another web extension injects some CSS code to the page, and breaks Vimium's UI. So please provide snapshots of CSS styles like this:

![image](https://user-images.githubusercontent.com/5547703/62843573-64726380-bced-11e9-81b1-132ee05b5988.png)

What I want is style lists in the right panel of Developer Tools, for nodes including `id="vimiumHintMarkerContainer"` and `class="vimiumReset internalVimiumHintMarker vimiumHintMarker"`

**Comment by misakimichy** [comment]
Here is the screenshots of CSS code:
![Screen Shot 2019-08-11 at 9 05 36 PM](https://user-images.githubusercontent.com/42012999/62845357-0b1e1c00-bc7c-11e9-9afd-0ca3f0a219b8.png)

![Screen Shot 2019-08-11 at 9 07 13 PM](https://user-images.githubusercontent.com/42012999/62845359-0fe2d000-bc7c-11e9-8c4a-3f360fbb7949.png)

**Comment by gdh1995** [comment]
This line is to blame:
![image](https://user-images.githubusercontent.com/5547703/62845421-60007780-bcfa-11e9-81df-e1a66e4ad029.png)

So, please turn off your other browser extensions one by one, and reload the page to watch if Vimium can show its hints successfully.

**Comment by misakimichy** [comment]
Great. Once I removed Lolli, the letter tabs are back when I press f key.

Thank you for figuring this out @gdh1995 👍

**Comment by gdh1995** [comment]
So you may report an issue to the extension's support forum.

**Comment by Cypher1** [comment]
Looks like this can be closed?
