### ISSUE TITLE
Can't bind shift-space and space to separate commands

### ISSUE THREAD

**Issue by QHayward** [philc/vimium#3374]
I wish to bind shift-space and space to separate commands if possible; currently, there doesn't seem to be a way to have them execute separate commands.

I'm not sure what the proper notation for this would be.
`<Space>` and `<space>` each override both shift-space and space commands.
`<s-space>`, `<shift-space>`, `<S-space>`, etc., don't seem to do anything at all.

**Comment by gdh1995** [comment]
Currently Vimium considers about <kbd>Shift</kbd> only if the pressed "char"'s length is 1, which means it can only be one of alphabets, numbers and punctuations. But as you see, <kbd>space</kbd> has a name of "space", so Vimium ignore the status of Shift.

**Comment by QHayward** [comment]
Same as #2388
Fixed in 1.66 (on 2020-03-02)
