### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by Beasta** [philc/vimium#3380]
Uncaught TypeError: Cannot read property 'length' of null

Context
_generated_background_page.html

Stack Trace
lib/utils.js:422 (anonymous function)

Details:
crashed when I used onetab to collapse all my open tabs

Browser and os:
OS: OSX
Browser: Brave Version 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)

![Screen Shot 2019-08-21 at 12 33 45 PM](https://user-images.githubusercontent.com/6305836/63462577-16a5db80-c410-11e9-9406-c6e3df510e35.png)

**Comment by philc** [comment]
We think this is fixed in master, which will be released to the store in 1-2 days.
