### ISSUE TITLE
Multiple configs

### ISSUE THREAD

**Issue by ctejada10** [philc/vimium#3383]
Hello,

I have a Mac and a Windows PC with Vimium installed on both. However, the commands set for my Mac clash with some Windows commands (ctrl + f and ctrl + l). Is it possible to have independent configs for each machine?

Thanks

**Comment by gdh1995** [comment]
You may try my customized version of Vimium - [Vimium C](https://github.com/gdh1995/vimium-c), and it supports `map f LinkHints.activateMode $if={"sys":"win"}` to declare mappings for Windows and ` `"mac"` for macOS, `"linux"` for Linux.
