### ISSUE TITLE
<a-a> stopped working.

### ISSUE THREAD

**Issue by politicus** [philc/vimium#3387]
Mapped "Alt+a" to visitPreviousTab long time ago. More than a year. 

Was so used to use it that when it stopped working around a month ago, I thought it was because I had a keyboard shortcut conflict with another extension. No other problem with Vimium.

Replaced this functionality by installing "CLUT: Cycle Last Used Tabs".

Browser: Brave Browser v76.0.68.131 (68.131)
Extension version: 1.64.6

**Comment by gdh1995** [comment]
So what's your question? If the `<a-a>` is used by another extension, then Vimium has nothing to do.

During my test on a newly installed Brave (76.0.3809.132 x64, Win10), Both `^` and `<a-a>` work well.

**Comment by philc** [comment]
Alt-bindings were broken (by the browser) on Mac at some point. I'm closing this in favor of #3197.
