### ISSUE TITLE
Holding shift doesn't flip mode when using f or F in Firefox

### ISSUE THREAD

**Issue by JCDenton52** [philc/vimium#3388]
In Chrome, I'm able to temporarily change the opening mode of `f` and `F` by pressing `Shift`. I'm unable to do this in Firefox on both Arch Linux and Windows 10.

Chrome: 76.0.3809.132
Chrome/Vimium: 1.64.6
Firefox: 69.0
Firefox/Vimium: 1.64.6

**Comment by gdh1995** [comment]
Can not reproduce on Firefox 69 ... Could you give an example page?

**Comment by JCDenton52** [comment]
It happens on every web page. I cleared Firefox's extensions, preferences, history, etc. and reinstalled Vimium -FF and the problem persisted; however, I was able to fix it after refreshing Firefox, which suggests that it was an issue with settings I changed in about:config. Closing this issue for now.
