### ISSUE TITLE
< mapped to goPrevious doesn't do anything

### ISSUE THREAD

**Issue by devnoname120** [philc/vimium#3391]
I'd like to map `goPrevious` and `goNext` to single `<` and `>` instead of the default of double ones.

Here is what I tried
```
unmap <<
map < goPrevious
unmap >>
map > goNext
```

However it doesn't do anything when this is activated. As soon as I remove this, the default `<<` and `>>` work again.

**Comment by devnoname120** [comment]
@philc Any updates on this?

**Comment by gdh1995** [comment]
I can not reproduce it on Chrome 79, Win 10 and GitHub issues page. Have you mapped `"<" + ...` or `">" + ...` to other commands? I mean something like `>a` ?

Or, please keep `>` to be mapped to `goNext` and then test <kbd>\></kbd>on this page:
https://gdh1995.github.io/vimium-c/keyboard-test.html . A snapshot will be helpful.

**Comment by devnoname120** [comment]
> 
> 
> I can not reproduce it on Chrome 79, Win 10 and GitHub issues page. Have you mapped `"<" + ...` or `">" + ...` to other commands? I mean something like `>a` ?

No, I haven't.

> Or, please keep `>` to be mapped to `goNext` and then test >on this page:
> https://gdh1995.github.io/vimium-c/keyboard-test.html . A snapshot will be helpful.

Using the default Vimium mappings when I press `>` only the ShiftLeft keydown/up press shows up in the page.  If I press it twice it moves the tab to the right but nothing happens inside the page either.

If I do `map > goNext`, then pressing `>` (even twice) doesn't move the page to the right and again only the ShiftLeft keydown/up shows up in the page.

**Comment by gdh1995** [comment]
Then Vimium always succeeded in grabbing <kbd>\></kbd> actions but just failed to move a tab. It is really strange.

**Comment by devnoname120** [comment]
Could you test on Firefox to see whether you can reproduce the issue or not?

**Comment by gdh1995** [comment]
Oh I see.

In the default key mappings, `>>` is mapped to `moveTabRight` and `<<` to `moveTabLeft`. So do you misunderstand the actions of `moveTabRight` / `goNext`?

The real meaning of `goNext` is `Follow the link labeled next or >`, and will only find a link for "next" page and click it.

**Comment by devnoname120** [comment]
Wow that was it, thanks!
