### ISSUE TITLE
Some keys do not work on https://www.nydailynews.com/ (both chrome and firefox)

### ISSUE THREAD

**Issue by gnarendran** [philc/vimium#3398]
link hints (f/F), open URL (o/O) keys don't work
some keys like scrolling, tab navigation etc., do work.

chrome: 77.0.3865.75
firefox: 69.0
Vimium: 1.64.6

Regards

**Comment by gdh1995** [comment]
Confirmed, and I've filed a PR to fix this.

The page suppresses some events including "`DOMContentLoaded`", which makes Vimium fail to receive the "loaded" signal and do some work.
