### ISSUE TITLE
custom search engine

### ISSUE THREAD

**Issue by workstation-i** [philc/vimium#3399]
Can't use custom search engine with this command Vomnibar.activateBookmarksInNewTab.

**Comment by gdh1995** [comment]
Currently not available on Vimium.

(The following is an AD) I've written a customized version of Vimium: https://github.com/gdh1995/vimium-c . Its Vomnibar supports an extra usage, so a user can type a prefix of "`:o`" to ensure it in "omni" mode (whatever the original mode is), and then search engines are available. That means, if the query string is `:o g abc`, then Vimium C will search `abc` using the engine `g` (Google).
