### ISSUE TITLE
vimium does not work with smooth scroll

### ISSUE THREAD

**Issue by kazzmir** [philc/vimium#340]
vimium does not interact well with the smooth scroll extensions (https://chrome.google.com/extensions/detail/cccpiddacjljmfbbgeimpelpndgpoknn). I can press the arrow up/arrow down and get smooth scroll behavior, but pressing j/k or ctrl-d/ctrl-u does not produce the same behavior.

If its possible to make the two work at the same time (smooth scrolling while using vim keys to move) I would appreciate it.

**Comment by lillypad** [comment]
Javascript now supports smooth scrolling.
```javascript
function scroll_down(offset){
  try {
    window.scroll({
      top: (document.documentElement.scrollTop + offset),
      left: document.documentElement.scrollLeft,
      behavior: 'smooth'
    });
  } catch(error){
    console.log(error);
    return false;
  }
}

function scroll_up(offset){
  try {
    window.scroll({
      top: (document.documentElement.scrollTop - offset),
      left: document.documentElement.scrollLeft,
      behavior: 'smooth'
    });
  } catch(error){
    console.log(error);
    return false;
  }
}
```

Not sure if this is in there already but it's a suggestion none the less.

:smiley:

**Comment by smblott-github** [comment]
Thanks for that, @lillypad.  Vimium does not use this, however...

1. Vimium's smooth scrolling keeps going while you hold the key down, and stops on `keyup`.  It's not obvious that the `window.scroll()` API is suitable for that behaviour.

2. If it ain't broke, then don't fix it!

However, this is *good to know* anyway.

**Comment by lillypad** [comment]
Hey @smblott-github.

No need to fix it either in my opinion, it's not broken, and it scrolls smoothly when I hold the keys here as well.

:smiley:
