### ISSUE TITLE
[Firefox Nightly/BUG] ']]' and '[[' shortcuts do not work in Google or Bing search page

### ISSUE THREAD

**Issue by Titubery** [philc/vimium#3415]
When tying ']]' on Google search result page, it jumps to one of the listed sites instead of next page. and '[[' has no responses.

**Comment by gdh1995** [comment]
I guess it's because these search result pages show some path parts of page URLs that `]]` didn't work.

For further checks, please provide these messages:
* What's your Firefox's UI language?
* What's the URL that you found `]]` did not work?
* Do you have other browsers on which Vimium works well? If you have, please provide their UI languages.

**Comment by Titubery** [comment]
@gdh1995 I have latest Firefox and Chromium in English with `vimium` on Linux. But both two do not work in any Google search pages. i.e. When typing `]]` on [search of 'test'](https://www.google.com/search?client=firefox-b-d&q=test) , it jumps to this [wiki](https://en.wikipedia.org/wiki/Test). Also I have disabled all other extensions in my browser and never changed any key bindings with `]` or `[`. Did I misunderstand its function? By the way, it is confusing that `]]` works well on [Baidu search page](https://www.baidu.com/s?ie=utf-8&&wd=test).

**Comment by Titubery** [comment]
Many thanks, I'll try that. @gdh1995

**Comment by gdh1995** [comment]
What's your language settings of Google on https://www.google.com/preferences?hl=en#languages? In my tests on https://www.google.com/search?q=test (English page / Chinese page), Vimium C succeeded.

Currently, Vimium C only tries to find `>` and `Next`, so it will fail on Japanese pages. But I've planned to add support for Google search result pages in other languages, and it will be released in a few days.

**Comment by Titubery** [comment]
OK, I think I know why did that happen, the page language is English but the `next` button depends on my IP address. It seems not a big deal to support other languages of Google search by extending the next/previous patterns. It works now but that vimium still stucks in Bing, however, I seldom use that. Thanks and good luck!
![Screenshot from 2019-10-25 18-20-53](https://user-images.githubusercontent.com/17917040/67564440-89f00480-f755-11e9-9987-805297d18dd1.png)
![Screenshot from 2019-10-25 18-27-46](https://user-images.githubusercontent.com/17917040/67564447-8c525e80-f755-11e9-9116-5d140abe2d90.png)
