### ISSUE TITLE
[feature request] Is it possible to add second tab or something similar to vimium?

### ISSUE THREAD

**Issue by Wsine** [philc/vimium#3417]
I am a big fan of vimium. Every time i get started with a new computer, i will equip chrome with vimium plugin. 

I got used to use `alt/command + number_key` to switch to tab index, e.g. `alt + 1` to switch to the first tab. However, this hotkey is not the same in Windows platform. The default is `ctrl + num`.

So i wonder **is it possible to add a feature to vimium even with no default keybinding?** For example, a feature named `secondTab` or `thirdTab`, whose function is similar to `firstTab` and `lastTab`.

Looking forward for your reply.

With regrads

**Comment by gdh1995** [comment]
Currently, Vimium seems to have to such a command.

You may try my customized version of Vimium: [Vimium C](https://github.com/gdh1995/vimium-c), and it supports such mappings:

```
map <a-1> firstTab
map <a-2> firstTab count=2
map <a-3> firstTab count=3
```

**Comment by innaterebel** [comment]
I recall it's also possible for Vimium to map `firstTab` and `lastTab` with count prefix, so it is the <kbd>Alt</kbd>+<kbd>Number</kbd> scheme which Vimium does not support?

**Comment by gdh1995** [comment]
Sorry I made a mistake. After some tests, I have confirmed Vimium supports the same mapping on Win 10, so please map it as I said directly.

**Comment by Wsine** [comment]
Wow, I test it and it works. That's awsome. Thank you so much! And now i am a bigger fan of vimium 😸

**Comment by gdh1995** [comment]
Then you may close this issue, to tell others "this issue has been solved".

**Comment by Wsine** [comment]
Thanks for reminder.
