### ISSUE TITLE
Custom CSS for Link Hints inside iFrames seems to not be working correctly again

### ISSUE THREAD

**Issue by HarvardYard** [philc/vimium#3418]
I noticed this has been referenced before.
#2594
And fixed by:
#2683

However, it is still occurring for me. First started noticing it today [10.28.19].

Chrome Version: 78.0.3904.70 (Official Build) (64-bit) (cohort: 78_70_Win)
Vimium Version: 1.64.6

**Comment by gnarendran** [comment]
+1
To be able to use with the new "chrome://flags/#enable-force-dark", I tried to change the colors for link hints in "CSS for Vimium UI", and then noticed this issue. Currently working around by modifying vimium.css itself.

**Comment by gdh1995** [comment]
https://developer.chrome.com/extensions/content_scripts#document_start says:

> scripts marked "`document_start`" are injected after after files from css

But in tests on Chrome 53/61/74/78 x64 on Win 10, I found user-defined code which is injected into iframes by `chrome.tabs.insertCSS` may be overridden by those in vimium.css, and this means, I think, the document above is not always correct.

**Comment by qubist** [comment]
Chiming in here: in Firefox, my custom link hint CSS doesn't apply in the iframes of embedded YouTube videos.

macOS 11.0.1 (20B29)
Firefox 89.0.2 (64-bit)

**Comment by philc** [comment]
Closing this in favor of #3452, which I think is the same issue.
