### ISSUE TITLE
Google search page does not display properly

### ISSUE THREAD

**Issue by liufei666** [philc/vimium#3423]
![image](https://user-images.githubusercontent.com/23350579/68383854-67b4a880-0191-11ea-87c8-d42f7a022721.png)

**Comment by gdh1995** [comment]
What I see is:

![image](https://user-images.githubusercontent.com/5547703/68387759-0f35d900-019a-11ea-9f8c-9e5f62e305c7.png)

So why the URL path is at the top of a search result on your demo image? Is there a settings of Google Search, or a special browser extension causing ti?

**Comment by liufei666** [comment]
Thank you. I see other people's browsers same as yours.Maybe I set it wrong

**Comment by gdh1995** [comment]
Well, I'm still curious about how you set it. Are you modifying CSS styles through something like Greasemonkey?

**Comment by liufei666** [comment]
I have, but the search page is not open.

**Comment by taylorthurlow** [comment]
I also have this exact same problem on Firefox 72.

**Comment by codekeeperjava** [comment]
> What I see is:
> 
> ![image](https://user-images.githubusercontent.com/5547703/68387759-0f35d900-019a-11ea-9f8c-9e5f62e305c7.png)
> 
> So why is the URL path at the top of a search result on your demo image? Is there a settings of Google Search, or a special browser extension causing it?

This seems to be a change in Google, is there any solution? @gdh1995 

<https://news.mydrivers.com/1/651/651057.htm>

**Comment by gdh1995** [comment]
Well my Google has also became this version. Currently there's no options in Vimium to move such hints.

Or you may try my customized version of Vimium, Vimium C (https://github.com/gdh1995/vimium-c) - I added a special code part for such search result pages to move hint marks to the top-left of title items (more concretely, `a > h3`).
