### ISSUE TITLE
Facebook Messenger: Can't Open Stickers

### ISSUE THREAD

**Issue by raymondyou97** [philc/vimium#3427]
If I try clicking on the open sticker link when on `messenger.com`, it immediately closes it. This is for all icons on that row.

I narrowed the issue down to vimium as I disabled it and it fixed the issue.

I also have the exclusion of `https?://www.messenger.com/*`  for all keys.

https://media.giphy.com/media/f9SOCDldZHnPuDQVSM/giphy.gif

**Comment by raymondyou97** [comment]
Changing the exclusion to directly `https://www.messenger.com/` seemed to fix the issue.

**Comment by gdh1995** [comment]
It's very strange. If your exclusion pattern is `'https://www.messenger.com/` (without `*`), then it only matches the HTTPS version of homepage of messenger.com. So it means "it works well when you enable Vimium on such pages".
