### ISSUE TITLE
Alternative (non=qwerty) layouts suppot

### ISSUE THREAD

**Issue by vovoka** [philc/vimium#3431]
Hi! 
I'm using Colemak keyboard mapping.
LinkHints.activateMode shows hints with qwerty layout. For example if I see hint "AS" or "DF" I nave to type "AR" or "ST" correspoldly. I suppose that it is not a big deal to add mediate layer for translating QWERTY hints to Colemak / Dvorak ?

**Comment by gdh1995** [comment]
* Open Vimium's options page
* click "Show Advanced Options" at the bottom of the page
* find "Ignore keyboard layout" and select its checkbox
* click "Save Changes"
* take a try

**Comment by vovoka** [comment]
Sorry, can't find any checkboxes 
https://img.techpowerup.org/191115/vi.png

**Comment by gdh1995** [comment]
Click the "options" and Vimium will open options page

**Comment by vovoka** [comment]
Thank you!

**Comment by vovoka** [comment]
hm... not sure it works first time, however it does not now (short demo-video ar proof). 
https://youtu.be/pLPK_kuYZV0
I've checked "ARST" one by one (as a quick remind: ASDF  is equal to ARST in Colemak).
May I missing something?

**Comment by gdh1995** [comment]
Sorry I can't get what's wrong. In the video, you pressed `A`, `S`, `D` and `F` (4 letters printed in your keyboard) and Vimium got A/S/D/F correctly.

If you mean you want to use Colemak layout to type letters, I think you just need to uncheck the "ignore layout" and save options.

On my Win10 x64 + Chrome + The software from https://colemak.com/Windows , the "ignore layout" works just like in the video.

**Comment by akeley98** [comment]
The above answers solve the problem you stated; however, you may find it less confusing to uncheck "Ignore keyboard layout" and instead solve the problem by changing the characters in the "characters used for link hints" field. I use dvorak and chose "tnseicrloujkbm" as my keyboard hint characters.
