### ISSUE TITLE
I can not find vimium in microsoft edge store😂

### ISSUE THREAD

**Issue by xiaorong61** [philc/vimium#3432]
I can not find vimium in microsoft edge insider store😂

**Comment by sonakshimore** [comment]
**Publish Vimium to Microsoft Edge Add-ons website**

Microsoft Edge is the second most used browser on the web, making the browsing experience more flexible, offering many more services for users and optimized for Windows devices.

Microsoft Edge supports Chromium extensions, and you can publish your extensions to Microsoft Edge Add-ons website with minimal code changes. Find out more [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension).

If you have any more queries about porting Chrome extension to Microsoft Edge or anything else, you can contact the relevant teams whose links are given [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team). 

Let me know if this was helpful. I am happy to help you with more details.

**Comment by philc** [comment]
Hey folks, Vimium is now on the [Edge Add-ons site](https://microsoftedge.microsoft.com/addons/detail/vimium/djmieaghokpkpjfbpelnlkfgfjapaopa). Please leave a review there to help encourage others to try it.

Thanks!
