### ISSUE TITLE
[Question] Cycling between input boxes

### ISSUE THREAD

**Issue by ahmetb** [philc/vimium#3448]
On https://www.reddit.com/subreddits page I see 3 input boxes. Two of them are yellow, one is red after hitting `gi`. This makes me think I can cycle between the input boxes using `gi`, but the `?` documentation doesn't say so.

![image](https://user-images.githubusercontent.com/159209/71133991-77240a00-21b1-11ea-8863-7dba432a4419.png)

Is there actually a way to do this?

(Also FYI https://vimium.github.io/ seems to be out of date with `?` pane.)

**Comment by innaterebel** [comment]
Forgot where I knew it, but it is <kbd>Tab</kbd>.
The `gi` also accepts count prefix, meaning you can directly <kbd>3</kbd>`gi` to focus the 3rd input in the viewport.

**Comment by ahmetb** [comment]
Damn I have been trying gi2 gi3 etc.

**Comment by ahmetb** [comment]
Let's keep open for adding documentation around this.
