### ISSUE TITLE
Vimium only works in a background-loaded tab in Chrome 81

### ISSUE THREAD

**Issue by innaterebel** [philc/vimium#3449]
In current nightly Chrome Vimium is almost always disabled, console shows no error.
But is always normally enabled in a tab that is loaded in background, including an existing tab reloaded in background. So seems like a new timing issue.

Although a nightly bug, in my experience they seldom go away spontaneously in the case of Chromium. So file this now anyway for early investigation, if desired.

**Comment by lunamoth** [comment]
Chrome 81.0.4000.3 dev 64-bit

I have the same problem. Please fix it.

**Comment by rickyz** [comment]
I am also encountering this in the current Chrome dev channel, 81.0.4000.3 (Official Build) dev (64-bit).

I see these errors on the console for vimium's background page:

```
Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at Image.image.onload (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/background_scripts/main.js:627:48)
```

```
Error in event handler: Error: The imageData property must contain an ImageData object or dictionary of ImageData objects.
    at verifyImageData (extensions::setIcon:49:11)
    at setIcon (extensions::setIcon:86:7)
    at extensions::browserAction:14:5
    at Object.isEnabledForUrl (<URL>)
    at <URL>
```

This may explain why vimium only works on tabs loaded in the background - I'm guessing that vimium manages to inject itself into those pages without trying to change the icon.

**Comment by gdh1995** [comment]
I can not reproduce this on Chrome 81.0.4000.3 (Dev) / 81.0.4003.0 (Canary) on Win 10 x64.

Downloaded from https://tools.shuax.com/chrome/:
https://redirector.gvt1.com/edgedl/release2/chrome/cJXe57nB-Zh4wjva2XPl4A_81.0.4000.3/81.0.4000.3_chrome_installer.exe
https://redirector.gvt1.com/edgedl/release2/chrome/b_CGqrLDDZh00VFzc9m-dQ_81.0.4003.0/81.0.4003.0_chrome_installer.exe

**Comment by rickyz** [comment]
I am not sure why an image from chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb is considered to be from a different origin than the background page. I don't know quite enough about Chrome extensions to say whether this is a bug in Chrome or not.

That said, I have been able to work around this by replacing the relevant bit of main.js with:

```js
  ref = [ENABLED_ICON, DISABLED_ICON, PARTIAL_ICON];
  for (i = 0, len = ref.length; i < len; i++) {
    icon = ref[i];
    iconImageData[icon] = {};
    ref1 = [19, 38];
    fn = function(icon, scale) {
      if (!((chrome.areRunningVimiumTests != null) && chrome.areRunningVimiumTests)) {
        fetch(icon)
          .then(function(response) { return response.blob(); })
          .then(function(blob) { return createImageBitmap(blob); })
          .then(function(image) {
            var canvas = new OffscreenCanvas(scale, scale);
            var context = canvas.getContext("2d");
            context.drawImage(image, 0, 0, scale, scale);
            iconImageData[icon][scale] = context.getImageData(0, 0, scale, scale);
          })
      }
    };
    for (j = 0, len1 = ref1.length; j < len1; j++) {
      scale = ref1[j];
      fn(icon, scale);
    }
  }
```

(based on the code at https://source.chromium.org/chromium/chromium/src/+/master:extensions/renderer/resources/set_icon.js;l=7;drc=ec5f56aafc3a089668e7cfdf73e426b39546b368?originalUrl=https:%2F%2Fcs.chromium.org%2F)

It's a pity that extensions need to do such hacks to set icons. From what I can tell, this is to work around a Chrome memory leak (https://crbug.com/242215) that doesn't appear to have been fixed, at least based on comments on the bug.

**Comment by gdh1995** [comment]
What're your settings on chrome://flags? Or is this only on macOS?

**Comment by innaterebel** [comment]
Well now this is bizarre. This issue can only be reproduced on an existing profile.

First I tried a fresh profile, likely what @gdh1995 did. Okay, not reproducible indeed.
Afterward I have made a copy of my existing profile, then tried to reset all its flags, remove all other extensions, reset its settings to default, finally disable its sync which would then offer an option to completely wipe out ALL data and customization, doing this relaunches the browser and now your browser looks exactly like a fresh profile.
Then I installed Vimium anew and it still didn't work! lol

At this point my best guess is that this is caused by some of those server-side field trial experiments being conducted on all M81 branches, EXCEPT when the target profile is a first-run.
So last but not least, I create a fresh profile again, install Vimium, browse some web pages confirming it worked, close browser then reopen. TA-DAH! Reproducible now.

Nevertheless whether it IS the field trials is unverifiable, so we may be left unactionable here.

**Comment by innaterebel** [comment]
New finding: It's not accurate that it works on background-loaded tabs, it is
"it will work if content area doesn't have focus _before_ the page _starts_ loading".
That is,
1. Make a navigation.
2. Before the loading indicator starts spinning clockwise, moves the focus away from content area either by, say, Ctrl+L or F10 or F6.
3. After page started loading (not necessary finished), move focus back by Shift+F6. Vimium works.

So there goes your workaround for now. Not really a workaround and may be impossible to do if your connection is really fast...
I am convinced this is a Chrome bug now. However I don't know how to report this complexity to them.

**Comment by rickyz** [comment]
I spent some more time investigating this, and I believe the field experiment in question is `OutOfBlinkCorsEnabled`. I've filed a bug with some analysis at https://bugs.chromium.org/p/chromium/issues/detail?id=1036693

That said, the workaround I suggested above seems like a reasonable code cleanup that also works around this issue, so it might be worth doing that to unbreak the extension for affected users.

Another easier, but much hackier workaround is to add:

```js
image.crossOrigin = 'anonymous'
```

before setting image.src here: https://github.com/philc/vimium/blob/af673648d47cb2770aeeb34a92e5c95cde31d316/background_scripts/main.coffee#L314

**Comment by gdh1995** [comment]
@rickyz Confirmed and your work-around works well on Chrome 81 (Win 10 x64).

BTW, I want to share an edge case with you: Chrome has an command-line option "--disable-reading-from-canvas", and this will break dynamic extension icons (either Vimium's loading, or implicit loading in `extension::setIcon`.

**Comment by rickyz** [comment]
> BTW, I want to share an edge case with you: Chrome has an command-line option "--disable-reading-from-canvas", and this will break dynamic extension icons (either Vimium's loading, or implicit loading in `extension::setIcon`.
Yeah, I saw this in issue 2606. That seems to be due to https://crbug.com/768321 - the only workaround I know of for that bug is to create an ImageData directly with a byte array for the image, and passing that to setIcon.

**Comment by gdh1995** [comment]
Chrome Dev has been updated to 81.0.4021.2 and this bug has been fixed.
