### ISSUE TITLE
how can i enty caret mod agin

### ISSUE THREAD

**Issue by agxmaster** [philc/vimium#3456]
**Describe the bug**
Include a clear bug description.

**To Reproduce**
1. Go to URL '...'

Include a screenshot if applicable.

**Browser and Vimium version**

If you're using Chrome, include the Chrome and OSS version found at chrome://version. Also include the Vimium version found at chrome://extensions.

If you're using Firefox, report the Firefox and OS version found at about:. Also include the Vimium version found at about:addons.

**Comment by gdh1995** [comment]
https://github.com/philc/vimium/wiki/Visual-Mode
