### ISSUE TITLE
Migrate codebase from coffeescript to ES6

### ISSUE THREAD

**Issue by philc** [philc/vimium#3459]
Hey folks,

I plan to modernize the code base by porting it from coffeescript to ES6. This will make the source more accessible to more developers, and remove the complexity of having to transpile.

Major impacts of this:

1. Some hard-to-notice bugs may be introduced by the [decaffeinate](https://github.com/decaffeinate/decaffeinate) conversion. When I've used decaffeinate on large code bases before, I've botched a few cases of removing unnecessary implicit return statements which are on by default on coffeescript.

2. All of the open PRs will become unmergeable and require revision before they can be re-evaluated.

3. Forks of Vimium will no longer be able to cleanly rebase on top of our recent commits.

4. It will become harder to find the history behind each line using git blame and git grep.

I wanted to give a heads up that this is coming, in case anyone has strong objections. The tentative date for the conversion is Jan 20, 2020. I may ship a new release to the store before then, with a few bug fixes.

Regarding the open PRs, I'm going to review the most recent 20-30 and merge those which seem valuable and low-risk. If a change is large and has a strong risk of destabilizing the code base, I'll likely not merge it and ask that it be reworked post the ES6 conversion. In case anyone wants to advocate strongly for an existing open PR to get merged before the conversion, now is the time.

Once the source is converted to ES6, I'd appreciate beta testers using the version on master, to help surface breakages in features that I don't normally use, before this version gets shipped to the chrome store to a wider audience.

Thanks! This should be great!

**Comment by philc** [comment]
This has begun in 791d7378f0a7415833aa7d9fae05cca1be245cb1.

**Comment by imbrn** [comment]
What about Typescript? 🤓

**Comment by philc** [comment]
Formal types would be nice, but I want to generally avoid transpilation, to keep the development model simple.

**Comment by gdh1995** [comment]
Just a small tip: `async` / `await` are in ES2017 and only exists on Chrome 57+, so if we remove transpilation completely, then new developers have to take care of not using features newer than ES2015, like spread properties (`...`).

**Comment by philc** [comment]
@gdh1995 Great, thanks for calling this out. I'll bump the minimum required versions of Firefox and Chrome so we can use ES2017, and note which version of javascript developers are allowed to use in CONTRIBUTING.md.

Ok, this conversion is now complete. I did the port by hand very carefully, but even still, there are at least 3 bugs I was able to easily spot after some usage, which I didn't spot while I was in the middle of the conversion: #3566, #3567, #3568.

Retrospective: I'm very thankful to be done with Coffeescript. It has persisted long past its usefulness. Besides it being a barrier to entry for many javascript developers, it added insidious complexity which was gnawing at our code base:

1. Its syntactic sugar introduced a lot of ambiguity in the code that that had to be resolved as part of the javascript conversion. E.g. "which of these implicit return statements are really necessary?". I left many in the code base because eliminating every unnecessary statement was too time consuming, given our incomplete unit test coverage.
2. Required transpilation, which necessitates a longer dev tool chain, and makes it a two step process to debug exceptions thrown by our generated javascript when running in Chrome.
3. The generated javascript code was pretty ugly, partly because of the implicit returns.

From this point forward, I intend to make the code base increasingly simple. This was the first big step.

**Comment by philc** [comment]
@gdh1995 I've bumped the minimum versions for Chrome and Firefox to ensure support for ES2018 in b243ab61f8510868b6fa3df7fe5fb0eaed6fe033 and fbddc22a4da06ade2336145d973eb203a26ec430.

**Comment by gdh1995** [comment]
> checked google analytics for our chrome store page

How did you do that ? I'm also caring about the statistics of Chrome versions, but the extension dashboard doesn't provide it.

> have a Chrome version prior to 80

Maybe those old users don't need to visit Chrome Store page. And they may stay on an old Chrome.

Anyway, according to https://caniuse.com/usage-table , Chrome 69 only owns 0.09% of the total market , so 69 seems OKay.

**Comment by JUSTIVE** [comment]
> Formal types would be nice, but I want to generally avoid transpilation, to keep the development model simple.

How about adding JSdocs instead? no additional transpilation but handy type guides & autocompletion
