### ISSUE TITLE
Action to toggle vimium?

### ISSUE THREAD

**Issue by peter099** [philc/vimium#3461]
Is there a key action to toggle vimium on and off on a page?

**Comment by gdh1995** [comment]
> `i`       enter insert mode -- all commands will be ignored until you hit Esc to exit

Refer: https://github.com/philc/vimium#keyboard-bindings

And if you want to pass `<esc>` to a page itself, https://github.com/philc/vimium/wiki/Tips-and-Tricks#using-the-escape-key-in-inputs may help

**Comment by peter099** [comment]
Thanks!
