### ISSUE TITLE
Fix Chrome's createShadowRoot deprecation

### ISSUE THREAD

**Issue by philc** [philc/vimium#3466]
Saw this warning recently in the chrome://extensions error log:

`Element.createShadowRoot is deprecated and will be removed in M80, around February 2020. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.`

**Comment by gdh1995** [comment]
It's very strange. I've added #3175 to fix this warning (when #3175 was filed, the warning is "`will be removed in M73`"), and now Vimium should not call `createShadowRoot` on Chrome.

**Comment by gdh1995** [comment]
The PR has been merged just before v1.64.2, so what's the current version of Vimium on your computer? Have you run `cake build` if it's compiled from source?

**Comment by philc** [comment]
Oops, my mistake @gdh1995, you're right. This deprecation warning was due to switching back and forth between PRs as part of my PR cleanup. Sorry for the noise, and thanks for the quick response.
