### ISSUE TITLE
Tab navigation with numbers other than 0 does not work as expected

### ISSUE THREAD

**Issue by wmbus** [philc/vimium#3475]
**My assumption**
I read in the help section that I can use 'g0' to go to the first open tab, and 'g$' to go to the last. I expected I could use numbers to go to the second, third, fourth, etc. tab as well. If my assumption is incorrect, then it would be a nice feature (and the bug below might still be a bug). If my assumption is correct, here is the bug:

**Bug description**
When pressing g0, chrome navigates to the first tab immediately. g$ works as expected as well. When pressing g1 to g9, nothing happens at first. When you then press g0, you go to the tab which number you previously entered.

For example...

**To Reproduce**

1. Have 11 tabs open (or any number but at least 6);
2. Ensure the cursor is not in an input field, and the to-be-used tabs display actual websites, contrary to, for example, the 'new tab'-page or a 'settings'-page of chrome;
3. Type 'g6';
(nothing happens)
4. Type 'g0';
(chrome navigates to the sixth open tab)

Instead I would like to see chrome navigate to the sixth tab immediately after typing the '6' of step 3.

**Browser and Vimium version**

If you're using Chrome, include the Chrome and OSS version found at chrome://version. Also include the Vimium version found at chrome://extensions.

Using chrome: 79.0.3945.117 (Official Build) (64-bit) (cohort: Stable)
Using OS: Windows 10 OS Version 1909 (Build 18363.592)
Using Vimium: 1.64.6

**Comment by gdh1995** [comment]
Vimium's count prefix has two styles:
* by default, `6g0` goes to the 6th tab
* or if you define `map g6 firstTab count=6`, then `g6` will act as you expected.

**Comment by wmbus** [comment]
Thank you for your fast reply, since everything works as is, I will close the issue.
