### ISSUE TITLE
find mode supprot IME edit

### ISSUE THREAD

**Issue by Fifth-Patient** [philc/vimium#3480]
I am a user of [vimium-FF](https://addons.mozilla.org/zh-CN/firefox/addon/vimium-ff/).
Will Vimium-FF consider using the find mode (keycode -`f`) to support IME editing?
If not, I will continue to use firefox's search function (keycode-`F3`)

---

我是vimium-FF的用户。
Vimium-FF会考虑使用找到模式（键码-`f`）来持IME编辑吗？
如果不，我会继续使用firefox的搜索功能(键码-`F3`)。

**Comment by gdh1995** [comment]
Sorry but I can nor understand the comment well. Please consider about speaking in your native language directly, and I'll try to translate it into English, to let all contributors understand this issue easily.


抱歉没能理解你的问题，请直接用你的母语重新描述此问题，我会尽量把它翻译到英语来供大家理解。



---Original---

**Comment by Fifth-Patient** [comment]
感谢您花时间回复这个issue。

我是[vimium-FF](https://addons.mozilla.org/zh-CN/firefox/addon/vimium-ff/)的用户。
**find mode**不支持输入中文，后续会考虑支持中文输入法（IME）查找吗？

**Comment by gdh1995** [comment]
#### Original issue / 原始问题的翻译:
> Thank you for responding to this issue.
>
> I'm a user of Vimium-FF.
> FindMode doesn't support Chinese input, so will you consider about adding the support for Chinese (IME)?

#### Answer / 回答:

Reproduced on Firefox 72 + Win 10. This seems a compatibility bug. I'll try to fix it in days. While the due date for a new version has not been determined.

Translation / 翻译: 在 Firefox 72 + Windows 10 上确认了此问题。似乎是一个兼容性bug，这几天我会尽量修复。不过新版本的发布日期还未确定。

**Comment by Fifth-Patient** [comment]
嘿，朋友，我找到了[vimium-c](https://github.com/gdh1995/vimium-c)，它对中文的支持很好，find mode 也支持中文输入。似乎更适合中国用户，虽然你并没有说明vimium-c与Vimium之间有什么本质区别，不过我想功能都是一样的，谢谢你。
