### ISSUE TITLE
“No links to select” on some pages

### ISSUE THREAD

**Issue by wchargin** [philc/vimium#3484]
**Describe the bug** \
Pressing `f` yields “No links to select.” even when there are `<a href>`
elements on the page.

**To reproduce** \

1. Navigate to <https://colab.research.google.com/signup>.
2. Press `f`.

Note via “Inspect element” that all the blue-text links (“Restrictions
apply”, “Learn more”, “Colab FAQ”) are normal `a` elements with `href`
attributes. They are inside shadow roots.

Screenshot:

![Screenshot of “No links to select.” while a link is highlighted in the
dev tools inspector][ss]

[ss]: https://user-images.githubusercontent.com/4317806/74093654-b708be80-4a89-11ea-9c98-7339d22cfd6d.png

**Browser and Vimium version** \
Tested Vimium 1.64.6 in Firefox 72.0.2 and in Chrome 67.0.3396.99, both
on 64-bit Linux.

**Comment by gdh1995** [comment]
This is because of Shadow DOM, and will be fixed in the next release version.

**Comment by philc** [comment]
Yep, fixed in #3406. This will go out to the chrome store in 1-2 days. Thanks for filing.

**Comment by wchargin** [comment]
Awesome; thank you for the quick reply!
