### ISSUE TITLE
Is there a way to exit insert mode, other than pressing escape?

### ISSUE THREAD

**Issue by murermader** [philc/vimium#3485]
I am trying to escape insert mode without using the escape key. I couldn't find the "exit insert mode function" so I can't map a key to it. 

The reason I am asking is that I am often using hotkeys from websites to enter video full screen mode (for example f on youtube). Once I am in fullscreen, I want to get rid of the insert mode block at the bottom of the screen, without leaving fullscreen mode (pressing ESC).

Is there any way to do this in the current version of vimium, or is that a functionality that could be implemented?

**Comment by gdh1995** [comment]
<c-[&gt; works like escape.



---Original---

**Comment by murermader** [comment]
How exactly does that help me?

**Comment by gdh1995** [comment]
You can press `<c-[>` (<kbd>Ctrl</kbd>+<kbd>[</kbd>) to exit (most if not all) modes of Vimium, and this accepts `mapkey`, so `mapkey <c-c> <c-[>` will make `<c-c>` work like `<esc>`.

**Comment by pingz** [comment]
@gdh1995 not the same thing, you still quit the fullscreen and insert mode at the same time. `c-[` is identical to `Esc`.

**Comment by gdh1995** [comment]
c-[ support mapkey, so you may write: mapkey <c-]&gt; <c-[&gt;



---Original---

**Comment by pingz** [comment]
Oh, I get it. The original `c-[` is not the same as in `mapkey <c-[> <c-[>`.

**Comment by murermader** [comment]
I can't get the `CTRL + [` to work, maybe because I am using a german keyboard layout (QWERTZ), where I have to press `CTRL + Alt Gr + 8` to get the (`Alt Gr + 8` for  `[`) character, but it does not seem to work.

My solution that I am currently quite happy with, is just disabling the insert mode block in the advance settings. That works as well. 

Anyway, thanks for the help!

**Comment by gdh1995** [comment]
You may try mapkey Ctrl+E to Ctrl+[ , then it will be easier to exit insert mode - mapkey can map any key to the c-[



---Original---

**Comment by murermader** [comment]
Thanks, that works! I mixed up the order of the mapkey parameters when trying it out for myself, but just swapping them made it work. Appreciate the help👍

**Comment by cheecheeo** [comment]
@gdh1995 thanks for all the pointers, i wonder if this could be made any more discoverable via documentation.

**Comment by hraban** [comment]
another use for this: youtube has a hotkey to go fullscreen (<kbd>f</kbd>), but that only works in insert mode; pressing ESC then will exit fullscreen rather than hide that insert mode modal at the bottom. This workaround doesn't do that.

So to go full screen in youtube you can do <kbd>i</kbd><kbd>f</kbd><kbd>Ctrl+[</kbd>

**Comment by murermader** [comment]
@hraban yes, this is why i posted this on github. I guess I'll close this issue, as it is resolved.

From the issue text: 

> The reason I am asking is that I am often using hotkeys from websites to enter video full screen mode (for example f on youtube)

**Comment by hraban** [comment]
all my apologies, I will say twenty hail maries and do penance. consider my vile words unspoken.

**Comment by yassinebridi** [comment]
@hraban it still exits full screen, ctrl+[ acts like escape.

**Comment by gdh1995** [comment]
you may need 'mapkey' to let another key act like 'c-[' during Vimium handling it. Then your browser won't notice a 'c-['.&nbsp;



---Original---

**Comment by hraban** [comment]
> @hraban it still exits full screen, ctrl+[ acts like escape.

Ah, in that case this might depend on the OS or browser. On Mac, neither Chrome nor FF interpret <kbd>ctrl</kbd>+<kbd>[</kbd> as the <kbd>esc</kbd> key. I'm curious to know which browser / OS combo emulates terminal escape keys, if you have it?

**Comment by yassinebridi** [comment]
Actually the system itself doesn't intrepret `ctrl`+`[` as `esc`, but chrome does.
I'm using chrome: 87, Arch linux

**Comment by hraban** [comment]
> Actually the system itself doesn't intrepret `ctrl`+`[` as `esc`, but chrome does.
> I'm using chrome: 87, Arch linux

Nice. Chrome 87 + Mac definitely doesn't do this. But interesting that they've gone that way on Arch.

**Comment by pingz** [comment]
> > Actually the system itself doesn't intrepret `ctrl`+`[` as `esc`, but chrome does.
> > I'm using chrome: 87, Arch linux
> 
> Nice. Chrome 87 + Mac definitely doesn't do this. But interesting that they've gone that way on Arch.

It is a C0 control code. Xorg just pass key events to applications. Maybe it is GTK or something.

**Comment by gdh1995** [comment]
I think it may be because Chrome decides to exit full-screen mode on ctrl-[, but not Chrome receives/translates ctrl-[ to escape.



---Original---
