### ISSUE TITLE
Missing Link Hints

### ISSUE THREAD

**Issue by jmagaro88** [philc/vimium#3486]
Starting this morning, I am noticing a large number of link hints missing when I browse pages I am familiar with.

For example, in this image below, notice how there are no link hints for the Smart Home Devices on the right side of the page.

<img width="1350" alt="Screen Shot 2020-02-09 at 10 33 12 AM" src="https://user-images.githubusercontent.com/8763631/74104951-a575f400-4b27-11ea-8949-6bb7a952f696.png">

Or on this page, there are not link hints for any of the CNN Business headlines on the right side of the page. 

<img width="1355" alt="Screen Shot 2020-02-09 at 10 34 49 AM" src="https://user-images.githubusercontent.com/8763631/74104990-e1a95480-4b27-11ea-80ba-081f6137b6b8.png">

Strangely, it seems like the missing link hints are all on the far right side of the browser window.

**Comment by philc** [comment]
FYI @poacher2k (who developed #3486 and #2251) and @gdh1995 -- could one of you take a look? I couldn't reproduce the issue on cnn.com, but I can easily reproduce the Amazon.com case on `master`. Here's a screenshot. The unhinted link in this image carousel changes based on how wide the window is.

![image](https://user-images.githubusercontent.com/8598/74107459-19fb6380-4b25-11ea-8230-9ff5d46369ed.png)

Here's the carousel on amazon with a wider window:
![image](https://user-images.githubusercontent.com/8598/74107461-2aabd980-4b25-11ea-8681-7901caf7f258.png)

**Comment by matthew-cline** [comment]
Possibly related: go to [this image board](https://booru.vineshroom.net/post/list/streamer%3Avinny/1), press `f`, press `Esc`, then press `f` again.  The image thumbnails on the rightmost column won't have any hints on the second and subsequent times `f` is pressed, though they did the first time.

**Comment by gdh1995** [comment]
Well, it seems that Vimium's HUD hides them.

![image](https://user-images.githubusercontent.com/5547703/74115629-0adee900-4beb-11ea-9dbf-3c8701ad99d4.png)

**Comment by arobase-che** [comment]
I'm experimenting the same on zestedesavoir.com :s 

![2020-02-10-031918_1920x1080_scrot](https://user-images.githubusercontent.com/2202307/74116552-55913e80-4bb4-11ea-971f-9636f3b86fb0.png)


It seems to happen only on link from the right up corner.

**Comment by gdh1995** [comment]
@philc , it's enough to just modify 

https://github.com/philc/vimium/blob/5ccd6dc4f2dd081d96bdeb2e71bb4f0b9015b674/content_scripts/vimium.css#L328

into `height: 58px`.

**Comment by philc** [comment]
Doh! I’ll fix tonight and release to chrome store. Great find; kind of
hilarious.

**Comment by lornajane** [comment]
I'm using vimium-ff in firefox and I still see this exact issue - nothing in the right hand quarter of the screen gets labelled. It looks like it updated though - the add-on page says last updated 3 hours ago, and I removed and re-added my add-on. Still no joy. Is there anything I can do to help debug this?

**Comment by gdh1995** [comment]
The lastest version (v1.65.1) works well on my Firefox 72 and Win 10. Have you installed two Vimium from unpacked zip files?

Or try this: [vimium_ff-1.65.1-fx.xpi.zip](https://github.com/philc/vimium/files/4180882/vimium_ff-1.65.1-fx.xpi.zip) (downloaded from https://addons.mozilla.org/firefox/downloads/file/3502765/vimium
_ff-1.65.1-fx.xpi?src=dp-btn-primary)

**Comment by lornajane** [comment]
I installed via the add-ons and have restarted my browser. It is showing 1.65.1 as its version (I'm running Ubuntu) and I'm still missing some links on the right hand side of the screen.

**Comment by gdh1995** [comment]
@lornajane Could you give URL of the page or a screen snapshot? Maybe it is because of another reason.

**Comment by lornajane** [comment]
I can do both! https://www.theguardian.com/uk and screenshot attached
![Screenshot from 2020-02-11 12-42-30](https://user-images.githubusercontent.com/172607/74237757-338adf80-4ccc-11ea-8de2-a576e0073517.png)

**Comment by poacher2k** [comment]
@lornajane : thank you for both screenshot and URL! 

Many of these links have `aria-hidden="true"`, which I assume is the reason the link hints aren't appearing.

**Comment by gdh1995** [comment]
Oh this is just `[aria-hidden]`: ![image](https://user-images.githubusercontent.com/5547703/74241908-e7fe2300-4d17-11ea-8653-93c3dd22d8ed.png)

**Comment by magios** [comment]
issue still exists in firefox and vimium 1.65.1

**Comment by lornajane** [comment]
it's funny, because all the links have the `aria-hidden` property, and sometimes I get hints, sometimes I don't. Scrolling a little in one direction or another sometimes causes more hints to appear, but most of the links further to the right are without hints.
