### ISSUE TITLE
open link in a new tab just opens a blank background tab

### ISSUE THREAD

**Issue by nathgit** [philc/vimium#3487]
The open link in a new tab (F) doesn't work. It only opens a new blank tab (not a foreground tab with the link, a blank background tab). I have tried it over & over thinking maybe it was something I was doing wrong, but it hasn't worked right once since I installed it.

**Comment by gdh1995** [comment]
Are you using Firefox? What version of Vimium do you have? What pages does this issue occurs on?

**Comment by nathgit** [comment]
I'm using an up-to-date chromebook/Chrome on the stable channel. Vimium is version 1.64.6. It happens on all pages. I only installed vimium a few days ago.

**Comment by nathgit** [comment]
I have tried several different pages just now & they all work. I did have A LOT of tabs open before & I don't have as many open now, so I'm thinking that was the cause. I know if I tried to open a link in a new tab with the standard chromebook shortcut when I had a lot of tabs it very often would do that.
