### ISSUE TITLE
Some links missing after second look

### ISSUE THREAD

**Issue by nal-chris** [philc/vimium#3488]
**Describe the bug**
When showing all the links, after the second time some links/buttons on the right side of the page are missing. They are the links that are hidden behind the HUD.

**To Reproduce**
1. Go to any page with links and resize so that some of the links are within 300 pixels of the right hand side of the page.
2. Press "f" to show all the links/buttons on the page (and the HUD in the corner).
3. Press "esc" to clear them.
4. Press "f" again to show all the links/buttons.
5. All the links that are behind the HUD iframe are missing.

![2-press-f](https://user-images.githubusercontent.com/16105234/74138706-fcdc9880-4be9-11ea-9aa5-b12fecff763f.png)
![4-press-f-again](https://user-images.githubusercontent.com/16105234/74138716-ff3ef280-4be9-11ea-883b-c0f17824d9c2.png)
![5-links-missing-behind-HUD](https://user-images.githubusercontent.com/16105234/74138719-00701f80-4bea-11ea-9842-f2a9ed83d808.png)

**Browser and Vimium version**
Browser: Google Chrome - 80.0.3987.87 (Official Build) (64-bit)
OS: macOS Version 10.15.2 (Build 19C57)
Vimium: 1.65

**Comment by gdh1995** [comment]
Seems a duplicate of #3486 .

**Comment by philc** [comment]
@nal-chris What version of vimium do you have? If it's 1.65.1, please confirm that it reproduces on that version. I released that version to the chrome store yesterday to fix this.

**Comment by nal-chris** [comment]
I was on 1.65.0
My browser just upgraded to 1.65.1 today and now everything is working fine.
Thank you.

**Comment by magios** [comment]
issue still exists in firefox and vimium 1.65.1
