### ISSUE TITLE
keyboard shortcuts for visual (& caret) mode?

### ISSUE THREAD

**Issue by nathgit** [philc/vimium#3494]
What exactly can you do in visual mode? I have an idea of how it's used in Vim because of looking it up, but what exactly is possible using this extension? is it simply selecting/copying text (which is certainly useful) or is there more to it than that? Is there a list of keyboard shortcuts for visual mode & what they do?

**Comment by gdh1995** [comment]
In short, modify selection's range and yank (copy) text. Here's a brief introduction: https://github.com/philc/vimium/wiki/Visual-Mode

And the complete list is in https://github.com/philc/vimium/blob/master/content_scripts/mode_visual.coffee#L169-L209 .

**Comment by nathgit** [comment]
Thanks. I was hoping there was more to it than <i>just</i> select & copy.

**Comment by gdh1995** [comment]
Sorry I forgot `find ...`, `new FindMode` and `openUrl***` .
