### ISSUE TITLE
tab doesn't focus, so keyboard shortcuts don't work without clicking on page

### ISSUE THREAD

**Issue by nathgit** [philc/vimium#3497]
Tabs don't seem to focus automatically most of the time, so shortcuts are ignored until I click on an empty area of the page with the mouse which then makes it respond to shortcuts. I have enabled the option to prevent it from  focusing on the text box onload so that's not the problem unless it's just not working. I thought about submitting this as a bug report, but I don't know whether it's an issue with vimium or something that chrome os is blocking or what the problem is. The weird thing is it seems to work sometimes, just not reliably. It appears to work sometimes on github & youtube from the ones I've tried, but not reliably even there.

**Comment by nathgit** [comment]
I have cleared cache & refreshed the pages & they still don't work until I click an empty area on the screen.

**Comment by gdh1995** [comment]
Do you mean tabs created by Control+T or Meta+T (aka. "new tabs")?



---Original---

**Comment by nathgit** [comment]
I mean <b>any</b> tab..If I refresh this page, it would ignore typed shortcuts until I click on the screen somewhere. The weird thing is it apparently blocks up & down arrows too so I can't even use them to scroll up & down until I tap on the page.

**Comment by gdh1995** [comment]
What it will be if you disable all other browser extensions?

If you're using Linux / macOS, you may run `chrome --user-data-dir=/tmp/test_user_data` on a terminal and Chrome will start a new window and use `/tmp/test_user_data` as its main data folder temporarily. Then you can do some tests on such a brand-new Chrome.

**Comment by nathgit** [comment]
I'm using a chromebook but I do have the linux environment installed.

**Comment by gdh1995** [comment]
Oh I mean I personally want a further test result of what Vimium does on a brand-new Chrome. So, a simple way is to disable all other extensions and then test, but it's possible that this issue is caused by not other extensions but your current Chrome settings / installed plugins / runtime flags / command-line parameters and so on.

According to current information, one guess is that an extension injects an tiny / hidden iframe (a small area without visible content) to every tabs and focuses it, so you have to click to move the focus to normal content. To verify this idea, we may open Vimium Options by typing `chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/pages/options.html` to Chrome's address bar and pressing <kbd>Enter</kbd>, and then see whether Vimium can respond at once.

**Comment by nathgit** [comment]
vimium responds immediately on the settings page.

**Comment by nathgit** [comment]
What's strange is sometimes If I refresh the page again then try a shortcut it works. I tried on a few sites  It doesn't always work. I also disabled a couple extensions that I really don't use but I have quite a few extensions so it would be time consuming to test all of my extensions. would the terminal command work on chrome os with linux & is it easily reversible?

**Comment by nathgit** [comment]
I restarted & it seems to be working without having to do anything else. I waited a little bit to post this to make sure but it seems to work.

**Comment by nathgit** [comment]
I had added a few custom shortcuts for actions not mapped to a shortcut already like open in incognito mode, & an alternative to j & k for youtube because those are already mapped to other functions on youtube (j=rewind 15 secs, k=play/pause, l=fast-forward 15 secs.).

**Comment by philc** [comment]
This extension-specific setting in Chrome is related to some of the symptoms you described, in case you mistakenly had it set to "on click":

![image](https://user-images.githubusercontent.com/8598/74479776-a62ec300-4e64-11ea-99c6-0177e403687a.png)

**Comment by nathgit** [comment]
No. It's enabled on all sites. I think I just had to refresh all the pages, & then it started working.
