### ISSUE TITLE
How to disable the "Open link in current tab." hint?

### ISSUE THREAD

**Issue by edwinyzh** [philc/vimium#3510]
Hello,

Thanks for developing this extension which I cannot live without :)
Don't know since when, there is a "Open link in current tab." hint after I press 'F'. How to disable that? It always covers something I need to see on a small monitor.

Thanks.

**Comment by philc** [comment]
#3499 is maybe related, and will go out in the next release.

So we can empathize, can you post a screenshot to illustrate the pain you're feeling?

**Comment by edwinyzh** [comment]
@philc , I couldn't find that webpage to reproduce the issue now, but I remember the issue was that  in the 'f' mode, the big, yellow-background navigation characters were covered by the small "Open link in current tab." panel on the lower-right corner.

**Comment by gdh1995** [comment]
Yes and it's been fixed in #3499, too.
