### ISSUE TITLE
RegEx search broken on Google Chrome

### ISSUE THREAD

**Issue by devnoname120** [philc/vimium#3513]
**Describe the bug**
Whenever I type`/` and then my search query, it only searches as if it were text not a RegEx.

**To Reproduce**
1. Go to https://github.com/philc/vimium
2. Press `/` then type`\w+`
3. No results are found.

![image](https://user-images.githubusercontent.com/2824100/76000241-b259ed80-5f03-11ea-86ea-cb8f8c2ca669.png)

**Browser and Vimium version**

This problem happens in the following configurations:

**Config 1**:

OS: macOS Version 10.15.3 (Build 19D76)
Google Chrome: 80.0.3987.132 (Official Build) (64-bit)
Vimium: 1.66

**Config 2**:

OS: Windows 10 Version 1903 (OS Build 18362.657)
Version 80.0.3987.122 (Official Build) (64-bit)
Vimium: 1.66

---------------------------------

I can confirm that this issue doesn't happen on this configuration:

**Config 3**:

OS: Windows 10 Version 1903 (OS Build 18362.657)
Firefox: 73.0.1 (64-bit)
Vimium: 1.66

**Comment by gdh1995** [comment]
Have you enabled the advanced option of "Treat find queries as JavaScript regular expressions" on Vimium Options page?

Or you may type: `\r\w+` to notify Vimium the `\w+` is an RegExp.

**Comment by devnoname120** [comment]
Thanks, I missed this.
