### ISSUE TITLE
How do change the default search engine for the vomnibar?

### ISSUE THREAD

**Issue by allanwind** [philc/vimium#3514]
If I type something into the vomnibar and press enter it defaults to using the google search engine.  How do I change that (to DuckDuckGo)?  I reviewed the documentation and I didn't see anything relevant.  I was was able to configure a custom search engine but I would like to change the default.

I already configured DuckDuckGo as my default search engine in Firefox 68.5, so it appears to be a vimium specific.

**Comment by gdh1995** [comment]
On the options page of this extension, There are some advanced options, and then you can configure the default search engine.



---Original---

**Comment by allanwind** [comment]
Awesome, thank you.

On 2020-03-05 21:13:24, Dahan Gong wrote:
>On the options page of this extension, There are some advanced options, and then you can configure the default search engine.
>
>
>
>---Original---
>From: "Allan Wind"<notifications@github.com&gt;
>Date: Fri, Mar 6, 2020 07:42 AM
>To: "philc/vimium"<vimium@noreply.github.com&gt;;
>Cc: "Subscribed"<subscribed@noreply.github.com&gt;;
>Subject: [philc/vimium] How do change the default search engine for the vomnibar? (#3514)
>
>
>
>If I type something into the vomnibar and press enter it defaults to using the google search engine.  How do I change that (to DuckDuckGo)?  I reviewed the documentation and I didn't see anything relevant.  I was was able to configure a custom search engine but I would like to change the default.
>
>I already configured DuckDuckGo as my default search engine in Firefox 68.5, so it appears to be a vimium specific.
>
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly, view it on GitHub, or unsubscribe.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/philc/vimium/issues/3514#issuecomment-595603897

-- 
Allan Wind
Yaxto - Runs Your Business
<https://yaxto.com>

**Comment by robinmoussu** [comment]
If like me you didn’t found the advanced options, you have to open the settings of the extension, then click on the "advanced options" button at the bottom of the page.
