### ISSUE TITLE
[FEATURE REQUEST] Go to input box 

### ISSUE THREAD

**Issue by shadyabhi** [philc/vimium#3520]
Just like pressing `f` gives you an option to click a link, do you think it's valuable to have a similar feature for going to a specific input box? 

My use case is, if I open a webpage with a big form, I need an option to directly jump to a specific input.

**Comment by philc** [comment]
`f` should also work for any form input on a page. If it's not, please post a URL and screenshot.

`gi` also takes you to the first text input box on the page.

**Comment by shadyabhi** [comment]
@philc My bad for an invalid issue. :( 

I feel that the document should be updated to reflect this information. Currently, it makes the reader believe that it works for links only. 

The feature works as you described on some public websites as I checked but it's not working for an internal app that I use. Since the issue is not with the extension, I'll go ahead and close the issue. 

Thank you for your help.
