### ISSUE TITLE
Doesn't work properly on new Facebook web UI.

### ISSUE THREAD

**Issue by ysm0622** [philc/vimium#3525]
**Describe the bug**
Some links on the new Facebook web UI are doesn't work properly.

**To Reproduce**
1. Go to URL 'facebook.com'
2. Click on 'Switch to new Facebook'

![Apr-04-2020 16-17-51](https://user-images.githubusercontent.com/18487241/78421180-a42cf780-7690-11ea-87ef-bf8145de0b71.gif)

**Browser and Vimium version**
Firefox, Vimium 1.66

**Comment by brunonar** [comment]
It happens too on Mozilla developer's page. When you try to hit the top menus, it just blinks and do nothing.

Examle: https://developer.mozilla.org/pt-BR/search?q=favicons
