### ISSUE TITLE
"f" does not work when input method is Korean

### ISSUE THREAD

**Issue by taylorchenca** [philc/vimium#3531]
**Describe the bug**
When the input method is Korean (specifically, 2-set Korean on Mac), pressing "f" does not show labels.  

**To Reproduce**
1. Enable 2-set Korean input method on Mac
2. Open any web page on Chrome, like https://www.nytimes.com/
3. Press f
4. You would be able to see that, no labels are shown

**Browser and Vimium version**
Google Chrome: 80.0.3987.163 (Official Build) (64-bit)
OS: macOS Version 10.15.4 (Build 19E266)
Vimium: 1.66

**Comment by gdh1995** [comment]
Please try this:
* open Vimium's options page
* click the `Show Advanced Options` button at the bottom, to show some advanced option items
* find the `Ignore keyboard layout` checkbox and enable it
* save option changes
* try <kbd>F</kbd> again on nytimes

**Comment by taylorchenca** [comment]
> Please try this:
> 
> * open Vimium's options page
> * click the `Show Advanced Options` button at the bottom, to show some advanced option items
> * find the `Ignore keyboard layout` checkbox and enable it
> * save option changes
> * try F again on nytimes

@gdh1995 
That worked! Thank you. 
I will close this issue.
