### ISSUE TITLE
快速跳转某标签页

### ISSUE THREAD

**Issue by StephenWu5** [philc/vimium#3533]
我可以提个需求吗？就是我已经安装了一个插件显示标签页的序号，输入2gt，发现右移两个标签页，我的目的是要跳转到序号为2的标签页。你能实现它吗？

if you can't see my words，you can translate them in google. this question is important to me.

**Comment by gdh1995** [comment]
Please use `firstTab` and it supports count prefix to specify the index.

使用 `firstTab` 即可，支持数量前缀。

注：问题解决了的话，可以点击“Close”关闭这个问题。

**Comment by StephenWu5** [comment]
好的😄
