### ISSUE TITLE
Adding geometric shape unicode characters like these ◄► to goPrevoius/goNext command.

### ISSUE THREAD

**Issue by rp-karanth** [philc/vimium#3537]
I have come stumbled into pages where developers have used these right and left pointing pointers as previous pages in pagination. Can these types be included to trigger them while using '[[' and ']]'.
 These are some code point ranges I found out.
▶ to ▻ U+25B6 to U+25BB ; Right pointers.
◅ to ◀ U+25C5 to U+25C0 ; Left pointers.
← U+2190
→ U+2192
⇐ U+21D0
⇒ U+21D2
⏴ U+23F4
⏵ U+23F5
Can these be added in next version?

**Comment by gdh1995** [comment]
You may open Vimium Options page, click "`Show Advanced Options`" and then configure `Next patterns` and `Previous patterns`.

**Comment by rp-karanth** [comment]
There is no such option in my version `1.66` . Attaching screenshot. Custom key mappings is the one you are suggesting? Could you give an example please.
![sdgdgfgjhj](https://user-images.githubusercontent.com/13714473/79418374-14614480-7fd2-11ea-8b53-2495ad244dfd.PNG)

**Comment by rp-karanth** [comment]
I think the code should be changed in [setings.js](https://github.com/philc/vimium/blob/67a599848d16e389d76979deb30c4ed1a12127b0/lib/settings.js) line 213.

**Comment by gdh1995** [comment]
![image](https://user-images.githubusercontent.com/5547703/79419875-3f579280-7fea-11ea-96a7-f7f7e1020641.png)

Click this first.

**Comment by rp-karanth** [comment]
Oh I didnt observe  this. Problem solved. For sake of completion I will add those arrows here.
▶,▸,▹,►,▻,▷,→ ,⇒ ,⏵ 
◀,◁,◂,◃,◃,◄,◅,←,⇐ ,⏴
