### ISSUE TITLE
Disabling reload by pattern does not disable reload with count

### ISSUE THREAD

**Issue by anstosa** [philc/vimium#3548]
**Describe the bug**
I want to disable `r` to reload on Google Calendar because it reloads already with `r` without reloading the whole tab. That much works, except if I put a number before `r`, that counted reload is not disabled. I frequently use the keyboard combo `4rt` in Google Calendar for "switch to 7 day view, reload, and snap to today".

**To Reproduce**
1. Add rule for `https?://calendar.google.com/*` to disable `r`
2. Go to [https://calendar.google.com]
3. Hit `r` and note that page does not reload (this is correct)
4. Hit `4r` and note that 4 tabs reload (this is a BUG)

**Browser and Vimium version**
Google Chrome 81.0.4044.122
Vimium 1.66

**Comment by gdh1995** [comment]
Well, this is designed to do so: excluded characters works when there's "no prefix keys".

So I guess you can also disable `4` and `t` on Google Calendar to get `4rt` always passed by Vimium.

**Comment by anstosa** [comment]
Oh! I see, it's quite literally keys to ignore. As a new user, seems like it would be more intuitive to ignore keys using the same syntax as the mappings (<c-r> for control, r would ignore r even with a count, etc) but that makes sense. Thank you for clarifying!
