### ISSUE TITLE
Vimium gets disabled randomly, not sure what I'm doing

### ISSUE THREAD

**Issue by byrongibson** [philc/vimium#355]
This is probably a SUE rather than an issue, but the cause of the problem eludes me.  On two sites so far, I've hit some unknown key combination or something that disabled Vimium, and am not sure how to re-enable it.  It was working on these sites and every other one not in my blacklist, then it stopped.  The sites are:

http://www.mongodb.org/display/DOCS/Tutorial
http://www.reddit.com/

I checked to make sure I didn't drop into Insert mode, that's not the problem.  I also checked the command list and Advanced command list, but I don't see any key combination there that would disable Vimium, so no idea what caused this.

Any ideas?

**Comment by rrsahu** [comment]
For price range never compromise on your needs and specifications. You can request them to shift your workplace as well.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by rrsahu** [comment]
Once you have decided about Company and have already Professional for solutions then one of the representatives from Company will visit your house. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers Delhi">Packers and Movers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>

**Comment by rrsahu** [comment]
He will note down information of all your individual valuables that should be loaded and shifted. Once he has note down everything, he will provide the same information to Company as well.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers Chennai">Packers and Movers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers Noida">Packers and Movers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers Navi Mumbai">Packers and Movers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers Thane">Packers and Movers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers Ghaziabad">Packers and Movers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers Faridabad">Packers and Movers Faridabad</a>

**Comment by rrsahu** [comment]
This will help the Company in deciding final price for the project. It is depending on weight of outstanding, variety of products, kind of products and range as well. Extra expenses will be taken for automobile transportation. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>
