### ISSUE TITLE
In the search mode, the screen does not move when querying the next one

### ISSUE THREAD

**Issue by edte** [philc/vimium#3557]

**Comment by BachoSeven** [comment]
I can confirm this bug using `master` version and `Chromium`: after querying a search, the interface seems to freeze; I cannot use `n` or `N` to move around the searched instances; and pressing `Esc` does not allow me to move around with `j` and `k`; it only unfreezes if I use the mouse to click on an empty zone to unselect the highlighted query text.

**Comment by ggVGc** [comment]
Yep, confirmed here too

**Comment by RagnarGrootKoerkamp** [comment]
It took some debugging, but I think I've found the fix for this: #3847.

**Comment by philc** [comment]
Thanks Ragnar! I’ll take a look and merge this weekend.
