### ISSUE TITLE
Vomnibar does not display any bookmarks in Firefox 76.0

### ISSUE THREAD

**Issue by jjzmajic** [philc/vimium#3558]
**Describe the bug**
Vomnibar does not display any bookmarks in Firefox 76.0. Both `b` and `B` are broken.

**To Reproduce**
Press `b` or `B` in Firefox 76.0. Note that there are no bookmarks regardless of the search pattern. The bookmarks are still there the user's toolbar.

Include a screenshot if applicable.
It's just an empty vomnobar with no candidates

If you're using Firefox, report the Firefox and OS version found at about:support. Also include the Vimium version found at about:addons.

Firefox about:config
```
Name | Firefox
-- | --
76.0
20200506004813
Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0
Linux 5.4.35-1-lts
2/2               Enabled by default
9
Inactive
Found
Found
Found
false
```

Vimium 1.66, {d7742d87-e61d-4b78-b8a1-b469842139fa}

**Comment by gdh1995** [comment]
Sorry but I can not reproduce this issue on Firefox 76.0.1 (20200507114007, Win 10 x64), which was downloaded from http://ftp.mozilla.org/pub/firefox/releases/76.0.1/win64/zh-CN/Firefox%20Setup%2076.0.1.exe

**Comment by jjzmajic** [comment]
Hmm, the issue appears to have gone away after a system restart, though it persisted across Firefox restarts. Could it be that the plugin had a problem with Firefox being updated in the background? That's what happened when the problem arose.

Closing this as it would be an absolute devil to track down, even if it is a problem on Vimium's end, which I doubt.
