### ISSUE TITLE
Exclusion keys UI doesn't not work since the ES6 conversion

### ISSUE THREAD

**Issue by philc** [philc/vimium#3566]
I regressed this during the port from coffeescript to javascript in #3459.

1. The Vimium toolbar icon, when clicked, shows all passkey rules, rather than just the ones associated with the current page.
2. Adding a new rule and clicking save does not work.

I'm sure it's an easy fix.

**Comment by gdh1995** [comment]
ES6 class requires calling `super(...)` first, but in pages/options.js:176, `this.url = url` executes after `populateElement` has been called by the constructor of its base class.

We should delay `this.fetch();` in line 21, so that `fetch` will use complete instances.

**Comment by philc** [comment]
Great spot @gdh1995! Thanks.
