### ISSUE TITLE
Scrolling does not work in Notion

### ISSUE THREAD

**Issue by GauthamGoli** [philc/vimium#3574]
**Describe the bug**
Notion is a tool used by many companies, the scrolling function with keys J,K does not work
**To Reproduce**
1. Go to URL https://www.notion.so/Journal-template-9d753b3d4cda4f16a8b21914ebad6341
2. Try to scroll 

Include a screenshot if applicable.

Google Chrome | 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | macOS Version 10.15.4 (Build 19E287)

Vimium Version: 1.66

If you're using Chrome, include the Chrome and OSS version found at chrome://version. Also include the Vimium version found at chrome://extensions.

If you're using Firefox, report the Firefox and OS version found at about:support. Also include the Vimium version found at about:addons.

**Comment by gdh1995** [comment]
If you click `Journal template` then Vimium can scroll the page.

The below text are in invisible editable textbox, so if you click them Vimium will enter the Insert mode and most commands will not work.

**Comment by GauthamGoli** [comment]
`Journal template` is not clickable for me.

**Comment by gdh1995** [comment]
Um, I mean "click it using a mouse".

**Comment by GauthamGoli** [comment]
I tried that.

**Comment by GauthamGoli** [comment]
Oh sorry, I clicked on the wrong `Journal Template`

**Comment by YusufGandhi** [comment]
I am facing the same issue. Any Notion based websites automatically disable Vimium (see the screenshot. I didn't put any rule, but Vimium already excludes Notion URL. Is this expected?

![image](https://user-images.githubusercontent.com/2329909/92130037-778f2e80-ee2e-11ea-8b27-ccea9586bbd8.png)

**Comment by gdh1995** [comment]
&nbsp;This image means that the Vimium is not disabled - it will be disabled if you click 'save'.


&nbsp;Usually this is because it's in the insert mode.&nbsp; I as said above,&nbsp; this page abuses the 'contenteditable' attribute,&nbsp; and as a result Vimium have to disable itself when some content text gets focus.



---Original---
