### ISSUE TITLE
Tab is opened twice

### ISSUE THREAD

**Issue by james64** [philc/vimium#3579]
**Describe the bug**
I do not know whether issue is on vimium's side. I would like to ask for help determining that. See below for issue description.

**To Reproduce**
1. Go to `qwant.com` search engine
2. Enter a search term of your choice
3. When a result is clicked by mouse or is opened by vimium into separate tab (f shift \<code\>) everything is ok
4. If however a link is opened by vimium into this tab (f \<code\>) then new tab is opened **twice** in two separate new tabs. Issue is not about opening in new tab vs this tab. But it should not be opened twice.

**Browser and Vimium version**
Firefox - 76.0.1
OS - Linux 4.19.122-1-MANJARO
Vimium - 1.66

Please let me know if I can help debugging this.

**Comment by gdh1995** [comment]
Usually Firefox has a strict popup-window blocker, which will block Vimium's requests of clicking a link and opening a new tab for it. To work around it, Vimium has used a special part of code to create a tab with the link's URL (using web-extension APIs, which is not blocked).

According to what you met, it seems that this blocker has some changes and now passes Vimium's normal requests (the one using not web-extension APIs but "clicking" event). Maybe it's because of a special browser setting, a special flag in `about:config`, an environment variable, or something unexpected else.

**Comment by lydell** [comment]
> To work around it, Vimium has used a special part of code to create a tab with the link's URL (using web-extension APIs, which is not blocked).

@gdh1995 Can you link to that piece of code, please? I’m curious how it works :)

**Comment by gdh1995** [comment]
https://github.com/philc/vimium/blob/6aecf63544ab7371867537ad8caf8429d1410af4/lib/dom_utils.js#L323-L337

**Comment by lydell** [comment]
Cool, thanks! I’m not sure if it helps, but I’ve implemented workarounds for Firefox’s popup blocker too: https://github.com/lydell/LinkHints/blob/efa18fdfbf95016bd706b83a2d51545cb157b440/src/worker/Program.js#L1337-L1631

**Comment by james64** [comment]
@gdh1995 that also explains why firefox was showing me those popup-blocked msg even though there was no pop-up in sight. Seeing that msg I explicitly allowed popus from qwant. That's why normal request passed.

Removing qwant from white list indeed stops second tab from opening. I get that popup-block msg back. I need to dont-show-this-msg to remove it. 

Follow-up questiion. Is there a simple way to explain why this yellow block msg is not happening on all sites?

**Comment by gdh1995** [comment]
If a page hooks `click` events and use JavaScript code to do some UI changes, then there may be no block message.

This often occurs when JavaScript code (including those of extensions) wants to trigger `<a target="_blank">`, though I'm not sure whether Firefox blocks on all such types of pages or not. Compared with Chrome, Firefox has too many limits on web-extensions.

**Comment by james64** [comment]
Thanks for all the information!

**Comment by lydell** [comment]
I don’t think this issue should be closed. It _is_ possible to avoid the double-open and popup blocker (it works in my extension).

**Comment by gdh1995** [comment]
@lydell, the way of adding click listener on all items in `event.path` looks a bit long and too tricky, and:
* it can not work if a host script caches methods like `Event.prototype.preventDefault`
* it can not work if another extension register some listeners on the event instance.

**Comment by lydell** [comment]
Yes, it’s not perfect but it does work in a lot of situations. 🤷‍♂️

**Comment by Artturin** [comment]
this is happening to me on github now. started today or yesterday

**Comment by s-marios** [comment]
> this is happening to me on github now but instead it happens when i open a link into a new tab. started today or yesterday

Can confirm, I'm also affected on Firefox Nightly.
