### ISSUE TITLE
How to map hash (#) and quotes (") keys?

### ISSUE THREAD

**Issue by kurka** [philc/vimium#3581]
Given that both hash (#) and quotes (") are comment delimeters in custom key map field, how do I escape them, so I can map them to commands?

I tried the following, but with no success:

```
map # Marks.activateGotoMode
map \# Marks.activateGotoMode
map <#> Marks.activateGotoMode
```

Is this possible?

**Comment by gdh1995** [comment]
`map # Marks.activateGotoMode` should work. Do you use the English's QWERTY keyboard layout? What's your system and browser and browser version?

**Comment by kurka** [comment]
you are right, simple `map # Marks.activateGotoMode` indeed works. I'm not sure what went wrong yesterday, I think I was doing other changes, and this one did not take effect, or I simply failed noticing it.

Just for the record, I'm on Arch Linux, Firefox 76.0.1, using international-us keyboard.

Closing this as it's not an issue anymore.
