### ISSUE TITLE
Wrong search URL when searching with Vomnibar ('o') on Firefox with DuckDuckGo

### ISSUE THREAD

**Issue by jzhanson** [philc/vimium#3594]
When using the Vomnibar shortcut ('o') to search my default search engine DuckDuckGo, the keyword "search" is passed to DuckDuckGo regardless of what the entered text was.

1. Press 'o' to bring up omnibar
2. Enter search text.
3. Press enter.

Through Vomnibar:
<img width="755" alt="through_vomnibar" src="https://user-images.githubusercontent.com/22418440/84049668-b706c580-a97a-11ea-89c8-195e6e6291b5.png">

By typing into the Firefox search bar:
<img width="888" alt="through_search_bar" src="https://user-images.githubusercontent.com/22418440/84049671-b79f5c00-a97a-11ea-9d29-3fa771319841.png">

Firefox version 77.0.1, OS Darwin 16.7.0
Vimium version 1.66

**Comment by gdh1995** [comment]
What's your settings of `custom search engine` on the Vimium Options page?

It seems that DuckDuckGo refuses URLs like `https://duckduckgo.com/search?q=vimium`, and only expects `https://duckduckgo.com/?q=vimium` (no "`search`").

**Comment by jzhanson** [comment]
Ah, I had to change `Default Search Engine` to `https://www.duckduckgo.com/?q=`, thanks! Closing.
