### ISSUE TITLE
How to choose which scrolling column to scroll with jk? (Without using the mouse)

### ISSUE THREAD

**Issue by andre-fernando** [philc/vimium#3596]
Say you have a page with 3 scrollable columns in a row, if you use j /k then the first column will scroll. But to scroll the other columns you either have to click with the mouse to change focus or use / to search for a word in the other column and then use n to get the next scroll view into focus. Is there a simpler way to do this?

**Comment by gdh1995** [comment]
Press `f` and select a mark which is at the top-left corner of a scrollable area, and then you can scroll it with Vimium's commands like `j` and `k`.

**Comment by andre-fernando** [comment]
> Press `f` and select a mark which is at the top-left corner of a scrollable area, and then you can scroll it with Vimium's commands like `j` and `k`.

Thank you.

**Comment by rmf10003** [comment]
it seems like there is not always a mark in the top left of a scrollable section

**Comment by greg-nagy** [comment]
https://nextjs.org/docs/app/api-reference/file-conventions/middleware

how can I use this here?

**Comment by Bootjan** [comment]
>it seems like there is not always a mark in the top left of a scrollable section

Experiencing this as well. Has there been a fix thus far? Or is it planned. It would be a great improvement IMO

**Comment by HunterWhiteDev** [comment]
Is there a way to switch from the scrollable container back to scrolling the whole page? I was trying this on Indeed and they have the job description on the right which I can press f and select the right container to scroll but I dont see one to go back to scrolling the whole page
