### ISSUE TITLE
Jump to global mark should focus window containing target tab

### ISSUE THREAD

**Issue by hstalker** [philc/vimium#3599]
Jumping to a global mark does not also focus the window within which the target tab is located (but it *does* activate the marked tab within the target window as expected). This forces the user to switch windows via window manager in order to focus the target window.

It is unclear whether this is the desired behaviour, but it makes marks less useful for navigation when multiple shared-session browser windows are in use (which may be fairly common on multi-monitor setups).

**To Reproduce**
1. Create a window A.
2. Mark default tab A in window A via `mA`.
3. Create a tab B in window A, and focus tab B.
4. Create a new window B, and focus window B.
5. Attempt to jump to window A, tab A via `` `A``.
6. Notice that window B remains focused, but when changing windows via other means (e.g. the window manager), then in window A tab A is now focused.

**To Fix**
From a cursory glance, a fix could be akin to adding something similar to `chrome.windows.update(windowIdOfTab, {focused: true});` at `background_scripts/marks.js:75-76`, where `windowIdOfTab` would need to be obtained from the target `tabId`.

**Browser and Vimium version**
Firefox version 77.0.1
Vimium-ff version 1.66

**Comment by gdh1995** [comment]
Confirmed, and I've filed #3600 to fix it.

**Comment by philc** [comment]
Great work @hstalker for the well-written report, and @gdh1995 for the fix!

**Comment by danielyaa5** [comment]
this no longer works
