### ISSUE TITLE
n and N do nothing (Firefox, Ubuntu)

### ISSUE THREAD

**Issue by Dante-Isler** [philc/vimium#3614]
**Describe the bug**
After searching for text with `/<some text><ENTER>` `n` and `N` ought to jump to respectively the next and previous occurrences of `<some text>`. Instead, however, they do nothing.

**To Reproduce**
1. Go to URL `example.com`
2. Type `/am<ENTER>`
3. Type `n`
What ought to happen: jump to the next occurrence of `am`
What actually happens: nothing

The screenshot shows before and after step 3 (webpage is dark because of Dark Reader extension).
![Vimium-Firefox-bug-n-N-do-nothing](https://user-images.githubusercontent.com/66245629/86451090-4f8e2c80-bd12-11ea-9669-7e3eb2860a96.png)

**Browser and Vimium version**

about:support
Name: Firefox
Version: 78.0.1
Build ID: 20200630195452
Distribution ID: canonical
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
OS: Linux 5.4.0-40-generic
Application Binary: /usr/lib/firefox/firefox

about:addons
Version: 1.66
Last Updated: 3 July 2020

**Comment by sid-maddy** [comment]
@Dante-Isler, do you face this issue in normal windows or only in private windows?

**Comment by philc** [comment]
This should be fixed in c85940642292f2c5edd0fd41397d6d866041d488.
