### ISSUE TITLE
Advanced options on firefox: Cannot restore from backup

### ISSUE THREAD

**Issue by kiprasmel** [philc/vimium#3623]
The "Backup and Restore" section's `Restore` button for browsing files is broken/disabled or something and thus does not allow to restore from backup.

**Comment by antonalekseev** [comment]
Can confirm this one. Tested on macOS with FF 78.0.1 (64-bit) and 80.0a1 (2020-07-09) (64-bit). By the way not only `Restore` button is affected but `x` buttons at the end of row in `Excluded URLs` table are "disabled" as well.
<img width="562" alt="Screenshot 2020-07-09 at 20 39 00" src="https://user-images.githubusercontent.com/2895684/87072979-2d157b00-c20c-11ea-86a7-cdbdd2853c1d.png">
<img width="465" alt="Screenshot 2020-07-09 at 20 39 21" src="https://user-images.githubusercontent.com/2895684/87072983-2e46a800-c20c-11ea-8e63-e2f447af8b7b.png">

**Comment by fekfoq259** [comment]
Same issues on Windows 10 Firefox 81.0

**Comment by edisondotme** [comment]
Me too. FF 84 on Linux.

**Comment by mcp292** [comment]
Firefox 87 Arch Linux.

**Comment by mcp292** [comment]
> By the way not only `Restore` button is affected but `x` buttons at the end of row in `Excluded URLs` table are "disabled" as well.

Temporary fix https://github.com/philc/vimium/issues/3678#issuecomment-818377049
