### ISSUE TITLE
Vimium is disabled when a closed window is reopened

### ISSUE THREAD

**Issue by taylorchenca** [philc/vimium#3627]
**Describe the bug**
Vimium is disabled when a closed window is reopened. 
This issue is found on macOS Chrome. 

**To Reproduce**
1. Open new window on Chrome (Command + N on mac) 
2. Go to any URL (https://news.ycombinator.com for example) 
3. Confirm that Vimium is enabled (icon is blue)
4. Close window (Command + W on mac) 
5. Reopen window (Command + Shift + T on mac) 
6. Confirm that Vimium is disabled (icon is grey)

Screenshot of Vimium working normally (before window is closed) 
![image](https://user-images.githubusercontent.com/11932594/87384432-98cf4f00-c550-11ea-967a-62fb7136883f.png)

Screenshot of Vimium disabled (after window is closed and reopened) 
![image](https://user-images.githubusercontent.com/11932594/87384511-cb794780-c550-11ea-9dd7-2aeb3ee3c5a6.png)

**Workaround**
Refresh the page and Vimium would be enabled again. 

**Browser and Vimium version**
Google Chrome: 83.0.4103.116 (Official Build) (64-bit)
OS: macOS Version 10.15.5 (Build 19F101)
Vimium: 1.66

**Comment by gdh1995** [comment]
It seems that you need to click the page content to activate Vimium, so I think it's an issue about how a browser moves focus.

**Comment by taylorchenca** [comment]
Thank you for your comment. 

Your suggested workaround is valid. 

Do you think it is feasible to make it such that one does not need to click the page to activate Vimium? I use Vimium to reduce mouse usage as much as possible.

**Comment by gdh1995** [comment]
Extensions have no APIs to solve this.. You may press <kbd>Tab</kbd> for several times to move focus to a page.

**Comment by taylorchenca** [comment]
That is also a good workaround. 

<kbd>Command</kbd> + <kbd>Option</kbd> + <kbd>↑</kbd> also moves focus to the page and activates Vimium.
