### ISSUE TITLE
Generating link hint is slow on macOS 10.15.6 due to low hit test performance

### ISSUE THREAD

**Issue by crierr** [philc/vimium#3630]
**Describe the bug**
After an update to macOS 10.15.6, showing link hint on YouTube is very slow and makes a page unresponsive.
For most of sites, it works fine but it looks like some specific elements on YouTube triggers the issue.

The profile shows that most of time is consumed for hit testing.
It took 35s to show link hints. (There were 144 visibleElements in the page.)
![image](https://user-images.githubusercontent.com/4330940/87849865-fa176980-c926-11ea-9651-4d18c35fa34f.png)

As Vimium does, I tested `document.elementsFromPoint` in the dev tools console.
It took long on a specific position, which was 790, 1057 in my case. It eventually returned 25 elements but took a few seconds. `elementFromPoint`, which returns only top-most element, returned immediately.
![image](https://user-images.githubusercontent.com/4330940/87849494-15cd4080-c924-11ea-9bb4-dbf3ffc44620.png)

I wonder if it can be changed to use `elementFromPoint` over `elementsFromPoint` for better performance. https://github.com/philc/vimium/blob/master/content_scripts/link_hints.js#L1023

This actually seems like an issue of Chrome on macOS.
It wasn't reproduced on Windows 10 or previous version (<10.15.6) of macOS.
I updated my second macbook air to 10.15.6 for confirming that. The issue was not reproduced before the update, but I was able to reproduce the issue on my second mac after the update.

**To Reproduce**
1. Go to URL https://www.youtube.com/?feature=youtu.be
2. Scroll down until you see 'Latest YouTube posts'. You may not see this if you're not logged in.
3. Press 'f'

It should take long and the page is unresponsive until link hint appears.

**Browser and Vimium version**
Google Chrome: 84.0.4147.89 (Official Build) (64-bit)
OS: macOS Version 10.15.6 (Build 19G73)
Vimium: 1.66

**Comment by gdh1995** [comment]
We can do prefer `elementFromPoint`, but this is only a work-around and may fail on some more complex page.

It seems that we can file an issue for Chromium on https://bugs.chromium.org/p/chromium/issues/ .

**Comment by diegomichel** [comment]
Similar issue in windows:

![image](https://user-images.githubusercontent.com/848433/89047888-4a6dce80-d30c-11ea-87dc-fcf03b2f9f08.png)

Chrome Version: Version 84.0.4147.105
OS Windows 10 (19041.388)
Vimium 1.66
