### ISSUE TITLE
Vimium-FF – Some buttons in options screen do not work

### ISSUE THREAD

**Issue by JulianDeal** [philc/vimium#3634]
When I use vimium-FF on Firefox (78.0.2), in the options screen I can't click on the delete button (x) in the "Excluded URLs
and keys" section and I can't click on the "Browse..."-button in the "Backup and Restore"-section. So I'm not able to import any settings. Chrome is working totally fine.

**Comment by gdh1995** [comment]
fixed by #3624, which is waiting for merging.

**Comment by FranklinYu** [comment]
Before that fix is deployed, there seems to be a workaround for the delete button: remove the URL field, making it an invalid entry, and click “save”. This seems to remove that rule.

**Comment by Kwbmm** [comment]
A workaround, that should address the issue regardless of the element type, is to manually change the CSS of the affected element, for example the `Browse` button to import the setting:

  1. Right click on the `Browse` button
  2. Inspect element
  3. Select the `input` html element (if it's not already selected)
  4. On the `element` CSS insert a new property `pointer-event: all`

Button should be clickable. Of course, as soon as you refresh the page, the change will be lost and the button will be unclickable. But at least you can import your settings

**Comment by andruyd** [comment]
Coming from Fedora 33 with Firefox 86 (latest distro release), I'm unable to click on "Browse" to restore my configuration.

**Comment by andruyd** [comment]
> A workaround, that should address the issue regardless of the element type, is to manually change the CSS of the affected element, for example the `Browse` button to import the setting:
> 
>     1. Right click on the `Browse` button
> 
>     2. Inspect element
> 
>     3. Select the `input` html element (if it's not already selected)
> 
>     4. On the `element` CSS insert a new property `pointer-event: all`
> 
> 
> Button should be clickable. Of course, as soon as you refresh the page, the change will be lost and the button will be unclickable. But at least you can import your settings

Coming from Fedora 33 with Firefox 86 (latest distro release), I'm unable to click on "Browse" to restore my configuration.
Thanks it kinda work with a minor issue.
`pointer-event: all` doesn't work
![image](https://user-images.githubusercontent.com/8880522/109436247-8be76900-7a16-11eb-9f16-aa0e08541f40.png)

`pointer-events: all` works
![image](https://user-images.githubusercontent.com/8880522/109436261-a6b9dd80-7a16-11eb-97ba-185ca2d1fe98.png)
