### ISSUE TITLE
Number + gt moves number tabs forward, instead of jumping to the number-th tab.

### ISSUE THREAD

**Issue by stephen-huan** [philc/vimium#3635]
**Describe the bug**
If I'm on the 5th tab, and I type "2gt", then I'll be sent to the 7th tab.
This is inline with repetition, but what should happen is I should be sent to the 2nd tab.
From :help tabpage.txt
`{count}gt	Go to tab page {count}.  The first tab page has number one.`

**To Reproduce**
Go on a tab.
Type a number and then "gt", it will move you forward that number of tabs. 

**Browser and Vimium version**

Google Chrome: 84.0.4147.105 (Official Build) (64-bit)
OS: macOS Version 10.15.5 (Build 19F101)
Vimium: 1.66

**Comment by gdh1995** [comment]
In Vimium, `gt` means to go one tab right, while `g0` means to go to the first (or N-th).

You may see such default key bindings by press <kbd>?</kbd> on a normal page. Some commands are "advanced" and you'll need to click "show advanced commands" to see them.

**Comment by stephen-huan** [comment]
I can get g0 and g$ to work but g{count} doesn't work,
for example g1 doesn't bring me to the second tab
and g2 doesn't bring me to the third tab.

Am I doing something wrong?

**Comment by gdh1995** [comment]
Oh Vimium doesn't support count after keys, while only `N+keys` can be parsed.

**Comment by avielsh** [comment]
3g0 will talk you to the third tab
3g$ will take you 3 tabs backwards from the last

**Comment by stephen-huan** [comment]
Thank you!
