### ISSUE TITLE
Preserving formatting when yanking text

### ISSUE THREAD

**Issue by atsalolikhin-spokeo** [philc/vimium#3636]
Hello!  I just tried yanking text in visual mode, and it appears that what I get is plain text -- in other words, I lose the formatting.

In this case, I need the formatting.

Is there any way to yank text from a Web page without losing formatting?

**Comment by gdh1995** [comment]
Um, currently Vimium doesn't provide such a command / sub-command to do so.

**Comment by atsalolikhin-spokeo** [comment]
Okay, and thank you very much for your quick reply.

I would like to request that feature, please.

As a user of Vimium, I would like to be able to copy my daily standup report (which is formatted with heading, bullet items, and indented lists (if additional level of detail is warranted) from one tab into another, to email to my co-workers.

I edit my daily standup report in Vim on the CLI, in Markdown, and then use pandoc to convert it to HTML, to add the formatting. 

Without Vimium, I have to use my mouse to select the text.

I love the idea of being able to do it all in the keyboard, I reckon it'd be faster than having to break my flow to reach for the mouse.

**Comment by gdh1995** [comment]
Um, I just find this: why not try using <kbd>Ctrl+C</kbd> (or Command + C on macOS) to copy rich text?

**Comment by atsalolikhin-spokeo** [comment]
Hey! Using Command + C worked!  Thank you!!  :)
