### ISSUE TITLE
Navigating through tabs in Google Chrome and Prefix Count Arguments support.

### ISSUE THREAD

**Issue by politicus** [philc/vimium#3637]
Pinned tabs are not included as tabs when using a prefix. 

For example, if I am in the leftest and only pinned tab, typing `3K` (which equals to three times "Go one tab right (nextTab)") will open the third non pinned tab. 

Google Chrome v84.0.4147.105

**Comment by gdh1995** [comment]
`nextTab` means to go from the first tab to the fourth one, so it seemed to work well, doesn't it?

Do you want a command like `fourth` ?

**Comment by politicus** [comment]
If the focus is on the first pinned tab and I hit `nextTab` the second tab, pinned or not, is selected.

**Comment by gdh1995** [comment]
I mean, when `nextTab` is mapped to `K`, then `3K` will go from the 1st tab to the 4-th one (whether or not they're pinned).

If you map a key (like `J`) to `firstTab`, then `3J` will go to the 3rd tab whereever you are currently in.

**Comment by politicus** [comment]
That makes so much sense! Thank you! Would be great to add this gem to the documentation.
