### ISSUE TITLE
Seems to conflict with "video speed controller" chrome extension

### ISSUE THREAD

**Issue by Yu-yun-cong** [philc/vimium#3639]
**Describe the bug**
Hi,there.I've been using [video speed controller](https://github.com/igrigorik/videospeed) and vimium the same time.I like them both.
Personally I like the shortcut   (**z**  for Rewind **x**  for Advance) in **video speed controller**.After unmapping  **x**  in Vimium, I can use **x** normally.But however it seems that I can't use **z** to rewind online videos even after I unmap the key **z** on the Vimium.

Chrome 84.0.4147.105
Vimium v1.66

**Comment by gdh1995** [comment]
In Vimium's default key mappings, there's no `z` but `zH` (`scrollToLeft`) and `zL` (`scrollToRight`), so you need:
```
unmap zH
unmap zL
```

**Comment by Yu-yun-cong** [comment]
My bad :-(  ,   I tried **unmap z*** before,but not **zH** or **zL**. Thanks a lot.
