### ISSUE TITLE
"Feeling lucky..." custom search engine redirects to a redirection warning page in Brave browser.

### ISSUE THREAD

**Issue by politicus** [philc/vimium#3642]
**Describe the bug**
Sat the "Feeling lucky..." search engine keyword in Vimium options,
Fired the "Open URL, bookmark or history entry" keyboard shortcut,
Typed the "Feeling lucky..." search engine keyword and my query,
Hit enter,
Was redirected to a redirection warning web page.

Tried several times. Same result.

**Browser and Vimium version**
Brave Browser v84.1.11.104 (111.104)
Vimium 1.66

**Comment by gdh1995** [comment]
It seems The search engine still works as expected, and what you saw is just a middle page from Google website. According to its content, I think this page wants to give you a chance to close it, so that you won't directly see another site that you don't like.

**Comment by politicus** [comment]
Thank you @gdh1995! I think I needed to use the feature a little bit more to fully understand how it works 👍
