### ISSUE TITLE
LinkHints.activateMode action=hover doesn't show the hovered link.

### ISSUE THREAD

**Issue by politicus** [philc/vimium#3644]
I sat the  LinkHints.activateMode to action=hover in my settings expecting to see the url of the hovered link at the left bottom of my browser. 

I only saw a little grey pane saying "hover link" at the right side of my browser. 

Am I missing something? 

Vimium 1.66
Brave Browser v84.1.11.104 (111.104)

**Comment by gdh1995** [comment]
This command is only to tell "JavaScript code of the host page" to "do something because this element is hovered", but  it can not affect a browser's default behaviors.

**Comment by mcint** [comment]
Use `focus` mode instead. https://github.com/philc/vimium/issues/320#issuecomment-1883960443
