### ISSUE TITLE
firefox 80 steals focus to url bar opening a new tab via the "t" key 

### ISSUE THREAD

**Issue by kungfubeaner** [philc/vimium#3652]
firefox 80 steals focus to url bar opening a new tab via the "t" key 
this is while having a customized home page and using the
"new tab home page"  firefox extension

**Comment by gdh1995** [comment]
According to https://addons.mozilla.org/en-US/firefox/addon/new-tab-homepage :

> **Firefox 57+ users**
> 
> Please note, I am aware of the problem of the cursor being placed in the location / URL bar, at the start of the URL. I have filed bug 1411465 for this issue, which needs a Firefox / API fix. Unless anyone has any bright ideas, it seems I can't do much about this from the add-on right now.

This issue is not a bug of Vimium, but just because Firefox lacks an expected feature.

**Comment by kungfubeaner** [comment]
Thanks for the info I will close this issue then.

**Comment by kungfubeaner** [comment]
Hell

> According to https://addons.mozilla.org/en-US/firefox/addon/new-tab-homepage :
> 
> > **Firefox 57+ users**
> > Please note, I am aware of the problem of the cursor being placed in the location / URL bar, at the start of the URL. I have filed bug 1411465 for this issue, which needs a Firefox / API fix. Unless anyone has any bright ideas, it seems I can't do much about this from the add-on right now.
> 
> This issue is not a bug of Vimium, but just because Firefox lacks an expected feature.

I was thinking of a way to solve this and I was thinking.   If we could have an option to remap  "t"  to  open your home page the way  O <url here> does it.    I notice this doesn't steal focus from me when  i type   "O search.yahoo.com"    and  t opens a new tap for me which is search.yahoo.com  in the first place. so  maybe this could serve as a work around?   just an idea.

**Comment by gdh1995** [comment]
On Vimium Options page, click the "show advanced options" button to show all options, search `New tab URL` and then modify the URL and save.

**Comment by kungfubeaner** [comment]
> 
> 
> On Vimium Options page, click the "show advanced options" button to show all options, search `New tab URL` and then modify the URL and save.

Thank's a lot sir
