### ISSUE TITLE
firefox 80 won't let you hit the browse button in options to restore settings from a backup file

### ISSUE THREAD

**Issue by kungfubeaner** [philc/vimium#3653]
firefox 80 won't let you hit the browse button in options to restore settings from a backup file

**Comment by gdh1995** [comment]
Yes this is a bug since Firefox 78, and #3624 fixes this.

**Comment by kungfubeaner** [comment]
thanks will close this issue then.

**Comment by fekfoq259** [comment]
Same issue on Windows 10 Firefox 80.0.1. "Restore"  button no response.
