### ISSUE TITLE
Something is wrong with / search function

### ISSUE THREAD

**Issue by panltc** [philc/vimium#3654]
I can't use the search function

1. press `/`
2. press `sth`
3. press `enter`
5. nothing happened and vimium becomes invalid, no buttons can be pressed unless i click the mouse, btw I can use ctrl + w to close the tab.

**Browser and Vimium version**
Browser version: 85.0.4183.83
Vimium version: 1.66

**Comment by gdh1995** [comment]
Is the version you are using the master one, or v1.66 on Chrome Web Store?

The master version is still in development and there's indeed a bug when exiting FindMode but lacking a text box to focus.

**Comment by panltc** [comment]
> Is the version you are using the master one, or v1.66 on Chrome Web Store?
> 
> The master version is still in development and there's indeed a bug when exiting FindMode but lacking a text box to focus.
