### ISSUE TITLE
Map issue

### ISSUE THREAD

**Issue by happysmile12321** [philc/vimium#3657]
Hi,I want to call chrome right menu,I see the short-key is Shift + F10.So I want to map in vimium,is where a way I can do this?
I try this:
``
map z      Q\<F10> 
# which I thought,Q is include Shift,and I type in shift+q+\<F10> ,then chrome called right menu.but It not work in this.
# so I try to figure out if the map <F*> is work,I try this:
 map \<F11> scrollDown
# ok,it seems F11 works .(scrooldown when press F11 but not maxium)
# so I want to do this:
map q \<F11>
# it looks like that the right hand is only work if it is function of this plug.
``
So I want to ask about this.Is the way I do wrong?Or Author can enhance it?

**Comment by happysmile12321** [comment]
By the way,I use this command to know map's 2th args is in the code:
find . -type f -exec  sed -n '/scrollDown/p' {} \;

**Comment by gdh1995** [comment]
1. Vimium's `map` can not be used to trigger Chrome's inner functions. Neither do other web extensions.
2. `map q <f11>` is not a valid mapping: if you want a key to work like another key, then you may need `mapkey q <f11>`
3. If a mapping looks valid but doesn't work, maybe it is overridden by some other customized mappings of yours.
