### ISSUE TITLE
“Too many” permissions required

### ISSUE THREAD

**Issue by klmr** [philc/vimium#366]
The new version of Vimium (1.28) was automatically disabled by Chrome because it required additional permissions.

It would be nice if it included a short notice on _why_ these permissions are in fact required.
- My data on all websites
- My bookmarks
- My tabs and browsing activity

This may simply be Chrome’s formulation but this sounds like an awful lot of trust I’m placing in a plugin that should “merely” hook to certain keystrokes.

Note: I’m not objecting to the fact that Vimium requires these permissions. I’m merely pointing out that it sounds scary, and should be properly explained to the user, lest it creates a culture of always clicking “OK”, no matter what data a plugin wants to access (which is precisely what Chrome wants to prevent, for good reasons).

**Comment by rajeevksahu** [comment]
They deal with all the factors and did not allow them to crack or misplace. You will discover all the factors as you leave them. We are listed as Packers and Movers Services in Bangalore . We also provide our alternatives to the encompassing places too like Bangalore , Bangalore , Andheri, east aspect, etc.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
We take guarantee for your baggage and shift it very professionally. Car and automobile transportation alternatives are also provided by us. We give our alternatives to remote locations too. We have unique transportation components like car providers, automobile providers, etc. we take 100 percent guarantee for secure and secure distribution, and never put even only one the begining on your hardly earned automobiles.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
We give our alternatives at very reasonably priced range. Charges depend upon your baggage and their fill. If you want us to provide you content to some remote position then obviously you have to pay additional expenses for that. We provide you some other alternatives too like packaging and unpacking of items. Our expenses depend on our alternatives what we provide to you.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
Packers movers Bangalore gives you opportunity to shift without handling any trouble. We are sure that you did not get such alternatives at so much affordable price. If you want to compare expenses with others, then we also provide you comparison chart too. Our support and expenses are absolutely wise.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by john-kurkowski** [comment]
Just encountered the ask for new permissions again, which made me think twice.

<img width="308" alt="screen shot 2016-04-15 at 1 15 32 pm" src="https://cloud.githubusercontent.com/assets/299487/14573836/5a6d5406-030c-11e6-81b4-bc7b06778322.png">

In the app store, where you say Google is being alarmist, could you explain each permission it's asking for? Understood if you think it's benign. But as a user, understanding each, _briefly_, would help.

**Comment by innaterebel** [comment]
Up to this point they are pretty obvious though assuming you utilize a wide array of commands of Vimium.

- `All your data on the websites`: The scariest-sounding one, already explained by the closing comment above, is  basically how Vimium and most Extensions that interact with web pages can work.
- `Your browsing history`: So Vimium can offer the history functions.
- `Your bookmarks`: So Vimium can offer the bookmark functions.
- `Your copy and paste`: So commands like `yf`, `p`, and visual mode can work.
- `Display notifications`: The update notification when Vimium is updated.

I am just an average user and know nothing about coding, but as I see and use it, apparently they are all what Vimium is expected being able to do so it naturally needs those permissions.
