### ISSUE TITLE
[Feature Request] Map keys to other key combinations (so I can trigger extensions with a single keystroke)

### ISSUE THREAD

**Issue by mortenfriis** [philc/vimium#3670]
Hi,
it would be great if you could map keys to other key combinations (ie "map c <c-c>"). This would allow us to set shortcuts to an extension (ie CTRL+c) which we could then trigger with a single keystroke (c).

**Comment by gdh1995** [comment]
No. Vimium's `map` and `mapkey` can not affect how browsers or other extensions work, so they will always get a `c`, but not `ctrl+c`, even when you use `mapkey c <c-c>`

**Comment by mortenfriis** [comment]
OK. Thanks for clarifying.
