### ISSUE TITLE
seek for enhancement: add more hint mode

### ISSUE THREAD

**Issue by zerobikappa** [philc/vimium#3673]
would you consider to add more function for hint mode like tridactyl? such as:
focus an element,
view image in new tab,
save-as the linked resource,
save-as the linked image,
copy (yank) link's target to clipboard,
...

**Comment by nsunderland1** [comment]
There are more link hint commands available as custom mappings, but they're hidden away in the [docs](https://github.com/philc/vimium/wiki/Tips-and-Tricks).

```
map X LinkHints.activateMode action=hover
map X LinkHints.activateMode action=focus
map X LinkHints.activateMode action=copy-text
```

Also, if you go to Vimium's options and click "Show available commands" (next to the Custom Key Mappings box) there are a few more undocumented commands you can make mappings for, e.g. LinkHints.activateModeToDownloadLink.

> copy (yank) link's target to clipboard,

I believe that one's already available by default, with the shortcut `yf`
