### ISSUE TITLE
Brave Browser | Shortcuts for mute and pin have no affect

### ISSUE THREAD

**Issue by limakzi** [philc/vimium#3677]
**Describe the bug**
Brave Browser seems to have problems with Pinning the tab and muting the tab.
No events are logged in extension log.

**To Reproduce**
Steps to reproduce the behaviour:
- Have a fresh Vimium installation.
- Open any website that is not ignored by Vimium.
- Try to pin or mute website with `<a-p>` or `<a-m>`.

Include a screenshot if applicable.

**Browser and Vimium version**
```
Brave | 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)
```

Vimium:
```
Version
1.66
```

I have noticed few other issues with common symptoms.
- https://github.com/philc/vimium/issues/3387
- https://github.com/philc/vimium/issues/3620

**Comment by gdh1995** [comment]
Were you testing on a macOS?

**Comment by limakzi** [comment]
@gdh1995 Yes, I do.
Problem does not affect on Chrome, for example.

**Comment by atanasj** [comment]
I have discovered this issue is also present on Firefox for Mac too:

```bash
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H15
Firefox 83.0 (64-bit)
Vimium 1.66
```

Please let me know if you need more info.

**Comment by limakzi** [comment]
@gdh1995 Do you need more information? How can we help you solve that?

**Comment by gdh1995** [comment]
Here's my guess:

The macOS system will map `Alt+***` to some infrequent characters, which makes Vimium get wrong key name.

Test for this system-level mapping:

* open https://gdh1995.cn/vimium-c/keyboard-test.html
* click Vimium's icon and "save options" to make Vimium disabled on the page
* reload the page, and enable "Prevent all keyboard events"
* then press ``Alt+P` to see what it will log.

BTW, will it work if you map a lower-case English letter to `togglePinTab` (e.g. `map p togglePinTab`) ?

**Comment by limakzi** [comment]
@gdh1995 Workaround with mapping `p` to `togglePinTab` works perfectly.
You were right. `Alt + P` is mapped to `Ļ`.

```
-- | -- | -- | -- | -- | --
72 | keydown | AltLeft | Alt | Alt | 18
73 | keydown | KeyP | Ļ | Alt | 80
74 | keypress | KeyP | Ļ | Alt | 315
75 | keyup | KeyP | Ļ | Alt | 80
76 | keydown | KeyP | Ļ | Alt | 80
77 | keypress | KeyP | Ļ | Alt | 315
78 | keyup | KeyP | Ļ | Alt | 80
79 | keydown | KeyP | Ļ | Alt | 80
80 | keypress | KeyP | Ļ | Alt | 315
81 | keyup | KeyP | Ļ | Alt | 80
82 | keydown | KeyP | Ļ | Alt | 80
83 | keypress | KeyP | Ļ | Alt | 315
84 | keyup | KeyP | Ļ | Alt | 80
85 | keyup | AltLeft | Alt | &nbsp; | 18
```

**Comment by gdh1995** [comment]
BTW, my customized version of Vimium, named [Vimium C](https://github.com/gdh1995/vimium-c), has enhanced the option "Ignore keyboard layout" by adding a middle state and only ignoring layout when AltKey is being pressed (then `<a-p>` should be matched).

In a fresh installation, Vimium C on macOS will enable this middle state by default, so you may take a try.

**Comment by jukrb0x** [comment]
same issue, not working on pin and mute.

Chrome 94.0.4606.71

**Comment by gdh1995** [comment]
You may write your key mappings using the mapped chars, like `Ļ`, (see https://github.com/philc/vimium/wiki/Key-Mappings ). And I guess one of `map Ļ scrollDown` and `map <a-Ļ> scrollDown` will work.

Or you may use the advanced option named `Ignore Keyboard Layout` on Vimium Options to make Vimium ignore macOS' key mapping.

**Comment by suicide** [comment]
I have the same issue in brave
```
Version 1.31.91 Chromium: 95.0.4638.69 (Official Build) (64-bit)
```
vimium 1.67

on linux.

However, I am sure it was working in the past. Remapping to something not including ALT works fine.

**Comment by philc** [comment]
Great discussion here. I'm closing this in favor of #3197, because I think it's probably the same issue.
