### ISSUE TITLE
Vimium-FF: Button for removing an excluded URL rule is unclickable

### ISSUE THREAD

**Issue by mohamedhaddi** [philc/vimium#3678]
**Describe the bug**
Currently I use regular Firefox, but this has also been the case for Firefox Developer Edition: When I go to Vimium-FF options and try to remove a rule from the first section "Excluded URLs and keys", clicking on the "X" button does nothing.

**To Reproduce**
1. Open Firefox.
1. Go to Vimium-FF options.
2. Go to first section "Excluded URLs and keys".
3. If there are no excluded URLs, click on "Add Rule" to add one.
4. Try to remove a rule, by clicking the "X" button on the far right of the rule.

**Browser, OS and Vimium version**
Firefox 81.0
Windows_NT 10.0 19041
Vimium-FF 1.66

**Comment by nsunderland1** [comment]
I believe https://github.com/philc/vimium/pull/3624 will fix this if merged. The issue is that Firefox thinks the styling for `input:read-only` applies to more things than it should, and as a result pointer events get disabled on the `x` buttons.

**Comment by mcp292** [comment]
Still having this issue on Firefox 87 for Arch Linux.

**Comment by mcp292** [comment]
As a temporary workaround, just leave the urls blank then save. They should automatically be deleted.
