### ISSUE TITLE
Youtube HTML5 time scrollbar registers wrong cursor position

### ISSUE THREAD

**Issue by ipopov** [philc/vimium#368]
I initially filed this as a bug against Chrome (http://code.google.com/p/chromium/issues/detail?id=87589), but I now realize that it only happens when Vimium is enabled. So I'm more or less copy-pasting the report here. :)

Chrome Version       : 14.0.797.0

**What steps will reproduce the problem?**
1. Go to http://www.youtube.com/html5 to enable the Youtube HTML5 video experiment.
2. Play some video that has HTML5 playback enabled; for example, http://www.youtube.com/watch?v=VML1u8KJjEo
3. Attempt to jump to the middle of the video using the time scrollbar at the bottom of the video.

**What is the expected result?**

A "tooltip" pops up above the cursor denoting which time in the video this scrollbar position denotes.

**What happens instead?**

The tooltip pops up far to the left of the cursor, and the time that it shows is for the position where it pops up, not for where the cursor is.

**Please provide any additional information below. Attach a screenshot if possible.**

There seems to be some scaling (around 4/5ths) of the position where the cursor registers over the scrollbar. Thus, for earlier times in the video, the offset is negligible, but when hovering the rightmost end of the scrollbar, the time shown is actually for 4/5ths into the video.

_UserAgentString: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_7) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.797.0 Safari/535.1_

**Comment by rrsahuone** [comment]
. We can shift your furnishings as well. Heavy furnishings moving is boring and irritating procedure and challenging to shift to distances. Here packers and movers are doing the best job.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by rrsahuone** [comment]
Every time when individuals are preparing to shift to distant place, they are extremely conscious as most fragile products belong to them. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers in Delhi">Packers and Movers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by rrsahuone** [comment]
We help you in moving large products as well like car, bikes, scooter and similar moving mediums. In case, you need to shift such large products, expenses will be added additional for each product as per your specifications.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers in Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a>

**Comment by rrsahuone** [comment]
Now you must have got an concept how our offers are customized and how they vary according to need. This is the purpose we evaluate your need first, only then we record authorized packers and movers companies to your close by place.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
