### ISSUE TITLE
[feature request] add support for search bookmarks by category

### ISSUE THREAD

**Issue by Freed-Wu** [philc/vimium#3687]
By now, vimium only allow user search bookmark by website and name. such as
![image](https://user-images.githubusercontent.com/32936898/95934340-357ce380-0e03-11eb-8705-9542650f5936.png)

Can it support search bookmarks by category? like this
this is a bookmark category named 'home'

![Screenshot from 2020-10-14 09-40-37](https://user-images.githubusercontent.com/32936898/95934063-87713980-0e02-11eb-9dd5-f91e5f97a07f.png)
press home we can find all bookmarks belonging to 'home'.
![image](https://user-images.githubusercontent.com/32936898/95934422-60673780-0e03-11eb-865e-3a73b5e5dc56.png)

**Comment by gdh1995** [comment]
Type `/home` to search in folder names.

**Comment by Freed-Wu** [comment]
Thanks!
