### ISSUE TITLE
z-index - Vimium hint markers not top-most

### ISSUE THREAD

**Issue by a-p-f** [philc/vimium#3690]
**Describe the bug**
Vimium's styles don't guarantee that its UI appears on top of all page elements.

**To Reproduce**
Go to http://vimiumzindextest.surge.sh/

Activate link hints (f), and notice that they do not appear on top of the "CMS Toolbar". 

Note - this sample page represents a real-world scenario, from a CMS tool I'm actually building. The CMS appends the toolbar to the document body, and sets the z-index to maximum supported value (in all current browsers). 

**Browser and Vimium version**
Vimium version 1.66

**How To Fix**
You should be setting the z-index to the maximum possible value on every element you append directly to the document. Note: this will create a new [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context), so you can still use z-index to order elements (ie. individual hint markers) _within_ this container (and you don't need to use extremely high z-index values anymore - you can use any values you like).

I've created a [demo page](http://vimiumzindextest.surge.sh/fixed.html) which adds a style element to do exactly that (it fixes the hint marker container, but not the vomnibar or help overlay). 

**Further Discussion**
I see that the vomnibar and help overlay get appended to the html element (document.documentElement), rather than to the body element. If you're comfortable doing that, you might as well do that with the hint marker container, too. That approach (combined with setting z-index to 2147483647 on your container element) makes it impossible for any other page element to appear on top of your UI.

**Comment by a-p-f** [comment]
Sorry, ignore the the "Further Discussion" part. I thought that the `#vimiumHintMarkerContainer` was being appended to the body element, but I see now that it is actually being appended to the html element, just like your other overlays.

**Comment by philc** [comment]
Thank you @a-p-f for the clear report and the demo page. Related: #4315, #4068.

This particular case is fixed by showing links hints in a popover element, for browsers that support popover (Chrome, soon Firefox): 412cc37621a578ee260925f31e0722539af33f39
