### ISSUE TITLE
Move default search engine option

### ISSUE THREAD

**Issue by thomas-zahner** [philc/vimium#3692]
Currently the option to change the default search engine is located in the advanced options.
Most users would probably expect this options to be directly visible when opening the options menu since it is quite an important setting. For me personally it took a few minutes to figure out where to change the search engine used by vimium.

**Comment by philc** [comment]
Thanks Thomas. As part of v2.0, all options are visible by default on the options page. I've also moved the default search engine higher on the page in f8d56273ed602a40c6f9b5722111c74a32c37c3d.
