### ISSUE TITLE
Different behaviour when pressing Esc on FF and Chromium

### ISSUE THREAD

**Issue by magthe** [philc/vimium#3704]
**Describe the bug**

I use Vimium on both Firefox and Chromium, but I observe different behaviour when pressing the escape key.

I'm using an Anne Pro 2 keyboard, where I've remapped CapsLock to be Escape in the keyboard (using ObinsKit, the tool for configuring the keyboard).

This works perfectly everywhere except in Chromium where pressing the CapsLock key (i.e. Escape) doesn't do anything at all, while pressing the Escape key (i.e. CapsLock) both enters command mode _and_ locks to upper case.

It seems to me like Vimium uses the _Key_ rather than the _Code_ to determine what's been pressed. Can that be changed without other, unintended consequences?

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to https://gdh1995.cn/vimium-c/keyboard-test.html
2. Press CapsLock, followed by Escape

_In Firefox I see_

|     | Event   | Code     | Key      | Modifiers | KeyCode (legacy) |
| --- | ---     | ---      | ---      | ---       |              --- |
|   1 | keydown | Escape   | Escape   |           |               27 |
|   2 | keyup   | Escape   | Escape   |           |               27 |
|   3 | keydown | CapsLock | CapsLock |           |               20 |
|   4 | keyup   | CapsLock | CapsLock |           |               20 |

_In Chromium I see_

|     | Event   | Code     | Key      | Modifiers | KeyCode (legacy) |
| --- | ---     | ---      | ---      | ---       |              --- |
|   1 | keydown | Escape   | CapsLock |           |               20 |
|   2 | keyup   | Escape   | CapsLock |           |               20 |
|   3 | keydown | CapsLock | Escape   |           |               27 |
|   4 | keyup   | CapsLock | Escape   |           |               27 |

**Browser and Vimium version**

_Firefox_

Version | 82.0.2
Build ID | 20201028150324
User Agent | Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
OS | Linux 5.8.14-arch1-1 #1 SMP PREEMPT Wed, 07 Oct 2020 23:59:46 +0000
Vimium | 1.66

_Chromium_

Chromium | 86.0.4240.111 (Official Build) Arch Linux (64-bit)
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Linux
Vimium | 1.66

**Comment by gdh1995** [comment]
This means the keyboard remapping tool is not so considerate.

You may enable the advanced option named "ignore keyboard layout" on Vimium Options page to let it prefers `keyboardEvent.code`

**Comment by magthe** [comment]
Though FF (and everything else) sees different keys than Chromium, so I'm not sure if all the blame falls on the remapping tool.

Anyway, I had noticed that option but didn't understand what the description fully, plus that it needed a restart of the browser to take effect... now all is working as I want it. Thanks!

**Comment by magthe** [comment]
I just thought I'd report that after the latest upgrade of Chromium it's (again) the case that I must have "ignore keyboard layout" disabled in order for the (remapped) escape key to work as I want. I suppose what I saw was a regression in Chromium that now have been fixed :smiley:
