### ISSUE TITLE
Feature Request if not possible

### ISSUE THREAD

**Issue by yogi81** [philc/vimium#3705]
Usecase: Some websites offer keyboard based commands. I would like to have a possibility to directly forward my next key to the site. 

Question:
How can I tell vimium to skip my next key stroke and send it directly to the site? With trydactyl it is for example ctrl+v command.

**Comment by gdh1995** [comment]
`passNextKey`: https://github.com/philc/vimium/wiki/Tips-and-Tricks#using-the-escape-key-in-inputs

**Comment by yogi81** [comment]
thank you very much! this solves it!
