### ISSUE TITLE
Youtble muisc mark overlap

### ISSUE THREAD

**Issue by SLin0218** [philc/vimium#3707]
**Describe the bug**
`Youtble muisc mark overlap`
![image](https://user-images.githubusercontent.com/23139501/98625173-1877f980-234a-11eb-8110-517b901402bf.png)

**To Reproduce**
1. Go to URL 'https://music.youtube.com/playlist'
2. press on 'f'

**Browser and Vimium version**

`Chrome version 86.0.4240.183`
`Vimium 1.66`
`System OS macOS 10.15.7`

**Comment by gdh1995** [comment]
You may try my customized version of Vimium: Vimium C ([github](https://github.com/gdh1995/vimium-c), [gitee](https://gitee.com/gdh1995/vimium-c), [chrome web store](https://chrome.google.com/webstore/detail/vimium-c/hfjbmagddngcpeloejdejnfgbamkjaeg)), and it agressively filters out some element.

The only issue I've found on this page is that Vimium C fails to click the "auto play more songs" button, and I'll try to fix it in a next release.

**Comment by SLin0218** [comment]
@gdh1995  thanks
