### ISSUE TITLE
How to map cmd+shift+c?

### ISSUE THREAD

**Issue by srikat** [philc/vimium#3711]
I would like to press `i` to begin inspecting webpage elements using the Dev Tools.

I tried

```
unmap i
map i <m-s-c>
```

but it doesn't seem to be working.

Any help is appreciated.

Thanks in advance.

**Comment by gdh1995** [comment]
No. Vimium has no way to open the Dev Tools, and it's a limit existing in all browsers.

**Comment by srikat** [comment]
Pity.

I mapped it to `⌘i` instead using Keyboard Maestro.
