### ISSUE TITLE
Feature Request: Toggle view/hide tab numbers.

### ISSUE THREAD

**Issue by mohamedhaddi** [philc/vimium#3713]
Hi!

**Feature motive:**

I often use the \<number\>K or \<number\>J keys to jump to tabs, but it's usually only efficient with closer tabs, once the tab I want to jump to is ~5 or more tabs away it becomes much slower to count how many tabs I want to jump, so it would be much easier and faster to do it if one can show the tab number they want to jump to.

**Feature description:**

Suggestion 1:

Just like how we can enable the absolute or relative line numbers in Vim, it would be cool to have a key that enables/toggles numbers on tabs (one could configure in the settings if they would like to show absolute or relative tab numbers), for example:

![scrn-1](https://user-images.githubusercontent.com/6943864/100396747-8e68aa00-3046-11eb-8c6b-688a5105f375.gif)

A lot more useful in larger screens:

![scrn-2](https://user-images.githubusercontent.com/6943864/100396749-90cb0400-3046-11eb-9115-336bd8682a57.gif)

Suggestion 2:

Maybe they could just be shown with the F key along with the URLs. Like so:

![scrn-3](https://user-images.githubusercontent.com/6943864/100396910-77768780-3047-11eb-8678-150b9d4009ae.gif)

**Comment by philc** [comment]
@mohamedhaddi this is a cool idea, and thank you for the clear write up and gif. The main blocker here is that Chrome extensions like Vimium we can't modify the visual appearance of the tab UI bar in Chrome, which makes a feature like this impossible, unfortunately.
