### ISSUE TITLE
Vimium shortcuts are not available in view-source mode

### ISSUE THREAD

**Issue by vincevargadev** [philc/vimium#3722]
**Describe the bug**

I use Vimium to open the current page's source by the `gs` keyboard shortcut.

I see the source, but I can't use the Vimium shortcuts anymore. Having the shortcuts also in view-source mode would be great as I could navigate through the source code very quickly.

**To Reproduce**

1. Make sure Vimium is installed and enabled
2. Hit `gs` to view page source
3. Try to use `j` to scroll down (or any other shortcuts).
4. It won't work.

**Browser and Vimium version**

```
Google Chrome | 86.0.4240.111 (Official Build) (x86_64)
-- | --
OS | macOS Version 10.15.7 (Build 19H2)
JavaScript | V8 8.6.395.17
Vimium 1.66
```

**Comment by mwanchap** [comment]
Chrome extensions don't seem have access to this page for some reason. I have a few different dark mode extensions (overrides colours on websites to make them darker) and none of them can change the colours on the view source page either.

**Comment by vincevargadev** [comment]
Oh, that's a pity. Then I guess the issue can be closed as there's not much that vimium can do.
