### ISSUE TITLE
Feature request: shortcut to enable/disable Vimium on the site

### ISSUE THREAD

**Issue by vargavince91** [philc/vimium#3723]
### My issue

I really like the Vimium extension, however, the keyboard shortcuts conflict with some websites.

Example: YouTube
* f: fullscreen
* j k l: rewind, pause, forward

I know that I could redefine the keys to make sure that the extension doesn't have a conflict with the website, doing so is very cumbersome and if someone wants to support multiple sites, taking care of all the key bindings gets difficult.

I could also disable Vimium in the extension options, for example, I could exclude URLs, like: `https?://www.youtube.com/watch*`, however, these solutions do not let me enjoy Vimium and the YouTube keyboard shortcuts at the same time (meaning: without going to the extension settings).

### Solution:

It would be great to have a Vimium shortcut to enable/disable Vimium easily within a tab.

That would let me use the website's shortcuts for some time, then turn on Vimium and use Vimium shortcuts for a while.

In the case of the YouTube example:
* while Vimium is disabled: make video full screen with f, go back and forth using the j and l keys
* while Vimium is enabled: open link with f, scroll up and down with j and k

I hope this example can help you see why I would like to have the ability to switch between the different modes, without having to relearn, and redefine the key mapping.

**Comment by gdh1995** [comment]
Vimium has `enterInsertMode` and `passNextKey`, and `passNextKey` supports an option of `normal` to disable "pass keys" temporarily.

For example, with `map Pn passNextKey normal`, `10000Pn` will enter Normal mode during the next 10000 key strokes, and you can exit this Normal mode in any time by pressing `<esc>`.

**Comment by gdh1995** [comment]
BTW, if you still want a single key to enable/disable Vimium completely, or want to disable Vimium in all frames of a tab, you may try my customized version of Vimium - Vimium C (https://github.com/gdh1995/vimium-c) - and it supports quite a few controlling commands like this request (https://github.com/gdh1995/vimium-c/wiki/Enable-or-Disable-all-frames-by-a-shortcut).

**Comment by vargavince91** [comment]
Thank you, that worked perfectly!
