### ISSUE TITLE
Button in vimium options doesn't work on Firefox

### ISSUE THREAD

**Issue by matildeopbravo** [philc/vimium#3725]
Whenever I want to use vimium advanced options to restore my backup file, the button simply doesn't work, it doesn't even act like a button. I notice that the button **"Add Rule"** changes color on hover, the button "Browse" does not and it does absolutely nothing when clicked. I noticed that this issue only happens with **Firefox** and **Firefox-developer-edition** because it worked on **chromium**.

**Steps to reproduce the behavior:**
1. Go to vimium options 
2. Click on "Show advanced options"
3. "Click Browse"

**Browser and Vimium version**
Firefox-developer-edition
Arch Linux
Mozilla Firefox 84.0b8
Vimium 1.66 version

I am attaching a picture with the button I'm referring to.

![image](https://user-images.githubusercontent.com/56790511/102024009-2b398000-3d87-11eb-8e4d-eb511805c62c.png)

**Comment by tammersaleh** [comment]
I see the same issue.  Vimium-FF 1.66, Firefox 89.0.1

**Comment by fadh1l** [comment]
same issue on firefox 108.0 with vimium Version 1.64.6.
The browse button for importing config file isn't clickable.

**Comment by gerryhernandez** [comment]
This seems to have regressed. As a workaround, I was able to hack in the equivalent CSS (the fix from #3624 - removing `:read-only`) using the FF dev tools.
