### ISSUE TITLE
Vimium not working on tabs which failed to load

### ISSUE THREAD

**Issue by mark2185** [philc/vimium#3734]
**Describe the bug**
I cannot use `vimium` on tabs which result in `This site can't be reached`.

I get it if the browser's homepage is disabled for security reasons, but why is `vimium` disabled in this case?

**To Reproduce**
1. Go to URL 'http://thisisnotareallink.com/'
2. Try to use `J` or `K` to go to a different tab

**Browser and Vimium version**
Browser: `brave, 1.18.70 Chromium: 87.0.4280.101 (Official Build) (x86_64)`
Vimium: `1.66`

Note:
This is slightly annoying when I have a few sites opened which are accessible only from a workplace network, and when I switch to my home network, those sites won't load, but I still want to be able to switch through them with `J` and `K`.

**Comment by gdh1995** [comment]
The page is also priviledged.

You may try my [Vimium C](https://github.com/gdh1995/vimium-c), and it provides some browser-level shortcuts on `chrome://extensions/shortcuts`, to trigger commands everywhere.

**Comment by mark2185** [comment]
I see no benefit of `J` or `K` over `ctrl + (shift + ) tab` if I cannot use them everywhere, same goes for `Vimium C`.

**Comment by gdh1995** [comment]
vimium c's global shortcuts (not normal key mappings) can be used to swirch tabs. For example, I'm using alt-c and alt-v



---Original---
