### ISSUE TITLE
Feature Request: R (big r) to empty cache and reload

### ISSUE THREAD

**Issue by mikevare** [philc/vimium#3735]
In Chrome, there is only the option to do a hard reload using a shortcut CMD+SHIFT+R
If its possible, it would be awesome to simply press R to empty your cache and fully reload.
Normally, you need to open dev tools (r-click -> inspect) and r-click on the reload button, which is terrible.

I just found you extension, it's great, thank you. :-)

**Comment by philc** [comment]
Great idea. This would be a great feature. It looks like this is possible with the tabs API ( https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/reload ) :

`browser.tabs.reload(2, {bypassCache: true});`

Anyone who wants to take a stab at it, I'd be happy to merge a PR.

**Comment by gdh1995** [comment]
&nbsp;There has been such an option, named "hard".
https://github.com/philc/vimium/blob/bdf654aebe6f570f427c5f7bc9592cad86e642b5/background_scripts/main.js#L336



---Original---

**Comment by mikevare** [comment]
Thanks gdh1995, so it will work after adding this line to your options
```map R reload hard```

Maybe someone can add this to the default key map, it makes total sense for webdevs :)

**Comment by philc** [comment]
This was added as an advanced command under the keybinding "R" in #4445, which should make it more discoverable.
