### ISSUE TITLE
Opening link in new tab WHILE visiting it (not working)

### ISSUE THREAD

**Issue by faxotherapy** [philc/vimium#3740]
**Describe the bug**
While opening a link in a new tab, Vimium is not able to access the tab immediately afterwards. I have to switch manually to the new tab by pressing `K` key. It happens for any site.

**To Reproduce**
1. Press ⇧ and `F` to select link.
2. Press ⇧ and the letters associated to the link.

Result: a new tab is created, but Vimium does not automatically access it afterwards. The only option available is opening a link in a new tab while remaining on the current page.

**Browser and Vimium version**

Firefox 84.0.1 + MacOS Mojave + Vimium 1.66

**Comment by gdh1995** [comment]
Replace the Shift key in step 2 with Ctrl, and then Vimium will show "Open link in new tab and switch to it".

Or use the command of `LinkHints.activateModeToOpenInNewForegroundTab` directly.
