### ISSUE TITLE
Hovering over a link does not work as described in the wiki

### ISSUE THREAD

**Issue by martindzejky** [philc/vimium#3741]
**Describe the bug**

As per the wiki page [Tips and Tricks](https://github.com/philc/vimium/wiki/Tips-and-Tricks#hovering-over-links-using-linkhints), I included this in my Custom key mappings:

```
map hf LinkHints.activateMode action=hover
```

However, pressing `hf` and then selecting a link always **clicks** on it, never just hovers. Note that I have enabled the filtered link-hint mode and also require ENTER to activate a link.

![image](https://user-images.githubusercontent.com/4700122/103648366-0d61d400-4f5d-11eb-97cb-9ee9dfcd5536.png)

**To Reproduce**
1. Include `map hf LinkHints.activateMode action=mouseover` in your custom keymaps
2. Go to `https://www.google.com`
3. Press `hf lucky<enter>`

I would expect this to only hover over the button and not press it. However, Vimium clicks on the button and that takes me to `https://www.google.com/doodles`.

**Browser and Vimium version**

Chrome: `Version 87.0.4280.88 (Official Build) (x86_64)`
OS: `macOS Catalina 10.15.7`
Vimium: `1.66`

**Comment by martindzejky** [comment]
Now I suspect that this has something to do with the keys in the mapping because when I map it to, for example, `X`, it works as I'd expect. Why is `hf` not working?

**Comment by gdh1995** [comment]
`mouseover` is not a valid action, but `hover` is.

**Comment by gdh1995** [comment]
![image](https://user-images.githubusercontent.com/5547703/103649909-32c10300-4f9a-11eb-9771-a78f1e46bab6.png)

BTW, valid actions are: `copy-text`, `focus` and `hover`.

**Comment by martindzejky** [comment]
`hover` works now, it actually was not a problem with hovering but with the keymap. I've rebound the action to `<C-f>` and now it works as expected. Thanks!

**Comment by 22csnyder** [comment]
Though this is closed, what you describe is consistent with a problem I just figured out and there is no explaination posted here.

The keymap 'hf' is problematic because the prefix 'h' is already bound. The interpretation is "do 'h' then do 'f'". That is why you observe action=click.

Aside from choosing another keymap, I predict your problem should also go away by writing "unmap h" in the preceeding line.

**Comment by matthewgson** [comment]
Hover works great! I hoped this feature to work similarly to "f" and it perfectly does! Thanks.
