### ISSUE TITLE
⌘Cmd key exits insert mode

### ISSUE THREAD

**Issue by babramczyk** [philc/vimium#3743]
**Describe the bug**
When in insert mode, on ⌘ keydown insert mode is exited.

**Why this matters**
Some apps (e.g. Trello copying and pasting cards) require you to use a ⌘-based keycombo to do actions. See Trello's example here:

![image](https://user-images.githubusercontent.com/16885191/103660260-00c88600-4f33-11eb-9cb8-15aafa49a851.png)

**To Reproduce**
1. Enter insert mode on a page with `i`
2. Hold down ⌘

Include a screenshot if applicable.

**Browser and Vimium version**

Chrome: 87.0.4280.88 (Official Build) (x86_64)

Vimium: 1.66

**Comment by leodahal4** [comment]
Mine works fine. May be this problem is for only MAC?
I am on,
Firefox 84.0.1
Vimium 1.66

**Comment by babramczyk** [comment]
Huh... yeah now that you say that, I tested it on a few sites, and it
actually seems like Trello is the only site this bug happens for me
on... 🤔

On January 7, 2021, Caleb Foust <notifications@github.com> wrote:
> Mine works fine. May be this problem is for only MAC?
>  I am on,
>  Firefox 84.0.1
>  Vimium 1.66
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/philc/vimium/issues/3743#issuecomment-756654292>, or

unsubscribe <https://github.com/notifications/unsubscribe-
auth/AEA2LR5JSK4NVEENEUIL5SLSY3G5FANCNFSM4VVJY6BA>.

**Comment by leodahal4** [comment]
Sorry to say that, But mine works fine with Trello too.

Is there anyone out having this same issue?
