### ISSUE TITLE
Capturing stretched-link does not work if anchor tag does not have any text

### ISSUE THREAD

**Issue by amenat** [philc/vimium#3744]
**Describe the bug**
`stretched-link` do not work if anchor tag doesn't have any text inside it: https://getbootstrap.com/docs/4.4/utilities/stretched-link/ 

**To Reproduce**
1. Go to: https://codepen.io/dasdaksjdal/full/ZEpRGOd
2. Press `f` to find links: 

**Browser and Vimium version**
Vimium 1.66 on chrome 87.0.4280.88 
Vimium 1.66 on firefox 84.0

I think it can likely be considered bad practice to use stretched link in anchor tag without any text, if you feel that way, please close the issue.

**Comment by gdh1995** [comment]
Reproduced. Well, because there're no APIs in current browsers to get accurate bounding boxes of such pesudo elements, I think it's impossible to make Vimium recognize such a usage perfectly.

**Comment by amenat** [comment]
I did some digging myself too and agree that it's too much to expect Vimium to recognize such pseudo-elements. 

Closing.
