### ISSUE TITLE
Toggle between tabs

### ISSUE THREAD

**Issue by gabrielbeauchemin** [philc/vimium#3751]
I would like to be able to toggle between two tabs. It is useful, as we are frequently working in between two tabs and would want to switch easily between one and another.

Thank you. Your extension is amazing, very useful and intuitive!!

**Comment by gdh1995** [comment]
There's a command named `visitPreviousTab` and you may take a try.

**Comment by gabrielbeauchemin** [comment]
Ok I close this issue because visitPreviousTab command (by typing ^) does exactly what I wanted.
