### ISSUE TITLE
After typing "o", how to navigate options?

### ISSUE THREAD

**Issue by jordan-brookman** [philc/vimium#3753]
The Vimium video tutorial says "Typing 'o' in Vimium let's you quickly open bookmarks, history, and Google searches.  You can navigate through this list using shortcuts."

What are the "shortcuts"?  Are the arrow keys the only way to scroll up and down through the selections?  If so, is it possible to be able to use keys that are not more reachable from the home row position?

**Comment by gdh1995** [comment]
Ctrl+J/K to scroll down/up.

**Comment by jordan-brookman** [comment]
> Ctrl+J/K to scroll down/up.

This is what I was looking for.  Thank you.
