### ISSUE TITLE
DuckDuckGo Instead of Google Search

### ISSUE THREAD

**Issue by faxotherapy** [philc/vimium#3756]
Hi,
is it possible to have DuckDuckGo launched right after I input some keywords (⇧ + O)? Currently, it's Google Search. I looked at the doc, but could found nothing with regard to search engine preference to use.

Thanks for your help.

**Comment by gdh1995** [comment]
Go to Vimium Options page, click the "Show Advanced Options" button at the bottom bar, and then edit "Default search
engine" to replace its value with `https://duckduckgo.com/?q=%s`. Then click "Save Changes" and try it.

**Comment by jzelinskie** [comment]
I hate to bump this, but there's really no way to use the browser's default search engine?

**Comment by faxotherapy** [comment]
The Chrome vesion is different from the Firefox version. There's no "Default search engine" in Chrome, only “Custom search
engines”. Under Chrome version I have uncommented the line `d: https://duckduckgo.com/?q=%s DuckDuckGo`

Now, how to I call this option? Thanks for your help.

**Comment by gdh1995** [comment]
@jzelinskie No API to read those engines.

@faxotherapy Then you need to click `Save changes`, and then:
1. press `o` to make Vomnibar show
2. type `d foo` (type `d`, press space, and then type `foo`) to search `foo` using DuckDuckGo
