### ISSUE TITLE
Bug: Opening links in new tab fails in LibreWolf 84.0.2

### ISSUE THREAD

**Issue by demoknight-tf2-lol** [philc/vimium#3758]
Steps to reproduce:
Press the key bound to `LinkHints.activateModeToOpenInNewTab`, and select a link to open in the new tab

Expected result:
Link opens in new tab

What happens:
The labels for links disappear, and nothing else happens

config file backup:
```json
{
  "settingsVersion": "1.66",
  "exclusionRules": [
    {
      "pattern": "https?://mail.google.com/*",
      "passKeys": ""
    }
  ],
  "filterLinkHints": false,
  "waitForEnterForFilteredHints": true,
  "hideHud": false,
  "keyMappings": "# Insert your preferred key mappings here.\nunmap X\nunmap x\n\nmap q removeTab\nmap Q restoreTab\nmap <c-d> scrollFullPageDown\nmap <c-u> scrollFullPageUp\nmap gi enterInsertMode\nmap i focusInput\nmap F LinkHints.activateModeToOpenInNewTab\nmap <a-f> LinkHints.activateModeToOpenInNewForegroundTab\nmap J goBack\nmap K goForward\nmap H previousTab\nmap L nextTab",
  "linkHintCharacters": "sadfjklewcmpgh",
  "linkHintNumbers": "0123456789",
  "newTabUrl": "about:newtab",
  "nextPatterns": "next,more,newer,>,›,→,»,≫,>>",
  "previousPatterns": "prev,previous,back,older,<,‹,←,«,≪,<<",
  "regexFindMode": false,
  "ignoreKeyboardLayout": false,
  "scrollStepSize": 60,
  "smoothScroll": true,
  "grabBackFocus": true,
  "searchEngines": "w: https://www.wikipedia.org/w/index.php?title=Special:Search&search=%s Wikipedia",
  "searchUrl": "https://duckduckgo.com/?q=",
  "userDefinedLinkHintCss": "div > .vimiumHintMarker {\n/* linkhint boxes */\nbackground: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#FFF785),\n  color-stop(100%,#FFC542));\nborder: 1px solid #E3BE23;\n}\n\ndiv > .vimiumHintMarker span {\n/* linkhint text */\ncolor: black;\nfont-weight: bold;\nfont-size: 12px;\n}\n\ndiv > .vimiumHintMarker > .matchingCharacter {\n}"
}
```

**Comment by demoknight-tf2-lol** [comment]
Every other method I have tested for opening a new tab does work properly. It is just this particular method that fails.

**Comment by demoknight-tf2-lol** [comment]
I have found out that this happens whenever you have popups disabled (`dom.disable_open_during_load`). This is kinda weird behaviour because a lot of other commands in vimium that open popups seem to work perfectly OK.

**Comment by gdh1995** [comment]
Those which work are opening new tabs directly through the browser APIs like `browser.tabs.create`, but LinkHints only means a suggestion to web pages themselves that "I'm clicking this using ShiftKey and CtrlKey, and you can do whatever you want". As a result, Firefox's popup blocker (in strict mode) will always block LinkHints' suggestions.

**Comment by LTGiardino** [comment]
> I have found out that this happens whenever you have popups disabled (`dom.disable_open_during_load`). This is kinda weird behaviour because a lot of other commands in vimium that open popups seem to work perfectly OK.

Hey I'm having the same issue. I checked `about:config` on LibreWolf 85.0.2 and `dom.disable_open_during_load` is set to true.
Is there any other setting I should check for this to work?

**Comment by LTGiardino** [comment]
> I have found out that this happens whenever you have popups disabled (`dom.disable_open_during_load`). This is kinda weird behaviour because a lot of other commands in vimium that open popups seem to work perfectly OK.

Hi. I'm having the same issue. I tried enabling/disabling `dom.disable_open_during_load` on `about:config`.
Neither option worked on LibreWolf 85.0.2 .
Is there any other option I should check to get this working?

**Comment by garcke** [comment]
I've submitted PR, which could let vimium to detect all Firefox based browser and fixing the issue.

**Comment by MichalRybecky** [comment]
Hello, facing same issue, version 86.0.1, none of the above solution working.

**Comment by Solovey61** [comment]
LibreWolf 87.0
Vimium 1.66
Have the same issue

**Comment by tubize** [comment]
same here,
librewolf 89.0.2
vimium 1.66

**Comment by StitiFatah** [comment]
Still experiencing the issue. 
vimium : 2.1.2
librewolf : 136.0-2
