### ISSUE TITLE
Bug: Smooth scrolling fails when privacy.resistFingerprinting is set to true (Firefox)

### ISSUE THREAD

**Issue by demoknight-tf2-lol** [philc/vimium#3759]
I have tested this on Firefox 85.0 and LibreWolf 84.0.1 on Arch Linux

Steps to reproduce: set `privacy.resistFingerprinting` to `true` in `about:config`.
Smooth scrolling fails to function correctly.

**Comment by gdh1995** [comment]
A duplicate of #3641, and #3701 may fix this (though I think the PR still has some new issues).

**Comment by kaimyel** [comment]
This issue is still persists.

**Comment by philc** [comment]
Closing in favor of #3641.
