### ISSUE TITLE
Bug: cannot change focus on page with multiple scroll bars

### ISSUE THREAD

**Issue by watsheldon** [philc/vimium#3760]
For example, on outlook web version (The following is a picture of the outlook app, but the idea is the same):

![image](https://user-images.githubusercontent.com/29114212/106335646-34939300-62c8-11eb-9735-9d33251596cb.png)

I can't change which side of the page to scroll. Have tried `gf` and `gF`, both only focus on the top frame instead of switching between the separate sections.

**Comment by tripfish** [comment]
Try using `LinkHints.activateMode action=focus` first, to focus a link on the area you want to scroll.

Here are possible maps:
`map X LinkHints.activateMode action=hover`
`map X LinkHints.activateMode action=focus`
`map X LinkHints.activateMode action=copy-text`

**Comment by watsheldon** [comment]
@tripfish Thanks, been using this method as a workaround. I was hoping for an option to cycle through all the sections, even those without a link, just like how `Tab` cycles through all the text boxes. I will close this issue since it seems that vimium currently does not support this feature.
