### ISSUE TITLE
Find Command not working on firefox

### ISSUE THREAD

**Issue by ahmedelhori** [philc/vimium#3774]
**Describe the bug**
When typing "/" and a letter, the input >>sometimes<< stops accepting any more letters.
Someone also reported this on the Mozilla addons website.

**To Reproduce**
1. Use Firefox
1. Go to any URL
2. Try finding any word

**Browser and Vimium version**
Firefox version 86.0 (64-bit) archlinux
Vimium Last Updated February 26, 2021

**Comment by therealhouri** [comment]
After Downgrading to Firefox 84 the Issues seems to be gone.

**Comment by avemilia** [comment]
Always reproducible on manjaro linux, ff 86, vimium 1.66.

Only one letter after slash is accepted, everything else is swallowed. Interestingly, if you start searching with slash (that is, it will show you //), then the search works fine and you can type as much as you want.

**Comment by rasfincher-caravan** [comment]
Also confirmed on Firefox Developer Edition 87.0b3 running on Windows 10.

**Comment by 1103st-labs** [comment]
Also confirmed on Linux Mint 20 Ulyana with Firefox 86.0 and vimium 1.66.

**Comment by MDingas** [comment]
Confirmed on most recent version of arch linux with Firefox 86.0

**Comment by andruyd** [comment]
Confirmed this issue on Fedora 33 with Firefox 86 (latest distro release). Another interesting thing I observed was that the extension is labelled experimental on addons.mozilla.org. I also noticed that the configuration restore function is not working.

**Comment by desmap** [comment]
Confirmed on Windows + Firefox 86

**Comment by BenSYZ** [comment]
For me, this problem only exists if there are URLs on the search results.

**Comment by fabriziobertoglio1987** [comment]
as probably this find functionality takes the html and search in it, the issues seems to be related to the html hierarchy and exactly where the cursor is positioned.

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

In this test I move the Caret Cursor to the correct position on the page and then I can search for that work, makes no sense doing this but it is useful to understand the problem.

| **ABLE to find  the Environment Word** | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/109666176-3d99ad80-7b6f-11eb-95bc-87fe4f7855df.mp4" width="700" height="" /> |

In this test case the caret cursor (the one you move with tab key) is positioned on some other html element and the find / key does not search on that paragrach which includes Environment but on other parts of html

| **UNABLE to find the Environment Word** | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/109666209-44c0bb80-7b6f-11eb-8474-264b2d64f976.mp4" width="700" height="" /> |

</p>
</details>

In my case I also changed the shape of the caret cursor so I could better troubleshoot this issue 

https://support.mozilla.org/en-US/questions/1280609

so I changed the cursor and enabled caret browsing with F7. Now I can clearly see the cursor moving to the correct position in the screen. 

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

| **after** | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/109668027-088e5a80-7b71-11eb-8e5f-707b2e208765.mp4" width="700" height="" /> |

</p>
</details>

**Comment by rddunphy** [comment]
> For me, this problem only exists if there are URLs on the search results.

Didn't realise until I read it, but this is exactly right - as I type, it highlights the first result on the page. If the highlighted text is part of a URL, it then blocks and won't let me type any further characters. If I hit escape and try entering the same text again, it blocks immediately after the first character, as it's now starting the search from the URL it found previously.

I'm using FF 86.0 on Kubuntu 20.10.

**Comment by euglevi** [comment]
I have the same exact issues with Firefox 86 on Ubuntu 20.04.

**Comment by r2vq** [comment]
Also confirmed on Firefox 86 on macOS Catalina

**Comment by nsunderland1** [comment]
> Someone also reported this on the Mozilla addons website.

@therealhouri Do you have a link to this issue?

**Comment by StarTroop** [comment]
The Vimium-C extension doesn't have this issue, and is updated regularly. Does anyone know what the difference is which causes this issue?

**Comment by therealhouri** [comment]
> The Vimium-C extension doesn't have this issue, and is updated regularly.

It says on the Vimium-C extension github page, that they have rewritten The code from Coffescript to Javascript and then to Typescript.

**Comment by MDingas** [comment]
The repository has not been updated in a long time, is it possible this may not get fixed in the foreseeable future?

**Comment by fabriziobertoglio1987** [comment]
@philc could you have a look at this issue please?
I'll have to downgrade 2 machines to firefox 84 and disable automatic updates...

**Comment by fabriziobertoglio1987** [comment]
> The Vimium-C extension doesn't have this issue, and is updated regularly. Does anyone know what the difference is which causes this issue?

https://addons.mozilla.org/en-US/firefox/addon/vimium-c/
https://github.com/gdh1995/vimium-c

>A Customized Vimium (to click web page content and manipulate browser windows using only keyboard) having Chinese support, global Commands and injection functionality, in C-style code for quicker action and less resource cost.

**Comment by schlueter** [comment]
On MacOS Big Sur, this issue presents on Firefox 86. It does not present on the Firefox 78.8.0esr release, which may be a better alternative, security wise, to downgrading to Firefox 84.

**Comment by BenSYZ** [comment]
I also confirm that the Vimium-c extension does not have this issue with Firefox 86.0.1 on Arch Linux(5.11.6-arch1-1).

**Comment by billwanjohi** [comment]
Downgrading to firefox 85.0.1 (manjaro) worked for me

- downgraded with the [downgrade](https://github.com/pbrisbin/downgrade) archlinux utility
- launched firefox with `firefox --allow-downgrade` to avoid having to resync my profile

But eventually we're gonna get a security bug that makes this untenable...

**Comment by alk3mist** [comment]
@philc, could you take a look at this issue? 20 comments were added in 20 days. and many people will appreciate the fix for this bug.

**Comment by StarTroop** [comment]
To those looking for a replacement, and don't want to use Vimium-C due to the author's official stance on Taiwan's independence, I recommend Tridactyl. It's very flexible, has a theme similar to the omnibox, and if the defaults don't suit you it's very easy to customise it to match Vimium or your own taste. The only caveat is that the find function is currently unfinished (no incsearch) thus unused by default (it defaults to using Firefox's quick find, but I find the current state of Tridactyl's find tool satisfactory so I use it anyway.)

**Comment by corngood** [comment]
I did a little investigation.  This change:

https://github.com/corngood/vimium/commit/5ae97a932c435e29e60f825c7bf1c4bf365604e7

stops the input area from losing focus.  There's another problem I'm now looking at, but I'm not sure if it's related:

- open find `/`
- enter a search that has some match
- press enter

vimium will end up in `PostFindMode`, which blocks all keyboard input until focus changes.  I'm still not sure what the intended behaviour is here.

**Comment by fabriziobertoglio1987** [comment]
the intended behaviour is in `PostFindMode` you navigate forward and back in your search with `n`, then you can start a selection with `vc`... but the question is why we get in `PostFindMode` **without** pressing the Enter key..

because my experience is 

- I want to search `Paragraph`
- I type `P`
- it goes in `PostFindMode`

there must me something triggering `PostFindMode` at the wrong time

**Comment by alk3mist** [comment]
I wonder if this issue might be related to this FF feature? 
https://support.mozilla.org/en-US/kb/accessibility-features-firefox-make-firefox-and-we#w_search-for-text-when-you-start-to-type

**Comment by fabriziobertoglio1987** [comment]
I was trying some new plugins and just find out 2 awesome tools for firefox which improve and can also replace Vimium

https://github.com/tridactyl/tridactyl
https://github.com/glacambre/firenvim

I just started using this extensions after watching the video below which allows me to use full nvim editor in every firefox input box, feature currently missing in Vimium but perfectly integrated!
https://youtu.be/1iuzniAe44Q

**Comment by spockupo** [comment]
> 
> 
> Always reproducible on manjaro linux, ff 86, vimium 1.66.
> 
> Only one letter after slash is accepted, everything else is swallowed. Interestingly, if you start searching with slash (that is, it will show you //), then the search works fine and you can type as much as you want.

...unless it actually finds a slash and the character you typed following // - then it's the same behaviour and no longer works.  At least on Win10, FF 87.0.

**Comment by dkotik** [comment]
Reproducible on POP OS, Firefox 86

**Comment by Melandel** [comment]
Quick question from a newbie: [when] will this merge be available on https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/versions/ ?

**Comment by chunga2020** [comment]
Still an issue in v1.66 with Firefox 88.0.1 on Ubuntu 21.04. Any updates?

**Comment by aalvarado** [comment]
I got an update for it today and seems fixed in version `v1.67`. Thank you for fixing it! Very cool

**Comment by WhiteBlackGoose** [comment]
Hi! Still hitting this issue. Vimium 1.67.1, Mozilla Firefox 106.0b4

**Comment by gdh1995** [comment]
@WhiteBlackGoose Confirmed. This is because recent updates in Firefox break the way Vimium recognize Firefox (#4033), and #4080 will help.

**Comment by WhiteBlackGoose** [comment]
I see. Thanks so much for your work!

By the way... weirdly enough, I cannot reproduce it right now, and `/` works :flushed:

**Comment by gdh1995** [comment]
@WhiteBlackGoose Firefox 106.0b9 rollbacks the default value of `extensions.InstallTrigger.enabled` on its `about:config` page, from `false` back to `true`, so `InstallTrigger` comes back and Vimium learns it's in Firefox again.

**Comment by vyv03354** [comment]
Currently `extensions.InstallTrigger.enabled` is `false` only on Nightly an early Beta. It will be tuned to `false` on all channels in the future. Please do not depend on `InstallTrigger`, period.

**Comment by philc** [comment]
The use of InstallTrigger is discussed in #4033 and is now resolved (removed) in c5f232c75ee5fafd95eda456c1db88363902814a.
