### ISSUE TITLE
Bookmark search in bookmarklet contents

### ISSUE THREAD

**Issue by lonelykid** [philc/vimium#3777]
**Describe the bug**
Bookmarklet is all shortened to `javascript:...`. Thus searching does not work on its content. I don't add names to bookmarks on my toolbar to save some space. I only add favicons to them. For bookmarks in folders. I do assign names. I need vimium to search bookmarklet contents. Also I think first 30 characters of the bookmarklet can be displayed. This would be a easy fix. I can PR if allowed.

**To Reproduce**
1. open omnibox with either b or B
2. type content of a bookmarklet
https://github.com/philc/vimium/blob/bdf654aebe6f570f427c5f7bc9592cad86e642b5/background_scripts/completion.js#L260
Include a screenshot if applicable.

**Browser and Vimium version**
Vimium 1.66
chromium 90

If you're using Chrome, include the Chrome and OSS version found at chrome://version. Also include the Vimium version found at chrome://extensions.

If you're using Firefox, report the Firefox and OS version found at about:support. Also include the Vimium version found at about:addons.

**Comment by gdh1995** [comment]
As a work around. You may copy your JS bookmarks on toolbar into a special sub-folder and assign meaningful names to those new items.

Reason of the current code: JS urls are usually too complicated to read (#961), and then it's my idea in https://github.com/philc/vimium/pull/2089#issuecomment-210328262 to ignore js code when matching.

**Comment by lonelykid** [comment]
ok. I don't understand what's wrong with displaying and matching bookmarklet contents. but since it has been this way for some time, let's leave this issue here to see if other people would want this.
