### ISSUE TITLE
"Follow link" function hints not showing

### ISSUE THREAD

**Issue by damianjozwiak** [philc/vimium#3778]
When I press the F key to open a link, the "Open link in current/new tab" pop-up shows up, but the link hints don't, as shown in the screenshot. On some pages the hints are not shown at all and on some of them they are shown lower than they should be, making it impossible to know which link do they relate to.

![image](https://user-images.githubusercontent.com/39242831/110092545-ffcc9d00-7d99-11eb-9eea-58929e4218ba.png)

**Browser version:** 1.20.110 Chromium: 88.0.4324.192 (Official Build) (64-bit)
**Vimium version:** 1.66

**Comment by gdh1995** [comment]
Could you provide a snapshot of the page's console log messages (open "Developer Tools" for the page and click the "console" panel), when LinkHints can not show hint markers?

On Windows/Linux, <kbd>F12</kbd> can open the Developer Tools; on macOS, <kbd>⌘ + Option + i</kbd> does so.

**Comment by damianjozwiak** [comment]
I'd like to, but the console log is empty

**Comment by gdh1995** [comment]
Hello, I think maybe your issue is just like #3827 .
