### ISSUE TITLE
`PassNextKey normal` doesn't work on Firefox

### ISSUE THREAD

**Issue by rddunphy** [philc/vimium#3781]
**Describe the bug**

In my Vimium options I have the following mappings:

```
map <c-]> passNextKey
map <c-}> passNextKey normal
```

`passNextKey` works as expected, but `passNextKey normal` only works when I'm already in normal mode. When I type <kbd>Ctrl</kbd> + <kbd>}</kbd> in normal mode, the HUD displays this:

![image](https://user-images.githubusercontent.com/10012625/110484385-822ec700-80e2-11eb-8a02-fd7da70bd2f4.png)

But when I'm either in insert mode or editting a text field, typing <kbd>Ctrl</kbd> + <kbd>}</kbd> appears to do the same as just `passNextKey`:

![image](https://user-images.githubusercontent.com/10012625/110484705-d174f780-80e2-11eb-9f67-ce53b6b66eb5.png)

**To Reproduce**
1. Add `map <c-}> passNextKey normal` to Vimium options
2. Click on a textarea (the GitHub comment box works for this)
3. Type <kbd>Ctrl</kbd> + <kbd>}</kbd> foolowed by <kbd>F</kbd>
4. Instead of activating link hints, an `f` is inserted into the textarea

**Browser and Vimium version**

Firefox 86.0 on Kubuntu 20.10
Vimium 1.66

Edit: typo in version number

**Comment by webartifex** [comment]
I can confirm this bug on Firefox 88.0 on Ubuntu 20.04

**Comment by gdh1995** [comment]
The works as designed. Keys of `PassNextKey` in insert mode to bypass Vimium's handler for <kbd>Escape</kbd>, so that `<c-]><esc>` will pass <kbd>Escape</kbd> to pages (#1985). While it's not expected to enter a normal version of `PassNextKey` mode.

**Comment by rddunphy** [comment]
According to the [Tips and Tricks page](https://github.com/philc/vimium/wiki/Tips-and-Tricks#disabling-pass-keys) on the wiki, `PassNextKey normal` should "Execute just one Vimium normal-mode command." My understanding of this is that if you're in insert mode, it will execute the following binding as if you were in normal mode.

**Comment by gdh1995** [comment]
Um, it was usually used in normal mode and to bypass existing passKeys matched in exclusion rules.

**Comment by rddunphy** [comment]
Ah right, thanks for clearing that up! I thought it was intended as a way to execute Vimium commands from anywhere - this would be useful since some websites make it difficult to leave text inputs (e.g. in the WhatsApp web app the input field is immediately refocussed after pressing Escape, so there's no easy way to navigate away without using the mouse).

**Comment by gdh1995** [comment]
As for this need, you may try my customized version of Vimium - [Vimium C](https://github.com/gdh1995/vimium-c) - and it allows  `<f1> ~ <f12>` in insert mode by default. If you need you can use `mapKey` to change how it handles F1~F12, or make it recognize other keys as insert-mode-usable (https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box).
