### ISSUE TITLE
White background on Dark Github

### ISSUE THREAD

**Issue by weeebdev** [philc/vimium#3797]
**Describe the bug**
There is a white background when triggering vimium inside of Github with dark theme.

**To Reproduce**
1. Go to URL 'https://github.com/'
2. Click on '/' or 'o'

![image](https://user-images.githubusercontent.com/48881444/113290062-c2f0b900-92f9-11eb-9d83-12f3cd1aa6aa.png)
![image](https://user-images.githubusercontent.com/48881444/113290080-ca17c700-92f9-11eb-9760-07310e78da5e.png)

**Browser and Vimium version**

Vivaldi | 3.7.2218.52 (Stable channel) (64-bit)
-- | --
Vimium|1.66

I know that's the duplicate of #3732 and #3452 , but the solution with
```css
iframe.vimiumUIComponentVisible {
    color-scheme: none;
}
```
didn't work for me.

**Comment by gdh1995** [comment]
Seems like #3732 .

**Comment by Adoliin** [comment]
I had this problem too and when I decided to open a new issue, I found yours.
Also I am using a custom CSS dark theme for vimium which works well for all sites except GitHub

**Comment by weeebdev** [comment]
> I had this problem too and when I decided to open a new issue, I found yours.
> Also I am using a custom CSS dark theme for vimium which works well for all sites except GitHub

Same. I used Dracula for Vimium, but it has nothing to do with this issue. I tried default vimium settings and it's the same

**Comment by Adoliin** [comment]
I guess there is no maintainer that have noticed this issue yet. So I will try debugging this in my free time and submit a pull request if I found the cause of the problem.

**Comment by gdh1995** [comment]
@Adoliin Have you tried https://github.com/philc/vimium/issues/3732#issuecomment-749997600 ?

**Comment by weeebdev** [comment]
> @Adoliin Have you tried [#3732 (comment)](https://github.com/philc/vimium/issues/3732#issuecomment-749997600) ?

It didn't work for me

**Comment by Adoliin** [comment]
> @Adoliin Have you tried [#3732 (comment)](https://github.com/philc/vimium/issues/3732#issuecomment-749997600) ?

Yes fortunately [#3732 (comment)](https://github.com/philc/vimium/issues/3732#issuecomment-749997600) worked for me but only if I edit the content_scripts/vimium.css and pack the extension myself.
Is there no other way to include it in my custom CSS config? And if is it possible why not include this "fix" in the master branch?
Also thanks for your help :)

**Comment by Adoliin** [comment]
> It didn't work for me
@weeebdev I guess you didn't get it. You must clone this repo and add `.vimiumUIComponentVisible { color-scheme: light; }` to `/content_scripts/vimium.css` and then load the extension in chrome extension settings.
I hope this helps you.

**Comment by Adoliin** [comment]
> It didn't work for me

@weeebdev I guess you didn't get it. You must clone this repo and add `.vimiumUIComponentVisible { color-scheme: light; }` to `/content_scripts/vimium.css` and then load the extension in chrome extension settings.
I hope this helps you.

**Comment by weeebdev** [comment]
> > It didn't work for me
> 
> @weeebdev I guess you didn't get it. You must clone this repo and add `.vimiumUIComponentVisible { color-scheme: light; }` to `/content_scripts/vimium.css` and then load the extension in chrome extension settings.
> I hope this helps you.

Oh. I see. I did it in configurations, so that's why it didn't work. Do they plan to release it on Chrome Store? I'd prefer from store rather than build myself

**Comment by Adoliin** [comment]
> > > It didn't work for me
> > 
> > 
> > @weeebdev I guess you didn't get it. You must clone this repo and add `.vimiumUIComponentVisible { color-scheme: light; }` to `/content_scripts/vimium.css` and then load the extension in chrome extension settings.
> > I hope this helps you.
> 
> Oh. I see. I did it in configurations, so that's why it didn't work. Do they plan to release it on Chrome Store? I'd prefer from store rather than build myself

I guess all we can do for now is wait until they merge it in `master` and then release in chrome store as the next version rolls out.
In the meantime you can try building it yourself.
