### ISSUE TITLE
vomnibar: change "tab" descriptor?

### ISSUE THREAD

**Issue by drewauff** [philc/vimium#3799]
I am using a custom css, the only left for me to change is the word "tab" that appears before the tabs title in the vomnibar?

I have been through all the code in the chrome extension but cant find any reference to it anywhere.

Have I missed it? 

I want to change to something else more to my liking/needs.

**Comment by gdh1995** [comment]
It's built in:

https://github.com/philc/vimium/blob/bdf654aebe6f570f427c5f7bc9592cad86e642b5/background_scripts/completion.js#L74-L81

**Comment by drewauff** [comment]
@gdh1995 so cant be changed? 

That label just seems so janky and out place.

**Comment by drewauff** [comment]
@gdh1995 errr the code is very different to the chrome store version...

**Comment by drewauff** [comment]
what I want is when the type is detected as "tab" then instead of the word "tab" display insertTextIdentifer for example.

**Comment by drewauff** [comment]
Thanks for the input, figured it out myself.
