### ISSUE TITLE
Add a "pass-through next key" shortcut

### ISSUE THREAD

**Issue by philc** [philc/vimium#38]
This is so you can pass-through one keystroke into the page or browser which Vimium will ignore.

**Comment by smblott-github** [comment]
Closing.
Partly because passkeys often circumvents the need for this.  And, in other cases `i`, then something, then `Esc` isn't so bad.

(Also, what is "one key".  Many sites, like Google Drive, use two-key shortcuts.  Probably best just not to go there.)

**Comment by j-cr** [comment]
For anyone googling this:

`map \ passNextKey`
