### ISSUE TITLE
Vimium does not start up with browser

### ISSUE THREAD

**Issue by drewauff** [philc/vimium#3802]
Whenever I restart my browser I have to refresh the the page to load Vimium, is there a way to 
force Chrome or Vivaldi (I use both) to load vimium properly at startup?

**Comment by drewauff** [comment]
am dumb.

**Comment by kvnloughead** [comment]
Hi, maybe I'm a bit dumb too. How did you resolve this?

**Comment by kvnloughead** [comment]
am dumb too.

**Comment by drewauff** [comment]
lol
