### ISSUE TITLE
'/' conflict with Chrome shortcut of jump to search input

### ISSUE THREAD

**Issue by zitup** [philc/vimium#3805]
**Describe the bug**
`/` call Vimium conflict whit Chrome’s `/` to focus on search input on chrome search page

![image](https://user-images.githubusercontent.com/12710516/114995895-dd698b80-9ed0-11eb-9767-384af7ba035c.png)
which in red box mean click '/' to jump to search input

Chrome version: 90.0.4430.72
Vimium version: 1.66

**Comment by gdh1995** [comment]
You can `unmap /` and map another key to enterFindMode - https://github.com/philc/vimium#custom-key-mappings

**Comment by zitup** [comment]
ok, thanks
