### ISSUE TITLE
Is there a way to use queue link mode with links opening in the same tab?

### ISSUE THREAD

**Issue by aaron-a-f** [philc/vimium#3808]
I've realised that using the link mode with queue allows me to really quickly navigate through forms and webpages, but it requires holding down shift in order for the link to open in the same tab. Is there a way to get link mode to stay on until cancelled, and to permanently open in the same tab?

Many thanks

**Comment by gdh1995** [comment]
There's a command named `LinkHints.activateModeWithQueue` and you may use <kbd>Alt-F</kbd> to trigger it.

**Comment by aaron-a-f** [comment]
@gdh1995 Thanks for the reply. This is actually the mode I'm talking about. I'm wondering if there is a way to get link mode with queue to open links in the same tab, and not a new one?

**Comment by gdh1995** [comment]
Um, if a link opens in a same tab, then the old page, including its LinkHints mode, will be unloaded. But up to now there's no logic in Vimium to auto re-activate LinkHints during new pages loading.

**Comment by aaron-a-f** [comment]
Thanks @gdh1995. The use case that I'm using this for is when I want to quickly fill out forms or navigate inside a single page application. I've created a fork where "activate mode with queue" opens links in the same tab by default, and it's a much faster way to interact with forms and navigate SPAs.

Thanks for your help, will resolve this now.

**Comment by gdh1995** [comment]
Why does your website open a new tab when you want to click form fields? It's somehow a bug of the website.

If you do need this, you may also try my customized version of Vimium, named [Vimium C](https://github.com/gdh1995/vimium-c), and it supports more modes in LinkHints. For this issue, you may use:
```
map <a-f> LinkHints.activateMode mode=16
```

The `16` means `queue` without `newTab`, and `LinkHints.activateModeWithQueue` indicates `mode=18`

**Comment by AntonioRedondo** [comment]
@aaron-a-f It seems that the command you actually intended to you use was the one fired with `f` (lower-case f, open a link in the current tab) rather than with `F` (upper-case F, open a link in a new tab)?
