### ISSUE TITLE
Search is not working on Firefox nightly

### ISSUE THREAD

**Issue by zer09** [philc/vimium#3809]
**Describe the bug**
When you trying to search  using the "/", you can only type the first letter then the search box lost focus.
BTW I am using Firefox nightly.

**To Reproduce**
1. Go to any website
2. Type "/" to search.
3. After the first letter is typed the search box lost focus.

**Browser and Vimium version**
Browser: Firefox Nightly 90.0a1 (2021-04-24) (64-bit)
Vimium: v 1.66

**Comment by gdh1995** [comment]
Have you tried the fix in #3801 ?

**Comment by zer09** [comment]
Sorry, I tried but still wont work

**Comment by gdh1995** [comment]
What's your operating system? I tested PR 3801 on my Win 10 20H2 x64 with Firefox 90.0a1 build 20210424155423 (https://ftp.mozilla.org/pub/firefox/nightly/2021/04/2021-04-24-15-54-23-mozilla-central/), and Vimium's FindMode works.

**Comment by zer09** [comment]
I am on Manjaro.
When I tried, sometimes I can type the whole word but sometimes I cant. And also I cant cycle to the search word, and when I press "/" for the second time the FindMode wont show up

**Comment by gdh1995** [comment]
I beg your pardon, but have you checked out the branch named `gdh1995:fix-findmode-on-ff`?

**Comment by zer09** [comment]
Im so sorry, I forgot to checkout the branch. And its working now.

**Comment by ranelpadon** [comment]
I have same issue on Mac Mojave - Firefox 88. Does the fix will be rolled-out soon? And does the Vimium extension will auto-update itself? Thanks :)

**Comment by lindhe** [comment]
I'm running FF 89.0 and it's broken.

**Comment by ranelpadon** [comment]
BTW, I've switched to **Vimium-C** since few weeks ago, since it's an improved **Vimium**, with more features, no issues anymore in searching:
https://github.com/gdh1995/vimium-c/
