### ISSUE TITLE
can anyone explain the permission it requests access to

### ISSUE THREAD

**Issue by JunkyardCat** [philc/vimium#3812]
can anyone please tell me what information vimium gets and send back to server if ever i will allow the permission?

**Comment by WuerfelDev** [comment]
From the chrome store description:
> NOTE Chrome has some alarmist messaging around the permissions that Vimium needs to run. Really all it's asking for is that Vimium's javascript be loaded into every page. Don't be alarmed. Vimium never talks to any servers and does absolutely nothing with your data. Read the open source code if you're curious.
> (https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb)

Also:
https://github.com/philc/vimium/wiki/Privacy-policy

**Comment by philc** [comment]
Thanks @WuerfelDev for answering. I've added an entry to the [FAQ](https://github.com/philc/vimium/wiki/FAQ#why-does-the-vimium-extension-require-so-many-chrome-permissions).
