### ISSUE TITLE
[FindMode] Unable to jump to next or previous match

### ISSUE THREAD

**Issue by twio142** [philc/vimium#3818]
**Describe the bug**
Unable to cycle among find matches using `n` / `N`. When pressing `n`, the highlight just stays on the first match. After clicking aside and then press `n` again, it sometimes jump to the next match, but sometimes still stick with the same one.

**To Reproduce**
1. Type `/query` (it does prompt with the query and the count of matches)
2. Press `enter`
3. Press `n` or `N`

**Browser and Vimium version**

MacOS 11.3
Chrome 90.0
Vimium: the newest version of this repo (not the v1.66 release, that one doesn't has this bug though)

**Comment by gdh1995** [comment]
It might be the same issue as #3774 and would be fixed by #3801

**Comment by twio142** [comment]
Fixes the problem. Thanks!
