### ISSUE TITLE
Docs: can't find the commands for any action to remap

### ISSUE THREAD

**Issue by Aaditay** [philc/vimium#3822]
Vimium as of now do not implement any ```remap``` command for configuring stuff.
So for remapping binding we will need to map our new  key binding to action's command

For example i want to remap gg to g.
that's how it would look like
``` 
unmap gg
map g scrollToTop
````

Now i can't find any doc that lists the commands for every default mapping, i will have to look into the [source code](https://github.com/philc/vimium/blob/master/background_scripts/commands.js) to  what ```gg``` commands to (```scrollToTop```in the the case)
 
So,  Any wiki that lists the commands for every default keybinding will be helpful for Vimium Users

**Comment by gdh1995** [comment]
Oh it's in https://github.com/philc/vimium#keyboard-bindings .

**Comment by FORGIS98** [comment]
You also have Vimium command listing when you edit options from the browser: right-click on Vimium plugin >> Options >> Show available commands. There you have a full list of commands with "key code" names. Like you have `f` that opens a link in the current tab its "key code" is `LinkHints.activateMode`.

**Comment by Aaditay** [comment]
nvm, i didn't noticed that. Also there is Show advanced command options there.
