### ISSUE TITLE
Vimium does not work on localhost, pdf (local or web link) and untill web page has loaded.

### ISSUE THREAD

**Issue by backward-crazy-mage-puppy-36** [philc/vimium#3826]
Vimium version 1.66

Browsers: 
Google Chrome (Version 91.0.4472.77) 
Chromium Brave (Version 1.24.85 Chromium: 90.0.4430.212)
Chromium Edge (91.0.864.37)
(I have tried with older versions as well, the same is true for chrome as well)

OS: Ubuntu 21.04, MacOS Catalina

ISSUE: Vimium does not work on localhost pages (e.g. http://localhost:3000/). There are no excluded urls and keys rules enabled. 
Is it possible to enable Vimium for broswer settings tab ( brave://extensions/ ;  chrome://version etc.)
Is it possible to enable Vimium for PDFs (local files or web links e.g. https://readthedocs.org/projects/copyq/downloads/pdf/latest/)?
Vimium also does not work till the page has loaded. So if you want to close a popup window, you have to wait for it finish loading. Can this behaviour be changed?

**Comment by 3nt3** [comment]
that is expected behavior since vimium is an extension and injects code for its own ui into the web pages.

**Comment by gdh1995** [comment]
> on localhost

It's a strange bug and I can not reproduce it on my computer. Will Vimium C work on a simple Nginx Welcome page at `http://localhost:8080/` ?

> on `chrome://*`

I have a customized version of Vimium, named [Vimium C](https://github.com/gdh1995/vimium-c), and it can work on `chrome://*` if you:
* enable an option named `Run on chrome://* pages` on Vimium C Options
* and enable `#extensions-on-chrome-urls` on `chrome://flags`
* it seems that it can't work on Brave's new tab page

> on PDF files

If you also install [PDF Viewer for Vimium C](https://chrome.google.com/webstore/detail/pdf-viewer-for-vimium-c/nacjakoppgmdcpemlfnfegmlhipddanj), then Vimium C can work on PDF reading pages.

**Comment by backward-crazy-mage-puppy-36** [comment]
> that is expected behavior since vimium is an extension and injects code for its own ui into the web pages.

Are all 4 expected behaviour or are you referring to vimium waiting for pages to load?

**Comment by backward-crazy-mage-puppy-36** [comment]
w

> > on localhost
> 
> It's a strange bug and I can not reproduce it on my computer (Vimium master, MS Edge 90). Will Vimium work on a simple Nginx Welcome page at `http://localhost:8080/` ?
> 
> > on `chrome://*`
> 
> I have a customized version of Vimium, named [Vimium C](https://github.com/gdh1995/vimium-c), and it can work on `chrome://*` if you:
> 
> * enable an option named `Run on chrome://* pages` on Vimium C Options
> * and enable `#extensions-on-chrome-urls` on `chrome://flags`
> * it seems that it can't work on Brave's new tab page
> 
> BTW, will Vimium C work on your localhost:3000 ?
> 
> > on PDF files
> 
> If you also install [PDF Viewer for Vimium C](https://chrome.google.com/webstore/detail/pdf-viewer-for-vimium-c/nacjakoppgmdcpemlfnfegmlhipddanj), then Vimium C can work on PDF reading pages.

unfortunately both PDF Viewer for Vimium C & Vimium C did not work for me n Brave. I have not tried them in edge or crome.

**Comment by gdh1995** [comment]
What error did the two extensions report? Extensions on Chrome Web Store should be able to work on Brave without any change.

**Comment by 3nt3** [comment]
> > that is expected behavior since vimium is an extension and injects code for its own ui into the web pages.
> 
> Are all 4 expected behaviour or are you referring to vimium waiting for pages to load?

I think all are expected since you
1. can't inject js if the page hasn't loaded
2. can't inject js into a pdf
3. can't inject js into special browser sites (settings, extension etc.) either because they are not using js or because chrome prohibits it

Only exception would be localhost since that should just be normal html.

**Comment by backward-crazy-mage-puppy-36** [comment]
> > > that is expected behavior since vimium is an extension and injects code for its own ui into the web pages.
> > 
> > 
> > Are all 4 expected behaviour or are you referring to vimium waiting for pages to load?
> 
> I think all are expected since you
> 
> 1. can't inject js if the page hasn't loaded
> 2. can't inject js into a pdf
> 3. can't inject js into special browser sites (settings, extension etc.) either because they are not using js or because chrome prohibits it
> 
> Only exception would be localhost since that should just be normal html.

Thanks for the explanation. That clears it up.

**Comment by fabriziobertoglio1987** [comment]
solved with vimiumc
