### ISSUE TITLE
duckduckgo "remove unofficial extensions"

### ISSUE THREAD

**Issue by 3nt3** [philc/vimium#3828]
**Describe the bug**

When searching with duckduckgo, it does not show results but redirects to [this page](https://help.duckduckgo.com/add-ons/removal/).

**To Reproduce**
1. start vomnibar
2. search something
3. redirect

**Browser and Vimium version**

Brave/Chrome Version: Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit)

Vimium Version: 1.66

**Comment by gdh1995** [comment]
What's your search engine rule? During my tests, `d: https://duckduckgo.com/?q=%s DuckDuckGo` works as expected.

It your rule is the same, then it seems some other extensions on your computer hacks Chrome.

**Comment by 3nt3** [comment]
yes my search engine was bad. It was `https://duckduckgo.com/search?q=%s` instead of `https://duckduckgo.com/?q=%s`.
