### ISSUE TITLE
Vimium options not showing where to change font size

### ISSUE THREAD

**Issue by creednaylor** [philc/vimium#3829]
**Describe the bug**

When I go to the Vimium options it does't give me the option to change the CSS even though I see it here vimium/pages/options.html. I want to increase the font size of the little tags that appear when I press "f" on a webpage.

**To Reproduce**
1. Go the options for the Vimium Chrome extension from within chrome://extensions.

Screenshot of what I get:

![image](https://user-images.githubusercontent.com/16467643/120388745-c946e580-c2e8-11eb-9c59-26733931b995.png)

**Browser and Vimium version**

 I'm on Vimium 1.66, the latest release. Chrome version 91.0.4472.77 (Official Build) (x86_64)

**Comment by gdh1995** [comment]
there's a button of "show advanced options" at the bottom of Vimium Options page. click it to see more options.



---Original---
From: "Creed ***@***.***&gt;
Date: Wed, Jun 2, 2021 04:53 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [philc/vimium] Vimium options not showing where to change font size (#3829)




 
Describe the bug
 
When I go to the Vimium options it does't give me the option to change the CSS even though I see it here vimium/pages/options.html. I want to increase the font size of the little tags that appear when I press "f" on a webpage.
 
To Reproduce
 Steps to reproduce the behavior:
  
Go the options for the Vimium Chrome extension from within chrome://extensions 
 

 
Browser and Vimium version
 
I'm on Vimium 1.66, the latest release. Chrome version 91.0.4472.77 (Official Build) (x86_64)

**Comment by creednaylor** [comment]
There it is, thank you!!! Worked putting in my own CSS!
