### ISSUE TITLE
[BUG] F and f have identical behavior

### ISSUE THREAD

**Issue by thevinter** [philc/vimium#3833]
**Describe the bug**
Pressing `f` and selecting a link doesn't open it in the same tab but it opens the link in a new tab in a way similar to the `F` behavior

**To Reproduce**
1. Press `f`
2. Press the keys corresponding to any link

**Browser and Vimium version**:
* Brave | 1.25.70 Chromium: 91.0.4472.77 
* Vimium 1.66

**Comment by thevinter** [comment]
I restarted the pc and it started working

**Comment by ckmufeng** [comment]
hemmm, i meet exact the same issue.
