### ISSUE TITLE
[not so important Bug report, easy fix]: change Plugin's website on the chrome store to the new github pages domain

### ISSUE THREAD

**Issue by TrevCan** [philc/vimium#3837]
whoever is in charge of the plugin's page on the google chrome store (https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb), I would advise to change the link of the homepage, as it does not work due to the change of `github.com` (https://vimium.github.com/) to `github.io` (https://vimium.github.io/)

**Comment by philc** [comment]
Thank you very much the heads up. I've updated the link and the new chrome store page is in approval; t should go live in the next few days.
