### ISSUE TITLE
Vimium Firefox Dark Mode

### ISSUE THREAD

**Issue by troydm** [philc/vimium#3856]
Vimium 1.67 Dark Mode is not working in Firefox 89.0.2 despite dark theme enabled and Dark Reader present and enabled

**Comment by snprajwal** [comment]
Vimium is configured using custom CSS. See under Advanced Options while configuring it.

**Comment by troydm** [comment]
@snprajwal it says leave it empty to reset, so I empty this option and save settings but still don't get Dark theme vimium UI

**Comment by snprajwal** [comment]
https://github.com/thuanpham2311/vimium_dark_theme

**Comment by troydm** [comment]
@snprajwal thx, didn't know about that
