### ISSUE TITLE
Logitech mouse M337 wheel left/right tilt are disabled by the extension.

### ISSUE THREAD

**Issue by imageslr** [philc/vimium#3857]
**Describe the bug**
I'm using [Logitech mouse M337](https://secure.logitech.com/en-au/manuals/m337-setup-guide).  

I configured "Versatile scroll wheel" function as:
1. **tilt left**: go back
2. **tilt right**: go forward

![image](https://user-images.githubusercontent.com/17822028/125424481-a5e984d4-b4dd-4de6-8453-b237acebcf42.png)

It works in Stealth mode, but not compatible with Vimium.

**Browser and Vimium version**

Google Chrome | 91.0.4472.114 (正式版本) (x86_64)
修订版本 | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
操作系统 | macOS 版本10.15.7（版号19H2）
JavaScript | V8 9.1.269.36

Vimium 1.67

**Comment by gdh1995** [comment]
Please go to https://gdh1995.cn/vimium-c/keyboard-test.html, disable Vimium and then check what keys the mouse sends to your browser on tilt left/right.

**Comment by imageslr** [comment]
@gdh1995 Hi, this page won't capture any mouse event at all, even left/right click.

**Comment by gdh1995** [comment]
Even when `tilt left` and with Vimium disabled?

**Comment by imageslr** [comment]
Yes. I have uninstalled Vimium. When `tile left`, it just simply go back.

I also changed `tilt left` config, it worked but nothing captured on the page.

![image](https://user-images.githubusercontent.com/17822028/125430478-b0fa9faf-bd95-45bd-9d1c-f54401d80c3d.png)

**Comment by gdh1995** [comment]
What will a `tilt left` do, if you: install Vimium, refresh test page, left-click blank area of the page and then trigger `tilt left`?

BTW, I have a customized version of Vimium, named [Vimium C](https://github.com/gdh1995/vimium-c). Could you also do tests on it ?

**Comment by imageslr** [comment]
The page cannot capture "tilt left" event for both extensions.

But "tile left" works after I reinstall vimium. I don't know why...

I guess this is a problem of Logitech Options itself, not Vimium. 

Thanks for your help! If there are any useful information, I will let you know.
