### ISSUE TITLE
<enter> in excluded keys?

### ISSUE THREAD

**Issue by benthamite** [philc/vimium#3863]
Is there a way to add `<enter>` to the "Keys" list under "Excluded URLs and keys". I currently have the string `?jknpxervctgils#uld/y`, but neither appending `<enter>` to it nor replacing it with `<enter>` seems to work.

**Comment by gdh1995** [comment]
No there isn'.t Exclusion doesn't support long keys.

**Comment by benthamite** [comment]
Thank you.
