### ISSUE TITLE
In chrome, we can't enter caret mode.

### ISSUE THREAD

**Issue by bushnerd** [philc/vimium#3865]
**Describe the bug**
In version 1.66, we can type 'v' to enter 'Visual mode', then type 'c' to enter 'Caret mode' to change the cursor's position to where we want to process.

But when 1.67, we can not do that. Actually, i don't know how to enter 'Caret mode'.

**To Reproduce**
As above.

**Browser and Vimium version**

Chromium 80.0.3987.163
Vimium 1.67

**Comment by BachoSeven** [comment]
this should be fixed by #3877
