### ISSUE TITLE
Feature request: follow link - use letters on left (or right) side of the keyboard only

### ISSUE THREAD

**Issue by predkambrij** [philc/vimium#3871]
By default when we press f (or shift f) we get annotated links with letters, but those letters are from both sides of keyboard. This is a bit annoying, because if we're switching back and forth from browser to other application that requires switching from mouse to keyboard, only to type some letters from right side of the keyboard.

So, I propose that there'd be a setting to limit those letters to only left side of the keyboard (or right side for left-handers).

**Comment by gdh1995** [comment]
![image](https://user-images.githubusercontent.com/5547703/126636983-3afa7abc-cf02-49bc-bb60-08166ffca1b2.png)

**Comment by predkambrij** [comment]
Thanks! I didn't notice Advanced Options :)
