### ISSUE TITLE
Allow custom keymap only for specific sites

### ISSUE THREAD

**Issue by CarlaFernandez** [philc/vimium#3874]
Hello,

I usually use Jupyter Notebooks in the browser. These notebooks have custom keymaps which also function similarly to Vim, so Vimium interferes with them. For example, to enter a search function you must use Esc+F, which if you try with Vimium activated doesn't work (of course, it shows you link hints).

My current solution is simply deactivating Vimium completely for Jupyter Notebook URLs, but I would like the best of both worlds: being able to create custom keymaps which would apply only to Jupyter Notebook URLs. In any other site, the usual keymaps would apply.

Would this be possible? I think it's a pretty amazing feature.

**Comment by gdh1995** [comment]
In short, Vimum doesn't support such a feature. You may see my feature design (and customized version of Vimium) in https://github.com/philc/vimium/issues/3272#issuecomment-475296695 .

**Comment by CarlaFernandez** [comment]
Amazing! Will give it a try, thank you :)

**Comment by CarlaFernandez** [comment]
Hello again @gdh1995,
I tried to configure Vimium C as you explain in your post, but it seems not to be working. Here's a pic of my configuration:
![image](https://user-images.githubusercontent.com/9136877/127447981-fcede54e-29e6-4566-ad6e-d3ea7d925e00.png)

As I understand, with this configuration Vimium should only work if I press the f9 key, and when I'm done with it I should press f10 to exit insert mode. However, if I don't press f9 and just press f, link hints still appear. Any ideas?

**Comment by CarlaFernandez** [comment]
Ah! I managed to get it working. Turns out the URL was http instead of https, so the URL pattern wasn't matching. Finally replaced it by ^http://localhost:* and it works wonders.
Thanks again!

**Comment by gdh1995** [comment]
Yes Vimium C tries to guess a regexp from your pattern, but it failed and made a wrong one.

BTW, as said in https://github.com/gdh1995/vimium-c/wiki/Enable-or-Disable-all-frames-by-a-shortcut#how-to-switch-between-two-statuses , now you may use `vimium://status/toggle-enabled` to toggle status using only one key.

**Comment by CarlaFernandez** [comment]
cool!
