### ISSUE TITLE
Supporting new keyboard layouts

### ISSUE THREAD

**Issue by Rassska** [philc/vimium#3875]
Hi, there! 
Is it worth to work on adding new language keyboard layouts?

For instance, if I'll switch to the Russian layout, I'm not completely able to use vimium and it's a bit annoying to switch back every single time. 

To be honest, I can work on adding a simple thing, which will translate certain character to the eng char and it perfectly will work.
If not, I'm glad to hear what is your opinion on that?!

**Comment by gdh1995** [comment]
There have been features to do so:
1. https://github.com/philc/vimium#custom-key-mappings and https://github.com/philc/vimium/wiki/Key-Mappings
2. or just enable the `Ignore keyboard layout` option

![image](https://user-images.githubusercontent.com/5547703/127731460-8fb5c789-f376-43d6-be97-44881fb4bf46.png)

**Comment by Rassska** [comment]
> There have been features to do so:
> 
> 1. https://github.com/philc/vimium#custom-key-mappings and https://github.com/philc/vimium/wiki/Key-Mappings
> 2. or just enable the `Ignore keyboard layout` option
> 
> ![image](https://user-images.githubusercontent.com/5547703/127731460-8fb5c789-f376-43d6-be97-44881fb4bf46.png)

Sry, I didn't see that one :)
