### ISSUE TITLE
Feature request : going back to the previous position on the page.

### ISSUE THREAD

**Issue by politicus** [philc/vimium#3882]
I experience this use case at least one time a day and am well aware the question of going back to a position is possible (marks), has been posted few times on Github ([here](https://github.com/philc/vimium/issues/2261) and [here](https://github.com/philc/vimium/issues/2261)).

My use case is a little bit different. One could named it "marks for when you forgot to create a mark and should have created a mark".

Let's imagine you're on a news website, like reddit.com or the dailymail.co.uk, you keep scrolling trying to find one link worth clicking. Once you have found this link you mistakenly, for example, either hit the "Scroll to the top of the page (scrollToTop)" or the "Scroll to the bottom of the page (scrollToBottom)" key. 

Your are now at the top of the bottom of the page. Definitely, not where you want to. Your carelessness will force you to scroll back where you are. 

Wouldn't it be nice if, for example, every time, the user fires a special command, like one of the two I mentioned above, Vimium automatically would create a sort of mark, so the user could come back, right back, where he was on the page. 

And, if the user does not fire this "gotoMark" command right after having fired for example a "Scroll to the top of the page (scrollToTop)" or a "Scroll to the bottom of the page (scrollToBottom)" command, Vimium wouldn't create a mark, let him go navigate again, like nothing happened.

**Comment by gdh1995** [comment]
Up to now, Vimium's `scrollToTop` and `scrollToBottom` should have created a "in-page" mark (named ``` ` ```), and then you may press 
<kbd>\`</kbd><kbd>\`</kbd> (two ``` ` ``` character) to trigger `Marks.activateGotoMode` and  jump to the mark.

**Comment by politicus** [comment]
Thank you very much @gdh1995 for, one more time, putting me in the picture. 

I, now, understand what you mean with the two backticks ("jump back to the position before the previous jump -that is, before the previous gg, G, n, N, / or `a"). Hitting the backtick key triggers nothing for me, which makes completely sense as I remapped `Marks.activateGotoMode` to ctrl+g. 

In my experience, while using `scrollToTop` and `scrollToBottom` no in-page mark was created. When I triggered "Marks.activateGotoMode`, I was asked to select a mark I `Marks.activateCreateMode`. 

Hitting ctrl+g, invistes me to indicate a the mark I want to go to. No jump to the mark I want to go to.

For info, my settings are:

```
map <c-c> Marks.activateCreateMode swap
map <c-g> Marks.activateGotoMode swap
```

**Comment by gdh1995** [comment]
When you said about `scrollToTop`, did you mean a button which can be clicked to scroll to top on your test page?

Vimium's `scrollToTop` and `scrollToBottom` commands does create and update "local" marks. I've tested your mapping on a fresh profile of Chrome 92, and <kbd>g</kbd><kbd>g</kbd>, after a while, <kbd>Ctrl+G</kbd> and <kbd>\`</kbd> worked as expected.

**Comment by politicus** [comment]
By `scrollToTop`, I meant `Scroll to the top of the page (scrollToTop)` as defined in the Vimium settings.

I am using Brave Browser v92.1.27.109. and tried the following commands on reddit.com :

`scrollToBottom`,
Then `scrollToTop`,
Then `Marks.activateGotoMode ` (without the swap option)

And all I got is the little bar with `Go to mark...`.

**Comment by gdh1995** [comment]
Yes `Marks.activateGotoMode` will show `Go tomark ...`, but it should then accept <kbd>\`</kbd> as a "temporary" mark and scroll back (to bottom, in this example).

**Comment by politicus** [comment]
Found a workaround/solution/sort of an explanation.

Switching to the USA Input Source allowed me to use the backtick (the key next to the left `Shift` key). Then, and then only, it worked as you told me. 

Thank you for your help @gdh1995 !

**Comment by gdh1995** [comment]
Then you may use ```mapkey <xxx> ` ``` or enable the `Ignore keyboard layout` option to tell Vimium how to recognize ``` ` ``` correctly.

**Comment by politicus** [comment]
Enabling the `Ignore keyboard layout` messes everything. Tried with a few keys. Feels like my keyboard layout, while set to French doesn't behave as set to French. For example hitting the M key shows links when I is supposed to scroll to the bottom. 

So, not the best option I guess. 

About `` mapkey <xxx> ` ``   By what should I replace xxx ? The backtick key of my French keyboard?

**Comment by gdh1995** [comment]
> The backtick key of my French keyboard?

Yes. You may open https://gdh1995.cn/vimium-c/keyboard-test.html , make Vimium in insert mode, and then press ``` \` ``` to see values in the `Key` column.

**Comment by politicus** [comment]
I added `mapkey <220>`  \` to my Vimium settings. Tried scrollToBottom, Then scrollToTop, Then Marks.activateGotoMode (without the swap option) and nothing is happening. 

Apparently, `Go to mark ...` doesn't accept ` as a "temporary" mark.

**Comment by gdh1995** [comment]
Could you provide a snapshot of the test results on keyboard test.html?
I believe a "key" will never be 220.&nbsp;



---Original---
From: "Francois Albert ***@***.***&gt;
Date: Tue, Aug 10, 2021 18:19 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [philc/vimium] Feature request : going back to the previous position on the page. (#3882)




 
I added mapkey <220&gt;  ` to my Vimium settings. Tried scrollToBottom, Then scrollToTop, Then Marks.activateGotoMode (without the swap option) and nothing is happening.
 
Apparently, Go to mark ... doesn't accept ` as a "temporary" mark.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by politicus** [comment]
![test_5](https://user-images.githubusercontent.com/333521/128873769-ad49924c-d055-4436-911d-1ba20f64ff10.png)

**Comment by gdh1995** [comment]
Well, it seems your French keyboard layout doesn't support ``` ` ```, because `Dead` is not a reliable key name - many rare keys share such an identifier.

Fortunately, Vimium also treats ``` ' ``` (single quote) as a "local" mark name, so you may try `<c-g>'` .

**Comment by politicus** [comment]
Added `map <c-g>'` to my settings. Tried `scrollToBottom`, Then `scrollToTop`, Then `Marks.activateGotoMode` (without the swap option) then `Ctrl-g` and nothing is happening.

**Comment by gdh1995** [comment]
No. What I meant is not a mapping of `<c-g>'`. I mean, press `<c-g>` (using your old mappings) to activate Marks' `Goto` mode, and then press ``` ' ``` to trigger a last "local" mark.

**Comment by politicus** [comment]
When I activate `Goto` mode, then the backtick, nothing is happening. It just opens the `Go to mark...` window. The "local" mark is not activated.

**Comment by gdh1995** [comment]
Not “backtick” (``` ` ```), but the single quotation marks (`'`)
