### ISSUE TITLE
Feature Request: Allow Vomnibar.activate only with custom serach engine completion

### ISSUE THREAD

**Issue by JiguGit** [philc/vimium#3886]
To currently use a custom search engine, I have to open the Vomnibar, enter my keyword and then wait until completions for tabs, bookmarks and history are finished before the custom search is activated.

This takes several seconds, if one has many bookmarks, tabs and/or a long history.

Several issues have already talked about the slow performance:
- https://github.com/philc/vimium/issues/3661
- https://github.com/philc/vimium/issues/2131
- https://github.com/philc/vimium/issues/1802
- https://github.com/philc/vimium/issues/1790

It would be nice to use custom search immediately without having to wait for redundant completions.

**Comment by gdh1995** [comment]
You may use `keyword=<search-engine-name>` in Custom key mappings. For example:
```
map w Vomnibar.activate keyword=w
```

**Comment by JiguGit** [comment]
Thanks, this works. 

But is a bit tedious to maintain, since I use multiple custom search engines.
Currently I have added key mappings like this:
`map g<my-keyword> Vomnibar.activate keyword=<my-keyword>`
`map g<my-keyword-capitalized> Vomnibar.activateInNewTab keyword=<my-keyword>`
