### ISSUE TITLE
Webpage behind vomnibar completely blacked out.

### ISSUE THREAD

**Issue by drewauff** [philc/vimium#3898]
When the vomnibar is activated the current webpage is completely blacked out.

How can I change this to the page is still fully visible behind the vomnibar?

note: I dont me a transparent vomnibar.

**Comment by gdh1995** [comment]
Any screen snapshot of "blacked out"? It's strange since Vimium should not change page content on Vomnibar showing.

**Comment by drewauff** [comment]
I dont think a snapshot will help.

To put it simply, when vomnibar in active (visible) the entirety of the current is black.

I thought it was a variable in my custom theme..but it doesnt seeem like it. I have tried everything, I even when into vimiums files, specifically the directories Pages and content_scripts.

I admit I have tinkered with both vimium.css and vominibar.css to fix it, nothing changed so reverted back to the originals.
