### ISSUE TITLE
Add a pass-through mode

### ISSUE THREAD

**Issue by philc** [philc/vimium#39]
This is so you can pass-through all keystrokes into the page or browser which Vimium will ignore. This mode can be exited by hitting escape.

**Comment by rajeevksahu** [comment]
We value the cash the consumer pays to us that is why we repay it by providing the elevated level of reliability and commitment in our alternatives of Packing Moving Thane. You must comprehend all Expert contracts rightly with the mover or company before you sign any statements. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
We believe in the finish transparency in the deal that is why the Expert document has obvious reference of the terms and conditions and even expenses of our alternatives. We create everything obvious and do not impose any hidden expenses. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
EXPERT Packers is an knowledgeable moving company and has extremely knowledgeable best packers and movers in Thane. We are best known for our quick, simple, efficient and affordable moving alternatives throughout the nation.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
Nowadays, lifestyle has become so hectic that it is next to impossible to shift to another position with all your large content and stuffs. What to talk of remote locations, it is just difficult enough to even shift to close by locations. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by Evidlo** [comment]
This is not well-covered by insert mode, as insert mode tends to turn itself off when a textbox loses focus.  A passthrough-like mode should only be toggled by a keyboard shortcut.
