### ISSUE TITLE
<number>g to jump to tab

### ISSUE THREAD

**Issue by phoerious** [philc/vimium#390]
Feature request: use &lt;number&gt;g to jump to tab &lt;number&gt;. So 1g would jump to the first tab from the left, 5g to the fifth tab etc. -1g, -2g, -3g etc. could jump to the first/second/third etc. tab from the right.

**Comment by CaldwellYSR** [comment]
I think this is still useful especially for non-chrome users. I got used to Chrome's ctrl# shortcut  but Firefox doesn't have it. g$ and g0 are helpful but not quite what I'm looking for.

**Comment by smblott-github** [comment]
`2g0` takes you to the second tab. `3g0` the third.  And so on.

Remap `firstTab` if you want a different key binding.

**Comment by shafayetejaman** [comment]
Default ctrl+<tab index> is faster and ignores tab group

**Comment by ajwadjaved** [comment]
Was there any update on this? I wouldn't mind submitting a patch for this
