### ISSUE TITLE
[Bug] Vimium conflicts with Tencent Docs' shortcuts

### ISSUE THREAD

**Issue by wenfangdu** [philc/vimium#3904]
**Describe the bug**

If Vimium is enabled, <kbd>Ctrl</kbd>+<kbd>[</kbd> and <kbd>Ctrl</kbd>+<kbd>]</kbd> can't be used on Tencent Docs, which are for increasing/decreasing the font size of a document.

**To Reproduce**

1. Go to [Tencent Docs](https://docs.qq.com).
2. Create a document and put in some text.
3. Select the text and use <kbd>Ctrl</kbd>+<kbd>[</kbd> and <kbd>Ctrl</kbd>+<kbd>]</kbd> to change the font size.
4. Font size is not changing.

**Browser and Vimium version**

Chrome: 93.0.4577.63
Vimium: 1.67

**Comment by wenfangdu** [comment]
@gdh1995 Could you take a look at this, I didn't find the language switcher for Tencent Docs.

**Comment by gdh1995** [comment]
There's a command named `passNextKey` in Vimium and you may add a key mapping for it, trigger this key and then press `ctrl+[` or any other key. It supports count prefix, so `3` + mapped key will pass 3 single keys (or composed keys) to a page.

**Comment by gdh1995** [comment]
Or you may add an exclusion rule of the url and passKeys=`[` to make Vimium always ignore `Ctrl+[`.

**Comment by wenfangdu** [comment]
@gdh1995 Thanks for the fast reply, I tried this config to make Vimium always ignore <kbd>Ctrl</kbd>+<kbd>[</kbd> and <kbd>Ctrl</kbd>+<kbd>]</kbd>. but the shortcuts are still not working, am I missing something?

![image](https://user-images.githubusercontent.com/28700378/132266089-d8b94f99-a0f1-4933-b7ef-4e9f423c9789.png)

**Comment by gdh1995** [comment]
Oh it's my fault. I forgot that Vimium doesn't support composed keys in "excluded pass keys" - it only supports single characters.

You may try my customized version, named [Vimium C](https://github.com/gdh1995/vimium-c), and it supports `<c-[> <c-]>` as pass keys.

**Comment by wenfangdu** [comment]
@gdh1995 Thanks, before disabling, what do <kbd>Ctrl</kbd>+<kbd>[</kbd> and <kbd>Ctrl</kbd>+<kbd>]</kbd> do in Vimium?

**Comment by wenfangdu** [comment]
@gdh1995 Here're some of the mappings that I tried in Vimium, at last, I brought <kbd>Ctrl</kbd>+<kbd>[</kbd> and <kbd>Ctrl</kbd>+<kbd>]</kbd> back, although I'm not sure why:

```
👇 works
mapkey <c-[> <null>
👇 don't work
unmap <c-[>
mapkey <c-[> null
mapkey <c-[> <>
```

**Comment by gdh1995** [comment]
`null` and `<>` are not valid composed-key names. `<null>` is.

**Comment by wenfangdu** [comment]
I did some research and found some related info.

From [CHANGELOG](https://github.com/philc/vimium/blob/master/CHANGELOG.md):

> 1.13 (2010-01-21)
>
> `<c-[>` is now equivalent to `Esc`, to match the behavior of VIM.
>
> 1.61 (2017-10-27)
>
> You can now map `<c-[>` to a command (in which case it will not be treated as `Escape`).

From [Key Mapping](https://github.com/philc/vimium/wiki/Tips-and-Tricks#key-mapping):

> ```
> # Disable <c-[>:
> mapkey <c-[> <anyOldJunk>
> ```

From [Custom Key Mappings](https://github.com/philc/vimium#custom-key-mappings):

> The following special keys are available for mapping:
>
> - `<c-*>`, `<a-*>`, `<m-*>` for ctrl, alt, and meta (command on Mac) respectively with any key. Replace `*`
>   with the key of choice.
> - `<left>`, `<right>`, `<up>`, `<down>` for the arrow keys.
> - `<f1>` through `<f12>` for the function keys.
> - `<space>` for the space key.
> - `<tab>`, `<enter>`, `<delete>`, `<backspace>`, `<insert>`, `<home>` and `<end>` for the corresponding non-printable keys (version 1.62 onwards).

**Comment by wenfangdu** [comment]
I did some research and found some related info.

From [CHANGELOG](https://github.com/philc/vimium/blob/master/CHANGELOG.md):

> 1.13 (2010-01-21)
>
> `<c-[>` is now equivalent to `Esc`, to match the behavior of VIM.
>
> 1.61 (2017-10-27)
>
> You can now map `<c-[>` to a command (in which case it will not be treated as `Escape`).

From [Key Mapping](https://github.com/philc/vimium/wiki/Tips-and-Tricks#key-mapping):

> ```
> # Disable <c-[>:
> mapkey <c-[> <anyOldJunk>
> ```

From [Custom Key Mappings](https://github.com/philc/vimium#custom-key-mappings):

> The following special keys are available for mapping:
>
> - `<c-*>`, `<a-*>`, `<m-*>` for ctrl, alt, and meta (command on Mac) respectively with any key. Replace `*`
>   with the key of choice.
> - `<left>`, `<right>`, `<up>`, `<down>` for the arrow keys.
> - `<f1>` through `<f12>` for the function keys.
> - `<space>` for the space key.
> - `<tab>`, `<enter>`, `<delete>`, `<backspace>`, `<insert>`, `<home>` and `<end>` for the corresponding non-printable keys (version 1.62 onwards).

I guess Vimium didn't find a `<null>` key, so it behaves as a noop key.

**Comment by wenfangdu** [comment]
@gdh1995 I think `unmap <c-[>` is supposed to restore <kbd>Ctrl</kbd>+<kbd>[</kbd>, but why is it not effective?

**Comment by gdh1995** [comment]
Because `<esc>` and `<c-[>` are not "keys mapped by default" but work as built-in action triggers.
