### ISSUE TITLE
[feature request] `g1` to go to first tab, `g2` second tab, ... `g9` ninth tab

### ISSUE THREAD

**Issue by atsalolikhin-spokeo** [philc/vimium#3906]
As a Vimium user, I would like to be able to switch to the first nine tabs using `g[1-9]`.

e.g., `g1` to go the first tab, `g2` to go to the second tab, and so on, through `g9` for the ninth tab.

This would be regardless of the pinned/unpinned status of the tab.

Related:  https://github.com/philc/vimium/issues/3770

**Comment by gdh1995** [comment]
You may add this to key mappings:
```
map g1 firstTab
map g2 firstTab count=2
map g3 firstTab count=3
# and so on
```

**Comment by atsalolikhin-spokeo** [comment]
Sweet!  That works! Except the `?` help says `go to the first tab` for all of them (and also for `g0`):

![image](https://user-images.githubusercontent.com/66701226/132667276-a09e3174-9206-491b-bfeb-8c4579bcd11a.png)

I can live with that. 

BTW, I just saw this in the README:

```
g0      go to the first tab. Use ng0 to go to n-th tab
```

So `ng4` takes me to the fourth tab.

But I like the mapping better (less keystrokes).
 
Thanks!  :)

**Comment by matru** [comment]
I have a small issue with ngX, seems like it always try to jump into find mode and search for the next query, so I can't really use ng to navigate tabs?

`n       cycle forward to the next find match`
`N       cycle backward to the previous find match`
