### ISSUE TITLE
Feature to add bookmark using Vomnibar

### ISSUE THREAD

**Issue by snprajwal** [philc/vimium#3909]
`a` in normal mode will bring up Vomnibar, where the path to save the bookmark can be entered. Will a PR for this be accepted?

**Comment by janacm** [comment]
Hey @snprajwal, did this ever get added?

**Comment by roryfahy** [comment]
this is a cool idea!  did you ever find a workaround for this @janacm? something to fuzzy search folders and save to a specific one without the mouse perhaps?

**Comment by janacm** [comment]
Hey I switched over to SurfingKeys, which supports this feature. (https://chrome.google.com/webstore/detail/surfingkeys/gfbliohnnapiefjpjlpjnehglfpaknnc)
