### ISSUE TITLE
Javascript bookmarks not working anymore

### ISSUE THREAD

**Issue by gmclelland** [philc/vimium#3911]
**Describe the bug**
I noticed my javascript bookmarklets do not work anymore when invoked with the Vomnibar bar.

**To Reproduce**
1. Press b to invoke the vomnibar
2. Type the name of the bookmarklet that is stored in your Chrome bookmarks
3. Press Enter to invoke the bookmarklet
4. Vomnibar disappears and nothing happens

**Browser and Vimium version**
Google Chrome | 93.0.4577.63 (Official Build) (x86_64)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 10.13.6 (Build 17G14042)

Vimium version 1.67

Thanks for making such a useful extension, it really helps to speed up my online workflows.

**Comment by gdh1995** [comment]
Just now I tested `javascript:alert(1)` and Vomnibar successuflly made it run and show a dialog. Then please verify whether your JavaScript code in the bookmarklet still works or not.

I tested on Chrome 92 and 93.0.4577.82  on Win 10 x64.

**Comment by gmclelland** [comment]
Strange, I tried javascript:alert(1) and it worked as well.  I guess it must be something wrong with my bookmarklets then?

Thanks for checking on this.  I close this for now and do some more testing.
