### ISSUE TITLE
Is there a way to disable YouTube's native `i` function after entering insert mode through Vimium?

### ISSUE THREAD

**Issue by wenfangdu** [philc/vimium#3914]
I often mistype <kbd>i</kbd> to enter mini player on YouTube after entering insert mode, it happens quite frequently since I enabled "Hide the Heads Up Display (HUD) in insert mode".

Is there a way to disable YouTube's native <kbd>i</kbd> function after entering insert mode through Vimium?

**Comment by gdh1995** [comment]
You may map `i` to a command of Vimium, like `map i mainFrame`, and then Vimium will hook `i`.

**Comment by wenfangdu** [comment]
@gdh1995 Thanks for the reply! Sorry for not explaining this clearly at first.

I want to block <kbd>i</kbd> from being sent to the page after entering insert mode, currently, as I tried, using `map i mainFrame` will block entering insert mode as well, which is unwanted.

So, is there a way to disable YouTube's native <kbd>i</kbd> function _after entering insert mode_ through Vimium?

**Comment by gdh1995** [comment]
> using `map i mainFrame` will block entering insert mode as well, which is unwanted.

You may map another key to `enterInsertMode`.

> disable YouTube's native i function _after entering insert mode_

No. `enterInsertMode` means to block nothing (except `Escape` and `Ctrl+[`).

**Comment by wenfangdu** [comment]
My current workaround when encountering such a situation is to press <kbd>i</kbd> again to switch back to the normal player.

**Comment by wenfangdu** [comment]
A better way is to just exclude certain Vimium keys on the site, see https://github.com/philc/vimium/wiki/Disabling-Vimium.
