### ISSUE TITLE
Hint mode not working on Github

### ISSUE THREAD

**Issue by drewauff** [philc/vimium#3920]
Hints are black on black in Github, is this fixable by me? or is this an actual bug.EDIT: seems I had it set to #000000 on #000000 yet I was get a yellowish color. hmmm

Also in the vimium settings in the custom css section, is that saved locally? if so where? I am on MacOS and Id very much prefer to edit it elsewhere. I know I can cut and paste but Ive had no luck with that a while ago and daren't do it again.

**Comment by gdh1995** [comment]
You just need to write CSS in any way you like and then paste it into `Custom CSS`. It's saved into a database file in your browser's user-data folder, so you can not edit Vimium's "configuration file" directly.

**Comment by drewauff** [comment]
oh ok, would have been a great option to have.

Thank You.
