### ISSUE TITLE
Can't switch to caret mode after updating 

### ISSUE THREAD

**Issue by MahanFathi** [philc/vimium#3926]
I'm using Chrome, Vimium version 1.67, and I can't seem to switch to caret mode using any keybinding. No luck with `c` or `v` followed by `c`. Is it just me or other people also experiencing the same thing?

**Comment by ChrispyChris** [comment]
I've tried digging around the code to figure out what the deal is because I'd like to be able to enter caret mode from visual mode, but I'm having no luck. Is anyone currently looking at this?

**Comment by gdh1995** [comment]
Both #3867 and #3877 can solve this. But they requires more time to merge.

**Comment by RudRho** [comment]
Ok, i wiill wait for this merge casue it's quite imporatnt for my workflwo

**Comment by BachoSeven** [comment]
Should be closed since #3877 was merged.
