### ISSUE TITLE
Manipulate text using visual mode in search bar

### ISSUE THREAD

**Issue by MaxisJaisi** [philc/vimium#3931]
On YouTube I navigate to the first available search bar using the command gi. Now I would like to manipulate text in the search bar (besides inserting text) like deleting blocks of text, or selecting all text, or yanking parts of the text I've typed. How can I do this efficiently?

**Comment by gdh1995** [comment]
You may try https://chrome.google.com/webstore/detail/wasavi/dgogifpkoilgiofhhhodbodcfgomelhe , which is recommended in #1961

**Comment by gdh1995** [comment]
Or you may try my customized version of Vimium, named Vimium C (https://github.com/gdh1995/vimium-c), which supports `VisualMode` in input boxes and provides some methods to trigger commands in input boxes (https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box#insert-mode).

**Comment by MaxisJaisi** [comment]
Thank you @gdh1995
