### ISSUE TITLE
Excluded keys should be comma- or space-delimited to prevent common keys from being excluded

### ISSUE THREAD

**Issue by setek** [philc/vimium#3934]
**Describe the bug**
If you want to exclude `gf` but not `f`, you can't, because of a lack of delimiters.

**To Reproduce**
1. Set up an exclude site
2. Add specific keys for exclusion, something with commonalities, such as `gf`
3. See that `f` is being excluded

<img width="501" alt="image" src="https://user-images.githubusercontent.com/5126295/136638992-f230d8a4-db0d-4f1b-8c1a-0ade4e9d5339.png">

**Browser and Vimium version**

- Firefox: 92.0.1
- Vimium: 1.67
- OS: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64

**Comment by gdh1995** [comment]
Vimium must decide whether to exclude a key once it's pressed, so `gf` is not a logically valid pass key. But `g` is, and you may use just a single character of `g` to disable all mapped keys starting with `g`.
