### ISSUE TITLE
Mapping 'reload page' command always maps ' r ' + your map key.

### ISSUE THREAD

**Issue by AlexString** [philc/vimium#3953]
Tried to map 'reload page' to 'rr' instead of 'r'. So when I do the unmaping 'r' and mapping 'rr' configuration, it appears that 'r' is forced to be mapped on the reload command even if 'r' is mapped on other command.

**To Reproduce**
```
unmap r 
* hit save button *
map rr reload
* hit save button *
* now show the vimium help with ?
```
As I said, it forces 'r' to be on reload command even if 'r' is mapped on another:
```
unmap r
*save
map r Vomnibar.activateBookmarksInNewTab
*save
map rr reload
* save
* show vimium help
```

**Browser and Vimium version**
Vivaldi: 4.3
Vimium: 1.67

**Comment by gdh1995** [comment]
![image](https://user-images.githubusercontent.com/5547703/141748952-5af54029-e33d-4de2-b590-4607c291717a.png)

This should work, unless the "save options" button fails.

**Comment by AlexString** [comment]
It worked, thanks.
