### ISSUE TITLE
Why doesn't Vimium provide single letters & jumps directly to double letters?

### ISSUE THREAD

**Issue by XtremePwnership** [philc/vimium#3955]
**Describe the bug**
On many websites (eg Reddit) I've noticed Vimium will jump directly to showing double letters even though single letters are free. Why is this? Shouldn't A through Z be used first & only after they've been used up should double letters start?

**Browser and Vimium version**
Chrome Version 95.0.4638.69 (Official Build) (64-bit)
Vimium 1.67

**Comment by gdh1995** [comment]
You may change this option:

![image](https://user-images.githubusercontent.com/5547703/141748186-7f413674-d190-4e5c-ad66-fc8d77c27d36.png)

**Comment by XtremePwnership** [comment]
Thanks man!
