### ISSUE TITLE
Custom CSS Set In Vimium Options Not Rendering On Webpages

### ISSUE THREAD

**Issue by creednaylor** [philc/vimium#3956]
**Describe the bug**
Include a clear bug description.

I set the CSS in the "CSS for Vimium UI" box. However, some pages seem to recognize the change of color from yellow to blue, while others do not.

**To Reproduce**
1. Go to URL '...'

Include a screenshot if applicable.

![image](https://user-images.githubusercontent.com/16467643/141854654-2227c209-b14e-4657-8f61-31ffe2e86b4c.png)

![image](https://user-images.githubusercontent.com/16467643/141854680-7fb53f25-5db8-490a-ae79-41ff20d146d6.png)

![image](https://user-images.githubusercontent.com/16467643/141854691-eee159c7-1f17-47a4-bd89-8c5c8e461a33.png)

**Browser and Vimium version**

If you're using Chrome, include the Chrome and OSS version found at chrome://version. Also include the Vimium version found at chrome://extensions.

If you're using Firefox, report the Firefox and OS version found at about:support. Also include the Vimium version found at about:addons.

Google Chrome - Version 95.0.4638.69 (Official Build) (x86_64)
I'm on Vimium 1.67

**Comment by gdh1995** [comment]
Will be fixed by #3883 .

**Comment by philc** [comment]
Closing this in favor of #3452, which I think is the same issue.
