### ISSUE TITLE
Where is caret mode?

### ISSUE THREAD

**Issue by nathgit** [philc/vimium#3957]
Where is caret mode? When I type 'c', nothing happens in visual or normal mode. What is the code to create the mapping (enterVisualMode)? Also, what is the difference between visual & visual line mode?

**Comment by nathgit** [comment]
NVM https://github.com/philc/vimium/issues/1642#issuecomment-99721223

**Comment by gdh1995** [comment]
It's a known bug and will be fixed by #3877 .

**Comment by aichi-t** [comment]
Any chance for #3877 to get merged soon @gdh1995? Would be great to have this feature working again
