### ISSUE TITLE
[Request] selected content searched in a new tab

### ISSUE THREAD

**Issue by zitup** [philc/vimium#3959]
Is this possible? I can help if needed.

**Comment by gdh1995** [comment]
You may use `v` to enter `VisualMode`, and then press `P` to open selected text in a new tab, or `p` to open it in a current tab.

BTW, you may try my customized version of Vimium - Vimium C (https://github.com/gdh1995/vimium-c), and it supports a new command named `autoOpen`, to auto open selected text (or copied text), in a new tab by default, with an optional `keyword` parameter to use `Custom search engines`.

**Comment by zitup** [comment]
ok, thanks
