### ISSUE TITLE
jump to tab like open link (f)

### ISSUE THREAD

**Issue by KiaraGrouwstra** [philc/vimium#3963]
hi,
like many others, i tend to have a bunch of tabs open.
i would like to be able to use the keyboard to navigate to a tab.

now, Chrome offers shortcuts alt-1 to alt-9 to navigate to tabs 1-8 and the last one, respectively.
these improve over the functionality to jump to previous or next tabs, as not every tab you cross by needs to get retrieved to ram (?) making it faster.
unfortunately, this doesn't help for tabs >#8.

Vimium, fortunately, offers `#g0` as an alternative: press a number, then `g0`, and you'll jump to that tab, even if it's >#8.
the issue i have here is, i tend to not keep count.
if i have a lot of tabs open, i don't wanna try and keep count whether the one i'd like to navigate to is #15 or #25.

now, to select links, Vimium offers `f` and `F`, which mark links with letters, so one can type a code corresponding to the desired link.
i imagine a similar mechanism might facilitate jumping to a specific tab without having to keep count.

might this be a feature of interest for Vimium?

**Comment by gdh1995** [comment]
By default `T` (shift+T) is bound to `Vomnibar.activateTabSelection` and then you may search in tab titles and URLs.

**Comment by KiaraGrouwstra** [comment]
thank you! that'll do. :see_no_evil:
