### ISSUE TITLE
Can't override `scrollToTop`

### ISSUE THREAD

**Issue by azzamsa** [philc/vimium#3978]
**Describe the bug**
I am able to override other keys but not `scrollToTop`.

I have tried:

``` js
# 1
mapkey U scrollToTop --> does not work

# 2
mapkey U gg --> does not work

# 3
unmap gg
mapkey U scrollToTop --> does not work
```

**To Reproduce**

1. Add the config below 
2. Try pressing `U` to see it it works

```js
# colemak version

# d         Scroll a half page down
mapkey e d

# gg        Scroll to the top of the page
mapkey U scrollToTop
```

Include a screenshot if applicable.

**Browser and Vimium version**

```
Name 	Firefox
Version 	95.0.2
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
OS 	Linux 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08)
```

```
Author Stephen Blott
Version 1.67
Last Updated September 8, 2021
```

Thank you for vimium

**Comment by gdh1995** [comment]
For command names, please use not `mapKey` but `map`: https://github.com/philc/vimium#custom-key-mappings

**Comment by azzamsa** [comment]
Thanks. `map U scrollToTop` now works. 


I wonder why this does not work

```
mapkey U gg --> does not work
```

**Comment by gdh1995** [comment]
`mapKey` is used to rename a single key to another single key.

You should write `map U scrollToTop`
