### ISSUE TITLE
follow new tab opens 2 tabs

### ISSUE THREAD

**Issue by zlice** [philc/vimium#3979]
### Bug
Pressing `F` to follow a link in a new tab/window opens 2 new tabs in Firefox nightly.

### Steps
1. Go to page
2. Press `F`
3. Enter link to follow

### Sys info

- Firefox nightly
- Void Linux

### Comments

This started happening a bit back after I rebuilt my profile and updated Vimium.

`browser.link.open_newwindow` is `3` (default value) and "Open links in tabs instead of new windows" is checked in settings/preferences. There is an open bug about URIs misbehaving with different `open_newwindow` values in Nightly.

**Comment by sarangjo** [comment]
I'm experiencing the same issue on Firefox Nightly on Windows 11. @zlice can you share a link to the open bug in Nightly?

**Comment by gdh1995** [comment]
Duplicate of #3964. This is not a bug of Firefox, but a bug of Vimium.

Old versions of Firefox don't allow Vimium to "open links in a new tab", so Vimium adds some tricks to bypass the limit. But it seems Firefox 96 removes this limit ...

**Comment by saevarb** [comment]
I'm having this issue as well and have been having it for a few days. FF DE 96.0b8

**Comment by nath1as** [comment]
Same on FF nightly 97 / arch linux

**Comment by zlice** [comment]
Closing as this is a dupe of #3964 as gdh pointed out
