### ISSUE TITLE
Feature Request: keyboard sequence bindable action to copy a word or line from the page

### ISSUE THREAD

**Issue by akharrou** [philc/vimium#3983]
Sometimes you want to quickly copy a word or line off the current page screen. to do this we can ofc grab the mouse, select and copy the selection, OR with vimium you can perform a search via `/` key action, then press `Enter` then press `v` to enter visual mode and finally press `y` to yank (copy) the selection. The latter alternative, although already an improvement, is rather tiring: 
1. you get moved from the current location as you type in the search box
2. then you have to find the specific occurrence on the page that you were at
3. the `Enter-> v -> y` key sequene is tiresome

Would it be possible to add a functionality that can do exactly what the `LinkHints.activateMode action=copy-text` does, except that instead of having hint results limited to URLs, you would have any text word, line, and for the greatest flexibility and customizability also any user specified regex. you might have the word, line and regex be separate bindable actions.

Inspiration is from [`kitty` terminal emulator hints](https://sw.kovidgoyal.net/kitty/kittens/hints/?highlight=hint) which can do this (and more) in the terminal:

- copy word: `kitty +kitten hints --type=word`
- copy line: `kitty +kitten hints --type=line`
- copy any predefined regular expression: `kitty +kitten hints --type=regex --regex="<REGEXP>"`

Example config of resulting functionality:

```
# vimium config

## find all words in current screen page and 
## provide hint that if triggered copies the
## entire word to clipboard
map cw LinkHints.activateMode type=word action=copy-text

## find all lines in current screen page and 
## provide hint that if triggered copies the
## entire line to clipboard
map cl LinkHints.activateMode type=line action=copy-text

## find all IP-address-port in current screen
## page and provide hint that if triggered 
## copies the IP-address-port to clipboard
map ci LinkHints.activateMode type=regex regex="\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}(:\d+)?\b" action=copy-text
```

---

Thank you for this incredible and indispensible chrome plugin, I use it every second !

**Comment by gdh1995** [comment]
You may try my customized version of Vimium, named Vimium C (https://github.com/gdh1995/vimium-c), and it supports `LinkHints.activateSelect` to select any word and enter VisualMode.

And you may even write mappings like:
```
map ci LinkHints.activateSelect textFilter="/\\bth/i"
```

**Comment by kiuKisas** [comment]
is vimium-c has more features than vimium ? Or they are different in some way ?

**Comment by gdh1995** [comment]
@kiuKisas Vimium C has more commands and many more command options than Vimium, except 2 features of across-origin LinkHints and Vomnibar's online word completion. But Vimium C lacks documents and only has some Wiki pages describing a few advanced usages (https://github.com/gdh1995/vimium-c/wiki).

**Comment by arabshapt** [comment]
@gdh1995, is it possible to copy any word by having these hints on all words(not only links). I know that I can search with */* slash and then use visual mode to select and yank. But it would be great to be able to select text with hints... similar to Easymotion... Is there a technical limitation? so with easymotion you can go to line or word. With Vimium C I would expect to put hints on first word on each line or on each word respectively. Then selecting a hint would put cursor or selection on the word

**Comment by philc** [comment]
I can see how this would be useful. I use ace-jump in Emacs which provides similar functionality. But I haven't personally felt the need for this in the browser, and it would be complicated to implement. Since it's it's not a broad appeal feature and I wouldn't use it personally, I wouldn't have the bandwidth to maintain it.

**Comment by gdh1995** [comment]
@arabshapt As said in the last comment, the feature of `selecting a word in a line" is also too complicated for me - in fact, I'm busy with work and have less time to add features to Vimium C than several years before.
