### ISSUE TITLE
pressing F opens duplicate tabs. vimium-ff 1.67.1 . Firefox 96.0, Linux

### ISSUE THREAD

**Issue by rldmt** [philc/vimium#3998]
**Describe the bug**
When on firefox v96.0 for Ubuntu 20.04, if I press F opens two duplicate tabs instead of one. I looked up #3989 and it mentions this same thing but it the fix was for Windows OS. Vimium is latest v1.67.1

**To Reproduce**
1. While viewing a web page, press F and choose a link.
2. You'll see that two of the same tab will open in Firefox.

{
  "application": {
    "name": "Firefox",
    "osVersion": "Linux 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022",
    "version": "96.0",
    "buildID": "20220106144528",
    "distributionID": "canonical",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0",
    "safeMode": false,
    "supportURL": "https://support.mozilla.org/1/firefox/96.0/Linux/en-US/",
    "osTheme": "Yaru / Yaru",
    "numTotalWindows": 1,
    "numFissionWindows": 0,
    "numRemoteWindows": 1,
    "fissionAutoStart": false,
    "fissionDecisionStatus": "disabledByDefault",
    "remoteAutoStart": true,
    "policiesStatus": 0,
    "keyLocationServiceGoogleFound": true,
    "keySafebrowsingGoogleFound": true,
    "keyMozillaFound": false
  },
  "securitySoftware": {
    "registeredAntiVirus": "",
    "registeredAntiSpyware": "",
    "registeredFirewall": ""
  },
  "processes": {
    "remoteTypes": {
      "privilegedabout": 1,
      "extension": 1,
      "web": 6,
      "privilegedmozilla": 1,
      "prealloc": 1
    },
    "maxWebContentProcesses": 8
  },
  "environmentVariables": {
    "DISPLAY": ":0",
    "MOZ_APP_LAUNCHER": "/usr/bin/firefox",
    "MOZ_ASSUME_USER_NS": "1",
    "MOZ_CRASHREPORTER_EVENTS_DIRECTORY": "/home/erialdo/.mozilla/firefox/90bso150.HardenedFF/crashes/events",
    "MOZ_CRASHREPORTER_RESTART_ARG_0": "/usr/bin/firefox",
    "MOZ_CRASHREPORTER_RESTART_ARG_1": "-new-window",
    "MOZ_CRASHREPORTER_RESTART_ARG_2": "",
    "MOZ_CRASHREPORTER_DATA_DIRECTORY": "/home/erialdo/.mozilla/firefox/Crash Reports",
    "MOZ_CRASHREPORTER_PING_DIRECTORY": "/home/erialdo/.mozilla/firefox/Pending Pings",
    "MOZ_CRASHREPORTER_STRINGS_OVERRIDE": "/usr/lib/firefox/browser/crashreporter-override.ini",
    "MOZ_LAUNCHED_CHILD": "",
    "MOZ_APP_SILENT_START": "",
    "XRE_PROFILE_PATH": "",
    "XRE_PROFILE_LOCAL_PATH": "",
    "XRE_START_OFFLINE": "",
    "XRE_BINARY_PATH": "",
    "XRE_RESTARTED_BY_PROFILE_MANAGER": ""
  },
  "modifiedPreferences": {
    "accessibility.typeaheadfind.flashBar": 0,
    "browser.cache.disk.enable": false,
    "browser.contentblocking.category": "custom",
    "browser.search.region": "AL",
    "browser.search.suggest.enabled": false,
    "browser.sessionstore.interval": 30000,
    "browser.sessionstore.privacy_level": 2,
    "browser.sessionstore.upgradeBackup.latestBuildID": "20220106144528",
    "browser.startup.homepage": "about:blank",
    "browser.startup.homepage_override.buildID": "20220106144528",
    "browser.startup.homepage_override.mstone": "96.0",
    "browser.tabs.crashReporting.sendReport": false,
    "browser.urlbar.placeholderName": "DuckDuckGo",
    "browser.urlbar.placeholderName.private": "DuckDuckGo",
    "browser.urlbar.quicksuggest.migrationVersion": 2,
    "browser.urlbar.quicksuggest.scenario": "history",
    "browser.urlbar.resultGroups": "{\"children\":[{\"maxResultCount\":1,\"children\":[{\"group\":\"heuristicTest\"},{\"group\":\"heuristicExtension\"},{\"group\":\"heuristicSearchTip\"},{\"group\":\"heuristicOmnibox\"},{\"group\":\"heuristicEngineAlias\"},{\"group\":\"heuristicBookmarkKeyword\"},{\"group\":\"heuristicAutofill\"},{\"group\":\"heuristicPreloaded\"},{\"group\":\"heuristicTokenAliasEngine\"},{\"group\":\"heuristicFallback\"}]},{\"group\":\"extension\",\"availableSpan\":5},{\"flexChildren\":true,\"children\":[{\"group\":\"generalParent\",\"children\":[{\"availableSpan\":3,\"group\":\"inputHistory\"},{\"flexChildren\":true,\"children\":[{\"flex\":1,\"group\":\"remoteTab\"},{\"flex\":2,\"group\":\"general\"},{\"flex\":2,\"group\":\"aboutPages\"},{\"flex\":1,\"group\":\"preloaded\"}]},{\"group\":\"inputHistory\"}],\"flex\":2},{\"children\":[{\"flexChildren\":true,\"children\":[{\"flex\":2,\"group\":\"formHistory\"},{\"flex\":4,\"group\":\"remoteSuggestion\"}]},{\"group\":\"tailSuggestion\"}],\"flex\":1}]}]}",
    "browser.urlbar.showSearchSuggestionsFirst": false,
    "browser.urlbar.suggest.openpage": false,
    "browser.urlbar.suggest.searches": false,
    "browser.urlbar.suggest.topsites": false,
    "browser.urlbar.tipShownCount.searchTip_onboard": 4,
    "browser.urlbar.trimURLs": false,
    "doh-rollout.balrog-migration-done": true,
    "doh-rollout.disable-heuristics": true,
    "doh-rollout.doneFirstRun": true,
    "doh-rollout.home-region": "AL",
    "extensions.formautofill.addresses.enabled": false,
    "extensions.formautofill.available": "off",
    "extensions.formautofill.creditCards.available": false,
    "extensions.formautofill.creditCards.enabled": false,
    "extensions.formautofill.heuristics.enabled": false,
    "extensions.lastAppVersion": "96.0",
    "general.useragent.override": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0",
    "idle.lastDailyNotification": 1643186276,
    "media.gmp-manager.lastCheck": 1643201909,
    "media.autoplay.default": 5,
    "media.gmp-gmpopenh264.abi": "x86_64-gcc3",
    "media.gmp-gmpopenh264.lastUpdate": 1633087085,
    "media.gmp-gmpopenh264.version": "1.8.1.1",
    "media.gmp-manager.buildID": "20220106144528",
    "media.gmp.storage.version.observed": 1,
    "media.peerconnection.enabled": false,
    "media.peerconnection.ice.default_address_only": true,
    "media.peerconnection.ice.no_host": true,
    "media.peerconnection.ice.proxy_only_if_behind_proxy": true,
    "media.videocontrols.picture-in-picture.video-toggle.has-used": true,
    "network.captive-portal-service.enabled": false,
    "network.connectivity-service.enabled": false,
    "network.cookie.cookieBehavior": 1,
    "network.dns.disableIPv6": true,
    "network.dns.disablePrefetch": true,
    "network.http.referer.XOriginPolicy": 2,
    "network.http.referer.XOriginTrimmingPolicy": 2,
    "network.http.speculative-parallel-limit": 0,
    "network.predictor.enabled": false,
    "network.prefetch-next": false,
    "network.trr.blocklist_cleanup_done": true,
    "network.trr.mode": 5,
    "network.trr.uri": "https://mozilla.cloudflare-dns.com/dns-query",
    "places.database.lastMaintenance": 1642760632,
    "privacy.sanitize.pending": "[{\"id\":\"shutdown\",\"itemsToClear\":[\"offlineApps\",\"siteSettings\"],\"options\":{}},{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]",
    "privacy.clearOnShutdown.cache": false,
    "privacy.clearOnShutdown.cookies": false,
    "privacy.clearOnShutdown.downloads": false,
    "privacy.clearOnShutdown.formdata": false,
    "privacy.clearOnShutdown.history": false,
    "privacy.clearOnShutdown.offlineApps": true,
    "privacy.clearOnShutdown.sessions": false,
    "privacy.clearOnShutdown.siteSettings": true,
    "privacy.donottrackheader.enabled": true,
    "privacy.history.custom": true,
    "privacy.purge_trackers.date_in_cookie_database": "0",
    "privacy.sanitize.sanitizeOnShutdown": true,
    "privacy.trackingprotection.enabled": true,
    "privacy.trackingprotection.socialtracking.enabled": true,
    "security.remote_settings.crlite_filters.checked": 1643187838,
    "security.remote_settings.intermediates.checked": 1643166128,
    "security.sandbox.content.tempDirSuffix": "de0d2d48-ed44-4318-820a-bb7fb589c9df",
    "services.sync.declinedEngines": "",
    "signon.autofillForms": false,
    "signon.generation.enabled": false,
    "signon.rememberSignons": false,
    "storage.vacuum.last.index": 1,
    "storage.vacuum.last.places.sqlite": 1642138732,
    "webgl.disabled": true
  },
  "lockedPreferences": {
    "fission.autostart.session": false
  },
  "printingPreferences": {},
  "media": {
    "currentAudioBackend": "pulse-rust",
    "currentMaxAudioChannels": 2,
    "currentPreferredSampleRate": 48000,
    "audioOutputDevices": [
      {
        "name": "Built-in Audio Analog Stereo",
        "groupId": "/devices/pci0000:00/0000:00:1b.0/sound/card0",
        "vendor": "Intel Corporation",
        "type": 2,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 16,
        "maxChannels": 2,
        "defaultRate": 48000,
        "maxRate": 384000,
        "minRate": 1,
        "maxLatency": 0,
        "minLatency": 0
      }
    ],
    "audioInputDevices": [
      {
        "name": "Monitor of Built-in Audio Analog Stereo",
        "groupId": "/devices/pci0000:00/0000:00:1b.0/sound/card0",
        "vendor": "Intel Corporation",
        "type": 1,
        "state": 2,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 16,
        "maxChannels": 2,
        "defaultRate": 48000,
        "maxRate": 384000,
        "minRate": 1,
        "maxLatency": 0,
        "minLatency": 0
      },
      {
        "name": "Built-in Audio Analog Stereo",
        "groupId": "/devices/pci0000:00/0000:00:1b.0/sound/card0",
        "vendor": "Intel Corporation",
        "type": 1,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 16,
        "maxChannels": 2,
        "defaultRate": 44100,
        "maxRate": 384000,
        "minRate": 1,
        "maxLatency": 0,
        "minLatency": 0
      }
    ]
  },
  "accessibility": {
    "isActive": true,
    "forceDisabled": 0,
    "handlerUsed": false,
    "instantiator": ""
  },
  "startupCache": {
    "DiskCachePath": "/home/erialdo/.cache/mozilla/firefox/90bso150.HardenedFF/startupCache/startupCache.8.little",
    "IgnoreDiskCache": false,
    "FoundDiskCacheOnInit": true,
    "WroteToDiskCache": false
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.33",
      "version": "4.33"
    },
    "NSS": {
      "minVersion": "3.73.1",
      "version": "3.73.1"
    },
    "NSSUTIL": {
      "minVersion": "3.73.1",
      "version": "3.73.1"
    },
    "NSSSSL": {
      "minVersion": "3.73.1",
      "version": "3.73.1"
    },
    "NSSSMIME": {
      "minVersion": "3.73.1",
      "version": "3.73.1"
    }
  },
  "userJS": {
    "exists": false
  },
  "intl": {
    "localeService": {
      "requested": [
        "en-US"
      ],
      "available": [
        "en-US"
      ],
      "supported": [
        "en-US"
      ],
      "regionalPrefs": [
        "en-US"
      ],
      "defaultLocale": "en-US"
    },
    "osPrefs": {
      "systemLocales": [
        "en-US"
      ],
      "regionalPrefsLocales": [
        "sq-AL"
      ]
    }
  },
  "crashes": {
    "submitted": [],
    "pending": 0
  },
  "sandbox": {
    "hasSeccompBPF": true,
    "hasSeccompTSync": true,
    "hasPrivilegedUserNamespaces": true,
    "hasUserNamespaces": true,
    "canSandboxContent": true,
    "canSandboxMedia": true,
    "syscallLog": [],
    "contentSandboxLevel": 4,
    "effectiveContentSandboxLevel": 4,
    "contentWin32kLockdownState": "Win32k Lockdown disabled -- Operating system not supported"
  },
  "remoteAgent": {
    "listening": false,
    "url": ""
  },
  "graphics": {
    "numTotalWindows": 2,
    "numAcceleratedWindows": 2,
    "windowLayerManagerType": "WebRender",
    "windowLayerManagerRemote": true,
    "adapterDescription": "Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)",
    "adapterVendorID": "0x8086",
    "adapterDeviceID": "0x0116",
    "adapterRAM": 0,
    "adapterDrivers": "",
    "driverVendor": "mesa/i965",
    "driverVersion": "21.0.3.0",
    "driverDate": "",
    "adapterVendorID2": "0x10de",
    "adapterDeviceID2": "0x1057",
    "isGPU2Active": false,
    "targetFrameRate": 60,
    "windowProtocol": "x11",
    "desktopEnvironment": "gnome",
    "webgl1Renderer": "WebGL is currently disabled.",
    "webgl1Version": "-",
    "webgl1DriverExtensions": "-",
    "webgl1Extensions": "-",
    "webgl1WSIInfo": "-",
    "webgl2Renderer": "WebGL is currently disabled.",
    "webgl2Version": "-",
    "webgl2DriverExtensions": "-",
    "webgl2Extensions": "-",
    "webgl2WSIInfo": "-",
    "info": {
      "AzureFallbackCanvasBackend": "skia",
      "AzureCanvasBackend": "skia",
      "AzureContentBackend": "skia",
      "ApzWheelInput": 1,
      "ApzDragInput": 1,
      "ApzKeyboardInput": 1,
      "ApzAutoscrollInput": 1,
      "ApzZoomingInput": 1,
      "CMSOutputProfile": "AAAF1GxjbXMEMAAAbW50clJHQiBYWVogB+UADAAGAAgAGQANYWNzcEFQUEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1sY21z9pUT2DvF81O0BLFHdkYXngAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOZGVzYwAAASwAAAAyY3BydAAAAWAAAACGd3RwdAAAAegAAAAUY2hhZAAAAfwAAAAsclhZWgAAAigAAAAUYlhZWgAAAjwAAAAUZ1hZWgAAAlAAAAAUclRSQwAAAmQAAAAQZ1RSQwAAAmQAAAAQYlRSQwAAAmQAAAAQY2hybQAAAnQAAAAkbWV0YQAAApgAAALWZG1uZAAABXAAAAAuZG1kZAAABaAAAAAybWx1YwAAAAAAAAABAAAADGVuVVMAAAAWAAAAHABEAEUATABMACAAVQAyADQAMQAyAE0AAG1sdWMAAAAAAAAAAQAAAAxlblVTAAAAagAAABwAVABoAGkAcwAgAHAAcgBvAGYAaQBsAGUAIABpAHMAIABmAHIAZQBlACAAbwBmACAAawBuAG8AdwBuACAAYwBvAHAAeQByAGkAZwBoAHQAIAByAGUAcwB0AHIAaQBjAHQAaQBvAG4AcwAuAABYWVogAAAAAAAA9tYAAQAAAADTLXNmMzIAAAAAAAELtwAABZb///NWAAAHKQAA/df///u2///9pQAAA9oAAMD2WFlaIAAAAAAAAHAWAAA5RAAAA6NYWVogAAAAAAAAJKcAAA9ZAAC2gFhZWiAAAAAAAABiGgAAt2MAABkJcGFyYQAAAAAAAAAAAAIzM2Nocm0AAAAAAAMAAAAAo8AAAFSAAABMwAAAmYAAACaAAAAPQGRpY3QAAAAAAAAACgAAABAAAACwAAAAFgAAAMYAAAAqAAAA8AAAABQAAAEEAAAAFgAAARoAAAAWAAABMAAAABgAAAFIAAAAFgAAAV4AAAAIAAABZgAAACIAAAGIAAAAEgAAAZoAAAASAAABrAAAAAYAAAGyAAAAFAAAAcYAAAAqAAAB8AAAABAAAAIAAAAAQAAAAkAAAAAWAAACVgAAAAwAAAJiAAAAIgAAAoQAAABSAEMATQBGAF8AcAByAG8AZAB1AGMAdABnAG4AbwBtAGUALQBzAGUAdAB0AGkAbgBnAHMALQBkAGEAZQBtAG8AbgBFAEQASQBEAF8AbQBvAGQAZQBsAEQARQBMAEwAIABVADIANAAxADIATQBFAEQASQBEAF8AcwBlAHIAaQBhAGwAVABLADgANQBLADMAMQA1ADQASgBUAEwARABBAFQAQQBfAHMAbwB1AHIAYwBlAGUAZABpAGQARQBEAEkARABfAG0AYQBuAHUAZgBhAGMAdAB1AHIAZQByAEQAZQBsAGwAIABJAG4AYwAuAEUARABJAEQAXwBtAG4AZgB0AEQARQBMAEMATQBGAF8AYgBpAG4AYQByAHkAZwBuAG8AbQBlAC0AcwBlAHQAdABpAG4AZwBzAC0AZABhAGUAbQBvAG4ARQBEAEkARABfAG0AZAA1AGEAOQAwADkANgAyAGYANwBmADMANAAxADEAOQBkADYAOABkADYAMwBmADgANgA2AGMANABhADIAOQAyADgANwBDAE0ARgBfAHYAZQByAHMAaQBvAG4AMwAuADMANgAuADEATQBBAFAAUABJAE4ARwBfAGQAZQB2AGkAYwBlAF8AaQBkAHgAcgBhAG4AZAByAC0ARABlAGwAbAAgAEkAbgBjAC4ALQBEAEUATABMACAAVQAyADQAMQAyAE0ALQBUAEsAOAA1AEsAMwAxADUANABKAFQATAAAbWx1YwAAAAAAAAABAAAADGVuVVMAAAASAAAAHABEAGUAbABsACAASQBuAGMALgAAbWx1YwAAAAAAAAABAAAADGVuVVMAAAAWAAAAHABEAEUATABMACAAVQAyADQAMQAyAE0AAA==",
      "DisplayCount": 1,
      "Display0": "1920x1200 default"
    },
    "featureLog": {
      "features": [
        {
          "name": "HW_COMPOSITING",
          "description": "Compositing",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "OPENGL_COMPOSITING",
          "description": "OpenGL Compositing",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER",
          "description": "WebRender",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER_QUALIFIED",
          "description": "WebRender qualified",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER_COMPOSITOR",
          "description": "WebRender native compositor",
          "status": "blocklisted",
          "log": [
            {
              "type": "default",
              "status": "disabled",
              "message": "Disabled by default"
            },
            {
              "type": "env",
              "status": "blocklisted",
              "message": "Blocklisted by gfxInfo"
            }
          ]
        },
        {
          "name": "WEBRENDER_PARTIAL",
          "description": "WebRender partial present",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER_SHADER_CACHE",
          "description": "WebRender shader disk cache",
          "status": "disabled",
          "log": [
            {
              "type": "default",
              "status": "disabled",
              "message": "Disabled by default"
            }
          ]
        },
        {
          "name": "WEBRENDER_OPTIMIZED_SHADERS",
          "description": "WebRender optimized shaders",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER_ANGLE",
          "description": "WebRender ANGLE",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "env",
              "status": "unavailable",
              "message": "OS not supported"
            }
          ]
        },
        {
          "name": "WEBRENDER_DCOMP_PRESENT",
          "description": "WebRender DirectComposition",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "user",
              "status": "disabled",
              "message": "User disabled via pref"
            },
            {
              "type": "env",
              "status": "unavailable",
              "message": "Requires Windows 10 or later"
            },
            {
              "type": "runtime",
              "status": "unavailable",
              "message": "Requires ANGLE"
            }
          ]
        },
        {
          "name": "WEBRENDER_SOFTWARE",
          "description": "WebRender software fallback",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBGPU",
          "description": "WebGPU",
          "status": "blocked",
          "log": [
            {
              "type": "default",
              "status": "disabled",
              "message": "Disabled by default"
            },
            {
              "type": "runtime",
              "status": "blocked",
              "message": "WebGPU can only be enabled in nightly"
            }
          ]
        },
        {
          "name": "X11_EGL",
          "description": "X11 EGL",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "DMABUF",
          "description": "DMABUF",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        }
      ],
      "fallbacks": []
    },
    "crashGuards": []
  },
  "experimentalFeatures": [
    [
      "experimental-features-abouthome-startup-cache",
      "browser.startup.homepage.abouthome_cache.enabled",
      false
    ],
    [
      "experimental-features-cookie-samesite-lax-by-default2",
      "network.cookie.sameSite.laxByDefault",
      true
    ],
    [
      "experimental-features-cookie-samesite-none-requires-secure2",
      "network.cookie.sameSite.noneRequiresSecure",
      true
    ],
    [
      "experimental-features-cookie-samesite-schemeful",
      "network.cookie.sameSite.schemeful",
      true
    ],
    [
      "experimental-features-css-cascade-layers",
      "layout.css.cascade-layers.enabled",
      false
    ],
    [
      "experimental-features-css-constructable-stylesheets",
      "layout.css.constructable-stylesheets.enabled",
      false
    ],
    [
      "experimental-features-css-masonry2",
      "layout.css.grid-template-masonry-value.enabled",
      false
    ],
    [
      "experimental-features-devtools-compatibility-panel",
      "devtools.inspector.compatibility.enabled",
      false
    ],
    [
      "experimental-features-devtools-execution-context-selector",
      "devtools.webconsole.input.context",
      false
    ],
    [
      "experimental-features-devtools-serviceworker-debugger-support",
      "devtools.debugger.features.windowless-service-workers",
      false
    ],
    [
      "experimental-features-fission",
      "fission.autostart",
      false
    ],
    [
      "experimental-features-media-jxl",
      "image.jxl.enabled",
      false
    ],
    [
      "experimental-features-multi-pip",
      "media.videocontrols.picture-in-picture.allow-multiple",
      true
    ],
    [
      "experimental-features-ime-search",
      "browser.urlbar.keepPanelOpenDuringImeComposition",
      false
    ],
    [
      "experimental-features-web-gpu2",
      "dom.webgpu.enabled",
      false
    ],
    [
      "experimental-features-webrtc-global-mute-toggles",
      "privacy.webrtc.globalMuteToggles",
      false
    ],
    [
      "experimental-features-win32k-lockdown",
      "security.sandbox.content.win32k-disable",
      false
    ]
  ],
  "addons": [
    {
      "name": "Add-ons Search Detection",
      "type": "extension",
      "version": "2.0.0",
      "isActive": true,
      "id": "addons-search-detection@mozilla.com"
    },
    {
      "name": "Amazon.com",
      "type": "extension",
      "version": "1.3",
      "isActive": true,
      "id": "amazondotcom@search.mozilla.org"
    },
    {
      "name": "Bing",
      "type": "extension",
      "version": "1.3",
      "isActive": true,
      "id": "bing@search.mozilla.org"
    },
    {
      "name": "DuckDuckGo",
      "type": "extension",
      "version": "1.1",
      "isActive": true,
      "id": "ddg@search.mozilla.org"
    },
    {
      "name": "Google",
      "type": "extension",
      "version": "1.1",
      "isActive": true,
      "id": "google@search.mozilla.org"
    },
    {
      "name": "Privacy Badger",
      "type": "extension",
      "version": "2021.11.23.1",
      "isActive": true,
      "id": "jid1-MnnxcxisBPnSXQ@jetpack"
    },
    {
      "name": "uBlock Origin",
      "type": "extension",
      "version": "1.40.8",
      "isActive": true,
      "id": "uBlock0@raymondhill.net"
    },
    {
      "name": "Vimium",
      "type": "extension",
      "version": "1.67.1",
      "isActive": true,
      "id": "{d7742d87-e61d-4b78-b8a1-b469842139fa}"
    },
    {
      "name": "Wikipedia (en)",
      "type": "extension",
      "version": "1.1",
      "isActive": true,
      "id": "wikipedia@search.mozilla.org"
    }
  ],
  "features": [
    {
      "name": "DoH Roll-Out",
      "version": "2.0.0",
      "id": "doh-rollout@mozilla.org"
    },
    {
      "name": "Firefox Screenshots",
      "version": "39.0.1",
      "id": "screenshots@mozilla.org"
    },
    {
      "name": "Form Autofill",
      "version": "1.0.1",
      "id": "formautofill@mozilla.org"
    },
    {
      "name": "Picture-In-Picture",
      "version": "1.0.0",
      "id": "pictureinpicture@mozilla.org"
    },
    {
      "name": "Proxy Failover",
      "version": "1.0.2",
      "id": "proxy-failover@mozilla.com"
    },
    {
      "name": "Web Compatibility Interventions",
      "version": "29.2.0",
      "id": "webcompat@mozilla.org"
    },
    {
      "name": "WebCompat Reporter",
      "version": "1.4.2",
      "id": "webcompat-reporter@mozilla.org"
    }
  ],
  "normandy": {
    "addonStudies": [],
    "prefRollouts": [],
    "prefStudies": [],
    "nimbusExperiments": [],
    "remoteConfigs": []
  }
}

Vimium version 1.67.1

**Comment by rldmt** [comment]
That was quick. I changed the version of mozilla in the field userAgent. I am leaving this here in case someone stumbles.

**Comment by gdh1995** [comment]
Sorry to disturb you, but why is this closed? Is the bug of duplicated tabs solved in Vimium v1.67.1 ?

**Comment by rldmt** [comment]
> Sorry to disturb you, but why is this closed? Is the bug of duplicated tabs solved in Vimium v1.67.1 ?

I am sorry for the very late reply. If I remember correctly I solved the issue by changing the user agent to a Windows machine.

**Comment by gdh1995** [comment]
Oh then it may be because you used a user agent which said Firefox version is before 96. Fixed by #3985 (it has been in v1.67.1) and #4000 .
