### ISSUE TITLE
it dont have [ignore keyboard layout]

### ISSUE THREAD

**Issue by gintering1000** [philc/vimium#4006]
- i have to use opera browser :(
- i wanna use in korean mode :(
- it dont have [ignore keyboard layout] :(
![image](https://user-images.githubusercontent.com/77244047/152695310-a10ba746-b43f-4278-bad8-eff9c6ef7be7.png)
![image](https://user-images.githubusercontent.com/77244047/152695267-0a637298-25f0-430c-a5ca-4dad60d31ac7.png)
![image](https://user-images.githubusercontent.com/77244047/152695458-7a42c04c-3a55-4595-bcc2-2f529d9d3a8f.png)
![image](https://user-images.githubusercontent.com/77244047/152695317-429a9c63-db3c-48b2-ba23-c5090a023757.png)

**Comment by gdh1995** [comment]
You need to open a tab named `Vimium Options` first, by clicking
![image](https://user-images.githubusercontent.com/5547703/152715183-990cfe7d-1700-4b8d-9012-2735164eec18.png)
