### ISSUE TITLE
How to `focusInput` to the beginning of input in a single shortcut?

### ISSUE THREAD

**Issue by solzard** [philc/vimium#4011]
I want to have a single keyboard shortcut to 1) `focusInput` and 2) go to the beginning of an input text.
Since `gi focusInput` inself goes to the end of an input text, I need to type`gi` and then `Cmd + ←` to go to the beginning.
Are there any good ways to do this feature?

**Comment by gdh1995** [comment]
Currently there's no option for `focusInput` to do this in Vimium.

You may try my customized version of Vimium - Vimium C (https://github.com/gdh1995/vimium-c) - it supports:
```
# move selection to start, if 1) an old caret is not in "the middle of text"; and 2) there's no selection range, or all text are selected
map xxx focusInput select="start"
# `select` can also be `end` (the default), `all`, `all-input` (aka `all-line`)
```
