### ISSUE TITLE
[Bug] Yanking on github repo page does not return URL in address bar

### ISSUE THREAD

**Issue by nicoandmee** [philc/vimium#4018]
**Describe the bug**
When visiting a github repo, performing `yy` to copy the URL never seems to return the actual URL in the address bar. 

**To Reproduce**
1. Go to URL `https://github.com/philc/vimium`
2. Press `yy`
3. Observe output is of the form: `https://github.com/philc/vimium/tree/682ebb5cb773999e79106e7b896fd3320ac02502`

I'm curious why this is.
**Browser and Vimium version**
Brave [Version 1.37.77 Chromium: 99.0.4844.45 (Official Build) beta (64-bit)](https://brave.com/latest/)

Vimium v1.67

**Comment by gdh1995** [comment]
I can not reproduce this on a fresh profile of Chrome 98 x64 on Win10. Please try disabling all other extensions on your Chrome, reload the GitHub tab and then retry `yy`.

**Comment by nicoandmee** [comment]
Can confirm this was a conflict with another Github-related extension. Worked fine with everything disabled. Not a big deal for me to copy the URL by `ge` + `Ctrl+C`. 

thanks!

**Comment by gdh1995** [comment]
Could you share the name of the other Github-related extension. I'm curious how to make my customized version of Vimium (https://github.com/gdh1995/vimium-c) work with it.
