### ISSUE TITLE
Open a link with uppercase caused two same tabs opened

### ISSUE THREAD

**Issue by Ynjxsjmh** [philc/vimium#4021]
**Describe the bug**

1. Press `f` to generate hints for all links visible

![image](https://user-images.githubusercontent.com/40143136/156961546-400f182e-8ab2-44a0-964d-ebe3fe8418eb.png)

2. Press uppercase letter like `L` in above picture to open link in new tab. However, it opens the same tab twice

![image](https://user-images.githubusercontent.com/40143136/156961693-364d6c5b-59b6-4b43-83b8-d23a51a40996.png)

**Browser and Vimium version**

- Firefox version: 91.6.0esr (64-bit)
- Vimium version: 1.67.1
- OS: Arch Linux x86_64
- Kernel: 5.16.11-arch1-1

**Comment by gdh1995** [comment]
Confirmed. This has been reported in some comments and will be fixed by #4000.
