### ISSUE TITLE
Firefox warning: InstallTrigger is deprecated and will be removed in the future.

### ISSUE THREAD

**Issue by kashav** [philc/vimium#4033]
**Describe the bug**
I see this warning in Firefox console on content pages.

```
InstallTrigger is deprecated and will be removed in the future. utils.js:30:22
```

**To Reproduce**
1. Download a recent-ish Firefox Nightly, I'm using 20220322065927.
1. Install Vimium, perhaps in a fresh profile.
1. Go to https://example.com or any other website.
1. Open the console.

**Browser and Vimium version**

Browser: Firefox Nightly 100.0a1 20220322065927
Vimium: 1.67.1

**Comment by kashav** [comment]
Looks like it was deprecated in https://bugzilla.mozilla.org/show_bug.cgi?id=1754441.

Here's the line in Vimium: https://github.com/philc/vimium/blob/master/lib/utils.js#L29-L31.

**Comment by davidrunger** [comment]
Here's a permalink to the line in Vimium: https://github.com/philc/vimium/blob/97729f72533276d0d2aeb9f6b039e51cb96b785d/lib/utils.js#L23

**Comment by gdh1995** [comment]
Just a note: On Firefox 106.0b4, `extensions.InstallTrigger.enabled` on `about:blank` is `false`, while 106.0b9 makes it `true` again (https://github.com/philc/vimium/issues/3774#issuecomment-1272740734).
