### ISSUE TITLE
feature: I would like shift+up/down for history forward/back and shift+left/right for changing tab left/right.. but shift has no modifier, or?

### ISSUE THREAD

**Issue by Jirido** [philc/vimium#4036]
I come from many years on pentadactyl/FF (lately PaleMoon) and guake/(tabbed+alacritty) and have used shift+left/right to change tabs. (ctrl+left/right moves them)
I also use shift+up/down for history. These sit so well in my right hand and I would like to continue to use them while shifting to Vimium.. Is this possible? 
If not, could you add a shift modifier <s-*>  so I could use \<s-up> etc..?

Else I would like to thank you for your good work.

**Comment by jarredhawkins** [comment]
Just went searching for this too -- looks like it's already implemented (`<s-*>`), just not documented yet.

See documentation PR here: https://github.com/philc/vimium/pull/3976

**Comment by Jirido** [comment]
Wow, good. Then I close this issue. Thanks!
