### ISSUE TITLE
Question: is omnibar limited to 10 items only?

### ISSUE THREAD

**Issue by laoshaw** [philc/vimium#4042]
Using newest chrome with newest vimium on Linux (ubuntu 20.04), each time I use o or b, I only see 10 items in the list, is there a limit for bookmark/history/etc search? can it list everything it can find

**Comment by gdh1995** [comment]
Yes only 10. You may add query words to get more near suggestions.

**Comment by laoshaw** [comment]
would be nice if it searches all bookmarks/tabs, or let me customize how many items to search, 10 is a fairly small numbers. chrome be default will show 150 history matches.

or is there a way to tie two keys in vimium to open search bookmarks(chrome://bookmarks/?#q=%) and search histories(chrome://history/undefined??q=%s), they're not pop-up omnibars, but might still be better than only 10 items.

**Comment by gdh1995** [comment]
You may add this to `Custom key mappings` on Vimium Options:
```
map x createTab chrome://history
```

If you do want to see more suggestions, you may try my `Vimium C` (https://github.com/gdh1995/vimium-c), and its Vomnibar support `PageDown`/`PageUp` (aka `Shift+ArrowDown` / `Shift+ArrowUp`) to go to another page of 10 suggestions. It has also a special setting item to control how many suggestions in one screen, which accepts `3~25`.
![image](https://user-images.githubusercontent.com/5547703/163329251-d1090cb2-0e7f-4b12-8f19-3b082c65d2b8.png)
![image](https://user-images.githubusercontent.com/5547703/163329049-4a7798b6-c3cd-4919-a1b6-99ee376420cf.png)
