### ISSUE TITLE
keywords are unrecognizable in find mode

### ISSUE THREAD

**Issue by akhiljalagam** [philc/vimium#4044]
![image](https://user-images.githubusercontent.com/21128035/163370823-49f9e65d-6343-462c-99e9-931172ca6117.png)

keywords are unrecognizable in find mode

**To Reproduce**
not sure when it behaves like that

**Browser and Vimium version**

vimium: 1.67
Google Chrome: 100.0.4896.88 (Official Build) (64-bit)

**Comment by akhiljalagam** [comment]
**update:**
this issue disappeared when I paused ad blocker in the browser.

**Comment by philc** [comment]
@akhiljalagam I don't understand the bug from the screenshot, but it sounds like it's no longer an issue?

**Comment by akhiljalagam** [comment]
@philc can't see the second character. it's hiding behind.
![image](https://user-images.githubusercontent.com/21128035/169464524-4579ee03-72e2-4603-a3e3-354dfd8926bf.png)

**Comment by gdh1995** [comment]
You may press `Space` to switch orders of those hint markers.
