### ISSUE TITLE
CSS linkhint boxes not working outside settings page.

### ISSUE THREAD

**Issue by OliverAThunes** [philc/vimium#4047]
**Describe the bug**
Setting the css for the link hint boxes only shows the changes in the chrome extensions options, and not any other page I am on.
Other CSS settings work fine everywhere but only link hint boxes do not work.

**To Reproduce**
1. Go to chrome vimium options
2. Set css for vimium UI to
`div > .vimiumHintMarker {
  background: #FF7CAF;
  border: none;
}`
3. Save and refresh.
4. Press f on the vimium options page and see that it is working,
5. Press f on any other page and see that it is not working.

**Browser and Vimium version**
Chrome: 100.0.4896.127
Vimium: 1.67

**Comment by gdh1995** [comment]
How about adding `!important`?

**Comment by OliverAThunes** [comment]
No, that does not work. I came across a pull request that might fix this issue. https://github.com/philc/vimium/pull/3883

**Comment by gdh1995** [comment]
The PR is made by me. Today I've reproduced the same issue on Chrome 95 + my Win 10, but not on Chrome 98 or 100.

`div > .vimiumHintMarker { background: #FF7CAF !important; border: none; }` does work on Chrome 95, so I think there might be some other issues preventing your code from taking effects, like potential typos.

**Comment by OliverAThunes** [comment]
Alright I seem to have made a typo. `!important` works as a workaround until that PR gets merged.
