### ISSUE TITLE
no "click button" shortcut. really big lack

### ISSUE THREAD

**Issue by cosimopp** [philc/vimium#4048]
It would work like "f": rather than just showing links, It would show clickable elements too! (e.g. drop menu).
pls implement it, you have done an amazing work ;)

**Comment by gdh1995** [comment]
Could you provide a web URL which contains such drop menus?

**Comment by cosimopp** [comment]
https://corsi.unibo.it/laurea/informatica/orario-lezioni

![Screenshot_2022-04-29_13-01-22](https://user-images.githubusercontent.com/95437148/165932506-cf554875-30ed-4e6b-9aec-807a4ccba47e.png)

after you click "K" on the webpage, you are not any more able to use "f/F" feature in order to see clickable elements :(

**Comment by gdh1995** [comment]
It's limited (and required) by your browser.

Some years ago Chrome allows JS code to make a `<select>` show its popup list, but the feature was removed ignoring opposition from many developers.

So there's nothing Vimium can do. But when you use `f` and press `K`, yourself may:
* press `Space`/`Enter` to show the popup list
* press `ArrowDown` and `ArrowUp` to switch among list items
