### ISSUE TITLE
Port Vimium to work in Emacs webkit / xwidget-webkit

### ISSUE THREAD

**Issue by rwilson-lib** [philc/vimium#4049]
**Describe the bug**

I really love this extension.

Can you create a package of emac xwidget-webkit

**To Reproduce**
1. Go to URL '...'

Include a screenshot if applicable.

**Browser and Vimium version**

If you're using Chrome, include the Chrome and OSS version found at chrome://version. Also include the Vimium version found at chrome://extensions.

If you're using Firefox, report the Firefox and OS version found at about:support. Also include the Vimium version found at about:addons.

**Comment by philc** [comment]
I'm glad you're enjoying the extension! I think creating a version of Vimium for xwidget-webkit is outside the scope of this repo, but could naturally live in a fork if someone was interesting in writing it.
