### ISSUE TITLE
copy an element's text to the clipboard

### ISSUE THREAD

**Issue by brianeg** [philc/vimium#4050]
**Describe the bug**
Include a clear bug description.

Tridactyl firefox has this function:

 copy an element's text to the clipboard **;p**

I miss it in vimium

BR
Brian

**To Reproduce**
1. Go to URL '...'

Include a screenshot if applicable.

**Browser and Vimium version**
Chrome 1,67
If you're using Chrome, include the Chrome and OSS version found at chrome://version. Also include the Vimium version found at chrome://extensions.

If you're using Firefox, report the Firefox and OS version found at about:support. Also include the Vimium version found at about:addons.

**Comment by gdh1995** [comment]
You may try such a mapping: ```map f LinkHints.activateMode action="copy-text"```

**Comment by brianeg** [comment]
Dear gdh1995
You are brilliant, however, have not used map f, I use it all the time :-) but map c
I have to copy an invoice number why it is not activated via map c, see attachment.
BR Brian

![mapc](https://user-images.githubusercontent.com/25778395/167773572-78671456-8785-45e7-9975-2ef7e87514fd.jpg)

**Comment by gdh1995** [comment]
Um it's because up to now LinkHints in Vimium only shows markers for "clickable" items.

If you do want to show hint markers for all visible text parts, you may try my customized version of Vimium - Vimium C (https://github.com/gdh1995/vimium-c), and it support such mappings:
```
# `anyText` means to match all elements with visible text
# `action="copy-text"` means to copy text
map xxx LinkHints.activate anyText action="copy-text"
```

**Comment by brianeg** [comment]
Dear Dahan Gong 
Thank you very much Vimium C perfectly covers my needs.
BR
Brian
