### ISSUE TITLE
Custom search in Firefox

### ISSUE THREAD

**Issue by raffaem** [philc/vimium#4051]
Vimium: 1.67.1
Firefox: 100.0

I have some bookmarks with keywords.

For example, "https://www.merriam-webster.com/dictionary?s=%s" is associated with the "mw" keyword.

When I type "mw hello" in the search bar, it opens the related dictionary entry.

But when I press `o` and type the same thing in the VOmnibar (is this how is it called?), vimium just search "mw hello" on Google.

Are keyworded bookmarks supposed to work?

Or are custom search engines supported only on Google Chrome?

**Comment by gdh1995** [comment]
Keyworded bookmarks on Firefox are not supported yet.

You need to manually add search engines you want to use into the `Custom search engines` on Vimium Options, because browsers don't provide extensions with such a API of accessing search engineson `chrome://settings/searchEngines`.

**Comment by philc** [comment]
@gdh1995 thanks for chiming in here. I've added an [FAQ entry](https://github.com/philc/vimium/wiki/FAQ#can-vimiums-vomnibar-use-the-custom-search-engines-ive-defined-in-the-browser) for this for future users.

**Comment by ilveroluca** [comment]
looks like a duplicate of #3036
