### ISSUE TITLE
Using Alt+number shortcut to navigate between tabs breaks with resistFingerprinting

### ISSUE THREAD

**Issue by Goshenkata** [philc/vimium#4053]
### Description:
Using Alt+number shortcut to navigate between tabs breaks with privacy.resistFingerprinting turned on,
when i disable either resistFingerprinting or Vimium it works as normal but with both on nothing happens, except sometimes when it actually switches the tab correctly.

### Steps to reproduce:
1. Go to about:config and set privacy.resistFingerprinting to true
2. Press Alt + some number to navigate tabs, most of the time it won't respond.

### Browser and Vimium versions
Browser: Firefox 100.0
Vimium: 1.67.1

**Comment by gdh1995** [comment]
Um, I'm not sure but it seems not a built-in feature of Firefox. Are you using other extensions like https://addons.mozilla.org/en-US/firefox/addon/alt-number-to-switch-tabs ?

**Comment by gdh1995** [comment]
And, Firefox's `privacy.resistFingerprinting` will hide all keyboard messages when `Alt` is being pressed, which making some shortcuts impossible to trigger. I think there's no way for web-extensions to bypass the limit.

**Comment by simao** [comment]
I am having the same problem. Alt+Number switching is a built in feature of firefox https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly (see "Go to Tab 1 to 8"). But it only breaks with resistFingerprinting + vimium enabled.

With resistFingerprint and without vimium this feature still works.

**Comment by simao** [comment]
yes, that works :) Thanks a lot!

**Comment by Goshenkata** [comment]
Thanks a lot from me too!
