### ISSUE TITLE
Feature request: open pages from the O bar in new tab

### ISSUE THREAD

**Issue by tinoargentino** [philc/vimium#4057]
Use case:
When trying to open a page using the 'o' bar, pages are loaded in the current page, disrupting the workflow. I'd like to be able to open them in a new tab, either by default, or by holding down something such as command+enter

**Comment by tinoargentino** [comment]
just found out this is done with shift+enter lol

**Comment by gdh1995** [comment]
You may also press `shift+o` (Shift and the English letter O) to trigger `Vomnibar.activateInNewTab`, and the command will open URLs in new tabs by default.
