### ISSUE TITLE
Cannot toggle between Caret and Visual Mode

### ISSUE THREAD

**Issue by williamhCode** [philc/vimium#4062]
**The Bug**
I cannot switch between Caret mode and Visual mode. If I press v, and I go into visual mode, pressing c does nothing except for cancelling the selection. Vice-versa if I press v and it auto goes to Caret mode, if i press v again it doesn't go into Visual mode.

**Browser and Vimium version**
Google Chrome (macOS) -
101.0.4951.64 (Official Build) (arm64)

**Comment by mcp292** [comment]
Same issue:
Firefox 101 
Arch Linux

**Comment by Jesspu** [comment]
Same issue
Vivaldi 5.3.2679.55 (Stable channel)
Windows 10

**Comment by gdh1995** [comment]
Um, #4062 will fix this.

**Comment by BachoSeven** [comment]
Now that #3877 is merged this can be closed
