### ISSUE TITLE
How to open  a new tab in the most right side on browser.

### ISSUE THREAD

**Issue by kay-adamof** [philc/vimium#4065]
I'd like to do the following process with less key strokes:

- Open a search result in a new tab via Vomnibar.
- Move the opened tab to the most right side of browser.

Currently, I'm trying to press 3 keys as followings:

- Press "o" key ( assigned as "map o Vomnibar.activateInNewTab")
- Press ">" key
- Press ">" key
( The pressing "two less than key >>" is assigned as "map >> moveTabRight count=99")

Is there any way to do both of opening and moving a tab by just pressing "o" ?
It's something like this:

- map o Vomnibar.activateInNewTab moveTabRight count=99

Thank you for your helping.

**Comment by gdh1995** [comment]
You may try my customized version, Vimium C (https://github.com/gdh1995/vimium-c), and it supports:
```
map o Vomnibar.activateInNewTab position="end"
```

`position` can be `start / begin ; before / prev ; after / next ; end`, and its default value is `next`.
