### ISSUE TITLE
Feature request: configurable `scroll speed` would be awesome 🍰 

### ISSUE THREAD

**Issue by nevzatseferoglu** [philc/vimium#4073]
First of all, thanks for your efforts and creating this awesome tool ❤️  💯 

It would be great to have a some sort of setting that makes altering **scroll speed** available 🤔 . Especially for a scenario that involves reading a document from the webpage.

What do you think ?

@smblott-github 
@philc 
@int3 
@mrmr1993

**Comment by gdh1995** [comment]
You may configure this:
![image](https://user-images.githubusercontent.com/5547703/173187595-847eaf1c-9c81-42d3-bfea-5443b9b1b7f0.png)

**Comment by nevzatseferoglu** [comment]
Thanks @gdh1995 👍🏼
