### ISSUE TITLE
Migrate to manifest v3; v2 is deprecated in Chrome

### ISSUE THREAD

**Issue by M1cha** [philc/vimium#4075]
Chrome now shows the following warning in the extensions list:
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

**Comment by ademuri** [comment]
@philc any updates on this work? I looked at this briefly, and I think there is a decent amount of work to do - specifically around [migrating background scripts to service workers](https://developer.chrome.com/docs/extensions/migrating/to-service-workers/).

**Comment by philc** [comment]
Hey @ademuri , there has been lots of progress on the [manifest-v3](https://github.com/philc/vimium/tree/manifest-v3) branch. I'll open a PR for it soon. You're right, it has required a massive undertaking / partial rewrite.

**Comment by philc** [comment]
This has since been completed in #4274!
