### ISSUE TITLE
Links opened with Shift+F create duplicate tabs

### ISSUE THREAD

**Issue by gulkily** [philc/vimium#4077]
**Describe the bug**
Been affected by this issue since Waterfox G4.0.7 (Gecko 91.6) and up to today's version. Waterfox G4.0.6 works fine. The same issue affects Firefox as well, though I am not a regular user of it.

**To Reproduce**
1. Go to URL http://news.ycombinator.com/
2. Press Shift+F
3. Choose any of the hints presented

Expected: One tab opens

Actual: Two tabs open

Include a screenshot if applicable.

<img width="864" alt="Screen Shot 2022-06-19 at 8 57 56 PM" src="https://user-images.githubusercontent.com/1530699/174507827-93972d94-3e51-4ffb-9176-7e7803348917.png">

**Browser and Vimium version**

Waterfox G4.1.2.1 Mac (issue started with G4.0.7)

Vimium 1.67.1

If you're using Chrome, include the Chrome and OS version found at chrome://version. Also include the Vimium version found at chrome://extensions.

If you're using Firefox, report the Firefox and OS version found at about:support. Also include the Vimium version found at about:addons.

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:91.0) Gecko/20100101 Firefox/91.0 Waterfox/91.10.0

**Comment by glazari** [comment]
I have been having the same problem.

Vimium 1.67.1

Firefox version: 91.10.0esr

**Comment by l1yefeng** [comment]
See #4032

**Comment by haarts** [comment]
FYI The `resistFingerprinting` flag is off and I experience the issue still. I'm also using [Cameleon](https://addons.mozilla.org/en-US/firefox/addon/chameleon-ext/), when I disable that extension it works as expected.

**Comment by philc** [comment]
Vimium-FF is now 1.67.2 on the firefox store, so this should be resolved.

**Comment by gulkily** [comment]
Confirmed fixed here. Thank you!!!
