### ISSUE TITLE
How do I use only  a certain keys? 

### ISSUE THREAD

**Issue by tusqasi** [philc/vimium#4082]
There is excluding function functionality, I want to use only a certain vim-keys for some website.   

How can I go about doing this?

One solution:
Take all the keys from https://github.com/philc/vimium/wiki/Keymap do some scripting and put them in which site I want, but that is not easy.

**Comment by gdh1995** [comment]
This is a duplicated issue of #3272, and the idea in https://github.com/philc/vimium/issues/3272#issuecomment-475296695 may help.

**Comment by tusqasi** [comment]
Seems  https://github.com/philc/vimium/issues/3272#issuecomment-475296695 is exactly what I needed.
