### ISSUE TITLE
[Firefox] "Go one tab left" and "Go one tab right" don't work when in a pinned tab

### ISSUE THREAD

**Issue by prasant94** [philc/vimium#4096]
**Describe the bug**
"Go one tab left" and "Go one tab right" don't work when in a pinned tab in Firefox

**To Reproduce**
1. Open firefox browser
2. Open 3 tabs and pin them (right click on tab and click "Pin tab")
3. Go to the second pinned tab
4. Hit `J` or `K`

**Browser and Vimium version**

Name 	Firefox
Version 	103.0
Build ID 	20220718155818
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0
OS 	Darwin 20.6.0 Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64

Vimium version: 1.67.1

**Comment by gdh1995** [comment]
Um, sorry but I can't reproduce this on a fresh profile of Firefox 103 x64 on my Win11.

**Comment by prasant94** [comment]
Ok I think I know what was happening. My pinned tabs are all gmail inboxes and vimium gets disabled on gmail.
