### ISSUE TITLE
[Feature Request] Two way address bar focus shortcut

### ISSUE THREAD

**Issue by mries92** [philc/vimium#4106]
Hey, love the plugin. One thing consistently irks me though. If I press `CTRL+L` to navigate to the address bar, I have to manually click back in the page to get back to using Vimium.

It would be awesome if I could press `CTRL+L` again to focus back on the page, and continue using Vimium without having to touch the mouse. As a *solution*, I can `CTRL+F` and search for a space, then hit `ENTER` to refocus the page, then `ESC` to close the serach box. But this is multiple keystrokes and somewhat jenky.

I'm not sure if this is something that is possible with the extensions api, or if this is something that has been requested before, but figured I would put it out there.

Thanks a lot for the great plugin!

**Comment by gdh1995** [comment]
Currently it's impossible for web extensions to do so on Chrome, because Chrome doesn't provide any API to move focus back to page content. In my memory, there was a feature request in Chromium forum many years ago but nobody has decided to add it.

**Comment by mries92** [comment]
I thought something like that may be the case, ty for the answer!

**Comment by vimeitor** [comment]
@mries92 Why not simply press escape while the address bar is focused? That should focus the page again.

**Comment by sunsande** [comment]
>  As a solution, I can CTRL+F and search for a space, then hit ENTER to refocus the page, then ESC to close the serach box. 

After the focus is in the URL field (after `CTRL+L` or the same `ALT+D`), it is enough to press `CTRL+F` and `ESC` - the focus will go back to the page content (no need to search for a space by pressing `SPACE , ENTER` ).

This works also if you are somewhere else , for example in the search field  on the browser's toolbar.

Still multiple keystrokes , but 2 less :).

Thank you both @mries92 and @gdh1995 !
