### ISSUE TITLE
[Feature Request] Search through your open tabs

### ISSUE THREAD

**Issue by reikrom** [philc/vimium#4113]
Current behavior:
When using "Search through your open tabs" and a tab doesn't exist it defaults to a google search in current open tab

Desired behavior:
When using "Search through your open tabs" and the tab doesn't exist a new tab should open with the google search query from with the input.

**Comment by Takuto88** [comment]
For me, the extension behaves exactly as you desire already 🤔

**Comment by gdh1995** [comment]
@Takuto88 Sorry but what's the version of your said "Vimium"? Vimium 1.67.2 opens a query word in a current tab in `T` mode; while my Vimium C v1.99.3 (https://github.com/gdh1995/vimium-c) opens it in a new tab by default.

Though there's indeed a working around - when you're in Vimium's `Vomnibar.activateTabSelection`, you may use `Ctrl+Enter` to open your query words in a new tab.

**Comment by Takuto88** [comment]
@gdh1995 Sorry I must have either missed the "in a **new** tab" aspect of this report or I've pressed `Ctrl+Enter` without noticing during my test. You are right that this only searches in the current tab, which I also find kind of odd 😅 .

**Comment by reikrom** [comment]
@gdh1995 I've swapped `T` and `t` functionalities as I use tab search more than `visitPreviousTab` 
If I hold Shift when hitting enter for a non-existent tab-name in the tab search modal, THEN it'll open in a new tab, otherwise, the new search will override the current tab.

I think my re-mapping didn't extend to all the keypress listeners `t` vs `T` 
```
map t Vomnibar.activateTabSelection
map T visitPreviousTab
```
