### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Goproxer** [philc/vimium#4117]
Compatibility with the Firefox extension `Simple Tab Groups`.
https://github.com/drive4ik/simple-tab-groups
The current behavior is quite weird :(

**Comment by jjmonsalveg** [comment]
I have an issue when I try to use J or K to move to the previous/next tab. For some reason, vimium is not behaving as ctrl+tab or ctrl+shift+tab does. I mean sometimes does go right/left movements but other times just jumps to another group of tabs leaving the current group, did you find a solution to this problem?

**Comment by Goproxer** [comment]
> @Goproxer I have an issue when I try to use J or K to move to the previous/next tab. For some reason, vimium is not behaving as ctrl+tab or ctrl+shift+tab does. I mean sometimes does go right/left movements but other times just jumps to another group of tabs leaving the current group, did you find a solution to this problem?
>
Yeah, that's also the problem I'm facing. Sadly no. Probably need some internal tweaking to make them compatible.

**Comment by Goproxer** [comment]
> It's because `Simple Tab Groups` switches tab groups by showing and hiding tabs, but Vimium doesn't consider about tab "`hidden`" status on Firefox.
> 
> You may try my customized version of Vimium, named Vimium C (https://github.com/gdh1995/vimium-c), and its `previousTab` and `nextTab` will auto jump over hidden tabs.

It's nice to see a maintained version of this amazing extension and I'm definitely switching. Thank you for your work!
