### ISSUE TITLE
When switching web pages vimium stops working

### ISSUE THREAD

**Issue by Orlando-pt** [philc/vimium#4127]
Each time I move from one page to another I need to click `Esc` for `vimium` to start working properly. Otherwise the page will not accept any of the usual commands. Another way to make the extension work is to just click with the mouse on the page.

**To Reproduce**
1. Go to any URL
2. Check that you're unable to perform any `vimium` command

**Browser and Vimium version**
- Brave browser: `1.43.93 Chromium: 105.0.5195.127 (Official Build) (x86_64) `
- OS: `macOS Version 12.4`
- Vimium: `Version 1.67`

**Comment by gdh1995** [comment]
I guess it's because your test page focused its text box when you switched to it, and then Vimium auto entered Insert Mode and suppressed its key mappings.

**Comment by Orlando-pt** [comment]
But the strange thing is that this behaviour happens on all the sites I visit. @gdh1995 Do You have any idea how I can solve this problem?

**Comment by gdh1995** [comment]
What about disabling all other browser extensions except Vimium, and retrying your tests?

**Comment by Orlando-pt** [comment]
It was conflicting with another extension, after removing it vimium started working perfectly.

**Comment by philc** [comment]
Out of curiosity, which extension was in conflict?

**Comment by Orlando-pt** [comment]
It was the `Weava` extension. You can see it [here](https://chrome.google.com/webstore/detail/weava-highlighter-pdf-web/cbnaodkpfinfiipjblikofhlhlcickei).

**Comment by gdh1995** [comment]
Well, it's because the extension Weava injects some CSS code which harms other extensions - if only they use `body~div` - on some websites (including not Google but www.baidu.com).
