### ISSUE TITLE
"Open the clipboard's URL in the current tab" no longer working

### ISSUE THREAD

**Issue by XOKP** [philc/vimium#4130]
**Describe the bug**
Both "Open the clipboard's URL in the current tab" and "Open the clipboard's URL in a new tab" are no longer working for weeks.

**To Reproduce**
1. Go to any URL.
2. Enter the key mapped to "Open the clipboard's URL in the current tab" or "Open the clipboard's URL in a new tab".
3. It navigates to the default page, but not what is in the clipboard.

**Browser and Vimium version**
Chrome version: 105.0.5195.125 (Official Build) (x86_64) 
Vimium version: 1.67

**Comment by tyler-tm** [comment]
+1

Reproducible in Vimium on Chrome (same versions as above).

Not reproducible with Vimium-FF, with the same actions from the same page.

**Comment by NI57721** [comment]
Duplicate of #4122 #4120

**Comment by NI57721** [comment]
Duplicate of #4120

**Comment by BachoSeven** [comment]
@XOKP feel free to close this, as it's a duplicate.

**Comment by XOKP** [comment]
The issue has been fixed now.
