### ISSUE TITLE
`d` key not workling on youtube

### ISSUE THREAD

**Issue by scarf005** [philc/vimium#4134]
**Describe the bug**
`d` key does nothing when playing a youtube video.

**To Reproduce**
1. go to any youtube video (for example: https://www.youtube.com/watch?v=mPZkdNFkNps
2. press `d` key. nothing happens. (`d` key is not in ignored list)

![image](https://user-images.githubusercontent.com/54838975/193733575-f8941b35-ab29-4f71-8e53-c6d80327e863.png)

**Browser and Vimium version**
```
vimium version: 1.67.1
firefox version: 106.0b6
OS version: Linux 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022
```

**Comment by metalx1000** [comment]
It's working for me.  I've tried it in 2 different versions of Fire Fox from the Debian repositories. 
OS Version: Linux 6.0.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.2-1 (2022-10-16) x86_64 GNU/Linux
Fire Fox Versions:
102.4.0esr (64-bit)
106.0 (64-bit)

Vimium Version: version 1.67.2

Are you still having the problem or has an update fixed it for you?
This issue might be closed if it's been fixed.

**Comment by metalx1000** [comment]
I've added "map d nextTab" to my setup and it's still working for me.
I'm not sure why it's not working for you. 🤷

**Comment by scarf005** [comment]
![_05](https://user-images.githubusercontent.com/54838975/197220721-3aa9aaf0-f3e3-4954-a55a-02ce300a349e.png)

...oh. it was because vimium execlude-keys does not recognize arrow keys.
so in this case, `<down>` ignored `<>down`, which contained `d`, hence not working.

**Comment by gdh1995** [comment]
Um, yes those keys only support single characters, but not composed keys
