### ISSUE TITLE
Filtering out youtube.com query string

### ISSUE THREAD

**Issue by E-RELevant** [philc/vimium#4135]
**Describe the bug**
While using the `Excluded URLs and keys` option to filter out youtube videos (as the extension overrides the default shortcuts), the filter does not recognize the query string while using a wildcard `/watch?v=*`. That leaves you with one of two options: either the extension work around entire website pages or you have to disable it to the entire website.

**To Reproduce**
Step*s to reproduce the behavior:
1. Under `Excluded URLs and keys`, add `https?://www.youtube.com/watch?v=*`
2. Go to URL ['youtube.com'](https://www.youtube.com)
3. Click on a video, and try to activate one of the shortcuts (for example: `shift+?`)

Include a screenshot if applicable.
![image](https://user-images.githubusercontent.com/20738487/193978616-81a58d28-5e30-4939-b496-8f7791fbd1bc.png)

**Browser and Vimium version**
Microsoft Edge 105.0.1343.53 (Official build) (64-bit)
Vimium v1.67

**Comment by DaBauer** [comment]
Heya I hope I'm reading you right. But the you need to escape the `?`. It won't match it and you end up with it matching `watcv=*` or `watchv=*`, I did the same as you only matching `watch*`. When escaping (`watch\?v=*`) it works for me.
I also mapped c to LinkHints.activateMode to be able to use it still.

**Comment by E-RELevant** [comment]
> Heya I hope I'm reading you right.
> 
> But the you need to escape the `?`. It won't match it and you end up with it matching `watcv=*` or `watchv=*`, I did the same as you only matching `watch*`. When escaping (`watch\?v=*`) it works for me.
> 
> I also mapped c to LinkHints.activateMode to be able to use it still.

Thanks for this observation and detailed explanation, which seems to resolve this problem. My bad.
