### ISSUE TITLE
Page wide exclude keys are not case-sensitive

### ISSUE THREAD

**Issue by martin-braun** [philc/vimium#4136]
**Describe the bug**
Custom key mappings (from the options) are case-sensitive, which is good. However website specific key excludes are not.

**To Reproduce**
1. Go to URL youtube.com
2. Add the key `I` as exclude key for the website
3. Start a video and press shift + `i`

YouTube allows to minimize the current video either with `i` or `I`. I use `i` for jumping into an input field, but I want to remain the possibility to minimize videos on YouTube using the capital `i`.

Part of my config is

```
map i focusInput
map I enterInsertMode
```

I don't need insert mode on YouTube, because all player controls are sensitive to capital letters by using the shift key, but I cannot exclude my shift key bindings, hence this issue.

**Browser and Vimium version**

Brave 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (x86_64)
Vimium 1.67

**Comment by gdh1995** [comment]
Um, so you want to make Youtube accept Shift+I as "minimizing video" - am I right?

If so, I'm afraid it's too hard to do by web extensions. `Shift` is a status which can not be hidden easily. I suggest you may use another key to trigger `focusInput`.

**Comment by martin-braun** [comment]
@gdh1995 thx for the reply, you got it, that's exactly what I want. Using a different key was possible, but it would defeat the purpose of this extension, namely to mimic Vim keys in the browser. I want to jump to an input field with `i`, on YouTube as well. YouTube accepts shift + `i` for minimizing as well.

What I don't understand is: Why can a status like `shift` not specifically hidden when I can indeed have different mappings for keys with and without a status. I.e. Why can I have different mappings for `i` and `I` (shift + `i`), but I cannot ignore one over the other on specific websites.

I can paste `unmap I` in the settings globally and things will work on YouTube like I want them to work. So I wish to have page-specific bindings in a way that I can add `unmap I` only on YouTube and my issue would be solved.

Thanks.

**Comment by gdh1995** [comment]
Oh I misunderstood your issue because I seldom uses Youtube. Basically, Vimium's `exclusion rules` do support case-sensitive matching, so I'm not sure what's wrong in your Vimium.

During my test today Vimium was able to exclude a single `I` (but not `i`) on a video page of youtube.com on my Chrome 106, Win11. And my test configuration is exactly the same:
![image](https://user-images.githubusercontent.com/5547703/194896522-93de88f7-d993-4f44-bd5c-b193b8d76b79.png)

**Comment by martin-braun** [comment]
Pretty sure I messed up somewhere, it's working now, I didn't test it since I reported this issue and I literally had this configuration. Weird. Thanks for the help, very happy it works now. :)
