### ISSUE TITLE
Is it possible to assign shift+space or control+space to an action? 

### ISSUE THREAD

**Issue by emilyyyylime** [philc/vimium#4137]
If so how, otherwise this is a feature request

**Comment by gdh1995** [comment]
```
map <c-space> scrollUp
map <s-space> scrollDown
```

**Comment by dansteen** [comment]
Thanks!  What about control+shift+space?

**Comment by dansteen** [comment]
figured it out!

<c-s-space>

Thanks!

**Comment by gdh1995** [comment]
Um, some shortcut keys may have been occupied by other applications on your operating system.
