### ISSUE TITLE
add transparent of `f` button

### ISSUE THREAD

**Issue by NEX-S** [philc/vimium#4140]
![image](https://user-images.githubusercontent.com/97107165/194650541-a7b62993-378b-4ac0-8321-16ef03bbf968.png)
In some cases, the `f` will blocking our sight, maybe we need add some transparency of it?

**Comment by gdh1995** [comment]
You may configure CSS code on Vimium Options:
![image](https://user-images.githubusercontent.com/5547703/194796933-3305ed4a-8616-4370-baff-d375ef2a156d.png)

**Comment by gdh1995** [comment]
yes, but it uses some different css selectors.

**Comment by gdh1995** [comment]
Here's some differences between Vimium C and Vimium on the `Custom CSS` option: https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-custom-CSS#finding-element-classes-and-ids
