### ISSUE TITLE
Is it possible to navigate to relative paths using o/O?

### ISSUE THREAD

**Issue by baroxyton** [philc/vimium#4143]
I use Vimium-FF

is it possible to configure it as such that opening vomnibar on `https://www.google.com` and entering `/maps` navigates to `https://www.google.com/maps`?

**Comment by gdh1995** [comment]
There's a command named `Vomnibar.activateEditUrl` and it has been mapped to `ge` by default. So you may take a try.

**Comment by metalx1000** [comment]
Seems like this can be marked as "closed"
