### ISSUE TITLE
If you use a keyboard that is not in English, shortcuts do not work

### ISSUE THREAD

**Issue by E-RELevant** [philc/vimium#4145]
**Describe the bug**
The different keypads won't respond if the keyboard layout is different from English while using the web browser. The only time they will work is when the layout is changed to English.

**To Reproduce**
1. Configure multi keyboard-layout
2. Use the extension in a non-English keyboard layout

**Browser and Vimium version**

Microsoft Edge 106.0.1370.47 (Official build) (64-bit)
Vimium v1.67

**Comment by gdh1995** [comment]
Um, it's designed to do so, and you may add mappings for your keyboard layout manually - some examples are on https://github.com/philc/vimium/wiki/Key-Mappings

**Comment by E-RELevant** [comment]
> Um, it's designed to do so, and you may add mappings for your keyboard layout manually - some examples are on https://github.com/philc/vimium/wiki/Key-Mappings

Appreciate the quick response, did not notice that. Thanks!
