### ISSUE TITLE
Vimium-FF uses "i" for link hints and fails when using them

### ISSUE THREAD

**Issue by Schweber** [philc/vimium#4146]
I am using Vimium-FF 1.67.1 with Librewolf 105.1. In Advanced Options i have set `Characters used for link hints` to `sadjklh`. Still, Vimium-FF employs the letter `I` as a link hint and all link hints terminate when i enter the letter `I`.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/64630479/196369389-397a9fe9-1dec-4afa-94dd-b072281e4ee2.png">

<img width="858" alt="image" src="https://user-images.githubusercontent.com/64630479/196369471-b0280583-52a0-439b-9f4e-33550a4bca96.png">

I then unmapped the letter `I` in `Custom key mappings` but this doesn't solve the problem. `Search when you start typing` is disabled in Firefox/Librewolf.

I am also using Vimium with Chromium with the same settings and there it works fine and doesn't employ the letter `I` for link hints.

**Comment by gdh1995** [comment]
It seems your characters only includes `l` (a lower-case version of `L`), but not `i` (a lower case of `I`). So you may press `L` key to select those hints.

It's your system font which cause the `L` letter looks like `I`.

**Comment by gdh1995** [comment]
Sorry my last comment seems wrong. I'm not sure why, but in your first snapshot characters doesn't include `i`, but the 2nd snapshot does show both `L` and `I`. It's very strange.

Are you sure that the 2 snapshots were using a same configuration?

**Comment by Schweber** [comment]
Yes, they are of the same configuration, taken at the same time. 

As mentioned, in Chromium it works fine for me with exactly the same settings. That's why i find it particularly strange.

Also that it terminates when i enter the letter `i` feels strange.

**Comment by Schweber** [comment]
Yes, it happens on all websites:

<img width="926" alt="image" src="https://user-images.githubusercontent.com/64630479/196594805-7ceecae4-a1c6-4014-8afa-02d9cf6b8f07.png">

And also with all other extensions disabled:

<img width="957" alt="image" src="https://user-images.githubusercontent.com/64630479/196594930-5a1a23df-212e-4cc6-b163-ad5f09daab95.png">

Just to make sure, i checked again the settings of Vimium:

<img width="651" alt="image" src="https://user-images.githubusercontent.com/64630479/196595087-5eda2551-1ef5-414a-99c7-78b6ffbcfd53.png">


Could this be related to Librewolf (fork of FIrefox)?

**Comment by Schweber** [comment]
These are my settings (renamed to .txt because github won't allow .json):
[vimium-options.txt](https://github.com/philc/vimium/files/9816755/vimium-options.txt)

**Comment by gdh1995** [comment]
Now I guess the `I` you saw was `J. You may increase padding of hint markers to see bottom of letters.

**Comment by Schweber** [comment]
You are right. They are `J`s but in Librewolf they are rendered so that they protrude out of the bottom.

Thank you!

**Comment by gdh1995** [comment]
It's "font (font-family)" which decide how a character looks like. You may add custom CSS to adjust it:
```
.vimiumHintMarker > .vimiumReset {
  font-family: Consolas; /* or any other font existing on your computer system */
}
```

![image](https://user-images.githubusercontent.com/5547703/196858706-47fe1f7b-8c15-4dad-8923-a7c2eb2fdec7.png)

**Comment by Schweber** [comment]
This doesn't have any effect on my system. I tried `sans-serif`, `Hack`, `Fira Code` and `Liberation sans`. The font is always the same.

Anyway, the increased padding is a sufficient fix for my problem. Thank you again.

**Comment by gdh1995** [comment]
Maybe it means the CSS didn't take effect. So you may try:
``` css
.vimiumHintMarker > .vimiumReset {
  font-family: Consolas !important;
}
```

**Comment by Schweber** [comment]
Hmm, that doesn't improve it.

Anyway, thank you again for your help.

**Comment by gdh1995** [comment]
Um are you sure that those font names exist on your browser's environment? If you use some container tools, like Docker, WSL and Flatpak, then maybe your browser can not access those font files.

You may use your browser's DevTools to debug CSS and fonts:
![image](https://user-images.githubusercontent.com/5547703/197320658-bee762f4-e0bf-4672-9817-cc17f20f56c7.png)

**Comment by Schweber** [comment]
Ah, I'm running librewolf in firejail, maybe this has got something to do with it.



22. Oktober 2022 um 06:58, "Dahan Gong" schrieb:
