### ISSUE TITLE
Can't type a backslash in a textbox or textarea

### ISSUE THREAD

**Issue by benjamine** [philc/vimium#415]
When using windows auth usernames usually contain a backslash "\", I can't type it, when I do the textbox (or textarea) just loose focus, and no backslash is added.
I tried switching to "input mode", but it doesn't help.

I'm using:
* Vimum 1.30
* Chrome 15.0.874.121
* Windows 7 
* Spanish Latin Keyboard

Thanks!

**Comment by smblott-github** [comment]
Closing.
Resolved.
