### ISSUE TITLE
White background on dark GitHub after v.1.67.3

### ISSUE THREAD

**Issue by 53R3n17Y-serenity** [philc/vimium#4156]
**Describe the bug**  
White background around Vomnibar, HUD and Help Page (vimiumHelpDialog) on GitHub with custom CSS after v.1.67.3  
I use my own [custom CSS](https://github.com/53R3n17Y-serenity/vimium).   
So far only on GitHub where I came across this issue.  

**To Reproduce**
1. Go to 'https://github.com/'
2. Activate Vomnibar, HUD or Help Page. 

![White background](https://user-images.githubusercontent.com/100675600/198869058-2b31c7f2-0239-42a2-a235-5ce53292660d.png)

**Browser and Vimium version**
Vimium v.1.67.3  
Firefox 106.0.2  

**Other Browsers are fine**  
Vimium v.1.67.2  
Google Chrome | 107.0.5304.87 (Official Build)  
Vimium v.1.67.2  
Vivaldi | 5.5.2805.42 (Stable channel) stable (64-bit)  

**What I have tried**  
Looked at [Comparing v1.67.2...v.1.67.3 · philc/vimium](https://github.com/philc/vimium/compare/v1.67.2...v.1.67.3 "Comparing v1.67.2...v.1.67.3 · philc/vimium")  
Searched this repo found this #3797 Followed some links in that post.  As far as I understand, to fix the issue would be to clone repo and modify extension's CSS directly.  

I'm just confused if this is a new issue or an old issue is reintroduced with  
```css
.vimiumUIComponentVisible {
-  color-scheme: light;
+  color-scheme: normal;
}
```  
Or it's something else.  

I also tried wrapping my CSS with  
```css
@media (prefers-color-scheme: dark) {}
```

**Comment by kiuKisas** [comment]
Same issue here on firefox 106.0.2 & vimium 1.67.3, didn't found an other website that github with this issue, yet.
I'm using this theme: https://github.com/catppuccin/vimium (mocha). Also tried witht the default theme and got the same issue.
Can be fixed on github by setting `color-scheme: light` for the vomnibar iframe, indeed. will turn into a light version, and `color-scheme: dark` produce the same bug as on github with `normal`. 
Hope it helps !

**Comment by gdh1995** [comment]
Um `color-scheme:light` does fix this issue, but `normal` is used to fix another related issue happening since Firefox 106 - https://github.com/philc/vimium/issues/4148#issue-1417141849 .

**Comment by nikinbaidar** [comment]
> Can be fixed on github by setting `color-scheme: light` for the vomnibar iframe, indeed. will turn into a light version, and `color-scheme: dark` produce the same bug as on github with `normal`. Hope it helps !

Adding 
```
iframe.vimiumUIComponentVisible {
    color-scheme: dark;
}
```
To the CSS for Vimium UI doesn't work for me. Do I have to make changes at `/content_scripts/vominbar.css` ?

**Comment by gdh1995** [comment]
@nikinbaidar  Yes you have.

It seems Vimium has to use JavaScript code to check the element and then modify Vomnibar iframe's style.

**Comment by nikinbaidar** [comment]
> @nikinbaidar Yes you have.
> 
> It seems Vimium has to use JavaScript code to check the element and then modify Vomnibar iframe's style.

These in `/content_scripts/vimium.css` works for the moment.
```
.vimiumUIComponentVisible {
  color-scheme: normal;
}

iframe.vimiumUIComponentVisible {
    color-scheme: light;
}
```

**Comment by gdh1995** [comment]
Hello, you may try my #4159, which looks ugly but does succeed during my tests.

**Comment by kuator** [comment]
I decided to downgrade: https://support.mozilla.org/en-US/questions/1164888

**Comment by gdh1995** [comment]
Hello all, I just find another clean and stable way to fix the color issues: `color-scheme: light dark` on `<iframe>` works perfectly. And #4159 has been updated,

**Comment by kiuKisas** [comment]
same issue on https://wiki.hyprland.org/

**Comment by nath1as** [comment]
same issue on facebook
