### ISSUE TITLE
Problem when running Vimium

### ISSUE THREAD

**Issue by vvvv1236** [philc/vimium#4160]
Just downloaded Vimium so totally new
After installing it to the extensions within chrome, setting up a keyboard shortcut to run Vimium and trying to run it, I am shown this

![image](https://user-images.githubusercontent.com/117285820/199501570-fe592b0b-ceaa-412d-b274-94c135ee598c.png)

I did a bit of research but cant figure what this is/asks me to do, given that I am new I assume it is straight forward for some or even all of you

Many thanks!

**Comment by gdh1995** [comment]
Then you don't need to click Vimium icon and modify settings in the popup dialog.

You may open Vimium Options, click all `X` buttons of `Excluded URLs and keys` and then click `Save Options` at the bottom of the page. Then you may press `?` to see Vimium's default shortcut mappings.

**Comment by philc** [comment]
I think the excluded keys dialog is confusing and should be reworked. That's tracked elsewhere, so closing this.
