### ISSUE TITLE
1.67.3 for Chrome

### ISSUE THREAD

**Issue by suewonjp** [philc/vimium#4162]
Thank you for excellent work!

I'm looking forward to using 1.67.3 on Chrome, but the version is still not there.

https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en

You know 1.67.2 on Chrome has an issue with yc, yf commands, so I miss the time when those commands used to work...

Can I ask you when we'll get 1.67.3 on Chrome?

**Comment by philc** [comment]
They rejected it because of a copy and paste permissions issue. I need to
look into it. Also, the dark mode fix that’s in 1.67.3 is a regression on
some sites. I’ll look into it this weekend.

**Comment by philc** [comment]
By “they”, I mean that chrome store rejected the latest vimium update.

**Comment by gdh1995** [comment]
In order to support dark mdoe, #4159 should work.

**Comment by suewonjp** [comment]
> They rejected it because of a copy and paste permissions issue.

Sad... 😞

**Comment by suewonjp** [comment]
I've confirmed yc, yf commands work with 1.67.4 on Chrome.
Thank you.
