### ISSUE TITLE
LinkHints broken since last update (firefox)

### ISSUE THREAD

**Issue by MrJJJ** [philc/vimium#4179]
**Describe the bug**
When trying to type the letter of link hints, sometimes it doesn't work (particularly when there is twice the same letter)

**To Reproduce**
Try to type a link hint with twice the same letter

Include a screenshot if applicable.

**Browser and Vimium version**
Vmium C [1.99.9](https://github.com/gdh1995/vimium-c/blob/master/RELEASE-NOTES.md#1999), Firefox 107, Linux

Name 	Firefox
Version 	107.0
Compilation ID 	20221111000055
Distribution ID 	canonical-002
OS Linux 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022

**Comment by gdh1995** [comment]
Hello v1.99.90 should have fixed this bug (firstly reported in https://github.com/gdh1995/vimium-c/issues/810).

BTW, this issue belongs to the repo of https://github.com/gdh1995/vimium-c/issues, but not here.
