### ISSUE TITLE
Listen to event.code rather than event.key

### ISSUE THREAD

**Issue by anterpin** [philc/vimium#4181]
**Feature Request**
In order to add functionality to multiple keyboard layout, listen to the event.code rather than the event.key

Example:
Currently, the keybindings don't work with a russian keyboard layout.

**Comment by gdh1995** [comment]
You may try `Custom Key Mappings` like https://github.com/philc/vimium/wiki/Key-Mappings#russian-language-keyboards , or just enable `Ignore keyboard layout`:
![image](https://user-images.githubusercontent.com/5547703/203695602-cb6b1f12-e08d-498b-aa3a-d497d035d42e.png)

**Comment by anterpin** [comment]
Ohhh, thank you, I didn't see that options, it works fine.
Have a great day!

**Comment by toropanov** [comment]
That works well, but it might be beneficial to include a feature to select a custom language?
