### ISSUE TITLE
"C" no longer copies URLs despite saying the link was yanked

### ISSUE THREAD

**Issue by KeronCyst** [philc/vimium#4183]
I don't know what happened; this just suddenly stopped working after years of no problems.

Microsoft Edge Version 107.0.1418.56 (Official build) (64-bit) on Windows 11 Home 22H2.

**Comment by kungfubeaner** [comment]
The issue started for me yesterday on Firefox too on both Arch Linux and Windows

**Comment by chapmanjacobd** [comment]
Yes. I also have noticed this in Firefox the past two days especially (because I have been needing to yank more URLs than normal) but it likely has not been working since Nov 26 when my firefox was upgraded to 107.0-4 from 107.0-3

**Comment by EvtRei** [comment]
I have the same issue on librewolf with version 1.67.4 of the extension.
It worked again when i downgraded to version 1.67.3.
I'm thinking it may be the changes in commit 15ba534 that broke this feature on Firefox based browsers.

**Comment by jetgogol** [comment]
Same issue with 1.67.4, also librewolf.

**Comment by tomit4** [comment]
I also have this issue on Librewolf FireFox 106.0.4 for the about a week or so now. Not the most annoying thing in the world (Ctrl+L + Ctrl+C will do the same), but yy was super handy especially when clipboard is enabled in vim editor...
Is fix possible?

**Comment by Felixoid** [comment]
Hello dear @philc, and thank you so much for the great extension!

Please, consider taking a look into the issue, it's very inconvenient to have any URL yanking broken ^_^

**Comment by ElectricCoffee** [comment]
Is there a way to fix this perhaps?

According to the mdn docs for clipboard access, Firefox does things a bit different: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard#browser_compatibility

**Comment by foxxx0** [comment]
For all of you in dire need for a fix:
A workaround has already been posted by @EvtRei : https://github.com/philc/vimium/issues/4183#issuecomment-1336119095
And I can confirm that it's working for me too.

Just downgrade to 1.67.3 for now and afterwards make sure to disable auto-updates for vimium until this issue is resolved.
(Just subscribe to this github issue to get notified about updates and to eventually re-enable auto-updates for this extension)

**Comment by Felixoid** [comment]
Thank you @foxxx0 

Just in case, the older version for FF can be downloaded on the page https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/versions/, [a direct link](https://addons.mozilla.org/firefox/downloads/file/4023331/vimium_ff-1.67.3.xpi)

**Comment by ZAHMIK** [comment]
+1

**Comment by spiderbit** [comment]
@Felixoid The file is no longer available, I am stuck at 1.67.4 on the extension website there is only Version 1.64.6 from 2019 as latest version. Which is also strange because that date matches more the 1.64.5 version the 1.64.6 version was released according to github 2020.

**Comment by Felixoid** [comment]
![image](https://user-images.githubusercontent.com/3025537/208918515-f1cb36db-b31d-4ead-bf5f-29e3e48e0afa.png)

yes, something happened with the extension definitely. @philc what happened?

**Comment by spiderbit** [comment]
@Felixoid apparently that: #4195
