### ISSUE TITLE
Vimium does not work on tabs of other extensions

### ISSUE THREAD

**Issue by sakalys** [philc/vimium#4190]
**Describe the bug**
Navigating to another tab does not work if you are currently focusing a tab of another extension. E. g. if you are on a custom "new tab" screen provided by "Toby" chrome extension, or, if you are currently on a tab of a "suspended tab" of a tab suspender plugin, then when pressing `shift+j`, or `shift+k` you are unable to navigate away. 
Actually I think none of the other vimium commands work as well. 

**To Reproduce**
1. Suspend a tab with any of the  "tab suspender" plugins. E.g. https://chrome.google.com/webstore/detail/tab-suspender/fiabciakcmgepblmdkmemdbbkilneeeh
2. Try to act with any of the vimium commands.
3. They do not work.

**Browser and Vimium version**
Brave: 1.45.127 Chromium: 107.0.5304.110 (Official Build) (x86_64)
Revision: 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS: macOS Version 12.5.1 (Build 21G83)
Vimium: 1.67.4

**Comment by gdh1995** [comment]
It's a limit of browsers including Chrome and Firefox.

**Comment by sakalys** [comment]
that’s sad
