### ISSUE TITLE
Vomnibar doesn't support Vim Normal Mode (feature request?)

### ISSUE THREAD

**Issue by azinsharaf** [philc/vimium#4198]
Hi, Thanks for this great extension.
As far as I know vomnibar currently doesn't support Vim `Normal` mode. For instance using `b` for bookmark shows vominbar and after typing some characters there is no way to go up/down using j & k keys. The only option is using arrow keys. In `Telescope` pressing escape key changes the status to `Normal` mode and then the items can be selected using j/k keys. And pressing escape twice closes the window.  

**Browser and Vimium version**
Brave: 1.46
Vimuim: 1.67.4

**Comment by nikinbaidar** [comment]
You can use `<C-j>` to move up and `<C-k>` to move down and `C-CR` to edit the selected link.

**Comment by azinsharaf** [comment]
Thanks!
