### ISSUE TITLE
Vimium: how to remap key o ?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [philc/vimium#4206]
i want to remap the key
o       Open URL, bookmark, or history entry
But how is this commands name?
map s Open URL ?

How is the genious "Vomnibar" called ? :)

thx

**Comment by Clemens-Ratte-Polle** [comment]
thx :)
But too compicated not only for me i guess.
Perhaps you could always list all active mappings to better understand the logic? :)
So long i will us this : edge://extensions/shortcuts

**Comment by gdh1995** [comment]
Checkbox is not enough, because a command may be mapped to quite a few different keys with different parameters.
