### ISSUE TITLE
Publish extension to Microsoft Edge Add-ons

### ISSUE THREAD

**Issue by MPThLee** [philc/vimium#4211]
MS Edge is based on Chromium now since 2020 according to [Wikipedia](https://en.wikipedia.org/wiki/Microsoft_Edge#New_Edge_(2019%E2%80%93present)), It is compatible with Chrome version without changing core codes. (Some of extension API that related to Google is removed on Edge but doesn't used on here.)

As The browser comes with External store compatiblity especially Chrome Webstore), It's easy to install and use. However, As it is *Extetrnal*, User need to allow the setting to continue. (See below image)
![image](https://user-images.githubusercontent.com/26970092/213607520-7fdca1f3-eeda-482f-9070-5dea78084312.png)

So, Why not to publish the extension on [Microsoft Edge Add-ons](https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home)? It's just CWS but for Edge.

Porting is [simple](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension). As both runs on same engine, Just rebrand on name and descriotion (eg: `Chrome` to `Edge`) and remove `update_url` (which is required for other side too.). 

Any other steps are [Create edge developer account on Partner center](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/create-dev-account) and [Publish extension to their store](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension). (Both are MS documentation)

**But**, As of July 2022, Microsoft is not accepting new Manifest v2` extensions as of [migrating to Manifest V3](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/manifest-v3). 
So should refactor code with v3 compatible. It is same for other browser. (Releated: #4075)

This issue is higly related with #2076

**Comment by philc** [comment]
Thanks for filing this and for the various pointers. I'll take a look! As you say, Vimium needs to be migrated to manifest v3 before publishing, and I'm not yet sure how big of a change that will be, but it's planned for early this year.

**Comment by philc** [comment]
Hey @MPThLee, Vimium is now on the [Edge Add-ons site](https://microsoftedge.microsoft.com/addons/detail/vimium/djmieaghokpkpjfbpelnlkfgfjapaopa). Please leave a review there to help encourage others to try it.

Thanks!
