### ISSUE TITLE
Options page broken if all Excluded rules cleared

### ISSUE THREAD

**Issue by kLabz** [philc/vimium#4223]
I cleared all "Excluded URLs and keys" and now my options page is unusable (breaks with `can't access property "Exclusions"`, can't do anything in there).

Using firefox with latest Vimium-FF extension.

As a workaround / a way to unblock me, is there a way to reset my vimum config, or manually edit it?

![image](https://user-images.githubusercontent.com/6101998/218677729-370284ee-3b2c-4503-b51a-a9caa071a37b.png)

**Comment by kLabz** [comment]
Seems to be temporary containers messing around with the extension options page, actually..

**Comment by gdh1995** [comment]
Oh yes, Firefox's `container` will prevent Vimium from accessing its settings.
