### ISSUE TITLE
Press "T" then "Search through your open tabs", hope to display the index of the tab page and highlight the current tab page。

### ISSUE THREAD

**Issue by dyguests** [philc/vimium#4231]
**Describe the bug**
Press "T" then "Search through your open tabs",
hope to display the index of the tab page and highlight the current tab page

**To Reproduce**
1. Press "T"
2. show open tabs.

Include a screenshot if applicable.

**Browser and Vimium version**

If you're using Chrome, include the Chrome and OS version found at chrome://version. Also include the Vimium version found at chrome://extensions.

If you're using Firefox, report the Firefox and OS version found at about:support. Also include the Vimium version found at about:addons.

**Comment by gdh1995** [comment]
No Vimium doesn't show tab index.

**Comment by dyguests** [comment]
I found that vimium is the perfect solution to hide the tab bar and address bar of chrome, but I can't know which tab page I am currently in after pressing "T".

:(

**Comment by dyguests** [comment]
@gdh1995 you are genius！
