### ISSUE TITLE
Make it possible to focus a scrollable div without using the mouse

### ISSUE THREAD

**Issue by vbaruh** [philc/vimium#425]
Take a look, my expectation is that the scrolling should work on the main frame but it does not affect anything.
Opening links functionality work fine.

**Comment by marlun** [comment]
I often need to click no the part of the page that I want to scroll before being able to use the keyboard. Is it still planned to make it possible using the keyboard?

**Comment by smblott-github** [comment]
Ah.  The "Vimium click", @marlun.

Often, the `gF` (focus the main frame) command helps.

**Comment by marlun** [comment]
Unfortunately that almost never works for me because it's never multiple frames. Take for example http://redux.js.org/docs/introduction/ThreePrinciples.html if I load it, move to another section using vimium F I can no longer scroll the main text div.

**Comment by smblott-github** [comment]
[This branch](https://github.com/smblott-github/vimium/tree/global-link-hints-extended) is an extension of #2048 which (amongst other things) makes scrollable divs selectable.  For example, with filtered hints, it looks like this...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/14063964/dbf6a612-f3e4-11e5-9c28-45d9e98e5853.png)

**Comment by tamvm** [comment]
> [This branch](https://github.com/smblott-github/vimium/tree/global-link-hints-extended) is an extension of #2048 which (amongst other things) makes scrollable divs selectable. For example, with filtered hints, it looks like this...
> 
> ![snapshot](https://cloud.githubusercontent.com/assets/2641335/14063964/dbf6a612-f3e4-11e5-9c28-45d9e98e5853.png)

Hi @smblott-github, thank you for your contribution in this project for the community. 

The idea about choosing scrollable div is quite nice, I just want to ask about the implementation of that, how to config as your image?

Thank you,
