### ISSUE TITLE
focusInput not working correctly on Google search page

### ISSUE THREAD

**Issue by asgeirtj** [philc/vimium#4251]
**Describe the bug**
This issue first appeared about a month ago. Normally when focusInput is used on any page the cursor goes to the end of the text if there is text there already. However, when using Google search the cursor now appears at the start of the already input text if there is one. Note that this only happens on the Google search page not on www.google.com, that is the problem comes into place if you search for something on google.com or in your browser URL field and then want to amend the search term by adding something to it, usually to the end of the search term. 

**To Reproduce**
1. Go to URL 'www.google.com'
2. Click on 'search for something'
3. On the results page use focusinput to focus the input you will see that the cursor goes to the start of the input instead of the end

Include a screenshot if applicable.

**Browser and Vimium version**
Microsoft Edge
Version 112.0.1722.64 (Official build) (64-bit)
Vimium version 1.67.4

**Comment by tasusu** [comment]
Deprecate of https://github.com/philc/vimium/issues/4247

**Comment by philc** [comment]
Closing in favor of #4247.

**Comment by asgeirtj** [comment]
Sorry, was it fixed? I'm not familiar with Github :). Regards, Ásgeir

**Comment by philc** [comment]
@asgeirtj I've just submitted this fix to the Chrome and Firefox stores as v1.67.7, and it should go live in the next day or two.
