### ISSUE TITLE
Focusing content page

### ISSUE THREAD

**Issue by majkinetor** [philc/vimium#426]
On many instances main page gets deselected and needs to be clicked once in other for vimio to continue working. 
It would be good to at least have an option to select the main frame.

For instance, on google plus if I use vimio to open notification panel from the google toolbar, if I press ESC toolbar is gone and vimio stops working until I click on the page.

**Comment by smblott-github** [comment]
This would be a great feature to have.  The "Double `Esc`" idea seems a bit hokey.  Perhaps a new command `goToMainFrame` with a binding of `gF` would be better.

@mrmr1993.  Do you have any insight into a reliable way to detect the "main" frame?

**Comment by mrmr1993** [comment]
> Do you have any insight into a reliable way to detect the "main" frame?

You can pass `frameId: 0` in the options for [`chrome.tabs.sendMessage`](https://developer.chrome.com/extensions/tabs#method-sendMessage) and only the top frame will recieve the message. That seems like the easiest way to do it.

**Comment by smblott-github** [comment]
Yes, @mrmr1993.  Thanks.  I was wondering about @int3's concerns above, e.g. re. GMail.

**Comment by mrmr1993** [comment]
Since frames are only an implementation detail, it would be better to try to get the other commands (search, link hints, etc.) to work across all frames in a tab. Then this problem goes away altogether.

**Comment by boblehest** [comment]
Here's an example: http://doc.rust-lang.org/1.0.0-beta.2/book/
When I first load the page, nothing (in view) is focused. Scrolling has no apparent effect. I think it would be nice with a command that displays a link over each frame for you to select, like this: http://i.imgur.com/x4lenuH.png
