### ISSUE TITLE
Unfocus input/textarea on <C-c>?

### ISSUE THREAD

**Issue by martin-braun** [philc/vimium#4271]
If I have no selected any text, would it be possible to unfocus the current input/textarea, so the page navigation is available again?

I don't like ESC to be honest.

**Comment by gdh1995** [comment]
No, although Vimium supports `mapKey` in key mappings, but it only accept mappings from a single character to another single character.

You may try my customized version, named Vimium C (https://github.com/gdh1995/vimium-c), and it supports:
```
mapKey <c-c> <esc>
```

And if you want to only enable such a mapping when an input box is focused, then you may use:
```
mapKey <c-c:i> <esc>
```

**Comment by martin-braun** [comment]
@philc @gdh1995 I don't understand why you both never decided to work on one project. I think all those great extensions should've been upstreamed.

Thank you.
