### ISSUE TITLE
how to make the search window appears on the lower left foot  like vim instead of the lower right foot 

### ISSUE THREAD

**Issue by edte** [philc/vimium#4291]
May I ask how to use CSS to modify, so that the search window that appears after pressing /  appears on the lower left foot like vim. instead of the lower right foot 

this: 
<img width="394" alt="截屏2023-08-04 17 31 27" src="https://github.com/philc/vimium/assets/50194671/13e52e32-8fe0-470f-b880-cd56be7db650">

**Comment by wjianbo** [comment]
Hope this could help.
![image](https://github.com/philc/vimium/assets/2434388/73d5503e-4055-42b3-92f6-6bd4a86538eb)

**Comment by edte** [comment]
it works,thanks.
