### ISSUE TITLE
Scroll commands not working j/k u/d G/gg

### ISSUE THREAD

**Issue by mcint** [philc/vimium#4293]
**Describe the bug**
I've encountered this bug on other sites, at the moment I just have https://google.github.io/typograms/ to mention.

Any of `k`, `u`, `gg` will move the viewport up about 3px or 0.035em (1/28, 28 keypresses per line).

I've tried manually running vimium's functions but I'm not quite sure what objects they're loaded on in the DOM (might be a nice wiki page). But the standard(?) scrollBy, scrollTo, and similar on `document.scrollingElement` (-> `body`) and `document.body`, are not helping me on this example.

`document.scrollingElement.scroll("x", 1000)` works for me on xkcd.com, but not on this site.

**To Reproduce**
1. Go to URL '[this site](https://google.github.io/typograms/)'
2. Use spacebar to move view down a page
3. Try j/k, u/d, gg/G

Include a screenshot if applicable.

**Browser and Vimium version**
Browser: 1.56.14 Chromium: 115.0.5790.114 (Official Build) (64-bit) 
Vimium: 1.67.7 (chrome extension store)

Seems to be similar or related to #962, #1138, #2168 (PR), or #2756

**Comment by mcint** [comment]
Notes for myself as I think about addressing this:
- I had a local diff for customized handling of the focused element on pages with embeds, especially twitter feeds, lost only local copy when computer was stolen. 

- These PRs, merged except noted closed ones, look related and might direct me to relevant sections of the codebase.
[Site-specific hack to make expanded tweets scrollable. by smblott-github](https://github.com/philc/vimium/pull/3101)
[Start searching for scrollable elements from <body> instead of <html> whenever possible by mrmr1993](https://github.com/philc/vimium/pull/2801)
[Suppress link hint keys by mrmr1993](https://github.com/philc/vimium/pull/2782)
(Closed) [When a sub-frame cannot scroll, focus the top frame. by smblott-github](https://github.com/philc/vimium/pull/2875)
[use Element::scrollBy if it exists by gdh1995](https://github.com/philc/vimium/pull/3111)
[Use document.scrollingElement for scrolling by dpogue](https://github.com/philc/vimium/pull/2168)
(Closed) [Implement scrolling to percent (the '%' command). by leoj3n](https://github.com/philc/vimium/pull/1965)
[Link hints: false positives and scrollable divs by smblott-github](https://github.com/philc/vimium/pull/2069)
[Fix scrolling for webpages using web components by mrmr1993](https://github.com/philc/vimium/pull/1803)
[Move Scroller.init() up the handler stack. by smblott-github](https://github.com/philc/vimium/pull/1527)
(Closed) [Restore scroll position after failed find with /. by smblott-github](https://github.com/philc/vimium/pull/1459)
[Initialize scroller to first scrollable element. by smblott-github](https://github.com/philc/vimium/pull/1360)
(Closed) [Scrolling; any change counts as a successful scroll. by smblott-github](https://github.com/philc/vimium/pull/1326)

**Comment by gdh1995** [comment]
Um not reproduced on Vimium v1.67.6 and a current `master` version on MS Edge 115 and Win 11.

**Comment by danielkaczmarczyk** [comment]
On Vimium version 1.67.7 and Firefox 116.0.3 (64-bit) MacOS works fine too, can't reproduce.

**Comment by philc** [comment]
I couldn't reproduce.
