### ISSUE TITLE
Make it possible to map the "delete" key in Vimium's shortcuts

### ISSUE THREAD

**Issue by tzarskyz** [philc/vimium#430]
1. Anyway to map the delete key on a qwerty keyboard, mac specifically.? I tried 'map <delete> ...' with no luck, tried a few others same result. I am trying to map it to 'focusInput'.

**Comment by VaughnGH** [comment]
Would it be possible to add this feature now? Chrome has foolishly removed the ability to hit (shift+) backspace/delete to navigate forwards or backwards in history. [Google has created a poorly/non-functional extension](https://chrome.google.com/webstore/detail/go-back-with-backspace/eekailopagacbcdloonjhbiecobagjci/support)  to re-add this feature, it would be nice to instead use vimium to add these hotkeys.

**Comment by smblott-github** [comment]
@VaughnGH... We've already added `<backspace>` (see [here](https://github.com/philc/vimium#release-notes)).  It'll be in the next release.

I don't see any problem adding `<delete>` too.  It might be as simple as add the relevant entry in `keyNames` ([here](https://github.com/philc/vimium/blob/master/lib/keyboard_utils.coffee)) and testing it.

PR welcome.

**Comment by BohrShaw** [comment]
@smblott-github `map <s-backspace> goForward` seems not working?

**Comment by smblott-github** [comment]
@BohrShaw.  Vimium doesn't support `<s-ANYTHING>` (does it?).

`<c-backspace>` works.

Perhaps we should support `<s-SOMETHING>`, that might be worth raising as a separate issue.
