### ISSUE TITLE
[Feature Request] `Save Changes` button is hard to notice, and modifications are not reflected.

### ISSUE THREAD

**Issue by umizaru** [philc/vimium#4304]
## Current behavior
- The `Custom search engines` field in `Vimium Options` and the `Save Changes` button are far apart, so it is difficult to notice the existence of the `Save Changes` button and the modifications are not reflected in the settings.

![スクリーンショット 2023-09-09 17 10 57](https://github.com/oss-gate/workshop/assets/57088113/c6cb10ac-fc40-43c5-bf7d-04e0532ebbed)

## Expected behavior of new feature
I'd be happy with any of the following:.
- Move the `Save Changes` button to a space just below `Custom search engines`, for example.
- Put a note just below the `Custom search engines` field that says something like "Please press the `Save Changes` button after entering information".
- In the [Custom search engines documentation](https://github.com/philc/vimium/wiki/Search-Engines#ideas-for-search-engine-shortcuts), add a note that says, "When you add a shortcut, press the Save Changed button. Don't forget to click the Save Changed button after adding a shortcut.
- Or, if the entries in the `Excluded URLs and keys`, `Custom key mappings`, and `Custom search engines` fields are modified, the entries in those fields will be reflected without pressing `Save Changes`.

**Comment by tanujjain** [comment]
Taking no effect for me too. Tried excluding urls. Using chrome Version 116.0.5845.187 (Official Build) (arm64).

**Comment by philc** [comment]
It is the case that the Vimium options page will show an alert if you try to close the page without pressing Save. I just confirmed this behavior on Vimium v1.67.5 and on master. Is that not happening for you?

**Comment by umizaru** [comment]
@philc 
Apologies for the delay in replying.

Yes, I have confirmed that even in my environment, if I change the options and try to close the page without pressing the Save button, I get an alert.

However, the problem is that it is difficult to notice the Save Changes button. Therefore, I have listed expected behavior of new feature. We would appreciate your consideration.

**Comment by philc** [comment]
1. The options page refresh in v2.0 should help with this somewhat -- there's no longer a large gap between the options and the save button.
2. I think the alert when you leave the page is sufficient to remind the user that pressing Save is required.
3. Another approach is to make all changes persist with requiring that the user press Save, but that doesn't seem high priority to me given 1 and 2.
