### ISSUE TITLE
vomnibar navigation via <tab> broken?

### ISSUE THREAD

**Issue by ewollesen** [philc/vimium#4313]
**Describe the bug**

[According to Tips and Tricks](https://github.com/philc/vimium/wiki/Tips-and-Tricks#moving-in-the-vomnibars-list) one can use &lt;tab&gt; to navigate vomnibar entries. This worked for me in v1.67.3. However, with the latest master (specifically `9c01200d`, using &lt;tab&gt; seems to be picked up by the browser, and it moves focus from the vomnibar to the current browser tab. C-j/C-n/arrow keys still work, but man, I have a lot of muscle memory tied to using tab. :( 

**To Reproduce**

1. Press `o` to open the vomnibar
2. Type something to get a few entries populated in the vomnibar
3. Press &lt;tab&gt;

Include a screenshot if applicable.

**Browser and Vimium version**

Firefox: 117.0.1 
OS: Linux 6.2.0-1013-lowlatency #13-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep 7 08:58:56 UTC 2023
Vimium: 2.0.0

**Comment by philc** [comment]
Oops, that was a recent regression. Thank you for reporting it @ewollesen.
