### ISSUE TITLE
Release version 2.0

### ISSUE THREAD

**Issue by philc** [philc/vimium#4317]
I'm creating this issue to make folks aware that this large release is finally rolling out.

I expect to see some issues related to the new version because of these changes:

* We're using manifest v3.
* This extension requests a different set of permissions (as required by the migration to manifest v3).
* There's been a lot of code changes, including a new options data schema.

Over this coming week, I will slowly and progressively roll this out on the Chrome store, beginning with 1% of users.

**Comment by hiddenruins** [comment]
Congrats on the huge release.

I had switched to the vimium-c fork some time ago. I forgot, but I think it had to do with it working on pages like new tab, chrome store.

Looks like it's time to give vimium v2.0 a try.

**Comment by philc** [comment]
@waynehoover yes, I plan to after the Chrome rollout progresses, although I expect some Firefox-specific issues. While I developed v2.0 mostly using Firefox, I do my daily browsing with Chrome and have caught many bugs while using v2.0 it casually. Firefox hasn't gotten this same testing. It would be helpful if those using Firefox for daily browsing could switch to v2.0 to surface any critical bugs encountered in daily usage.

**Comment by stevium** [comment]
@philc I tried to load it in Firefox using `about:debugging` , but it fails with: 
```
Extension is invalid
Reading manifest: Error processing background: Value must either: contain the required "page" property, contain the required "scripts" property, or not contain an unexpected "type" property
```
I'm using `Nightly 120.0a1` with `extensions.manifestV3.enabled` and `extensions.backgroundServiceWorker.enabled`

**Comment by philc** [comment]
This has been rolled out to 100% of Chrome users. I've just now published it to the Mozilla addons site. Unlike the Chrome store, the Firefox addons site has no partial rollout feature, so fasten your seatbelts Firefox users! 😬

**Comment by philc** [comment]
Alright: Vimium 2.0 is fully rolled out to Chrome and Firefox users!

The Firefox installation experience is a regression compared to manifest V2, unfortunately, due to the way permissions are currently handled in Firefox. See the discussion in #4348.
