### ISSUE TITLE
'yy' Yank URL not working in Chrome

### ISSUE THREAD

**Issue by Baggydawg** [philc/vimium#4318]
**Description**

This has been an issue for the last year or so; I've been unable to yank the current tab's URL using 'yy'.

The UI shows correctly, making me think the link has been grabbed – however, it never works.

I've tried remapping to other keybindings: no luck.

I've also removed the extension and tried reinstalling: again, no luck.

**To Reproduce**

Literally just tap 'yy' or whatever binding is set to 'copyCurrentUrl'.

**Browser and Vimium version**

Chrome Version: 117.0.5938.92 (Official Build) (arm64) 

Vimium Version: 1.67.7

**Comment by simojo** [comment]
Using `yy` works as expected for me with:

* Chromium 109.0.5414.119
* Vimium Version: 1.67.7

so more than likely it's a chrome specific issue, given that we have the same version of vimium.

**Comment by philc** [comment]
Tobias, can you go to chrome://extensions, click on Details for Vimium, then click on "Site settings", and review whether the Clipboard permission is set to "Allow"?

**Comment by Baggydawg** [comment]
philc that worked!!!!!!!! thank you so much dude!!!!!!!!!!
