### ISSUE TITLE
Bookmarklets not working after upgrading vimium to 2.0.1 from 1.67.7

### ISSUE THREAD

**Issue by evanhackett** [philc/vimium#4329]
After upgrading the extension from 1.67.7 to 2.0.1, executing bookmarklets results in an error:

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Either the 'unsafe-inline' keyword, a hash ('sha256-8A9dGbzGLmv6YVPmnRg+Gb9PD+2+28AjtFwl8TgxqDE='), or a nonce ('nonce-...') is required to enable inline execution.

injectUserScript @ dom_utils.js:654
```

**To Reproduce**

Simply execute any bookmarklet using the bookmark search feature.

**Browser and Vimium version**

For my Browser I am using Brave version 1.58.135. The issue is present on Vimium 2.0.1, but version 1.67.7 did not have this issue.

**Comment by philc** [comment]
Confirmed. This also reproduces on Chrome, but not Firefox. I'll work on a fix.
