### ISSUE TITLE
"args is not defined" in tab_operations.js when executing bookmarklet

### ISSUE THREAD

**Issue by joobus** [philc/vimium#4334]
**Describe the bug**

When executing a bookmarklet I am getting the error:
```
Uncaught (in promise) ReferenceError: args is not defined
    at openUrlInCurrentTab (tab_operations.js:36:7)
    at main.js:667:36
    at async utils.js:378:24
```

[Link to offending line](https://github.com/philc/vimium/blob/master/background_scripts/tab_operations.js#L36).  Possibly you meant `scriptingArgs.world = "MAIN"`?

I'm not sure if this is related to [this](https://github.com/philc/vimium/issues/4331).  I checked the site's content policy and it didn't seem restrictive.

**To Reproduce**

1. Go to URL 'https://www.zerohedge.com/geopolitical/israel-gives-11-million-gazans-24-hours-evacuate-northern-strip-hamas-says-ignore'
2. Execute this bookmarklet via the vomnibar:
```javascript
javascript:window.location.href="https://talk.zerohedge.com/embed/stream?asset_url="+window.location.href;
```

![args-not-defined-vimium](https://github.com/philc/vimium/assets/24600223/5afcd70b-2168-4be7-93b0-4a0d690cc2a4)

**Browser and Vimium version**

Brave: 1.60.89 Chromium: 118.0.5993.70 (Official Build) beta (64-bit) 

Vimium: 2.0.2

**Comment by joobus** [comment]
Possibly you meant `scriptingArgs.world = "MAIN"` [here](https://github.com/philc/vimium/blob/master/background_scripts/tab_operations.js#L36)?

**Comment by philc** [comment]
That is embarrassing 😠. Thank you @joobus for the detailed report. I'll push this out as a new version tonight.
