### ISSUE TITLE
Escape when using github search bar doesn't exit

### ISSUE THREAD

**Issue by migui3230** [philc/vimium#4336]
When I try to use Vimium on Git Hub while using the search bar, I press the Escape button and it doesn't exit from the search menu. 

I tried using passNextKey but that didn't work, but im not sure if I passed it in correctly to the options

**Comment by jamescooke** [comment]
I'm also struggling to get the escape button to exit from text areas after updating - there seem to be some times that the HTML text element "keeps focus" and escape can't release it. I've had to use tab to move focus to a non-text area to get out of "insert mode".

Does that tally with what you've found?

**Comment by jamescooke** [comment]
(For example after posting this comment - I then couldn't leave the comment box with Escape 😬 )

**Comment by jamescooke** [comment]
Seems like this is the error that happens before Escape stops working for me in Firefox:

`TypeError: this.passNextKeyKeys.includes is not a function`

```js
    handleKeyEvent moz-extension://c090af27-74b4-4570-840c-6d09f6076e70/content_scripts/mode_insert.js:41
    bubbleEvent moz-extension://c090af27-74b4-4570-840c-6d09f6076e70/lib/handler_stack.js:63
    installListeners moz-extension://c090af27-74b4-4570-840c-6d09f6076e70/content_scripts/vimium_frontend.js:299
    installListener moz-extension://c090af27-74b4-4570-840c-6d09f6076e70/content_scripts/vimium_frontend.js:281
    forTrusted moz-extension://c090af27-74b4-4570-840c-6d09f6076e70/lib/utils.js:6
```

**Comment by tranquochoan** [comment]
Oh I'm having the same issue, only for me it happens on and off, I notice that it happens when I have a private window opened.

**Comment by jamescooke** [comment]
Yes - happens intermittently for me too. My theory is that it happen on tabs I keep open during my work day... When I switch back to them, Escape has stopped working.

**Comment by renodubois** [comment]
+1, this has been happening to me also. It's intermittent, but I get that same error + stack trace that was posted above. I've only noticed it on GitHub so far.

**Comment by philc** [comment]
Thanks everyone. I've addressed the stack trace that @jamescooke provided (thanks!) and I believe I've fixed the overall issue. I'll make a new release tonight. Let me know if you see this again in Vimium 2.0.5+.
