### ISSUE TITLE
With recent Vimium update ```f``` key no longer pulls up links to type

### ISSUE THREAD

**Issue by austinwilcox** [philc/vimium#4338]
Navigate to any URL and when I click ```f``` instead of seeing all the beautiful tabs that I can navigate to, I get nothing. When looking into the console I get this on page load, and I assume it has something to do with vimium not loading correctly.

```
Error handling response: SyntaxError: Unexpected token 'o', "[object Obj"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.handleUpdateFromChromeStorage (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/lib/settings.js:113:28)
    at chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/lib/settings.js:62:20
```

**Browser and Vimium version**
Brave Browser Version 117.1.58.137
Vimium 1.67.7

Not sure the best way to remedy the issue, if I need to side load the browser extension I am fine doing that. I just tested the new version in Chrome and ```f``` works fine, so it seems like there is some sort of interference with the brave browser.

**Comment by austinwilcox** [comment]
To add to this, ```o``` does not pull up the url bar in the UI.

**Comment by austinwilcox** [comment]
edit* removed comment about ```o``` not working. That was a mistake on my end that disabled that.

**Comment by philc** [comment]
hey @austinwilcox, Vimium 2.0 is partially rolled out to many Chrome users, but not all. The format of Vimium's settings has changed in v2.0 which could be related to the exception you've listed.

Do you have Vimium installed on multiple computers? If so, has one of them been upgraded to Vimium 2.0 and one still stuck on 1.67.7?

**Comment by austinwilcox** [comment]
@philc Your message provided me the fix! Just by simply uninstalling the plugin and reinstalling it upgraded me to 2.0, and now the beautiful ```f``` key works again. Thank your for the response on here, I will mark this as done.
