### ISSUE TITLE
Collecting link hints fails entirely for page with invalid HTML `area` coordinates

### ISSUE THREAD

**Issue by ChristianHein** [philc/vimium#4342]
**Describe the bug**

Vimium fails to show any link hints on the following website after pressing `f`: [https://nba.uth.tmc.edu/neuroanatomy/index.html](https://nba.uth.tmc.edu/neuroanatomy/index.html).  
I've tested this on both Firefox and Chrome.

**To Reproduce**

1. Go to URL "[https://nba.uth.tmc.edu/neuroanatomy/index.html](https://nba.uth.tmc.edu/neuroanatomy/index.html)".
2. Press `f`.
3. Notice the corner pop-up: "Collecting hints..."
4. Even after the pop-up goes away, nothing more happens. The expected behavior is that we should now see link hints on all valid links on the page.

**Developer Console Output**
- Firefox:  
   ```TypeError: Document.elementsFromPoint: Argument 1 is not a finite floating-point value. link_hints.js:1179:14```
- Chrome:  
   ```Uncaught (in promise) TypeError: Failed to execute 'elementsFromPoint' on 'Document': The provided double value is non-finite. at Object.getElementFromPoint (link_hints.js:1236:14)```

**MWE**
I've created a minimal, working example based on the above webpage which exhibits the same behavior:
```
<!DOCTYPE html>
<html>
  <body>
    <img src="https://nba.uth.tmc.edu/neuroanatomy/Assets/images/nao_logo_narrow_MMS.gif" width="955" height="100" usemap="#Map">
    <map name="Map">
      <area shape="poly" coords="5,5" href="#">
    </map>
    <a href="https://nba.uth.tmc.edu/neuroanatomy/index.html">Home
```
I believe the error occurs because the page uses invalid coordinates for the `area` tag. The HTML standard says there must be at least 3 coordinate pairs, but this example only uses one pair. Simply adding one more coordinate pair fixes the problem and link hints are properly shown (e.g. `coords="5,5,10,10"`).

**Browser and Vimium version**
- Firefox 118.0.1, Vimium 1.67.7, OS: Linux 6.5.5-arch1-1 <span>#</span>1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 22:55:13 +0000
- Chrome 117.0.5938.132 (Official Build) (64-bit), Vimium 2.0.3, OS: Linux

**Comment by philc** [comment]
Hmm, tricky. Thanks for the bug report @ChristianHein. The fix for this will go out to the store tomorrow.
