### ISSUE TITLE
Vimium stopped working after update

### ISSUE THREAD

**Issue by MarcoPolo-PasTonMolo** [philc/vimium#4345]
**Describe the bug**
Vimium stopped worknig completely after the update. I can get it to temporarily work if I reinstall it and it only works on new tabs, or on old tabs but only if I refresh them, stops worknig shortly after or after I close and open the browser. Also noticed that it starts working any time I change any of its settings from the chrome://extensions page. 

Include a clear bug description.

**To Reproduce**

1. Re/Install vimium
2. Should be working correctly
3. Close and open browser again
4. Stops working
5. Go to chrome://extensions
6. Under vimium's inspect views I see: service worker(inactive) but the icon is blue
7. Disable and enable vimium using the "On" property on that page

9. Vimium is working
10. Close and Reopen browser 
11. Doesn't work again

Include a screenshot if applicable.

**Browser and Vimium version**

If you're using Chrome, include the Chrome and OS version found at chrome://version. Also include
the Vimium version found at chrome://extensions.
Brave | 1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Linux

Vimium: Version 2.0.4

**Comment by philc** [comment]
Hi @MarcoPolo-PasTonMolo, are there any errors printed in the service worker javascript Console? You can open this by clicking on Vimium's service worker link in `chrome://extensions`.

Second, are there any errors printed in the javascript console for a regular webpage? E.g. navigate to google.com and select View > Developer > JavaScript Console. In particular, try this on a tab which was previously working with Vimium but has stopped working.

Finally, do you have Vimium installed in Chrome on multiple devices?

**Comment by MarcoPolo-PasTonMolo** [comment]
No errors in the console of regular pages, don't have vimium on chrome on another device, only on firefox on the same one but that one is not updated.

As for the service worker I cannot open it while it's inactive but if I activate it (by disabling and enabling vimium in the extensions page) then there are no errors.

**Comment by philc** [comment]
@MarcoPolo-PasTonMolo I don't have any further ideas without logging info.

One thing you can try is to open the error console for Vimium's service worker and leave that window open while you browse. Once Vimium stopes working for you, check the service worker error console window to see if an error was logged.

**Comment by MarcoPolo-PasTonMolo** [comment]
Nothing gets logged. It stopped working but he console is empty

**Comment by MarcoPolo-PasTonMolo** [comment]
I think now it works fine. Maybe I needed to restart my computer for it to get working I'm not sure to be honest

**Comment by philc** [comment]
Which browser are you using?

**Comment by MarcoPolo-PasTonMolo** [comment]
Brave, I provided the version in the issue description.
Some other errors:
![image](https://github.com/philc/vimium/assets/79863493/6275b85f-07ec-4e0f-b121-3d623f8adc95)
I got the same error for:
lib/settings.js:0
background_scripts/exclusions.js:0
background_scripts/tab_operations.js:0
background_scripts/marks.js:0
background_scripts/main.js:0

**Comment by MarcoPolo-PasTonMolo** [comment]
New error:
![image](https://github.com/philc/vimium/assets/79863493/7d7425fd-3a63-4d33-921d-53f02d79b39b)

**Comment by MarcoPolo-PasTonMolo** [comment]
@philc Do these erros help? ^

**Comment by MarcoPolo-PasTonMolo** [comment]
@philc This still happens, do the errors I provided help? I'm still using the same versions I mentioned in this issue

**Comment by gdh1995** [comment]
Your last snapshot showed Vimium's background worker process had been dead.

As far as I know, old versions of Chrome has some strict limitations on extension's background worker process, while Chrome 110+ relaxes them and then Vimium "may keep alive" if only Vimium's background worker is "triggered" in a recent 30 seconds.

However, maybe 30 seconds are too short ? And, I'm not sure whether Vimium can keep alive if all used is only `LinkHints` in a recent 30 seconds.
