### ISSUE TITLE
When installing Vimium for Firefox, users must manually enable the "all hosts" permission

### ISSUE THREAD

**Issue by philc** [philc/vimium#4348]
I wanted to poll the community of Vimium Firefox users about what they think of the installation UX now that Vimium uses Manifest v3, and the ideas below for improving it.

From my testing, installing Vimium on Firefox from the Mozilla Addons store installs it without the "all hosts" permission enabled (see screenshot below). I didn't see a popup prompting about this on installation.

Until this happens, Vimium will only run on sites for which the user explicitly enables it, which they can do by right clicking on the Vimium extension icon in the toolbar and selecting "always allow for <example-site.com>".

Enabling Vimium for all sites is buried in the browser settings:

1. Go to about:addons
2. Click on Vimium
3. Switch to the Permissions tab
4. Enable "Access your data for all websites" under Optional permissions.

This seems like a really obscure process for the average user to overcome just to get Vimium working as it's supposed to. Note that this same opt-in all hosts permissions UX will affect many other Firefox extensions which require content scripts on every site (like ad blockers), as they migrate to Manifest V3.

This is a new UX imposed on manifest V3 extensions; manifest v2 extensions get the all hosts permission automatically granted if it's listed in their extension's manifest. It's discussed here: ([one](https://discourse.mozilla.org/t/permissions-not-being-asked-upon-add-on-installation/110570/5), [two](https://blog.mozilla.org/addons/2022/11/17/unified-extensions-button-and-how-to-handle-permissions-in-manifest-v3/)).

Here are some ideas for improving the situation for Firefox users:

1. Add warnings in the Vimium README, and on the store page, that the user has to manually enable this permission, and provide instructions for how to do it.
2. When the Vimium icon is left-clicked, and Vimium hasn't been enabled for all hosts, explain the need for the all hosts permission, and show a button which requests this permission. [1]
3. Show some kind of a popup within the current page the user is browsing. For this to be possible, the user has to have previously manually approved Vimium on that domain, so that its content scripts are loaded.

[1] This seems to be possible with the [permissions.request()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request) API. A notable restriction here is that the API call must happen in response to a user action.

<img width="695" alt="image" src="https://github.com/philc/vimium/assets/8598/6a2f1b81-a617-4231-8de9-4ecbc7595781">

**Comment by tobbez** [comment]
The **second idea** would provide most value.

The toolbar icon already gets a notification dot (![image](https://github.com/philc/vimium/assets/9334/e6fb1d13-9d1c-4957-9bb2-b8bc527155da)), nudging users to click it (especially if they notice that the extension doesn't appear to work).

While convenient, the popup wouldn't even need a button for enabling the permission to be useful. Just instructions for finding and enabling the permission would be a significant improvement over the current text (which is fairly useless for this situation):

![image](https://github.com/philc/vimium/assets/9334/20ef52e1-c4ed-467f-8504-8b4755a3d879)

The **first idea** won't help existing (upgrading) users at all. Adding a warning on the store page will likely help some new users. As for the README, I think users would be likely to skip past it and go directly to the issue tracker when trying to figure out why the extension doesn't work.

The **third idea** seems to provide limited value, especially if the second one is implemented. If a user enabled the extension for a single site, they likely did it by clicking the toolbar icon, in which case they should have been presented with the means to enable the all sites permission already.

Also, in the initial state after installation/upgrade the extension is not allowed to run on any sites, and in the case of a new installation, the extension cannot even be given permission to run on the current site (the extension store).

**Comment by wadeduvall** [comment]
I support ideas 1 and 2. I spend several minutes searching the internet (issue is too new to really be indexed by search engines) and even looking at the Vimium config (I'm coming from Chrome where it warns you during install about the permissions). Adding a bit of text to the vimium warning will go a LONG way, and will prevent users from having to dig through Github issues in order to find what they need.

**Comment by philc** [comment]
Thanks for the discussion everyone. I've added some UI to the action popup, and I'll update the README and Firefox installation pages to give users a heads up that they need to enable this permission.
