### ISSUE TITLE
After activating Find Mode, each key press yields "Uncaught TypeError: node.checkVisibility is not a function"

### ISSUE THREAD

**Issue by chilip3pp3r** [philc/vimium#4356]
**Describe the bug**

After activating Find Mode, each key press yields "Uncaught TypeError: node.checkVisibility is not a function". After pressing `return` and then `n`, the HUD reports "No query to find."

On loading any page, there is also error "Unchecked runtime.lastError: The message port closed before a response was received."

**To Reproduce**

1. Activate Find Mode with `/`
2. Input any string
3. Press `return`

<img width="1840" alt="Screen Shot 2023-11-02 at 08 43 24" src="https://github.com/philc/vimium/assets/34785619/40cf96d0-4476-420c-a7b7-b78d568fdeaf">

**Browser and Vimium version**

Chrome Version 104.0.5112.101 (Official Build) (arm64)
macOS Version 12.2.1 (Build 21D62)
Vimium 2.0.4

**Comment by philc** [comment]
Hey @chilip3pp3r, nice catch -- thanks for filing this. You can resolve this bug by upgrading your Chrome version to 105 or later. I'll increase Vimium's minimum required version of Chrome so that other users don't run into this.
