### ISSUE TITLE
prevent pinned tabs from being closed

### ISSUE THREAD

**Issue by GianniGi** [philc/vimium#4359]
**Describe the bug**

pinned tabs normally can't be closed with ctrl-w

vimium should respect this behaviour

pinned tabs should stay open also when you press "x"

**To Reproduce**

pin a tab

press x

the tab closes, while it should stay opened, since ctrl-w doesn't close pinned tabs

**Browser and Vimium version**

vimium 
2.0.4
Last Updated
27 October 2023

Name 	Firefox
Version 	119.0
Build ID 	20231019122658

**Comment by philc** [comment]
Thanks for the bug. This is fixed in #4365.
