### ISSUE TITLE
Handling of >3 character TLDs

### ISSUE THREAD

**Issue by leoheitmannruiz** [philc/vimium#4362]
It seems that domains with TLDs longer than 3 characters are not recognized as domains and in turn are searched for, instead of being opened directly. This issue seems related #3268.

An obvious solution, I thought, was to decide whether the query was a domain or a search query using a simple regex. It seems Vimium is already doing something similar? Searching for example.zfc (any three characters after the dot), Vimium tries to directly open the query, as if it were a valid domain.

I like this behavior, as it is not often that the query is not a domain. Can this behavior please be expanded to <14? 13 characters seems to be the longest TLD (https://longest.domains/).

**Comment by philc** [comment]
Thanks for your input @leoheitmannruiz. I'm closing this in favor of #3268; we can continue the discussion there.
