### ISSUE TITLE
Link hints don't work with the "Review changes" button on GitHub's PR view

### ISSUE THREAD

**Issue by eramdam** [philc/vimium#4369]
**Describe the bug**

Basically what the title says 😅 Vimium's link hints seem to detect the button just fine but when triggered, nothing happens. This used to work before (I want to say a few weeks ago?) so either a Vimium update broke it or GitHub changed something such that it breaks Vimium in that situation.

**To Reproduce**

![CleanShot 2023-11-22 at 12 06 08](https://github.com/philc/vimium/assets/1409924/67cae718-2e1f-4b58-a221-84b62926ea77)

**Browser and Vimium version**

Firefox 119.0.1 on MacOS 14.0
Vimium 2.0.6

Settings file -> [vimium-options.json](https://github.com/philc/vimium/files/13443981/vimium-options.json)

**Comment by joshblack** [comment]
Hi there! 👋 Just wanted to chime in on the GitHub side for this issue. I've been trying to track down why this might be happening and thankfully it seems like the review dialog ends up opening now but the buttons within it are not showing up as links 🤔 

This may potentially be related to the usage of the [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API) for this component under-the-hood (just a guess). Tried to re-create this over in: https://codepen.io/joshblack/full/NWJKRBr with a simpler version to see if it's the case.

**Comment by eramdam** [comment]
> Hi there! 👋 Just wanted to chime in on the GitHub side for this issue. I've been trying to track down why this might be happening and thankfully it seems like the review dialog ends up opening now but the buttons within it are not showing up as links 🤔
> 
> This may potentially be related to the usage of the [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API) for this component under-the-hood (just a guess). Tried to re-create this over in: [codepen.io/joshblack/full/NWJKRBr](https://codepen.io/joshblack/full/NWJKRBr) with a simpler version to see if it's the case.

So I tried and if I enable `dom.element.popover.enabled` in Firefox, it works just fine so I guess the issue might be with whatever polyfill you're using for the Popover API on Firefox? (the flag I turned on isn't the default (yet?))

**Comment by pksjce** [comment]
Hi @eramdam - Taking over from @joshblack - Do you see this working fine in Chrome browser? The feature has been present there since quite some time and I see vimium not working as expected inside the popover.

**Comment by eramdam** [comment]
> Hi @eramdam - Taking over from @joshblack - Do you see this working fine in Chrome browser? The feature has been present there since quite some time and I see vimium not working as expected inside the popover.

I indeed see the same issue in Firefox (vimium not picking up links inside the popover)

**Comment by keithamus** [comment]
This may be due to this line: https://github.com/oddbird/popover-polyfill/blob/84089e83ed0ea2d89d5f7cb0648f1249b602e754/src/popover.ts#L306?

**Comment by keithamus** [comment]
Hey friends, I've deployed a fix on GitHub.com, this should no longer be an issue.

**Comment by eramdam** [comment]
> Hey friends, I've deployed a fix on GitHub.com, this should no longer be an issue.

Can confirm, thank you 🙏
