### ISSUE TITLE
Can Vimium be used to control other Chrome Extensions?

### ISSUE THREAD

**Issue by aaphid** [philc/vimium#4377]
Is it possible to use Vimium to activate and use Chrome Extensions?

**Comment by philc** [comment]
No, without modification. It is technically for two extensions to communicate with each other at runtime via message passing. But:

* Vimium would need to be hard-coded with a list of specific extensions that it can work with
* the extensions themselves would need to be modified
* there would need to be some agreed-upon command-invocation protocol

I consider this out of the scope of Vimium.
