### ISSUE TITLE
Fix description when `f` and `Shift + f` are pressed.

### ISSUE THREAD

**Issue by Phantola** [philc/vimium#4378]
**Describe the bug**
First of all, I apologize my poor english.

I use a mac, ventura.
I lightly use vimium for navigate a site.

I think I found a little fix point,

when I press just `f` this message is represented. 
but actually open page with new tab
<img width="273" alt="image" src="https://github.com/philc/vimium/assets/75708535/30b73651-25f8-466e-959e-b158f69f7717">

on the other hand,
`Shift + f` represented this message is represented.
<img width="267" alt="image" src="https://github.com/philc/vimium/assets/75708535/ecbea1c8-52cd-4dac-93ab-819bf6dc5cfb">
but actually open page with same tab

I think the description of the two commands above is reversed.

**To Reproduce**

See a description when press `f`, and `Shift + f` in right down area

1. Press `f`  
<img width="273" alt="image" src="https://github.com/philc/vimium/assets/75708535/30b73651-25f8-466e-959e-b158f69f7717">   

2. Press `Shift + f`
<img width="267" alt="image" src="https://github.com/philc/vimium/assets/75708535/ecbea1c8-52cd-4dac-93ab-819bf6dc5cfb">   

**Browser and Vimium version**

Chrome :  119.0.6045.159 (공식 빌드) (arm64) 
Vimium : 2.0.5

**Comment by philc** [comment]
When you press `f`, if you type the letter without using shift, it should open in the same tab. Are you continuing to hold down shift as you type the letter? 

Possibly related: #4364.

**Comment by Phantola** [comment]
@philc Thanks your advice. I think this issue is related.
I confused. Thanks a lot. Have a nice dev!
