### ISSUE TITLE
How to globally disable command duplication

### ISSUE THREAD

**Issue by GeekDuanLian** [philc/vimium#4386]
I wish to send the original numeric key.
I've tried `unmapAll`, `unmap 1` but neither works.

**Comment by gdh1995** [comment]
you may use exclusion rules and add `1234567890` into `pass keys`

**Comment by GeekDuanLian** [comment]
![image](https://github.com/philc/vimium/assets/6257434/fd583d42-6785-4e9a-8e17-d08c57ecccbe)
@gdh1995 Thanks, this works!
