### ISSUE TITLE
Custom searches do not work since version 2.0.4

### ISSUE THREAD

**Issue by christ4k** [philc/vimium#4394]
When opening vomnibar, I type the text that I have configured to work with a custom search, and it does not work as expected. The initial text stays as text and the search rule does not fire up.

For example, the rule:
`@dhub https://hub.docker.com/search?q=%s`

When I type:
`@dhub jellyfin`
and press enter, it searches with my default search engine the query above.

I downgraded to 1.67.7 from the version history of mozilla add-ons and it worked as it worked so many years that I use it.

**Comment by astr0n0mer** [comment]
Hey @christ4k
I believe you missed a colon `:` after your custom search keyword

This rule searches your query on Docker hub as you'd expect
`@dhub: https://hub.docker.com/search?q=%s`

Tested on Vimium v2.0.5

**Comment by christ4k** [comment]
You're right! I don't know how this happened. Some of my custom searches had the colon and some not...
