### ISSUE TITLE
[feature] Allow Custom key mappings for full screen.

### ISSUE THREAD

**Issue by iamashwin99** [philc/vimium#4400]
Since the `F` key is captured in vimium, most video players that expect a F key down to make full screen, cant be controlled anyway. A solution for this is to enable a custom key mapping that allows the fullscreen command from within vimium.

**Comment by fish1968** [comment]
I guess a proper way is to first enter insert mode by pressing `i`, and then press `f` to enter full screen. Insert mode could be canceled by `esc` key.
I am actually a vimium-c user, but I think this [issue](https://github.com/gdh1995/vimium-c/issues/1066) of `vimium-c` might be helpful.

**Comment by philc** [comment]
A similar solution is to bind the `passNextKey` command, and use that instead of insert mode. Then, ESC needn't be pressed once in fullscreen mode.
