### ISSUE TITLE
[feature request] do not close tab on ctrl-w

### ISSUE THREAD

**Issue by gmankab** [philc/vimium#4405]
so, vim deletes backwards on ctrl-w by default, but browsers closes tab on ctrl-w

i have a vim habit, so i usually accedentaly close tabs

please bind delete backwards on ctrl-w, or disable this sourcut at all so then tabs will not close

**Comment by matenestor** [comment]
> vim deletes backwards on ctrl-w by default

Vim doesn't delete backwards. It is a fist part for window commands. You probably have some Vim distribution or custom bindings.

**Comment by gmankab** [comment]
@matenestor, vi, vim, and neovim all deletes backwards on ctrl-w without any distrobutions or custom bindings

**Comment by gmankab** [comment]
solution - https://github.com/gdh1995/vimium-c/issues/1075#issuecomment-1892672009

**Comment by matenestor** [comment]
> @matenestor, vi, vim, and neovim all deletes backwards on ctrl-w without any distrobutions or custom bindings

Aha, in `input` mode they do. I was trying it in `normal` mode. Sorry for the confusion
