### ISSUE TITLE
Having a shortcut to collapse all the html collapsable elements at once. 

### ISSUE THREAD

**Issue by kirubeltadesse** [philc/vimium#4412]
If you are viewing the pull request file on GitHub and you want to quickly glance over the files that are changed. This will come so handy. Please let me know if you already have a solution for this. I have been looking everywhere for it.

**Comment by philc** [comment]
I don't follow the workflow you're looking for -- could you elaborate?

And by collapsible element on a github PR page, do you mean the down arrow in the upper left corner of this image?
<img width="426" alt="image" src="https://github.com/philc/vimium/assets/8598/e93b5771-2813-4cef-9aaf-1288d508e26b">

If that's what you mean, and you want a way to click on all such buttons on the page, then an approach I've seen for this is to write a snippet of javascript which finds all such buttons on the page, and simulates a click on them. You can store that snippet as a bookmarklet and run it using the vomnibar (or use something like Chrome's bookmark toolbar).

**Comment by kirubeltadesse** [comment]
@philc Yes, you are right. That was what I was referring too. Thank you for your feedback. I will look into it.
