### ISSUE TITLE
Vomnibar does not treat URLs with missing // correctly

### ISSUE THREAD

**Issue by leoheitmannruiz** [philc/vimium#4415]
**Describe the bug**

URLs, which are missing a // are not recognized as URLs and in turned are searched for, instead of being opened directly. The URL spec says this formatting should be tolerated, if I understand correctly. See https://url.spec.whatwg.org/#special-scheme-missing-following-solidus.

**To Reproduce**

1. Open the vomnibar
2. Enter https:example.com

**Browser and Vimium version**

2.0.6

**Comment by gdh1995** [comment]
When will such URLs happen? I mean, if `:` has been typed, why not type a further `//` ?
