### ISSUE TITLE
Pin/Unpin not responsive on Firefox

### ISSUE THREAD

**Issue by brandon-toner** [philc/vimium#4423]
**Describe the bug**

The pin/unpin toggle does not appear to work on Firefox.

**To Reproduce**

1. Navigate to tab (pinned, or unpinned)
2. Trigger shortcut (<a-p>) (option-p)
3. No effect

Note: I also tried mapping to an available key binding to test alternate bindings. 

Include a screenshot if applicable.

**Browser and Vimium version**

Vimium: Version 2.0.6
Firefox: 123.0 (64-bit)
MacOS 14.2 (23C64)

**Comment by philc** [comment]
I think the actual issue here is that option-p is not being detected by Vimium on Mac due to #3197. You can confirm this by rebinding it to another key and see if that works:

`map p togglePinTab`
