### ISSUE TITLE
Can I configure my vimium?

### ISSUE THREAD

**Issue by end-cycle** [philc/vimium#4440]
I want to configure my vimium so that I can't leave the current webpage immediately when I accidentally double-click the f key.

For example, when I click on f, I want the matching link to be used without the f key as an identifier or only with the f key as a double identifier.

Is there any support for this function now, and if not, can it be implemented?

**Comment by philg-dev** [comment]
You can remove the `f` character from the list of characters that will appear in the automatically generated link-hints. That way there will never be a link hint that contains `f`. That way double tapping the `f` key will simply open and close the link-hint overlay again.

![image](https://github.com/philc/vimium/assets/6079229/aa4e77d5-d050-49b6-acce-163bc173e69a)

**Comment by end-cycle** [comment]
> You can remove the `f` character from the list of characters that will appear in the automatically generated link-hints. That way there will never be a link hint that contains `f`. That way double tapping the `f` key will simply open and close the link-hint overlay again.
> 
> ![image](https://private-user-images.githubusercontent.com/6079229/317581749-aa4e77d5-d050-49b6-acce-163bc173e69a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTcyMTcsIm5iZiI6MTcxMTU5NjkxNywicGF0aCI6Ii82MDc5MjI5LzMxNzU4MTc0OS1hYTRlNzdkNS1kMDUwLTQ5YjYtYWNjZS0xNjNiYzE3M2U2OWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMDMzNTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTdhNDQxOTMzYjVmZGNlYzFhZTU0YmJjMTdhZjc0NTA4NWNlMjJlOTFlNjIzYTI3OThmMDdiNzJhMDE3Nzc5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zXfzJLmFPbLW58dLSaePBNeCLCrTT6sSTK7xRHN4Tyc)
> 
> > (Disclaimer: I've noticed that the author of the add-on has a similar name as I do. I'm not the same person - I'm a very new user of Vimium and was just looking into things.)

Thank you for replay,it solve my probleam.😊
