### ISSUE TITLE
Hint overlays do not appear on GitHub Enterprise

### ISSUE THREAD

**Issue by bent0b0x** [philc/vimium#4446]
**Describe the bug**

Pressing `f` to trigger link/button hints does not yield any visible overlays on GitHub Enterprise. This is probably due to https://github.com/philc/vimium/commit/412cc37621a578ee260925f31e0722539af33f39.   

**To Reproduce**

1. Go to any github enterprise page
2. Press `f`

I would expect the overlays to appear so that I can press character keys to open links, but they do not appear.

**Browser and Vimium version**
Vimium: 2.1.0
Chrome: Version 123.0.6312.87 (Official Build) (arm64)

**Comment by philc** [comment]
I'm surprised -- I'm not sure what would be so different about github enterprise vs. the regular site that would break link hints.

Unfortunately, I don't have access to any github enterprise instances. Could someone with access to it take a closer look?

**Comment by bent0b0x** [comment]
It looks like the hint markers are all being rendered, but they are not visible due to a css rule that gets included in GHE (at least the version my org is on, which is `GitHub Enterprise Server 3.9.4`):

```
@supports not selector([popover]:open)
[popover]:not(.\:open) {
    display: none;
}
```

My `css` chops are a bit stale, but it looks like this is ultimately saying "hide all popover elements unless they are explicitly open"?

I think adding `display: 'block'` [here](https://github.com/philc/vimium/blob/9780226bf472eae93f49ee9d8984e6f2f12668ed/content_scripts/link_hints.js#L418-L425) would fix the issue, I can PR that to discuss

**Comment by changmin-ahn** [comment]
Same for `GitHub Enterprise Server 3.9.10` 😢

**Comment by roachsinai** [comment]
> I'm surprised -- I'm not sure what would be so different about github enterprise vs. the regular site that would break link hints.
> 
> Unfortunately, I don't have access to any github enterprise instances. Could someone with access to one take a closer look?

No. I cannot use `/` to search a word in regular site now. Type `/` and after type target word, vimium show it found matches, but can't jump to it by press Enter.

**Comment by bent0b0x** [comment]
FYI, here's a temporary config-level fix until a new version of Vimium is released w/ a patch

https://github.com/philc/vimium/pull/4451#issuecomment-2034349648

**Comment by roachsinai** [comment]
Thanks for quick reply!

**Comment by philc** [comment]
v2.1.2 includes this fix and I've submitted it to the stores today.
