### ISSUE TITLE
createTab position=end tries to open URL "position=end"

### ISSUE THREAD

**Issue by kinclma1** [philc/vimium#4450]
**Describe the bug**

In the new Vimium version in Google Chrome, mapping <key mapping> createTab position=end <links> now opens a new tab with the address "position=end" in addition to opening the URLs that follow. Vimium still respects that the tabs should be at the end but keeps it in the list of URLs to open.

**To Reproduce**

1. Add a mapping: map <key> createTab position=end <link1> [<link2>...]
2. Save options
3. use the mapped key
4. Observe that the first newly open tab is probably a search for the term position=end in the default search engine

![2024-03-30-005248_857x220_scrot](https://github.com/philc/vimium/assets/2377824/3447ad11-02f1-498c-85e2-9dc7179778e4)

**Browser and Vimium version**

Google Chrome	123.0.6312.86
Vimium 2.1.0

**Comment by philc** [comment]
Tricky. Great find @kinclma1. This fix will go out with the next version.

**Comment by kinclma1** [comment]
Thank you!

**Comment by wenfangdu** [comment]
@philc When will the next version come out? I use `t` quite frequently, the current behavior is quite annoying.

**Comment by philc** [comment]
v2.1.2 includes this fix and I've submitted it to the stores today.
