### ISSUE TITLE
[feature request]: Want a vertical tabs, or tabs search to find tabs easily.

### ISSUE THREAD

**Issue by tausiq2003** [philc/vimium#4456]
Feature request: Need a vertical tabs or tabs search to find tab in tabs easily.

Description: While searching for a particular tab in a bunch of tabs, which is very overwhelming, we need a feature to search or list the tabs so that we can search within it or move using the `j` or `k` keys, or search using `/` and navigate using `n` or `N`, to find a tab easily.

Solution proposed: Never thought of one, just wrote this immediately. But can we make a mode to search for tabs? Let's discuss below.

Video(e.g. I wanted to find a Love with Lua GitHub that I opened, about the problem I am facing):

https://github.com/philc/vimium/assets/80088029/42a4cadd-2367-407d-b198-5c0bdfb9a3e2

**Comment by philc** [comment]
Hey @tausiq2003, is the Vimium command `Vomnibar.activateTabSelection` (bound by default to T) insufficient?

**Comment by tausiq2003** [comment]
cool, never knew this, closing this issue, apologies for bothering you.
