### ISSUE TITLE
[Question] What does 1-9 do in Vimium normal mode?

### ISSUE THREAD

**Issue by wenfangdu** [philc/vimium#4459]
When watching a YouTube video with Vimium normal mode, pressing 0 can jump to the beginning of a video, pressing 1-9 does nothing but blocking the native 1-9 functions of YouTube. So, what exactly does 1-9 do in Vimium normal mode?

If 1-9 indeed does nothing, can we pass it to the page?

**Comment by wenfangdu** [comment]
@YunfangHou If 1-9 do nothing, I'd prefer them being passed to the page.

**Comment by CrispyFlowe** [comment]
It does. Actually you can tell vimium to perform action multiple time, like vim. I usually use `10t`, which open 10 new google tabs for me. 

It works for almost all vimium hotkeys. Other combination works well to, like `99j` move page down 99 times, `10P` paste ten times, `99H`/`99L` move in history 99 times. If you want you can press `i` to enter insert mode, then type 0-9 in youtube

**Comment by wenfangdu** [comment]
@CrispyFlowe Wow, didn't know Vimium supports this before, closing.
