### ISSUE TITLE
Able to scroll with keybindings

### ISSUE THREAD

**Issue by HakaishinShwet** [philc/vimium#4466]
As we have many scroll bars in many webpages so it would be nice to be able to scroll left and right with keybindings.

**Comment by VincentBarkman** [comment]
Hello,

When you press the "?" key, you will see the following navigation shortcuts:

- `h`: Scroll left
- `l`: Scroll right
- `j`: Scroll down
- `k`: Scroll up

This allows you to move up and down with `k` and `j`, and left and right with `h` and `l`.

Best regards,  
Vincent A. Barkman
