### ISSUE TITLE
letters on tabs and/or move to a specific tab with shortcut

### ISSUE THREAD

**Issue by marconetto** [philc/vimium#4494]
I'm looking for alternatives to move to specific tabs faster. I understand we have in vimium: Vomnibar.activateTabSelection (bound by default to T).

I'm looking for one of these two options:
a) be able to press f (or other key) and have letters on  the browser tabs (not sure if that would be feasible), similar to letters on links. I think here, what would be perhaps be feasible is to add letters on the title of the pages. (similar to: <https://chromewebstore.google.com/detail/chrome-show-tab-numbers/pflnpcinjbcfefgbejjfanemlgcfjbna>)
b) have a short cut to move to specific tab: something like g1,g2,...

**Comment by UncleSnail** [comment]
**Option B already exists.** The default keyboard shortcuts to do this are alt+1-9. So to go to your first tab, press alt+1, or second with alt+2, etc. I hope this helps and solves your issue. You are right that perhaps this functionality could be made more clear. You can also go to first and last tabs with g0 and g$.
For option a, I believe the only way to possibly achieve this would be like you say, to alter the titles of the page, which does not stand out very well and could be a difficult feature to set up and maintain. The way that links are being marked cannot be done outside of the page.

**Comment by marconetto** [comment]
thanks @UncleSnail  for the clarification!

**Comment by UncleSnail** [comment]
> thanks @UncleSnail for the clarification!

You're welcome. If this solves the problem, you can close this issue.
