### ISSUE TITLE
Find not scrolling to plaintext results inside div with scrollbar.

### ISSUE THREAD

**Issue by Jack-023** [philc/vimium#4498]
**Describe the bug**

When using find and hitting enter. Vimium is correctly finding results in the page but won't scroll the div down so that they are visible. The search will scroll as expected to results that are links.
**To Reproduce**

1. Go to URL [GDScript Reference](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html)
2. Search the page for the string "for" ie `/for`
3. Hit `n` several times. You will see that while it scrolls through the results there will be no feedback at all until it reaches part of a link at which point the page will scroll in the expected way.

Include a screenshot if applicable.

**Browser and Vimium version**
Firefox	127.0
Vimium	2.1.2

**Comment by UncleSnail** [comment]
Good finding, I am experiencing the same thing on that website. It appears to be an issue with the overflow element being positioned with `position: absolute;`. If I remove the absolute positioning the scrolling works correctly. Someone should definitely look into this and see if we can find a fix.

**Comment by Jack-023** [comment]
Thanks for your response. Good find on the style that seems to cause the issue. Would be nice to have this fixed but in the meantime I have been able to band-aid the problem by adding a stylus rule to set that property to static on the site.

**Comment by souvlakeeb** [comment]
Are you still experiencing this? I can't reproduce.

Firefox 128.0.3 \
Vimium 2.1.2

**Comment by Jack-023** [comment]
Nope, appears to be fixed.
