### ISSUE TITLE
Vimium in Firefox scrolls down OK with `j`, but `k` tabs between links instead of scrolling up

### ISSUE THREAD

**Issue by jamescooke** [philc/vimium#4510]
**Describe the bug**

It looks like `j` is working OK for scrolling down, but confusingly, pressing `k` doesn't scroll up. Instead it does a behaviour similar to `<tab>` - it steps through clickable links. Depending where those links are on the page, pressing `k` _can_ cause the page to hop / scroll a bit up or down.

**To Reproduce**

1. Go to URL: https://news.ycombinator.com/newsfaq.html 👈🏻 a nice plain text page.
2. Use `j` to scroll down a page length.
3. Press `k` once and the page will hop back up to the top and the link in the title will be highlighted:

![Screenshot from 2024-06-29 23-04-18](https://github.com/philc/vimium/assets/781059/54a96ca8-c9c7-4c78-a25d-be21866423b9)

4. Press `k` multiple times to tab through the links, but appears to keep them at the top of the view pane. Using `K` (shift `k`) goes in the reverse direction.

Expected behaviour = pressing `k` should have scrolled the page back up and not highlighted any links.

### Additional failures

* Can't follow any links with `k` shortcuts. Pressing `f` shows the "link codes", but none containing `k` can be followed, pressing `k` starts the tabbing / highlighting of links again 😞 .
* Using `gg` to get the the top of the page and `G` for the bottom both fail - again doing some kind of tabbing through links.

**Browser and Vimium version**

If you're using Firefox, report the Firefox and OS version found at about:support. Also include the
Vimium version found at about:addons.

| Attr | Value |
| --- | --- |
| Firefox version | `126.0.1` |
| Firefox build | `20240526221752` |
| OS version | `Linux 5.15.0-113-generic #123~20.04.1-Ubuntu SMP Wed Jun 12 17:33:13 UTC 2024` |
| Vimium version | `2.1.2` |

Possibly related issue: https://github.com/philc/vimium/issues/4491 👈🏻 because _maybe_ the pressing `k` is highlighting a link and scrolling stops?

**Comment by jamescooke** [comment]
FIXED IT! I'd accidentally turned on Ubuntu's screen reader - who'd have thought that would completely break the functionality of vimium 🤯 .

In case anyone is reading this - you can turn that off in settings:

![Screenshot from 2024-07-01 09-51-32](https://github.com/philc/vimium/assets/781059/793d2f40-d40d-4031-bb6c-0fc02f4765b9)

And the problem is that there's a default shortcut to turn it on: `Alt+Super+S` which I obviously fat-fingered and with a muted computer didn't notice 🤦🏻 .

Thanks for a great vimium plugin - I'd be lost without it 🙏🏻

**Comment by philc** [comment]
Thanks James for documenting the solution. If anyone else encounters the conflict with screen reader, hopefully they'll find this thread.
