### ISSUE TITLE
White block is displayed when using vimium with dark reader 

### ISSUE THREAD

**Issue by Grandkahuna43325** [philc/vimium#4513]
When I use vimium with dark reader I get a big white rectangle. 
I believe that it's the background of the vimium but I couldn't find it's css...

**With dark reader**
![image](https://github.com/philc/vimium/assets/77882915/b2529dcc-3eb5-48e8-ba82-946154a23101)
**Without dark reader**
![image](https://github.com/philc/vimium/assets/77882915/d1138df8-86a2-42c2-8781-976e1585faa1)

PS: I use dracula theme for vimium but the issue is the same without it, and the 'background' is also displayed when I press '/' and it looks like this:
![image](https://github.com/philc/vimium/assets/77882915/23cf0b78-1fa7-46e1-aba0-dba463a30f60)

Browser info:
Thorium	117.0.5938.157
Fedora release 39
vimium 2.1.2
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by Grandkahuna43325** [comment]
Well I can do it on pretty much every website, I just press 'o' and the white background is here. It's on every website that has Dark reader turned on, if I turn it off it works as intended. 
I've reinstalled vimium and dark reader but the issue persists. I believe that all the vimium commands that display something have this 'background', and I have no other issues with dark reader.

**Comment by philc** [comment]
I also use Dark Reader and have no issues. Can you post a screenshot of your Dark Reader settings?

**Comment by Grandkahuna43325** [comment]
it's a fresh install so no custom settings

**Comment by UncleSnail** [comment]
So you don't have any other addons installed besides Vimium and Dark Reader and you still have this problem in Chromium? That's odd. I don't see how you using Fedora or any of its settings should effect this. I am on Wayland and it works, and I know X11 works.
Have you tried clearing your Chrome profile then also not logging in? I'm not sure how they play together, but Thorium might be using some of the same profile files as Chromium, in which might lie the problem.

**Comment by Grandkahuna43325** [comment]
You're right, on firefox it works fine, I'll look around.
sorry for taking so long to respond.
