### ISSUE TITLE
o/O/b/B can't open `file:///` uri

### ISSUE THREAD

**Issue by nuclear06** [philc/vimium#4521]
**Describe the bug**
`o/O/b/B` keys can't open URL using `file:///` URI scheme.

**To Reproduce**

1. browse a random local file so that there is a file:/// history. (or add as bookmark)
2. use `o/O/b/B` to open that URI.

**Browser and Vimium version**

Google Chrome	122.0.6261.94 (Official Build) (64-bit) 
Revision	880dbf29479c6152d5e4f08dfd3a96b30f919e56-refs/branch-heads/6261@{# 960}
OS	Linux
Vimium version: 2.1.2

**Comment by philg-dev** [comment]
For security reasons, webextensions can not create tabs from privileged URLs. This includes `file://` URLs, as documented here:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create#url

So this is not a feature that can be implemented in Vimium.
