### ISSUE TITLE
[FF] How to open `about:about` using only vimium?

### ISSUE THREAD

**Issue by mrdgo** [philc/vimium#4540]
**Describe the bug**

I don't want to use the urlbar - I disabled it in my userChrome, because `about:about` and sub-pages are the only reason I ever use it. Vomnibar is king. However, I would love to access `about:x` pages using vimium. I tried `map a createTab about:about`, but it doesn't cut it. How do I? If that is currently impossible, I hereby request it as a feature :)

**Browser and Vimium version**

OS: Arch linux
FF version: 130.0
Vimium version: 2.1.2

**Comment by UncleSnail** [comment]
I thought this would be possible by making a bookmark of the tab, but it appears that Vimium also cannot open that bookmark. This may be a bug or it may be impossible for addons to open special pages, I'm not sure.

However, I do know that it is impossible for addons to control special pages, so even if it is possible, once you are there, Vimium will not work on that page, so it will not be possible to navigate away from there with Vimium. Thus, theoretically, if you disable your address bar etc, this could lead to a "soft stuck" state. Just a note.

**Comment by mrdgo** [comment]
Thanks for your reply!

Also not sure, I open an issue over at firefox.

About control: yes sure, we have to use the mouse on special pages.

**Comment by mrdgo** [comment]
Apparently, it isn't and won't ever be possible. The only solution is to create a bookmark for `about:about` and then using the bookmark menu `Ctrl b` and open the page from there. We don't need the url-bar, but can't do it in vimium either.
