### ISSUE TITLE
Suggestion: shortcut for focusing URL bar / omnibar

### ISSUE THREAD

**Issue by nicksergeant** [philc/vimium#477]
In Pentadactyl, this is essentially "o". This would be a great feature, IMO. I switched from Pentadactyl -> Chrome + Vimium and this is the only thing I'm still missing.

**Comment by rrsahutwo** [comment]
People for moving have a lot of factors that have to be handled or done in the whole procedure of moving of their house. The activities and processes include product packaging of products in a right way, arranging for automobile, safe running and unloading and even unpacking and putting in order, etc. Doing all these projects needs a perfect initiatives and a lot of effort that does not only consume your useful time, but also create you tired physically as well as mentally. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
All these challenging projects are very frustrating that can create you indulge. Relocating your company, house can also be a more problematic when you have fear of harm of your valuables. Overall, the finish moving procedure is very, stressful, stress-full and frustrating procedure. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
During their moving needs, everyone wants to be totally exempt from all the problems and boring projects. The best remedy of such kind of problems is to take help of expert packers movers Bangalore . We come up with the expert assistance in this Professional.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
EXPERT Packers is a name of a major moving and product packaging organization that brings a finish remedy of the moving problems mentioned above. We are expert movers and packers in Bangalore and have a whole line remedy with our moving features. If you want to create sure that moving procedure including all the processes doesn't become a stressful, distressing, troublesome and frustrating procedure for you all, you must seek the services of our complete moving solutions. We are a group of expert packers & movers in Bangalore . 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by lindhe** [comment]
I'm coming from VimFX, and was used to this. I think it _would_ be great to have a better way of focusing the URL bar than the built in Ctrl+L or <kbd>F6</kbd>. Being able to choose <kbd>o</kbd> instead of the defualt shortcuts would be easier to reach and/or fewer buttons to press.

I would very much like to have this feature. If you are not going to implement it yourself, would a PR be welcome?

**Comment by mrmr1993** [comment]
> If you are not going to implement it yourself, would a PR be welcome?

We haven't implemented this because we can't: there are no APIs that let us do it. If you do find a way, please submit a PR, but I'm not optimistic.

**Comment by rococode** [comment]
Would it be possible to optionally copy the current URL into the <kbd>o</kbd>-key bar? I'm also coming from VimFX, and the main usage of the <kbd>o</kbd> for me was to make quick adjustments to the URL.

For example if I were on reddit and wanted to go from `reddit.com/r/all` to `reddit.com/r/gifs` then I could just hit <kbd>o</kbd><kbd>Ctrl</kbd><kbd>Backspace</kbd> and type gifs. With an empty <kbd>o</kbd> bar it's a little longer to do that.

**Comment by martin-braun** [comment]
I like the extension, but I'm not a huge fan of the vomnibar, I think the omnibar is fine as it is, besides the fact that we cannot focus it with "o".
