### ISSUE TITLE
Use a link-hints-like UI to select a frame to focus

### ISSUE THREAD

**Issue by icx-jonv** [philc/vimium#494]
The biggest problem I have with Vimium is Chrome's insistence on picking the incorrect frame to place focus.  I really like the tags used for links, would it be possible to add tags for frames?  For instance, I press gf (or something else) and tags show up on all of the frames, making it easy to select one that will gain focus.

**Comment by boblehest** [comment]
Example website where this is an issue: http://doc.rust-lang.org/nightly/book/
Would be great if I could focus a frame like this: http://i.imgur.com/x4lenuH.png

**Comment by smblott-github** [comment]
Closing.
Old, and discussed elsewhere,
