### ISSUE TITLE
Disable Vimium on PDFs.

### ISSUE THREAD

**Issue by arbrown** [philc/vimium#501]
I opened up a pdf form with user-fillable text boxes, but when I tried typing in them, vimium captured my keystrokes, and only passed through unmapped keys.  For instance, typing a q in a textbox closed the tab completely.  I think vimium ought to be disabled by default when opening up pdfs, especially pdfs with forms you can type in.  For reference, here is the pdf I opened:

http://publicsafety.utah.gov/dld/documents/DLD6AOnlineApp1-10.pdf

**Comment by smblott-github** [comment]
Closing.
No further action required.
