### ISSUE TITLE
Vimium seems to be disabled on all local files

### ISSUE THREAD

**Issue by nikreiman** [philc/vimium#502]
When using Chrome to browse local files via file:/// , I can't use the navigation or other vimium commands. Is this a limitation of the underlying plugin framework?

**Comment by smanilov** [comment]
The checkbox doesn't seem to be there any more?

**Comment by zmcui** [comment]
@smanilov it is still there on latest chrome

**Comment by vyq** [comment]
1. Go to chrome://extensions/?id=dbepggeogbaibhgnhhndojpepiihcmeb
    1. Alternatively, go to chrome://extensions/
    2. Find `Vimium`
    3. Click `Details`
2. Toggle `Allow access to file URLs`
