### ISSUE TITLE
use the bookmark folder name for search keyword?

### ISSUE THREAD

**Issue by s2marine** [philc/vimium#509]

**Comment by Melkster** [comment]
@philc Why was this closed? Is it implementable? I'd love this feature :)

**Comment by gdh1995** [comment]
@Melkster if you search "`/`" + "some words", then Vimium will search in bookmark folder names. For example, "`/test`" will match bookmark folders whose names start with "test"; "`/test/foo/bar`" will match a bookmark folder / item, if only: its name is "bar" and its parent folder is "foo" and the parent's parent is "test".

**Comment by Melkster** [comment]
@gdh1995 That's awesome, thanks! Maybe this should be mentioned in the help page? :)

**Comment by gdh1995** [comment]
There has been one in https://github.com/philc/vimium/wiki/Tips-and-Tricks#searching-bookmarks-by-folder
