### ISSUE TITLE
How to prevent hint overlap?

### ISSUE THREAD

**Issue by byrongibson** [philc/vimium#512]
Love the addon, thanks!  Only issue I have is on certain social news sites, there's a lot of overlap that makes it impossible to see what the second letter of the font-hint is.  I keep guessing, and guessing wrong.

Example:  http://i.imgur.com/iM2vI.png (see left column, font hints for upvote/downvote arrows)

I tried adding 5px padding and margins to the custom hint CSS, then 15px margins, but no change.  Any suggestions how to fix it?

Thanks!

**Comment by RafaelArgiro** [comment]
Also running into this issue sometimes. Quite annoying. Maybe just add a toggle key (like F2) that toggles the order in which all hint boxes are displayed...

**Comment by philc** [comment]
@RafaelArgiro That feature was added in 2016 (19e1178b). For alphabet hints, typing `space` when the hints are showing will cycle through which one is on top. For filtered hints, it requires using any modifier (e.g. alt-space) because space can otherwise be used to filter down the set of hints.
