### ISSUE TITLE
Consider an alternate css to the Vomnibox, so it feels more like Chrome. 

### ISSUE THREAD

**Issue by philc** [philc/vimium#515]
I like the current dark style for its usability and readability. I'll play with the styles a bit to see if I can maintain the usability and readability while making it feel a little more like Chrome's native UI.

**Comment by CarloDePieri** [comment]
Hi, is there any way to chage the current look back to a darker one? (would an option to choose omnibox theme be interesting?)

**Comment by dexter0195** [comment]
You can theme it editing the css in ~/.config/chromium/[profile]/Extensions/[vimium-externsion]/vomnibar.css
Just remember to backup it as I think it will be overwritten on plugin update.
