### ISSUE TITLE
Should `t` be "open vomnibar" instead of "open new tab"?

### ISSUE THREAD

**Issue by int3** [philc/vimium#521]
It should open vomnibox and launch the selected URI in a new tab. This would match Vimperator's behavior.

**Comment by rajeevksahu** [comment]
Our technical employees at our packaging and movers has got tremendous encounter in providing damage 100 % free transportation of your content. They think the valuables of the customers to be their own valuables and save them from any wear and tear which enables our client to believe in on our packaging and movers without any individual doubt. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
All the components we use while packaging your items are of top great quality which is the reason that your content are packed and moved in the best way according to your demands. Our movers packers Mangalore alternatives are just the way you need them. You can rely on our Mangalore packers and movers alternatives quickly as we have delivered our packaging and movers to a variety of clients already. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
We always provide finish fulfillment to our clients thorough providing fantastic moving alternatives to them after recognizing their variety of moving needs and specifications. Hence if you want your useful items to be transferred securely from one position to another, then you can get in touch with our packaging and movers at once. We assure you that you won’t remorse after selecting our packaging and moving support for your house moving or workplace moving.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
Mysore is one of the beautiful places in Indian. It is well known for its beauty. Every year, lots of Tourist from all across the world visit here. Most of plenty of time lots of company personalities establish their company here. This is regarded as excellent commercial and educational area. Packers and Movers Services in Mysore allows in moving and moving without putting any additional pressure over you.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by smblott-github** [comment]
Closing.
Ship has sailed.
