### ISSUE TITLE
Add a preference to prevent pages from stealing Vimium's focus when they first load

### ISSUE THREAD

**Issue by stetskevych** [philc/vimium#523]
I like to scroll through my tabs using J,K. This works fine, until a tab has a highlighted text area, which the browser starts typing into. Next, I have to press Esc and continue with J,K until i encounter the next highlighted text area.
If wanted to type into a text area, I would select it myself using the f key.
Please fix :)

**Comment by Zamicol** [comment]
Is there an issue open for tabs stealing focus when changing tabs?  

Pages (like Google) can steal focus when changing tabs.

**Comment by smblott-github** [comment]
No, there isn't.  There's only an option to prevent the page stealing the focus when first visiting a page.

I get that what you describe is annoying, but an option to grab back the focus when changing tab could be annoying too.  E.g. you're composing an email, and jump to another tab to grab some info, and when you jump back your email has lost the focus.

Not sure about this, but...  Google doesn't grab the focus for me.  Do you have *instant search* enabled on Google.

**Comment by Zamicol** [comment]
So as a user,  I think I have these tabs:

|----X---|---Y---|---A---|---Z---|----W---|----W---|----W---|----W---|----W---|

But in reality I have these tabs:

|----X---|---Y---|---Evil Steal focus tab---|---Z---|----W---|----W---|----W---|----W---|----W---|

To transverse from Z to Y, I would "shift, j, j, unshift"  Instead, I'm stuck in A. 

Tabs should be prevented from stealing focus until I "unshift", release shift.
