### ISSUE TITLE
Ctrl+Alt+[ behaves like Ctrl+[ with custom keyboard mappings in windows

### ISSUE THREAD

**Issue by sbaumeister** [philc/vimium#526]
I'm using custom keyboard shortcuts on windows, including `Ctrl+Alt+[` or `AltGr+[` for a german umlaut "ü". By activating vimium in chrome this shortcut no longer works. It seems this combo behaves like `Ctrl+[` or the `Esc` key.

**Comment by smblott-github** [comment]
(Old) dup of #1906.
