### ISSUE TITLE
Quick Marks

### ISSUE THREAD

**Issue by kalbasit** [philc/vimium#53]
#Introduction
Quick Marks are like bookmarks but they are manipulated through keyboard shortcuts, for example we can save http://mail.google.com as key M, and after hitting the sequence requesting quick marks and then M, gmail will be opened in the current tab (or in a new tab if requested)

#Functionality
I porpose using the keys *go* (to open in the current tab) and *gn* (to open in a new tab), to save a bookmark, we can either create a new textArea to enter URL using *gs* or save the current page using *gS*, we can also Implement that as commands (like Vimperator) but since this functionality is still to be done, I will simply implement *gs* and *gS* first.

#Data Model
This function will rely heavily on localStorage, the same way settings are saved, but I need to work on that first.

**Comment by rajeevksahu** [comment]
Get up to five quotes from certified movers and packers in Bangalore and select the best accordance to your budget!

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
Whenever we think about moving to some new position, some tensions always come in our mind. One of the biggest annoying factors is to shift that large baggage from your present property to the new one. Shifting and moving is an integral aspect of lifestyle. We have to shift to a new position, not only for fun or change but also to provide a push to our lifestyle. We all need to survive and for better lifestyle effort is really essential.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
Bangalore is an commercial sector. Every year, lots of company bodies shift here to set up their company, and to achieve something better in their lifestyle. In such cases, packers & movers in Bangalore are like the only helping hands for us. They provide their alternatives with an excellent liability. You can believe in them blindly. They are so excellent in their duties that you cannot even imagine. If you are planning for Packing Moving Bangalore then we are here to help you without putting additional pressure on you.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
If you have any doubt about choosing expert help, then let us discuss about it. We need to seek the services of expert not only to show status in society. Actually, we need them. In this active environment, this is really annoying to shift from one position to another. With such hectic schedule, we do not have a chance to shift all large and packed baggage by own.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by Rejlan** [comment]
Hi,

Is it possible to clear quick marks all at once, or access them maybe?

**Comment by smblott-github** [comment]
Not really, @Rejlan.

Global marks are stored in `chrome.storage.sync`, local marks in `localStorage`.

(I think we can close this issue; it's very old.)
