### ISSUE TITLE
Make Vimium work on the New Tab Page

### ISSUE THREAD

**Issue by philc** [philc/vimium#531]
It's possible to provide our own "new tab page". See the developer [docs here](http://code.google.com/chrome/extensions/override.html).

The benefits would be:

* we're reading your keystrokes, so you can switch away from that tab using Vimium's keys
* you can use our vomnibar from a new tab page

There are two questions we'll need to answer:

1. Can we take the [input focus away](http://groups.google.com/a/chromium.org/group/chromium-extensions/browse_thread/thread/54772f1e849942b1/5a68f8f2110fc766) from Chrome's URL box when our new tab page is opened? If we can't, there's not much point.
2. Is it possible to let users enable/disable our new tab integration? If users don't want Vimium to handle their new tab page (e.g. they have another extension they want to use), they should be able to turn it off. From what I can tell, Chrome on Mac doesn't have a UI for this. If two extensions want to handle your new tab page, the last one you install wins, and there's no UI to change that.

**Comment by nikess** [comment]
@smblott-github using that method, omnibar still steals focus?

**Comment by smblott-github** [comment]
No. Works well for me.

**Comment by nikess** [comment]
Hmmm, seems to work for some but not for others.  Thanks. 

On the whole though, still too slow for me - even with a locally served file. New tab needs to be *instant*.

**Comment by rrsahuone** [comment]
After leaving your position, everything will be discussed by Company owner to decide on the selling price and it will be intimated you as well. This is the way how product packaging moving Company works and provides proposes to their customers. Don’t panic as all provides are usually affordable and 100 % safe or effective.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by rrsahuone** [comment]
Sometimes, it becomes hard getting right expert for right job. Although internet service is there to help you but that is not sufficient. You need other factors too like believe in, stability and stability. How can you believe in someone just because his website is outstanding or he is getting outstanding reviews from customers? Reviews can even be written or posted artificially. Is there any middleman who can guarantee about the Company? Here, we come at the front to take the responsibility that your cope is 100 % safe and effective.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers in Delhi">Packers and Movers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by rrsahuone** [comment]
We record you with best Packers movers in Bangalore having outstanding popularity and always getting positive feedback from client. They not only help in moving or shifting but also manage most fragile products with highest appropriate care that are most susceptible to damage. These all individual valuables are handled in most expert style by Company.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers in Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a>

**Comment by rrsahuone** [comment]
If you are looking for some moving solutions, which can help you while moving and shifting, then here we are to help you. We are going to talk about about Packers and Movers Services in Bangalore . Packers and movers are popular now days, whenever we are talking about moving and shifting. This is up to you, which packers and movers company you are going to select while shifting. Here we are going to talk about to select suitable company according to your need.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by bschnabel** [comment]
I know this is a very old issue but by now it seems to be possible, that an extensions can overrite the new tab page and this beeing implemented as an option.

this addon: https://chromewebstore.google.com/detail/lesezeichenleiste/jdbnofccmhefkmjbkkdkfiicjkgofkdh?hl=de

offers this options screen:

![Image](https://github.com/user-attachments/assets/4bad1caf-6ca1-4e4e-9a1f-f1a842441266)

if offers to
- overwrite new tab page with a page created by the applications or a custom page
- focus address bar yes / no

I included the addons page here and that way ctrl+T has same effect as just t in vimium
