### ISSUE TITLE
Allowing Users to Tab Through Link Hints

### ISSUE THREAD

**Issue by DeadDork** [philc/vimium#538]
Hiya,

As far as I can tell, Vimium does not allow users to tab through matched link hints. I've tried tab, left, right, up, down, etc. to no avail.

That said, Vimprobable's link hints do allow users to tab (and shift-tab in reverse) through matched link hints. So, for instance, if you match link "testosterone" and link "test" with hint "test", you can then hit tab to cycle through these two matches. While it's useful for expediting hinting in some cases (e.g. "antidisestablishment" vs "antidisestablishmentism"), it's most useful when the full hint is still ambiguous (e.g. you want "test", but the the link hint falls on "testosterone" first). The latter's a definite PITA, as it forces the user to reverse course and try again with numbers or a mouse.

If I had some time, I would submit the patch myself. But deadlines...

Anyway, thanks in advance!

**Comment by smblott-github** [comment]
This is implemented for filtered hints.
