### ISSUE TITLE
Space out overlapping link hints

### ISSUE THREAD

**Issue by DeadDork** [philc/vimium#540]
Hiya,

This rarely happens outside of a wikipedia reference section. That said, I've noticed that if links are placed too closely together, their respective link hints will overlap to illegibility. It would be nice if link hints could be spaced out at least far enough apart to clearly show the first character of each hint.

Thanks!

**Comment by smblott-github** [comment]
Closing.
The VimFX idea that's floating around is probably more workable.

(Can't find the link right now.)
