### ISSUE TITLE
Shortcut key(s) for "Close Other Tabs" or "Close Tabs to the Right"?

### ISSUE THREAD

**Issue by emallove** [philc/vimium#546]
Is there a shortcut key(s) for "Close Other Tabs" or "Close Tabs to the Right"?

**Comment by kylescousin** [comment]
Has this been implemented yet? 


I can't seem to find it anywhere

**Comment by gdh1995** [comment]
@kylescousin There're 3 **advanced** commands named "closeTabsOnRight", "closeTabsOnLeft" and "closeOtherTabs". You may see them by clicking "Show advanced commands" in the help dialog.

**Comment by kylescousin** [comment]
Wow... Thanks.

Really useful.
