### ISSUE TITLE
The Vomnibar doesn't support custom search engines / smart searches

### ISSUE THREAD

**Issue by johnwchrome** [philc/vimium#553]
after upgrade to 1.32.1, i can use "o" to popup the urlbar, it work well.
but i can not use "o" popup urlbar with search engine.

when i use the urlbar, i can type "search.google.com"(or other search engine keyword),
then type "tab" then i can search something on those search engine,
but when i use "o" to popup the urlbar, i can not type "tab" to use search engine.

sorry, my english is very bad, i hope you will understand, what i want to say.

anyway the new "o" feature is very nice.

thank you.

**Comment by rrsahutwo** [comment]
That is why when we seek the services of motorists, the candidates have to go through the tests and interviews and after getting fulfillment with the motorists skills and experience, we seek the services of them for the perform. After choosing motorists, we take training and necessary instructions to create the perform of moving secure and safe. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
Our expert motorists are committed to take your luggage and you to your location soon enough. You need not take pressure about how your perform would be managed in initiatives and how it would be finished with protection. We are knowledgeable and have already helped countless customers in their moving needs.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
Care India packers value your luggage, cash and so pay a appropriate attention to create it more and more practical and safe. To create you totally exempt from the different aspects of moving, we have a finish group of experts. Packers and loaders are also included in our group to create all the perform done under the flagship of Care India packers. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
Our packers can package your domestic factors like your TV, refrigerators, Coolers, Costly furnishings and other factors that need a great appropriate care while product packaging, running and unloading. If you are in need of the plan features for your costly products, you don’t need to go anywhere else. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
