### ISSUE TITLE
J for nextTab and K for previousTab

### ISSUE THREAD

**Issue by invl** [philc/vimium#554]
I'm very comfortable using Vimium since the first time, except the mapping of J and K.

I think It's natural to press J to go "down" to next tab, and K to go "up" to previous tab.

Also tabs layout may be vertical, J for down and K for up is still a natural way to go.

As some people may argue, J is left, K is right, it's natural too, 

so I raise this post to see if it's common or just me. 

Personally I could just remap them, but I think a good design doesn't make people think.

**Comment by drobati** [comment]
I know this is a really old issue but I figured I would drop this work around for those who also fell this is weird.

```
map J nextTab
map K previousTab
```
