### ISSUE TITLE
Bookmarks and History should be separated

### ISSUE THREAD

**Issue by s2marine** [philc/vimium#558]
When I use the 'o', there is so many items that I can't find the bookmark I want.
Bookmarks and History should be separated.
Like 'b' for Bookmarks and 'h' for History.

**Comment by rajeevksahu** [comment]
The alternatives are not just limited to packaging and moving. Professionals also assemble or disassemble the factors as per your request. We deal with your expensive items as well like projector, TV, laptops, files, printers, FAX devices etc. and many other similar items.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
Movers Packers Bangalore is giving best expert alternatives in your price range. Either you are planning to shift house or office; they are just best choice available close by you. When you will check the accessories or other equipment available for moving, you will rely itself on their alternatives. They are 100 percent secure and efficient to perform with.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
Now moving within town or even to other position has become much easier than it was regarded in past. You just have to have to explain your specifications and variety of options is available with you in your price range. Expert help can create everything stress 100 % free either it is packaging, moving or moving. To handle your moving needs, there is nothing better than expert help.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
The experts are giving most great quality alternatives and handling all your moving needs wisely. We help you in choosing best expert organizations so that you can be sure that your personal items are in secure hands only. All of our listed movers and packers are well equipped and well handled to deal with all of your moving needs.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>
