### ISSUE TITLE
No response to commands until newly opened tab is initialized/loaded

### ISSUE THREAD

**Issue by rzetterberg** [philc/vimium#559]
After I updated to version 1.33 I noticed a change in the response in the plugin after you open a new tab. 

Before when you opened a new tab with F [link slug], you could quickly open more tabs instantaneously.  However after the update it seems that the new tab must initialize/load (takes about 500 ms to 1000 ms) before the plugin even responds to new commands.

This makes the workflow of opening a lot of links in new tabs very crippling when there is a delay in command response.

**Comment by smblott-github** [comment]
Closing.
Out of date.
