### ISSUE TITLE
Factor in a bookmark's folder name in the vomnibar

### ISSUE THREAD

**Issue by benhamill** [philc/vimium#571]
I don't know how hard this might be, but I just occured to me that it would be wicked-cool if, after hitting `b` to bring up the bookmark-focused-vomnibar, it would be aware of bookmark folders. So that if I had these bookmarks:

```
Bookmarks
├── comics
│   ├── Penny Arcade
│   ├── Johnny Wander
│   └── Questionable Content
├── code
│   ├── Github
│   ├── Rails docs
│   └── rubydoc.org
└── Twitter
```

It would be awesome if `b` would know that 'comics/' should only suggest from the comics folder and that 'i' would suggest Github, Rails docs and Twitter, but 'cod/i' would suggest only Github and Rails docs. That sounds like it might be a big departure from the current vomnibar code, so I'm just throwing this out there. I'm thinking about it the way that fuzzyfinder.vim does its matching.

**Comment by mtsagias** [comment]
+1

**Comment by smblott-github** [comment]
@mtsagias.  Open the vomnibar in bookmark mode (`b` or `B`), type `/`.

**Comment by mtsagias** [comment]
@smblott-github That's awesome !!! Thanks a lot.

**Comment by benhamill** [comment]
:heart:
