### ISSUE TITLE
Vimium On Locally Hosted Pages?

### ISSUE THREAD

**Issue by benhamill** [philc/vimium#572]
I have noticed that if I visit a local file, either by opening an html file with ctrl-o or being served by a webserver on localhost, vimium doesn't seem to load. I'm not sure of the reason and I have the "Allow access to file URLs " box checked in the extension section of Chrome's settings. Bug? Feature request? User error?

**Comment by tconn89** [comment]
I have `localhost:8080` excluded in vimium options, but it still works on localhost.  I tried `.*localhost` too

**Comment by smblott-github** [comment]
@tconn89.  Exclusion rules are just Javascript regular expressions (with one small exception) which are matched against _the whole URL_ (so, the scheme and all).

The exception is that `*` is replaced with `.*`.

If you edit the exclusion rules via the Vimium popup, then the rule turns red if it does not match the current page, so you can see whether your rule is working.
