### ISSUE TITLE
Javascript bookmarklets variables are not scoped at Window

### ISSUE THREAD

**Issue by s2marine** [philc/vimium#575]
For example, this bookmarklet

``` javascript
javascript: var hello = 'world'
```

It works when I click it from the bookmark bar.
But when I use the `b`, variable is still undefined.

**Comment by rrsahutwo** [comment]
We are one of the most well-known moving companies in Indian significant places such as Bangalore , Bangalore , Bangalore , Bangalore , Bangalore , Bangalore , Bangalore , Bangalore , Bangalore , Bangalore , Bangalore , and Bangalore and so on. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
We provide efficient moving alternatives to our clients. When you are in need of packers, loaders and movers to transportation your family items or workplace items, you need not think more about this, you just need to get in touch with experts to meet your moving needs.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
The first factor that creates us the first priority for our clients for the moving needs is our affordable expenses. We consider the value of the cash what our clients pay us and that is why we repay it with our efficient, secure and affordable moving alternatives. The reason behind our affordable expenses is that we have our own group of the experts for the different actions Expert moving. The expert packers, loaders, and drivers are always prepared to help our clients in executing all the required duties. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
The best packers and movers in Bangalore comprehend the value of your items and so we package them with appropriate wrappers and containers ensuring their protection. The protection of the items also depends on how expert the packers and loaders are and how careful they are. That is why we have a qualified, knowledgeable, accountable and devoted employees for packaging and running.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
