### ISSUE TITLE
Support for opening vim as an external editor for textareas

### ISSUE THREAD

**Issue by markstos** [philc/vimium#58]
Allow users to edit textareas with their desktop vim seems like a natural fit for this extension. 

The code is already there to re-use for this in the TextAid extension, as well as the "vrome" extension, also on Github. 

Note that as of today "vrome" has an insecure security model for their implementation, because they allow you to pass an arbitrary shell command that over HTTP  that will be run to launch the editor. I have notified the author about that. TextAid addresses the issue simply by hardcoding an editor in the source of the tiny "web server" that is used. 

Thanks!

**Comment by Hi-Angel** [comment]
@markstos I am reading [TextAid extension description](https://addons.mozilla.org/en-US/firefox/addon/textaid/) and I don't see anything related to launching external editor. How do you use it?

**Comment by markstos** [comment]
@Hi-Angel 16 years ago when I opened the issue, TextAid referred to a different extension. But search for Firefox external editor extensions and there some others now. I'm not current using any of them.

Some examples:

https://github.com/jlebon/textern
https://addons.mozilla.org/en-US/firefox/addon/external-editor/
