### ISSUE TITLE
Excluding apps.facebook.com/?foo=bar&bar=baz doesn't work as it should

### ISSUE THREAD

**Issue by emallove** [philc/vimium#589]
I'm stuck trying to get Vimium to exclude this URL:

  `http://apps.facebook.com/ea_scrabble_closed/?fb_source=bookmark_favorites&ref=bookmarks&count=0&fb_bmpos=5_0`

This is with the following  regular expression patterns added to `Excluded URLs`:
`
    http*://apps.facebook.com/*
    *apps.facebook.com/*
`

**Comment by smblott-github** [comment]
Closing.
Assume resolved.
