### ISSUE TITLE
wish: reverse J and K for tab navigation

### ISSUE THREAD

**Issue by markstos** [philc/vimium#59]
Because J is left of K, I expected that J would go to the tab to the left of the current one. The opposite behavior happens. 

The documentation is not specific here, referring to "previous" and "next" instead of "left" and "right". The documentation should be clarified in either case. 

Unrelated, I love that hinting allows me to jump to form inputs as well as links. Thanks!

**Comment by bupd** [comment]
How can I add this as custom rule. 

Since I use vertical tabs. pressing J should move one tab down which is to the right. and pressing K should move one tab up which is in normal tabs moving to the left.

Wish this would be possible.
