### ISSUE TITLE
Jump to the next header (h1, h2) using a shortcut

### ISSUE THREAD

**Issue by abbiekressner** [philc/vimium#595]
Is there a way to jump to the next header on a page?  For example, I am reading a blog index page, and I want to jump to the next entry.  Can I program a shortcut to jump to the next `<h1>`, `<h2>`, `<h3>`, etc. element?

**Comment by fenuks** [comment]
I also think it would be very useful option to have, e.g. to skim through long wikipedia articles. Vim has <kbd>]]</kbd> to jump to new section, but it is used for something different in vimium. Please reconsider opening this issue. :)
