### ISSUE TITLE
Current selection wiped out when a vomnibar is opened

### ISSUE THREAD

**Issue by mdegat01** [philc/vimium#599]
Opening the vomnibar switches focus to a new element on the page so any selection you had is gone.  This poses a problem with the "b" vomnibar, specifically with bookmarklets, many bookmarklets pick up the selection from the current page and operate on it.  By eliminating the ability to select many bookmarklets won't work with Vimium (which is really a shame because having it autocomplete bookmarklets available based on the function you are looking for and then execute them is excellent).

Since the vomnibar is an input on the page and you have to focus on the vomnibar to submit there is no way the selection can be maintained during entry.  So I think that leaves two options: have a new keystroke for submit that tells the vomnibar to wait for a selection then eval the bookmarklet (alt/cmd+enter? ctrl+enter? something with right-arrow key?), or attempt to save the selection during the b entry and then re-select it before evalling the bookmarklet.

The first one should be relatively easy by having the eval fire in a listener for the onselect event but it is clunkier, users must learn a new button and are probably going to have to reselect text a few times before they get used to it.  The second one would probably surprise people the first time it happened but it seems more intuitive and seemless.  This post http://webcloud.se/log/Selecting-text-with-JavaScript/ and this one http://www.webdeveloper.com/forum/showthread.php?t=73493 lead me to believe it's possible but it definitely looks like a PITA.

Of course there could be other solutions as well but there are a lot of bookmarklets out there that use this so it would be a shame if users had to use their mouse for those ones.

**Comment by mrmr1993** [comment]
This is fixed in master.
