### ISSUE TITLE
List and Run Apps in the search box

### ISSUE THREAD

**Issue by mdegat01** [philc/vimium#600]
Currently apps are not accessible from any of the searches, you have to open the new tab page and click on them to open them.  Some of them are basically bookmarks so those are no problem but a lot are not.  Apps and extensions can list out all the installed apps and extensions and launch other ones if they make use of the management api (http://code.google.com/chrome/extensions/management.html).  It would be nice if apps were included in the searches, the most logical one to me is the bookmark searching vomnibox but the "o" box would work fine as well.

It would be really nice if you could open extensions too, if say the options page or the popover appeared as items you could launch since that would eliminate having to use the mouse for that as well.  I can't figure out if that's possible though, it doesn't seem to be in the management doc.

**Comment by Ridermansb** [comment]
Any progress on this?
