### ISSUE TITLE
Show linkhints for content in iframes

### ISSUE THREAD

**Issue by philc** [philc/vimium#602]
The keypoint website is a good example -- the login form is an iframe, and linkhints do not show for the login boxes.

[https://www.keypointcu.com](https://www.keypointcu.com/)

**Comment by jaekyeom** [comment]
Is there any update on this?

**Comment by mrmr1993** [comment]
I'm working on it (albeit slowly, I'm quite busy at work as of late). I hope to get properly moving with this when Steve is back.

If it's of any interest, my plan is:
* make `LinkHints` code more friendly and orthogonal (so we can call parts of it in frames without needing the whole mode)
  - #1761 is the start of this
* add the ability to update hints when presented with new links (so hints can be shown incrementally as frames report them)
  - we need to ensure that, when we update the hints, to add links, existing hints will only change by having a suffix added (ie. `a` -> `ab` or `aab`, not `a` -> `bb`).
* move the mode to the top frame only, and have other frames enter a 'helper' mode
  - communicating between frames using a `CustomEvent` seems like the easiest, least-brittle way to get only the hints we want (ie. only query visible frames).
  - rendering the hints in the top frame keeps the UI in step and helps with consistent positioning, so I plan to do this too.

All of these are relatively simple, so long as everyone agrees on this implementation. If I get some free time at the weekend I'll try to write and push a full working version.

**Comment by tsim0** [comment]
Any update on this? Google reCAPTCHA doesn't work because of this too.

**Comment by smblott-github** [comment]
It should be fixed in the next release (see #2048), @tsim0.  If anybody'd be willing to take that for a spin (it's in `master`) and provide feedback, then that'd be appreciated.

Closing.
