### ISSUE TITLE
Bookmark search doesn't appear to factor in recency strongly enough

### ISSUE THREAD

**Issue by philc** [philc/vimium#607]
Perhaps it's related to bookmarklets. A friend (Harry) just showed me that his instapaper bookmarklet always comes up second in his bookmark search results, even if he just accessed it 2 seconds ago.

**Comment by smblott-github** [comment]
Closing.  We should **not** do this.

Bookmarks are things we use again and again.  If we factored in recency, then the stuff you type to get a particular bookmark would change from time to time.  That's bad.

The bookmark vomnibar should not depend on recency.
