### ISSUE TITLE
Add option to delete tab and focus left/right adjacent tab.

### ISSUE THREAD

**Issue by haesken** [philc/vimium#608]
Currently when a key mapped to `removeTab` is pressed, the tab is closed and the last active tab is focused.
I find this very unpredictable because I don't try to remember the order I opened tabs.

I would love to have options to delete a tab and focus the tab to the left or right of it.

Example:
`x`: Delete tab and focus last active tab.
`c-x`: Delete tab and focus the tab to the immediate left.
`a-x`: Delete tab and focus the tab to the immediate right.

Forgive me if this is already implemented, I searched and could not find anything similar except for the number prepend functionality.

**Comment by Thiana** [comment]
Since there appears to be no way to map a single key to multiple commands (ie, 'removeTab previousTab' or 'xgT') could you please reconsider adding commands to delete the current tab and move left/right? Thanks.
