### ISSUE TITLE
Allow selecting of arbitrary text on the page (visual mode)

### ISSUE THREAD

**Issue by ilya** [philc/vimium#61]
from the gallery page:
<snip>
the biggest problem is that HOW TO SELECT.
Sometime we select a text, sometimes a link.
After selecting we do a lot to the selected, copy & paste, search it in a search engine lists, send it by gmail, and so on.
We really need the select function.
</snip>

**Comment by zhangchiqing** [comment]
+1

**Comment by smblott-github** [comment]
@zhangchiqing Visual mode is implemented in `master`, and a beta version will be in the next release.

(I think we can close this issue now.)

**Comment by zhangchiqing** [comment]
Awesome! Thanks @smblott-github +1

**Comment by chowie** [comment]
+42

**Comment by Zenadix** [comment]
+1 Can't wait to try out this feature!

**Comment by Sydney-o9** [comment]
+1

**Comment by vicariousgreg** [comment]
+1

**Comment by milushov** [comment]
omg, it's awesome, thanks!

**Comment by lukecampbell** [comment]
:+1:

**Comment by perglr** [comment]
+1

**Comment by rajeevksahu** [comment]
By all these factors you definitely got some concept, that how personalized ways we used to provide your delicate items. All the large components are transported without any damage and bothering others. Now you don’t have to disturb your visitors to come and help you.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
As you already have more appropriate choice to select. But one most essential factor, what you have to analyze is the list of your specifications. You have to discover out your specifications and then get in touch with to some close by and authorized packers and movers organizations to help you.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
EXPERT Packers is a leading movers that is best known for reliability, royalty, transparency in the efficient moving alternatives and affordable expenses. Experienced packers movers Nagpur at the company provide whole line remedy of moving throughout the nation. The significant places like as Bangalore , Bangalore , Bangalore , Bangalore , Bangalore , Nagpur, Bangalore and others are within reach of the movers. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
We have a huge system of the expert who are geared up to help clients in their moving specifications. Whether you like to go to the short place or the remotest one, you need not get stressed considering the issues what generally come at plenty of duration of managing the projects or on the way. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by IstiCusi** [comment]
Thanks a lot for that great plugin -- like it very much ! A text cursor to move to text for copying would
be a plus -- but the / search way is working as well. Cheers and kind regards, Stephan

**Comment by vlain** [comment]
+1

**Comment by githubutilities** [comment]
+1, waiting for a life-saving visual mode.

**Comment by smblott-github** [comment]
@githubutilities ... See the [wiki](https://github.com/philc/vimium/wiki/Visual-Mode).

**Comment by githubutilities** [comment]
thanks @smblott-github , but in caret mode, the cursor does not go down as the page scrolled. I think it would be better for cursor to move as the page scrolled.

**Comment by sesas** [comment]
@Catincan is the bounty still on?  I can't get that link to load.  And can I add more to the bounty?

**Comment by greenSnot** [comment]
+1

**Comment by szebrowski** [comment]
I dream for the visual mode to be more like AceJump: https://www.youtube.com/watch?v=8cgy8ITtsJE

**Comment by rancherobeans** [comment]
Leaving this for people who skip to the end. It exists and works well: https://github.com/philc/vimium/wiki/Visual-Mode
