### ISSUE TITLE
Make entries in the vomnibar clickable

### ISSUE THREAD

**Issue by UncleBill** [philc/vimium#615]
I like Vimium very much!
I mapped the keys only under my left hand ( **QWERTASDFGBVC** ) for link hint
so that i could use my left hand for link hinting,and,my right hand holding on the mouse for something else.I like using Vimium this way.
But when I want to open a bookmark ,I should hint **B** , text some key words ,and then move one of my hands to hint **ENTER**.
That makes me feel uncomfortable.
If you could let the matched bookmark items clickable ,it Vimium be more easy and fun to use! :-)

**Comment by smblott-github** [comment]
> Somewhat related, but clicking on the page behind the vomnibar while the vomnibar is being shown should hide the vomnibar, as it does chrome's omnibar.

This is already implemented.

But clicking on a vomnibar entry is still missing.  Help still wanted.

**Comment by smblott-github** [comment]
See #2260.
