### ISSUE TITLE
Shortcut to save the webpage?

### ISSUE THREAD

**Issue by santosh** [philc/vimium#616]
This is the feature I really miss in Vimium. I can press `t` to open a new tab, press `r` to reload the tab, press`x` to close the tab. But we can't press `s` to save the tab.

Can we simulate Chrome's `CTRL+S` _(Save)_ shortcut to Vimium? And then map it to `s`?

**Comment by rajeevksahu** [comment]
When you think of moving from one position to another, you are worried about which automobile will be appropriate for your requirement? How will you handle to packaging tasks? How will you be able to fill these items in the vehicle? How will you reload the items by your own in the position where all the people around you are new? 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
The worry of damage of items during the trip creates you upset months before you have to shift. But now it is needless to worry about all them as we handle your each and every process very comfortably. You just have to get in touch with our experts. We will strategy and handle your moving projects. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
Thane packers and movers will go through your need and recommend you the most appropriate automobile according to your need. Then our expert packers will package your items in the appropriate containers and wrappers considering the nature of the items. Professional packers comprehend how to package the different items appropriately ensuring their protection. Packers 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
Packers use wood made containers also for the protection of the items. Our experts fill, get rid of and rearrange your excellent in your new position very carefully therefore, you need indulge in the projects.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>
