### ISSUE TITLE
Deprecate/remove the custom CSS for link hints feature

### ISSUE THREAD

**Issue by philc** [philc/vimium#636]
This is an advanced option which allows you to override the CSS styling of the linkhints.

I can't remember why we added it, but it's pretty unintuitive and currently semi-broken since we restyled the linkhints (see #626). What are some current compelling use cases for this feature?

**Comment by smblott-github** [comment]
> I propose we disable this (but leave the code and preference in place) in the next-next release and see what kind of feedback we get.

We could leave everything in place, and just remove the entry from the options page...  And see what people say.  That way, those who are married to the idea will still be using their custom CSS.

(And we place a *heads-up* in the release notes.)

**Comment by philc** [comment]
PR #3346 disabled this feature. I closed that with this comment:

For now, I don't want to deal with removing something existing people might be using, and I think hiding it for new users isn't a great option: we still have the code complexity -- we're just reducing the UI complexity.

A more robust way to evaluate deprecating features is to implement some basic analytics collection and have some stats/counters on how many people are using each feature. If only X% of the population is using a given feature, then we can more cleanly debate its deprecation.
