### ISSUE TITLE
Make "f" cancel link hints

### ISSUE THREAD

**Issue by ghost** [philc/vimium#638]
After pressing 'f' to be able to navigate/select a link to follow, it would be nice if 'f' wasn't a choice, in case you want to start over, or in case you accidentally hit it twice. Just a suggestion.

**Comment by afilp** [comment]
@philc

May I also vote in favor to this suggestion?

1. I also often hit "f" twice.
2. It is a more natural finger movement to cancel the hints by just pressing the same button again "f". I find that it strains my little finger to try to reach the ESC button in my laptop. 

All we request is that we keep the "f ESC" logic, while also disabling "f f" from being a valid link hint AND make it behave as "f ESC" instead.

Would you please reconsider this?

Thanks.

**Comment by smblott-github** [comment]
This is [what is implemented](https://github.com/philc/vimium/issues/638#issuecomment-9639421).

Just remove `f` from your hint characters on the options page.

**Comment by afilp** [comment]
You are right, sorry I didn't get it at first. It is simple now.
