### ISSUE TITLE
Public messagelistener for enabling and disabling vimium temporarily

### ISSUE THREAD

**Issue by deadcyclo** [philc/vimium#643]
Could you please implement a public message listener (chrome.extension.onMessageExternal.addListener) for enabling and disabling temporarily (Like pressing i and esc). As of now vimium does not play nicely with other extensions, but simply grabs the keypresses it wants and doesn't allow anybody else to use them. By implementing a public way of disabling like this, other extensions could disable vimium temporarily to be able to perform similar functions.

At the moment I'm creating an extension that has a function similar to vimiums follow link function, so I need access to those keys which basically means I have to fork vimium to include the functionality described above, but it would be so much nicer to have it default in vimium. 

Don't let vimium be the neighborhood bully that doesn't play nice with any of the other extensions on the block. ;-)

**Comment by smblott-github** [comment]
Closing.
No progress.
