### ISSUE TITLE
Feature Request: Hide Mouse Icon if not moving

### ISSUE THREAD

**Issue by k0pernikus** [philc/vimium#662]
Due to vimium I barely use the mouse to navigate and scroll. This is fine.

Yet alas I often misplace the mouse icon somewhere on the page where it just bugs me.

So it would be rad if the mouse icon would just disappear automagically if the user does not use it at the moment. And reappear if the user starts using it.

**Comment by smblott-github** [comment]
Closing.
We tried implementing a cursor hider and it proved unreliable.
