### ISSUE TITLE
Feature Request: Implement faster movement with the curly braces?

### ISSUE THREAD

**Issue by Goles** [philc/vimium#666]
Has someone thought of implementing faster movement in the website by using the curly braces like in vim?

Maybe moving through blocks of text or something ?

What do you guys think ?

**Comment by philg-dev** [comment]
@wleoncio nice necro of an issue that's been inactive for almost 13 years.

In caret mode on Chromium based browsers it should already be possible to move by paragraph with `{` and `}`. This `granularity` is unfortunately not supported in Firefox based browsers. See #4633 for some more details and other related insights on the topic.

Feel free to add some thoughts on the not-so-dead-yet issues instead.
