### ISSUE TITLE
Reload all tabs

### ISSUE THREAD

**Issue by djv** [philc/vimium#674]
It would be nice to have a 'reload all tabs' functionality like in Firefox. Chrome doesn't have that built-in and I don't feel like installing extensions for that.

**Comment by smblott-github** [comment]
What about adding a `count` prefix to `reload`.  Then `99r` would reload all tabs.

(However, there does seem to be a lack of interest in this.)

**Comment by Mehradzie** [comment]
I can clarify `99r` does not work. I have tried other numbers as well. I must say I was very excited by it as it is as VIM as it gets and would be very clever.
I honestly think this is a great feature. Say in the scenario that you need to close Firefox down for an update or something and when it comes back up, you gotta wait for every single page to reload when you jump in. 
Would be deeply appreciated if you could add such feature. ( For the sake of valentines day at least 😛  )
