### ISSUE TITLE
default search engine configuration for vomnibar

### ISSUE THREAD

**Issue by ghost** [philc/vimium#681]
The vomnibar  falls back to searching Google.  The Google search URL is embedded in the code.  There is no way to change it (short of editing the code).

Either:
1. Fall back to the default search engine configured in chrome, or
2. Allow the default search engine for the vomnibar to be set in the settings page.

I'm not sure 1 is possible.  I can't find anywhere in the chrome.\* API that allows access to the search engine interface, and search engines don't seem to show up in the bookmarks interface.

So 2 seems like the only option.

I'd be happy to work on implementing this, if there's any interest.

(Apologies if this is already in the Issues database.  I did search, but couldn't find it.)

Thanks!

Steve.

**Comment by francisco-simoes** [comment]
Still not working on firefox

**Comment by NicTanghe** [comment]
Indeed i am also unable to edit the default search engine.

**Comment by MrQUACKK** [comment]
> Still not working on firefox

go to `about:addons` and then click on the 3 dots beside vimium and click preferences from the menu. Click on `"Show Advanced Options"` at the bottom, keep scrolling down until you find `"Default search  engine"` and modify what is in the text box beside it. For example I set it to `https://duckduckgo.com/?q=` to use DDG as my default search engine. I'm on firefox 90.0.1 64-bit BTW. Hope this helps :) 

![2021-09-10-155238_843x56_scrot](https://user-images.githubusercontent.com/80370416/132909954-d17e4874-7e9f-42eb-8699-03d50d2d8c09.png)

**Comment by imsosora** [comment]
> > Still not working on firefox
> 
> go to `about:addons` and then click on the 3 dots beside vimium and click preferences from the menu. Click on `"Show Advanced Options"` at the bottom, keep scrolling down until you find `"Default search engine"` and modify what is in the text box beside it. For example I set it to `https://duckduckgo.com/?q=` to use DDG as my default search engine. I'm on firefox 90.0.1 64-bit BTW. Hope this helps :)
> 
> ![2021-09-10-155238_843x56_scrot](https://user-images.githubusercontent.com/80370416/132909954-d17e4874-7e9f-42eb-8699-03d50d2d8c09.png)

This helped! Though I can't understand why it was hidden so well.
