### ISSUE TITLE
"Shift" key clears "find" status

### ISSUE THREAD

**Issue by tvladeck** [philc/vimium#697]
Commonly I will press `f` to see all the links, and then press `shift` to make the link open in a new tab. In previous versions, this would just toggle the command to open in a new tab. Now, it clears the `f` status entirely, meaning I would have to press `shift-f` to bring up the links again. I am unsure if this is desired or not, but since it's a departure I figured I'd let you know.

**Comment by smblott-github** [comment]
Closing.
Resolved as functionality has been reinstated.
