### ISSUE TITLE
Escape insert mode with custom shortcut

### ISSUE THREAD

**Issue by MrJJJ** [philc/vimium#706]
In vim, I like to escape insert mode with jk.
The escape key is really annoying to tap.

**Comment by rajeevksahu** [comment]
We are absolutely involved in our job. So you don’t have to take a crack from your workplace or perform to look after us. We are well known because of our excellent popularity. Our perform is the character certificate for us. We all want to earn a large amount and grow rapidly, but all we do is absolutely trustable.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
Affordability in our do not means that we are fake or do not perform neatly. This is just to pamper our clients and reduce few burdens from them. Our expenses depend on the distance and amount of fill which we have to deal with. Bangalore packers and movers are there to help you anytime, anywhere. You do not have any need to take stress about your items or anything else.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
You just have to tell us full address and we will do our job as soon as possible. If you want us to provide your fill to huge distance then prices definitely increases. If you think that we are charging much more than other movers and packers in Bangalore than we also provide a comparison chart to you. You can compare our expenses from other organizations.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
We also provide unloading alternatives to our clients. That means we package excellent from your present position and unpacked and settle it to your other position. Authorized merchants and certified vendors are our liability. We provide you with best alternatives and requirement only for your believe in.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by EquipoP** [comment]
jk is a pretty  common  thing to write nowadays (https://www.urbandictionary.com/define.php?term=jk) and it could also appear in some places like variable names or something.
