### ISSUE TITLE
能否实现存图功能

### ISSUE THREAD

**Issue by gonejack** [philc/vimium#726]
很喜欢存网页上的图片，每次都要鼠标右键另存为，很累很无爱。

**Comment by gonejack** [comment]
Hi, 8 years later, are there any updates about Chrome's support of this feature?

**Comment by gdh1995** [comment]
Hello, I have a customized version of Vimium, named [Vimium C](https://github.com/gdh1995/vimium-c), and I've added a feature to select an image and show (open) it in a new tab, and then you may use `Ctrl+S` on the new tab to save it. The command is named `LinkHints.activateModeToOpenImage`. But up to now there're still some cases where Vimium C can not recognize images.

Vimium C also has a `LinkHints.activateModeToDownloadImage`, which may fail in more cases, compared with `LinkHints.activateModeToOpenImage`.
