### ISSUE TITLE
goBack in history, open a new tab

### ISSUE THREAD

**Issue by napcae** [philc/vimium#731]
Implement a function to go back in history and open it in a new tab. Usually you click with the middle mouse button on the left arrow to do so. This will open a background tab with the page you visited before.

**Comment by tbrodbeck** [comment]
I just bring forth my support for this feature request!

**Comment by gdh1995** [comment]
Ah, thanks to this idea, I just implemented it in my Vimium C. I haven't known this usage of Chrome before.
