### ISSUE TITLE
Is there a cancel(return/back) shortcut key for vimium?

### ISSUE THREAD

**Issue by nifengtang** [philc/vimium#732]
**\*    Is there a cancel(return/back) shortcut key for vimium?

Usually I just using ESC key to get back,but the key is far from my fingers.

Is there any way I can get back using another key or keys?

**\*   Can I choose some characters/words on the pages,by using vimium?(if I do not use my mouse click on somewhere of the page)

**Comment by rrsahutwo** [comment]
They use appropriate containers, paper and pure cotton containers during packaging process. For sensitive components, they provide their unique alternatives. After packaging all the sensitive and normal things they transportation it with appropriate automobile and medium. Their abilities create their perform perfect. After moving, they get rid of all the items to your position.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
There perform does not finished here. After unloading they unpacked everything too. If you want them to handle the whole product at its position, then they also provide such alternatives too. They have only one motive, and this is to satisfy their clients with their alternatives. Once client get fulfillment, they encounter proud.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
Clients believe in is very essential for packers & movers in Bangalore . If client do not believe in over their alternatives, then it seems impossible to perform in such situations. They do not requirement for additional payment for their provided alternatives. In Bangalore , you will discover many affordable movers and packers.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
You have to pay fixed prices for their alternatives which are affordable and affordable too. You do not have to pay any additional expenses to them. they provide help in different chores like in packaging all the items in containers and paper, fill them in transportation medium, moving to clients position and after all, unloading them.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
