### ISSUE TITLE
Feature request: Select all existing text in an input or textarea by using caps

### ISSUE THREAD

**Issue by gavinhughes** [philc/vimium#754]
A common use case is to select a text field with the intent of replacing the text in the field.  

It would be useful to have a shortcut that selects all existing text in the field when the field is selected.

This could be done intuitively using the same metaphor that applies to links.  When a link is selected with caps, it opens in a new tab.

I propose that a text field selected by caps selects all the text in that field for easy replacement.

**Comment by smblott-github** [comment]
Closing.
`Crtl-A` isn't so bad.
