### ISSUE TITLE
Hints broken on a specific website

### ISSUE THREAD

**Issue by ghost** [philc/vimium#756]
Site in question is: http://www.distributed.net/Main_Page

Rather than have the hints show up next to the links on the page, I get this - see attached image.
![2013-01-12-231614_1276x1397_scrot](https://f.cloud.github.com/assets/2908060/62695/2af61834-5d51-11e2-8477-76ec1b226f09.png)

Only ever seen this behavior on this particular site.  I searched the issues but couldn't find anything describing behavior like this.

I'm using the following Chromium.

Chromium	25.0.1323.1 (Developer Build 167142) Ubuntu 12.10
OS	Linux 
WebKit	537.19 (trunk@134111)
JavaScript	V8 3.15.1.2
Flash	11.2 r202
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.19 (KHTML, like Gecko) Ubuntu/12.10 Chromium/25.0.1323.1 Chrome/25.0.1323.1 Safari/537.19
Command Line	 /usr/lib/chromium-browser/chromium-browser --flag-switches-begin --flag-switches-end
Executable Path	/usr/lib/chromium-browser/chromium-browser

**Comment by smblott-github** [comment]
Closing.
Seems resolved.
