### ISSUE TITLE
Keyboard shortcuts don't work in Evernote Clearly overlay

### ISSUE THREAD

**Issue by sbaney** [philc/vimium#760]
It's not a huge deal, but the keyboard shortcuts do not work when the overlay from Evernote Clearly is applied.

Google Chrome	24.0.1312.52 (Official Build 175374) m

Vimium 1.42

**Comment by GP03DHulaki** [comment]
Hi, I have the same issue on macbook, chrome `Version 39.0.2171.95 (64-bit)`, vimium `1.49`.

**Comment by smblott-github** [comment]
The Clearly overlay is running in an iframe with a chrome-extension URI.  Vimium (and other extensions) don't run on such frames - Chrome doesn't let them.  Unfortunately, it probably won't be possible to fix this issue...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/5904862/9aebb000-a583-11e4-8fe6-0f5e26dbb4b5.png)

**Comment by ajpaulson** [comment]
Ok - good info. 

At least I know why now.

**Comment by GP03DHulaki** [comment]
Ok, it seems I can only use SPACE and shift-SPACE instead of [d] and [u] in clearly for some time. Not that bad. Or save it to Instapaper.
