### ISSUE TITLE
open new tab by F

### ISSUE THREAD

**Issue by hjyssg** [philc/vimium#761]
when trying to open a new tab, I type "F" +theLinkLettetIwantToOpen.
The page is open on the current tab.

**Comment by rrsahutwo** [comment]
EXPERT Packers has earned a higher popularity as a movers throughout the nation. Settled in the market before many years, we have curved a niche and we think proud to provide people in their moving needs. We provide the elevated commitment level, liability, punctuality and timely distribution in our alternatives. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
That is why we have become the first priority of the people looking for moving features. I have countless pleased clients across the nation and it is what gives us more and more popularity in the transportation market. Actually the measurement of our success in Packers and Movers Services in Bangalore is not based on the cash what we earn, but it is based on the variety of clients we provide. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
We have a lot of our repeated clients and from the new ones most of the clients are from reference. These pleased clients in the almost all significant places of Indian tell our success story.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
If you are planning to shift from your present position to another one, you should be very cautious to seek the services of movers packers in Bangalore . Hiring the accountable movers and packers in Bangalore is the biggest effort what you can do for the protection of your baggage. If you are able to seek the services of the knowledgeable and accountable experts, you need not worry about any factors. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
