### ISSUE TITLE
why when i press ctrl+f i see popup with exclude url option?

### ISSUE THREAD

**Issue by milushov** [philc/vimium#769]
several versions ago it was not!
how to desable it? because it is very sucks

my system is ubuntu 12.04

![this](http://joxi.ru/uploads/prod/20130203/f46/11b/34dc6ee95bba89527a1fd938f1c84d90bac11ca5.jpeg)

sorry if I messed up something

**Comment by smblott-github** [comment]
Closing.
Assume resolved.
