### ISSUE TITLE
Vimium gets disabled randomly when navigating to different tabs.

### ISSUE THREAD

**Issue by ovidiuvisan** [philc/vimium#773]
Most consistently it doesn't work on https://chrome.google.com/webstore/category/home and in most tabs that have https sited opened.
Chromium: Version 24.0.1312.56 Built on Ubuntu 12.10, running on LinuxMint 14 (24.0.1312.56-0ubuntu0.12.10.3)

**Comment by smblott-github** [comment]
Closing.
Assuming resolved.
