### ISSUE TITLE
Does not work on Google search result page

### ISSUE THREAD

**Issue by jhshi** [philc/vimium#797]
Use Alt+D to focus address bar, enter keyword, but the Vimium will refuse working on the result page. Only "x" works though, other keys (f,d,u) don't work.

I've turn the instant search feature off, still not working.

**Comment by dylnmc** [comment]
This was still happening to me in Linux Mint 17.01. What I had to do was to Firefox's addon's manager and disable "Mint Search Enhancer."

**Comment by rhys-vdw** [comment]
Could this be back?

![image](https://user-images.githubusercontent.com/822105/57592350-969ee880-7579-11e9-863a-f3d64a6900bb.png)

**Comment by MeloMing** [comment]
> Could this be back?
> 
> ![image](https://user-images.githubusercontent.com/822105/57592350-969ee880-7579-11e9-863a-f3d64a6900bb.png)

hey,I seem to have the same problem with you,no matter I search from the Omnibox or google homepage the vimium icon is always gray，have you fixed this problem？

**Comment by gdh1995** [comment]
@rhys-vdw Are you using Opera? It has some built-in safety limitaions causing thia issue.

**Comment by MeloMing** [comment]
> @rhys-vdw @MeloMing Are you using Opera? It has some built-in safety limitaions causing thia issue.

I am using chrome

**Comment by onejae** [comment]
It's still happening to my chrome.

**Comment by Flurrywinde** [comment]
Opera user here. @gdh1995 I found it works again by going to Extensions and checking the box to allow access to search results.

**Comment by rsha256** [comment]
yep going to `opera://extensions` and giving access to search results worked for me, thanks Flurrywinde!

**Comment by filipewvandrade** [comment]
> Opera user here. @gdh1995 I found it works again by going to Extensions and checking the box to allow access to search results.

Thank you, works for me too
