### ISSUE TITLE
how to let plugin option page valid with B operate

### ISSUE THREAD

**Issue by loyalpartner** [philc/vimium#805]
i add a bookmark like : 
chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/options/options.html

then i type B and selecte the item,
![1](https://f.cloud.github.com/assets/1442249/303285/2baced44-9621-11e2-9c11-807041a6bfc2.png)

but i can't go to the vimium option page?

it use google to search,not go to the page
![2](https://f.cloud.github.com/assets/1442249/303303/938ae9a2-9621-11e2-8167-d080a4d4c64b.png)

**Comment by smblott-github** [comment]
Closing.
Been fixed.
