### ISSUE TITLE
Suggestion: On visual mode

### ISSUE THREAD

**Issue by hyh1048576** [philc/vimium#809]
In #61 the possibility of visual mode have been discussed. It says

> the biggest problem is that HOW TO SELECT.

I thought about it, and it is tricky to have a cursor to jump between `<div>`'s, as the cursor can go to weird place which one doesn't expect. And there is an issue of invisible `<div>`'s, like those with `display:none;` by Adblock.

How about the following:

Hitting `v` will have the same effect as hitting `f`, and the user is allow to choose which `<div>` he/she wants to focus on (by typing 2 or 3 letters, just like the link hint). And then he/she can just work over there. (e.g. maybe `o` opens a link under cursor, `s` searches the selected text, `c` copies the selected text, etc. ----And `h` `j` `k` `l` moves the cursor, of course) After the job is done hitting `Esc` quits the visual mode.

It is just some quick thought on this, and there are details to be fill in, e.g. whether/how visual mode should work in text input field etc. or at least we should let the cursor to jump among different <p> tags. I want to know what people think about this UI, certainly it is not how vim does it, but we are on a browser and things are now different.

**Comment by smblott-github** [comment]
Closing.
We have visual mode.
