### ISSUE TITLE
Timeout for retaining URLs in clipboard.

### ISSUE THREAD

**Issue by gnufreak** [philc/vimium#815]
Scenario:

You want to open multiple tabs with a search form to search for item1, item2 and item3.

1. You have item1 in your clipboard
2. You search for it in the first tab with the page
3. You press yy, P to open the same page in the new tab to search for item2
4. You repeat this for item3 as well

Problem:
When you paste into the search form input, you paste the copied URLs instead of what you previously had in there: 'item1'. (I'm aware that this is working as expected now).

Would it be possible to:
1. Upon pressing 'yy' to yank the URL, copy the current contents of the clipboard to a temporary variable
2. Start a timer (timeout configurable in settings)
3. When it expires, revert the clipboard contents to the previous value stored in the temporary variable?

I'm not sure if it is, but I thought it wouldn't hurt to ask. This could allow to:

1. Have item1 in the clipboard
2. Open my search page, paste the item1 into the form
3. Press yy P
4. Wait a second or so, paste again to get item1, change it to item2

and repeat it as many times as needed. This is something that would save having to switch to a previous tab where you have 'item1', copy it again, switch back to the newly opened tab, paste it and so on.

Regards,
Martin

**Comment by smblott-github** [comment]
Closing.
Not sure there's a lot we can do.
