### ISSUE TITLE
I hope that there is a feedback each Vimium operation

### ISSUE THREAD

**Issue by pihao** [philc/vimium#823]
* **我的问题**  
	当我使用网上银行的时候，我正在向输入框中输入一些字符。  
	一不小心碰到了触摸板，导致Vimium被激活。  
	这时我还以为在输入状态，一旦这时我输入字符“r”就会导致页面被刷新。  
	这时我会觉得奇怪和愤怒，因为我要重新进行麻烦的登陆验证。  
	也许要过了半天我才能意识到是因激活了Vimium。  
* **解决问题**  
	所以我希望每个Vimium的操作都有一个反馈，比如一个小提示或者其它形式的反馈。  
	提示的使用与否可以进行设置，以方便那些不需要操作反馈的用户。  

*我非常喜欢Vimium，感谢你看完我的建议！*

translate by Google
---

* **My question**
	When I use online banking, I was some characters to the input box.
	Accidentally hit the touchpad, the lead Vimium is activated.
	At this time, I thought, once when I enter the character "r" in the input state will cause the page is refreshed.
	At this time I would be surprised and angry, because I want to re-login authentication of the trouble.
	Perhaps over half a day to realize that is activated Vimium.

* **Solve the problem**
So I hope that there is a feedback each Vimium operation, such asa small tips or other forms of feedback.
The use of prompts or not can be set up to facilitate those who do not need user feedback.

*I really like Vimium Thank you for reading my suggestion!*

![Demo](https://f.cloud.github.com/assets/3308394/457874/cc4eb2da-b3ba-11e2-9c9c-6133ed9b5429.png)

**Comment by smblott-github** [comment]
Closing.
Old.
