### ISSUE TITLE
Feature Suggestion: split windows (vertical or horizontal)

### ISSUE THREAD

**Issue by jkmacc** [philc/vimium#824]
Firstly, thanks to all who make this a top-notch plugin, and one that I could not browse without:-)

I'd love to see split window functionality as part of Vimium.  While this is possible with other Chrome extensions, it seems like a very useful and Vim-like operation.  A simple CTRL-W_CTRL-S or :sp  for horizontal, or CTRL-W_CTRL-V or :vs for vertical would be very impressive indeed!

Thank you for your consideration.

**Comment by smblott-github** [comment]
Closing.
Beyond scope.
