### ISSUE TITLE
Feature Request - Number qualifier for yy hotkey

### ISSUE THREAD

**Issue by sunzoom** [philc/vimium#827]
yy should copy the current link address. (Works)

1yy should copy the current link address (Disregards the number 1 but yy qualifies and copies URL)

nyy doesn't do anything.

Feature request is to copy the current tab links and n URLs right of the tab. 

This will allow many open tabs to be opened.

Another feature request:

At the moment you can jump from tab 1 to tab 25 by using 25KK however its hard to count the tabs. Is there a way you can have a virtual pointer to them like the f shows on the hyperlinks. This would be a real time saver.

Kind Regards,
Sandeep

**Comment by smblott-github** [comment]
Closing.
Lack of interest.
