### ISSUE TITLE
Settings test and getCurrentVersion() problem

### ISSUE THREAD

**Issue by sainaen** [philc/vimium#832]
There is a minor problem with current version of Settings test in these lines:
```coffee
Utils.getCurrentVersion = -> '1.42'
{Settings} = require "../../background_scripts/settings.js"
```
The thing is that when Settings object is creating it uses `Utils.getCurrentVersion()` as default `settingsVersion` property value, and the first line replaces this function with a stub. But, as you can see in the [current travis build log](https://travis-ci.org/philc/vimium/builds/7028359), sometimes original version of `getCurrentVersion()` is accessible from the scope of `settings.js`. And as a result we get an error 'ReferenceError: chrome is not defined'.

As a proof, I've created two exactly the same branches in my fork, and build them on travis with `console.log(Utils.getCurrentVersion.toString)` in `settings.coffee`:
[First one](https://travis-ci.org/sainaen/vimium/builds/7043099) (passed):
```js
function () {
  return '1.42';
}
```
[Second one](https://travis-ci.org/sainaen/vimium/builds/7043523) (failed):
```js
function () {
  return chrome.runtime.getManifest().version;
}
```

I don't know how to fix it right now.

**Comment by smblott-github** [comment]
Closing.
Old.
