### ISSUE TITLE
How back from url address bar to site?

### ISSUE THREAD

**Issue by alexche8** [philc/vimium#840]
When I press ctrl-l or alt-d to go to the adress bar I cant go back to the site and use vimium.
I already read some articles on this thame http://productforums.google.com/forum/#!topic/chrome/mLuqJskmfyQ . As I undersood chrome does not have this functionality from start. Of course there are F6, but this works only for Windows. Has vimium any shortcut for returning to the page from url bar?

**Comment by TMiguelT** [comment]
This is a great hack! For reference, the settings should look something like this, in Settings, Manage search engines, Other search engines:
![image](https://cloud.githubusercontent.com/assets/5019367/20123453/4e9d7e20-a673-11e6-9201-5bec12a418ef.png)

**Comment by samuele-artuso** [comment]
When the omnibar is focussed, just hit F6 once (if the bookmark bar is hidden) or twice (if the bookmark bar is visible).

**Comment by nickpesce** [comment]
The hack that @TMiguelT posted didn't work for me, but I was able to get it to work by changing the URL to "javascript: document.getElementsByTagName("html").focus();".

**Comment by yuha0** [comment]
I am on Chrome 64.0.3282.119 and pressing `ESC` moves focus from the address bar to webpage for me.

**Comment by mlevesquedion** [comment]
In my case Shift + F6 does the trick.

**Comment by PiedPieper** [comment]
Or you can press tab

**Comment by sunnyday2006** [comment]
Sometimes you have to tab probably  more than one time.

**Comment by rsslldnphy** [comment]
I absolutely ❤️ this hack @sainaen and have been using it for years - thank you! However I've recently switched to Firefox where I've been unable to accomplish the same thing in the same way.

I managed to get an alternative working though: in firefox you can assign a keyword to your bookmarks, so I created a bookmark with a location of `javascript:()` and a keyword of `j` - and it works. 🎉 

Thought I'd post it here in case anyone else stumbles across this issue as I did.

**Comment by jolenzy** [comment]
I finally find a solution, so I stopped by to share it :) Hit Ctrl+l - and the current address/url gets focused and selected - works in Chrome and Firefox for sure.

**Comment by melkor217** [comment]
> I finally find a solution, so I stopped by to share it :) Hit Ctrl+l - and the current address/url gets focused and selected - works in Chrome and Firefox for sure.

I guess point is to switch focus back to page

**Comment by blakerunyon09** [comment]
@Ryanauger95 with a touchdown pass over here.

**Comment by jchhuang-tech** [comment]
> I managed to get an alternative working though: in firefox you can assign a keyword to your bookmarks, so I created a bookmark with a location of `javascript:()` and a keyword of `j` - and it works. tada

For firefox this is great but it only works in the address bar, not the search bar, if you have a separate search bar.
And F6 does unfocus the bar but man is that key disgusting to hit
My workaround is <Ctrl+H><Ctrl+H>, which toggles the history sidebar twice, and after that you're back on the page

**Comment by leoriohub** [comment]
Can F6 be remapped? it is such a bad keybind
