### ISSUE TITLE
Freature request: Shortcut for "Close other tabs"

### ISSUE THREAD

**Issue by ivenhov** [philc/vimium#851]
Would be nice to have that key binding.
Any key combination would do for me.

**Comment by markstos** [comment]
Where are the keyboard shortcuts for these commands documented? I don't see any documentation updated by the PR.

**Comment by smblott-github** [comment]
Go the the Vimium options page.

Click *Show available commands*.

There's also some additional information on the [Wiki](https://github.com/philc/vimium/wiki).

**Comment by markstos** [comment]
@smblott-github Thanks. I found them listed in the Advanced available commands, but there no key mappings. I presume it's then up to each user to set our own key mappings for these? (which I see now to do)? Or is there is a way to run a one-off command (which I haven't figured out how to do).

**Comment by smblott-github** [comment]
Create your own mapping for unmapped keys.
