### ISSUE TITLE
Shadow DOM problem/suggestion

### ISSUE THREAD

**Issue by bliker** [philc/vimium#853]
Hi!
I am currently finishing porting my extension to use _Shadow DOM_. I was wrestling with the same issue like vimium, where css of page I was injecting into has been modifying css of the extension. Shadow DOM separates extension from other styles, Very neat.

But when I have Input element inside of `#documet-fragment` vimium still reacts to typing like  I am not in input.
[Example on JsBin](http://jsbin.com/asufis/2)

if you want to check my [extension](https://github.com/bliker/magickyslovnik/tree/shadow). It is in Slovak, but code is in English.

**Comment by mrmr1993** [comment]
The example above no longer works now `Element.webkitCreateShadowRoot` has been depreciated. Updated example [here](http://jsfiddle.net/0xL12q5w/).

We can detect that an element has a shadow root by checking that `element.shadowRoot != null`, and further can capture `focus` events after one fires on the shadow root with `element.shadowRoot.addEventListener("focus", listener, true)`. Tying this together, we should be able to activate input mode for shadow DOM elements to kill this bug.

**Comment by mrmr1993** [comment]
This was fixed by #1627.
