### ISSUE TITLE
New/current tab inversion when using caps letters as link-filtering numbers

### ISSUE THREAD

**Issue by lalopmak** [philc/vimium#857]
Google Chrome	27.0.1453.93 (Official Build 200836) beta
OS	Linux 
Vimium 1.43 

=======

Recently, I've tried using capital letters as the "Numbers used for filtered link hints".  This way, I could type the link content (using lower-case letters) then use capital letters to complete the navigation - easier than reaching to the actual numbers.

This works almost perfectly, except that, when the link is completed via one of the capital letters, the new/current tab gets switched around!  That is, if I'd used LinkHints.activateMode, it would open in a new tab.  And if I'd used LinkHints.activateModeToOpenInNewTab, it would open in the current tab.

Steps to reproduce:
1. Check  "Use the link's name and numbers for link hint filtering" 
2. Set "Numbers used for filtered link hints" as the capital letters "HKLUYNEIO"
3a. Try LinkHints.activateMode, finishing with a capital.  It will open the link in a new tab.
3b. Try LinkHints.activateModeToOpenInNewTab, finishing with a capital.  It will open the link in the current tab.

If you finished with a lowercase (i.e. via normal typing of the link content) the behavior is as expected.

**Comment by smblott-github** [comment]
Closing.
We have decided to stick with this behaviour.
