### ISSUE TITLE
Feature suggestion: keep `l` free for liking things in Facebook

### ISSUE THREAD

**Issue by Atcold** [philc/vimium#860]
It's kind of nice just clicking on `l` to *like* things in *Facebook* and now.. it doesn't work any more :cry: 
Can you restore this keystroke somehow?

**Comment by dragon788** [comment]
You can enter insert mode or add facebook.com to the list of exclusions and tell it to pass through 'l'.

**Comment by smblott-github** [comment]
You can add `l` as an excluded key in the page popup...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7559547/6cd50688-f7b0-11e4-8040-c8c8525733db.png)

**Comment by Atcold** [comment]
Alright, tnx!
