### ISSUE TITLE
Suggestion: Permanent f/F

### ISSUE THREAD

**Issue by axelGschaider** [philc/vimium#877]
I understand that this should probably not be the standard behavior but I would really love to have a setting that keeps the f/F-hints from disappearing after I've chosen one.

Background:
A) I sometimes want to open a batch of links via F and it's a bit tiresome to have to click F over and over again

B) sometimes I use f to click some buttons that don't cause a page reload.

I'm sorry if this is a duplication. I did a rough search and didn't come up with anything.

**Comment by dragon788** [comment]
I believe another reason this behavior wouldn't work very well is if you were to scroll since the hints are generated based on the position on the page and being in view the link hints WOULD change. Definitely learned some tricks from reading this though.
