### ISSUE TITLE
Copy the page title to the clipboard

### ISSUE THREAD

**Issue by baskerville** [philc/vimium#889]
I'd like to be able to copy the page title to the clipboard.

**Comment by vincentbernat** [comment]
@philc What better tools are available for that? This seems an useful feature for me.

**Comment by smblott-github** [comment]
> What better tools are available for that?

If you're feeling really geeky, then perhaps [chromix](https://github.com/smblott-github/chromix). `chromix list` gives:

```
849 https://github.com/philc/vimium/issues/889 Copy the page title to the clipboard ? Issue #889 ? philc/vimium
```

> This seems an useful feature for me.

It might be useful, but I'm not sure it's sufficiently useful to warrant a new command.  An undiscoverable hack would be to have `2yy` yank the title.

**Comment by mrmr1993** [comment]
@vincentbernat you could create a bookmarklet with the address `javascript:void(prompt("You may copy the page title below:", document.title));`, trigger that from the Vomnibar, and copy the title from the resulting prompt.

A resolution to #1392 would allow custom commands &mdash; so you, rather than the project maintainers, get the final say in which functionality you can have &mdash; but that's not a high priority issue at the moment.

**Comment by vincentbernat** [comment]
@mrmr1993 Well, I would need to use the mouse. Even if you can put the text somewhere else, copy/pasting it would be rather less convenient than a two key shortcut.

@smblott-github Using Linux, I am currently using `xwininfo -root -children | grep Chromium`. I could do an alias. But this seems more natural to put just that in Vimium.

**Comment by mrmr1993** [comment]
> I would need to use the mouse.

@vincentbernat  you shouldn't need to. If you create the bookmarklet and give it a name like `titleText`, you should be able to access it with `b titleText`, maybe tab a few times to select the bookmarklet, and then ctrl-c when the prompt comes up. It's not ideal, but it should work.

**Comment by vincentbernat** [comment]
@mrmr1993 Oh, yes, sorry, I missed the comma before `document.title`. That seems a good workaround. Thanks!

**Comment by ymyke** [comment]
@philc Here's my use case why I think something like `yp` or `ys` to yank the page title would be useful: I often send around links to web pages to friends or work colleagues. Most of the time, I want to send not only the link but also the page title, as it usually contains,e.g., the title of an article and helps recipients better understand what the link is about.

Today, I need to painstakingly select and copy an article's title manually.

Edge allows me to copy link+title in one, however a) other browsers don't and b) I'd like to have the two things separate.
