### ISSUE TITLE
Allow binding to arrow keys

### ISSUE THREAD

**Issue by ilya** [philc/vimium#89]
from the gallery page:

"I'd like to map the left arrow to previousTab, is this possible?

I tried:

map <Left> previousTab

But Vimium doesn't seem to like it."

**Comment by imnickvaughn** [comment]
..no link to an actual solution :(

**Comment by smblott-github** [comment]
> ..no link to an actual solution :(

It's in the [README](https://github.com/philc/vimium#custom-key-mappings).

It's just:

    map <left> scrollLeft

(or whatever).

**Comment by Bekon241** [comment]
Yes this can be usefull when you want go next prev short on YT only... better add leader j and k then use f and ui combo to next vid all the time... :( Tridactyl also have problem with that becouse YT most time use java script to block aroows for security reason i think... :( I still not find solution for that i use even --force flag and nothing help but i use tridactyl now.
i like when "D" is used to close tabs and x not also dd, cc, can be usefull to delete line of text in imput area and change mode dd + normal and cc + insert

**PS. When you use short on full screen mode j and k work properly somtime and you can go next video using j**
but i use chrome for test this, i love librewolf and geko engine not chromium then i rly hate when some script on YT block all in librewolf/ff becouse subtitles not on most time. Florp browser have less problems with subs i think this is libre wolf settup problem becouse meny restriction for privacy reason.

I even not coding, i just lern vim motion year ago and now i can life without this... I think i must change kde for some tiling manager mayby hyprland becouse i want not touch my mouse if i not play games.

This is my config for tridactyll unfortunetely still not all work... :(
But maybe this give you some another functionality hint for vimium.

```
# time between keypresses
set timeoutlen 400 

# time after leader press and leader SPACE
set leader <Space>
set leadertimeout 2000

" Delete current line (dd) when insert mode in windows like (search) and back to normal mode.
bind --mode=insert dd composite text.delete-line ; jumptoparent ; mode normal

"  Delete curent line and stay in insert mode (cc)
bind --mode=normal cc composite text.delete-line ; jumptoparent ; mode insert

" Send actual ArrowDown/ArrowUp key events
bind --mode=normal <space>j composite js tri.native.sendKey("ArrowDown", "current") ; jumptoparent
bind --mode=normal <space>k composite js tri.native.sendKey("ArrowUp", "current") ; jumptoparent 
```
Thanks for hard work :) Cheers from Poland i wait for update with good neews :)
