### ISSUE TITLE
New feature: open link in a new tab and switch to it

### ISSUE THREAD

**Issue by cespare** [philc/vimium#900]
Apologies if this is already in the issue tracker somewhere; a cursory search didn't turn it up.

My most common use case for opening links with `F` (open in new tab) is to immediately switch to that tab. It would be great if there were a link opening shortcut that opened the link in a new tab and switched to it as well. What if either (a) there were an option to make `F` behave this way, or (b) there were a new shortcut for this?

Also, is this possible? It might not be easy to figure out which tab the link was opened in. (Remember that it's not necessarily the next tab over.)

**Comment by hinell** [comment]
@philic PLEASE DOCUMENT THIS FEATURE, thanks!

**Comment by flavius-popan** [comment]
@chtenb Dude, I did a happy dance so hard I nearly split my jeans. THANK YOU!

**Comment by busfahrer** [comment]
Tip:

When replacing F with this version, you can still use Alt-f (followed by escape) to get back the old behavior of opening the link in a background tab.

**Comment by MusaToTheMoon** [comment]
I love the internet
