### ISSUE TITLE
Change Vomnibar's tab listing to be "last accessed" rather than "created at"

### ISSUE THREAD

**Issue by dylan-conlin** [philc/vimium#909]
When invoking "search tabs" (by default bound to shift + t), instead of listing my tabs chronologically, I'd like the option to change the default sort order to "last active" or "most recent"

Essentially, I'd like the option of changing vimium's tab searching behavior to match emacs' buffer-switching behavior.

**Comment by dragon788** [comment]
I think the tab search is using an MRU (most recently used) now rather than creation date, is this fixed?

**Comment by mrmr1993** [comment]
> is this fixed?

Yes, since 422a87e1e664ea86edf3e628d465ac700af404d0.
