### ISSUE TITLE
request: q style macros

### ISSUE THREAD

**Issue by octagonal** [philc/vimium#910]
Has it ever been considered to add a macro system to Vimium? It would be especially handy for doing repetitive tasks like going to a certain page and whatnot.

**Comment by TreyBlancher** [comment]
+3 voting for this.  I have a need to do several repetitive tasks on a web page.  Being
able to record a q + <letter register> macro, and then execute it with @<letter> would
ease the pain since the system I access doesn't have a good way to do bulk operations.
Vimium makes it MUCH easier, but without a way to record the macro it's lacking in
functionality.

Writing a script for these things is secondary, but recording the macro like vim does
would be most helpful.

**Comment by smblott-github** [comment]
@TreyBlancher... Could you give a concrete use case, please?

(While on the face of it this seems like an interesting idea, I wonder whether it might be tricky in light of the amount of asynchronous processing we do.)

**Comment by TreyBlancher** [comment]
@smblott-github:  The only use case I have is PortaSIP's administration user interface,
something you're not likely to have access to.  Essentially I want this feature to work
similar to vim's macros, hit 'q' and a register letter, which begins recording.  Any
vimium commands get put into the macro, until 'q' is typed again.  That way, tedious
tasks could be automated.

Macros for filling out e.g. router configuration pages, or anything achievable with
vimium commands.  Static pages which do not change.  An editor to modify the macro and
insert e.g. pauses would be helpful too.

As it is I used a combination of Keyboard Maestro macros and vimium to do what I want,
but it's rather clunky (and I don't want to rely on Keyboard Maestro anymore).

**Comment by Beasta** [comment]
+1 for this feature as TreyBlancher put it

**Comment by jpribyl** [comment]
+1 for this, I have to make lots of repetitive changes while setting permissions! I also have to wait for pages to load - so it would be super cool to have a "real time" feature that (when enabled) waits before pushing the next key for as long as you did during macro creation. In the mean time, I wonder if it would be possible to do jerry-rig something with autokey.. I'll update this if I figure it out!

**Comment by leikoilja** [comment]
Still very much requested feature in 2020

**Comment by sz47** [comment]
Even after about 9 years later this would be a happy addition

**Comment by jackyhevey** [comment]
+1 for this

**Comment by CalebBertrand** [comment]
In https://github.com/philc/vimium/issues/2230 it's mentioned that the asynchronous nature of most browser events would make this difficult, but I wonder if something like a polling mechanism could work, for example you have a macro which clicks a certain link, then clicks another link on the page once it loads. After the page load, the `f` command can poll for that link a few times, and will timeout if it can't be found for too long. I believe playwright does something similar. Even if macros only worked for a subset of commands, it would be super helpful.
