### ISSUE TITLE
Scrolling doesn't work in current Chrome Canary (32.0.1661.0)

### ISSUE THREAD

**Issue by sainaen** [philc/vimium#928]
I've digged a bit into this issue and found this revision with patch to Chrome: http://src.chromium.org/viewvc/blink?view=revision&revision=158864

According to commit message there, from now on `document.body.scrollTop` and `document.documentElement.scrollTop` will change their behavior to opposite in strict mode: `body.scrollTop` will always return 0 (but we still could set it to some value though) and `documentElement.scrollTop` will return proper value. Same thing with `scrollLeft`.

Current Vimium's implementation of scrolling (see `content_scripts/scroller.coffee`) relies on `document.body` so it doesn't work anymore.

I've tried to do something with it, but right now I cannot think of a way to fix this problem in current Canary (add support of browser behavior in both strict and quirk modes) and in the same time don't break anything in current Stable, so I would really appreciate any help.

**Comment by smblott-github** [comment]
Closing.
Out of date.
