### ISSUE TITLE
Open a new tab (and switch to it) when I type 'twitter.com' in the addresss bar somewhere after the first t letter

### ISSUE THREAD

**Issue by schemacs** [philc/vimium#937]
This happens every time when there is a `t` letter in the url when I typing at the address bar. No tab should be open when the address bar is focused. But I have no idea if we can detect current focus point(the cursor is on the page or typing in the address bar).

Vimium 1.43
Chrome Version 30.0.1599.101
OS: Ubuntu 13.10 x86_64

**Comment by smblott-github** [comment]
Closing.
Not relevant.
