### ISSUE TITLE
Does vimium work well for local html file?

### ISSUE THREAD

**Issue by mingchaoyan** [philc/vimium#938]
I often browse some local documents (Like file:///D:/Program%20Files/erl5.9.2/doc/index.html)? But at that time vimium stops working. Is it a bug? Or there is no way to use vimium for local file?

**Comment by boblehest** [comment]
Can confirm the issue exists.

**Comment by mrmr1993** [comment]
There should be a checkbox next to Vimium in `chrome://extensions`! Sorry nobody's got to this sooner.

**Comment by mingchaoyan** [comment]
@boblehest @mrmr1993  Thanks, you are right!
