### ISSUE TITLE
Single line Vomnibar suggestions to fit more on screen

### ISSUE THREAD

**Issue by lyallh** [philc/vimium#939]
Hi,
I've been playing with some customizations to optionally display a more compact Vomnibar. This was out of a desire to see more entries on screen, especially when searching open tabs. 

Here's a screenshot. I will tidy things up for a pull request in future, particularly if anyone shows interest.

Just creating this issue as a suggestion.

![vomnibar-compact](https://f.cloud.github.com/assets/3969710/1398554/050656ce-3ca4-11e3-8f13-a9f745cc3bd6.jpg)

**Comment by smblott-github** [comment]
Closing.
No action required.
