### ISSUE TITLE
Doesn't work with my native language (russian)

### ISSUE THREAD

**Issue by gohoho** [philc/vimium#953]
When I change my keyboard layout to russian I can't use vimium hotkeys. Is it possible to use vimium with both english and russian layouts?

**Comment by gvlasov** [comment]
Currently the right way to work with Vimium using a non-latin layout is to use the option **Advanced Options -> Miscellaneous Options -> Ignore Keyboard Layout**. Using custom mappings as suggested above doesn't solve the problem of needing to switch to a latin layout when selecting a link with `f`.
