### ISSUE TITLE
Pop ups no longer get focus when launched from Omnibar bookmark search with "b"

### ISSUE THREAD

**Issue by bryankennedy** [philc/vimium#955]
Something changed. Not sure if it was Vimium of Chrome. However, I used to be able to:

1. Type "b"
1. Search for a bookmark which launches a pop-up window (I use this for bookmarking sites with Pinboard).
1. Hit enter to select the bookmark.
1. The pop-up window would launch with focus where I could start typing into it immediately.

However, the pop-up window no longer gains focus for typing. The window is in front of the parent window, but typing focus is retained by the parent window which is obscured. This causes any typing to trigger all kinds of Vimium shortcuts to popup when I'd rather be typing in the pop-up window. The only way to force focus onto the pop-up is by clicking on it (grumble) or by cmd+` through the open windows until the pop-up is selected.

Can anyone point me to a workaround or a possible code area where I could help fixing this issue? Is this possibly considered the desired behavior?

**Comment by smblott-github** [comment]
Closing.
No response from OP.
