### ISSUE TITLE
Vomnibar: don't show the javascript contents of bookmarklets

### ISSUE THREAD

**Issue by philc** [philc/vimium#961]
We shouldn't show or index the javascript of bookmarklets.

![screen shot 2013-11-22 at 2 54 15 pm](https://f.cloud.github.com/assets/8598/1604892/4f552200-53c9-11e3-821c-0ebb08050c1f.png)

**Comment by wildeyes** [comment]
Would the appropriate solution be to remove the js-contents and just center the "bookmark - {{bookmark.name}}"?

**Comment by smblott-github** [comment]
Centring doesn't seem best.  Would it not look odd with everything else left aligned?

What about just replacing the second line with...
```
javascript:...
```

#984 seems to replace the JS with the first URL it contains.  I'm not sure how reliable that would be.
