### ISSUE TITLE
[feature] add new command to cycle through recent tabs

### ISSUE THREAD

**Issue by farzher** [philc/vimium#965]
Should behave exactly like `ctrl + tab` in sublime text.

When I `shift + t` to go somewhere, I want to be able to just go back to where I was recently.

**Comment by dragon788** [comment]
This looks old and solved, can somebody close it?

**Comment by inakiabt** [comment]
How it was solved?

**Comment by mrmr1993** [comment]
> How it was solved?

It wasn't. Looks like @dragon788 misunderstood the issue.

**Comment by dragon788** [comment]
Ah, yes, I was under the impression that using the tab vomnibar navigation should cover most of the use case, though I think it would be awesome if we the ability to jump to a specific tab in a single keypress rather than tabbing through the whole list, but that's probably another issue.

**Comment by farzher** [comment]
I didn't realize vomnibar worked so well for this in all cases, nice. There's no need for a new command.

Although I noticed a bug(?) when multiple chromes are open.
I'm not sure exactly what's happening, but it's weird. I think each chrome has its own history.
If switching between tabs between chrome windows, the tab history gets messed up
