### ISSUE TITLE
The "copyToClipboard" handler should not have a return value

### ISSUE THREAD

**Issue by harry313** [philc/vimium#966]
When I call this sentence below in content script:
```
chrome.runtime.sendMessage({handler: 'copyToClipboard', data: '111'}, callback);
```

It will throw an error:
Error in event handler for runtime.onMessage: TypeError: Converting circular structure to JSON
And the callback function will not be called.

I found the error is throwed at this position in main.js:
```
    if (sendRequestHandlers[request.handler]) {
      sendResponse(sendRequestHandlers[request.handler](request, sender));
    }
```

The return value of "copyToClipboard" will be passed to sendResponse, but before this, the value will be converted to JSON format. So, it has a error here, the value here is not a simple type, it can not be stringified.

**Comment by smblott-github** [comment]
Closing.
Resolved.
