### ISSUE TITLE
A shortcut to hover over a link

### ISSUE THREAD

**Issue by AnandDegwekar** [philc/vimium#980]
Great plugin, 
I wanted to add a feature request, 
In websites like facebook or quora you many need to hover over a link to see something, 
eg In quora you hover over someones name to see their pic and follow button
in FB you can hover over some item in the feed to see it expanded without clicking on it,
Is there a way to do that, Can you add it?
Thanks

**Comment by smblott-github** [comment]
Closing.
Discussed in a number of other threads.
