### ISSUE TITLE
unable to unset ']' key

### ISSUE THREAD

**Issue by Akenaide** [philc/vimium#986]
Hello,
browser : Chrome

I can not unset ] key. I don't even know what is exactly do, I just see it unfocus when I typing.

I add "unset ]" in the config but I don't see any change.

Great plugin I starting using vim a lot and it feel great to use the same way to navigate in my browser.

sorry for my poor english

**Comment by niwox** [comment]
any solution for this partical issue ?

**Comment by mrmr1993** [comment]
Sorry this has been sat so long. I'd been hoping that a fix for #301 would resolve this along the way, but #1140 didn't make the grade.

I've pushed 956145d as my attempt at a (very low quality) fix. @niwox (or somebody else), could you test it? If it works, I'll put it in a PR.

**Comment by Akenaide** [comment]
Sorry for the late, your change do the job. I can type "]" again with vimium activate o/

Thanks

**Comment by Akenaide** [comment]
oops

**Comment by niwox** [comment]
No fix on the official release yet for this issue ?

**Comment by roessland** [comment]
I cannot type [ in Vimium on my Norwegian keyboard (I had to copy paste it in here). It is typed by pressing AltGr+8, or equivalently Ctrl+Alt+8. I lose focus from the textarea when I press it.

It's also impossible to unmap. I've tried

unmap [  
unmap <c-a-8>  
unmap <c-[>

and some other combinations.

**Comment by zieren** [comment]
Same here (German layout).

**Comment by smblott-github** [comment]
OK.  Added *next-version* label.  We should fix this.

(It happens because `Ctrl-[` is hardwired to be "Escape".)

**Comment by niwox** [comment]
I believe `Alt Gr - [` is hardwired to be Escape too. Any fix for that ?

**Comment by andersoyvind** [comment]
This will be a noticable issue, as users of online javascript editors (jsbin, jsfiddle etc) or the interactive training sites (codeschool etc) will face the <insert bracket here>-issue, eventually.
Glad that it is worked on.

**Comment by smblott-github** [comment]
Closing. #2215 is merged (and released), which should fix most of the issues here.
