### ISSUE TITLE
New Hotkey CTRL+[ : Force command-mode and focus page 

### ISSUE THREAD

**Issue by freeo** [philc/vimium#988]
Sometimes the page content is somehow unselected and therefore vimium doesn't work and I have to reach over to the mouse just to click on the page... Cycling trough the browser main elements with F6 doesn't work in this case, `<ESC>` neither.

This relatively rare problem plus the inconvenient F6 hotkey sparked the idea of introducing a  new command to force the focus on the page. Should work in all other states of the browser including when the cursor is in the omnibar, which makes it necessary to include a modifier the command. This suggestion means to extend  the **command-mode** to be even more independent of what it going on in chrome, beyond the function of `<ESC>`.

To follow Vim's logic as much as possible, this should be achieved by pressing `<ESC>`, which is problematic because of chrome itself.I therefore suggest the combination `<C-[>` for the function "*hard escape to command-mode with forced focus on the web-page*". The combination is another equivalent for `<ESC>`, so it doesn't break Vim's logic. And the biggest pro is, that it is unmapped!

I think this would be a nice enrichment for vimium, which would make reaching over to the mouse even less likely.

**Comment by philc** [comment]
Can we use [this feature in chrome](http://www.omgchrome.com/keyboard-control-scope-chrome-extensions/) to implement this?

**Comment by smblott-github** [comment]
> Can we use this feature in chrome to implement this?

I tried using this to `.focus()`, and `.simulateSelect()` on `document.body` (7d85036ac1b03ea416607a2a8cb5c6eb57923262).  Didn't work, unfortunately.

My branch is [here](https://github.com/smblott-github/vimium/tree/escape-the-omnibar), if anybody has other ideas.

**Comment by mrmr1993** [comment]
> if anybody has other ideas.

I could imagine jumping quickly in to fullscreen, focusing an element/the document/etc. and jumping back out again might work.

**Comment by gdh1995** [comment]
> to move the current tab to a new window and then replace it in the same position in the original window

It seems not to work for `chrome://newtab`.

**Comment by hjdivad** [comment]
For others who wander over here, a workaround is to create a custom search engine with some hotkey (eg `f`) that uses the "search engine" `javascript:`

![settings_-_search_engines](https://cloud.githubusercontent.com/assets/17980/10372077/16901130-6d9b-11e5-994f-cda1cfdbef3e.png)

When some tab steals your focus, you can get out of it by hitting the location bar focusing (⌘-l on macs) and then `f` and enter.

A proper configurable shortcut for this is obviously preferable.

**Comment by smblott-github** [comment]
Cool, @hjdivad.  That seems to work.  Perhaps this should go in the wiki?

**Comment by rrsahuone** [comment]
Actually when you are working yourself, you cannot be sure on authenticity of merchant. We get you record for most reliable movers and packers in Bangalore . 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by rrsahuone** [comment]
All are certified and 100 % safe to perform with. We evaluate suppliers depending on different parameters like reviews, Company profile, their popularity and individual discussion with existing or previous customers. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers in Delhi">Packers and Movers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by rrsahuone** [comment]
These all factors create us sure that we are providing you 100 % safe cope that you can believe in any moment.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers in Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a>

**Comment by rrsahuone** [comment]
Packers and movers in Bangalore not only help you in shifting house but providing you a smooth platform on which life goes simple and shifting procedure can be maintained wisely. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by halbtuerke** [comment]
@hjdivad Thanks for the hint, this works really well. :+1:
